### ISSUE TITLE
Granting specific file access to specific conversations / conversation folders

### ISSUE THREAD

**Issue by eschindev** [microsoft/vscode-copilot-release#100]
Following up on [this issue](https://github.com/microsoft/vscode-copilot-release/issues/99), it would be great to assign access to project files or directories to conversation folders or individual conversations. This would allow users to make a set of files visible to a conversation, or any conversations saved within a given conversation folder, such that ChatGPT can reference all available code when evaluating a request in that conversation, and respond more appropriately.

**Comment by roblourens** [comment]
The `@workspace` chat agent has access to other files in your workspace, and giving the user more control over context will continue to be a focus in January
