### ISSUE TITLE
Inline chat crops out full response when asked a question that required detailed answer.

### ISSUE THREAD

**Issue by theReynald** [microsoft/vscode-copilot-release#1001]
**Description of bug**

Inline chat crops out full answer when asked a question that required detailed answer.

![Screenshot 2024-03-04 at 2 42 21 PM](https://github.com/microsoft/vscode-copilot-release/assets/100732140/ac5d61f4-587e-4938-8313-cffee511aa9b)

With a long response, clicking the carrot (^) doesn't reveal full response when clicked.

If 'view in chat' is clicked, the full response is revealed. Only one and part of two is displayed. Not three unless viewed in chat panel.

- VS Code Version: 1.88.0-insider
- OS Version: Somona 14.3.1
- Logs:

**Steps to Reproduce:**

1. Highlight 3 lines of code similar to the image
2. Start inline chat
3. Ask it to "explain the difference between these 3 lines"

**Expected behavior:** 
The complete response is shown when the carrot is clicked

**Impact on user/customer/partner:** 
Confusion. The user may think there's not more to the response when there is. 

**Desired outcome/Solution:**
If the user must click 'View in Chat' to see the remainder of the response, then there should be an ellipsis instead of a carrot that collapses/uncollapses the screen. 

OR, the carrot should reveal the remaining response.

**Comment by jrieken** [comment]
Great timing. I removed the expand/collapse logic yesterday, with todays insiders the content will scroll allowing you to see the whole reply

**Comment by theReynald** [comment]
[like]  Reynald Adolphe reacted to your message:
________________________________
