### ISSUE TITLE
Using @workspace /new with a command that uses a dot makes chat go unstable

### ISSUE THREAD

**Issue by robconery** [microsoft/vscode-copilot-release#1003]
- VS Code Version:  1.88 March 2024
- OS Version: Mac OS Sonoma 14.2.1
- Logs: https://www.dropbox.com/scl/fi/ks2wqbp75d6gllts48u7m/20240305T144653.zip?rlkey=475t0x7xhsjqkazbvioivmffb&dl=0

Steps to Reproduce:

1. Open up any project directory with code in it (Node, .NET, etc)
2. Open up a chat window and type `@workspace /new .gitignore`

The chat window goes "unstable", repeating various messages and some with a complete loss of formatting:

<img width="368" alt="screenshot_658" src="https://github.com/microsoft/vscode-copilot-release/assets/78586/2e9808b9-8dc1-4421-9d25-77aa10dac6b2">

I confirmed this with 2 separate colleagues (Jon Galloway, on Windows and Aaron Wislang, Mac).

**Comment by KonradGC** [comment]
I get the same behaviour but atleast for me it isnt due to a dot in the question. It happens also without a dot here. This causes also very fast the rate exceeded limit message. Its really frustrating.

**Comment by bhavyaus** [comment]
Fixed in latest stable release.
