### ISSUE TITLE
Cannot use chat

### ISSUE THREAD

**Issue by phatd0nut** [microsoft/vscode-copilot-release#1004]
Type: <b>Bug</b>

I restarted my PC from an earlier restoration point because my touchpad stopped working. Now when I open VSC my gGitHub Copilot chat is not working, I cannot write it anything. I have tried to delete the cache folder to no success and also sync my settings with GitHub, but I dont know if that went through because I still cant use the chat, also dont think the settings updated.

Extension version: 0.13.0
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:41:44.469Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (6.68GB free)|
|Process Argv|C:\\Users\\enorz\\Documents\\IMWT\\VT24\\1ME333 - Interaktionsdesign 3\\U2 --crash-reporter-id 97b17d21-b9cb-4e11-b7f0-c274f86bbbff|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
d34g3935:30971562
fegfb526:30973843
bg6jg535:30979843
78248357:30976999
dsvsc020:30976470

```

</details>

**Comment by phatd0nut** [comment]
I managed to copy old settings from the sync log manually FYI

**Comment by Maxim-Mazurok** [comment]
Same, my company got a business trial license and now the chat is gone. Was there before on my personal preview license

Version: 1.88.0-insider (user setup)
Commit: d73fa8b14a6c873958d00a7d7ad13fcb540a052c
Date: 2024-03-05T05:47:29.930Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by aiday-mar** [comment]
hi @roblourens @lramos15  just wanted to ask if you know who I could route this to?

**Comment by ttongabs** [comment]
Same on VS20222 17.9.2

**Comment by Siriletyoucry** [comment]
same on VS Code Insiders 1.88.0

**Comment by Maxim-Mazurok** [comment]
Got it back, also received email "[GitHub] You have been granted access to Copilot Chat in the IDE"

Version: 1.88.0-insider (user setup)
Commit: ea142b5ccdcb797b1de6b1a46fecbf25dea2e229
Date: 2024-03-06T05:47:45.312Z
Electron: 28.2.5
ElectronBuildId: 27336930
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by phatd0nut** [comment]
> Got it back, also received email "[GitHub] You have been granted access to Copilot Chat in the IDE"
> 
> Version: 1.88.0-insider (user setup) Commit: ea142b5ccdcb797b1de6b1a46fecbf25dea2e229 Date: 2024-03-06T05:47:45.312Z Electron: 28.2.5 ElectronBuildId: 27336930 Chromium: 120.0.6099.291 Node.js: 18.18.2 V8: 12.0.267.19-electron.0 OS: Windows_NT x64 10.0.22631

Did you do anything to get it back?

**Comment by phatd0nut** [comment]
Still cannot send any message to the chat

**Comment by phatd0nut** [comment]
I got this when clicking "Send Chat Feedback"

command 'github.copilot.interactiveSession.feedback' not found

**Comment by Maxim-Mazurok** [comment]
No sorry, my issue was different, I didn't have chat window/button at all, likely due to the license change

**Comment by Design-01** [comment]
I have the same issue, Copilot Chat window is blank, it will not launch in a separate window either. It was playing up before it completely went blank. Previously it accepted one comment, it would respond, then after that I'd get nothing. Now it is just completely blank and non responsive. Any ideas? 

Just a thought I have copilot on my windows machine now as part of the windows update. I'm not sure if this has anything to do with it .

**Comment by roblourens** [comment]
Please make sure you have the latest version of VS Code and the Copilot Chat extension installed. If so, please share the log from the Copilot Chat channel

**Comment by sherwyn33** [comment]
Might be resolved now. Had a similar issue with VS code version 1.87.2 
Did a vs code user install for the previous version 1.86.2 and that fixed it. Seems like a missing file in the new version
https://update.code.visualstudio.com/1.86.2/win32-x64-user/stable

**Comment by phatd0nut** [comment]
Sorry for the late response, I forgot to reply here.

I fixed it with a clean reinstall of the IDE and all my extensions. After my recovery from last saved point on Winodws it messed with either the IDE or extensions.
