### ISSUE TITLE
[from zendesk] two reports of VSCode Chat hanging if the ms-python extension is out of date

### ISSUE THREAD

**Issue by jeffreyhunter77** [microsoft/vscode-copilot-release#1005]
The follow was raised as a support escalation for Copilot (original issue is https://github.com/github/copilot/issues/9092):

## Why are you seeing this issue?
This is a [support escalation](https://github.com/github/support/blob/main/docs/escalation-processes.md)! You can find out more about expectations on communications and response times in the [on-call docs](https://thehub.github.com/epd/engineering/incident-response/support-to-engineering-escalation-process/#support-escalation-response-procedures-and-best-practices). Thank you for doing your part to keep GitHub customers happy!

## Severity
_Note, for Sev1 issues always page the team first, using the PagerDuty information in the [service catalog](https://catalog.githubapp.com/services) and the command `.pager trigger copilot-foundations-ep <reason>`. Opening an issue for a Sev2 incident can come later (and can be done by the available Escalation Engineer)._

- [ ] sev1 - **Engineering must _respond_, when paged, within 10 minutes**
- [x] sev2 - **Engineering must _respond_ to this issue within 1 business day**
- [ ] sev3 - **EPD squad for the team must _respond_ to this issue within 2 business days**

## Service
[copilot](https://catalog.githubapp.com/services?service=copilot)

## Issue

Was able to repro by downgrading the Python extension in VSCode to 2021.12.... 

![Image](https://github.com/microsoft/vscode-copilot-release/assets/33921/7f50b925-efa0-4b84-b819-35e30144a9a7)

Updating the Python extension fixes it, but does Chat need to fall down over an old python extension? 

Second ticket has `ms-python.python-2022.18.2`

**Customer Impact**

- Include information about customer impact, including which key/strategic customers are impacted.
- Include org/repo/user information for this issue where possible.
- Link to Zendesk Ticket(s)
[ZD_2652733_](https://github.zendesk.com/agent/tickets/2652733)
[ZD_2650856_](https://github.zendesk.com/agent/tickets/2650856)

**GitHub Product(s) Impacted (check appropriate boxes and provide GHES version if applicable)**

- [ ] GitHub.com (including GHEC)
- [ ] GitHub Enterprise Server.
      If GHES, please list the version of GHES the customer is on here:
- [ ] Proxima (ghe.com)
      If Proxima, please list the customer tenant:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by roblourens** [comment]
Back then, the Python extension patched `replaceAll` with a non-compliant monkeypatch: https://github.com/microsoft/vscode-python/issues/18871#issuecomment-1404038609

This would break any extension that tries to use `replaceAll`. I don't think Copilot Chat should do anything to work around this- looks like it's been fixed in the Python extension for a very long time, and users shouldn't use years-old extensions.
