### ISSUE TITLE
[FR] Command to open the chat history

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-copilot-release#1008]
Currently, there's no command to open the chat history popup:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28700378/4c92e933-349c-43ec-b831-8f6e0963bf6a)
We'd have to open the chat sidebar, then click the show chats icon to open it:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28700378/9041cb0c-0422-401d-8e00-1b81563dca92)
Which is inefficient, please add this command.

**Comment by roblourens** [comment]
Good point, I'll show that command in the command palette
