### ISSUE TITLE
[FR] Command to open the last chat editor

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-copilot-release#1009]
Currently, every time when using the `workbench.action.chat.openInEditor` command, a new chat editor is opened, will be great to have a command that opens the last chat editor.

**Comment by roblourens** [comment]
What does this mean exactly, it switches to a chat editor tab that is already open?

**Comment by wenfangdu** [comment]
@roblourens To open the last created chat, instead of opening a new chat.

**Comment by roblourens** [comment]
I can't think of any other commands that are essentially "open the last opened editor of type X", that's a bit weird to me

**Comment by wenfangdu** [comment]
@roblourens Fine, I'll use `ctrl+tab` for now.
