### ISSUE TITLE
Answers should be aware of the Editor/IDE where GitHub Copilot is running

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-copilot-release#101]
Answers provided by GitHub Copilot should be limited / directed to the current Editor/IDE, to avoid unsupported operations.

For instance, I was developing a basic C# command line app in Visual Studio Code, and Copilot Chat explained a _missing import_ in my source code with this:

> The error message "The name 'JsonConvert' does not exist in the current context" means that the compiler cannot find the JsonConvert class. This class is part of the Newtonsoft.Json NuGet package, which is a popular package for working with JSON in .NET.

> To fix this error, you need to add a reference to the Newtonsoft.Json NuGet package. You can do this by following these steps:

> 1. Right-click on your project in the Solution Explorer and select "Manage NuGet Packages".
> 2. In the "Browse" tab, search for "Newtonsoft.Json".
> 3. Click on the "Install" button to install the package.

> Once you have installed the package, you should be able to use the JsonConvert class in your code without any issues.

Everything is perfect, except that these are steps are expected to work on Visual Studio, not Visual Studio Code, which still relies on command line for this. So, I think that GitHub Copilot should take this in consideration when providing answers.

BTW, I promptly asked how to add the package using command line, and GitHub Copilot gave me the perfect solution.

> You can add a NuGet package to your project using the command line by using the dotnet command. Here are the steps:
> 1. Open a command prompt or terminal window.
> 2. Navigate to the directory that contains your project file (.csproj file).
> 3. Run the following command to add the package:
> `dotnet add package <package-name> `
> Replace <package-name> with the name of the package you want to install.
> 4. Press Enter to run the command.

Thank you

**Comment by lramos15** [comment]
Should be fixed now 
<img width="315" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/8f088eec-156a-46f1-9505-a16d84c2042c">
