### ISSUE TITLE
[FR] Command to send message, and Command to enter new line

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-copilot-release#1010]
Background: some users prefer using `Cmd+Enter` to send message, and `Enter` to enter new line, most chat apps support this setting. Would be nice if copilot chat supports it as well.

Currently, `Enter` is bound to send message, and `Shift+Enter` is bound to enter new line, and they are unconfigurable. I suggest adding two commands to send message and enter new line, so that users can bind the shortcuts themselves, for backwards compatibility, `Enter` is bound to the send message command, and `Shift+Enter` is bound to the enter new line command.

Another thing is that `Enter` is so easily mistyped, oftentimes the question is not finished or contains typos, but I typed `Enter` out of habit, would have to restart the conversation again. In this case, `Cmd+Enter` is a better shortcut for me.

**Comment by jrieken** [comment]
For this you can change the keybinding for the `workbench.action.chat.submit` from `Enter` to `Cmd+Enter`
