### ISSUE TITLE
Wierd behaviour on my specific question

### ISSUE THREAD

**Issue by FaizanAhmad127** [microsoft/vscode-copilot-release#1014]
I had a problem with file uploading on Flutter Web. And I asked the copilot the following question:

I am getting an error on uploading a file in web but uploading on android is fine. The error is: Unsupported operation: _Namespace

The response was the following:
Please check your firewall rules and network connection then try again. Error Code: ERR_HTTP2_STREAM_ERROR.

I thought something happened to my internet but then I asked multiple different questions and copilot gave me a normal answer to that. Then I again asked the same question:
I am getting an error on uploading a file in web but uploading on android is fine. The error is: Unsupported operation: _Namespace

And the response was something new:

<p><strong>No server is currently available to service your request.</strong></p>
<p>Sorry about that. Please try refreshing and contact us if the problem persists.</p>
<div id="suggestions">
<a href="https://github.com/contact">Contact Support</a> &mdash;
<a href="https://www.githubstatus.com">GitHub Status</a> &mdash;
<a href="https://twitter.com/githubstatus">@githubstatus</a>
</div>

**Comment by eina84** [comment]
I am getting the same error when asking code questions in VS Code. Just started happening today multiple times.

**Comment by testcas** [comment]
I am also getting the same error and restarting is not really helping (VS Code or my laptop).

**Comment by Jackywu87** [comment]
I have the same problem.

**Comment by mucaoshen** [comment]
same problem +1

**Comment by sleekyom** [comment]
I have the same issue too

**Comment by sophietotterstrom** [comment]
Same error for me, restarting does not fix it

**Comment by VanicekTomas** [comment]
Same error for me

**Comment by rogue-wild** [comment]
same issue. 
![image](https://github.com/microsoft/vscode-copilot-release/assets/42809447/102ba2d7-cf42-46bb-9732-e1e72e76d6e8)

**Comment by Bergbok** [comment]
+1

**Comment by DiD-BDX** [comment]
same +1

**Comment by olsn** [comment]
Same, +1

**Comment by caendesilva** [comment]
Having issues in both PhpStorm (even after updating to the latest plugin version) and in VS Code.

    Error on ghost text request: FetchError: Stream closed with error code NGHTTP2_REFUSED_STREAM

**Comment by RasmusGodske** [comment]
Same, +1

**Comment by beingkk** [comment]
+1

**Comment by amnezziaa** [comment]
+1

**Comment by cd-slash** [comment]
+1, still occurring, reload window or restart fixes briefly but recurs again very quickly (~ 1 minute)

**Comment by weber8thomas** [comment]
+1

**Comment by caendesilva** [comment]
@mucaoshen, @sleekyom, @zeng407, @imDanSable, @VanicekTomas, @Bergbok, @DiD-BDX, @olsn, @RasmusGodske, @amnezziaa, @weber8thomas, and @matgayno:

Please don't comment with just "+1" or "same". Unless you can provide any new information, it's not helpful and just clutters the discussion, what's worse: you send spam emails to all the participants.

Instead, if you only wish to mark that you are experiencing the same issue, please use the thumbs up button on the original thread!

**Comment by lramos15** [comment]
There was a service incident on the servers which process our LLM requests, please indicate if you're still experiencing this issue and I will reopen the issue. Apologies for the interruption. Thanks!
