### ISSUE TITLE
copilot crashing vscode

### ISSUE THREAD

**Issue by ValdirGiorgi** [microsoft/vscode-copilot-release#1016]
Type: <b>Bug</b>

whenever I ask a question in the copilot chat, vscode crashes on the second question and other vscode features crash, I have already disabled all extensions, leaving only copilot, the same still happens.

Extension version: 0.13.0
VS Code version: Code 1.87.1 (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:21:36.258Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.69GB free)|
|Process Argv|--crash-reporter-id cabc3e0b-8dec-45ff-afbd-0771c4e364e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30958158
dsvsc020:30976470

```

</details>

**Comment by TylerLeonhardt** [comment]
Can you tell me what you're seeing when you say crashing? Ideally with a gif/screenshot. Is it crashing the VS Code process? Is it crashing just the extension host where extensions run? Can you provide the contents of the `window` Output Channel:
<img width="795" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/2644648/51a34d91-015a-462c-8bc1-cd9b5d66beae">

**Comment by ValdirGiorgi** [comment]
closing

**Comment by ValdirGiorgi** [comment]
The window freezes and no log was obtained, but after the last update it is no longer happening. We can close, thank you.
