### ISSUE TITLE
@workspace /new giving weird responses

### ISSUE THREAD

**Issue by Parul-mahajan** [microsoft/vscode-copilot-release#1020]
- VS Code Version: 1.87.1
- OS Version:Windows_NT x64 10.0.22631
- Logs:

Steps to Reproduce:

1. I created the prompt to create a website to show features of github copilot but it shows multiple responses and shows following error in logs `[CodeOrDocsSearchClient] [repo:] Error fetching code search. Retrying in 5 seconds. Query: ```html` 
![image](https://github.com/microsoft/vscode-copilot-release/assets/64400938/ab5b903d-3dd1-4f2b-920d-2e3e606f717a)
![image](https://github.com/microsoft/vscode-copilot-release/assets/64400938/dda5b8e4-0441-40eb-ab0c-d5bd1aa535e4)

and if it does create workspace it's showing no code or either the workspace doesn't get created just creates empty folder with partial code.

**Comment by KonradGC** [comment]
Iam also getting a problem while creating with the /new command something. The chat is producing the same answer more than 50times if i ask him to create me something. And as soon as he finishes it, i will get 50 times the same output with nearly zero content in the files.. if iam tryin to work this way i get the rate exceeded limit message pretty fast and i get blocked for the rest of the day from using the chat. 

PLEASE PLEASE Fix this cause its nearly unusable this way or just tell me what iam doing wrong.. i really rely this week on the power of the copilot chat :)

**Comment by Parul-mahajan** [comment]
Hi is there a work around this problem, I have a customer demo and I need to show this feature

**Comment by bhavyaus** [comment]
@Parul-mahajan you can get the fix on a newer version of the extension.

**Comment by Parul-mahajan** [comment]
Hey @bhavyaus I have tried both release and pre-release version this is still not working out for me, either it's showing output in loop or repository doesn't get created.

**Comment by bhavyaus** [comment]
@Parul-mahajan could you please share the pre-release version? I'm unable to reproduce this issue on the latest insiders with latest pre-release extension.
