### ISSUE TITLE
Copilot Vision in VS Code

### ISSUE THREAD

**Issue by Helder-Machava** [microsoft/vscode-copilot-release#1024]
The recent advancements in AI have been remarkable. I've been thinking, it would be amazing if VS Code could eventually have a feature where a programmer inputs a layout image, and Copilot generates code to build that layout or element.

**Comment by justschen** [comment]
closing this in favor for https://github.com/microsoft/vscode-copilot-release/issues/554. if interested, we now have [this "Vision for Copilot Preview" extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-copilot-vision) as well which is a "bring your own key" model
