### ISSUE TITLE
Feature Request: Control over reference lookup from open editors

### ISSUE THREAD

**Issue by shimonsalamon** [microsoft/vscode-copilot-release#1026]
I've been using GitHub Copilot and it's been a great help in my development process. However, I've noticed that Copilot uses the context of the currently open file to generate suggestions, even when the conversation is not related to the open file. This sometimes leads to less accurate responses.

I'd like to suggest a feature that would give users more control over this behavior. It would be helpful to have a checkbox or some form of control in the settings to toggle whether Copilot should look up references from open editors. This way, users can choose to limit the context to the conversation when the open file is not relevant.

I believe this feature would enhance the user experience by providing more accurate suggestions based on the user's preference.

Thank you for considering my suggestion.

**Comment by roblourens** [comment]
Thanks for this suggestion! It's a great idea, in fact it's exactly what we are working on this month. Follow https://github.com/microsoft/vscode-copilot-release/issues/675, hope you try it out once we have something working in Insiders.
