### ISSUE TITLE
Responsible AI Service is way to sensitive

### ISSUE THREAD

**Issue by Kireobat** [microsoft/vscode-copilot-release#1029]
### Responsible AI Service is way to sensitive.

I was working with an Arduino and making some code for it. I asked copilot this question:
```
Can you write an explanation for the following connections on my D1 mini please:

TX, RX, 5 SCL, 4 SDA, 0, 2, GND, VBUS, RST, AO, 16, SCK 14, MISO 12, MCSI 13, SS 15, 3V3
```

Which may seem totaly innocent at first glance, but Responsible AI Services was smart enough to see that I had "**SS**" in the request meaning that I was up to no good and probably a nazi. Responsible AI Services did the right thing and blocked my horrible and dangerous request.

I eventually figured that the "**SS**"  might be the problem so I asked this instead:

```
Can you write an explanation for the following connections on my D1 mini please:

TX, RX, 5 SCL, 4 SDA, 0, 2, GND, VBUS, RST, AO, 16, SCK 14, MISO 12, MCSI 13, 15, 3V3
```

And this was accepted. I hope that whoever is responsible for Responsible AI Services can adjust their regex pattern so that you don't get flagged for merely including "**SS**"  in a question.

Thanks for reading

**Comment by SigismondPhilippe** [comment]
That "responsible AI service" is just some stakeholders at github trying to exist. It is a very good argument to try other, better tuned, ai copilot.

**Comment by thispaul** [comment]
@Kireobat i'm having trouble reproducing this issue. when i use the same prompt, i get a response back from copilot chat in vs code. are you still having this problem with the same prompt?

thank you



![Image](https://github.com/microsoft/vscode-copilot-release/assets/90000203/b7a0fd39-4423-46cd-98a9-962b453a0366)

**Comment by lramos15** [comment]
@thispaul I just started a new chat and copy and pasted that prompt
<img width="845" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/ff710cb7-38d1-4c3e-b73c-181144199955">

**Comment by Kireobat** [comment]
I still have the issue when including the "SS"
![image](https://github.com/microsoft/vscode-copilot-release/assets/89387628/9df22dd4-0896-44e0-be81-cadb29ecbb46)

**Comment by thispaul** [comment]
Thanks @Kireobat we are troubleshooting this with the RAI team

**Comment by GGLionCross** [comment]
I can confirm that my prompt "Please put the elapsed time in hh:mm:ss format" was also flagged.

**Comment by ced-mos** [comment]
I have the same issue but for another prompt. However, I haven't found the reason why. Especially as I entered a prompt in German, where I haven't anything special.

Therefore, is there the possibility to get the reason, why the information was filtered, to troubleshoot the process myself?

**Comment by Simsalaba** [comment]
flagging double "s" is ridiculous. Mine got flagged for "killTask" which is a function in a library.

**Comment by sspage** [comment]
+1 - trying to have it evaulate any JSON is a nightmare given the random characters that might hurt its feelings... makes it unusable.

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
