### ISSUE TITLE
Copilot is not responding

### ISSUE THREAD

**Issue by DanielvNiek** [microsoft/vscode-copilot-release#1032]
Type: <b>Performance Issue</b>

I have restarted vscode, used another internet network, restarted my laptop and still copilot is not responding. I also tried some other ai coding extensions which also use the internet to get code suggestions and they all work fine.
Error on ghost text request: FetchError: The pending stream has been canceled (caused by: Client network socket disconnected before secure TLS connection was established)
    at fetch (/root/.vscode-server/extensions/github.copilot-1.172.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/root/.vscode-server/extensions/github.copilot-1.172.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Wj.fetch (/root/.vscode-server/extensions/github.copilot-1.172.0/lib/src/network/helix.ts:78:22)
    at aN.fetchWithParameters (/root/.vscode-server/extensions/github.copilot-1.172.0/lib/src/openai/fetch.ts:429:26)
    at aN.fetchAndStreamCompletions (/root/.vscode-server/extensions/github.copilot-1.172.0/lib/src/openai/fetch.ts:322:26)
    at genericGetCompletionsFromNetwork (/root/.vscode-server/extensions/github.copilot-1.172.0/lib/src/ghostText/ghostText.ts:150:21)
    at getGhostText (/root/.vscode-server/extensions/github.copilot-1.172.0/lib/src/ghostText/ghostText.ts:699:23)
    at calculateInlineCompletions (/root/.vscode-server/extensions/github.copilot-1.172.0/extension/src/ghostText/ghostText.ts:167:20)
    at provideInlineCompletions (/root/.vscode-server/extensions/github.copilot-1.172.0/extension/src/ghostText/ghostText.ts:285:18)
    at jR.provideInlineCompletionItems (/root/.vscode-server/extensions/github.copilot-1.172.0/extension/src/ghostText/ghostText.ts:313:27)
    at K.provideInlineCompletions (/root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/out/vs/workbench/api/node/extensionHostProcess.js:143:56159) {
  type: 'system',
  _name: 'FetchError',
  code: 'ERR_HTTP2_STREAM_CANCEL',
  errno: undefined,
  erroredSysCall: undefined,
  vslsStack: [
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {},
    CallSite {}, CallSite {}
  ]
}

Extension version: 0.11.1
VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 23.0.0
Modes:
Remote OS version: Linux arm64 6.6.12-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 1adeb76d-7722-4810-8c99-276b4b5f31fc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Container danielvniek/alis-code-arm (alis-vscode-server) @ desktop-linux|
|OS|Linux arm64 6.6.12-linuxkit|
|CPUs|unknown (10 x 0)|
|Memory (System)|15.60GB (13.44GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   11	   213	   904	code main
   11	    82	   912	   gpu-process
    2	    33	   913	   utility-network-service
   35	   442	   921	window [1] (iam.proto — alis-os-services-iam-v1 (Workspace) [Container danielvniek/alis-code-arm (alis-vscode-server) @ desktop-linux])
   13	    82	   991	shared-process
    0	     0	  1620	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    4	    98	  1541	extensionHost [1]
    0	    33	  1565	     docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=6ed5a033-7cf3-4f5e-96fd-c6f60fc00bf31710417204520 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /bin/sh
    0	    16	  1566	       /Applications/Docker.app/Contents/Resources/bin/com.docker.cli exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=6ed5a033-7cf3-4f5e-96fd-c6f60fc00bf31710417204520 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /bin/sh
    0	    33	  1577	     docker exec -i -u root 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /bin/sh
    0	    16	  1578	       /Applications/Docker.app/Contents/Resources/bin/com.docker.cli exec -i -u root 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /bin/sh
    0	    33	  1582	     docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=6ed5a033-7cf3-4f5e-96fd-c6f60fc00bf31710417204520 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node -e \012\011\011\011\011const net = require('net');\012\011\011\011\011const fs = require('fs');\012\011\011\011\011process.stdin.pause();\012\011\011\011\011const client = net.createConnection({ host: '127.0.0.1', port: 55203 }, () => {\012\011\011\011\011\011console.error('Connection established');\012\011\011\011\011\011client.pipe(process.stdout);\012\011\011\011\011\011process.stdin.pipe(client);\012\011\011\011\011});\012\011\011\011\011client.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote close with error' : 'Remote close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011client.on('error', function (err) {\012\011\011\011\011\011process.stderr.write(err && (err.stack || err.message) || String(err));\012\011\011\011\011});\012\011\011\011\011process.stdin.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote stdin close with error' : 'Remote stdin close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011process.on('uncaughtException', function (err) {\012\011\011\011\011\011fs.writeSync(process.stderr.fd, `Uncaught Exception: ${String(err && (err.stack || err.message) || err)}\n`);\012\011\011\011\011});\012\011\011\011
    2	    16	  1586	       /Applications/Docker.app/Contents/Resources/bin/com.docker.cli exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=6ed5a033-7cf3-4f5e-96fd-c6f60fc00bf31710417204520 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node -e \012\011\011\011\011const net = require('net');\012\011\011\011\011const fs = require('fs');\012\011\011\011\011process.stdin.pause();\012\011\011\011\011const client = net.createConnection({ host: '127.0.0.1', port: 55203 }, () => {\012\011\011\011\011\011console.error('Connection established');\012\011\011\011\011\011client.pipe(process.stdout);\012\011\011\011\011\011process.stdin.pipe(client);\012\011\011\011\011});\012\011\011\011\011client.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote close with error' : 'Remote close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011client.on('error', function (err) {\012\011\011\011\011\011process.stderr.write(err && (err.stack || err.message) || String(err));\012\011\011\011\011});\012\011\011\011\011process.stdin.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote stdin close with error' : 'Remote stdin close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011process.on('uncaughtException', function (err) {\012\011\011\011\011\011fs.writeSync(process.stderr.fd, `Uncaught Exception: ${String(err && (err.stack || err.message) || err)}\n`);\012\011\011\011\011});\012\011\011\011
    0	    33	  1587	     docker exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=6ed5a033-7cf3-4f5e-96fd-c6f60fc00bf31710417204520 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node -e \012\011\011\011\011const net = require('net');\012\011\011\011\011const fs = require('fs');\012\011\011\011\011process.stdin.pause();\012\011\011\011\011const client = net.createConnection({ host: '127.0.0.1', port: 55203 }, () => {\012\011\011\011\011\011console.error('Connection established');\012\011\011\011\011\011client.pipe(process.stdout);\012\011\011\011\011\011process.stdin.pipe(client);\012\011\011\011\011});\012\011\011\011\011client.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote close with error' : 'Remote close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011client.on('error', function (err) {\012\011\011\011\011\011process.stderr.write(err && (err.stack || err.message) || String(err));\012\011\011\011\011});\012\011\011\011\011process.stdin.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote stdin close with error' : 'Remote stdin close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011process.on('uncaughtException', function (err) {\012\011\011\011\011\011fs.writeSync(process.stderr.fd, `Uncaught Exception: ${String(err && (err.stack || err.message) || err)}\n`);\012\011\011\011\011});\012\011\011\011
    0	    16	  1588	       /Applications/Docker.app/Contents/Resources/bin/com.docker.cli exec -i -u root -e VSCODE_REMOTE_CONTAINERS_SESSION=6ed5a033-7cf3-4f5e-96fd-c6f60fc00bf31710417204520 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /root/.vscode-server/bin/8b3775030ed1a69b13e4f4c628c612102e30a681/node -e \012\011\011\011\011const net = require('net');\012\011\011\011\011const fs = require('fs');\012\011\011\011\011process.stdin.pause();\012\011\011\011\011const client = net.createConnection({ host: '127.0.0.1', port: 55203 }, () => {\012\011\011\011\011\011console.error('Connection established');\012\011\011\011\011\011client.pipe(process.stdout);\012\011\011\011\011\011process.stdin.pipe(client);\012\011\011\011\011});\012\011\011\011\011client.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote close with error' : 'Remote close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011client.on('error', function (err) {\012\011\011\011\011\011process.stderr.write(err && (err.stack || err.message) || String(err));\012\011\011\011\011});\012\011\011\011\011process.stdin.on('close', function (hadError) {\012\011\011\011\011\011console.error(hadError ? 'Remote stdin close with error' : 'Remote stdin close');\012\011\011\011\011\011process.exit(hadError ? 1 : 0);\012\011\011\011\011});\012\011\011\011\011process.on('uncaughtException', function (err) {\012\011\011\011\011\011fs.writeSync(process.stderr.fd, `Uncaught Exception: ${String(err && (err.stack || err.message) || err)}\n`);\012\011\011\011\011});\012\011\011\011
    0	    33	  1613	     electron-nodejs (settings.js settings.js )
    0	    16	  1616	       electron-nodejs (settings.js settings.js )
    0	    33	  1614	     docker exec -i -u root -w /root/.vscode-server/extensions 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /bin/sh -c # Watch installed extensions\012\011\011\011trap "exit 0" 15\012\011\011\011old=`ls -A --full-time`\012\011\011\011counter=0\012\011\011\011while [ $counter -lt 60 ]\012\011\011\011do\012\011\011\011\011sleep 1\012\011\011\011\011new=`ls -A --full-time`\012\011\011\011\011if [ "$new" != "$old" ]\012\011\011\011\011then\012\011\011\011\011\011exit 1\012\011\011\011\011fi\012\011\011\011\011counter=`expr $counter + 1`\012\011\011\011done\012\011\011\011exit 2\012\011\011
    0	    16	  1615	       /Applications/Docker.app/Contents/Resources/bin/com.docker.cli exec -i -u root -w /root/.vscode-server/extensions 9a718bfaf826c854e59e65872789c64a1423262de834abb0701fc18a682b5dd8 /bin/sh -c # Watch installed extensions\012\011\011\011trap "exit 0" 15\012\011\011\011old=`ls -A --full-time`\012\011\011\011counter=0\012\011\011\011while [ $counter -lt 60 ]\012\011\011\011do\012\011\011\011\011sleep 1\012\011\011\011\011new=`ls -A --full-time`\012\011\011\011\011if [ "$new" != "$old" ]\012\011\011\011\011then\012\011\011\011\011\011exit 1\012\011\011\011\011fi\012\011\011\011\011counter=`expr $counter + 1`\012\011\011\011done\012\011\011\011exit 2\012\011\011
    0	    49	  1589	fileWatcher [1]
   30	    98	  1618	window [2] (Issue Reporter)

Remote: Container danielvniek/alis-code-arm (alis-vscode-server) @ desktop-linux
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
bg6jg535:30979843
dsvsc020:30976470
666c4381:30973075
gee8j676:30988843

```

</details>

**Comment by devm33** [comment]
Hello 👋 if you could share the `GitHub Copilot: Collect Diagnostics` output ([docs](https://docs.github.com/en/copilot/troubleshooting-github-copilot/viewing-logs-for-github-copilot-in-your-environment?tool=vscode#viewing-network-connectivity-diagnostics-logs-1)) that can help pin down the issue. We also have some [troubleshooting steps](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot).

**Comment by deepak1556** [comment]
Error is from helix fetcher. Can you also try adding the following setting

```
"github.copilot.advanced": {
        "debug.useElectronFetcher": true
    },
```

Restart vscode and see if the issue persists. The above setting will force a different network stack in the application, I would like to check if it is an issue at client or the OS.

**Comment by deepak1556** [comment]
I also noticed your VS Code version is quite old, can you check with our [latest insiders](https://code.visualstudio.com/insiders) with the above setting

**Comment by cancanu3131** [comment]
> Error is from helix fetcher. Can you also try adding the following setting
> 
> ```
> "github.copilot.advanced": {
>         "debug.useElectronFetcher": true
>     },
> ```
> 
> Restart vscode and see if the issue persists. The above setting will force a different network stack in the application, I would like to check if it is an issue at client or the OS.

where to add that helixfetcher setting

**Comment by devm33** [comment]
> > Error is from helix fetcher. Can you also try adding the following setting
> > ```
> > "github.copilot.advanced": {
> >         "debug.useElectronFetcher": true
> >     },
> > ```
> > Restart vscode and see if the issue persists. The above setting will force a different network stack in the application, I would like to check if it is an issue at client or the OS.
> 
> where to add that helixfetcher setting

To your VS Code settings.json https://code.visualstudio.com/docs/getstarted/settings#_settingsjson

**Comment by chrisk314** [comment]
I'm also encountering a similar error related to the helix fetcher. Output from Copilot when attempting to activate the extension. Interestingly, Copilot Chat does eventually activate successfully and I am able to use the chat window. I can also run prompts directly in my open source files. Auto-complete suggestions, however, are not working at all.
```txt
2024-06-28 10:47:12.151 [error] [auth] The operation was aborted.
2024-06-28 10:47:33.055 [error] [default] Error sending telemetry AbortError: The operation was aborted.
    at fetch (/home/csk/.vscode-server-insiders/extensions/github.copilot-1.208.959/node_modules/@adobe/helix-fetch/src/fetch/index.js:96:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/csk/.vscode-server-insiders/extensions/github.copilot-1.208.959/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at Iq.fetch (/home/csk/.vscode-server-insiders/extensions/github.copilot-1.208.959/lib/src/network/helix.ts:88:22) {
  type: 'aborted',
  _name: 'AbortError'
}
```

I added the copilot advanced config suggested above to use the electron fetcher to my user settings.json file, but this had no effect. Helix fetcher is still used after VS Code restart and system restart.

My OS is Windows 11 with WSL2 Ubuntu 22.04. Copilot is enabled in a WSL Ubuntu 22.04 remote.

GitHub Copilot extension version: v1.208.959 (pre-release)

Info about my VS Code install.

Version: 1.91.0-insider (user setup)
Commit: aea213b7fcc7de5c24ad797ac1af209b159d451f
Date: 2024-06-28T05:56:20.804Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by marko91** [comment]
Same problem as @chrisk314, haven't been able to use Github Copilot for the last ~7 days.

Any solutions / suggestions?

**Comment by devm33** [comment]
@marko91 are you using WSL as well? (The electron-based networking is not available in WSL)

**Comment by marko91** [comment]
@devm33 Yes, using WSL as well. Makes sense, setting useElectronFetcher had no effect.

For me Copilot did work for the trial month, I have since paid for it, but it hasn't been working and my error log is identical to the one from @chrisk314 

I have tried some suggestions that I found online like checked
- that my VS is up to date
- login / logout from my GitHub account in VS
- that my Copilot extensions are up to date
- tried switching to pre-release version of Copilot extensions
- tried installed older versions of Copilot extensions
- that @builtin Github Authentication extension is enabled

**Comment by canuckjacq** [comment]
Looks similar to #1313 maybe?

**Comment by Coding-Rod** [comment]
I got the exact same error using WSL2 and Windows 11, Abort error, Have anyone solved already?

**Comment by FalcorX** [comment]
To resolve the "Error sending telemetry AbortError: The operation was aborted." error when using Windows 11 / WSL2 and Visual Studio Code with the WSL Extension I had to manually set my DNS server in windows. In Network Connections > Properties > Internet Protocol Version 4 > Properties > Use the following DNS server addresses: Primary: 1.1.1.1 Alternate: 8.8.8.8

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-copilot-release/issues/741 as this matches the originally reported error.
