### ISSUE TITLE
Why still Github Copilot can't write directly to code file?!

### ISSUE THREAD

**Issue by suygetsu1256** [microsoft/vscode-copilot-release#1033]
I don't want to be rude but can someone tell me when you developers will add the feature Copilot editing code itself?
Don't you guys get paid because of the developing the chatbot? While there is this beauty feature why still not adding it to chatbot???

The Feature i ask for is:
Lets say there is code file i open in Visual Studio Code that have 400 line of code. 
When i ask for a code fix to Copilot chat he gaves me code but the codes he gave me 2-3 different codes and they are very far from each other and its hard to put NEW added codes because you dont know where to put and its stealing too much time!

Please add feature that Copilot can edit file when i ask for!

**Comment by lramos15** [comment]
Please try inline chat, via `CMD / CTRL + I`. This is our vision for allowing copilot to write directly to the code file
