### ISSUE TITLE
Support File Exclusions

### ISSUE THREAD

**Issue by jwyza-pi** [microsoft/vscode-copilot-release#1036]
Github copilot supports the ability at a repository level to exclude it from functioning on a subset of files.  It would be substantially useful to have copilot chat also support those same exclusions.

**Comment by lramos15** [comment]
Copilot chat now supports the content exclusion feature 
https://docs.github.com/en/copilot/managing-github-copilot-in-your-organization/configuring-content-exclusions-for-github-copilot

**Comment by ced-mos** [comment]
> Copilot chat now supports the content exclusion feature https://docs.github.com/en/copilot/managing-github-copilot-in-your-organization/configuring-content-exclusions-for-github-copilot

I have read the documentation. However I am wondering if there is already the feature planned to exclude files from the copilot chat mode? I ask as this is excluded based on the limitation description from the link you mentioned.
