### ISSUE TITLE
Using copilot to generate commit messages should generate messages in the language being used, not only English

### ISSUE THREAD

**Issue by z505985755** [microsoft/vscode-copilot-release#1039]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.Use copilot to generate commit messages

**Comment by lszomoru** [comment]
Please use the `github.copilot.chat.localeOverride` to control the language being used when generating the commit message.

**Comment by z505985755** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/21410404/5f857c73-3bd1-4e25-8c76-9b8a75d88d7a)
![image](https://github.com/microsoft/vscode-copilot-release/assets/21410404/6ef4e3c4-abfd-4634-ad92-343d321f908d)

However, this is useless,All three tabs have been set up and vscode has been restarted.

**Comment by lszomoru** [comment]
The shared screenshot is the output generated by the `/doc` slash command and not commit message generation. Adding @ulugbekna to confirm that the `/doc` slash command has the ability to generate documentation in languages other than English.

**Comment by ulugbekna** [comment]
> 
The shared screenshot is the output generated by the /doc slash command and not commit message generation. Adding @ulugbekna to confirm that the /doc slash command has the ability to generate documentation in languages other than English.


I believe neither commit message generation nor /doc currently supports other languages? Created an [issue](https://github.com/microsoft/vscode-copilot-release/issues/1072) to track this for /doc.

**Comment by lszomoru** [comment]
Commit message generation does honour the `github.copilot.chat.localeOverride` setting.

**Comment by z505985755** [comment]
> 提交消息生成确实遵循该设置。`github.copilot.chat.localeOverride`

Yes, but it does not take effect when generating documents

**Comment by z505985755** [comment]
> > 共享屏幕截图是由 /doc slash 命令生成的输出，而不是提交消息生成。添加以确认 /doc slash 命令能够以英语以外的语言生成文档。
> 
> 我相信提交消息生成和 /doc 目前都不支持其他语言？为 /doc 创建了一个[跟踪此问题](https://github.com/microsoft/vscode-copilot-release/issues/1072)的问题。
generating commit messages supports other languages, but generating documents does not.

**Comment by z505985755** [comment]
> > 共享屏幕截图是由 /doc slash 命令生成的输出，而不是提交消息生成。添加以确认 /doc slash 命令能够以英语以外的语言生成文档。
> 
> 我相信提交消息生成和 /doc 目前都不支持其他语言？为 /doc 创建了一个[跟踪此问题](https://github.com/microsoft/vscode-copilot-release/issues/1072)的问题。

generating commit messages supports other languages, but generating documents does not.

**Comment by z505985755** [comment]
> > The shared screenshot is the output generated by the /doc slash command and not commit message generation. Adding @ulugbekna to confirm that the /doc slash command has the ability to generate documentation in languages other than English.
> 
> I believe neither commit message generation nor /doc currently supports other languages? Created an [issue](https://github.com/microsoft/vscode-copilot-release/issues/1072) to track this for /doc.

generating commit messages supports other languages, but generating documents does not.
