### ISSUE TITLE
Multiple chat windows

### ISSUE THREAD

**Issue by irmo-de** [microsoft/vscode-copilot-release#104]
Currently, there is only one global chat. It would be great to have some sort of tabs to work on multiple issues.

**Comment by RogerBarreto** [comment]
@irmo-de Using the approach here #60 you can do that.

> Ctrl + Shift + P -> chat: open Editor (github copilot)

You can also make quick questions without opening a new tab or the sidebar. This is especially useful when used with a keybinding:

> Ctrl + Shift + P -> chat: ask quick question


[Comment](https://github.com/microsoft/vscode-copilot-release/issues/60#issuecomment-1558197350)

**Comment by roblourens** [comment]
Good response @RogerBarreto, thanks. Hoping to make the chat editor more discoverable as well.
