### ISSUE TITLE
Need access to the older versions of Copilot Chat

### ISSUE THREAD

**Issue by ethanUSAA** [microsoft/vscode-copilot-release#1044]
Hello, 

My company has a packaging process for each new version of VSCode. 
As it stands we are on an older version of VSCode, 1.86 or 1.87.1 depending on how the packaging rollout is progressing. 

I need access to the final version of Copilot Chat 0.12 and 0.13 so that we can pilot Copilot Chat on these older versions of VSCode. 
On the marketplace page, the only the most current version is available which we are not able to use.

**Comment by roblourens** [comment]
When you an install an extension in vscode, you always get latest version of the extension that is compatible with that version of VS Coe
