### ISSUE TITLE
The "Copy" option in the right-click menu is actually executing "Copy All", instead of copying the selected content.

### ISSUE THREAD

**Issue by mercury233** [microsoft/vscode-copilot-release#1047]
Type: <b>Bug</b>

![GIF 2024-3-16 15-43-09](https://github.com/microsoft/vscode-copilot-release/assets/13391795/5522d14d-cbfa-4b43-bd8e-0dfaa740ba25)

In this gif, I'm trying to select and copy the text "menu" in the copilot answer, but it actually copied the full answer.

Extension version: 0.13.2024022301
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (23.57GB free)|
|Process Argv|F:\\Works\\db-yugioh-card-com\\output\\cfile2.js --crash-reporter-id c6fccd0f-d5a1-4b23-9532-fe36f0b79168|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470
gee8j676:30988843

```

</details>

**Comment by roblourens** [comment]
This option is supposed to copy the full message. "Copy All" copies the full conversation.

https://github.com/microsoft/vscode-copilot-release/issues/416
