### ISSUE TITLE
/explain never works

### ISSUE THREAD

**Issue by bwhitlock71** [microsoft/vscode-copilot-release#1048]
bwhitlock71: /explain

GitHub Copilot: 

Oops, your response got filtered. Vote down if you think this shouldn't have happened.

This happened every time I try /explain and I have tried disabling and enabling copilot and restarting VS Code and I can't seem to get it to work properly. Has anyone else had this issue?

**Comment by Ambmoney** [comment]
I'm having this problem as well. Why? I've tried the available fixes ie. writing prompt differently.

**Comment by lramos15** [comment]
Are you still experiencing this problem. Can you include a screenshot and your logs via `CMD/CTRL + SHIFT + U` -> `Copilot Chat`. Thanks!
