### ISSUE TITLE
Corresponding line numbers for code corrections/replacement.

### ISSUE THREAD

**Issue by wesbob** [microsoft/vscode-copilot-release#105]
As of now, when I use Copilot to help fix a coding error, it provides the corrected code. However, it would be even more efficient and beneficial if Copilot could also indicate the specific line numbers in my current file where the corrected code should be replaced.

**Comment by jc-noel** [comment]
Great idea! In a large file it can be challenging to see which line is being corrected or changed. I wonder if this is just a prompt change or toggle to add it?

**Comment by wesbob** [comment]
I'm not sure at the moment, but I did try to prompt to add the line numbers in which to replace. While it did output some line numbers, it just wasn't in correspondence with the error I gave it in the beginning. If I find a toggle or better prompt I will update!

**Comment by originlake** [comment]
I think it's better to only propose the changes but not apply them directly. Users can choose to apply the changes by clicking some buttons. In my case, the fixes are not always correct and then I have to revert them or sometimes only need to cherry-pick a couple of lines.

**Comment by gamousquesORT** [comment]
I agree, I frequently use the inline chat to ask copilot to replace several lines of code, and it is hard to see what it is going to change.  In the screenshot it says changed 5 lines but I don't see which ones.

![change several lines of code](https://github.com/microsoft/vscode-copilot-release/assets/27827078/12003ad3-5083-4207-9682-289ead9c8087)

**Comment by roblourens** [comment]
Inline chat has improved a lot and is what we recommend for working with code in an editor
