### ISSUE TITLE
Better chat management for CoPilot

### ISSUE THREAD

**Issue by hopk8** [microsoft/vscode-copilot-release#1052]
Please add chat management functionality. As a new user to GitHub CoPilot I find the management of chat(s) confusing and completely unnavigable. Please add functionality to easily name chats, see a list of chats by name, and select and open chats. Currently, my chat history has been wiped clear and I seemingly have no way to retrieve my chat history. I did not initiate this, but discovered it upon login, whereas my chat history was there just a day prior. Please also add functionality to easily save and export chats for later use so information is not lost.

**Comment by roblourens** [comment]
You can click the History icon at the top of the view to open chats. This history is per-workspace, maybe that's the confusion. You can also find the Export and Import Session commands in the F1 command palette.

Feature request for rename: https://github.com/microsoft/vscode-copilot-release/issues/459
