### ISSUE TITLE
When scrolling up from the bottom of a chat window on Mac OSX sonoma

### ISSUE THREAD

**Issue by CoryWBoris** [microsoft/vscode-copilot-release#1053]
On the latest version of vs code for mac osx Sonoma, the copilot chat has a scrolling bug when you start to accrue a long response history. The bug happens when you scroll up at any pace. As you scroll up, there will be a random scroll down, of any amount, at any time when scrolling up. I'm curious if there any others who have observed this.

Really think the chat is becoming very useful overall, and I really appreciate the work being put into it daily!

-C

**Comment by roblourens** [comment]
I don't quite follow, but are you using Insiders? If not, can you check if it happens in VS Code Insiders?

Or a screen recording/screenshot might help explain it?

**Comment by CoryWBoris** [comment]
Sorry about the lack of clarity. To be more clear, what I realized is that there seems to be a freezing that occurs if I scroll too quickly on a sufficiently large chat history when using co-pilot chat. When I experimented with differing lengths that trigger the glitch, I found it didn't take more than 4 or 5 full responses to trigger this. The 'jumping' behavior I noticed can happen in either direction, specifically scrolling up suddenly or scrolling down suddenly. It feels like scrolling too quickly causes this freeze, and then the store up of scroll momentum is released at once, making it difficult to scroll precisely for a large enough chat history.

https://github.com/microsoft/vscode-copilot-release/assets/129540279/8825bb6e-3151-4024-93f7-88969a57b6a2

**Comment by CoryWBoris** [comment]
And just a further note to add here, if the chat history is sufficiently large, vs code essentially locks up and becomes very slow, and almost inoperable while the chats' messages are being displayed in live time. When a chat message response is done being written by the co pilot engine, vs code still is a bit slow and delayed, feels like about a half second or so of lag between typing and seeing my letters in the chat window. I'm using a 2020 macbook pro with an intel 8 core

**Comment by roblourens** [comment]
I'm aware of a minor layout issue with codeblocks, but I haven't seen any slowness or freezing as a result. Could you try to repro it then grab a profile following these steps? https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process Assuming you'll see high CPU in the renderer process
