### ISSUE TITLE
Mangled response from new workspace intent

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#1059]
<img width="372" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/323878/bb0ed727-55d5-43a6-a753-b9b7323704c1">

**Comment by bhavyaus** [comment]
Linked potential cause. Will fix it up.

**Comment by bhavyaus** [comment]
@mjbvz I'm also seeing this in other queries:

![image](https://github.com/microsoft/vscode-copilot-release/assets/25044782/5ee94ed0-78bd-469a-826d-73570b72f7bc)

**Comment by mjbvz** [comment]
Pretty bad as it prints out the entire message again every time a new character is added to the response. Will see if I can get a new build out once the fix is merged

**Comment by mjbvz** [comment]
Should be fixed now. Taking a look at getting out a new insiders
