### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by varadpatil** [microsoft/vscode-copilot-release#1060]
Type: <b>Bug</b>

Namaskar,

Copilot Chat is not working for a month. I'm payed subscriber. Please fix this at the earliest. Also request you to compensate the one month of payment, which was waste as the Copilot Chat was not working, and I had to rely on chat GPT for this duration, which was an extra payment. If this continues, i'll have to stop paying for Copilot and go for Chat GPT.

Looking forward for your co-operation.

Dhanyavad.

Extension version: 0.13.1
VS Code version: Code - Insiders 1.88.0-insider (f7c827a5e0ddbba66425ea54e33430bce8f53c84, 2024-03-20T05:51:34.759Z)
OS version: Linux x64 6.5.0-26-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 3599)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|28, 27, 23|
|Memory (System)|62.53GB (48.08GB free)|
|Process Argv|. --crash-reporter-id e8806bdb-7cde-42ca-8701-d0f9233aec5f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:30992800
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
d6fi2104:30968146
pydisww1:30991133
cppperfnew:30980852
d34g3935:30961436
fegfb526:30952798
bg6jg535:30979844
ccp2r3:30958153
pythonait:30973460
666c4381:30973073
gee8j676:30988845

```

</details>

**Comment by digitarald** [comment]
Please use the pre-release version of Copilot Chat (`0.14.*`) with Insiders. Please re-open of this doesn't fix it.

**Comment by varadpatil** [comment]
Dhanyavad @digitarald, it fixed the issue.

**Comment by tomaszszadziul** [comment]
@digitarald 
It's stopped working for me as well:

https://github.com/microsoft/vscode-copilot-release/assets/54362456/50e0d469-6c28-45b6-bb06-9320be952684

Currently I'm using: 
VSC: 1.87.2
System: Ubuntu 20.04.6 LTS 
GitHub Copilot Chat v0.13.2024022301 (pre-release)
GitHub Copilot v1.175.781 (pre-release)
It's a subscription from organisation.
