### ISSUE TITLE
Editing a previous chat message

### ISSUE THREAD

**Issue by L-Sypniewski** [microsoft/vscode-copilot-release#1067]
Ability to edit an already posted chat message would make the whole experience a lot faster. 
Currently, if my prompt turns out to yield not the result that I'd expect I need to
- copy the old message
    - if the message contains code snippets I need to copy each of them separately
-  manually delete the message
- paste the old message and edit
- apply the same metadata (for example, select a file with `#file`)

It would be acceptable for text-only messages, but there's no way to select the old message if it contains code snippets (text between ```).

Alternatively, the ability to copy the whole messages would make the process less painful. I could just:
- copy the whole message (including the code snippets and metadata)
- manually delete the message
- paste the old message and edit

**Comment by roblourens** [comment]
Did you know that you can press the up arrow to get the previous message back into the input?

**Comment by L-Sypniewski** [comment]
@roblourens I had no idea about the up arrow hotkey. 
Editing a message similarly to ChatGPT UI would be awesome, but this up arrow hotkey is a massive improvement to my workflow, thank you!
