### ISSUE TITLE
It won't provide any solution or the chat doesn't works as well 

### ISSUE THREAD

**Issue by SriVaishnavi01** [microsoft/vscode-copilot-release#1069]
- VS Code Version: 1.88.0 insider 
- OS Version: 11 Pro 
- Logs: zn.interactive.sendInteractiveRequestToProvider is not a function

Steps to Reproduce:

1. just use it ctrl + i  
2.

**Comment by joyceerhl** [comment]
Do you have the latest Copilot Chat pre-release installed and the latest VS Code Insiders?

**Comment by SriVaishnavi01** [comment]
It's been fixed.
