### ISSUE TITLE
Unexpected markdown rendering in chat request - Pasted code disappears when posting a message

### ISSUE THREAD

**Issue by Golem28** [microsoft/vscode-copilot-release#107]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Write a message
2. Paste code after the message
3. Post the message (the code is used in the reply, but is not shown)

**Comment by roblourens** [comment]
Can you share a screenshot? I'm not sure what you are seeing

**Comment by Golem28** [comment]
### First Example
I copied all the code in the image
![Bildschirmfoto vom 2023-05-25 08-55-49](https://github.com/microsoft/vscode-copilot-release/assets/117809300/502d4fe4-3349-4107-8ddf-f48d84de9656)

And than posted it and only a part of the code is shown in the chat:
![Bildschirmfoto vom 2023-05-25 08-56-49](https://github.com/microsoft/vscode-copilot-release/assets/117809300/dc4ba427-5a7e-4f44-af65-fbdac69b1cb0)

### Second Example
Here i copied the code again after the :. 
![Bildschirmfoto vom 2023-05-25 09-00-10](https://github.com/microsoft/vscode-copilot-release/assets/117809300/2c0b3b37-de6d-40fd-afce-5be46a8ef675)

And only a + is showing up at the place where the code should be:
![Bildschirmfoto vom 2023-05-25 09-00-21](https://github.com/microsoft/vscode-copilot-release/assets/117809300/f4738b24-36f3-4fd4-baa4-9cc026acef5f)

**Comment by roblourens** [comment]
Your message is rendered as markdown, but this is another good reason to get rid of rendering requests as markdown
