### ISSUE TITLE
High CPU usage at idle (20%)

### ISSUE THREAD

**Issue by danieln78** [microsoft/vscode-copilot-release#1070]
Type: <b>Bug</b>

Extension Bisect found that it was the Copilot chat that did it.

Didn't have any issues before activating copilot chat yesterday.

Extension version: 0.10.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.72GB (18.95GB free)|
|Process Argv|--crash-reporter-id 9c3abada-89cb-43e2-b696-327d9fc29d2c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30998030
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfcontrol:30979541
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonaic:30996667
gee8j676:30988843
dsvsc021:30996838

```

</details>

**Comment by lramos15** [comment]
Please ensure that your extension is up to date. 0.10.1 isn't the latest.

**Comment by deepak1556** [comment]
After updating the extension and if you still experience the issue, please follow the steps below to collect cpu profile

* Disable all extensions except Copilot chat
* From command palette run `Show Running Extensions`
* From the toolbar in top right corner choose `Start Extension Host profile`
* Let the profile run for a few seconds while ensuring the cpu usage reported in the issue is confirmed
* From the toolbar choose `Stop Extension Host Profile` and save it
* Attach the profile to this issue thread
