### ISSUE TITLE
whenever I using GitHub co-pilot chat in vscode it does not work well now days!

### ISSUE THREAD

**Issue by KuntalRathod** [microsoft/vscode-copilot-release#1076]
<img width="689" alt="Screenshot 2024-03-26 at 10 58 56 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/108223965/3dcfa88e-c147-4c7c-b166-26d4442a4e6a">

- VS Code Version: 1.87.2
- OS Version:  Darwin arm64 23.4.0
- Logs: Please check your firewall rules and network connection then try again. Error Code: ECONNREFUSED.
- System : Mac OS

Steps to Reproduce:

1.
2.

**Comment by lramos15** [comment]
Are you connected to some sort of firewall?

**Comment by chrmarti** [comment]
@devm33 Could you help with this?

**Comment by devm33** [comment]
One thing to try is the new networking, can you add the following to your settings:

```json
   "github.copilot.advanced": {
        "debug.useElectronFetcher": true
    },
```

If that doesn't work please share the `GitHub Copilot: Collect Diagnostics` output ([docs](https://docs.github.com/en/copilot/troubleshooting-github-copilot/viewing-logs-for-github-copilot-in-your-environment?tool=vscode#viewing-network-connectivity-diagnostics-logs-1)) and also try these [troubleshooting steps](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot).

**Comment by KuntalRathod** [comment]
> Are you connected to some sort of firewall?

No I'm not connected to any sort of firewall!!

**Comment by mengdaxing** [comment]
> One thing to try is the new networking, can you add the following to your settings:
> 
> ```json
>    "github.copilot.advanced": {
>         "debug.useElectronFetcher": true
>     },
> ```
> 
> If that doesn't work please share the `GitHub Copilot: Collect Diagnostics` output ([docs](https://docs.github.com/en/copilot/troubleshooting-github-copilot/viewing-logs-for-github-copilot-in-your-environment?tool=vscode#viewing-network-connectivity-diagnostics-logs-1)) and also try these [troubleshooting steps](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot).



> One thing to try is the new networking, can you add the following to your settings:
> 
> ```json
>    "github.copilot.advanced": {
>         "debug.useElectronFetcher": true
>     },
> ```
> 
> If that doesn't work please share the `GitHub Copilot: Collect Diagnostics` output ([docs](https://docs.github.com/en/copilot/troubleshooting-github-copilot/viewing-logs-for-github-copilot-in-your-environment?tool=vscode#viewing-network-connectivity-diagnostics-logs-1)) and also try these [troubleshooting steps](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-network-errors-for-github-copilot).

Wow, this one worked!
