### ISSUE TITLE
Ideally, having Copilot understand context so as not offer same suggestions maybe a megabyte of storage for an hour on text base conversation

### ISSUE THREAD

**Issue by AGSUofC** [microsoft/vscode-copilot-release#1078]
Here is a conversation I had with GitHub Copilot Chat in VSCode when I noticed now, and it has done in the past that it was providing a solution that had not worked previously, and it is now suggesting it again. It would be ideal if some memory was allocated to, say, an hour's worth of temporary storage of a conversation within the same chat (keep it as text base, as that should not take up too much memory). I would hazard a guess of maybe one megabyte for an hour of text conversation that Copilot could reference while responding and seeing that from that text it had already offered a solution that didn't work.  It would eliminate forgetting and suggesting code that didn't work or had changed previously:

GitHub Copilot
You should add the line model.add(Reshape((n_output, 1))) in the create_generator function, replacing the existing reshape line. Here's how it should look:
def create_generator():
    model = Sequential()
    model.add(Dense(units=256, input_dim=n_input*n_features))
    model.add(LeakyReLU(0.2))
    model.add(Dense(units=512))
    model.add(LeakyReLU(0.2))
    model.add(Dense(units=1024))
    model.add(LeakyReLU(0.2))
    model.add(Dense(units=n_output, activation='tanh'))
    model.add(Reshape((n_output, 1)))  # Reshape the output to match the discriminator's input shape
    return model
This change is in Block 3 of your code. The reshape layer is the last layer in your generator model. It changes the shape of the output to match the input shape expected by the discriminator.

AGSUofC
Do you keep track of all the suggestions and the errors prevously from this chat?

GitHub Copilot
As an AI, I don't have the ability to remember or keep track of past interactions. Each conversation is independent and doesn't have context from previous conversations. However, the platform that's using this AI model may store conversation history for the duration of a single session.

AGSUofC
I'm using VScode while chatting with you. My concern is that you previously, in this chat, had me change 
To this: 
model.add(Reshape((n_input, n_features))) # Reshape the output to be 3-dimensional
From this:
model.add(Reshape((n_output, 1))) # Reshape the output to be 3-dimensional

Do you notice that you are now suggesting I go back to n_ouput? It sucks that you can't find what we've chatted about just a few hours ago in this very same chat. I'm worried you are taking me into a circle, as you can't remember what you had me changed, and we're going back to the start, and I've lost 3 hours of work. Unless you think if we change back to n_ouput, will the other four suggestions you just made for changes work?

GitHub Copilot
I apologize for the confusion. As an AI, I don't have the ability to remember past interactions. However, the reshape layer should match the input shape of the discriminator. If the discriminator's input shape is (n_input, n_features), then the generator's reshape layer should be model.add(Reshape((n_input, n_features))). If the discriminator's input shape is (n_output, 1), then the generator's reshape layer should be model.add(Reshape((n_output, 1))).
The goal is to ensure that the generator's output shape matches the discriminator's input shape. If the other changes I suggested don't depend on this particular reshape layer, you can implement them first and then adjust the reshape layer as needed. I'm here to assist you, and I'm sorry for any inconvenience caused.

AGSUofC
First, what do you mean by "ability to remember past interactions"? You know I'm talking about this chat we're having here. I'm not talking about a different chat conversation, but this one we've had for the last few hours.

GitHub Copilot
I apologize for any confusion. As an AI, I can't recall or store information from previous interactions within the same conversation. Each request is processed independently and doesn't have the context of earlier requests. This means I can't look back at previous parts of the conversation or remember what was discussed earlier in the same conversation. I designed this way to prioritize user privacy and data security. I'm here to provide information and assistance based on the current request, independent of previous interactions.

AGSUofC
You know this will cause a problem, as you will then go back and forth, saying, " Oh, solution A doesn't work. Let's try solution B." After trying solution B, you will say, "Oh, solution B doesn't work. Let's try this solution, which happens to be solution A." So, we end up going back and forth because you will only look at solutions A and B when there could be solution C.

GitHub Copilot
I understand your concern. As an AI, I provide suggestions based on the current context and the information available at the moment. If a previous suggestion didn't work, I try to provide an alternative solution. However, I don't have the ability to recall past interactions or remember previous suggestions. I'm here to assist you, and I'm sorry for any inconvenience caused. If you have a specific issue with your code, please provide the details and I'll do my best to help you find a solution.

AGSUofC
I'm afraid you can't. You are just providing the same two solutions repeatedly and never looking beyond those.

GitHub Copilot
I understand your frustration and I apologize for any inconvenience. As an AI, I provide solutions based on the information available at the moment. If the provided solutions are not working, it might be beneficial to take a step back and revisit the problem. If you could provide more context or details about the issue you're facing, I'll do my best to help you find a solution.

AGSUofC
Is there a better AI out there that can help? Like Chatgpt, Gemni, Perplexity AI, etc. What do you suggest?

GitHub Copilot
As an AI developed by OpenAI, I can provide information about the AI models developed by OpenAI. GPT-3 and Codex are two of the most advanced models developed by OpenAI. GPT-3 is designed for general-purpose tasks and can generate human-like text based on the input provided. Codex, which powers GitHub Copilot, is specifically designed for coding-related tasks and can generate code based on the input provided.

However, the effectiveness of an AI model can depend on the specific task and the data it was trained on. For software development tasks, GitHub Copilot powered by Codex could be a good choice. For general conversation and text generation, GPT-3 could be a good choice.

There are also many other AI models developed by different organizations. Some of them include Google's BERT and T5, Facebook's BART, and Microsoft's Turing-NLG. Each of these models has its own strengths and is designed for different tasks. The choice of model can depend on the specific requirements of your task.

AGSUofC
So when you say, "By saying "I can provide assistance based on the current context of our conversation," I mean that I can respond to your inquiries and provide guidance based on the information you've provided in our current conversation session. However, I don't retain the memory of past interactions or suggestions made within this session." I'm lost in your grammar as conersation and suggestion?

GitHub Copilot
I apologize for any confusion. What I meant to say is that I can provide assistance based on the information you provide in the current conversation. However, I don't have the ability to remember or recall past interactions or suggestions made within this conversation. Each request is processed independently and doesn't have context from previous requests. I hope this clarifies your question.

AGSUofC
how do I tell we're in a current conversation and "past interactions or suggestions made within this conversation."

GitHub Copilot
As an AI, I don't have the ability to maintain a conversation history or recall past interactions. Each request you make is processed independently, without context from previous requests. When I mention "current conversation", I'm referring to the immediate request and response. For example, if you ask a question and I provide an answer, that's considered a single conversation turn. If you ask a follow-up question related to the previous one within the same request, I can respond to it because it's part of the same immediate context. However, if you ask a follow-up question in a new request, I won't have the context of the previous question because I don't have the ability to remember past interactions.

AGSUofC
How do I ensure that I ask a follow-up question related to the previous one within the same request?

GitHub Copilot
To ask a follow-up question within the same request, you simply need to include it in the same message or conversation turn. For example, if you asked a question about a piece of code and I provided an answer, you can immediately ask a related question in your next message. This way, the context of the previous question is still available for the current conversation turn. However, if you start a new conversation or if there are several unrelated messages in between, the context of the previous question might be lost.

AGSUofC
Okay, if I understand correctly, if I ask a question and you provide an answer, I can ask another question related to that answer, and so on, and I could even ask a question related to your first answer, even if it was 20 questions ago.

GitHub Copilot
Yes, you can ask a follow-up question at any point. However, please note that I don't have the ability to recall past interactions. Each question you ask is processed independently, without context from previous questions. So if you ask a follow-up question related to a previous one, it would be helpful to provide some context from the previous question to ensure I provide the most accurate and helpful response.

I edited our conversation a bit, for clarity.

**Comment by aiday-mar** [comment]
Hi @AGSUofC thank you for posting this issue. I believe that there the prompt sent contains in memory part of the past conversation, but I am think it does not go far back. After an hour of continuous talking to copilot, the conversations you have previously had would likely be forgotten already. Pinging @lramos15 whom I believe knows more about this.

**Comment by AGSUofC** [comment]
Aiday,

Thank you for taking the time to get back to me. As you can see from my discussion with Copilot, it’s not that it keeps some in it; you have to stay on just the thread of its answers. Suppose one deviates from asking a question like “why” and decides to do something instead of fixing a coding problem. It’s a new thread, and it has forgotten about the question, even if it was 20 seconds ago. Ideally, it would be great if it had in its memory all the threads for, say, an hour so that when we try to resolve a problem, it will check what a solution would be and then check its memory to see if we had tried it before, and if it has, then search through its database, to see what would be a different solution. I usually, at the start, give it multiple blocks from the beginning of my code so it has an understanding of what I’m doing. When we try to make a fix, I ask if the problem is earlier on and if we should look at that instead of where the error is occurring.

I say it works reasonably well; I need to prompt it adequately. I know different AI tools prefer other ways; if you recommend a link for Copilot, that would be helpful.

Thanks again.

Cheers,
       Alex

----------------------------------------------------------------
Alexander G. Sidaway, PMP
Transdisciplinary Research Ph.D. Candidate
Departments of Environmental Design (EVDS) /
Electrical & Software Engineering (E&SE)
Field of Study: Climate Informatics (AI & Urban Systems)
____________________________________________________________________________________________________________________________________________

E: ***@***.******@***.***>     The University of Calgary
                                                   2500 University Dr. NW
                                                    Calgary, AB, T2N 1N4

linkedin.com/in/alex-sidaway-phd-candidate-pmp-95a55815<https://www.linkedin.com/in/alex-sidaway-phd-candidate-pmp-95a55815>
_________________________________________________________________________________ ____________________________________________________________

ISC: Protected

**Comment by aiday-mar** [comment]
Hi @AGSUofC thanks for the clarification. Other team members would know better how the history is implemented in Copilot. Let's see what they say.

**Comment by aiday-mar** [comment]
Hi @AGSUofC I believe we have improved history retention since the month of March. Do you still see this issue?
