### ISSUE TITLE
[Feature Request]: Remember a different width for the Chat tab and for the other tabs

### ISSUE THREAD

**Issue by XStarlink** [microsoft/vscode-copilot-release#108]
Hello,

I don't keep the Chat tab open all the time, and I find that Chat is more comfortable with a good width,

I would like that when I am on the Chat tab, it remembers the width I set, and when I go back to the other tabs (e.g. files), it returns to a smaller width.

**Comment by roblourens** [comment]
This isn't really practical for us to implement with the way I think the sidebar should work. But, you might want to move chat to the panel or use a chat editor
