### ISSUE TITLE
Copilot wont use workspace

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#1085]
Copilot keeps telling me: I apologize for the confusion. As an AI developed by OpenAI, I don't have the ability to access your local files or workspace. The @workspace directive in the prompt is a hypothetical construct for the purpose of this simulation and doesn't grant actual access to a user's workspace.
- VS Code Version:  Version: 1.88.0-insider (Universal)
- OS Version: Soma 14.4
- GitHub Copilot Chat:  v0.14.2024032701 (pre-release) 

Steps to Reproduce:

1. use @workspace

**Comment by mjbvz** [comment]
Please share an example question. A screenshot of the chat may also be helpful

**Comment by jrwashburn** [comment]
May not be the exact same scenario, but I'm also having difficulty getting copilot to use the reference from the workspace. Screenshot:
[Screenshot 2024-03-28 at 7.14.56 PM.png.pdf](https://github.com/microsoft/vscode-copilot-release/files/14797560/Screenshot.2024-03-28.at.7.14.56.PM.png.pdf)

**Comment by EternalGoldenBraid** [comment]
Exact same issue here. File is shown to be included as a reference (like in the above image) but it's promptly ignored based on the model's response.

**Comment by mjbvz** [comment]
I think the original issue @salientknight was seeing is unrelated to these other posters. In the original case, it looks like `@workspace` itself was not recognized. Right now `@workspace`  needs to be at the start of the prompt. You can confirm it's working by seeing the `@workspace` word change colors. Correct:

![Image](https://github.com/user-attachments/assets/543c1529-7956-49e7-8656-116490c1d44e)

Incorrect:

![Image](https://github.com/user-attachments/assets/138b8214-e204-4133-aa7e-a53dcfe4f19a)


---

For these other issues, we have fixed a few issues that could cause long files referenced by `@workspace` to be silently dropped from the prompt. If you try manually including a long file, you will now also see a warning about this:

![Image](https://github.com/user-attachments/assets/d9f345aa-25c0-4d57-afd6-566fb5a5c433)
