### ISSUE TITLE
Copilot Chat with @workspace and @new tags regenerates response in loop

### ISSUE THREAD

**Issue by kshitijzutshi** [microsoft/vscode-copilot-release#1090]
**Specs**

- VS Code Version: 1.87.1 (Universal)
- OS Version: Darwin arm64 23.4.0

**Steps to Reproduce:**

1. Initiate a new chat starting with "**@ workspace**" tag followed by "**@ new**" tag
2. Enter the prompt into copilot chat, in this case eg., "Help me write code in C#"
3. Copilot responds with the folder structure for a C# project but for next explanation, after every word regenerates the folder structure. Screenshot and Recording attached.

<img width="650" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/13203059/69a94e73-8f93-4862-980e-124afe67d070">

https://github.com/microsoft/vscode-copilot-release/assets/13203059/64958e02-6221-44b9-b50f-ea89331f6eaa

**Comment by bhavyaus** [comment]
This issue has been fixed in the latest release.

**Comment by kshitijzutshi** [comment]
@bhavyaus Oh cool. I will check it up after updating on my end with latest release. Great work! 🎊
