### ISSUE TITLE
[Bug] `/help` doesn't include `#file` context variable

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-copilot-release#1092]
Type `/help` in chat window, the response doesn't include the `#file` context variable:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28700378/541eaf05-1142-44ec-aa4c-9cf7940b1887)
I suggest updating the `/help` response template to include all chat features.

**Comment by roblourens** [comment]
Good point, thanks
