### ISSUE TITLE
Does not understand context of the code

### ISSUE THREAD

**Issue by ishaileshmishra** [microsoft/vscode-copilot-release#1094]
- VS Code Version: 

```
Version: 1.87.2 (Universal)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z (3 wks ago)
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.4.0
```

- OS Version:  MacOS, 14.4.1 (23E224)

- Logs: 

Steps to Reproduce:

1. Select any block of code and ask to write a test for the selected chunk
2. even after providing the context of the code like environment, framework and language it is unable to figure it out, how to write code

**Comment by roblourens** [comment]
If the selection is too large to fit into the context window, then it could be omitted- this is generally what is happening in this case.

**Comment by MikeImbar** [comment]
What is too large? 200 lines? 2000? I am having the same issue with 300 lines of code.

**Comment by roblourens** [comment]
Depends. 300 lines might be too much
