### ISSUE TITLE
Edit multiple files in one request with Copilot

### ISSUE THREAD

**Issue by ZFYL** [microsoft/vscode-copilot-release#1098]
I am using Copilot in a Django project which i try to keep really vanilla. Thus it's using all the basic building blocks and Copilot easily applies the best practices. But i find myself in long sessions of copy paste into different linked files urls.py, models.py, views.py, serializers.py and tests.py etc. So these are simple changes that need to be made in 8+ files every time.

Would be nice to have a `@workspace /edit Add a new field to the Requests model and change all the subsequent related files in the project` that shows a similar UI like `/new` and when pressing an *Apply changes* button it adds the changes.

The changes could be reviewed during a commit. If the commit contains breaking changes we could rollback the changes.

Is there in plans to add such a feature? Is there a similar plugin or a command combination that does this or similar?

Thanks for the response!

**Comment by maciekgajewski** [comment]
Yep. Changing both header and implementation in a C++ project would be nice

**Comment by AdrianLThomas** [comment]
This would be great for scenarios where you want to do a larger "find and replace" but where you can't do it with a simple regex. For example changing multiple test files to meet a new convention / meet best practice. I can envisage a prompt to explain the problem and Copilot could go ahead and make the change.

**Comment by marian-toaderr** [comment]
no news on this?

**Comment by isidorn** [comment]
This is now done, please try out the Copilot Edits view and let us know what you think
https://code.visualstudio.com/docs/copilot/copilot-edits
