### ISSUE TITLE
Temporary test files breaking jest

### ISSUE THREAD

**Issue by ndemayo-bah** [microsoft/vscode-copilot-release#1099]
I have a typescript Azure Function app with jest and ts-jest; my tests are passing just fine, but when I ask copilot to make any modifications to the tests, it will create a "temporary" file within my workspace that is only visible within chat. This file is causing a couple of issues:
1. The problems tab in vs code is showing errors related to the temporary file, which will open said file within vscode
2. The **biggest** problem... `jest` will start picking up on any of the tests in that file, and fail them, causing in duplicated tests and errors that don't actually exist.

For number 2 above, the only way I've been able to resolve this is to completely delete my local code and re-clone from git.

- VS Code Version: 1.87.2
- OS Version: macOS Sonoma 14.4.1

Steps to Reproduce:

1. Ask copilot to generate tests for a file in the workspace
2. Open vscode problem window and note that the temp file's problems are listed
4. Run `jest` and note that there are now extra tests that fail

**Comment by ericchapman80** [comment]
I've posted this in the Copilot discussion as well via this [question](https://github.com/orgs/community/discussions/116675).

**Comment by ndemayo-bah** [comment]
Discovered the issue and it was not copilot related... the Azure Function was including my tests folder when building and jest was finding those tests and running them along with my actual ones... this issue can be closed :)
