### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by FlorianMartinez01** [microsoft/vscode-copilot-release#11]
Hi,

I have received the beta access this morning and I've follow the installation instruction but I don't have any chat icon. I'm on VSCode last update and i also tried it on the insider. Did I do something wrong ?

Thank for your help and I hope I will be able to try it soon.

![image](https://github.com/microsoft/vscode-copilot-release/assets/32646182/847f58e2-782c-4179-9a06-e4e19155d764)

**Comment by Qasszls** [comment]
Hello, please attach the software version, system version and installed plug-in screenshots

**Comment by FlorianMartinez01** [comment]
Sure, I forgot to attached them

Here are the two plug-in installed
![image](https://github.com/microsoft/vscode-copilot-release/assets/32646182/ff43e373-d609-4c03-b11b-8fbd4c5052a0)

And here are my about from VS Code
![image](https://github.com/microsoft/vscode-copilot-release/assets/32646182/8493e5ed-816e-41ae-9727-8b92fdb5056e)

**Comment by Qasszls** [comment]
Maybe you can look at this. I think it's a software version issue：https://github.com/microsoft/vscode-copilot-release/issues/8#issuecomment-1550757564

**Comment by FlorianMartinez01** [comment]
Thanks you a lot, I have already try with the insider version but seems to download an old insider version instead of the last one. It fix now.

Have a great Dev Day :)
