### ISSUE TITLE
Vscode command unable to delete nonexistent file

### ISSUE THREAD

**Issue by asportnoy** [microsoft/vscode-copilot-release#110]
- VS Code Version: Version: 1.79.0-insider microsoft/vscode@f6be5461f8bc69013a605f5baea834651c6589fb
- OS Version: macOS Ventura 13.3.1
- Logs: N/A

I get this error whenever I try to use a `/vscode` command
![Screenshot 2023-05-24 at 12 18 16](https://github.com/microsoft/vscode-copilot-release/assets/14863373/e8df2ad6-1862-461b-bfee-88e5d280a8b3)

Steps to Reproduce:

1. Use any `/vscode` command

**Comment by mark-wiemer** [comment]
Same for Windows 11:

> /vscode what version of vs code is this and how can I tell?

Indexing, this should only happen once and takes about a few minutes...

Unable to delete nonexistent file 'vscode-userdata:/c:/Users/mwiemer/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/settingEmbeddings.json'

**Comment by lramos15** [comment]
Thanks for the report. A fix is pending :)
