### ISSUE TITLE
Copilot can't see any code if too much is highlighted

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#1101]
There seems to be a hidden line limit for the amount of highlighted code that can be sent with a chat request. Anything beyond that and Copilot acts like nothing is highlighted (despite the fact that the chat UI indicates the file and all the highlighted lines were actually sent):

![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/4ca002d8-2d17-47bd-9036-f119a3b635f0)

This leads to a lot of unnecessary confusion and frustration. There either needs to be clear feedback when the number of highlighted lines is too high, or preferably the API needs to be improved so it can handle more code at once.

The latter would be a much better option - Claude 3 Opus can handle huge amounts of code, and as a result can have much more meaningful interactions when dealing with large sections of a codebase. I'm finding Claude to be far more capable than Copilot in this respect. Copilot needs to catch up or it'll be left behind.

**Comment by lramos15** [comment]
We've increased the token window quite a bit and made better efforts here to make Copilot work with large documents. Give it a try and let us know what you think 👍
