### ISSUE TITLE
Programmatically generate commit messages

### ISSUE THREAD

**Issue by RoCat** [microsoft/vscode-copilot-release#1103]
Hi all,

I currently use a internal company script to create commits and merge requests.
This tool, bound with an issue tracker allow to generate commits using conventional commit and kind of automatically link this commit to an issue.

command looks like: "commit-tool -m "commit message" -t "spent time" -i "issue ID"
then it generate the commit, and read the issue to create a PR on the central remote with a link to the issue + its title for context

I wanted to improve that tool using copilot to generate the commit message according to :
- the staged diff
- the issue title

If I manually uses the chat and ask for a commit message that works. But what I want is to uses same mechanics programmatically and get the commit message without human interactions / noises.

I tried some unfortunate things using "gh copilot suggest" command and I king of run out of idea...
Is that something intended to be possible currently or planed or should I just change to use openAI API call ?

**Comment by lramos15** [comment]
This is out of scope, and better intended for an LLM API.
