### ISSUE TITLE
Can't use chat anymore 

### ISSUE THREAD

**Issue by pcc-sainik** [microsoft/vscode-copilot-release#1105]
On installing copilot extension I am seeing `aiTextSearchProvider` related log in the logs. I am unable to interact with the chat UI. If somehow I am able to send messages then it keeps thinking/generating.

Extension Version
Github Copilot: 1.178.0
Github Copilot Chat: 0.14.0

- VS Code Version: 1.88.0
- OS Version: Windows_NT x64 10.0.19045
- Logs: 

> 2024-04-06 11:02:30.763 [info] [FetcherService] Using Helix fetcher
2024-04-06 11:02:30.763 [info] [gitExtensionService] Initializing Git extension service.
2024-04-06 11:02:31.046 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-06 11:02:31.046 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-04-06 11:02:31.046 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-04-06 11:02:32.324 [info] [auth] Logged in as pcc-sainik
2024-04-06 11:02:33.214 [info] [chat] copilot token chat_enabled: true
2024-04-06 11:02:33.214 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-04-06 11:02:33.214 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-06 11:02:33.274 [info] [auth] Got Copilot token for pcc-sainik
2024-04-06 11:02:34.597 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-04-06 11:02:34.597 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.

Steps to Reproduce:

1. Install the extension.
2. you'll see aiTextSearchProvider in logs

**Comment by pcc-sainik** [comment]
Update: the error is still there but I am able to interact with copilot in the chat. I am okay to close the issue now.

**Comment by wuxiaohan2023** [comment]
hello , I have also encountered this issue, which can only be used in chat and cannot be directly prompted in the code view

**Comment by EvanJameson** [comment]
Also experiencing this issue, any recourse?

**Comment by canichangeitlaterquestionmark** [comment]
same here, token expired or invalid 403 
![image](https://github.com/microsoft/vscode-copilot-release/assets/168717740/3b51b359-6186-4508-900a-1ed281e2a7da)

**Comment by danielstefanescu** [comment]
The issue appeared today:

![2024-05-08 10_02_33-Clipboard](https://github.com/microsoft/vscode-copilot-release/assets/19574258/6821e505-a812-4137-976d-c1ab76934e31)

**Comment by zkreutzjanz** [comment]
@joyceerhl You closed this with no info, can you link us to most recent issue tracking?

**Comment by sergei3000** [comment]
me too

<img width="1159" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/18502517/2bb259b2-92a8-49f0-8984-6602007a264b">

**Comment by delano** [comment]
I'm seeing the same error in the dev tools console when opening a in a new window.

Steps to Reproduce:
1. Install or enable GitHub Copilot extension. 
1. Open a New Window via File > New Window
1. Open dev tools via Command Palette > Toggle Developer Tools  


### Versions

#### Extensions
GitHub Copilot: v1.194.886 (pre-release)
GitHub Copilot Chat: v0.15.2024043005 (pre-release)

#### VS Code

Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.5.0

### Error text

```
console.ts:137 [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
```

**Comment by od-dstefan** [comment]
@zkreutzjanz - Did you end up opening a new issue with this? I'm experiencing the same issue (Registration of interactive providers failed) for the aiTextSearchProvider extension.  The Yellow Diamond Icon 
![image](https://github.com/microsoft/vscode-copilot-release/assets/157532298/7cfa17ec-0dfe-423e-90dd-f14d924b6472)
 only showed on files that were not known code (.tfvars, .env,). it does not appear in files that are known types (.py, .tf, .md).

**Comment by zkreutzjanz** [comment]
@od-dstefan No, it started working for me. I was on the latest release when the issue occured, i had to totally wipe and reinstall for everything to work. IE remove all extensions from profile, uninstall vs code, reinstall and add needed extensions.
