### ISSUE TITLE
Co pilot not working in Fedora

### ISSUE THREAD

**Issue by happinessisreal** [microsoft/vscode-copilot-release#1106]
I have recently moved to Fedora. I just installed VS Code and along with it GitHub Copilot. But it doesn't seem to work. This issue also occurred before when I was using Ubuntu which I couldn't fix. Now it is happening again in Fedora. So I don't think it is a Fedora specific issue.

VS Code Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:25:57.039Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.4-200.fc39.x86_64
Github Copilot Version : 1.178.0
Github Copilot Chat Version :0.14.0

Logs:

> 
2024-04-06 13:06:24.888 [info] [FetcherService] Using Helix fetcher
2024-04-06 13:06:24.888 [info] [gitExtensionService] Initializing Git extension service.
2024-04-06 13:06:24.888 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-06 13:06:24.888 [info] [gitExtensionService] Enablement state of the vscode.git extension: false.
2024-04-06 13:06:25.267 [info] [auth] Logged in as happinessisreal
2024-04-06 13:06:26.246 [info] [chat] copilot token chat_enabled: true
2024-04-06 13:06:26.246 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-04-06 13:06:26.246 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-06 13:06:26.246 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-04-06 13:06:26.283 [info] [auth] Got Copilot token for happinessisreal
2024-04-06 13:06:27.794 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-06 13:06:27.794 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-06 13:06:27.794 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-06 13:06:27.794 [info] [chat fetch] chat model gpt-4
2024-04-06 13:06:58.476 [info] [FetcherService] Using Helix fetcher
2024-04-06 13:06:58.476 [info] [gitExtensionService] Initializing Git extension service.
2024-04-06 13:06:58.576 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-04-06 13:06:58.576 [info] [gitExtensionService] Enablement state of the vscode.git extension: false.
2024-04-06 13:06:59.434 [info] [auth] Logged in as happinessisreal
2024-04-06 13:07:00.177 [info] [chat] copilot token chat_enabled: true
2024-04-06 13:07:00.177 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-04-06 13:07:00.177 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-04-06 13:07:00.177 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-04-06 13:07:00.213 [info] [auth] Got Copilot token for happinessisreal
2024-04-06 13:07:07.837 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-06 13:07:07.837 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-06 13:07:07.837 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-06 13:07:07.837 [info] [chat fetch] chat model gpt-4
2024-04-06 13:11:16.684 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-06 13:11:16.684 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-06 13:11:16.684 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-06 13:11:16.684 [info] [chat fetch] chat model gpt-4
2024-04-06 13:12:13.921 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-06 13:12:13.921 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-06 13:12:13.921 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-06 13:12:13.921 [info] [chat fetch] chat model gpt-4
2024-04-06 13:12:42.074 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-06 13:12:42.074 [info] [chat fetch] modelMaxPromptTokens 3072
2024-04-06 13:12:42.074 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-06 13:12:42.074 [info] [chat fetch] chat model gpt-4

Steps to Reproduce:

1. Open VS Code
2. Run any command in copilot
![Screenshot_20240406_131722](https://github.com/microsoft/vscode-copilot-release/assets/50579737/03dcdeac-ad48-46ef-9e52-068cd0d43706)

**Comment by kousw** [comment]
I have the same issue.
On Windows host it works fine. However, on WSL via remote ssh it does not work well.

Neither normal Copilot nor Chat can be used, but the logs will not output anything except those related to aiTextSearchProvider.

**Comment by aslanutku** [comment]
> I have the same issue. On Windows host it works fine. However, on WSL via remote ssh it does not work well.
> 
> Neither normal Copilot nor Chat can be used, but the logs will not output anything except those related to aiTextSearchProvider.

I'm also facing the same issue. Have you found a solution?

**Comment by lramos15** [comment]
I believe this has been fixed in an update. Can you update your extension and VS Code and let me know if you're still having issues

**Comment by gcanitezer** [comment]
Similar error in macos. It always restarts the extension host and chat send button becomes a square box.

```
Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): extensionsAny, newSymbolNamesProvider, interactive, chatProvider, codeActionAI, findTextInFiles, findFiles2, textSearchProvider, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, mappedEditsProvider, aiRelatedInformation, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, contribSourceControlInputBoxMenu, authLearnMore, testObserver, aiTextSearchProvider
product.json (WINS): interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver
log.ts:419  INFO Started local extension host with pid 36087.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/myuser/.vscode/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/myuser/.vscode/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ ../../../vs/workbenc…nWorker.worker.js:6
log.ts:439   ERR [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
console.ts:137 [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
w @ console.ts:137
log.ts:419  INFO [perf] Render performance baseline is 30ms
abstractExtensionService.ts:800 Extension host (LocalProcess pid: 36087) terminated unexpectedly. Code: 5, Signal: unknown
yb @ abstractExtensionService.ts:800
log.ts:439   ERR Extension host (LocalProcess pid: 36087) terminated unexpectedly. No extensions were activated.
log.ts:419  INFO Automatically restarting the extension host.
6An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
log.ts:419  INFO Started local extension host with pid 36539.
log.ts:439   ERR [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
console.ts:137 [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
w @ console.ts:137
log.ts:439   ERR No registered selector for ID: copilot-chat.fixWithCopilot
log.ts:439   ERR No registered selector for ID: copilot-chat.generateCommitMessage
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/myuser/.vscode/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
log.ts:419  INFO Started local extension host with pid 36806.
TMScopeRegistry.ts:46 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///Users/myuser/.vscode/extensions/redhat.vscode-yaml-1.14.0/syntaxes/yaml.tmLanguage.json
register @ TMScopeRegistry.ts:46
log.ts:439   ERR No registered selector for ID: ms-vscode.npm-command
log.ts:439   ERR [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
console.ts:137 [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
w @ console.ts:137
log.ts:439   ERR No registered selector for ID: copilot-chat.fixWithCopilot
log.ts:439   ERR No registered selector for ID: copilot-chat.generateCommitMessage
abstractExtensionService.ts:800 Extension host (LocalProcess pid: 36806) terminated unexpectedly. Code: 5, Signal: unknown
yb @ abstractExtensionService.ts:800
log.ts:439   ERR Extension host (LocalProcess pid: 36806) terminated unexpectedly. No extensions were activated.
log.ts:419  INFO Automatically restarting the extension host.
log.ts:419  INFO Started local extension host with pid 37056.
log.ts:439   ERR No registered selector for ID: ms-vscode.npm-command
log.ts:439   ERR [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
console.ts:137 [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
w @ console.ts:137
log.ts:439   ERR No registered selector for ID: copilot-chat.fixWithCopilot
log.ts:439   ERR No registered selector for ID: copilot-chat.generateCommitMessage
```
