### ISSUE TITLE
PHP code highlighting no longer works properly in Copilot chat

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#1107]
PHP code highlighting no longer works properly in Copilot chat. Highlighting is only shown for code that includes the `<?php` tag at the top. So basically all "snippets" are shown without highlighting.

This makes chat responses extremely hard to read when dealing with large chunks of code:
![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/1cf98b18-9d13-4b92-9890-9c9da374c21e)

Confirmation that it works if `<?php` is present:
![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/7ce6a7fb-fd06-4110-a7fb-77b4ecdc072c)
![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/09713447-cb8b-441e-a214-f4b226f02cc2)

**Comment by binaryfire** [comment]
Hi @roblourens. Could you clarify if any changes were made in an attempt to fix https://github.com/microsoft/vscode-copilot-release/issues/1104? The timing of that issue seems to line up perfectly with the beginning of this one. If so, could those changes please be reverted ASAP until a better fix for https://github.com/microsoft/vscode-copilot-release/issues/1104 can be figured out? The lack of syntax highlighting is a major usability issue.

**Comment by roblourens** [comment]
PHP highlighting only works with a <?php tag, since only code that comes after that is really php code. Since you asked for it to not include the tag, the code isn't highlighted. Nothing new here, although I understand that it's annoying, but that's just how php (and our syntax highlighting) works.

**Comment by binaryfire** [comment]
@roblourens Um.... I didn't ask for that? That's my point! It was another user, and that user's request has broken PHP highlight for **everyone**. Why is this issue being closed as "won't fix"? I don't understand why a single user's request is being put ahead of the entire PHP community.

**Comment by binaryfire** [comment]
Hi @Tyriar. Can you please ask someone who actually uses PHP to review this? This decision makes zero sense and is the kind of thing that will push users towards language-specific IDEs that are built by people who understand their user base. I.e. PHPStorm from JetBrains.

**Comment by roblourens** [comment]
By "Since you asked for it" I mean, in the chat prompt screenshot that you included above

**Comment by binaryfire** [comment]
Hi @roblourens. Here's an example which doesn't show any code highlighting in chat. It's strange since the language token (which I'm assuming is the opening "```php" part) is present.

I've also noticed that sometimes the copy icon will add an opening `<?php` tag even when it isn't visible in the chat window. And in these cases, the chat window code still isn't highlighted. 

So it seems like highlighting is ignoring the "```php" token and is only adding highlighting when `<?php` is actually visible at the top of the code block in the chat window.


```
binaryfire: I'm dynamically constructing the Filament run job form from the input_fields database field. The format of input_fields has changed. This is the new format:

[
  {
    "name": "test1",
    "type": "select",
    "options": [
      {
        "label": "aaa",
        "value": "bbb",
        "default": false
      },
      {
        "label": "ccc",
        "value": "ddd",
        "default": true
      }
    ],
    "description": "<p>Test 1</p>",
    "is_required": true
  },
  {
    "name": "test2",
    "type": "text_input",
    "options": {
      "f501020c-d2fa-4937-88d8-910c1303122b": {
        "label": null,
        "value": null,
        "default": false
      }
    },
    "description": "<p>Test 2</p>",
    "is_required": false
  }
]

Refactor the getRunJobFields private method to use the new data format.

GitHub Copilot: The `getRunJobFields` method needs to be updated to handle the new data format. Here's how you can do it:

```php
private function getRunJobFields(AutomationJob $record): array
{
    $data = $record->input_fields;

    $fields = collect($data)->map(function ($option) {
        $type = $option['type'];
        $name = $option['name'];
        $label = $option['label'];
        $description = $option['description'];
        $isRequired = $option['is_required'];
        $options = collect($option['options'])->mapWithKeys(function ($item) {
            return [$item['value'] => $item['label']];
        })->toArray();
        $value = collect($option['options'])->firstWhere('default', true)['value'] ?? null;

        switch ($type) {
            case 'text_input':
                return \Filament\Forms\Components\TextInput::make($name)
                    ->label($label)
                    ->hint($description)
                    ->required($isRequired)
                    ->value($value);
            case 'select':
                return \Filament\Forms\Components\Select::make($name)
                    ->label($label)
                    ->hint($description)
                    ->options($options)
                    ->required($isRequired)
                    ->value($value);
            case 'radio':
                return \Filament\Forms\Components\Radio::make($name)
                    ->label($label)
                    ->hint($description)
                    ->options($options)
                    ->required($isRequired)
                    ->value($value);
            case 'checkbox':
                return \Filament\Forms\Components\Checkbox::make($name)
                    ->label($label)
                    ->hint($description)
                    ->required($isRequired)
                    ->value($value);
            default:
                return null;
        }
    })->filter();

    return $fields->toArray();
}
```

In this updated method, the `options` array is transformed into an associative array where the keys are the option values and the values are the option labels. The `value` is set to the value of the first option where `default` is `true`. If no such option exists, `value` is set to `null`. The `description` and `is_required` fields are also used to set the hint and required status of the form component, respectively.`

**Comment by msolla-ligno** [comment]
More examples of wrong highlight in php copilot chat
![imagen](https://github.com/microsoft/vscode-copilot-release/assets/126880127/89a9f28d-02a7-43b3-bc10-1b26906419cc)

**Comment by roblourens** [comment]
I see it now, thanks, this does break sometimes. The intent is to add `<?php` when the LLM didn't include it, to ensure that highlighting works. Then we've got the other issue for copying php code without the tag.

**Comment by badasukerubin** [comment]
This is still an issue:

![image](https://github.com/microsoft/vscode-copilot-release/assets/20546078/8ee340da-b0ea-4681-ba83-9ee019e9815f)

It's also still inserts the tags at the Cursor regardless.

![image](https://github.com/microsoft/vscode-copilot-release/assets/20546078/56b2c8a9-ae51-45a1-b8d5-b1a101c50528)

cc @roblourens

**Comment by msolla-ligno** [comment]
> This is still an issue:
> 
> ![image](https://private-user-images.githubusercontent.com/20546078/335164585-8ee340da-b0ea-4681-ba83-9ee019e9815f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjk3NzgsIm5iZiI6MTcxNzA2OTQ3OCwicGF0aCI6Ii8yMDU0NjA3OC8zMzUxNjQ1ODUtOGVlMzQwZGEtYjBlYS00NjgxLWJhODMtOWVlMDE5ZTk4MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTE1NTAyOGIwNjY5ZTY5ZjJkMmIwM2FlYzg1YmY2ZDA1ZGQzZTBiMzYwYmZlM2QwOWQ2N2YxY2JjZmZkOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dHVJ1AhoVJErJQjfWSJ6Jjt_7FKyMQYX3ZFv9ggd_Vg)
> 
> It's also still inserts the tags at the Cursor regardless.
> 
> ![image](https://private-user-images.githubusercontent.com/20546078/335165442-56b2c8a9-ae51-45a1-b8d5-b1a101c50528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjk3NzgsIm5iZiI6MTcxNzA2OTQ3OCwicGF0aCI6Ii8yMDU0NjA3OC8zMzUxNjU0NDItNTZiMmM4YTktYWU1MS00NWExLWI4ZDUtYjFhMTAxYzUwNTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExNDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNWRhNjI2OWFjNTA2YWE2YjI4MTBjYjczNmZkOWU3MDVmNjZlMmE1NDRmM2ZlZmJlMTI3MWNjMDE0ZjI1MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Caft5U7mxf6XL2Q9SJ48tY9Klyn4LfrLbg6QSGnnUQ)
> 
> cc @roblourens

same for me

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1104 is for copying/inserting codeblocks.

It's only fixed in VS Code Insiders currently, are you using that?

**Comment by badasukerubin** [comment]
No, I use the regular VS Code. When does it ship to that?

**Comment by roblourens** [comment]
Next week

**Comment by alexander-nolan** [comment]
What was the fix for this? I've had the same problem with HCL code since February:

https://github.com/microsoft/vscode-copilot-release/issues/881
