### ISSUE TITLE
Incorrect response to basic inline chat question 

### ISSUE THREAD

**Issue by theReynald** [microsoft/vscode-copilot-release#1108]
- VS Code Version: Version: 1.89.0-insider
- OS Version: Sonoma 14.4.1
- Logs:

Steps to Reproduce:

1. Open chat in VS Code and ask it "What's the short cut for copilot inline chat?"
It responds with a long approach by suggesting to 1st open the command pallet & then typing "GitHub Copilot: Open Copilot Inline Chat" rather then just saying CMD+I.

Kind of defeats the purpose of a shortcut.

<img width="1271" alt="Bug 1 - ShortCutForInlineChatWrong" src="https://github.com/microsoft/vscode-copilot-release/assets/100732140/5c05fc66-5a53-4479-ab47-80187fbd2299">

**Comment by roblourens** [comment]
If you use the `@vscode` chat participant, it gets this question correct. In the future, we will probably be able to detect a vscode question and direct it to the right participant automatically
