### ISSUE TITLE
@terminal Font Increase Question Response Wrong

### ISSUE THREAD

**Issue by theReynald** [microsoft/vscode-copilot-release#1109]
- VS Code Version: Version: 1.89.0-insider
- OS Version: Sonoma 14.4.1
- Logs:

Steps to Reproduce:

1. Open chat & enter @terminal How do I increase font in terminal
2. The response it to hit CMD + Plus which is not right because we are using the @terminald participant so it should know the context if for fonts in the terminal - not the whole screen. If I use @vscode participant, it gives a better answer saying to use the command palette for "Terminal: Increase Font Size" which only increase the terminal font.
3. 
<img width="815" alt="Bug 2 - @terminalFontIncreaseQuestionWrong" src="https://github.com/microsoft/vscode-copilot-release/assets/100732140/8191596a-2540-4e20-bf97-97427ebb2cff">

**Comment by burkeholland** [comment]
I'm not able to replicate...



![Image](https://github.com/microsoft/vscode-copilot-release/assets/686963/c25d23ef-6f22-4fea-96d3-365e359d4a3d)

**Comment by Tyriar** [comment]
`@terminal`'s purpose is to answer questions about commands, so it's basically just like rolling a dice what terminal is answers for. `@vscode` is built for this purpose.

**Comment by burkeholland** [comment]
Makes sense. I think ideally the @terminal would know about the VS Code terminal as well from a developer perspective since the user is in the terminal within VS Code. The context is implied.

**Comment by Tyriar** [comment]
Ideally, and it does know know that it's VS Code, but I suspect prompting in that direction would degrade the results that it's actually intended to give.
