### ISSUE TITLE
Vscode command: Role must be "user", got "assistant"

### ISSUE THREAD

**Issue by asportnoy** [microsoft/vscode-copilot-release#111]
- VS Code Version: Version: 1.79.0-insider microsoft/vscode@f6be5461f8bc69013a605f5baea834651c6589fb
- OS Version: macOS Ventura 13.3.1
- Logs: N/A

Using `/vscode` with no additional prompt gives the aforementioned error

Steps to Reproduce:

1. Send `/vscode` with nothing else

**Comment by isaiahtaylor** [comment]
I was getting this consistently for a particular message which had a large ```hcl section in it.

**Comment by lramos15** [comment]
@isaiahtaylor I believe this bug is caused by when the message in the chat has too many characters causing it to be removed from the history which is not ideal. We're investigating a solution probably in the form of a character limit like other chats such as Discord uses.

**Comment by marmelade500** [comment]
I'm getting the same error, at least give it the character limit of GPT4. I wasn't surpassing that limit and still got this error.

**Comment by digitarald** [comment]
The original issue is a dupe of https://github.com/microsoft/vscode-copilot-release/issues/59 and fixed. Later issues with large responses are dupe of #20

**Comment by asportnoy** [comment]
Both of those issues seem to have different messages from mine. Are you sure they're the same?

**Comment by digitarald** [comment]
Yes, both basically mean the JSON we send to the API gets truncated.
