### ISSUE TITLE
this thing has amnesia?

### ISSUE THREAD

**Issue by mieprenzo** [microsoft/vscode-copilot-release#1111]
- VS Code Version: newest
- OS Version: windows 11
- Logs: none

Steps to Reproduce:

1. add reference from a file
2. add a reference from another file to edit that one as well
3. copilot completely forgot the context of its own code in the first reference

I want to know how it is possible this thing forget stuff in 2 seconds!

**Comment by DevBrent** [comment]
You'd have to follow this path:

1. https://arxiv.org/abs/1706.03762
2. https://arxiv.org/abs/2005.14165
3. https://medium.com/@crskilpatrick807/context-windows-the-short-term-memory-of-large-language-models-ab878fc6f9b5

ChatGPT which backs Copilot is "stateless". It has no memory.

**Comment by lramos15** [comment]
Consolidating to https://github.com/microsoft/vscode-copilot-release/issues/624
