### ISSUE TITLE
Allow removal of the prompt to install GitHub Copilot without actually installing it.

### ISSUE THREAD

**Issue by fishnet37222** [microsoft/vscode-copilot-release#1113]
I'd like the ability to get rid of the GitHub Copilot installation prompt without actually installing it.

I don't use GitHub Copilot and I don't plan on using it.  I find it very annoying that the only way to get rid of the prompt to install Github Copilot is to install GitHub Copilot especially since I will just be uninstalling it right after.

**Comment by digitarald** [comment]
@fishnet37222 do you have a screenshot of which prompt you mean?

**Comment by fishnet37222** [comment]
This screenshot shows the prompt.  I've highlighted it in yellow.
![image](https://github.com/microsoft/vscode-copilot-release/assets/1977106/0514898a-7574-4e31-abcd-c96d937302eb)

**Comment by fishnet37222** [comment]
BTW, I'm using the latest Insider build.

**Comment by bhavyaus** [comment]
@fishnet37222 Clicking on the prompt and dismissing the modal dialog which shows up will clear this badge notification and prevent it from showing up again.  I'll work on cleaning up this experience.

**Comment by fishnet37222** [comment]
I just tried clicking cancel on the dialog and it doesn't remove the notification.
