### ISSUE TITLE
PHP code highlighting no longer works properly in Copilot chat (take 2)

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#1114]
I'm opening another issue for this because the previous one (https://github.com/microsoft/vscode-copilot-release/issues/1107) was incorrectly closed. The team didn't take the time to read my issue properly and I was told I was the one who requested the change that broke this. I wasn't.

A user has requested that `<?php` be removed from PHP code snippets shown in Copilot Chat chat: https://github.com/microsoft/vscode-copilot-release/issues/1104. This has broken PHP code highlighting in the chat window. Highlighting is now only shown for code that includes the `<?php` tag at the top. So all "snippets" (which is the majority of returned code) are shown without highlighting. Screenshots below. 

I've searched the GitHub issues and discussions and couldn't find anyone else requesting this change. It doesn't make sense to prioritize a single user's request over the readability of the chat window for the entire PHP community.

This change has made chat responses extremely hard to read, to the point of being almost unusable for meaningful PHP development. The cognitive load when trying to read things like this is painful:
![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/1cf98b18-9d13-4b92-9890-9c9da374c21e)

Confirmation that the removal of the `<?php` tag is the cause of the issue:
![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/09713447-cb8b-441e-a214-f4b226f02cc2)
![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/7ce6a7fb-fd06-4110-a7fb-77b4ecdc072c)

**Comment by binaryfire** [comment]
PS. Here is some code from the VS Code codebase without any syntax highlighting, if you need a more familiar reference:

![image](https://github.com/microsoft/vscode-copilot-release/assets/5361908/c3db1569-0f9e-4760-87a3-bc6bc41cc881)

**Comment by roblourens** [comment]
Please don't open a dupe issue, we can always continue conversation or reopen a closed issue
