### ISSUE TITLE
Copilot does not give me any suggestions

### ISSUE THREAD

**Issue by rednag** [microsoft/vscode-copilot-release#1118]
I'm not getting any logs except that it is successfully authenticated.

Already tested it with code-insiders_1.89.0-1712729740_amd64.deb, but same issue.

- VS Code Version: code_1.88.0-1712152114_amd64.deb
- OS Version: Ubuntu 22.04.1
- Logs: I don't see any, although I set the log level to debug. 

Steps to Reproduce:

1. Opening VSCode
2. Waiting for Copilot to authenticate
3. Start coding without suggestions, although the spinner at the bottom right is spinning all the time.

**Comment by rednag** [comment]
Although Copilot Chat is working like a charm.

**Comment by rednag** [comment]
`2024-04-10 17:30:34.345 [error] [default] Error sending telemetry FetchError: The pending stream has been canceled (caused by: self signed certificate in certificate chain)
    at fetch (/home/user/.vscode/extensions/github.copilot-1.178.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (/home/user/.vscode/extensions/github.copilot-1.178.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
    at ZU.fetch (/home/user/.vscode/extensions/github.copilot-1.178.0/lib/src/network/helix.ts:78:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ERR_HTTP2_STREAM_CANCEL',
  errno: undefined,
  erroredSysCall: undefined`

**Comment by alexdima** [comment]
> self signed certificate in certificate chain

I think this might be the root problem. Could you please try out the latest pre-release version of the extension together with vscode insiders? There we have changed the network stack we're using by default to be the Chromium network stack. Thanks!

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode-copilot-release/issues/741.
