### ISSUE TITLE
Generated code nearly duplicated entire file

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/vscode-copilot-release#112]
- VS Code Version: Insiders (how can I tell specifics?)
- OS Version: Windows 11
- Logs: see below

Steps to Reproduce:

1. Open a react component with exhaustive-deps issues
2. Use Ctrl+I then ask something like "fix the exhaustive deps issues in this file"

Expected: The only lines modified are deps lines

Actual: Entire file nearly duplicated from selection downward

Logs:

[INFO] [default] [2023-05-24T20:27:29.900Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:27:30.180Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 278 ms
[INFO] [streamMessages] [2023-05-24T20:27:30.200Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:27:30.201Z] request done: headerRequestId: [853aca54-d731-473d-b47b-a69bd467cc38] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:27:30.480Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:27:30.556Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 75 ms
[INFO] [default] [2023-05-24T20:27:36.406Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:27:36.974Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 567 ms
[INFO] [streamMessages] [2023-05-24T20:27:37.502Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:27:37.505Z] request done: headerRequestId: [1d4e69a3-4854-4c39-b7ea-20b075b33cd8] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:27:37.511Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:27:37.734Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 223 ms
[INFO] [streamMessages] [2023-05-24T20:27:37.737Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:27:37.738Z] request done: headerRequestId: [51858b8d-fa34-4a28-b19a-dfbc4cbf4a3a] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:28:41.111Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:28:41.697Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 584 ms
[INFO] [streamMessages] [2023-05-24T20:28:43.296Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:28:43.298Z] request done: headerRequestId: [30de78f5-39da-4b80-b166-ad7c54598dab] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:28:43.306Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:28:43.697Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 391 ms
[INFO] [streamMessages] [2023-05-24T20:28:43.700Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:28:43.700Z] request done: headerRequestId: [3815948e-090a-4e72-b312-c4e8bd2b86d0] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:30:52.975Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:30:53.118Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 142 ms
[INFO] [streamMessages] [2023-05-24T20:30:53.121Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:30:53.122Z] request done: headerRequestId: [1f78c52f-d3ba-4298-b5be-bd8bdc1968e7] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:30:53.137Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:30:53.629Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 490 ms
[INFO] [streamMessages] [2023-05-24T20:30:55.498Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:30:55.500Z] request done: headerRequestId: [34dc8332-7e91-4d5d-8a51-243e92b92861] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:31:41.848Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:31:42.017Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 168 ms
[INFO] [streamMessages] [2023-05-24T20:31:42.019Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-05-24T20:31:42.019Z] request done: headerRequestId: [d5f6eff6-810a-4dab-96ab-8c4f494bbef2] model deployment ID: [xa68ad36c6722]
[INFO] [default] [2023-05-24T20:31:42.037Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2023-05-24T20:31:42.584Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 546 ms
[INFO] [streamMessages] [2023-05-24T20:32:04.565Z] message 0 returned. finish reason: [null]
[ERROR] [streamChoices] [2023-05-24T20:32:04.568Z] Error parsing extraData: data: {"id":"chatcmpl-7JpR0yrc4SQ24eXlqt1QGl0OATbLH","object":"chat.completion.chunk","created":1684960302,"model":"copilot-chat","choices":[{"index":0,"finish_reason":
[INFO] [streamChoices] [2023-05-24T20:32:04.570Z] request done: headerRequestId: [5d51c815-caa9-492a-a329-8dbda3c6ea20] model deployment ID: [xa68ad36c6722]

**Comment by 1nVitr0** [comment]
I have had similar issues where I asked copilot to insert a single line and it duplicated the entire block

**Comment by mark-wiemer** [comment]
Note I can't share code publicly as it's Microsoft-proprietary, but I may be able to share it through Microsoft-FTE channels. Contact @mwiemer on Teams if you need the exact code snippet.

**Comment by alexdima** [comment]
@mark-wiemer I reached out to you on Teams.

**Comment by alexdima** [comment]
We can't repro the issue anymore.
