### ISSUE TITLE
Default context in chat references #editor

### ISSUE THREAD

**Issue by wolfsilver** [microsoft/vscode-copilot-release#1120]
- VS Code Version:1.88.0
- OS Version: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.88.0 Chrome/120.0.6099.291 Electron/28.2.8 Safari/537.36
- Logs:

> https://code.visualstudio.com/updates/v1_86#_default-context-in-chat
> We are experimenting with not including code in the viewport by default, but only including code that is selected.

Default context changed from 1.86. But now it references the `#editor` context.

Steps to Reproduce:

1. chat with copilot
2. 
![image](https://github.com/microsoft/vscode-copilot-release/assets/2452450/4d81f7a2-d99c-4d14-b2f9-1459cf60d40d)

**Comment by roblourens** [comment]
This experiment was reverted, so it will bring in editor context by default
