### ISSUE TITLE
Github Copilot is causing unresponsive behaviour in the editor

### ISSUE THREAD

**Issue by ChrisSimLeg** [microsoft/vscode-copilot-release#1122]
Type: <b>Bug</b>

Using the Copilot Chat feature results in a constant loading spinner next to the cursor, indicating to me that the editor is stuck on something. 

Using any editor feature, like renaming a variable, after chatting with the Copilot results in an ~3min long loading bar where nothing is happening.
After those 3min, the editor recovers and works properly again.

I assume there is some process running in the background which is stuck, running into a timeout eventually.

Extension version: 0.14.0
VS Code version: Code 1.88.0 (5c3e652f63e798a5ac2f31ffd0d863669328dc4c, 2024-04-03T13:26:18.741Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 7730U with Radeon Graphics      (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|14.80GB (1.00GB free)|
|Process Argv|--crash-reporter-id d14fc530-a1b5-41cc-a4cb-5608e0948585|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
bdiig495:31013172

```

</details>

**Comment by roblourens** [comment]
I haven't seen this and am not sure how chat would be related to these editor features. Can you try disabling other extensions, maybe sharing a screen recording, or checking for processes that are using high cpu when this happens?

**Comment by ChrisSimLeg** [comment]
Forgot to update this. I found that this issue was only occurring in a specific repository. Doing a fresh clone of that repository fixed this for me.
