### ISSUE TITLE
Update Issues, Repository links in `package.json` 

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-copilot-release#113]
When viewing the extension on the Marketplace, the `Issues` and `Repository` links are:

https://github.com/community/community/discussions/categories/copilot

Should be pointing to this repo:

https://github.com/microsoft/vscode-copilot-release/issues
https://github.com/microsoft/vscode-copilot-release

**Comment by roblourens** [comment]
Looks like this was fixed
