### ISSUE TITLE
Save chat for a future query

### ISSUE THREAD

**Issue by almendieta** [microsoft/vscode-copilot-release#1132]
I think it would be great Copilot have a way to save a chat history to future querie. Today I lost all one month queries trying to open chat window in VS Code, close one of the windows... and this contained ALL chat history.

**Comment by roblourens** [comment]
You can click the history button at the top of the view to open a previous chat. Also, chat threads are saved per-workspace folder

**Comment by almendieta** [comment]
It's not a thing as Previous chat in vs code, and in my experience, once
you close a chat it is lost forever.



-----------------------------------------------------------------------------
Si vas a reenviar este mensaje, ten en cuenta lo siguiente:
            1..- Borra la dirección del remitente así como cualquier otra
dirección que aparezca en el cuerpo del mensaje.
            2.- Protege las direcciones de los destinatarios colocando las
mismas en la línea CCO (COPIA OCULTA), de esta forma evitamos los mensajes
SPAM.
