### ISSUE TITLE
Supporting Copy Select Scrolling Vertically 

### ISSUE THREAD

**Issue by ImadBouirmane** [microsoft/vscode-copilot-release#1134]
Hi Team 
I would like to send this feature I already checked here if its already been sent !

I just saw that I can't scrolling vertically when I'm selection code but horizontally its work fine as you will see in the video recoded below.

https://github.com/microsoft/vscode-copilot-release/assets/8468212/193971d4-e894-4bf5-938d-35c71deb764d

Regards with big thanks for this powerful tool 🙏

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/462
