### ISSUE TITLE
Inline /explain ignores user input

### ISSUE THREAD

**Issue by mzschwartz5** [microsoft/vscode-copilot-release#1137]
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.2.0

- Logs:

Steps to Reproduce:

1. Highlight line of code in editor
2. Cmd + i 
3. /explain
4. Enter some question or text into /explain
5. Result: note how copilot ignores the user input and simply explains the code with no further context

Previously, copilot used to consider user input when answers inline-explain questions. For that matter, copilot no longer even appears to restrict its explanations to the text highlighted inline. It explains the whole file.

**Comment by Trevor-Warthman-2** [comment]
Same issue here!

**Comment by luna-moonfang** [comment]
vscode back to 1.87 and it works.

**Comment by andreality92** [comment]
Same issue here! Using version 1.89

**Comment by joyceerhl** [comment]
Thanks for your patience, I cannot repro this behavior. Does this still occur for you?

**Comment by mzschwartz5** [comment]
I have since stopped using inline explain much as a result of this issue, but in my limited testing just now, it does appear to work again.
