### ISSUE TITLE
Doesn't work for Long messages

### ISSUE THREAD

**Issue by Shoriful732** [microsoft/vscode-copilot-release#1141]
In the Github copilot chat. at first it was really powerful and worked fine, but now it simply does not work for longer messages. it shows "unhandled status from server: 400 bad request: no user message, only message was a "system" message" If I write a long message.

**Comment by cfloressuazo** [comment]
Same here, for relative large messages I get the same message: `unhandled status from server: 400 bad request: no user message, only message was a "system" message`

**Comment by macluiggy** [comment]
a mi tampoco me funciono reflechuchadetumadrehijueputa

**Comment by ITorrenteP** [comment]
Same thing here.

**Comment by jjn1056** [comment]
me as well, anyone know the limit??

**Comment by fisforfaheem** [comment]
Exactly, why is htis happeing, the FREE CHATGPT 3.5 has more better response than this and better history

**Comment by lramos15** [comment]
I believe this has been fixed. Can anyone test again and confirm?

**Comment by fisforfaheem** [comment]
No, still exist it forgets long text just 300+ lines code

**Comment by lramos15** [comment]
Ok so no error, it just says that it doesn't have access?

**Comment by fisforfaheem** [comment]
Both, sometimes when u slect long text for some reason, and sometimes
without even selecting if the code is a bit large

**Comment by ArCiGo** [comment]
I'm having the same issue. Is there any update on this?

**Comment by rheimsothdecoit** [comment]
Still the same problem!

**Comment by SandroG1977** [comment]
Same problem. I'm thinking buy ChatGPT Pro and change copilot for GPT

**Comment by fisforfaheem** [comment]
Why doesnt the copilot understand my full project ??? as it so claims??

**Comment by SandroG1977** [comment]
Finally Moved to Bitso, it´s extremely better than Copilot

**Comment by fisforfaheem** [comment]
copilot is so dumb that it gives  a general implementation even if we give it context, with billions in revenue they cant increase the context

**Comment by lramos15** [comment]
We've increased the token budget quite a bit, so you should not run into this. Hope that helps, happy coding!
