### ISSUE TITLE
Account not linked to my enterprise account

### ISSUE THREAD

**Issue by tapantor** [microsoft/vscode-copilot-release#1142]
Type: <b>Bug</b>

Log in to GitHub from VS Code, I have no access to Copilot. But I use the same email to login as my Enterprise Account that has License for GitHub Enterpsie Cloud <enterprise> + Copilot. But it seems to have lost the link from Github to my enterprise Account

Extension version: 0.14.1
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (18.76GB free)|
|Process Argv|--crash-reporter-id 1ddc5285-bfbe-46dd-ac9b-f83093817d67|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
724cj586:31013169

```

</details>

**Comment by TylerLeonhardt** [comment]
@tapantor are you talking about multiple GitHub accounts here or just one? "I use the same email to login as my Enterprise Account"

Do you have 2 different GitHub accounts?

**Comment by tapantor** [comment]
I don't know. My subscription was terminated and then I had to regain access to copilot. At that point maybe a new GitHub account was created by mistake. But the email used is the same as my enterprise account. So could there be a different account with the same email?

Torbjörn Tapani
Developer
Tietoevry Care, Sweden

**Comment by tapantor** [comment]
Problem solved. User error. Had failed to rejoin organization in GitHub after account was reinstated.
