### ISSUE TITLE
Laggy chat input on Ubuntu

### ISSUE THREAD

**Issue by L-Sypniewski** [microsoft/vscode-copilot-release#1144]
I've noticed that recently the chat input has become laggy on Ubuntu 23.10. I also use the extension on macOS and it works smooth as it used to be.
The problem persists event after disabling all the extensions except Copilot Chat without any project being open.

- VS Code Version: 1.88.1
- OS Version: Ubuntu 23.10
- Logs:

Steps to Reproduce:

1. Open chat window
2. Type/delete anything in the chat input

**Comment by roblourens** [comment]
Is this still an issue in the latest? Can you explain more about what you mean by "laggy"?

**Comment by L-Sypniewski** [comment]
Sorry for the late reply. What I meant is there's a noticeable delay whenever you type/remove text

**Comment by roblourens** [comment]
Still in the latest? Does the same happen in any other input box in vscode?

**Comment by roblourens** [comment]
You could try capturing a perf trace, Help > Toggle Developer Tools, use the Performance tab and Record while reproing the issue.
