### ISSUE TITLE
Right click on highlighted text in chat copies entire response.  

### ISSUE THREAD

**Issue by synaption** [microsoft/vscode-copilot-release#1146]
When I right click on highlighted text in chat it copies the entire response instead of just the highlighted portion.  Ctrl+c functions as intended.  

- VS Code Version: 1.88.1
- OS Version: windows 11

Steps to Reproduce:

1. Ask copilot a question in chat.  
2. Highlight part of it's response.  
3. Right click to copy.
4. Right click to past somewhere.  
5. Be disappointed that it copied the entire response instead of just the highlighted portion.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/416
