### ISSUE TITLE
Request: Add default language setting for command output

### ISSUE THREAD

**Issue by Fukuhara-Masaki** [microsoft/vscode-copilot-release#115]
Hello to all the developers of GitHub Copilot Chat. I am a Japanese speaker who is using this chatbot, and I have a request to add a default language setting to change the output language of commands.

Currently, when using commands such as /explain, the output language may be in English at first. As a Japanese speaker, the current specification is a bit inconvenient. However, in our community, there are people who have English as their second language or who cannot understand English. Therefore, by adding a default language setting, users can receive output that is tailored to their language.

By adding a default language setting, users can receive output in their language every time they execute a command. This will make it easier for users to understand and use the commands.

For these reasons, I would be grateful if you could add a default language setting. Thank you very much.

**Comment by roblourens** [comment]
We now have this setting: `github.copilot.chat.localeOverride`
