### ISSUE TITLE
Don't know how much Million is Billion for God Sake.

### ISSUE THREAD

**Issue by Rudresh-sisode** [microsoft/vscode-copilot-release#1150]
Today I asked copilot how much million is one billion,
see the picture what is copilot is saying, this is 6 grade question in india.
Do your study wisely as I'm using copilot and my 10 dollar is much compare to indian rupees.
SHUT DOWN if your copilot's model is not capable for such elementary question,
Oohh internally you guys are using OpenAI's API, I see.
Alass!!!
![Copilot issue - 2](https://github.com/microsoft/vscode-copilot-release/assets/52784991/6b879fc5-92eb-4d93-9cc6-7fab681724f0)

**Comment by Rudresh-sisode** [comment]
![google's answer](https://github.com/microsoft/vscode-copilot-release/assets/52784991/92686f0c-d28d-4c98-bec6-d4081182d5fe)

see google's answer

**Comment by lramos15** [comment]
Just say it's not right and it will fix it for you. It's meant to assist with programming problems. It can write a script to calculate this for you 
<img width="554" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/36d1739b-c38c-4c0d-aea0-3d8d1206d7c4">
