### ISSUE TITLE
"All promises were rejected" error when using the `@workspace` tag

### ISSUE THREAD

**Issue by DylanDevelops** [microsoft/vscode-copilot-release#1153]
- VS Code Version: 1.88.1
- OS Version:
According to VSCode: Darwin arm64 23.4.0
Main OS: MacOS (Sonoma) 14.4.1 (23E224)
- Logs:

Steps to Reproduce:

1. Go to the https://github.com/desktop/desktop repository.
2. Ask a question passing in the @workspace argument
3. See results.

I had previously opened an issue in which the issue was closed saying that it was fixed but I'm getting this error again.

Refer to #842.

Screenshot:
<img width="356" alt="Screenshot 2024-04-23 at 5 07 30 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/48571264/fea0c8b8-8925-4ef4-9a42-c5b4c8f3b97a">

**Comment by TylerLeonhardt** [comment]
@DylanDevelops I believe we've done some work in this area, at the very least better logging, in the latest insiders. Can you grab [VS Code Insiders](http://code.visualstudio.com/insiders/) along with the Copilot Chat pre-release version (you can switch in the Extension pane in VS Code) and give this another try?
