### ISSUE TITLE
Using copilot chat to create the workspace structure and files does not work

### ISSUE THREAD

**Issue by github-cloudlabsuser-073** [microsoft/vscode-copilot-release#1154]
the prompt that we used: "@workspace can you create a workspace for an expense tracker application with all files and code"

it resulted in copilot answering that he cannot create files on the local file system

- VS Code Version: 
Version: 1.87.0 (system setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.20348
- OS Version:
Microsoft Windows [Version 10.0.20348.2322]

Using the /new command in addition to @workspace caused an incomplete workspace to be created
After installing a VS Code Update it worked

**Comment by mjbvz** [comment]
Yes `/new` is the way to do this. It provides specialized prompts and UI for creating a workspace
