### ISSUE TITLE
Unit test contents repeated.

### ISSUE THREAD

**Issue by ygqygq2** [microsoft/vscode-copilot-release#1157]
For example, if a file has multiple functions, after generating a unit test file for function one, select another function, and then generate a unit test, it will copy all the previous contents, cause the previous content is repeated. The experience was very poor and I wanted to improve.

**Comment by ulugbekna** [comment]
Hi @ygqygq2 ! 

Thank you for feedback! 

We're working on improving this. Stay tuned :-)
