### ISSUE TITLE
React Native environment setup

### ISSUE THREAD

**Issue by seamusa** [microsoft/vscode-copilot-release#1160]
There should be an option within copilot to setup development environments. In order for me to build a react native, I have to vis the react native website, read the reqs, and install all dependencies, and setup all environment variables. Copilot should already provide some automated script, or commands to install from my unique environment.

Perhaps this can be integrated with windows copilot. Where the dev needs can be passed to windows copilot. Windows copilot can then setup the development environment where vscode can focus on the dev experience?

**Comment by TylerLeonhardt** [comment]
Solving with AI: Have you tried out the `@workspace /new` command in chat? You might have your luck with chatting with that:
![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/39ba9c0f-4073-4aca-b550-870be66d49ff)

Solving without AI: Have you considered just crafting a devcontainer.json using https://containers.dev and then reusing that for all your projects? Looks like there is some existing flows out there for React Native + Devcontainer: https://dev.to/animusna/dev-container-for-react-native-with-expo-f7j
