### ISSUE TITLE
[auth] Invalid copilot token: missing token: 403

### ISSUE THREAD

**Issue by Nick90NL** [microsoft/vscode-copilot-release#1162]
- VS Code Version: 1.88.1 
- OS Version: Windows 11 Pro

Hello, i have issues regarding the copilot extension within VSCode, and i dont know why and what to do. I have emailed support several times. Can someone help me out? i had a (verified) student account.

This is the diagnostic rapport:

## Copilot

- Version: 1.184.0
- Build: prod
- Editor: vscode/1.88.1

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Node setup

- Number of root certificates: 141
- Operating system: Windows_NT
- Operating system version: 10.0.26100
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200 - 
- copilot-proxy.githubusercontent.com: HTTP 200 - 
- api.githubcopilot.com: HTTP 200 - 
- default.exp-tas.com: HTTP 200 - 

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: false
- Is `mac-ca` installed?: false

## Authentication

- GitHub username: Nick90NL

Error:
2024-04-26 10:11:45.886 [info] [auth] Invalid copilot token: missing token: 403 
2024-04-26 10:11:46.120 [error] [auth] Extension activation failed: "Contact Support. You are currently logged in as Nick90NL."

**Comment by lramos15** [comment]
The only thing you can do in this case is contact support. We cannot help you here in the public GitHub issues.
