### ISSUE TITLE
Showing selection reference when it was not used

### ISSUE THREAD

**Issue by MattAndrewsUSA** [microsoft/vscode-copilot-release#1164]
<img width="193" alt="GhCpScreen" src="https://github.com/microsoft/vscode-copilot-release/assets/65749612/e77e081c-a5cd-4caa-97b1-b4e896228020">

VSCode Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 22.5.0

macos 13.4.1 

GitHub Copilot v1.7

Steps to Reproduce:

1. Highlight code in editor and ask a question in GitHub Copilot Chat. It often works and is helpful.
2. Repeat exact same steps from above and sometimes, even after 5 straight correctly referenced questions/suggestions I receive "I'm sorry, but without the actual content of the main.js file, I can't provide the order in which the functions are called. Could you please provide the content of the file or the specific code snippet you're interested in?" or something similar,  while the chat shows the specific lines being referenced. See above screenshot. I've re-installed the extension and cleared the chat history multiple times and can find no discernible pattern as to when it works or not.

**Comment by roblourens** [comment]
You've selected 400 lines of code, which may not fit in our context window sometimes, depending on the length of the query and other things (I need to make sure that the selection takes precedence over conversation history)

Also, we will make a change to not show you that reference when it was not actually used in the prompt. I'll keep this open to track that.
