### ISSUE TITLE
'undefined' when clicking participant name in /help

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#1165]
- Run `/help`
- Click a participant name
- Get 'undefined'

<img width="244" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/323878/c268b021-c199-4c72-a7ed-8ad21be0325a">

**Comment by rzhao271** [comment]
I'm still seeing this in the current RC. Will likely have to wait for a newer one.
