### ISSUE TITLE
Copilot Chat icon does not display in left panel despite having installed the Github Copilot Chat extension

### ISSUE THREAD

**Issue by dooDad169** [microsoft/vscode-copilot-release#1167]
Type: <b>Bug</b>

1.) Open Visual Studio Code.
2.) Click on the Extensions icon in the left panel.
3.) Install the Github Copilot Chat extension in Visual Studio Code.
4.) Observe the left panel.

Expected: The Github Copilot Chat icon should appear in the left panel.
Actual: The Github Copilot Chat icon does not display.

Extension version: 0.14.1
VS Code version: Code 1.88.1 (Universal) (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id e452ad78-d383-4a01-ac57-9c16bd7dabbf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
fegfb526:30981948
bg6jg535:30979843
ccp2r6:30993542
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
chatpanelc:31018788
dsvsc021:30996838
9c06g630:31013171
pythoncenvptcf:31022791
dwnewjupytercf:31035177

```

</details>

**Comment by dooDad169** [comment]
<img width="1680" alt="Screenshot 2024-05-02 at 8 47 04 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/162342670/ee5e8493-fb56-42b9-a09f-c5a7fe03e00e">
![Screenshot 2024-05-02 at 8 48 09 AM](https://github.com/microsoft/vscode-copilot-release/assets/162342670/8e7c2aca-0b0e-4679-ad8e-ddf1d6baa9d7)

**Comment by dooDad169** [comment]
https://github.com/microsoft/vscode-copilot-release/assets/162342670/dbf01e2b-ebf3-44ad-91b4-bfce42f2750b

Okay, now the icon appears, but CoPilot Chat keeps failing to load.

**Comment by dooDad169** [comment]
Hello @TylerLeonhardt,

I've just been notified that Daniel Clemens may be our contact for getting our license.

**Comment by TylerLeonhardt** [comment]
Hi @dooDad169, have you had luck getting ahold of your contact?
