### ISSUE TITLE
r.report is not a function

### ISSUE THREAD

**Issue by adhnanshereef** [microsoft/vscode-copilot-release#1169]
- VS Code Version: GitHub Codespace
- OS Version: GitHub Codespace
- Logs: r.report is not a function

Problem:-
When I ask something, it shows "r.report is not a function".

**Comment by roblourens** [comment]
Please make sure you have updated to the latest version of the Copilot Chat extension, thanks

**Comment by kwokcb** [comment]
If it helps others: It's really not obvious but that I needed to "restart" the extension. You don't see unless you go to the extensions list and see a button asking you to do so. I doesn't seem to restart even if you restart vscode.
