### ISSUE TITLE
/Tests outputs nonsense and never stops streaming

### ISSUE THREAD

**Issue by malantin** [microsoft/vscode-copilot-release#1171]
Nonsense results when using /tests and it sometimes never stops streaming code.

![Image](https://github.com/microsoft/vscode-copilot-release/assets/5029466/26dce6e9-7525-4ea1-a18a-53e130a7fe5b)

- VS Code Version: 
Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:15:54.732Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Copilot: v1.186.854 (pre-release)
Copilot Chat: v0.15.2024043005 (pre-release)
- OS Version: GitHub Codespaces

Steps to Reproduce:

`1. /tests -> @workspace /tests`

**Comment by mjbvz** [comment]
Looks like an old nightly build. Should already be fixed
