### ISSUE TITLE
Inconsistent Cursor Position When Navigating Through History Using Up and Down Keys

### ISSUE THREAD

**Issue by sunliangqin** [microsoft/vscode-copilot-release#1172]
Steps to Reproduce:

1. Focus on the input box on the copilot view
2. Press up arrow key a few times
3. The previous queries will be populated, the cursor is at the beginning of the text.
4. Press down arrow key a few times
5. The next queries will be populated, but the cursor is at the end of the text.

Expectation:
The cursor position should be consistent at the end of populated text.

**Comment by roblourens** [comment]
That standard works well in single-line input boxes, but for multi-line inputs in vscode, I think it makes sense to say that the cursor needs to be at the very first character in the response to navigate back, and then it stays in that first position while navigating back, and it needs to be in the last position while navigating forward, and stays there.
