### ISSUE TITLE
Have co-pilot add links to vscode .json files when appropriate in answers

### ISSUE THREAD

**Issue by chris-lemurian** [microsoft/vscode-copilot-release#1174]
I would like co-pilot suggestions to include "links" when pointing to files to edit.

Here is my use-case example.

I asked co-pilot how to fix my test discovery.  The suggestions are generally good.  However, at step 3, it say to do something to my "settings.json" file.  Fine suggestion.  However, it doesn't tell me where to find the settings.json file in my .vscode directory.  Ideally, it would have made "settings.json" in the suggestion a link that would tell vscode to open that file for editing.  Then I could paste the suggestion in easily.  Now, I have to ask co-pilot how to edit the settings.json file.  An extra step.  An extra query.

**Comment by mjbvz** [comment]
The latest insiders builds of the extension create links for file paths

If you're still not seeing this working, please share an example workspace + question where you'd expect a llink

**Comment by chris-lemurian** [comment]
Thanks, I will try an insiders build.  Normally, i just use the stock
release, but I can look to see if this works like I hope, and presume that
it will eventually make it into the stock release.
