### ISSUE TITLE
The chat looses context and also display empty spaces and not work as intended

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1176]
It's sad to see after just 10 12 queries the chat stop working and gives weird erors and have to restart the VSCODE and even after daily updates this main issues not being solved why?

**Comment by lramos15** [comment]
What are the weird errors?

**Comment by fisforfaheem** [comment]
Startts explaining code instead of answering

**Comment by lramos15** [comment]
So you're asking it to write some code and it starts explaining it instead? You're not getting any actual exceptions

**Comment by fisforfaheem** [comment]
I select a code, and ask some questions... instead of following it gives
what the code does and stops
