### ISSUE TITLE
Support Dart 3.0 lanaguage, as current suggestions are based on dart lang 2.0 which is very old (3 years) and obeselte

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1177]
Dear developers kindly give dart 3.0 accepted suggestions and answers

**Comment by zivshek** [comment]
and Flutter, it's based on 2.8.1, while the current version is 3.19.5. @digitarald

**Comment by lramos15** [comment]
A model upgrade will fix this. Tracked in https://github.com/microsoft/vscode-copilot-release/issues/560

**Comment by fisforfaheem** [comment]
GitHub has no idea how frustrating it is that we get 2021 suggest

**Comment by fisforfaheem** [comment]
How come thry can say its not planned

**Comment by lramos15** [comment]
That's just GH's way of saying it's a duplicate of another issue

**Comment by fisforfaheem** [comment]
Oh, but i am asking for this for last 8 months now, why there has been no
progress at all, flutter version 3 in 2022 changed everything... Now it's
2024. And i get mostly 2021 era flutter
2.18 era answes
