### ISSUE TITLE
Regression: Pre-release Commit Message generation repeats old commit messages

### ISSUE THREAD

**Issue by nevercast** [microsoft/vscode-copilot-release#1183]
- VS Code Version: 1.89.0
- Copilot: v1.186.856 (pre-release)
- Copilot Chat: v0.15.2024043005 (pre-release)
- OS Version: Windows 10

Steps to Reproduce:

1. Write some commits in a project, use the Copilot Commit Message Generation as much as possible ✨
2. Notice that the commit messages deteriorate to uselessness, just repeating previous changes, becomes unrelated to the diff. 

[A recent change](https://code.visualstudio.com/updates/v1_88#_commit-message-generation-improvements) to VSCode added commit message history to the commit message completion functionality. An excellent idea, however, I suspect the prompt is poor, or there is an underlying bug. (Leaky LLM abstractions are pain, I get it.)

When I'm generating commit messages, I expect the commit to discuss the change, but the behaviour I'm now seeing is that the generated message just repeats aspects of the previous messages. 

I'd like to see an option to either:
1. Disable commit history included in the prompt
2. Modify the prompt
3. The prompt resolved by the copilot team.

**Comment by senkenn** [comment]
Same on v1.90.

**Comment by digitarald** [comment]
We since then updated the model. Can you comment if this still happens?
