### ISSUE TITLE
overlapping text in terminal

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode-copilot-release#1185]
Type: <b>Bug</b>

Steps:
open new terminal
immediately paste in a command
then the shell starts up (I do have a echo command in my zshrc)
the bug now occurs because the text I pased and the ghost text for the terminal overlap

Extension version: 0.16.2024050601
VS Code version: Code - Insiders 1.90.0-insider (Universal) (ccba2fc85c14bedeef5a72b7ebc0bde9b0e91948, 2024-05-06T08:08:04.226Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.68GB free)|
|Process Argv|--log error --crash-reporter-id 2c70a231-86d5-41c1-a744-69e0d9c3630e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vstes627:30244334
vsc_aa:30263845
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
ccp2r6:30958154
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
724cj586:31013169
a69g1124:31018687
dvdeprecationcf:31036533
pythonprt:31036556
dwnewjupytercf:31035177

```

</details>

**Comment by eleanorjboyd** [comment]
<img width="1724" alt="Screenshot 2024-05-06 at 11 54 16 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/26030610/63f9ded2-7db0-48be-8e41-04bf66f44bb9">

**Comment by Tyriar** [comment]
Stale, should be fixed
