### ISSUE TITLE
simple copilot chat mode

### ISSUE THREAD

**Issue by Aoyia** [microsoft/vscode-copilot-release#1191]
I want the chat function to support multiple sessions and keep session records, just like gpt3.5. I can define my own prompts and respond quickly without collecting context, which helps to quickly write some simple functions, such as:
I enter the function description, please return a function name, require camel case naming, and start with test.

Most of the time I will ask to name it like this, but every time I have to switch to gpt, and the built-in copilot chat is not very useful because it always collects data and then returns the results slowly, and there is no prompt. Session recording. Request to add such a simple copilot chat that remembers sessions, does not collect contextual information, and supports custom prompts

If it can be adopted, it will solve the steps for me to switch to gpt, improve the usage of copilot chat, and you can collect the developers' prompts and understand the developers' needs.

**Comment by roblourens** [comment]
You can switch to previous sessions by using the "Show Chats" command, it has a button at the top of the chat view. Does that help?

Besides that, I don't really understand your request, please explain some more
