### ISSUE TITLE
Getting r.report is not a function

### ISSUE THREAD

**Issue by VincentX33** [microsoft/vscode-copilot-release#1194]
Type: <b>Bug</b>

Just try to ask a question to chat, you get
```
r.report is not a function
```
as the output, with a red x icon

Extension version: 0.14.1
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1125G4 @ 2.00GHz (8 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (1.17GB free)|
|Process Argv|--crash-reporter-id 3d1bb688-77ad-4e07-bf18-e82d3c969bf6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Please make sure Copilot Chat is updated to the latest version, 0.15
