### ISSUE TITLE
Github copilot chat stop working on Ubuntu 22.04 on VSC 1.89.0

### ISSUE THREAD

**Issue by chiddekel** [microsoft/vscode-copilot-release#1196]
GitHub  copilot chat on VSC on Ubuntu 22.04 stop responding - even icon on left sidebar of VSC to reaper hanging the VSC.

**Comment by tstandley** [comment]
It's broken for me too on a mac. Downgrading to 1.188 sorta fixes the issue, but it's very slow now.

**Comment by Doctorbal** [comment]
Related issue: https://github.com/microsoft/vscode-copilot-release/issues/1200

**Comment by lramos15** [comment]
Can you attach your logs via `CTRL + SHIFT + U` -> `GitHub Copilot Chat`

**Comment by chiddekel** [comment]
> Can you attach your logs via `CTRL + SHIFT + U` -> `GitHub Copilot Chat`

Before any logs attempt - 
any interaction with starting GitHub Copilot Chat -
stop vsc main window.

**Comment by lramos15** [comment]
What is this dialog? 

Please attach logs + screenshots. Your description is very vague. Also VS code version + extension version
