### ISSUE TITLE
Copilot chat always displays "Oops, your response got filtered. Vote down if you think this shouldn't have happened."

### ISSUE THREAD

**Issue by JulianTRose** [microsoft/vscode-copilot-release#1197]
- VS Code Version: 1.82.2
- OS Version: MacOS 

No matter which query I enter I always get the following response by the copilot chat in VS "Oops, your response got filtered. Vote down if you think this shouldn't have happened.". 

In PyCharm the Chat works without error and I have tried reinstalling the extension in VS multiple times.

Does anyone know what the root issue for this might be?

<img width="309" alt="Screenshot 2024-05-10 at 17 00 09" src="https://github.com/microsoft/vscode-copilot-release/assets/165418018/3cd7caf2-89bb-4e94-ad5c-09ead33cbd10">

**Comment by lramos15** [comment]
What version of copilot chat are you using? YOu may need to update VS Code and Copilot Chat

**Comment by alexandrosandre** [comment]
Updated both, still happening. Also tried logging out and in again.

**Comment by lramos15** [comment]
@alexandrosandre Please include your copilot chat logs via `CMD / CTRL + SHIFT + U` -> `Copilot Chat`

**Comment by JulianTRose** [comment]
> Please update VS Code and Copilot Chat. You're on an older no longer supported version

Thank you, this fixed the issue. My VS Code was still in the download folder and therefore could not be updated
