### ISSUE TITLE
Wikipedia-like Clickable Links

### ISSUE THREAD

**Issue by manavsu** [microsoft/vscode-copilot-release#1199]
Having a links in responses that forward to definitions in chat or as a bubble would be nice, i.e.
Given a response:

To get your local IP address on a Mac, you can use the ifconfig command in the terminal. Here's how:
`ifconfig | grep inet`

It would be useful be able to just click on the ifconfig or grep keywords to get a quick definition or at least automatically ask "what is grep?"

**Comment by Tyriar** [comment]
Good idea, marking as out of scope for now as we don't plan on working on something like this for the foreseeable future. The thing I'm stuck on thinking about this is how to implement such a feature without being too in your face, being expensive/wasteful (too many LLM requests) and how to not conflict with other features.

We have native vscode auto complete coming soon though which will have some information we can pull easily https://code.visualstudio.com/updates/v1_96#_terminal-completions-for-more-shells
