### ISSUE TITLE
Feature Request: Conversation Saving and Loading as Markdown Files

### ISSUE THREAD

**Issue by dakurai** [microsoft/vscode-copilot-release#12]
I would like to request a new feature for Copilot Chat that enables users to save their current conversation as a markdown file. This feature would provide a convenient way to store and retrieve conversations for future reference or continuation.

### Save Conversation to Markdown File:

Introduce a new command or button that allows users to save their current conversation as a markdown file.
Upon initiating the save action, Copilot Chat should generate a markdown file containing the entire conversation history, including user inputs and AI responses.
The markdown file should follow a structured format that preserves the conversation flow, making it easily readable and shareable.
### Load Conversation from Markdown File:

Implement a functionality that enables users to load a previously saved markdown file to resume an old conversation.
Users should have the ability to select a markdown file from their local storage or provide a file path.
Upon loading the markdown file, Copilot Chat should populate the chat interface with the saved conversation, displaying it in the same format and sequence as originally saved.

Please consider implementing this feature as it would greatly enhance the usability and versatility of Copilot Chat, providing users with a practical solution to store, retrieve, and share conversations effortlessly. Thank you for considering my request.

**Comment by biiigwang** [comment]
I am looking forward to the completion of this feature. I have experienced a similar functionality in the `ChatGPT - Genie AI` plugin.

**Comment by roblourens** [comment]
This has been implemented using the chat export/import commands. However it is a JSON file, not markdown, because there is a bunch of metadata that we need to store and this is much easier.
