### ISSUE TITLE
Suggested response language based on the question language

### ISSUE THREAD

**Issue by Torvaldi** [microsoft/vscode-copilot-release#120]
I think that should be a great feature if suggested responses were based on the question's language.

- VS Code Version: 1.79.0-insider (commit f6be5461f8bc69013a605f5baea834651c6589fb)
- OS Version: Linux x86_64

Steps to Reproduce:

1. Ask anything to copilot in another language than English.
2. Check the suggested question that appears.

![copilotX](https://github.com/microsoft/vscode-copilot-release/assets/7703951/9f4841ad-60e4-4921-87c1-4d35ce288aa7)

**Comment by digitarald** [comment]
Works with locale override set:

<img width="1792" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/2ee33c5e-2713-436d-a987-4a9de657ddb4">
