### ISSUE TITLE
Last release just don't load

### ISSUE THREAD

**Issue by tchereau** [microsoft/vscode-copilot-release#1200]
Last release don't load, there is no icon in the stat bare, and there is no output.

- VS Code Version:  1.89.0
- OS Version: macOs 14.4.1 (23E224) with vscode connected via ssh to debian 12
- Logs: no logs in output.

Steps to Reproduce:

1. Install latest update to latest v1.189.0
2. Enjoy void..

How to solve:
Click the row on uninstall button and select v1.188.0

**Comment by Doctorbal** [comment]
Indeed. I am experiencing the same issues.

Latest Copilot release ~4h ago does not show the status menu and no output in the console log for this environment effectively not working:

- GitHub Copilot vscode version: v1.189.0
- VS Code Version: 1.89.1
- OS Version: Debian 12, Ubuntu 22.04 LTS (these are WSLv2 environments)
- Logs: no logs in output

Steps to Reproduce:

1. Install latest [GitHub Copilot vscode plugin](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot) on a WSLv2 instance running either Debian 12 or Ubuntu 22.04 LTS
2.  Ensure you log into GitHub to authenticate and validate Copilot login.
3. Load a simple file, e.g. `test.sh` and start typing to automatically enable auto completions
4. No output is seen.

Workaround (as already stated and validated on my end):

1. Downgrade to version v1.188.0 by selecting the extension in vscode -> Uninstall downwards carrot -> select `v1.188.0`.

v1.189.0 does appear to work on Windows OS (Win10) however...

**Comment by tstandley** [comment]
Count me in as well.

**Comment by roblourens** [comment]
This is the repo for the copilot chat extension, sounds like you're having trouble with copilot completions. You can report this at https://github.com/community/community/discussions/categories/copilot
