### ISSUE TITLE
Correct the way the Copilot extension is verifying chain of trust for proxy certificates

### ISSUE THREAD

**Issue by mtrimm-ercot** [microsoft/vscode-copilot-release#1201]
We are receiving "certificate has expired" when opening VS Code from the Github Copilot extension. We had another support ticket open for this issue that is now close: 2711036

The issue appears to be tied to the way the extension is validating the proxy certificate chain. Due to some expired CA certificates in our TRCA store the validation if failing. Removing a specific Issuing CAs certificates from the TRCA resolves the issue however this is not an easy workaround to implement enterprise wide due to the possibility of code signing certificates chaining back to the expired certificate chain of trust that is present in these certificates. It would seem that the extension is performing the validation in a way that is atypical for Windows applications as this is the only instance we have of this occurring. We would like to work with Github towards another resolution that does not require modifying our local certificate stores.

https://code.visualstudio.com/insiders/ -->

We would like chain of trust verification to use the currently valid Issuing and Root CA certificates when available as opposed to choosing the first certificate (or oldest) available as it appears to be doing at present.

**Comment by sazonovanton** [comment]
For me current version of Copilot started to ignore VSCode proxy settings.

**Comment by sazonovanton** [comment]
> I can't comment on previous versions but from the time we began using the Copilot extension that setting has had no effect. Overriding certificate verification isn't a long-term option for us given the ramifications; I would imagine that to be the case for many corporate users.

At least on v1.186.0 it is working

**Comment by chrmarti** [comment]
Expired certificates are ignored now.

**Comment by mtrimm-ercot** [comment]
Thank you.


***@***.***<http://www.ercot.com/>

Sean Trimm
Sr. Systems Administrator, IT Systems Reliability
2705 West Lake Drive | Taylor, TX 76574
O: 000-000-0000 | M: 210-952-7811

Confidentiality Notice: DO NOT FORWARD. The information contained in this e-mail message, and any documents attached, are privileged and confidential and are intended for the addressee only. If you have received this document in error, please notify the sender immediately and delete.
