### ISSUE TITLE
ERROR: Chat failed to load. Please ensure that the GitHub Copilot Chat extension is up to date.

### ISSUE THREAD

**Issue by RezaShamsipour** [microsoft/vscode-copilot-release#1202]
MY VS Code Version : 

Version: 1.89.1 (user setup)
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621

Logs Of Copilot Chat : 
[auth] Invalid copilot token: missing token: 403
" is not valid JSON)

Version of Copilot : 
1.190.0
Copilot Chat : 
0.15.1

**Comment by JoshMatthew** [comment]
Any updates on this? I am having the same issue

**Comment by RezaShamsipour** [comment]
yes, any update , problem stay 3 days ...

**Comment by MiladRST** [comment]
I am also having the same issue.

**Comment by T4st7** [comment]
Same issue here

**Comment by CamiloAntonio** [comment]
Same issue, any one know what it is?

**Comment by RezaShamsipour** [comment]
not yet ...

**Comment by justinschmidt-ventum** [comment]
I got the same issue on MacOS with latest versions of both Chat and Copilot

**Comment by lramos15** [comment]
I'm not seeing this on the latest insiders + pre-release. Please give it a try and let me know

**Comment by dataders** [comment]
@lramos15 I agree. I've opened with today's builds and the error is gone.

lucky you, a bug solved for free! 😸 

### Versions

Here's my before and after


| Software | Before | After |
|--------|--------|--------|
| VSCode | `2024-05-09T05:51:12.471Z` | `2024-05-13T12:40:11.489Z` |
| Copilot Extension | `1.193.0` | `1.194.883` | 
| Copilot Chat Extension | v0.16.2024051501 (pre-release) | `v0.16.2024051601 ` |
