### ISSUE TITLE
GPT-4o in Copilot

### ISSUE THREAD

**Issue by lyc280705** [microsoft/vscode-copilot-release#1211]
I want GPT-4o in Copilot Chat (better have Voice Model)

**Comment by fisforfaheem** [comment]
Much needed

**Comment by sam-moreton** [comment]
When GPT-4o?

**Comment by digitarald** [comment]
We'll update this issue as we get access to 4o, meanwhile please subscribe and add reactions.

To keep this issue focused on model update: If you got feature requests inspired by GPT-4o's new capabilities, please file a new issue.

**Comment by pidgeon777** [comment]
Also there is this topic here:

https://github.com/orgs/community/discussions/123670

**Comment by lyc280705** [comment]
Is Copilot using GPT-4o now?

**Comment by axeII** [comment]
I tried to ask copilot in vscode which GPT version it uses. I've got this answer:
```
I am using the GPT-4o version of OpenAI's GPT models.
```
So seems like copilot is already using GPT-4o model in vscode.

**Comment by hidaris** [comment]
> What about GitHub Copilot? Which model does it use? I'm talking about the Copilot autocomplete feature, not the chat function.

It's still 3.5, but it seems like Microsoft is experimenting with the 4o mini, so we might expect some upgrades in the future.

**Comment by lramos15** [comment]
Chat has been updated to utilize GPT-4o

**Comment by mcpdigital** [comment]
> GitHub Copilot Chat (v0.17+) has been updated to utilize GPT-4o, given you much faster responses with higher quality code: https://aka.ms/github-copilot-chat-gpt-4o

I've tried GPT-4o-mini for auto complete and it works fine, but in one day of basic coding it used 1.5 Million tokens and 1500 api calls. Daily cost about 25 cents. Maybe is still cheaper than the github copilot. The results were ok and fast.

**Comment by xilopaint** [comment]
> > GitHub Copilot Chat (v0.17+) has been updated to utilize GPT-4o, given you much faster responses with higher quality code: https://aka.ms/github-copilot-chat-gpt-4o
> 
> I've tried GPT-4o-mini for auto complete and it works fine, but in one day of basic coding it used 1.5 Million tokens and 1500 api calls. Daily cost about 25 cents. Maybe is still cheaper than the github copilot. The results were ok and fast.

@mcpdigital How have you managed to use GPT-4o-mini for autocomplete without GitHub Copilot?
