### ISSUE TITLE
How to disable semantic commit messages?

### ISSUE THREAD

**Issue by grooveshaker** [microsoft/vscode-copilot-release#1212]
I made an update just a few days ago and now when I use the “Generate commit message with Copilot” feature, I get the messages `chore:` and `feat:` in the commit message.
I am not a fan of this feature, but is there any way to prevent these messages from being output?
I have looked in past issues and looked in the settings but have not found a solution.
Thank you in advance.

My VSCode version is 1.89.1
GitHub Copilot version is v1.191.0

**Comment by jira-zz** [comment]
I'am experiencing the same issue.
Not sure if it is a bug or feature, but I don't like the change.

**Comment by digitarald** [comment]
Can you confirm that other commits in the repo you are working in are not using semantic commit formatting?

**Comment by grooveshaker** [comment]
Sure. There was a commit message generated using Copilot in the version just prior to the drafting of this issue.
Unfortunately, this repository is private, so the commits cannot be shared, but when these commits were soft reset and re-committed identically, the commit messages certainly did not contain semantic commit messages.
Am I right in saying that if I don't want to include semantic commit messages in a commit message, I must first manually edit the commit message, but at some point the semantic commit message will no longer be included?
Does this mean that Copilot is generating commit messages based on previous commit messages in addition to the staged changes?

**Comment by grooveshaker** [comment]
As it turns out, past commit messages do not seem to be affected.

When I tried it on my unpublished old repository, it outputs a commit message that contains those keywords, even though I had never written a commit message containing `chore` or `fix` before.
However, I am now wondering if it is inevitable because it is an LLM product, since chore may not be included depending on the contents of the commit.

However, considering that these commit messages were not included at all before, I have to assume that there must have been some changes due to the version upgrade.

**Comment by DEAD1SIDE** [comment]
I have the same Problem. Nobody wrote any commit message like that. I searched my codebase and the word "chore" comes up 0 times...

**Comment by grooveshaker** [comment]
I am a little disappointed that this ticket is not getting any support comments especially since Copilot is not just an open source but a monthly service.

It would be nice if there was an item that could set a pre-specified prompt for the commit message, like the Negative Prompt in Stable Diffusion, for example.

```json
{
    "github.copilot.promptsCommitMessage": {
        "semanticMessage": false
    }
}
```

**Comment by grooveshaker** [comment]
I made an operational error.

**Comment by kaishin** [comment]
I share the same opinion that this should controllable somehow. I would also to change the instruction to describe more what the commit is doing and less how it's doing it.

**Comment by lszomoru** [comment]
In the upcoming Copilot Chat extension release we have added support for custom instructions while generating commit messages. You can find more details about the feature in this comment - https://github.com/microsoft/vscode-copilot-release/issues/526#issuecomment-2509017787. Please give it a try and reopen this issue if custom instructions do not resolve this ask. Thanks!

**Comment by kaishin** [comment]
Thanks for the update @lszomoru!

**Comment by grooveshaker** [comment]
@lszomoru 
I appreciate the interesting change.
I wanted to try this change, but I am currently using GitHub Copilot v1.250.0.
Is there any way to use this change, even though it is not an option?
Or has this change not yet been released?

**Comment by lszomoru** [comment]
To take advantage of this functionality you have to install the latest version of the [Copilot Chat extension](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat).
