### ISSUE TITLE
Error: net::ERR_NETWORK_CHANGED 

### ISSUE THREAD

**Issue by ruralharry** [microsoft/vscode-copilot-release#1213]
- VS Code Version: 1.90.0-insider
- OS Version: sonama 14.5 (23F79)
- Logs: [extension] Error on conversation request: Error: net::ERR_NETWORK_CHANGED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/utility_init:2:9932)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)

Steps to Reproduce:

1. restart vscode
2. send message to copilot chat
3. no matter the VPN is ON/OFF

<img width="1459" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/103827197/0ff5cd2e-be49-466e-9855-6f17a28b02b2">

**Comment by alexdima** [comment]
@lramos15 This is https://github.com/microsoft/vscode-copilot/issues/4916
