### ISSUE TITLE
Problem regarding in ChatView Screen 

### ISSUE THREAD

**Issue by Amit10311** [microsoft/vscode-copilot-release#1214]
I want to mention that there is a problem with the Chat View. I can't resize it. It' very small. 

- VS Code Version: 1.89.1 
- OS Version:  Ubuntu 23.10 (Linu x64 6.5.0-28-generic)
- Logs: ChatView 

Steps to Reproduce:

1. ChatView, ask for code modification or code
2. The screen comes with very small view to check the changes. 

![Screenshot from 2024-05-14 17-35-14](https://github.com/microsoft/vscode-copilot-release/assets/20908007/cf632d6e-c7d6-4835-bf63-3762fb154880)

**Comment by jrieken** [comment]
This view can now be resized (in height) and is render full editor width

**Comment by Amit10311** [comment]
Can you please provide some information of the settings need for this.
