### ISSUE TITLE
Add Changelog to VS code marketplace with proper details, it not being udpate since version 1.7

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1215]
<img width="588" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/35878088/3700db07-e38e-411d-b5f1-3de7c0a151e3">

**Comment by fisforfaheem** [comment]
any updates

**Comment by ulugbekna** [comment]
The changelog on the screenshot comes from the inline-completions Copilot extension, not chat. Please, file the report here - https://github.com/orgs/community/discussions

**Comment by fisforfaheem** [comment]
Dear GitHub Team,

I am writing to suggest a valuable addition to the Visual Studio Code (VS
Code) extensions tab. As a developer who relies on extensions to enhance my
coding experience, I believe that including changelogs for all updates
would be a significant improvement.

Changelogs provide users with crucial information about the changes and
improvements made in each update. They allow us to stay informed about new
features, bug fixes, and potential compatibility issues. This transparency
is especially important for developers who rely on specific extensions for
their daily workflow.

In addition to enhancing the overall user experience, changelogs also play
a vital role in accessibility. By providing a clear and concise overview of
the changes, users with disabilities can quickly determine whether an
update addresses their specific needs or introduces any potential barriers.

I kindly request that you consider adding changelogs to all updates in the
VS Code extensions tab. This simple addition would greatly benefit the
entire developer community, including those with disabilities.

Thank you for your time and consideration.

Best regards,

Faheem Ahmad
