### ISSUE TITLE
Can't sign in to GitHub Copilot Chat in VS Code

### ISSUE THREAD

**Issue by peterbe** [microsoft/vscode-copilot-release#1217]
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z (1 wk ago)
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0

- Logs: ?? how?

**Steps to Reproduce**

1. Start the command palette
2. Type "copilot sign in"
3. Select "GitHub Copilot: Sign in to Chat"

**Expected result**

That I can sign in somewhere. That something happens. 

**Actual result**

Nothing happens. 

**Note**

- I *used* to have Copilot Chat
- I don't know when it disappeared and got "replaced" with a command palette to sign in
- I work for GitHub and can honestly not remember how I got Copilot Chat enabled in the first place
- My extension is up-to-date
- I do not know how to see logs for potential errors about being unable to open a browser or something

![Installed extension](https://github.com/microsoft/vscode-copilot-release/assets/26739/a8458351-f24e-4432-ae8e-4db7bca2d1dd)

**Comment by Mishalintech** [comment]
Similar problem. Used to work. Chat never produces a response and reinstalling has not helped.

**Comment by tomerbuber** [comment]
I also have a Similar Problem: [error] [auth] Extension activation failed: "network error"

**Comment by TylerLeonhardt** [comment]
@LUISRMENDOZA @Mishalintech @tomerbuber you all seem to be having issues with Copilot Completions not Copilot Chat...

Please take a look at the threads over in https://github.com/orgs/community/discussions/categories/copilot and open a new discussion if you don't think your issues are included.

**Comment by TylerLeonhardt** [comment]
@peterbe let's see if you're in the same boat... 

Click on Output and then choose GitHub Copilot and GitHub Copilot Chat and paste what you see in those here:

![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/9a63bb8c-a524-457f-9e9e-1089407f6f13)

**Comment by peterbe** [comment]
@TylerLeonhardt For "GitHub Copilot"
```
2024-06-05 20:59:39.415 [info] [fetcher] Using Electron fetcher, feature flag is enabled.
2024-06-05 20:59:39.438 [info] [auth] Sucessfully authenticated
2024-06-05 21:00:08.373 [info] [fetcher] Using Electron fetcher, feature flag is enabled.
2024-06-05 21:00:08.407 [info] [auth] Sucessfully authenticated
```

For "GitHub Copilot Chat"
```
2024-06-05 20:59:38.302 [info] [FetcherService] Using Helix fetcher
2024-06-05 20:59:38.302 [info] [gitExtensionService] Initializing Git extension service.
2024-06-05 20:59:38.302 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-06-05 20:59:38.302 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-06-05 20:59:38.302 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-06-05 20:59:38.626 [info] [auth] Logged in as peterbe
2024-06-05 20:59:39.774 [info] [chat] copilot token chat_enabled: true
2024-06-05 20:59:39.774 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-06-05 20:59:39.791 [info] [auth] Got Copilot token for peterbe
2024-06-05 20:59:39.792 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-06-05 20:59:39.792 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
2024-06-05 21:00:08.085 [info] [FetcherService] Using the Helix fetcher.
2024-06-05 21:00:08.085 [info] [gitExtensionService] Initializing Git extension service.
2024-06-05 21:00:08.085 [info] [gitExtensionService] Successfully activated the vscode.git extension.
2024-06-05 21:00:08.085 [info] [gitExtensionService] Enablement state of the vscode.git extension: true.
2024-06-05 21:00:08.085 [info] [gitExtensionService] Successfully registered Git commit message provider.
2024-06-05 21:00:08.085 [info] [auth] Logged in as peterbe
2024-06-05 21:00:08.539 [info] [chat] copilot token chat_enabled: true
2024-06-05 21:00:08.539 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-06-05 21:00:08.554 [info] [auth] Got Copilot token for peterbe
2024-06-05 21:00:08.555 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-06-05 21:00:08.555 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.
```

Nothing in this Output panel is appended when I use the command palette to try to sign in


![Command palette](https://github.com/microsoft/vscode-copilot-release/assets/26739/c07732da-8ce7-40bf-b2d7-dbae2d8d909c)

**Comment by TylerLeonhardt** [comment]
Sorry for the delay @peterbe, I was on vacation. Are you still having issues here?

**Comment by peterbe** [comment]
> Sorry for the delay @peterbe, I was on vacation. Are you still having issues here?

Yes. Nothing's changed since my last comment. 

Thank you for checking in! I hope we can figure this out because many others might be experiencing it and missing out.

**Comment by bulat15g** [comment]
I am facing the same error. Autocomplete works, but the chat doesn’t.

**Comment by TylerLeonhardt** [comment]
@peterbe We've just released VS Code 1.92 & Copilot Chat 0.18. (may take a moment for the build to be available)

1. Can you try with that? It has some auth related fixes that I made.
2. If that doesn't work, can you grab the pre-release version of Copilot Chat (0.19.x)? I've pretty much re-wrote the whole auth stack in it...

**Comment by Trewaters** [comment]
I am also unable to sign in using the Github chat extension. This has happened for me at work yesterday, now at home on my personal account. It started yesterday. I have tried to uninstall, sign out/in again. But anyway I try even with a PAT shows a failed login. I can login to the Github website so my credentials are good.

I was using the release v0.18.1 then tried pre-release but the issue persist.

Any ideas?

![Github chat error-redacted](https://github.com/user-attachments/assets/842d089f-a8bc-48e1-a924-51fdf56017ef)

**Comment by Trewaters** [comment]
Fixed my sign in issue by removing this setting and readding it. Removing it works too.
![image](https://github.com/user-attachments/assets/a65f6e89-1034-42fb-907b-96fabf2a860f)

**Comment by lucasgabrielcastro** [comment]
@Trewaters this worked for me, as soon as I deleted my preferred account it did fetch the auth token again. Thank you!

**Comment by gnllucena** [comment]
> Fixed my sign in issue by removing this setting and readding it. Removing it works too. ![image](https://private-user-images.githubusercontent.com/7051102/355501364-a65f6e89-1034-42fb-907b-96fabf2a860f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTM0NTIsIm5iZiI6MTcyMzA5MzE1MiwicGF0aCI6Ii83MDUxMTAyLzM1NTUwMTM2NC1hNjVmNmU4OS0xMDM0LTQyZmItOTA3Yi05NmZhYmYyYTg2MGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDQ1OTEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGE4OWMzNTFhZWVmNTVlNWM5Y2NkM2Y1YzM2Y2UwMTBkYmJmMzViMWM2ZmViNzljZWI4ZDkzNjk4NWE2YzljYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f_Sf0z9dw6L5b9p7iUHBKDFmY4z-gxzZETPbd3mTuBw)

this also worked for me, thanks dude!

**Comment by TylerLeonhardt** [comment]
What was it set to before you deleted the value?

**Comment by Trewaters** [comment]
> What was it set to before you deleted the value? I'm trying to track down how this is getting set incorrectly.

It was set to the correct username but I had to delete and re-enter the same correct username to fix my sign in issue.

**Comment by Trewaters** [comment]
> What was it set to before you deleted the value? I'm trying to track down how this is getting set incorrectly.

It was set to the correct username but I had to delete and re-enter the same correct username to fix my sign in issue.

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode-copilot-release/issues/1444

**Comment by gnllucena** [comment]
> What was it set to before you deleted the value? I'm trying to track down how this is getting set incorrectly.

I have two GitHub accounts set on vscode, one personal and one from work. When vscode prompt'ed me to login, I logged in with my personal account, and my work account was set on the settings page.

**Comment by peterkim3** [comment]
> Fixed my sign in issue by removing this setting and readding it. Removing it works too. ![image](https://private-user-images.githubusercontent.com/7051102/355501364-a65f6e89-1034-42fb-907b-96fabf2a860f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNTI1NDcsIm5iZiI6MTcyMzI1MjI0NywicGF0aCI6Ii83MDUxMTAyLzM1NTUwMTM2NC1hNjVmNmU4OS0xMDM0LTQyZmItOTA3Yi05NmZhYmYyYTg2MGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMDExMDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVjM2E2OTdmZDVkZGU3YjRkMDg2Y2Q5NTg2NjU0Mjg0ZDRkZjIxMmMwZWJkYjdhZTA3OTg0MWQzZDIxZjBlMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KbVMWBbVNfEXH4UKbNJs7qVHfcCHY2eiQIDSCkJ01aU)

Thank you, it works well

**Comment by bulat15g** [comment]
Sorry for the delayed response. What helped me was removing all accounts and extensions in VS Code. After that, I added everything back one by one. I did this about two weeks ago. 😊

**Comment by MattStarfield** [comment]
THANK YOU @Trewaters! That fix worked for me too.

**Comment by cholland-nv** [comment]
@Trewaters How do I access that to change preferred account?  Thanks!

**Comment by Trewaters** [comment]
> @Trewaters How do I access that to change preferred account? Thanks!

Got to...
![settings](https://github.com/user-attachments/assets/1f2e6c5d-9adf-4f97-9463-bfe05e8885f1)


1. Click "File" in top menu
2. Preferences > Click "Settings"
3. In "Search settings" look for term "copilot"
4. Update "Github > Copilot: Preferred Account"
5. delete current entry (even if it is correct)
6. add Account Username here

For some reason removing and re-adding worked for me.

**Comment by cholland-nv** [comment]
@Trewaters 
you rock!  thank you. that fixed it.
