### ISSUE TITLE
code selector not working hence chat is giving new code instead of using mine

### ISSUE THREAD

**Issue by derrickny** [microsoft/vscode-copilot-release#1222]
- VS Code Version:Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
- OS Version: Mac os 14.4.1 (23E224)
- Logs:

Steps to Reproduce:

1.
2.

**Comment by lramos15** [comment]
Please elaborate on what you mean by not working? How large is this file? Something we can repro would be helpful
