### ISSUE TITLE
Buggy behavior - Github Copilot in VS code no longer prompts after switching computers 

### ISSUE THREAD

**Issue by MashaMSFT** [microsoft/vscode-copilot-release#1231]
I installed the Github Copilot in VS Code extension on one computer, and it was working great. It would prompt me to autocomplete my sentences fairly regularly, and was awesome Then I switched computers, and now it no longer prompts me in .md files, though it does still sometimes prompt in .yml files. I've tried reinstalling the extension, and even VS Code, to no avail.

I'm using VS Code Version 1.89.0
Github Copilot: v1.187.0

Steps to Reproduce:

1. i open vs code with my copilot extension enabled
2. i do stuff, i don't get prompted - though i used to get prompted frequently

**Comment by lramos15** [comment]
Ghost text issues are managed over at. https://github.com/orgs/community/discussions/categories/copilot

This repository is just for VS Code Copilot Chat

**Comment by MashaMSFT** [comment]
I submitted there and there hasn't been much traction https://github.com/orgs/community/discussions/123031 also what's ghost text

**Comment by lramos15** [comment]
Ghost text / code completions is the AI suggestions inside the editor. 
Where as chat is the widget that you explicitly ask questions to

**Comment by lramos15** [comment]
What does the little copilot icon in the bottom right show in markdown files for you?

**Comment by MashaMSFT** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/32783170/6fd8a9c4-fc4a-4cb4-b0ac-7c73ad4656d5)

and the status shows "Disabled". i clicked that menu option, and now it shows ready...

could it have been that easy?  :o :o 

is there some reason it would automatically be disabled upon installation (and reinstallation)?

**Comment by MashaMSFT** [comment]
ah wait, nvm, after a few minutes, it shows disabled again
![image](https://github.com/microsoft/vscode-copilot-release/assets/32783170/ce6c40cb-baed-4f35-b003-d8e43eb4ac1c)

i click it again and it shows ready: 
![image](https://github.com/microsoft/vscode-copilot-release/assets/32783170/3bbdfa0f-f858-4117-9181-e3230a7957fd)

and then a min later: 
![image](https://github.com/microsoft/vscode-copilot-release/assets/32783170/c004800a-9c1f-4803-8e09-cdf2e9a5b48a)

T.T

**Comment by MashaMSFT** [comment]
It seems somehow my **Enable completions for 'markdown'** has become disabled, it was enabled by default before. I enabled it and I think it fixed my issue so I'll close this issue out :)
#please-close
