### ISSUE TITLE
The file address will be exposed in the chat content.

### ISSUE THREAD

**Issue by TJtangjun** [microsoft/vscode-copilot-release#1234]
- VS Code Version:1.89.1
- OS Version:W11
- Logs:

Sometimes, the file location information of the file is displayed in the chat content in clear text, I think it should be displayed as the rendered url address. Maybe it is caused by the incompatibility between the plugin and the Chinese language.

![image](https://github.com/microsoft/vscode-copilot-release/assets/23148245/bf099b1d-f8ba-416a-8d3d-f1ea55bc8713)

**Comment by mjbvz** [comment]
I believe this has been fixed in the current copilot release. Please let me know if you still see it
