### ISSUE TITLE
CO PILOT stops working after approximately 2 prompts

### ISSUE THREAD

**Issue by avahi-india** [microsoft/vscode-copilot-release#1236]
- VS Code Version: 1.89.1
- OS Version: Pop!_OS 22.04 LTS 
- Logs: 

After some 2 prompts the co pilot just stops working, if i send any texts in chat it will be showing generating for indefinite amount of time, co pilot works after i re-start vs code.

**Comment by mjbvz** [comment]
What version of the copilot chat extension are you using?

**Comment by mjbvz** [comment]
I believe this has been fixed. Please let me know if you still see it
