### ISSUE TITLE
In chat markdown, code's is not formatted correctly.

### ISSUE THREAD

**Issue by oguzdev35** [microsoft/vscode-copilot-release#1238]
Copilot Chat Version: v0.16.2024052401 (pre-release)

<img width="628" alt="Screen Shot 2024-05-24 at 11 23 30" src="https://github.com/microsoft/vscode-copilot-release/assets/58663835/200ba2b3-1da9-4c0e-a7fa-8263f0b394d4">

**Comment by rajeshmag** [comment]
+1, code indentation is broken, I am using **GitHub Copilot Chat** in **Visual Studio Code - Insiders**
![image](https://github.com/microsoft/vscode-copilot-release/assets/31005672/ac68f786-975e-4e5f-8b2c-cd9d1ac86e48)

**Comment by salientknight** [comment]
I am having the same problem. It started after I updated this morning.

**Comment by roblourens** [comment]
Fixed in https://github.com/microsoft/vscode/issues/213382, sorry!
