### ISSUE TITLE
copilot search ?

### ISSUE THREAD

**Issue by flyark** [microsoft/vscode-copilot-release#1240]
Type: <b>Feature Request</b>

I'd like to search the previous copilot chat but cmd+f doesn't allow searching the previous chat history. I don't know why. it's very inconvenient compared to chatgpt. 

Extension version: 0.15.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by roblourens** [comment]
We attempted this at one point, but it was hard to render the results. Can't find another open issue for it.

**Comment by Anselmoo** [comment]
> I'd like to search the previous copilot chat but cmd+f doesn't allow searching the previous chat history. I don't know why. it's very inconvenient compared to chatgpt.


Even when working with the chat window in the editor, it is challenging to obtain previous results, necessitating repeated requests, which incurs unnecessary resource consumption 👉 running out of quota for expensive models like `o1` or `Claude`
