### ISSUE TITLE
Copilot's knowledge on Flutter and Dart is severely outdated (version 2.8.1 vs current 3.22)

### ISSUE THREAD

**Issue by zivshek** [microsoft/vscode-copilot-release#1242]
Here's the response I got when questioning its Futtler code and suggestions:
"It seems there's a misunderstanding. Flutter's latest stable version at the time of writing is 2.8.1. If you're referring to Dart SDK version as 3.19.5, that's also not correct as Dart's latest stable version is 2.15.1."

3.19.5 is the version I have on my PC.

**Comment by lramos15** [comment]
Will be fixed via https://github.com/microsoft/vscode-copilot-release/issues/560
