### ISSUE TITLE
Add option to chat without workspace context

### ISSUE THREAD

**Issue by EwenDC** [microsoft/vscode-copilot-release#1249]
Having a back-and-forth with Copilot is very frustrating due to the lengthly process to collect workspace information (exacerbated by VSCode forcing the "@workspace" context, and the trigger-happiness of the algorithm that determines what to collect). This creates a ~5 second delay before each response that slows down conversation unnecessarily when asking general questions not related to your codebase.

On top of that, it makes Copilot dumber as it unnecessarily prioritises the data it gets from the workspace context over the current chat context. As an example, I was asking Copilot to write a comparator function for sorting arrays in JavaScript. When it responded with a function that only sorted numbers, I asked it to rewrite the function to cover all data types. Rather than pay attention to our chat context, it assumed I must be talking about a random function in a file I had open and started trying to rewrite it. After I restated the prompt about creating a new sorting function, it just parroted back the sorting function in our codebase that I was trying to compare against a Copilot generated implementation.

**Comment by lramos15** [comment]
It should not be including workspace everytime. Can you include a screen recording. https://gifcap.dev/ is a tool I use to capture screen recordings

**Comment by EwenDC** [comment]
Here's me opening a brand new VSCode window, and typing a message without any context. As you can see, the second the message is sent, it gains the @workspace context, and Copilot attempts to scan my workspace.
https://github.com/microsoft/vscode-copilot-release/assets/39972488/95d1d023-7739-4358-a6d9-115fbbe79c1d

**Comment by lramos15** [comment]
Hi @EwenDC, sorry this got buried a bit in my inbox. On the latest version are you still experiencing this problem?

**Comment by EwenDC** [comment]
Hi @lramos15, apologies for the slow response.

Yes, this is still occurring for me.
https://github.com/user-attachments/assets/3fe9256b-a5af-4a6b-979d-13d6a8087081

**Comment by lramos15** [comment]
Are you up to date? I see a pending extension update and VS Code update in that recording

**Comment by EwenDC** [comment]
Sorry missed your response again 😔. Updated and same result

https://github.com/user-attachments/assets/4b849c91-b164-473f-bfd4-c904782fee4f

**Comment by EwenDC** [comment]
Oh my god I am so dumb 🤦‍♂️. Yeah I was doing ctrl + enter. I blame slack for giving me the muscle memory. Thanks for sticking with me and sorry for wasting your time.

**Comment by roblourens** [comment]
No worries, you can also customize the keybindings if you'd like to keep the familiar muscle memory
