### ISSUE TITLE
allow for system context message.

### ISSUE THREAD

**Issue by luiz00martins** [microsoft/vscode-copilot-release#125]
### Version
Insider: 1.79.0-insider, commit f6be5461f8bc69013a605f5baea834651c6589fb
Copilot Chat: v0.1.2023052205

### Description
Same idea as in the OpenAPI Chat Playground:
![image](https://github.com/microsoft/vscode-copilot-release/assets/43142209/8e1fd845-89e6-4017-be7c-3b7a92d9de9e)

Have an option for a "system context" message, where you specify parameters for your chat, (such as "explain thoroughly", or "be short"), which will be taken into account during the whole conversation.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/563
