### ISSUE TITLE
Registered chat variables should not be hidden when using a chat agent

### ISSUE THREAD

**Issue by frblondin** [microsoft/vscode-copilot-release#1251]
Type: <b>Bug</b>

I am creating a new extension which adds new variables to GitHub Copilot Chat. This variable provides additional information that would enhance the /fix command performance.

I can successfully use the variable #myVariable and ask questions, but I cannot use this variable in combination with `/fix` command. The reason is that `/fix` automatically adds the `@workspace` agent, and variables become then filtered out (e.g. only default variables are shown, not added ones in extensions).

I think that it makes sense to filter commands depending on which agent is called, but I don't think it is relevant to filter variables too. Variables should be exposed regardless which agent is used... or at least a new parameter could be added when registering a variable to mark a variable as *global* (meaning that it should be useable regardless which agent is used).

Here is how the variable has been defined:
```
vscode.chat.registerChatVariableResolver(
    'git-refact-commits-var',
    'gitRefactCommits',
    'Last 10 refactoring (i.e. containing refact) commits from past history',
    '',
    true,
    { resolve: getRefactCommits }),
```

Image below shows that only default variables are shown, not added ones:
![image](https://github.com/microsoft/vscode-copilot-release/assets/5735134/4b43d89f-91c9-4404-bf06-7177bbdf98d8)

Extension version: 0.16.2024052702
VS Code version: Code - Insiders 1.90.0-insider (b9fa819edd893c590b28f3a09b75a81513e12fb9, 2024-05-24T17:21:19.268Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13950HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.61GB (50.73GB free)|
|Process Argv|C:\\Temp\\vscode-extension-samples\\chat-sample --crash-reporter-id ae3d8212-7e85-4d29-be44-058116e4fe47|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
nb_pri_only:31057983
26j00206:31048877

```

</details>

**Comment by roblourens** [comment]
We do allow other participants to use variables, but this is probably because you passed `true` to `isSlow`, you shouldn't use that for your variable.

Thanks for trying out the variables API, make sure you follow https://github.com/microsoft/vscode/issues/212995 for updates. Would love to hear more about how you're using it.
