### ISSUE TITLE
Context variable for current output/debug logs

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#1258]
Making sense of outputs is a great task for AI, especially when I can also show it the code I am debugging (tests, runtime issues, extension development, etc).

Could be either `#output` for the currently picked `Output` channel, or, more clicks, `#output:Tasks` for picking one of the available channels.

**Comment by meganrogge** [comment]
Assigning @sandy081 as this seems more related to output than debugging
