### ISSUE TITLE
Copilot loosing Context, instead start describing the code ( I don't have the ability to view your active selection or files)

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1259]
the answer i get:

`It seems like you have a Flutter application here, specifically an onboarding screen. However, you didn't specify what issue you're facing. Could you please provide more details about the problem you're encountering? This will help me provide a more accurate solution.`. 

```
I'm sorry for the confusion, but as an AI, I don't have the ability to view your active selection or files. I can only provide assistance based on the information you provide in the conversation. If you could provide the implementation of _buildOnboardingPage or more details about your issue, I'd be happy to help further.
als this crap:
```

**Comment by ulugbekna** [comment]
You can use shortcuts such as `#selection` or `#file` to have more specific context passed in your request.

**Comment by fisforfaheem** [comment]
Not fixed yet
