### ISSUE TITLE
no chat panel after installing copilot chat extension

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-copilot-release#1263]
Type: <b>Bug</b>

1. start out with copilot chat installed
2. create a new profile and reload the window
3. install github copilot extension (which also installs copilot chat)
4. no chat sidebar, so reload
:bug: still no chat sidebar

Extension version: 0.16.2024052901
VS Code version: Code - Insiders 1.90.0-insider (fc8762e773c35d4e52e8a7375704af2e24698e5d, 2024-05-29T05:49:46.157Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.09GB free)|
|Process Argv|--crash-reporter-id 99cd116c-59d9-4cd2-bda6-71a895fc8076|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
pythoncet0:30859736
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
showvideot:31016890
chatpanelt:31014475
01bff139:31013167
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
nb_pkg_only:31057982
26j00206:31048877
nativerepl2:31062443

```

</details>

**Comment by amunger** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/2019016/b25fd6a7-ed8f-486c-beb5-113766cc933b)

**Comment by roblourens** [comment]
When I did this, I got the stable version of the Copilot Chat extension, probably you got the same. I filed https://github.com/microsoft/vscode/issues/213959, that's wrong

**Comment by amunger** [comment]
I can no longer repro today, and pre-release is installed as expected
