### ISSUE TITLE
Allow web pages to be referred during context creation

### ISSUE THREAD

**Issue by cloudbow** [microsoft/vscode-copilot-release#1267]
Now that we have different chats associated to a vscode workspace and its persisted . I can switch between the and build classified contexts. This is awesome.! 

What I am missing is ability to refer to a web page like if I am building a rest api using fast api in python, then I want to use pydantic. I could possibly scrape the getting started page of pydantic and feed it into the context. This /web option would be a great idea to build context from the web page rather than copy it from the web.

**Comment by bhavyaus** [comment]
Please see: https://github.blog/changelog/2024-10-29-web-search-in-github-copilot-chat-now-available-for-copilot-individual/
