### ISSUE TITLE
Copilot rename suggestions ignore naming conventions from context

### ISSUE THREAD

**Issue by Ste1io** [microsoft/vscode-copilot-release#1269]
Copilot gives preferential treatment to camelCase naming convention when generating rename suggestions, regardless of the existing convention being used, naming convention of neighboring contextually-relevant functions, or even default language-specific best practices. For example, in a Python file:

![1717098027-vitalog webapp_-_pages80_Analyze_Log_File py](https://github.com/microsoft/vscode-copilot-release/assets/37424493/1a02dd40-b2e6-4fee-9330-4179984d4d5e)

![1717098493-vitalog webapp_-_streamlit_state py](https://github.com/microsoft/vscode-copilot-release/assets/37424493/0e8c24a9-b3bb-46ef-a0a7-3dd059fc5fb5)

It's almost like the rename suggestion prompt assumes everything is JavaScript.

If the current name being sent with the rename suggestion prompt uses snake_case, the rename suggestions should adhere to that. If the naming convention is unclear from the function being renamed (ie `def clear(self, key)`), either use the surrounding context, or just default to the language's best practice based on the file's selected language type or filename extension.

Compare the results from my basic (naïve) prompt below, which doesn't even mention naming conventions or include other existing function names in the context, to the inline function rename suggestions:

![1717099317-vitalog webapp_-_pages80_Analyze_Log_File py](https://github.com/microsoft/vscode-copilot-release/assets/37424493/fccda836-ec36-4ca1-a70d-da12c1f0a57a)

**Comment by ulugbekna** [comment]
Thank you for trying out the feature and filing this issue! I'll be working on a fix!
