### ISSUE TITLE
GitHub Copilot Chat No Working

### ISSUE THREAD

**Issue by sfonua10** [microsoft/vscode-copilot-release#1270]
Type: <b>Bug</b>

Click on chat icon in activity bar and it doesn't respond. 
Also, highlight code and hit `Command + i` and the popup doesn't appear to help.

CPUs	Apple M2 Pro (12 x 24)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg)	2, 2, 2
Memory (System)	32.00GB (0.80GB free)
Process Argv	--crash-reporter-id 0dfd6dbd-c2be-454b-8c1c-551a9fb326f0
Screen Reader	no
VM	0%

Extension version: 0.11.1
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.80GB free)|
|Process Argv|--crash-reporter-id 0dfd6dbd-c2be-454b-8c1c-551a9fb326f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31062275
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by ulugbekna** [comment]
You're on a quite old VS Code version. Consider upgrading to 1.89.1, which should fix this issue for you.

**Comment by ulugbekna** [comment]
@birgersp Make sure you're on latest release of Copilot Chat extension. Based on your screenshot, Copilot Chat extension is not activated which is either because it's not installed or not activated. You can also look at the dev console (command "Toggle developer tools") and see if you see any errors related to Copilot Chat. If it doesn't work out, please file a new issue with version of Copilot Chat.

**Comment by jutkko** [comment]
Having the same issue on Mac M2 machine, with up to date VS Code and up to date extension. Cannot send any messages, there is no interaction. 

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:54:35.075Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.3.0

<img width="894" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4571626/07afad1b-0a9d-4134-b877-6d88e250d6bf">

<img width="828" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4571626/79e83acb-a3a3-4e7b-86e7-ad3f6e6e9983">

**Comment by ulugbekna** [comment]
@jutkko Hi, thanks for your report! If you can still reproduce this issue, could you file a new issue with the developer tools logs? (you can open developer tools by invoking VS Code command "toggle developer tools" from the command palette (cmd+shift+p))

**Comment by ulugbekna** [comment]
Closing this issue as inactive.
