### ISSUE TITLE
Off topic filter incorrectly flagging programming-related questions in Korean

### ISSUE THREAD

**Issue by jvstatinydev** [microsoft/vscode-copilot-release#1272]
- VS Code Version: 1.89.1 (Universal)
- OS Version: Darwin arm64 23.1.0
- Logs: 
<img width="433" alt="Screenshot 2024-05-31 at 1 29 36 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/47021527/848443da-c7be-4280-b232-082f7713a8b9">

Steps to Reproduce:

1. Open a JavaScript file in VS Code.
2. Select a line of code. My code was `const tab = '   ';`
3. Open Copilot chat and ask in Korean, "이 변수명 적당해?" (Is this variable name appropriate?).
4. Despite the question being programming-related, the response is "Sorry, but I can only assist with programming related questions."

Additional Info:
- The file and the selected code line are referenced correctly, but the off-topic filter seems to incorrectly flag the question as non-programming related.
- The issue persists with the following VS Code setup:
  - Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
  - Date: 2024-05-07T05:14:24.611Z (3 weeks ago)
  - Electron: 28.2.8
  - ElectronBuildId: 27744544
  - Chromium: 120.0.6099.291
  - Node.js: 18.18.2
  - V8: 12.0.267.19-electron.0

Please let me know if any additional information is required.

**Comment by digitarald** [comment]
We updated the off-topic filter and see a significant drop in false-positive filtering in experiment results across different languages.

Closing as fixed, but please don't hesitate to file new issues in case you still run into this.
