### ISSUE TITLE
Installing release Copilot Chat in Insiders causes errors

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#1273]
Type: <b>Bug</b>

Should Insiders ever offer to install release Copilot Chat?

STR:
- Use Insiders with pre-release Chat extension
- Switched to release version of Copilot Chat, restarted extension host
- 🐛 Every chat message fails with `Cannot read properties of undefined (reading 'map')`
- Restart VS Code
- 🐛 Chat never appears

Logs after restart
```
2024-05-30 22:18:03.884 [error] Extension 'GitHub.copilot-chat' CANNOT register participant with invalid name: GitHub Copilot. Name must match /^[\w0-9_-]+$/.
2024-05-30 22:18:03.885 [error] Extension 'GitHub.copilot-chat' CANNOT register participant with invalid name: GitHub Copilot. Name must match /^[\w0-9_-]+$/.
```

Extension version: 0.15.2
VS Code version: Code - Insiders 1.90.0-insider (c6e45e96a6b0fe94e0dae5b13ab4167d69ec9788, 2024-05-28T10:49:48.138Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|64.00GB (4.59GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
I am getting following error when installing stable version of chat extension in insiders

![Image](https://github.com/microsoft/vscode-copilot-release/assets/10746682/c35b23b5-2233-4575-b234-499ee747cfba)


https://github.com/microsoft/vscode/blob/54dd0ecc653b89e6032369c6f4b1808bc8e37ec5/src/vs/workbench/contrib/chat/browser/chatParticipantContributions.ts#L167-L181

**Comment by isidorn** [comment]
Closing. If you can still repro please re-open. Thanks!
