### ISSUE TITLE
File can't be worked with

### ISSUE THREAD

**Issue by b3m1lGuccigang** [microsoft/vscode-copilot-release#1274]
- VS Code Version: 1.89.1
- OS Version:Linux x64 6.1.0-21-amd64
- Logs: As an AI, I can't see your active selection or the content of your files. Could you please provide the code snippet that you're referring to? Then I can help you determine if the primary colors are set correctly.

Steps to Reproduce:
![Screenshot from 2024-06-02 17-33-27](https://github.com/microsoft/vscode-copilot-release/assets/153606778/6f598f44-9b6a-4500-9680-70caaa3e11bf)
1.Dunno, worked fine for a while, maybe a update changed it? Only very recent problems
2.Asked for a very obvious thing here
When I started working with Copilot the chat worked better for finding different files etc., had a few slight problems recently

**Comment by roblourens** [comment]
Most likely, the selection is too long for the context window. It might still be listed incorrectly in "Used references", but in the next release which goes out this week, we will only list the reference in that section if it actually fit into the prompt. You can check that out to see whether it helps later this week or try it in Insiders today
