### ISSUE TITLE
Can't use copilot chat neither on side panel or on the text editor

### ISSUE THREAD

**Issue by igorrates** [microsoft/vscode-copilot-release#1276]
Type: <b>Bug</b>

The chat initiates neither on the side panel or on the text editor

![image](https://github.com/microsoft/vscode-copilot-release/assets/11565746/ce7732d5-c924-4653-b705-8629d5810c38)

Extension version: 0.15.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900K (32 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.77GB (25.54GB free)|
|Process Argv| --crash-reporter-id ee8eb152-112d-4ad5-89df-be768f244bab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
666c4381:31064718
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31061160
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by igorrates** [comment]
Just updated to the extension version v0.15.2 and also tried the pre-release version v0.16.2024060302, 

it doesn't work

**Comment by roblourens** [comment]
Not sure what the problem was, but we just released new versions, is it still happening with the latest?

If using VS Code Insiders, use the extension pre-release, and if using the stable VS Code, use the release version of the extension.

**Comment by igorrates** [comment]
I updated the extensions and code to the latest releases and it is now working again.

Id: GitHub.copilot
Version: 1.200.0

Id: GitHub.copilot-chat
Version: 0.16.0

VS Code
Version: 1.90.0 (system setup)
Commit: 89de5a8d4d6205e5b11647eb6a74844ca23d2573
Date: 2024-06-04T19:33:54.889Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
