### ISSUE TITLE
Extension activation failed unable to get local issuer certificate

### ISSUE THREAD

**Issue by wsmelton** [microsoft/vscode-copilot-release#128]
- VS Code Version:
  ```
  Version: 1.79.0-insider (system setup)
  Commit: f6be5461f8bc69013a605f5baea834651c6589fb
  Date: 2023-05-20T01:18:53.811Z
  Electron: 22.5.2
  Chromium: 108.0.5359.215
  Node.js: 16.17.1
  V8: 10.8.168.25-electron.0
  OS: Windows_NT x64 10.0.19042
  ```
- OS Version: `Windows_NT x64 10.0.19042`
- Logs: (Don't find any logs generated for this extension)

Steps to Reproduce:

1. Using ZScaler Internet Security
2. Install Copilot extension (nightly)
3. Restart VS Code
4. Receive error message:

```
[ERROR] [default] [2023-05-25T13:37:15.617Z] GitHub Copilot could not connect to server. Extension activation failed: "unable to get local issuer certificate"
```

![image](https://github.com/microsoft/vscode-copilot-release/assets/11204251/236ec95a-477b-4803-bf40-ed1f25f82bee)

**Comment by roblourens** [comment]
Should be fixed by now

**Comment by ttickell** [comment]
Same issue.  What was fixed?
