### ISSUE TITLE
"spoiler-free" answers when using dark high contrast theme

### ISSUE THREAD

**Issue by gtritchie** [microsoft/vscode-copilot-release#1284]
Type: <b>Bug</b>

Set workbench color theme to "Dark High Contrast" then ask a question in GitHub Copilot Chat (for example: "explain how printf works in c". Some of the text in the answer is displayed white-on-white and cannot be read. Switching to a different theme or selecting the text confirms presence of the text.

<img width="708" alt="screenshot of github copilot pane showing a repro case" src="https://github.com/microsoft/vscode-copilot-release/assets/10569626/65c9b12d-7f5b-4004-acbd-970ad9534eb4">

Extension version: 0.16.0
VS Code version: Code 1.90.0 (Universal) (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:44.157Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 8|
|Memory (System)|32.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id 3d0de755-e024-48e4-a9f5-c0d4e863f1d2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by joyceerhl** [comment]
This should now be fixed, please reopen if that's not the case
