### ISSUE TITLE
The diff window in the inline chat seems too small

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-copilot-release#1286]
The DIFF window in the inline chat seems too small for many use cases. Is it possible that allow user to resize the diff dialog manually? Or send the diff to a new window? In the DIFF dialog right now, it's **Split View**. Is it possible change to **Unified view**?

![image](https://github.com/microsoft/vscode-copilot-release/assets/88981/b935c449-cf92-4813-98c0-27f5e96e7d82)

**Comment by jrieken** [comment]
> Is it possible that allow user to resize the diff dialog manually?

This is possible with the `N hidden lines` UI

**Comment by doggy8088** [comment]
@jrieken I need WIDER window, but I can't drag.

**Comment by doggy8088** [comment]
@jrieken The dialog is really too narrow for the most of the use case.

**Comment by jrieken** [comment]
Closing because inline chat is now full width
