### ISSUE TITLE
Invalid reference

### ISSUE THREAD

**Issue by BrianMwengi** [microsoft/vscode-copilot-release#1288]
I keep getting invalid value reference in my  chat yet I have subcribed for this tool.

**Comment by Guerraart8** [comment]
On Friday, June 7, 2024, Brian Mweu ***@***.***> guerraart8:

**Comment by mjbvz** [comment]
I'm unsure what this means

If you're still seeing this issue, please fill out the template with your VS Code and extension versions. Also provide a detailed description of the issue and steps to reproduce it
