### ISSUE TITLE
Low quality & long answers in copilot chat (improvement proposal)

### ISSUE THREAD

**Issue by vladlabs** [microsoft/vscode-copilot-release#1289]
Copilot  chat often gives me extremely long responses with almost no useful information. Even if I will be a dumb junior developer it would not help me. This behavior is actually slow down my development because searching internet is faster that waiting for a long useless answer that clarifying it and waiting again.

I do not want to read 500-1000 characters to realize that answer to my question is "NO|Not possible".

I could partially fix this behavior by adding after each question "short answer, no explanation". But why should I do that after each question? 

## Solution 1

By default copilot should respond in short verbose way. 
I'm working I want brief/fast answer so I could continue to chat, clarifying requirements and so on.
If I would require explicit long answer than I could just ask for clarification or you could add addition command like "/clarify" to make Copilot give bigger response with all details on previous question.

## Solution 2 (preferred one)

Maybe It would be cool to have a custom shortcut or default modifier for all copilot chat queries.
For example I want configure to add by default to all my inputs "Short answer, do not explain"
I want to have custom command like "/clarify" that would expand to "Answer on previous question with full explanation and code samples if requred"

The second solution is more flexible as it allows me to have several pre-defined shortcuts that would fit my work process. So I would not waste time typing same clarification question again and again

Ideally I should have ability to customize copilot behaviour in `.vscode/settings.json` I mean like any other configuration it sould be possible to have global configuration and workspace related.

**Comment by roblourens** [comment]
I think the best solution for this is https://github.com/microsoft/vscode-copilot-release/issues/563 so you can customize it yourself, does that sound like it would help you?
