### ISSUE TITLE
Multiple simultaneous sessions for isolating disparate conversations

### ISSUE THREAD

**Issue by matrumz** [microsoft/vscode-copilot-release#129]
I'd like to see the ability to have multiple chat sessions simultaneously, without needing to repeatedly import/export sessions. Keeping disparate topics separate facilitates going back through history to reference previous responses.

Scenarios where this would be helpful:
- switching between projects / topics mid-work
- starting a side-chat in order to assist coworkers and answer their questions, then closing this chat

**Comment by Sandros94** [comment]
Totally agree.

>without needing to repeatedly import/export sessions

Where do you import/export chat sessions?

**Comment by matrumz** [comment]
> Where do you import/export chat sessions?

From the command palette: `Chat: Export Session...` and `Chat: Import Session...`

**Comment by roblourens** [comment]
We also now have chat in an editor
