### ISSUE TITLE
Copilot losing context AND unable to see code, AND keeps blaming me for its mistakes. 

### ISSUE THREAD

**Issue by jontim** [microsoft/vscode-copilot-release#1290]
For the last two weeks or so, Copilot has been unusable. It cannot retain context between one message and the next, and has lost the ability to read highlighted code. Or at least is pretending it can't read the code. Sometimes I see it flash-up "Reference frontend.js lines 1-368" or whatever that message is that tells you it's reading the code, and then it says "Unfortunately as an AI I cannot see your code, could you copy and paste it into the chat?" or one of 2-3 similar messages. Sometimes it tells me it can read a repo, so commit my changes etc. None of this works. 

When I try to copy code in to the chat, if it's just the code sometimes it gets through, most often it goes through and then copilot just says here is what your code does. Then i ask my actual query and it's context window is reset apparently - it says, great but I'd need to see your code to help with the issue you're describing (I'm paraphrasing). So this cycle is making me paranoid that the AI is actually screwing with me, although I know that's **_probably_** not happening.
- VS Code Version: 1.90.0
- OS Version: Sonoma 14.1.1
- Logs: see screenshot
<img width="1975" alt="copilot error" src="https://github.com/microsoft/vscode-copilot-release/assets/28566652/6e4608d5-435a-4bcd-8cd7-53df0db6262c">

Steps to Reproduce:

1. log into my account
2.try to use copilot
3. cry when it fails.

**Comment by veloper** [comment]
Can confirm, `Sorry, I can't assist with that.` is super easy to Trip and persists event past "/clear" which does not seems to actually clear any context.

**Comment by ben-kzn** [comment]
Happening for me as well. This makes copilot unusable and should be prioritized

**Comment by roblourens** [comment]
<img width="141" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/323878/08eea2f2-1c79-4a94-b13d-177680a814a2">

This is a clue- we have a slightly smaller context window to work with, so in this case it's not able to fit your code into the prompt and it can't see it.

It will look at your selection, but if it doesn't fit, then it won't see that either. Sorry that this is frustrating, we're working on it!

**Comment by dylan-evans** [comment]
Roblourens says, 'Sorry, i can't assist with that' ...

**Comment by PerryCodes** [comment]
Copilot is garbage and it's a crime to charge money for it.

**Comment by pmonasterio3** [comment]
This is still happening; there is no way to have Copilot work with selected code, Even using the suggested prompts, I get the "Sorry, I can't assist with that." repeatedly without any further context.

**Comment by KayElliot** [comment]
Still happening, wat about to post an issue then found this already posted. 

Jsut verified that it happens when selecting 55 or more lines of code, irregardless of what is defined on those lines.

**Comment by shishir-wm** [comment]
Its fkin criminal, it seems like the model has too small a context window.
downright unusable.
@roblourens pls work on it soon, 20$ for this is insane
