### ISSUE TITLE
Chat responses with "code format" in Markdown makes the result of the chat be inconsistent

### ISSUE THREAD

**Issue by sergio-vargas-edo** [microsoft/vscode-copilot-release#1291]
- VS Code Version: 1.90.0
- OS Version: macOS Sonoma 14.4.1

Steps to Reproduce:

1. Ask the chat to create the content of a README.md with instructions for running a command like "npm install"
2. That's it. The response is inconsistent because it will start with the right content generated but when trying to close the formatted code it makes the formatted content visible. (It looks like copilot is also using markdown for responses.

Take a look of the screenshot attached and check how it renders the content of the generated Markdown instead of sharing the code after "npm install"
 
![Screenshot 2024-06-08 at 13 14 28](https://github.com/microsoft/vscode-copilot-release/assets/155982556/72e45e7a-ad70-437b-964f-cfb191132abb)

Update: I tested with ChatGPT and the same issue happens. I need to ask the chats not to use ```bash or simmilar blocks in markdown code responses

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/793
