### ISSUE TITLE
@workspace error - bad export type for tree_sitter_tsx_external_scanner_create: undefined

### ISSUE THREAD

**Issue by Selyss** [microsoft/vscode-copilot-release#1292]
Using `@workspace` to add context results in an error `bad export type for tree_sitter_tsx_external_scanner_create: undefined`. This seems to occur when trying to use the context to generate a response. It occurs every time I try and use the service. Screenshot below.

- VS Code Version: 1.90.0
- OS Version: 

_In a codespace:_

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

- Logs:
2024-06-08 14:04:37.066 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-06-08 14:04:37.066 [info] [code-referencing] Public code references are enabled.
2024-06-08 14:04:37.067 [info] [auth] Sucessfully authenticated

Steps to Reproduce:
1. Open copilot chat
2. Create a prompt that adds `@workspace` context

![image](https://github.com/microsoft/vscode-copilot-release/assets/99344963/9ba36212-03b8-4dd6-b501-35e089537020)

**Comment by ulugbekna** [comment]
Thank you for filing the issue! 

Which version of Copilot Chat are you on? 

You can check it by finding the Copilot Chat extension in extension marketplace



![Image](https://github.com/microsoft/vscode-copilot-release/assets/16353531/d42b5cbd-c690-4449-a4fc-746ce9cc3358)

**Comment by Selyss** [comment]
I'm on `v0.16.0`.

**Comment by GarlandKey** [comment]
@Selyss Updating the extension and reloading fixed this error for me.

**Comment by mjbvz** [comment]
I think this issue has been fixed in the current release. Please let us know if you're still seeing it
