### ISSUE TITLE
When i use /vscode and ask somthing i get error

### ISSUE THREAD

**Issue by Guy-Talmi** [microsoft/vscode-copilot-release#130]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. in vs code chat window i ask /vscode how to open a file from command pallet
2. I get error: 
Unable to delete nonexistent file 'vscode-userdata:/c:/Users/guyt/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/commandEmbeddings.json'

**Comment by asportnoy** [comment]
Dupe of #110

**Comment by digitarald** [comment]
Dupe of #30
