### ISSUE TITLE
Missing/hidden quoted or wrapped text in co-pilot query response

### ISSUE THREAD

**Issue by BrandonXZ** [microsoft/vscode-copilot-release#1301]
Type: <b>Bug</b>

Ask Co-pilot any question on VSCode chat extension. Try to ask it something that requires it to put text into quotations or parenthesis. When the answer is generated, the text wrapped in ", ', (, {, [, ` chars displays as a solid white box where the text should be. The text is only made readable when the user selects the text as if to copy or cut it. 
My exact query was: "Tak to me about ONL_FULL_GROUP_BY mode, why might someone want to use this in a production environment?"

Extension version: 0.16.0
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (1.69GB free)|
|Process Argv|--crash-reporter-id a445b7dd-0bd0-4ccc-be12-6b82b739ebd6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by bhavyaus** [comment]
@BrandonXZ did you use the panel chat or the inline chat widget for your query?

**Comment by BrandonXZ** [comment]
It occurs in the panel chat, even if its expanded in the editor space. Haven't seen it happening inline with code.

**Comment by bhavyaus** [comment]
@BrandonXZ could you please share any sample prompts to help us repro this issue. Thanks.

**Comment by BrandonXZ** [comment]
issue resolved during previous update, can not reproduce at this point.
