### ISSUE TITLE
GitHub Copilot Chat Crashing Whole IDE

### ISSUE THREAD

**Issue by hgudella** [microsoft/vscode-copilot-release#1302]
- VS Code Version: 1.90.0 (user setup)
- OS Version: Windows_NT x64 10.0.22631
- Logs:

Steps to Reproduce:
1. Open VS Code
2. Open Github Copilot Chat - Select some code and ask a question.

IDE crashes with the following error

![image](https://github.com/microsoft/vscode-copilot-release/assets/4733681/bad2afdc-c9c9-4974-835f-af2673214ddb)

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report describes how to get a crash dump.
Can you try this?

**Comment by IAmJSD** [comment]
https://github.com/microsoft/vscode-copilot-release/assets/23243233/f655d2b6-325b-47ef-9070-0c526d44bfc1

I get a editor crash as soon as I install it, but do not get a crash from the editor (rather a hang but it is still active just seemingly blocked?) so I presume this won't be helpful? The log information from the shell might be though @aeschli

**Comment by aeschli** [comment]
It looks like the crash happens while the vscode-copilot extension is activated.
@digitarald Can we move this issue to the Github team?

**Comment by IAmJSD** [comment]
> It looks like the crash happens while the vscode-copilot extension is activated. @digitarald Can we move this issue to the Github team?

sorta, but it was related to the credentials store locking up VS Code here

**Comment by aeschli** [comment]
Oh, how did you find this out?
FYI @TylerLeonhardt

**Comment by IAmJSD** [comment]
> Oh, how did you find this out? FYI @TylerLeonhardt

lots of trial and error when I would open a repo that used GitHub and it also crashed, added `"password-store": "basic"` to my argv.json (I know this is unsafe, but I am the only user on this encrypted install, and I will come back to it later, just bodging this VS Code install) and it worked

**Comment by IAmJSD** [comment]
I think there is seemingly a deeper bug that causes the credential store to lock up that affects me on a near stock Ubuntu install (both with the deb and snap), but I don't know if it is the same bug OP has

**Comment by IAmJSD** [comment]
https://github.com/microsoft/vscode-copilot-release/assets/23243233/0cfdd898-eff0-47e9-836b-25beab95d7bc

just reproduced in a completely clean Ubuntu virtual machine install (I show a lot of the setup steps I clicked, a little different for partitioning but the rest is correct)

**Comment by IAmJSD** [comment]
@aeschli (sorry, I realised I forgot to tag you when I wrote all that)

**Comment by TylerLeonhardt** [comment]
@IAmJSD your issue is likely unrelated to @hgudella who was experiencing an OOM crash and on Windows. Would you mind creating a new issue and also attaching the crash dump as called out here?:
https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-a-crash-report
