### ISSUE TITLE
Feature Request: Shortcut for Sending Predefined Prompts to GitHub Copilot (prompt snippets)

### ISSUE THREAD

**Issue by goodjack** [microsoft/vscode-copilot-release#1303]
I often use the same prompts when working with GitHub Copilot in Visual Studio Code. Currently, I have to manually type or paste these prompts into Copilot's inline chat field each time, which can be time-consuming and repetitive.

I would like a feature that allows me to define a set of predefined prompts and assign a shortcut to each. When the shortcut is pressed, the corresponding prompt should be sent to GitHub Copilot automatically.

An alternative could be a dropdown menu or command palette entry that lists all predefined prompts, allowing me to select the one I want to use.

This feature would greatly improve my workflow and likely the workflows of other GitHub Copilot users who frequently use the same prompts. Thank you for considering this feature request.

**Comment by goodjack** [comment]
Oh I noticed it's similar to #754.

**Comment by roblourens** [comment]
Yeah, and this is essentially also something that we have described as "prompt snippets" but I can't find another open issue for that specifically

**Comment by Rafael-Silva-Oliveira** [comment]
Any news on this and if planned for future release? Super weird that Github Copilot doesn't have this feature already
