### ISSUE TITLE
When vscode is turned on for the first time, copilot will not perform auto-complete and will have to wait a long time

### ISSUE THREAD

**Issue by laterdayi** [microsoft/vscode-copilot-release#1305]
When vscode is turned on for the first time, copilot will not perform auto-complete and will have to wait a long time

https://github.com/microsoft/vscode-copilot-release/assets/122137647/04bc3726-ce2e-489c-b21a-3cbd7fd70f6d

**Comment by Tyriar** [comment]
This is actually related to the GitHub Copilot extension, not the GitHub Copilot Chat extension. Please report this at https://github.com/community/community/discussions/categories/copilot
