### ISSUE TITLE
AI is not good enough 

### ISSUE THREAD

**Issue by erangross** [microsoft/vscode-copilot-release#131]
I am not reporting bug, the AI simply not good enough. It makes mistakes when writing code I have tested on python.

I will test again in gpt version 5 or 6.

Thanks
Eran

**Comment by tg12** [comment]
I am sure the developers are going to love you.

**Comment by Shuyib** [comment]
It is never perfect. Even assistants make mistakes.

**Comment by erangross** [comment]
Guys, the chat feature works fine, is the AI not accurate when we are talking about coding.
I hope they will allow it to learn from its mistakes, that will be the best solution.
I will add a feature request that is missing now, is to be able to read the code without pasting it to the chat.
Eran

**Comment by YoraiLevi** [comment]
It performs worse than its cousin the default free chatgpt: ![image](https://github.com/microsoft/vscode-copilot-release/assets/50873841/1f0b2cce-c97e-4787-8674-23bed066ab1c)
