### ISSUE TITLE
Chat isn't accurate in explaining participants such as @vscode or @workspace

### ISSUE THREAD

**Issue by theReynald** [microsoft/vscode-copilot-release#1310]
- Copilot Chat Extension Version:cv0.16.1
- VS Code Version: 1.90.1
- OS Version: macOS Sonoma

Watch [video of issue here](https://microsoft-my.sharepoint.com/:v:/p/radolphe/Ec6p8SXn5FdDoe3SKAtJGJ8B9egXeloGcEXUBQTZdN1VGg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=QHq6dj).

Steps to Reproduce:

1. Open VS Code & chat
2. Ask it "how can i use @vscode" & observe the results.
3. Ask it about participants "what are the projects being looked at if I used @workspace" & observe the results. I kind of give an answer about searching file related to a workspace but doesn't seem to be referencing the participant. Also, sometimes it just says it can't assist. See video mentioned earlier.

If someone is new to using chat and new to using participants, they may ask chat about participants so chat should be able to tell the difference when question mentions VS Code versus @vscode. Or workspace versus @workspace.

**Comment by roblourens** [comment]
Right, it doesn't necessarily know everything about its own capabilities or those of registered participants. I'm going to fold this into https://github.com/microsoft/vscode-copilot-release/issues/63
