### ISSUE TITLE
Copilot has no memory of the current conversation thread or the coding environment

### ISSUE THREAD

**Issue by ericbarns** [microsoft/vscode-copilot-release#1312]
Ai in general but specifically for copilot within coding environment, where it is assumed the context is clear, with a focus on coding within vcode. It reviews HTML / JS script in a tab, then makes a coding recommendation for node.js, when clearly its a browser based solution that is required. Switch to Python, it recommends a solution that requires a simple plugin, which cant be found or installed after following all the many instructions and is unable to accurately resolve the errors thrown up by vcode as to why the install wont work. All of the above generates a huge waste of time for all concern and deep frustration, especially when copilot keeps repeating the same solution over and over again, without doing a very simple non Ai look up in the current conversation thread. This is a real problem, because it fundamentally display a lack of any intelligence, a 'does not compute' response was clearer and honest, way back (it generally told us, it was unable to find a solution), but co-pilot repeating like a parrot, tries to mask iy lack of intelligence. Constant apologise, saying i will learn, then to do the same thing again several minutes later (which must be an eternity for cloud based AI). Weren't expert system in 90's more intuit about their domain knowledge? Don't get me wrong, its ability to understand, language on structural level and infer meaning is very smart, and to review lines of code searching for errors and suggest better code, is nice if it works,  but if that is all, but in general does not understand the code, so cant provide relevant solutions in context of narrow defined domain (browser solution), then its just a clever code specific search engine! This does not warrant a fee for, as this very same facility is offered for free elsewhere without the implication ( embed nature in a coding environment ) as a code assistant.

[copilot-ai-issues.txt](https://github.com/user-attachments/files/15893194/copilot-ai-issues.txt)

**Comment by rishabnakarmi** [comment]
Agreed. Need to remind it the context, the part of code, or what I'm trying to do again and again every new prompt.

**Comment by znorris** [comment]
Likewise. I have to remind Copilot of the conversation context with every new message I send. If I add a file, that file is only available for the single message I've attached it to. Copilot also has no memory of its own earlier comments.

**Comment by Maker-Mindset** [comment]
I was able to use Copilot to great effect for the last few weeks. I am coding a website with PHP, CSS, jQuery, and MySQL. Having a limit in length for each conversation is pretty frustrating but, within a thread, I was able to slowly improve my code little by little.

However, two days ago, Copilot got amnesia!! After I asked the first question and got an answer, I was not able to tell it that the code that was suggested had a small bug. If I did, Copilot would simply suggest to me some random code that was unrelated to the originally suggested code. 

Now I am forced to ask a question and, after getting a suggested example code, I have to copy that code and start a new conversation where I paste that code within my new question. That's the only way to get a suggested improvement on an existing code. 

The fact that Copilor got amnesia all of a sudden is so frustrating. That has made my work with it so much more laborious.

**Comment by Maker-Mindset** [comment]
I believe that Microsoft may have set a threshold for free use of Copilot. If you use it very heavily, it will reach a point where it will begin to throttle its abilities to discourage the heavy user from relying so much on it. 
That's too bad. I was barely using Google anymore. Copilot was now my go-to tool for any information.
The frustration that Copilot put me through in the last two days left a sower taste in my mouth.
I am looking for a replacement...

**Comment by digitarald** [comment]
> I believe that Microsoft may have set a threshold for free use of Copilot. If you use it very heavily, it will reach a point where it will begin to throttle its abilities to discourage the heavy user from relying on it so much.

To clarify, _Free_ student/maintainer tiers do have extra thresholds or throttling but the same model access and context windows. The past releases context increased.

Could you provide a reproducible step of the flow you describe as broken, where follow-ups stop working.
