### ISSUE TITLE
Not working in WSL on WIndows. Works fine in Windows

### ISSUE THREAD

**Issue by NehalDamania** [microsoft/vscode-copilot-release#1313]
- Copilot Chat Extension Version: 0.16.1
- VS Code Version: 1.90.1
- OS Version: Windows 11 
- Logs:

Steps to Reproduce:

1. In windows WSL, Copilot chat and copilot both not working. It was working previously. Please note both are working fine on Windows. Also, Git works to push/pull code so internet access is present.

**Comment by NehalDamania** [comment]
ok. This is resolved. I created a new vs code workspace. Might be some issue in that. Now it is working

**Comment by NehalDamania** [comment]
This is stopping intermittently. Both Github Copilot chat and Github copilot stops. What could be the issue here.

**Comment by ibourn** [comment]
I have the same issue and in the copilot log : Error sending telemetry AbortError: The operation was aborted.
It was working fine on my two computers until one week ago. And now, nothing. I did try a clean unistall/reinstall with only the copilot extension but it didn't help. 
I used for the first time the copilot chat just before this problem.

**Comment by DixioBaldMan** [comment]
Same problem here since several days :
- try to re-install extension
- sign out and resign

**Comment by NehalDamania** [comment]
This got resolved for me in VS Code insiders build as of now.

**Comment by FalcorX** [comment]
To resolve the "Error sending telemetry AbortError: The operation was aborted." error when using Windows 11 / WSL2 and Visual Studio Code with the WSL Extension I had to manually set my DNS server in windows. In Network Connections > Properties > Internet Protocol Version 4 > Properties > Use the following DNS server addresses: Primary: 1.1.1.1 Alternate: 8.8.8.8

**Comment by chrmarti** [comment]
Merging with https://github.com/microsoft/vscode/issues/216658
