### ISSUE TITLE
Selective Code Insertion in Chat Dialog

### ISSUE THREAD

**Issue by GregorBiswanger** [microsoft/vscode-copilot-release#1316]
When suggesting source code in the chat dialog, I want to be able to mark only specific parts of the suggested code and insert them at the current cursor position in the source code. However, currently, the entire generated code block is being inserted.

#### Steps to Reproduce
1. Open the chat dialog in Visual Studio Code.
2. Request a code suggestion from GitHub Copilot.
3. Highlight a specific portion of the suggested code.
4. Click the button to insert the code at the current cursor position in the source file.

#### Expected Behavior
Only the highlighted portion of the suggested code should be inserted at the current cursor position in the source file.

#### Actual Behavior
The entire generated code block is inserted instead of just the highlighted portion.

#### Environment
- **Visual Studio Code Version**: 1.90.1
- **GitHub Copilot Chat Version**: v0.16.1
- **Operating System**: Windows 11

#### Additional Information
- It would be beneficial to have a feature that allows for selective insertion of code snippets.
- This enhancement would improve workflow efficiency by reducing the need to manually copy and paste specific parts of the suggested code.

#### Screenshot / Video
![19-06-2024_11-06-07](https://github.com/microsoft/vscode-copilot-release/assets/7336300/3c5bb81e-dd10-4631-b71e-4d7484cfd1fc)

**Comment by roblourens** [comment]
Copy/pasting the selection should also work

**Comment by GregorBiswanger** [comment]
It's about the flow of just being able to click on the button because the cursor is in exactly the right place.

**Comment by isidorn** [comment]
You can reference the #selection 
And we also plan to add other UI gestures from the editor to easily add the selection to the chat.
