### ISSUE TITLE
Edit and Refine Conversation History in Chat Dialog

### ISSUE THREAD

**Issue by GregorBiswanger** [microsoft/vscode-copilot-release#1317]
In the chat dialog, the ideal result often emerges after a prolonged conversation. However, due to the length of the conversation, some of the accumulated contextual information becomes vague and eventually gets lost. ChatGPT allows users to click on edit in the middle of the conversation to improve the prompt, making the conversation more concise and organized. Currently, I have to delete a message in the middle of the conversation and use the cursor keys to incorporate previously written content. This process is not optimal and user-friendly.

#### Steps to Reproduce
1. Engage in a lengthy conversation in the chat dialog.
2. Notice that some contextual information becomes vague and less useful over time.
3. Attempt to refine the conversation by editing a message in the middle of the chat.
4. Observe the current method of deleting messages and using cursor keys to incorporate changes.

#### Expected Behavior
- Ability to click on a message in the middle of the conversation and edit it directly.
- The edited message should update the conversation context seamlessly, making the dialog more concise and organized.

#### Actual Behavior
- Users must delete a message in the middle of the conversation.
- Users then have to use cursor keys to re-incorporate previously written content, which is not optimal or user-friendly.

#### Environment
- **Visual Studio Code Version**: 1.90.1
- **GitHub Copilot Version**: v0.16.1
- **Operating System**: Windows 11

#### Additional Information
- Implementing an edit feature in the chat dialog would significantly improve user experience.
- This enhancement would help maintain the clarity and relevance of the conversation context over extended interactions.

#### Screenshot / Video

The edit prompt in ChatGPT:
![chatgpt-edit](https://github.com/microsoft/vscode-copilot-release/assets/7336300/57f9b483-084d-4b0d-aa2f-9ca28b5c0490)

The edit prompt in Copilot Chat:
![copilot-edit](https://github.com/microsoft/vscode-copilot-release/assets/7336300/385b2cc5-7d00-4895-95ba-218cbdec2f2e)

**Comment by roblourens** [comment]
Was the second response not what you wanted? It's a bit hard to read in the gif.

When you edit in ChatGPT, you end up with a conversation shaped like a tree, which is interesting but in VS Code we decided that the complexity probably isn't worth it when you can just pull previous requests from history and delete messages when absolutely needed. You probably didn't need to delete the messages in this case.

**Comment by GregorBiswanger** [comment]
The length of a dialogue reduces the quality of the answer. It is best to start again at a certain point with the prompt specified there, because then you only have to adjust a little.

At the moment, I often stick with ChatGPT. The conversations are much easier to manage. I can call up previous conversations again and continue to work on them. Or improve current conversations by being able to correct a course that was leading in the wrong direction.

**Comment by FooBarWidget** [comment]
> When you edit in ChatGPT, you end up with a conversation shaped like a tree, which is interesting but in VS Code we decided that the complexity probably isn't worth it

It's fine if don't implement conversation trees. I think it's still valuable if I can go back to a specific message and edit it, discarding all following messages.
