### ISSUE TITLE
Custom Prompt Management and Community Sharing in Chat Dialog

### ISSUE THREAD

**Issue by GregorBiswanger** [microsoft/vscode-copilot-release#1318]
I would like to be able to save custom prompts and use them via commands like `/myprompt` in the chat dialog. Ideally, it would also be beneficial to have a feature for sharing prompt snippets within the community for recurring tasks. For example: "You are now a Clean Code expert. Pay explicit attention to SOLID principles," or "Refactor the code to adhere to...". Currently, users can only repeat previously entered prompts using the arrow keys in the chat dialog, which does not provide an ideal user experience.

#### Steps to Reproduce
1. Open the chat dialog in Visual Studio Code.
2. Enter a custom prompt.
3. Use the arrow keys to repeat the previously entered prompt.
4. Notice the lack of a streamlined method to save and reuse custom prompts or share them with the community.

#### Expected Behavior
- Ability to save custom prompts and call them using commands like `/myprompt`.
- A feature for community sharing of prompt snippets for recurring tasks.
- Improved user experience by allowing quick and efficient reuse of frequently used prompts.

#### Actual Behavior
- Users can only repeat previously entered prompts using the arrow keys.
- There is no functionality for saving custom prompts or sharing them within the community.

#### Environment
- **Visual Studio Code Version**: 1.90.1
- **GitHub Copilot Version**: v0.16.1
- **Operating System**: Windows 11

#### Additional Information
- Implementing a custom prompt management feature would significantly enhance user experience and efficiency.
- Community sharing of prompt snippets would foster collaboration and knowledge sharing among users.

**Comment by roblourens** [comment]
We've discussed this sort of thing a bit. Here's a couple feature requests to watch:

https://github.com/microsoft/vscode-copilot-release/issues/1303
https://github.com/microsoft/vscode-copilot-release/issues/563
