### ISSUE TITLE
[Rust][Copilot Chat] High level of hallucination when using Copilot chat with Rust language.

### ISSUE THREAD

**Issue by angelorodem** [microsoft/vscode-copilot-release#132]
- VS Code Version: Latest insider
- OS Version: Win11
- Logs: very long text chat

I think the main issue may come from GTP-x having a limited knowledge dating to 2021, but the i saw cases where the chat accused erroneously of:

- Things being allocated when they are not (New string and HashSets)
- Not understanding some basics of rust like mutable references (Thinking it allocates a new object in memory?)
- Thinking that a reference to a string slice allocates a new string in memory and its bad?
- Suggesting using other language methods that don't make sense (switch for loops for iterator::Any when there is no for loops in the code or when any can't be used)
- Saying that a parameter is not used when it is indeed used a lot
- Confidently accusing of corner cases not being covered when they are (and obviously covered).
- Suggests that lookup on a vector is better than a HashSet for cases where the number of items are unknown and big??
- many other weird suggestions...

**Comment by Dot32IsCool** [comment]
I found copilot would make up mistakes in my code and then suggest what i was already doing as the solution. It would also occasionally get the names of variables wrong.

**Comment by roblourens** [comment]
Concrete issue reports are the most helpful! We are also on GPT-4 now which hopefully helps
