### ISSUE TITLE
VS Code Sign In Button Not Working — Does Nothing When Clicked

### ISSUE THREAD

**Issue by shabaniddrisu** [microsoft/vscode-copilot-release#1320]
- Copilot Chat Extension Version: v0.16.1
- VS Code Version: v1.204.0
- OS Version: Mac OS.
- Logs: Nothing happening

Steps to Reproduce:

1. Installed Copilot in VS Code, Version: 1.90.2 (Universal).
2. Clicked on the added "Chat" tab.
3. Clicked on "Sign In" multiple times and nothing happens.
4. I'm correctly logged into my Github account online, yet it still ask me to "Sign In".
5. If I still try to "Sign In" by clicking the button in "Chat" it does nothing.

This has been going for about 2 weeks now if I am not mistaken after it has been working correctly. I tried a few methods, uninstalling and reinstalling, sign out from my Github account online and signing back in but not nothing seems to work.

Eventually, I returned back to ChatGPT.
I now have the time to raise an issue for this bug.

What is happening and how can this be fixed..?
I will happily continue my subscription if this could be fixed and the exact problem can shared too.

Warm Regards.

**Comment by scott-arcus** [comment]
I had this same issue. In my case it seems to have been related to having multiple git hub accounts logged in with VS Code.

It resolved itself after I filled in the setting "Preferred GitHub account for GitHub Copilot" under GitHub Copilot settings.

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Trigger the sign in
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Windows)
* drop in this issue the contents of the following:
  * `GitHub Authentication` Output channel
  * `GitHub Copilot Chat` Output channel

**Comment by indiepaleale** [comment]
I had the same issue. In my case I uninstalled the copilot exstension and deleted related files in the vscode extension folder manully. Then I reinstalled the extension that fixed my issue.
