### ISSUE TITLE
Copilot Chat Component Dialog Box Does Not Support Dark High Contrast Theme

### ISSUE THREAD

**Issue by yanxiaolu** [microsoft/vscode-copilot-release#1321]
Type: <b>Bug</b>

Dear VSCode Team,

I am writing to report an issue with the Copilot Chat component in Visual Studio Code. When using the Dark High Contrast theme, the dialog box of the Copilot Chat component does not seem to support this theme properly.

The issue arises when text within the dialog box is selected. The selected text turns white, making it virtually invisible against the white background of the selection highlight. This makes it impossible to see what text has been selected, which can be quite inconvenient.

I am using the latest version of Visual Studio Code and have experienced this issue consistently. I believe this is a bug that needs to be addressed to improve the usability of the Copilot Chat component, especially for those of us who prefer using the Dark High Contrast theme.

Thank you for your attention to this matter. I look forward to any updates or fixes regarding this issue.

Extension version: 0.16.1
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900KF (32 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.82GB (41.61GB free)|
|Process Argv|--crash-reporter-id 99696f3f-2f15-4be0-ad87-52cde40a7313|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
945dj816:31013170
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31077527

```

</details>

**Comment by milescb** [comment]
Hi, has there been any progress on this yet? I am also experience the same bug and would like it fixed! I'm using:

```
Version: 1.92.2 (Universal)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z (2 wks ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```
and the GitHib color theme v6.3.4. 

Thanks for the help!

**Comment by JHAmeasley** [comment]
The same is true for the light variant.

**Comment by daviddossett** [comment]
@yanxiaolu do you have a screenshot? I want to make sure I understand what you mean by dialog box here.
