### ISSUE TITLE
I want to add a feature 

### ISSUE THREAD

**Issue by solarslurpi** [microsoft/vscode-copilot-release#1322]
however, before I spent time doing the pre-requisites, I started wondering: couldn't copilot be set up to do the following items so that both of us are less frustrated (for me personally, entering the wrong query, etc. for you, getting frustrated that all of us don't do these "simple things")?  Thank you. and Thank you for all the effort that goes into copilot.

**Comment by lramos15** [comment]
I'm not sure I follow. Is this a feature request?

**Comment by solarslurpi** [comment]
Hello,
In order to enter a feature request, we must:
-------



-------
why don't you have copilot do this?

**Comment by lramos15** [comment]
Copilot would not be able to validate your bug exists in the latest version. Some bugs are very complex.
