### ISSUE TITLE
Painful ethical programming...

### ISSUE THREAD

**Issue by CuriousLayman** [microsoft/vscode-copilot-release#1324]
I am not sure if I should have put this into a bug report or desired feature, but the ethics on the copilot are frustratingly rigid. I am brand new to coding and 100% dependent on AI to help me muddle along. That being said, I have been able to create OCR readers, a wikileaks scraper, some PDF editors, and other minor bits of code that I know all of you would laugh at as hilariously simple. To me, this stuff is the definition of magic. 

The next project I wanted to work on was a webscraper for NewsBank. I understand the desire to not be sued, but I read NewsBank's terms of service and robots.txt file; I was not breaking ANY rules. I get access to Newsbank through my public library and use it frequently. Again, the code would in NO way break any sort of rules. 

I planned on putting download speed threshold of 750KB/s and a 10 second interval between each download. My plan was to just let this thing run for a few days as I used my desktop. Now, I am a noob, so maybe that is harmful in some way I am not seeing. But, as I am trying to learn how to build such a program Co-Pilot is INCESSANT about ethical practices. And, the problem is that literally every message between us is begun and/or endcapped by a 1 or 2 paragraph response about scraping ethically. 

Someone could correct me if I am wrong, but this eats up the limited token space available. I mean, roughly 1/4 to 1/3 of our back-and-forth is Co-Pilot lecturing me about the ethics of scraping, despite the fact that I showed co-pilot the robots.txt file from NewsBank, along with the format of all of the articles I would be downloading, and it AGREED I was within compliance of the file. Then, when the tokens run out of that conversation  and I can't add anymore, I have to start the whole process over again, of convincing the thing I am in compliance with their terms of service and scraping policy. 

All I am trying to do is gather data on incidents of police shooting unarmed people. This seems like a worthwhile academic pursuit that is being hindered by an overzealous ethical program. So, I hope that there is SOMETHING that can be done about this. Maybe allow for some way of uploading the robots.txt file and terms of service to Co-Pilot so that it can confirm or deny the ethical nature of the scrape. Or at the very least, limit the ethical warnings to once at the beginning. I don't understand why I am CONSTANTLY having be reminded about how to scrape ethically, and being chastised simply because I want a lot of data that is available to me through my public library (Pikes Peak Regional Library if anyone wants to confirm).  

My ultimate goal was to use some other fancy Python tools to asses the data in some way (no idea how,  yet, and that's not the point; I am still learning about the possibilities). Now, I know that some people could take the code that is given to them for one site, and use it on an unauthorized site. But, I imagine if a person is capable of altering some code to use nefariously, they are not dependent on Co-pilot to do so. And, that someone MAY use the code nefariously doesn't seem like a legitimate reason to prevent authorized use. I mean, pedophiles use TAILS and TOR, does that mean we should deny these tools to dissidents, whistleblowers, journalists, and free speech advocates? 

Again, I'm new to all of this, so maybe I am just being an idiot. That is always a possibility. It is just so frustrating to have a large portion of my AI interaction be the same repetitive crap that it says EVERY interaction. I think a single admonishment at the start of the conversation should be sufficient. And, now I'll stop being repetitive and leave it to the community to decide. Cheers.

**Comment by ulugbekna** [comment]
Thank you for bringing this to our attention. We appreciate your feedback and understand your concerns. Copilot Chat leverages a large language model (LLM), which, while advanced, can occasionally make mistakes. We continuously strive to improve its accuracy and performance, and your input is invaluable in this process.
