### ISSUE TITLE
Visual bug for context menu for code

### ISSUE THREAD

**Issue by issamansur** [microsoft/vscode-copilot-release#1328]
- Copilot Chat Extension Version: v0.16.1 (latest and previous versions have bug)
- VS Code Version: 1.90.2 (latest and previous versions have bug)
- OS Version: Windows 11 Pro 10.0.22631
- Logs: no needed

Steps to Reproduce:

1. Open `VSCode` (latest or previous)
2. Install `Copilot` extension (latest or previous)
3. Open right panel and change location to right side by holding
![image](https://github.com/microsoft/vscode-copilot-release/assets/77580844/16255cdf-a992-4d91-9147-6a04b1c3461d)
![image](https://github.com/microsoft/vscode-copilot-release/assets/77580844/d89ab504-3786-4a78-8423-602eceb86594)
4. Write any request/query in the chat, to which the `Copilot` will respond with an example of code
![image](https://github.com/microsoft/vscode-copilot-release/assets/77580844/eb94a7fc-3356-4c21-a501-c90b667f49f8)
5. Open context menu by right click on some text/place on second half
![image](https://github.com/microsoft/vscode-copilot-release/assets/77580844/e6857eb8-b763-40d6-b81d-017faf5f9d58)

**Comment by issamansur** [comment]
One more problem in last version of Copilot for context menu of  horizontal scroller:
![image](https://github.com/user-attachments/assets/76cdae5e-d2bc-4936-a9fe-bf25e00e8d38)
![image](https://github.com/user-attachments/assets/5cd9969b-afa1-4d5b-8c7b-2121778db6cd)

**Comment by sbatten** [comment]
I believe this is fixed.
