### ISSUE TITLE
Unable to press vote down button when response is filtered

### ISSUE THREAD

**Issue by dlemstra** [microsoft/vscode-copilot-release#133]
![afbeelding](https://github.com/microsoft/vscode-copilot-release/assets/10426229/db95558e-138d-4e6b-9cdc-1852abc080a8)

I am getting this message but I don't see a vote down button to report that this shouldn't have happened.

**Comment by psj-dev** [comment]
I'm experiencing the same thing

**Comment by Akash1134** [comment]
For better tracking: Similar feedback from the Copilot community: https://github.com/orgs/community/discussions/56134

**Comment by roblourens** [comment]
Should be fixed by now
