### ISSUE TITLE
copilot Chat Stops response

### ISSUE THREAD

**Issue by nanotecheg** [microsoft/vscode-copilot-release#1331]
- Copilot Chat Extension Version: v0.16.2024061102 (pre-release)
- VS Code Version: 1.90.2
- OS Version: ubuntu 22.04
- Logs:
2024-06-23 14:14:14.580 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1181 ms
2024-06-23 14:14:21.346 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-06-23 14:14:21.347 [info] [streamChoices] request done: requestId: [46d8fa7d-c61e-48bc-acd0-cdf5f1a2701e] model deployment ID: []

Steps to Reproduce:

1.
2.
![Screenshot from 2024-06-23 14-15-10](https://github.com/microsoft/vscode-copilot-release/assets/162161076/6a85715a-21e8-4798-b2a5-394ea2401879)
it stops and do that all time and sure my network and internet connection is good

**Comment by nanotecheg** [comment]
it is very annoying  really i keep stop and resend question again and again to respond

**Comment by digitarald** [comment]
@nanotecheg as a first step move from Chat pre-release to the stable version, which is recommended as you use VS Code's stable release.

![image](https://github.com/user-attachments/assets/dc7dcc51-63e3-4fad-9efa-1270dc97a0da)

@alexdima could this be networking related?

**Comment by alexdima** [comment]
@nanotecheg Are there any errors in Developer Tools? The UI appears to indicate that it is still processing the response (the square icon).

**Comment by nanotecheg** [comment]
@alexdima  now i use release version for weeks but i noticed that when open large file and send Request it stops but if i attached the file and open any empty file or even any extension  page copilot chat respond

**Comment by roblourens** [comment]
I'd expect that this is fixed, please lmk if it's still an issue
