### ISSUE TITLE
I hope coplit can check the code I am currently writing for code errors or logical errors.

### ISSUE THREAD

**Issue by z505985755** [microsoft/vscode-copilot-release#1334]
For example, I use javascript to write a comment if a=1, but the code is written as if(a=1), coplit will prompt that there may be a problem with this code

**Comment by ulugbekna** [comment]
Thank you for feedback! Errors are reported by language extensions such as Typescript or Python extensions. Copilot will help you fix those errors, however.

**Comment by z505985755** [comment]
No, I mean to identify logical errors, not syntactic errors. Language extensions can identify syntactic errors, but not logical errors.

**Comment by z505985755** [comment]
> No, I mean to identify logical errors, not syntactic errors. Language extensions can identify syntactic errors, but not logical errors.

No, I mean to identify logical errors, not syntactic errors. Language extensions can identify syntactic errors, but not logical errors.

**Comment by z505985755** [comment]
> Thank you for feedback! Errors are reported by language extensions such as Typescript or Python extensions. Copilot will help you fix those errors, however.

No, I mean to identify logical errors, not syntactic errors. Language extensions can identify syntactic errors, but not logical errors.
