### ISSUE TITLE
Copilot completions should see a workspace

### ISSUE THREAD

**Issue by charlesroddie** [microsoft/vscode-copilot-release#1335]
Currently copilot completions see content in opened files but not an entire workspace.

It should be possible to load a workspace (via a command, automatically, via an org-generated file - any method would be OK) and therefore get completions which:
1. Adapt to coding conventions of a workspace which may differ from typical code in that programming language.
2. Can generate better code in a workspace since this is often similar to other code in the same workspace.

Existing work involving workspaces has focused on chat and the more futuristic features of AI creation of pull requests. However code completion enables a lot of developer productivity and shouldn't be ignored.

**Comment by mjbvz** [comment]
Please file this feature request against the Copilot extension as it provides these completions: https://github.com/community/community/discussions/categories/copilot
