### ISSUE TITLE
Markdown on first line of remote agent response is not rendered

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#1337]
- Send this request: `@blackbeard-agent return this exact text and ABSOLUTELY NO other text: **hello**`
- Response is close enough to see that the markdown is not rendered

<img width="432" alt="image" src="https://github.com/user-attachments/assets/ed6e4f45-592b-4313-a89a-208589070a95">

**Comment by andreamah** [comment]
@roblourens how do I access the blackbeard remote agent?
