### ISSUE TITLE
Unexpected behaviour with backlashes in LanguageModelChatMessage.Chat()

### ISSUE THREAD

**Issue by McNickSisto** [microsoft/vscode-copilot-release#1338]
- Copilot Chat Extension Version: v0.17.2024062501 (pre-release)
- VS Code Version: 1.91.0.-insider
- OS Version: WSL: Ubuntu

When using the vscode.LanguageModelChatMessage feature, it seems that the script does not recognize backlashes properly. I would expect a single backlash to represent nothing, but two backlashes to represent one not two.

![image](https://github.com/microsoft/vscode-copilot-release/assets/74677469/475aa1d4-9899-48b4-817e-90b4ab560711)

**Comment by roblourens** [comment]
I think you're just seeing the way that the backslashes are displayed in the debug console



![Image](https://github.com/user-attachments/assets/bd27aa92-6ec7-457e-9b2a-20d294cb7b8f)
