### ISSUE TITLE
Heap's Algorithm bug

### ISSUE THREAD

**Issue by LaurenceMason** [microsoft/vscode-copilot-release#1347]
- Copilot Chat Extension Version: v1.208.0
- VS Code Version:  1.90.2
- OS Version: Windows 10 Enterprise 22H2
- Logs:

Steps to Reproduce:

1. Rust - start a new rust project. cargo new perms_test.
2. Delete the code from the main.rs file.
3. Ask Copilot to generate Heap's Algorithm as an iterator.

Fix:
1. The last permutation is not returned because the last expression of the 'next' is 'None'.
4. The last expression of the 'fn next' should be 'Some(result)' rather than 'None'
5. The tests do not detect this because 'zip' only zips the shortest of the two sequences.
6. The tests need to also check that the count of the permutations == the length of the expected permutations.

**Comment by ulugbekna** [comment]
Thank you for bringing this to our attention. We appreciate your feedback and understand your concerns. Copilot Chat leverages a large language model (LLM), which, while advanced, can occasionally make mistakes. We continuously strive to improve its accuracy and performance, and your input is invaluable in this process.
