### ISSUE TITLE
Copilot stopped working after switching from personal subscription to seat in company organization

### ISSUE THREAD

**Issue by vitobotta** [microsoft/vscode-copilot-release#1350]
Until a few days ago Copilot was working fine for me with VsCode stable version. I cancelled my subscription since the company added a seat to the company organization so they would pay for Copilot instead of me.

Since then, Copilot has stopped working and I got the error "Unable to resolve model with family selection: gpt-4".

Following https://github.com/microsoft/vscode-copilot-release/issues/1294 I also tried the latest Insider version of VsCode with the latest pre-release extensions for Copilot, ma no luck yet. At the moment with either version of VsCode the chat tab is black with the input field and I cannot start a conversation. Sometimes if I log out from Github and log in again in VsCode then I see a previous conversation with the gpt error above, but then the chat panel becomes black again and I only see the input field but nothing happens and I cannot create a new conversation. Right now I tried again and I can start a conversation again but I get the same gpt error as above.

- Copilot Chat Extension Version:
v0.17.2024062801
- VS Code Version:
Tried with both  1.91.0-insider and  1.90.2 
- OS Version:
macOS Sequoia b2
- Logs:
As stated in the other issue linked to above, I don't see a "Developer: GitHub Copilot Chat Diagnostics" item in my command palette so I don't know how to produce useful logs. Please advise.

I haven't been able to use Copilot for a few days now so thanks in advance for your help.

**Comment by vitobotta** [comment]
Update: it seems that the inline code suggestions are working now, but the chat is not.

**Comment by lramos15** [comment]
Your company needs to enable chat. Have they done so?

**Comment by vitobotta** [comment]
> Your company needs to enable chat. Have they done so?

That was it, thanks! My colleague who enabled the seats didn't know this. :)
