### ISSUE TITLE
Quick chat ignores "Github › Copilot › Chat: Locale Override" when ONLY using slash command without additional string.

### ISSUE THREAD

**Issue by ZetabS** [microsoft/vscode-copilot-release#1354]
- Copilot Chat Extension Version: v0.16.1
- VS Code Version: 1.90.2
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Set "Github › Copilot › Chat: Locale Override" to "ko". (or change vscode display language)
2. Write a simple code.
3. Select the code.
4. Press Ctrl + i.
5. Enter /explain

Expected:
Response in the language set by the "Locale Override" (in my case, Korean), similar to the behavior in the "Chat View".
![2024-06-29 14 52 20](https://github.com/microsoft/vscode-copilot-release/assets/55911793/e395724c-0026-4b2d-a91c-9256592307ab)

Actual:
Response is in English.
![2024-06-29 14 07 37](https://github.com/microsoft/vscode-copilot-release/assets/55911793/00aaac90-d747-445e-a579-85608b0e6fa7)

**Comment by joyceerhl** [comment]
I am unable to reproduce this behavior, could you please let us know if this still occurs for you?
