### ISSUE TITLE
Jumping Line UX improvement

### ISSUE THREAD

**Issue by peersky** [microsoft/vscode-copilot-release#1355]
I find it terrible trend in LLM models to generate stream of text that **consistently keeps on moving during generation**. 

While this allows me to catch the first line quicker, eventually text moves too fast, and working with Copilot actively for a month now, I can feel how badly it hurts my eyes, I basically have to look somewhere else to avoid seeing these jumping lines. 

Nevertheless, I appreciate having early output. 

What would be desired: 

1. Clear the page
2. Move cursor to the top left corner of the outputs widget  
3. Disable auto-scrolling of copilot output widget 
4. Start generating text top to bottom
5. If text overflows the visible screen it's okey: no-one reeds that fast

**Comment by roblourens** [comment]
I agree, would like to improve this: https://github.com/microsoft/vscode-copilot-release/issues/138
