### ISSUE TITLE
Inconsistent Responses in Different Languages for Programming-Related Questions

### ISSUE THREAD

**Issue by ReiRev** [microsoft/vscode-copilot-release#1356]
- Copilot Chat Extension Version: v0.16.1
- VS Code Version: 1.90.2 (Universal)
- OS Version:  macOS Sonoma 14.2.1 
- Logs:

Steps to Reproduce:

1. Enter the query “MUIのxsとはどういう意味ですか？また、xsは何の略ですか？” in Japanese in GitHub Copilot Chat.
2. Observe the response “Sorry, but I can only assist with programming related questions.”
3. Enter the equivalent query in English “What does xs in MUI mean? What does it stand for?”, which has the same meaning as the above Japanese questions.
4. Note that a proper response is provided in English.

Not limited to this specific question, the same issue occurs with many Japanese queries.

Expected Behavior: GitHub Copilot should provide consistent responses for programming-related queries regardless of the language used.

**Comment by mjbvz** [comment]
Is your editor in Japanese? Have you tried configuring the `github.copilot.chat.localeOverride` setting to specific Japanese explicitly?

**Comment by mjbvz** [comment]
Closing as we haven't heard back. It's possible that you just need to configure the language setting for these cases
