### ISSUE TITLE
Inline Suggestions Stopped Working

### ISSUE THREAD

**Issue by CSWinnall** [microsoft/vscode-copilot-release#1359]
Hi

As of 01/07/2024 my inline suggestions stopped working in vsCode.  
When I use ctrl+enter I always get this now:
![image](https://github.com/microsoft/vscode-copilot-release/assets/10554243/183ab5e8-190f-4e43-98c4-fab878b5efc7)

Here are the logs:
![image](https://github.com/microsoft/vscode-copilot-release/assets/10554243/ef79fc08-484b-4196-abc2-7cb95cddd92a)

I have checked my json settings and inline suggestion is true:
![image](https://github.com/microsoft/vscode-copilot-release/assets/10554243/1e34c140-82e3-49f8-8840-61d25867828f)

I have reload vsCode disabled, enabled the extensions uninstalled and reinstalled and tried the pre-release version.

Craig

**Comment by CSWinnall** [comment]
Hi 
This has started working again not sure why.
Craig

**Comment by CSWinnall** [comment]
No I was mistaken it is still an issue

**Comment by roblourens** [comment]
This repo is just for Copilot Chat. You can bring this up at https://github.com/community/community/discussions/categories/copilot
