### ISSUE TITLE
Support allowing other CA Certificates

### ISSUE THREAD

**Issue by jtele2** [microsoft/vscode-copilot-release#136]
``

GitHub CoPilot Chat does not work behind a corporate proxy that injects it's own CA Certificates into the trusted certificate root chain on WSL 2. I'm not sure what trusted certificate chain it is using, but the only way I could get it to work was by using this hack provided by this gist:

https://gist.github.com/sarimarton/55779cf95028860ea2126e61a6b377d0

This issue describes it in more detail, and this appears to be an issue with CoPilot in general.

https://gist.github.com/sarimarton/55779cf95028860ea2126e61a6b377d0?permalink_comment_id=4513487#gistcomment-4513487

**Comment by hstaudacher** [comment]
Self signed certificates are supported for Cfb users only right now. Is the user you are talking about a Cfb user? There is a simple way to find out. Just run this command in VSCode
<img width="724" alt="Screenshot 2023-06-07 at 09 36 18" src="https://github.com/microsoft/vscode-copilot-release/assets/289648/c72868eb-6c4f-422d-8e5f-28a4980cf1e0">
 and you should see section like this:
```md
## Feature Flags

- Self Signed Certificates: enabled
- Send Restricted Telemetry: disabled
```
If Self Signed Certificates is enabled the user is a Cfb user.

**Comment by kkroner8451** [comment]
We have seen this same issue and are Copilot for Business users. When we run the diagnostics we see that Self Signed Certificates are enabled. The Copilot for Business extension works fine and respects machine level certificates and the NODE_EXTRA_CA_CERTS setting that points to a bundle of these self-signed proxy certificates. However, the GitHub Copilot Chat extension does not appear to respect those settings and fails to activate.

**Comment by chrmarti** [comment]
The default settings for GitHub Copilot Chat now support this. Please open a new issue if this is still a problem.
