### ISSUE TITLE
Cant enter new messages, neither by using enter-key nor with clicking 'send' 

### ISSUE THREAD

**Issue by LukGer91** [microsoft/vscode-copilot-release#1360]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Used it to go through several code snippets to check for possible errors
2. After some code snippets I wanted some further explanation in the chat and could not send my message

**Comment by roblourens** [comment]
Can you include a screenshot? And ensure that you have the latest versions of everything? We just did another VS Code release today, you can try that.

Can you also check for errors in the Window output channel?

**Comment by roblourens** [comment]
Did you see this issue again?
