### ISSUE TITLE
Extension activation failed: "getaddrinfo ENOTFOUND api.github.com"

### ISSUE THREAD

**Issue by KuldeepSankhala** [microsoft/vscode-copilot-release#1363]
Type: <b>Bug</b>

getting following error while connecting to Copilot from VS Code - 2024-07-02 18:20:15.371 [error] [auth] Extension activation failed: "getaddrinfo ENOTFOUND api.github.com"

Extension version: 0.16.1
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (0.58GB free)|
|Process Argv|--crash-reporter-id 5e3765a2-e09b-43f9-83f3-6066527688b3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31082724

```

</details>

**Comment by KuldeepSankhala** [comment]
Adding more details on Error - 

2024-07-02 18:36:05.051 [error] [auth] Extension activation failed: "getaddrinfo ENOTFOUND api.github.com"
2024-07-02 18:36:07.680 [error] [default] Error sending telemetry FetchError: getaddrinfo ENOTFOUND copilot-telemetry.githubusercontent.com
    at fetch (c:\Users\xxxxx\.vscode\extensions\github.copilot-1.208.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:99:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at cachingFetch (c:\Users\xxxxx\.vscode\extensions\github.copilot-1.208.0\node_modules\@adobe\helix-fetch\src\fetch\index.js:288:16)
    at xq.fetch (c:\Users\xxxxx\.vscode\extensions\github.copilot-1.208.0\lib\src\network\helix.ts:88:22) {
  type: 'system',
  _name: 'FetchError',
  code: 'ENOTFOUND',
  errno: -3008,
  erroredSysCall: 'getaddrinfo'
}

**Comment by lramos15** [comment]
Do you have a firewall? This is saying you cannot DNS resolve the github domainn

**Comment by KuldeepSankhala** [comment]
Thanks. 
Yes, it was an issue with the proxy. Once I updated it, the problem was resolved.

**Comment by KuldeepSankhala** [comment]
Problem resolved after updating proxy.
