### ISSUE TITLE
Inline Chat fails instantly with no results

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#1365]
Type: <b>Bug</b>

Applying Inline Chat to a markdown file:

![Image](https://github.com/user-attachments/assets/5caeb127-cc61-4430-b4ec-7cabda306946)

Related log:

[Extension Host] [extension] Inline chat request is missing context information undefined undefined undefined (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:144:47717))

Extension version: 0.17.2024062801
VS Code version: Code - Insiders 1.92.0-insider (e6a828c5957959b7a18de37a567d850880101641, 2024-07-03T19:58:19.052Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 5|
|Memory (System)|64.00GB (6.98GB free)|
|Process Argv|--log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ulugbekna** [comment]
Please, update your extension to latest version (released today).

**Comment by andreialecu** [comment]
Still seeing this issue as of July 29 2024 on `v0.17.1` of the extension:

```
2024-07-29 11:42:35.046 [info] [extension] Inline chat request is missing context information, undefined, undefined, undefined
```

![CleanShot 2024-07-29 at 11 44 41@2x](https://github.com/user-attachments/assets/2a1431f4-b96c-43f1-9087-c8815ae7f1a4)
