### ISSUE TITLE
Asking for Markdown result will mess up the formatting

### ISSUE THREAD

**Issue by tom-nijhof** [microsoft/vscode-copilot-release#1367]
- Copilot Chat Extension Version: v0.17.0
- VS Code Version: 1.90.2
- OS Version: Windows 11
- Logs:
- 

Steps to Reproduce:

1. Ask for some result in markdown like "Give me a formula to go from celsius to Fahrenheit in markdown"
2. It will start okay but it will close its own markdown with the result
3. Looks like a markdown injections

![image](https://github.com/microsoft/vscode-copilot-release/assets/143697732/bb2e8c7b-c319-438a-8192-018205d48d3f)
![image](https://github.com/microsoft/vscode-copilot-release/assets/143697732/a4cf9e51-b1a2-434c-bcaa-e7e5bfca7f5a)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/793
