### ISSUE TITLE
Copilot is rude or doesn't respond for non-English requests

### ISSUE THREAD

**Issue by lzeal** [microsoft/vscode-copilot-release#1369]
If reqest is made in Ukrainian coplilot responds with only a code example or sais "Sorry, I can't assist with that.". The same question in English get complete responce with code and explanations. That's rude. He perfectly understands Ukrainian and I had a lot of conversations with him in that language before.

**Comment by ulugbekna** [comment]
The chat filters out non-programming related questions and requests, but it should speak different languages. 



![Image](https://github.com/user-attachments/assets/5b77db34-d94d-4993-8f67-7219ad9eb37c)
