### ISSUE TITLE
Make chat field full width again

### ISSUE THREAD

**Issue by imranbarbhuiya** [microsoft/vscode-copilot-release#137]
I use copilot chat at bottom position and it was working fine. But today it's size got reduced. Please make it full width again

![image](https://github.com/microsoft/vscode-copilot-release/assets/74945038/236262f7-e61b-46d4-a934-7091d75298f3)

**Comment by roblourens** [comment]
Most people prefer to read text in columns rather than one line across the screen. But this can probably be improved. Comments welcome here:

https://github.com/microsoft/vscode-copilot-release/issues/60
