### ISSUE TITLE
Apply in Editor very slow

### ISSUE THREAD

**Issue by james-berkheimer** [microsoft/vscode-copilot-release#1371]
- Copilot Chat Extension Version: v0.17.0
- VS Code Version: 1.91.0
- OS Version: Windows 10 Pro 19045.4529
- Logs:

Steps to Reproduce:

1. In a chat response, click the "Apply in editor" button.
2.  A progress window pops up and the applied code takes 1-3 seconds to apply.

Not sure if anyone else is having this issue.  But this function used to be instantaneous.  But now it takes a noticeable amount longer to apply the code into the editor.

**Comment by PKC278** [comment]
Same question.
GitHub Copilot Chat Extension Version: v0.17.0
GitHub Copilot Extension Version: v1.211.0
VS Code Version: 1.91.0
OS Version: MacOS 14.5

**Comment by alexrosen** [comment]
This started happening for me as well with the latest (7/5) release.

I'll add that the button to apply now also frequently does not replace the selection, but puts the code in random locations in the file about half the time. 

I'm now having to do copy/paste instead of Apply in Editor.

GitHub Copilot Chat Extension Version: v0.17.0
GitHub Copilot Extension Version: v1.211.0
VS Code Version: 1.91.0 (user setup)
Running in Edge on Windows 11 Home Version 10.0.22631 Build 22631

**Comment by aeschli** [comment]
What's new is that we now use the LLM to figure out the best way to apply the change.

**Comment by james-berkheimer** [comment]
> What's new is that we now use the LLM to figure out the best way to apply the change.

I dunno, I liked it using that as a way to insert the code at my prompt.  I rarely used the copy button because that's just extra clicks I don't want to make.  

Also, I'm not sure I see the benefit of having the LLM apply the code as it sees fit.  I just want to ask chat my questions and then decide on my own how best to apply the output.  The reason for this is that I will still have to review what Copilot does to my code regardless.  So it's not saving me any work.  Maybe I'm alone in this.  But after a year of using Copilot, I'd much rather it be focused on giving me answers rather than figuring out how it can manipulate my code for me.  Just my two cents.

**Comment by Atelier-Mx** [comment]
same problem, and when apply make a code disaster in another code zones

**Comment by aeschli** [comment]
We now offer two separate commands: `Apply In Editor` and `Insert at Cursor`

(Internal issue: https://github.com/microsoft/vscode-copilot/issues/6695)
