### ISSUE TITLE
Github copilet gives "Unable to resolve chat model with family selection: gpt-4"

### ISSUE THREAD

**Issue by 8Klaro8** [microsoft/vscode-copilot-release#1377]
**PLEASE NOTE:**
I read about this problem, and I found this issue:
https://github.com/microsoft/vscode-copilot-release/issues/1294
It has been closed and was mentioned by: [chrmarti](https://github.com/chrmarti) to create new issue, therefore I did so. 

When I restart VSC and I try to type into the chat it says:  Unable to resolve chat model with family selection: gpt-3.5-turbo, then if I type again it says: Unable to resolve chat model with family selection: gpt-4, although I did not subscribe to chatGTP.

**Based on the suggestions I switched to pre-release version. I tried to open "Developer: GitHub Copilot Chat Diagnostics" but I got this:**
- "Command 'Developer: GitHub Copilot Chat Diagnostics' resulted in an error command 'github.copilot.debug.collectDiagnostics' not found.

**INFO**
- Copilot Chat Extension Version: v1.211.978 (pre-release)
- VS Code Version: 1.91.0 (user setup)
- OS Version: Windows_NT x64 10.0.19045
- Logs:

## Copilot

- Version: 1.211.978
- Build: nightly
- Editor: vscode/1.91.0

## Environment

- http_proxy: n/a
- https_proxy: n/a
- no_proxy: n/a
- SSL_CERT_FILE: n/a
- SSL_CERT_DIR: n/a
- OPENSSL_CONF: n/a

## Feature Flags

- Send Restricted Telemetry: disabled
- Chat: enabled

## Node setup

- Number of root certificates: 146
- Operating system: Linux
- Operating system version: 5.15.153.1-microsoft-standard-WSL2
- Operating system architecture: x64
- NODE_OPTIONS: n/a
- NODE_EXTRA_CA_CERTS: n/a
- NODE_TLS_REJECT_UNAUTHORIZED: n/a
- tls default min version: TLSv1.2
- tls default max version: TLSv1.3

## Network Configuration

- Proxy host: n/a
- Proxy port: n/a
- Kerberos SPN: n/a
- Reject unauthorized: disabled
- Fetcher: HelixFetcher

## Reachability

- github.com: HTTP 200
- api.github.com: HTTP 200
- copilot-proxy.githubusercontent.com: HTTP 200
- api.githubcopilot.com: self-signed certificate in certificate chain
- default.exp-tas.com: HTTP 200

## VS Code Configuration

- HTTP proxy: 
- HTTP proxy authentication: n/a
- Proxy Strict SSL: true
- Extension HTTP proxy support: override

## Extensions

- Is `win-ca` installed?: true
- Is `mac-ca` installed?: true

## Authentication

- GitHub username: 8Klaro8

Steps to Reproduce:

1. Install Github copilot
2. Type something the chat field and press enter

**Comment by chrmarti** [comment]
@8Klaro8 You seem to be connected to WSL. Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) in WSL and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code for the two URLs:
- `https://api.githubcopilot.com`
- `https://copilot-proxy.githubusercontent.com`

(The diagnostics above show the first fail due to a certificate issue, but the second succeeds. Both have the same root certificate in their chain for me, so something appears to be different in your case.)

**Comment by 8Klaro8** [comment]
Hi @chrmarti !

Yes, I am using WSL, although the result is the same, when I try to use it without WSL.
The requested logs...

**https://api.githubcopilot.com**

- Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286)
Network Proxy Test 0.0.11
linux 5.15.153.1-microsoft-standard-WSL2 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://api.githubcopilot.com...
vscode-proxy-agent: DIRECT
Received error: read ECONNRESET (ECONNRESET)
Retrying while ignoring certificate issues to collect information on the certificate chain.

Sending GET request to https://api.githubcopilot.com (allowing unauthorized)...
vscode-proxy-agent: DIRECT
Received error: read ECONNRESET (ECONNRESET)

**https://copilot-proxy.githubusercontent.com**

- Note: Make sure to replace all sensitive information with dummy values before sharing this output.

VS Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286)
Network Proxy Test 0.0.11
linux 5.15.153.1-microsoft-standard-WSL2 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:

Sending GET request to https://copilot-proxy.githubusercontent.com...
vscode-proxy-agent: DIRECT
Received response:
- Status: 404 
Certificate chain:
- Subject: *.githubusercontent.com (GitHub, Inc.)
  Subject alt: DNS:*.githubusercontent.com, DNS:githubusercontent.com
  Validity: Jun 20 00:00:00 2024 GMT - Jun 19 23:59:59 2025 GMT
  Fingerprint: 01:72:81:80:B7:7B:99:17:D1:47:27:D0:F1:A6:A4:D5:A5:91:9B:3E
- Subject: DigiCert Global G2 TLS RSA SHA256 2020 CA1 (DigiCert Inc)
  Validity: Mar 30 00:00:00 2021 GMT - Mar 29 23:59:59 2031 GMT
  Fingerprint: 1B:51:1A:BE:AD:59:C6:CE:20:70:77:C0:BF:0E:00:43:B1:38:26:12
- Subject: DigiCert Global Root G2 (DigiCert Inc)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Self-signed
Local root certificates:
- Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2 (OS)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2


If there is anything else I can assist with, let me know.

**Comment by chrmarti** [comment]
The error in this case is ECONNRESET unlike before where it was "self-signed certificate in certificate chain".

Are you behind a firewall that might need to allow-list api.githubcopilot.com?

**Comment by itsalljustdata** [comment]
If I can piggyback into this one -i've got the same issue...

This is in a devcontainer (mcr.microsoft.com/devcontainers/python:3.11-bookworm) running on a debian machine, and i'm connecting from Win11


_Network Proxy Test Output_

```
VS Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286)
Network Proxy Test 0.0.11
linux 6.1.0-22-amd64 x64

Settings:
- http.proxy: 
- http.proxyAuthorization: null
- http.proxyStrictSSL: true
- http.proxySupport: override
- http.systemCertificates: true

Environment variables:
```

```
Sending GET request to https://copilot-proxy.githubusercontent.com...
vscode-proxy-agent: DIRECT
Received response:
- Status: 404 
Certificate chain:
- Subject: *.githubusercontent.com (GitHub, Inc.)
  Subject alt: DNS:*.githubusercontent.com, DNS:githubusercontent.com
  Validity: Jun 20 00:00:00 2024 GMT - Jun 19 23:59:59 2025 GMT
  Fingerprint: 01:72:81:80:B7:7B:99:17:D1:47:27:D0:F1:A6:A4:D5:A5:91:9B:3E
- Subject: DigiCert Global G2 TLS RSA SHA256 2020 CA1 (DigiCert Inc)
  Validity: Mar 30 00:00:00 2021 GMT - Mar 29 23:59:59 2031 GMT
  Fingerprint: 1B:51:1A:BE:AD:59:C6:CE:20:70:77:C0:BF:0E:00:43:B1:38:26:12
- Subject: DigiCert Global Root G2 (DigiCert Inc)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Self-signed
Local root certificates:
- Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2 (OS)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2
```

```
Sending GET request to https://api.githubcopilot.com...
vscode-proxy-agent: DIRECT
Received response:
- Status: 404 Not Found
Certificate chain:
- Subject: *.githubcopilot.com (GitHub, Inc.)
  Subject alt: DNS:*.githubcopilot.com, DNS:githubcopilot.com
  Validity: Aug 16 00:00:00 2023 GMT - Aug 16 23:59:59 2024 GMT
  Fingerprint: 54:59:1F:F1:6B:26:2F:B0:BC:68:70:BE:9F:E9:06:B3:37:7A:8A:9D
- Subject: DigiCert Global G2 TLS RSA SHA256 2020 CA1 (DigiCert Inc)
  Validity: Mar 30 00:00:00 2021 GMT - Mar 29 23:59:59 2031 GMT
  Fingerprint: 1B:51:1A:BE:AD:59:C6:CE:20:70:77:C0:BF:0E:00:43:B1:38:26:12
- Subject: DigiCert Global Root G2 (DigiCert Inc)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Self-signed
Local root certificates:
- Subject: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2 (OS)
  Validity: Aug  1 12:00:00 2013 GMT - Jan 15 12:00:00 2038 GMT
  Fingerprint: DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
  Issuer: C=US O=DigiCert Inc OU=www.digicert.com CN=DigiCert Global Root G2
```

**Comment by chrmarti** [comment]
@itsalljustdata That looks different. Could you open a new issue? Thanks.

**Comment by Neautrino** [comment]
@8Klaro8 I am also encountering the same issues in my WSL.

## Problem Description
1. Open VS Code in WSL
2. Try to use Copilot chat or fix issues
3. Receive error: "Unable to resolve chat model with family selection: gpt-3.5-turbo"

## Solution
The issue was resolved by:
1. Installing GitHub CLI:
``` sudo apt install gh ```
2. Authenticating with GitHub:
``` gh auth login ``` 
3. Restarting VS Code

**Comment by 8Klaro8** [comment]
> The error in this case is ECONNRESET unlike before where it was "self-signed certificate in certificate chain".
> 
> Are you behind a firewall that might need to allow-list api.githubcopilot.com?

Yes.

**Comment by chrmarti** [comment]
Make sure you get all the required hosts allow-listed: https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot. HTH!
