### ISSUE TITLE
Copilot cannot open file when using the @Workspace command

### ISSUE THREAD

**Issue by SawyerNic** [microsoft/vscode-copilot-release#1379]
When using the @Workspace command for my project it will always answer with 'cannot open file' even when asking about something related or unrelated, why doesn't it skip the file instead of throwing an error for the whole query. It will start to answer but stop (usually in the middle of a sentence) when it cannot read a certain file.

![Screenshot 2024-07-10 at 3 56 20 PM (2)](https://github.com/microsoft/vscode-copilot-release/assets/111994367/8cbe1543-867d-464c-94b2-fd394dd81192)

**Comment by mjbvz** [comment]
What VS Code version and Copilot extension version are you using?

**Comment by SawyerNic** [comment]
VS Code Version: v1.90.0 
Github Copilot Chat: v0.16.1

**Comment by mjbvz** [comment]
Thanks. Please try out the latest insiders release of the chat extension. I believe this should be fixed now
