### ISSUE TITLE
Chat is hard to read while scrolling

### ISSUE THREAD

**Issue by GooberFromHell** [microsoft/vscode-copilot-release#138]
### Description:
Currently, the Copilot chat windows in VSCode lacks any scroll or transition effects. Which, in conjunction with the speed at which Copilot "types" the response, causes the text to pass to quickly forcing the user to wait until the "typing" is completed before beginning to read the response. This creates a, minor, but unpleasant experience while using Copilot chat in between tasks and while waiting until completion to read and determine if the response is at all appropriate.

### Feature Requested:
Add extension options or documentation of the styling information, to allow the customization of how Copilot Chat responds. 

### Examples: 
- Default - Remain with no transitioning or response queueing.
- Smooth Scrolling - Create a smooth scroll transition when Copilot Chat enters a newline while "typing" a response.
- Instant - Hold response text generation until a full response is received and then post it to the chat window.
- Incremental - Post response text generation in blocks or sections.

**Comment by roblourens** [comment]
I don't think that smooth scrolling will help, I think that it will still be hard to read while the text is moving. I explored this a bit last month, one approach could be to scroll partway up when the response starts printing, so that it is less likely to have to scroll while the user is reading.

If we don't scroll automatically when the response reaches the bottom of the scroll container, then we should show a ⬇️ button to indicate that there is content below the fold.

I will explore this more next month

**Comment by digitarald** [comment]
@roblourens @daviddossett found the ChatGPT mobile app solves it nicely:

As the answer streams in:
a) by default, the top of the answer is the scroll snap point. Even as more lines stream in, the content doesn't move. The question can scroll off the screen.
b) once a user scrolls down, the scrolling snaps to the streaming text.

<img width="360" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/589ef4c7-ec79-430a-9a14-6e75d49adb08">

What helps is that the text input has streaming indicator, so the user knows when the response is complete.

**Comment by guillaume-mueller** [comment]
I don't understand how almost none complains about this, it's a huge ergonomic issue.

**Comment by istathar** [comment]
Would it be possible to just NOT autoscroll when generating an answer? Just let the pane grow below. The user can scroll down if they want to read more.

**Comment by Zitrax** [comment]
Gemini code assist seem to follow the "instant" example. It thinks a while and then all output comes in one go. I much more prefer that approach - at least an option for doing that instead would be nice.

**Comment by russeg** [comment]
I also want the instant reply, wait for it and dump it all. However do not scroll to the end of text! it does make sense since duh we don't read bottom to top!

**Comment by JeremyNahuel** [comment]
Echoing that this would be super beneficial!
