### ISSUE TITLE
Custom instructions

### ISSUE THREAD

**Issue by swimmer-303** [microsoft/vscode-copilot-release#1382]
ChatGPT has custom instructions. I would like that for Github Copilot. It is very annoying sometimes to keep telling Copilot to do something that should already happen.

**Comment by ksaitor** [comment]
agree. i'd set a custom instruction to: "show code snippet first. be concise. don't offer more than 2 sentences explaining the code"

**Comment by lramos15** [comment]
Duplicate #563
