### ISSUE TITLE
Error net::ERR_CONNECTION_RESET while using GitHub Copilot Chat

### ISSUE THREAD

**Issue by phalgunvaddepalli** [microsoft/vscode-copilot-release#1383]
- Copilot Chat Extension Version: v0.17.1
- VS Code Version:  vscode/1.91.1
- OS Version: Windows 11 23H2 (OS Build 22631.3737)
- Logs: Diagnostic command `F1 > Developer: GitHub Copilot Chat Diagnostics`
`## GitHub Copilot Chat

- Extension Version: 0.17.1 (prod)
- VS Code: vscode/1.91.1
- OS: Windows

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": true
  }
```

DNS Lookup api.githubcopilot.com: 140.82.112.21

Fetching https://api.githubcopilot.com/_ping:
- Electron Fetcher (configured): Error: net::ERR_CONNECTION_RESET
- Node Fetcher: Error: read ECONNRESET
- Helix Fetcher: Error: read ECONNRESET
`
Steps to Reproduce:

1. Attempting to use Github co-pilot chat causes the error "net::ERR_CONNECTION_RESET"

**Comment by chrmarti** [comment]
@phalgunvaddepalli Make sure your IT allows connections to all required hosts: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot)

**Comment by EvilCodeMorty** [comment]
Could you tell me more about your specific solution? I'm new. I'm new. It's the same mistake
