### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Kique261** [microsoft/vscode-copilot-release#1384]
- Copilot Chat Extension Version:1.213.0
- VS Code Version:1.91.0
- Logs:500 Internal Server Error

![屏幕截图 2024-07-13 090514](https://github.com/user-attachments/assets/d59221f9-c925-4132-ae94-8665676fd086)
Copilot can perfect worked yesterday, but reported this error this morning.
I opened vscode both in my win11 and wsl. They all reported this error.

**Comment by Kique261** [comment]
It can work now.

**Comment by czn43** [comment]
> It can work now.它现在可以工作了。
     I still  report 500 internal server errors 。 sad

**Comment by ZJU-shichuan** [comment]
I also report this.Will it be handled soon?

**Comment by MerielVaren** [comment]
plz fix it

**Comment by yuta-sakata** [comment]
no
[
![QQ截图20240713103158](https://github.com/user-attachments/assets/0de70a17-a38f-45ba-8cbb-e47447945b8d)
](url)

**Comment by Panda-Young** [comment]
![截图_20240713110532](https://github.com/user-attachments/assets/e61e84c2-8c34-4232-a2e3-5cf7dc7d9db4)

**Comment by yuta-sakata** [comment]
> ![截图_20240713110532](https://private-user-images.githubusercontent.com/22840862/348445749-e61e84c2-8c34-4232-a2e3-5cf7dc7d9db4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NDA1MTIsIm5iZiI6MTcyMDg0MDIxMiwicGF0aCI6Ii8yMjg0MDg2Mi8zNDg0NDU3NDktZTYxZTg0YzItOGMzNC00MjMyLWEyZTMtNWNmN2RjN2Q5ZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDAzMTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZDU2MjRlMzE0MTgwMjY4NzkyYWE4NTFkZGYyNDdlY2VlY2Y5OTczOWYwMWQ2MjE5M2JjNTQ2NDk1ZmQ0OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KGzfJKQprL4r-IduQOyIT3TzrFeDhEggh5dbklyCzHQ)

这个issue被关闭了，我新开了个issue反馈

**Comment by XipengYu** [comment]
![捕获](https://github.com/user-attachments/assets/701b79c0-2a48-4b1b-b3b6-57519c0c57e5)
I also report this

**Comment by roblourens** [comment]
This should be fixed- are you still seeing it?

**Comment by XipengYu** [comment]
copilot works now.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by JosephAdewole** [comment]
does not work for me. 400 and 500 errors intermittently

**Comment by chtoosha** [comment]
I also see this.

**Comment by dcode-me** [comment]
i am facing the same issue.
<img width="655" alt="Screenshot 2024-07-15 at 8 49 00 PM" src="https://github.com/user-attachments/assets/742e6092-cfd4-472c-8c59-fbd84eaa2e0e">

**Comment by roblourens** [comment]
Seems like this has come up again

**Comment by emitxyz** [comment]
<img width="457" alt="image" src="https://github.com/user-attachments/assets/8b4e48bc-a5eb-4aec-8095-115b90ef23c7">
<img width="465" alt="image" src="https://github.com/user-attachments/assets/f789dd32-9b39-4284-b256-638ac5d0392f">

Same - 500s and 400s

**Comment by suelife** [comment]
Same here.
![2024-07-16 08 51 51](https://github.com/user-attachments/assets/093f6a53-f189-40d4-813c-6e3f19b8bf33)

**Comment by suelife** [comment]
Same here.
![2024-07-16 08 51 51](https://github.com/user-attachments/assets/2eca0ef1-a7c2-4b85-a140-c96ef5610bad)

**Comment by Sherbieny** [comment]
Same here
500, 400 errors, also 'failed to make request'

**copilot autocomplete feature works fine**, but chat window and inline chat does not work (in files and cli)

info:
`
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
`

**Comment by emouawad** [comment]
same here

**Comment by hyummys** [comment]
![image](https://github.com/user-attachments/assets/8c35ba3f-47a8-4322-a63d-d6b6937d1c0d)
anyone got problem solved?

**Comment by dong-personal** [comment]
Same, hope it can be fixed sooner

**Comment by rantillon** [comment]
![image](https://github.com/user-attachments/assets/434c37b9-9c6d-4d64-999a-d36083fe6d9f)
Apparently this is happening again, an also:
![image](https://github.com/user-attachments/assets/5502a2f8-7a2d-441f-9a91-42372294f05c)

**Comment by Syu19** [comment]
same 500 and 400 errors.
damn, i thought it was my mistake

**Comment by Bistu-lt25680** [comment]
Shit,500error comes now

**Comment by nguyenduccangit** [comment]
I also got the same issues. Can not connect to github copilot.
![image](https://github.com/user-attachments/assets/45a8dcf0-75b2-443c-866a-da35e819b4de)

**Comment by kirtan-karmaflow** [comment]
Same for me

**Comment by czlx7** [comment]
Same for me,too

**Comment by kirtan-karmaflow** [comment]
> roblourens

Yes

**Comment by wusskk** [comment]
Same for me,too

**Comment by dazuiba** [comment]
First, I encountered a 400 Bad Request error. When I tried to reinstall VSCode Copilot, I then received a 500 Internal Server Error.

```

2024-07-16 09:20:46.329 [info] [auth] Logged in as xxxxx
2024-07-16 09:20:46.334 [info] [chat] copilot token chat_enabled: true
2024-07-16 09:20:46.334 [info] [auth] Got Copilot token for xxxxx
2024-07-16 09:22:05.885 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 5689 ms
2024-07-16 09:22:05.887 [info] [chat fetch] Request ID for failed request: , ebf6b18c-47e5-4bf2-a04f-71f42ec5e567
2024-07-16 09:25:14.340 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 26733 ms
2024-07-16 09:25:14.341 [info] [chat fetch] Request ID for failed request: , 0cc0c8b0-8c32-4487-82ec-047aa5298ccb
```

**Comment by XipengYu** [comment]
copilot  does not  work  now

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kumbiagit** [comment]
same for me as well. it went from a 400 error to 500

**Comment by hannahxuuu** [comment]
Same for me! Unfortunately have been getting 400 and 500 for the past hour

**Comment by hjKangIB** [comment]
same problem here. 500 or 400 Error

**Comment by dev-to2k** [comment]
same problem here

**Comment by zadamg** [comment]
same problem here

**Comment by Jikoc** [comment]
same problem here

**Comment by cyb3rjerry** [comment]
Yall please read the status page: https://www.githubstatus.com/

**Comment by YCChenVictor** [comment]
same problem here

**Comment by JustinTLT** [comment]
same here.

**Comment by KevinChungC** [comment]
same problem here.
![圖片](https://github.com/user-attachments/assets/48671708-f371-49ef-afe9-0ec08d510bd4)

I also check the status page when problem at the same time: https://www.githubstatus.com/
![圖片](https://github.com/user-attachments/assets/aca5472c-e3a4-430f-a15f-afb6bfe9193d)

**Comment by Zoey-Ying** [comment]
It seems a bug of copilot. Many people have this problem at the same time.

**Comment by Zoey-Ying** [comment]
> It seems a bug of copilot. Many people have this problem at the same time.

Switch to the release edition, it really works.

**Comment by TecReaGroup** [comment]
Yes, it seems like there are some errors with copilot, not our reasons

**Comment by TecReaGroup** [comment]
> > It seems a bug of copilot. Many people have this problem at the same time.
> 
> Switch to the release edition, it really works.

True, it works! Thanks!

**Comment by indrajithvinodnair** [comment]
Tried release and pre relaease versions, both have issues

**Comment by roblourens** [comment]
This should be fixed again. Sorry for the trouble.
