### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by thanhbtse** [microsoft/vscode-copilot-release#1385]
![Screenshot 2024-07-13 082058](https://github.com/user-attachments/assets/23c2da3f-8e4d-4428-9307-c2c40637a627)
i got this error in my copilot chat

**Comment by wanqingying** [comment]
same in my vscode .  but copilot works in idea

**Comment by ana-lapas** [comment]
chat ain't working here too.

**Comment by mhel33** [comment]
here too

**Comment by Knightluozichu** [comment]
me too

**Comment by iwangbowen** [comment]
the same and came here immediately

**Comment by dnafication** [comment]
+1

**Comment by dsoldera** [comment]
+1

**Comment by juansm3007** [comment]
me too

**Comment by nhokmoon** [comment]
I thought it was only me who caused this :+1:

**Comment by thanhbtse** [comment]
it work now

**Comment by iwangbowen** [comment]
If it doesn't work now, reinstall it
