### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by yuta-sakata** [microsoft/vscode-copilot-release#1386]
![QQ截图20240713103158](https://github.com/user-attachments/assets/50d1babc-ddef-4418-8683-501654183017)

**Comment by iwangbowen** [comment]
try reinstall the extension

**Comment by yuta-sakata** [comment]
> try reinstall the extension

I tried reinstalling the extension, but the problem still persists.

**Comment by Panda-Young** [comment]
+1

**Comment by Sun-0808** [comment]
+1

**Comment by JairoGt** [comment]
+1 I have the same problem

**Comment by Atelier-Mx** [comment]
+1 , mismo problema

**Comment by Oliver0804** [comment]
+1

**Comment by AnCial** [comment]
+1

**Comment by lramos15** [comment]
Apologies, there was a GitHub outage related to the Copilot services. This has since been resolved.
