### ISSUE TITLE
Unhandled status from server: 400 bad request

### ISSUE THREAD

**Issue by Jolanta27** [microsoft/vscode-copilot-release#1391]
- Copilot Chat Extension Version:
- VS Code Version: 
Version: 1.91.1 (Universal)
- OS Version: 
- 14.3.1 (23D60)
- Logs:

Steps to Reproduce:

1.
2.

**Comment by lramos15** [comment]
Apologies, there was a GitHub outage related to the Copilot services. This has since been resolved.
