### ISSUE TITLE
unhandled status from server: 400 Bad Request

### ISSUE THREAD

**Issue by 123GHLJ** [microsoft/vscode-copilot-release#1392]
Type: <b>Bug</b>

unhandled status from server: 400 Bad Request

Extension version: 0.17.1
VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.88GB (7.91GB free)|
|Process Argv|--crash-reporter-id b6fe0a26-de7d-4cfb-bb40-1ce4e2e5e22e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31094925
pythonrstrctxtcf:31093870
4930e709:31092288

```

</details>

**Comment by TYehan** [comment]
Just switch to the **"released version"** of the extension if using the "pre-released version".

Then **restart the extension** using the button shown there, this will solve the problem. 

![image](https://github.com/user-attachments/assets/fa6078e7-570b-41d3-a129-0c9ecfc5cafe)

![image](https://github.com/user-attachments/assets/7eb80f63-0b0b-4c93-af8e-ffc425e0a64a)

![image](https://github.com/user-attachments/assets/42704276-565e-4f6b-af12-0a1530cb5033)

Cheers!  ❤️

**Comment by KatlehoJordan** [comment]
> Just switch to the **"released version"** of the extension if using the "pre-released version".
> 
> Then **restart the extension** using the button shown there, this will solve the problem.
> 
> ![image](https://private-user-images.githubusercontent.com/85949077/348471068-fa6078e7-570b-41d3-a129-0c9ecfc5cafe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyOTAsIm5iZiI6MTcyMDg3NDk5MCwicGF0aCI6Ii84NTk0OTA3Ny8zNDg0NzEwNjgtZmE2MDc4ZTctNTcwYi00MWQzLWExMjktMGM5ZWNmYzVjYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEyNDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDI0OWRhNDdhYWZiN2ZjMGI4NTRjZjEzNTg5Y2Q0M2Y4NTliZDBmNzFjM2E4MTJiNGE1MTg2NGE5MThlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wreo7oLsFZljWMZpM2BO7Fv3VCTwodCVPVZXGe3_gJw)
> 
> ![image](https://private-user-images.githubusercontent.com/85949077/348471082-7eb80f63-0b0b-4c93-af8e-ffc425e0a64a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyOTAsIm5iZiI6MTcyMDg3NDk5MCwicGF0aCI6Ii84NTk0OTA3Ny8zNDg0NzEwODItN2ViODBmNjMtMGIwYi00YzkzLWFmOGUtZmZjNDI1ZTBhNjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEyNDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzM3NTQ2ZThiMjcxNGY3NjFkYzY2Njk0NzQ1ZDBiNTRhYjdjNzY4NGE5NzhhODA5YmJmODE4OTAwOGQ4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxwaswkV8-zJ9-xObpCrQouBRcNLN8XY3NqetIb0twI)
> 
> ![image](https://private-user-images.githubusercontent.com/85949077/348471129-42704276-565e-4f6b-af12-0a1530cb5033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyOTAsIm5iZiI6MTcyMDg3NDk5MCwicGF0aCI6Ii84NTk0OTA3Ny8zNDg0NzExMjktNDI3MDQyNzYtNTY1ZS00ZjZiLWFmMTItMGExNTMwY2I1MDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEyNDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ODFmNzZlYWM0M2E1NjI3Y2UyMTRjODRmZDlhM2M3YzdhYmU2MGQzNDUzMjNmZWY4MWQyNWY5YmRiZGQyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DD406ng4QBHVyxCtRSqJMyfrEAPwIKQ7VAj-j4pFIB8)
> 
> Cheers! ❤️

I am already using the released version and still getting this error. Any other tips? Any way to rollback to previous releases?

**Comment by TYehan** [comment]
> > Just switch to the **"released version"** of the extension if using the "pre-released version".
> > Then **restart the extension** using the button shown there, this will solve the problem.
> > ![image](https://private-user-images.githubusercontent.com/85949077/348471068-fa6078e7-570b-41d3-a129-0c9ecfc5cafe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyOTAsIm5iZiI6MTcyMDg3NDk5MCwicGF0aCI6Ii84NTk0OTA3Ny8zNDg0NzEwNjgtZmE2MDc4ZTctNTcwYi00MWQzLWExMjktMGM5ZWNmYzVjYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEyNDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NDI0OWRhNDdhYWZiN2ZjMGI4NTRjZjEzNTg5Y2Q0M2Y4NTliZDBmNzFjM2E4MTJiNGE1MTg2NGE5MThlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wreo7oLsFZljWMZpM2BO7Fv3VCTwodCVPVZXGe3_gJw)
> > ![image](https://private-user-images.githubusercontent.com/85949077/348471082-7eb80f63-0b0b-4c93-af8e-ffc425e0a64a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyOTAsIm5iZiI6MTcyMDg3NDk5MCwicGF0aCI6Ii84NTk0OTA3Ny8zNDg0NzEwODItN2ViODBmNjMtMGIwYi00YzkzLWFmOGUtZmZjNDI1ZTBhNjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEyNDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzM3NTQ2ZThiMjcxNGY3NjFkYzY2Njk0NzQ1ZDBiNTRhYjdjNzY4NGE5NzhhODA5YmJmODE4OTAwOGQ4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxwaswkV8-zJ9-xObpCrQouBRcNLN8XY3NqetIb0twI)
> > ![image](https://private-user-images.githubusercontent.com/85949077/348471129-42704276-565e-4f6b-af12-0a1530cb5033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA4NzUyOTAsIm5iZiI6MTcyMDg3NDk5MCwicGF0aCI6Ii84NTk0OTA3Ny8zNDg0NzExMjktNDI3MDQyNzYtNTY1ZS00ZjZiLWFmMTItMGExNTMwY2I1MDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEzVDEyNDk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ODFmNzZlYWM0M2E1NjI3Y2UyMTRjODRmZDlhM2M3YzdhYmU2MGQzNDUzMjNmZWY4MWQyNWY5YmRiZGQyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DD406ng4QBHVyxCtRSqJMyfrEAPwIKQ7VAj-j4pFIB8)
> > Cheers! ❤️
> 
> I am already using the released version and still getting this error. Any other tips? Any way to rollback to previous releases?

Yeah. It works Vise-versa too. cz it's a bug 🙂

**Comment by iwangbowen** [comment]
500 error followed by 400 bad request, what's next😒😒😒😒😒

**Comment by TYehan** [comment]
@iwangbowen  Can you try removing these settings from the JSON file:

```
"github.copilot.advanced": {
    "debug.overrideChatEngine": "copilot-ppee-centralus",
    "debug.overrideChatMaxTokenNum": 16384,
},
```

**Comment by TYehan** [comment]
@iwangbowen @KatlehoJordan  

There's currently an ongoing incident occurring https://www.githubstatus.com/

**Comment by lramos15** [comment]
Apologies, there was a GitHub outage related to the Copilot services. This has since been resolved.
