### ISSUE TITLE
unhandled status from server: 400 Bad Request

### ISSUE THREAD

**Issue by glow2590** [microsoft/vscode-copilot-release#1393]
- Copilot Chat Extension Version:v0.17.1
- VS Code Version:1.91.1
- OS Version:Windows 11
- Logs:
2024-07-13 18:38:16.941 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 202 ms
2024-07-13 18:38:16.941 [info] [chat fetch] Request ID for failed request: , 7fc84446-fed1-47a2-9d1e-2f108bae34c9
2024-07-13 18:38:16.943 [info] [chat fetch] Unhandled status from server:, 400, Bad Request

Steps to Reproduce:

1. On Every Chat message sent I get the error
2. this happened after my subscription expired then I entered the card again and renewed it but still had same issue before the renewal

**Comment by sfsaccone** [comment]
Same here. I just got my Copilot subscription. I get this on every chat query. Everything is the latest version. Same happens in Insiders with just the Copilot extensions installed.

Hopefully it's just a temporary server/networking issue.

**Comment by sfsaccone** [comment]
A Copilot "degradation" issue is being tracked at https://www.githubstatus.com. Looks like it's just about fixed.

**Comment by glow2590** [comment]
> A Copilot "degradation" issue is being tracked at https://www.githubstatus.com. Looks like it's just about fixed.

Thanks I will be checking it 🫡

**Comment by sfsaccone** [comment]
It's working now.

Maybe when this happens, replace the "400 Bad Request" error with a more informative message that includes a link to GitHub Status. That could prevent bug reports being created for temporary service outages.
