### ISSUE TITLE
the chat can't handle simple requests that otherwise work

### ISSUE THREAD

**Issue by fgaletic** [microsoft/vscode-copilot-release#1395]
Type: <b>Bug</b>

The extension that I am paying for is consistently failing with basic tasks. Without a specific context attachment it ignores the open file and answers it cannot see the code. When asked to answer something with specific context made of 3 files, it ignores 2 out of 3 and checks the active file even though it was not added specifically. It evades answering fully and gives useless timewasting pseudocode, I never requested that. I want specific answers. I am able to get specific answers in GPT-4 why would I continue paying for this???

Extension version: 0.17.1
VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (0.44GB free)|
|Process Argv|--crash-reporter-id fbd57247-5b5f-494a-baca-c6c24350da16|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31082724
pythonrstrctxtcf:31093870

```

</details>

**Comment by fisforfaheem** [comment]
Copilot Chat Not Working as Intended,These issues significantly impact productivity and trust in the Copilot Chat feature. Prompt resolution of these issues is crucial to enhance the user experience and ensure that developers can rely on Copilot Chat for accurate and contextually relevant assistance.

**Comment by joyceerhl** [comment]
Over the last few releases, we've rolled out larger context windows, added a widget that lets you control whether the active file is sent as context to the model,  and improved how we preserve files when there is too much context for the model. Please try it out again and let us know if you still see issues.
