### ISSUE TITLE
Copilot Chat Not Working as Intended, it's getting dumber and weird, not cares about context and still using chatgpt 3.5 answers

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1396]
**Title:** Copilot Chat Not Working as Intended

**Description:**
The GitHub Copilot Chat feature is experiencing significant issues that hinder its usability and effectiveness. These issues include a decline in the quality of responses, lack of context awareness, and continued use of outdated ChatGPT 3.5 responses instead of the more advanced ChatGPT-4.0. 

**Issues Encountered:**

1. **Decline in Quality of Responses:**
   - The responses generated by Copilot Chat have become increasingly less intelligent and often irrelevant. For example, when asking for assistance with a specific coding problem, the responses are vague and do not address the problem directly.
   - **Example:** When I requested help with a Flutter state management issue, Copilot Chat suggested a solution that was not only outdated but also incorrect, indicating a lack of understanding of the latest practices.

2. **Lack of Context Awareness:**
   - Copilot Chat frequently fails to maintain context throughout the conversation. This results in disjointed and confusing interactions, where the assistant seems to forget previous parts of the conversation.
   - **Example:** In a multi-step debugging session, after providing the initial context and receiving an initial suggestion, subsequent responses ignored the context provided earlier, leading to repeated and redundant advice.

3. **Usage of Outdated Responses:**
   - Despite the availability of ChatGPT-4.o, Copilot Chat continues to use responses based on the older ChatGPT-3.5 model. This results in less accurate and less useful responses.
   - **Example:** When asking for the latest best practices in Flutter development, Copilot Chat provided information that was relevant to older versions of Flutter, missing out on the latest advancements and recommendations.

**Expected Behavior:**
- Copilot Chat should leverage the latest ChatGPT-4.o model to provide more accurate, context-aware, and relevant responses.
- The assistant should be able to maintain context throughout the conversation to provide coherent and continuous assistance.
- The quality of responses should be improved to ensure they are intelligent, accurate, and directly address the user's queries.

**Steps to Reproduce:**
1. Start a Copilot Chat session.
2. Provide a specific programming query or debugging scenario.
3. Observe the quality of responses, context maintenance, and relevance of the information provided.

**Environment:**
VSCODE INSIDERS + latest GITHUB EXTENSION(prerelease)

**Additional Context:**
These issues significantly impact productivity and trust in the Copilot Chat feature. Prompt resolution of these issues is crucial to enhance the user experience and ensure that developers can rely on Copilot Chat for accurate and contextually relevant assistance.

**Comment by ulugbekna** [comment]
Thank you for feedback! We're working on addressing these issues!
