### ISSUE TITLE
Expandable window for copilot responses on main screen

### ISSUE THREAD

**Issue by theReynald** [microsoft/vscode-copilot-release#1399]
See video of explanation of feature request [here](https://microsoft-my.sharepoint.com/:v:/p/radolphe/EWLTZYKNedRKiub4x6lpj_UBhjA3zT0eAvC3ZZJv6WHqBQ?e=qR0Bqr&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D).

In short: When Copilot gives you a very detailed response in the main window, it would be nice if we could expand the window for a better view of all the content, rather than being forced to switch over to the left pane.

**Comment by jrieken** [comment]
inline chat is new resizable
