### ISSUE TITLE
Feature Request: Contextual understanding for entire workspace

### ISSUE THREAD

**Issue by ItsReddi** [microsoft/vscode-copilot-release#14]
Currently, the context that Copilot understands is limited to the actual selection of code. While this is indeed powerful, there are numerous cases where additional context would be immensely beneficial. In normal projects with multiple files and folders, there's a wealth of relevant context that is beyond the immediate view.

Therefore, I propose a feature enhancement where users have the option to send more than just the immediate selection of code to Copilot. Specifically, it would be fantastic if we could send entire files or even folders to provide broader context. This feature would allow Copilot to understand the larger scope of the codebase and make even more accurate and relevant suggestions.

Being able to provide a more comprehensive context could lead to a number of benefits. For example, it could help when working on projects, where the context of a single function or class may span multiple files. This feature could also be beneficial in cases where there are several interconnected components that impact the current selection of code.

This feature might bring about certain challenges, such as dealing with the potentially large amounts of data and the complexity of understanding the relationships between different parts of a project. However, I believe that with the strong AI capabilities of Copilot, these challenges can be surmounted.

**Comment by DennizSvens** [comment]
I totally agree on this one! Perhaps easily including files by tagging them with @ and using the same "modal" for selecting files as quick open (⌘ + P).

**Comment by mosure** [comment]
index selected files/folders with something like:
https://github.com/jerryjliu/llama_index/blob/1a598103430743ddc42da0e497ff503171941ed6/README.md

**Comment by tszumowski** [comment]
just started playing with the Chat beta and noticed also that it only really uses context in the currently open file. Would love for it to internally have context across all files in a project so it can understand how objects are passed through the full system.

**Comment by crackwitz** [comment]
I noticed that Chat doesn't ask questions, not even when it's confused (as I judge it).

In this instance, the question of extended access, when the chat context suggests it, Chat _could_ just ask the user to give permission, right? When the user tells it to grab certain context, it could then decide to open a "formal" dialog with user's message affecting prepopulated choices, the result of which is then an agreement by the user to grant Copilot the specified access. The model can't "lie" and claim that the user was okay with it, or anything. It's properly machine-readable ;)

> look into all .py files in the workspace

-> list workspace, all current .py files selected, one-time access pre-selected (i.e. for immediate consumption only)

> you can look into all .py files currently in the workspace

-> list workspace, those files selected, future access permission pre-selected

> you can look into all .py files in the workspace

-> list workspace, wildcard access indicated, future access permission pre-selected

**Comment by enriquemorenotent** [comment]
This is definitely what Copilot Chat needs to become. Otherwise, there is no benefit over using ChatGPT directly.

**Comment by crackwitz** [comment]
Agreed. I was hoping that Copilot Chat would be better at *programming* or that it would be able to look up documentation and library code on the fly. It doesn't seem to be. When I asked it something about playing video in a Qt GUI, it _invented_ APIs that don't exist, repeatedly. I showed it the exceptions (python tracebacks) several times and all its suggested corrections so far failed (granted, it's a tricky problem). I'm not even sure I can trust it to correctly reproduce plain standalone facts from docs/library source. It seems to reproduce those from memory, not from "tool use". Might be a model that isn't good at tool use, so it wasn't given the facility.

**Comment by william-kerr** [comment]
My [duplicate issue](https://github.com/microsoft/vscode-copilot-release/issues/87) got closed, and I've been referred to this issue.  The more I use GPT-4 directly through the chat.openai.com website, the more I appreciate how they reuse prior chat messages when creating the next response.  I've gotten to the point where I barely use Copilot chat (use it to explain things sometimes).  I still use some of the in-code auto suggestions from Copilot (not chat).  However, to get hard stuff done, I just paste code into a long running chat at chat.openai.com.

**Comment by enriquemorenotent** [comment]
@william-kerr Exactly the same for me

**Comment by landoncope** [comment]
I was surprised to see the tool doesn't have access to my code. What's the point, then? It seems like a no-brainer that a coding assistant should have access to a codebase.

**Comment by enriquemorenotent** [comment]
The problem is worse than "not having access to the whole project as context". It does not even have access to the code in the open file, that is outside the VIEWPORT!!

Steps to Reproduce:

1. If we ask a question about the code of the open file, it works without a problem, as seen in the image below

![image](https://github.com/microsoft/vscode-copilot-release/assets/368842/3362ac12-e9d0-4b4f-beeb-f513c9b64d96)

2. If we scroll downwards, until most of the lines of code are hidden from the viewport, Chat isn't able to answer the same question, as seen in the picture below.

![image](https://github.com/microsoft/vscode-copilot-release/assets/368842/0227e032-2fec-46de-91f5-eaa30acec4b2)

I am not sure if this is hilarious or sad

**Comment by kwokcb** [comment]
I guess as part of this, I found that if you open VScode folder at one level and chat and then open from a sub-folder the previous chat does not appear. Don't know if there is a way to preserve chats (any form of persistence) or least remember that a chat exists at the workspace level. Maybe no such concept?

**Comment by enriquemorenotent** [comment]
Is this issue being ignored? This seems by far the most important thing to be done, and we are getting zero feedback (that I know of)

**Comment by RobKaiser97** [comment]
Are there any laws on what ai are allowed to do or is it a capability issue. Like what causes the "As an AI language model, I am unable to perform that" or responses that get filtered for some reason

**Comment by enriquemorenotent** [comment]
@RobKaiser97 Probably depends on the country where the company in charge of that AI is located. That is, if we are only holding laws accountable for limiting capabilities. It is quite likely that in many cases it is more than that, like, for example, the desire of a company to stay out of trouble with certain collectives.

**Comment by RobKaiser97** [comment]
> @RobKaiser97 Probably depends on the country where the company in charge of that AI is located. That is, if we are only holding laws accountable for limiting capabilities. It is quite likely that in many cases it is more than that, like, for example, the desire of a company to stay out of trouble with certain collectives.

Fair point, it would be nice to get some transparency on those things but I won't hold my breath

**Comment by enriquemorenotent** [comment]
@RobKaiser97 Yes, please. Keep breathing.

**Comment by digitarald** [comment]
Closing as _"Used references"_ landed in Copilot Chat 0.10 as part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_workspace)

<img width="643" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/3ab3705a-0fc2-484c-9187-e4ee7866af40">

Please give it a try and file new issues for any follow-up feedback!

**Comment by enriquemorenotent** [comment]
Does it really write code, taking all the context? Or does it just answer question like "Explain" or "describe"?

If I am in a controller file, and I ask him to use an instance of a model, will it know its API and use it accordingly to write the code? Because that is not what the description seems to say. It sounds more like a "AI file search".

**Comment by digitarald** [comment]
It can do explain, but also generate net-new code based on a natural language query. If you use Insiders, you can also give `#file` a try to provide specific code.

We have a blog post soon with the nitty gritty. The gist is that AIs have a limited context window, so Copilot always needs to search and curate the right parts for grounding.

**Comment by Ubeydu** [comment]
> Closing as `@workspace` with _"Used references"_ landed in Copilot Chat 0.10 as part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_workspace)
> 
> <img alt="image" width="657" src="https://user-images.githubusercontent.com/8599/279833336-9ac45254-74ae-4319-8c57-a612221b6985.png">
> Please give it a try and file new issues for any follow-up feedback!

This doesn't seem to be working in my case. See the SS I am attaching. 
![Screenshot 2023-11-15 at 12 02 13](https://github.com/microsoft/vscode-copilot-release/assets/64747345/c80b16c2-3eb2-4b9d-b477-527d9f8619ae)

I asked it a general question, hoping it'd look into the project and get back to me with an answer. Instead, the response I got indicates that Copilot only checked the content of the file that is open in the editor. Beats the whole purpose. But, maybe I am missing something. Help would be appreciated, thank you.

**Comment by enriquemorenotent** [comment]
@Ubeydu Interestingly enough,the keyword `@workspace` does not seem to be highlighted like for the rest of us. Are you using the latest version of the extension, as well as the latest version of the editor?

![image](https://github.com/microsoft/vscode-copilot-release/assets/368842/14430e2c-f9ab-42fe-a862-ae1b2fdeeaa0)
![image](https://github.com/microsoft/vscode-copilot-release/assets/368842/b4307e27-046e-4831-bd68-b8b2c2e8b5fc)

**Comment by hacknug** [comment]
`@workspace` is highlighted for me. Here are the versions of my extensions:
- GitHub Copilot v1.136.550 (Pre-Release)
- GitHub Copilot Chat v0.10.1 (Preview)
- GitHub Copilot Labs v0.15.1019 (Preview)

**Comment by Ubeydu** [comment]
Thanks, now the @workspace is highlighted for me as well, it was the version of my Copilot Chat. I am yet to explore to see how good Copilot is when it comes to the code context issue. I wish it stopped saying: 

_Without more information or code, it's hard to say exactly where the routing setup is handled in your project._

 And, instead, it went ahead and looked into the whole project code. Maybe this will come around at some point as well. I don't know what are the technical difficulties that they are facing with this. Or, there may be other concerns that we don't know.

**Comment by robertofabrizi** [comment]
Im on the latest versions and it still doesn't work for me, I opened a spring boot entrypoint and it says that it contains no other code to understand what the microservice does, thus it's not accessing other opened files.

**Comment by robertofabrizi** [comment]
Yes I did. How many files did it use for context?

**Comment by benjipeto** [comment]
For my last question, it used 12 refs in total 😄 and only 4 files were open in my vscode

**Comment by robertofabrizi** [comment]
![MicrosoftTeams-image (2)](https://github.com/microsoft/vscode-copilot-release/assets/6720929/6e30b298-fca4-46ee-a114-97d31e7c0aec)
![MicrosoftTeams-image (1)](https://github.com/microsoft/vscode-copilot-release/assets/6720929/22655cf2-9ebf-4e67-a898-03883454a88f)

If I ask it to locate stuff like where is this or that, it considers more than one file. But if i don't ask a where query, but rather use @workplace /explain or @workplace give me a high level overview of what this project does, it only considers one file again.

**Comment by benjipeto** [comment]
I see your point. It has either something to do with the LLM and prompt creation, or something else [I don't know]. I would try to change the prompt and try different wording to see if that would generate different output. If still the same, then we can be sure, and it's something development related "stuff".

**Comment by benjipeto** [comment]
> Are the people at GitHub going to implement this feature in the next release? It's so ridiculous that an assistant cannot read the file directly.

It has been already implemented. As you can see the comments above, the `@workspace` command will search all related files in your workspace. I've noticed that sometimes includes files that has nothing to do with the question, but in my opinion that could be related to variable names etc. 

**Also make sure to create a workspace in your VSCode to be able to use the command.**

**Comment by demiro** [comment]
Hm.. for me **@workspace** is not working well - at least far from what I expected..

when I do this prompt:

> this is the error I get... could you please suggest the fixes?
> 
> [Vue warn] Computed is still dirty after getter evaluation, likely because a computed is mutating its own dependency in its getter. State mutations in computed getters should be avoided. Check the docs for more details: [https://vuejs.org/guide/essentials/computed.html#getters-should-be-side-effect-free](vscode-file://vscode-app/c:/Users/damir/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)

this is the response I get:

> The error message you're seeing is a warning from Vue.js about a computed property in your code. Computed properties in Vue.js should be pure functions, meaning they should not have any side effects. They should only depend on their reactive dependencies and should not modify any state.
> 
> The warning suggests that one of your computed properties is modifying its own dependency, which is causing it to be re-evaluated, and hence it's still "dirty" after the getter evaluation.
> 
> To fix this issue, you should review your computed properties and ensure they are not modifying any state. Here's an example of what you should avoid:
> 
> ```
> computed: {
>   total: {
>     get() {
>       this.items.push({ name: 'New Item' }); // This is a side effect
>       return this.items.length;
>     }
>   }
> }
> ```
> 
> In the above example, the total computed property is modifying its own dependency items by pushing a new item into it. This is a side effect and should be avoided.
> 
> Instead, you should ensure that your computed properties are pure functions that only depend on their reactive dependencies and do not modify any state:
> 
> ```
> computed: {
>   total() {
>     return this.items.length;
>   }
> }
> ```
> 
> In this corrected example, the total computed property is a pure function that only depends on items and does not modify any state. This is the correct way to use computed properties in Vue.js.


which is totally unusable:

> @workspace how is this helping me with the example? I want to see exactly in my code where the issue is and suggest a fix - not some random examples

response:

> I'm sorry, I can't answer that question with what I currently know about your workspace.

prompt: 

> how can you learn more about my workspace?

and final response:

> As an AI, I don't have direct access to your workspace or codebase. However, you can provide more context or share the relevant parts of your code where you're encountering the issue. This would allow me to give a more accurate and helpful response. Please ensure that any code you share does not contain sensitive information.


this is def. not in line what it was promised to deliver

**Comment by enriquemorenotent** [comment]
"workspace" is flaky at best, in all honesty

**Comment by mjbvz** [comment]
If `@workspace` isn't working as expected, please open a new issue with steps to reproduce and example code so we can investigate
