### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by zhaozhencn** [microsoft/vscode-copilot-release#1402]
Today, when I type anything in github copilot chat ,  it will report " unhandled status from server: 400 Bad Request "  or  " 500 Internal Server Error"  ,  But,  it was worked correct yesterterday.

**Comment by donghoon-song** [comment]
me either

**Comment by andreadme** [comment]
happened to me too

**Comment by chlai** [comment]
i have the same issue in Hong Kong!

**Comment by RillMa** [comment]
+1

**Comment by WinterClown88** [comment]
+1 in Korea

**Comment by HenryH24** [comment]
+1

**Comment by danhlan** [comment]
+1

**Comment by rishabhraj36** [comment]
I have been facing the same issue too

**Comment by toddsayersshell** [comment]
Experiencing both errors, also.

**Comment by jamesperet** [comment]
+1

**Comment by xdien** [comment]
+1

**Comment by z1yuan** [comment]
+1

**Comment by huajielong** [comment]
+1  in Japan

**Comment by Versirity** [comment]
It turns out that everyone has this problem

**Comment by SimonBill114** [comment]
+1

**Comment by guerreroezequiel** [comment]
same

**Comment by lai-vson** [comment]
same

**Comment by ProFive** [comment]
me too unhandled status from server: 400 Bad Request

**Comment by SimonBill114** [comment]
Just waitting...

**Comment by liwang2019** [comment]
+1

**Comment by zcmk123** [comment]
+1

**Comment by haojieonline** [comment]
+1

**Comment by kiko-freedom** [comment]
+1 Philippines

**Comment by hayleychiu** [comment]
+1  
unhandled status from server: 400 Bad Request or  500 Internal Server Error

**Comment by rrtt2323** [comment]
me too.

**Comment by AiprNick** [comment]
+1

**Comment by dodox132** [comment]
+1 in VN

**Comment by Kenny-Korea** [comment]
+1 from Korea.
I think it's mostly happening in Asian countries

**Comment by Gbast0** [comment]
+1 from Australia

**Comment by andreadme** [comment]
it's now working on my side. from PH

**Comment by TravisLei20** [comment]
Working in US too

**Comment by ulugbekna** [comment]
This was a temporary outage that should be now fixed. Thank you for filing this issue!

**Comment by Harold-Anderson** [comment]
![image](https://github.com/user-attachments/assets/a4e65faf-bcf6-4491-8273-d202a4d24b6f)
