### ISSUE TITLE
unhandled status from server: 400 Bad Request.

### ISSUE THREAD

**Issue by rrtt2323** [microsoft/vscode-copilot-release#1403]
![image](https://github.com/user-attachments/assets/94477c40-c00d-47c8-a748-056be438c2ef)
After today's launch, that's it.

**Comment by haonguyen1196** [comment]
+1

**Comment by lramos15** [comment]
There was a GH outage. Are you still experiencing this?

**Comment by rrtt2323** [comment]
> There was a GH outage. Are you still experiencing this?
It worked.

**Comment by rrtt2323** [comment]
> There was a GH outage. Are you still experiencing this?

It worked.
