### ISSUE TITLE
Copilot giving non context based answers even If I select the text

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1404]
Sample:

GitHub Copilot
Without seeing the specific code, I can provide a general explanation of why an application might be fetching alerts repeatedly:

Polling: The application might be using a polling mechanism where it is set to fetch alerts at regular intervals. This is common in applications that need to display real-time data but don't have a mechanism for push notifications.

Event Loop Issue: If the fetching logic is accidentally placed inside a loop without a proper exit condition or delay, it could cause the application to fetch alerts continuously.

State Management Issue: In frameworks that use state management (like React, Vue, or Flutter), if the state that triggers the fetch operation is updated in a way that inadvertently causes the fetch function to execute again, it can lead to repeated fetching.

Incorrect Dependency in Effect Hook: In React, for example, if you're using useEffect to fetch alerts and the dependency array is incorrectly set, it might cause the fetch function to run more often than intended.

Subscription Not Handled Properly: If the application subscribes to an event or a data stream to fetch alerts, and if the subscription is not managed properly (e.g., not unsubscribed when not needed), it could result in repeated fetching.

Backend Trigger: Sometimes, the backend or the server might be pushing updates more frequently than expected, causing the client-side application to fetch repeatedly in response to these updates.

To diagnose and fix the issue, consider the following steps:

Check if there's a polling mechanism and if it's necessary or can be optimized.
Review the logic and ensure it's not inside an unintended loop.
Verify state management logic or dependency arrays in hooks to ensure they're not causing the repeated fetching.
Ensure proper subscription management, including subscribing and unsubscribing at appropriate times.
Check the backend to see if it's behaving as expected.
If you can provide a specific segment of the code where the issue is happening, I could offer a more targeted solution.

**Comment by mjbvz** [comment]
what did you ask and what code did you have selected?

**Comment by fisforfaheem** [comment]
This happens not all the time but out of 10 ...it happens on 4-5  times,  WELL THE CODE WAS FOR FLUTTER SDK UI, IT WAS FLUTTER SDK CODE writting IN DART language

**Comment by mjbvz** [comment]
Please share the question you are asking and the code you have selected

**Comment by fisforfaheem** [comment]
I forgot the question and moved to usinf chatgpt pro instead, but i have seen copilot it very poor for millions of flutter DEVS

**Comment by mjbvz** [comment]
Closing as we need a simple explanation of the problem and steps to reproduce it
