### ISSUE TITLE
Improve readability of user input box when panel is narrow.

### ISSUE THREAD

**Issue by lettucegoblin** [microsoft/vscode-copilot-release#1408]
## Issue
User text in the input field becomes difficult to read when the panel is narrow. 
![image](https://github.com/user-attachments/assets/f0e5ac32-5546-4a5e-bfc7-30aab601f278)
The narrower the panel the more pronounced the issue with text readability for the user input box.

## Suggested Solution
A media container query breakpoint that switches to `flex-direction: column;` when narrow enough so the text field and buttons will be stacked rather than side by side.
### Solution Mockup:
![solution mockup](https://github.com/user-attachments/assets/5f9bd330-1da5-440a-adf6-22e76bed1f71)

From a UX standpoint, this is a bug but from a technical standpoint it's a feature request. Just for the future which would be the more appropriate category for me to have selected?

**Comment by isidorn** [comment]
This is fixed now, because the toolbar is below the input box. Closing as fixed.
