### ISSUE TITLE
Generated code doesn't follow coding style/standard or configured eslint rules.

### ISSUE THREAD

**Issue by rpuls** [microsoft/vscode-copilot-release#1416]
Hi. The following example is just one in many, Copilit is consistently generating "illegal" syntax every single time I ask it to generate unit tests.

I select the following function and use the right-click menu in vscode to "Generate tests"

```
const hasUserViewedUpcomingEvent = ({ dataStore, participantEventId }) => {
  const participantEvent = dataStore['user.participantEvent'][participantEventId];
  const participant = dataStore['user.participant'][participantEvent.participantId];
  const programState = dataStore['user.program'][participantEvent.programId].state;
  const programSectionList = programState.sectionList;
  const flatParticipantEventList = programSectionList.reduce((acc, section) => {
    return [
      ...acc,
      ...(R.path(['participantEventMap', participant.idName], section) || []).map(idName => E.byIdName(dataStore['user.participantEvent'], idName))];
  }, []);
  const currentIndex = flatParticipantEventList.findIndex(pe => pe.idName === participantEvent.idName);
  const upcomingParticipantEventList = flatParticipantEventList.slice(currentIndex + 1);
  const hasViewedUpcoming = upcomingParticipantEventList.some(pe => pe.viewedAt !== null || pe.hasCompleted); // Note: it's possible that upcoming event is completed by admin/facilitator
  return hasViewedUpcoming;
};
```
Copilot thinks for a while then generate the following unit test:

```
describe('hasUserViewedUpcomingEvent', function () {
  const dataStore = {
    'user.participantEvent': {
      '1': { id: '1', participantId: '1', programId: '1', eventId: '1', viewedAt: null, hasCompleted: false },
      '2': { id: '2', participantId: '1', programId: '1', eventId: '2', viewedAt: null, hasCompleted: false },
      '3': { id: '3', participantId: '1', programId: '1', eventId: '3', viewedAt: null, hasCompleted: false },
      '4': { id: '4', participantId: '1', programId: '1', eventId: '4', viewedAt: null, hasCompleted: false },
      '5': { id: '5', participantId: '1', programId: '1', eventId: '5', viewedAt: null, hasCompleted: false },
    },
    'user.participant': {
      '1': { id: '1', idName: 'participant1' },
    },
    'user.program': {
      '1': {
        id: '1',
        state: {
          sectionList: [
            {
              idName: 'section1',
              participantEventMap: {
                'participant1': ['1', '2'],
              },
            },
            {
              idName: 'section2',
              participantEventMap: {
                'participant1': ['3', '4'],
              },
            },
            {
              idName: 'section3',
              participantEventMap: {
                'participant1': ['5'],
              },
            },
          ],
        },
      },
    },
  };

  it('should return true if upcoming events have been viewed or completed', function () {
    const result = hasUserViewedUpcomingEvent({ dataStore, participantEventId: '2' });
    result.should.equal(true);
  });

  it('should return false if upcoming events have not been viewed or completed', function () {
    const result = hasUserViewedUpcomingEvent({ dataStore, participantEventId: '4' });
    result.should.equal(false);
  });
});
```

No other code in our entire code base has a single tailing comma on the last object/list item, and our eslint rule is setup to error on this syntax: 

```
        },
      },
    },
```

So vscode throws in a ton of red marks that I manually have to go over and fix when clicking the "Apply Edit"

1. Shouldn't it pickup on the lint rules, and/or follow practice of other code in same project?
2. Why is it even allowed to generated code that throws an error in the editor, shouldn't there be a feeback loop preventing generating code that causes an objective error?

- Copilot Chat Extension Version: 1.214.0
- VS Code Version: 1.91.1
- OS Version: Windows 11

**Comment by msbegee** [comment]
closed not complete

**Comment by ulugbekna** [comment]
Hello, thank you for filing this issue! 

You can use custom [instructions](https://code.visualstudio.com/docs/copilot/copilot-customization) to instruct Copilot on how to generate any code or tests. 

You can also attach config files of interest into the panel chat and add an additional instruction in your message to Copilot to respect those config files. Learn [more](https://code.visualstudio.com/docs/copilot/copilot-vscode-features).

**Comment by rpuls** [comment]
> Hello, thank you for filing this issue!
> 
> You can use custom [instructions](https://code.visualstudio.com/docs/copilot/copilot-customization) to instruct Copilot on how to generate any code or tests.
> 
> You can also attach config files of interest into the panel chat and add an additional instruction in your message to Copilot to respect those config files. Learn [more](https://code.visualstudio.com/docs/copilot/copilot-vscode-features).

Thank you for responding to my issue, this is a massive improvement. Being able to link files in the custom instructions is key to context management. Glad to see that this have been implemented
