### ISSUE TITLE
GitHub Copilot Chat Extension for VS Code doesn't finishes responses, no longer "sees" reference selections properly and the "Apply in Editor" functionality doesn't work anymore

### ISSUE THREAD

**Issue by lucas-ebi** [microsoft/vscode-copilot-release#1418]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Select a code snippet, open chat and ask questions about the selection. It not always can use it as reference.
2. Even when it sees the reference selection, most of times it gets stuck and doesn't finish the response.
3. Even if it finishes the response, it's no longer possible to "apply in editor".

**Comment by mjbvz** [comment]
Please fill in the issue template with the relevant VS Code and extension versions too

**Comment by mjbvz** [comment]
Closing as we need more information to investigate this properly
