### ISSUE TITLE
"Generate Commit Message with Copilot" button is not available, When you have multiple repositories open.

### ISSUE THREAD

**Issue by AndreVicencio** [microsoft/vscode-copilot-release#1419]
- Copilot Chat Extension Version: v1.216.0
- VS Code Version: 1.85.0 (Universal)
- OS Version: MacOS Sonoma 14.4
- Logs:

Steps to Reproduce:

1. Open VSCode on a directory that has more than 1 project/repository
2. Open the 'Source Control' extension

Expected Behaviour:
"Generate Commit Message with Copilot" button is available for all projects/repositories
![image](https://github.com/user-attachments/assets/a35bddad-0d15-41a0-b945-eda937aaee5d)

Actual Result:
"Generate Commit Message with Copilot" button is not available
![image](https://github.com/user-attachments/assets/210f6c6e-0f00-4db9-99bd-70fd53294edf)

**Comment by AndreVicencio** [comment]
Were you guys able to replicate?

**Comment by lszomoru** [comment]
@AndreVicencio, you seem to be running VS Code 1.85.0. 
Can you reproduce this issue with the latest version of VS Code and the latest version of the Copilot Chat extension? Thanks!

**Comment by AndreVicencio** [comment]
Updated to the latest version 1.91 and it's now working
