### ISSUE TITLE
Error 400 when trying to select a portion of code and sending a prompt

### ISSUE THREAD

**Issue by dichiara19** [microsoft/vscode-copilot-release#1420]
`unhandled status from server: 400 {"error":{"message":"The requested model is not supported.","param":"model","code":"model_not_supported","type":"invalid_request_error"}}`

- Copilot Chat Extension Version: v0.17.1
- VS Code Version: 
- OS Version: Windows 11 in remote connection to WSL
- Logs:

Steps to Reproduce:

1. Open a file
2. Start a chat
3. Select code 
4. Send any prompt

**Comment by lramos15** [comment]
Can you try restarting your VS Code instance? We did just stop an experiment that was using a temporary model.

If still having issues after restarting please attach your logs via `CTRL + SHIFT + U` -> `Github Copilot Chat`

**Comment by dichiara19** [comment]
Yes. Restarting vscode now solves the problem. Thank you
