### ISSUE TITLE
Feature request: Be able to edit the title of the Copilot tab

### ISSUE THREAD

**Issue by jdudley1123** [microsoft/vscode-copilot-release#1422]
When you put Copilot into its own tab, the title of the tab is a summary of the first thing you posted. This takes up quite a lot of space. I'd like to be able to edit it, or just have it say 'Copilot'.

![image](https://github.com/user-attachments/assets/b5ce7334-dcbd-414c-adce-b2447b7b8625)

**Comment by roblourens** [comment]
I'd like to have this too - https://github.com/microsoft/vscode-copilot-release/issues/725
