### ISSUE TITLE
Inline chat fails instantly with no results

### ISSUE THREAD

**Issue by andreialecu** [microsoft/vscode-copilot-release#1429]
Still seeing this issue as of July 29 2024 on `v0.17.1` of the extension:

```
2024-07-29 11:42:35.046 [info] [extension] Inline chat request is missing context information, undefined, undefined, undefined
```

![CleanShot 2024-07-29 at 11 44 41@2x](https://github.com/user-attachments/assets/2a1431f4-b96c-43f1-9087-c8815ae7f1a4)

It happens on any file, no matter the extension.

_Originally posted by @andreialecu in https://github.com/microsoft/vscode-copilot-release/issues/1365#issuecomment-2255352399_

**Comment by ulugbekna** [comment]
Thanks for filing the issue! 

Are you on vs code insiders? If yes, Insiders works best with the pre-release version of the extension (open the extensions view, find Copilot Chat extension and switch to pre-release)

**Comment by andreialecu** [comment]
Indeed I am on an insiders version. Switching to pre-release fixed it.

Thank you for the tip! Feel free to close if there's nothing that can be done here (perhaps a friendlier error message?)
