### ISSUE TITLE
command palette 'Ask Quick Question' command does not have a scroll

### ISSUE THREAD

**Issue by adnanjpg** [microsoft/vscode-copilot-release#143]
- VS Code Version: 1.79.0-insider (Universal)
- OS Version: macOS 13.3.1 (a) (22E772610a)

Steps to Reproduce:

1. open command palette using f1 or cmd + p
2. type 'chat: ask quick question'
3. enter a question
4. if the answer is long, it will not fit on the screen. there should be a scroll ability, but there is not

notice how in the image below the text is cut off, and I can't scroll to read the rest
<img width="1020" alt="Screenshot 2023-05-26 at 10 52 45 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/54329101/99204295-2fe2-4e6e-80b2-47a63fa4cfb5">

**Comment by roblourens** [comment]
This is fixed
