### ISSUE TITLE
Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. 

### ISSUE THREAD

**Issue by imarsalan02** [microsoft/vscode-copilot-release#1431]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by AdrianCarreno** [comment]
I have the same issue when asking basic questions about a docker compose file. As the questions are basic, and the code is pretty standard, it will, of course, match publicly available code. I have enabled the matches in my account (`Settings`>`Copilot`>`Suggestions matching public code (duplication detection filter)`) and it's still blocking the responses.

This is a major turn down for me, I have been using this extension for over 2 years, and now it has become useless thanks to this feature. I might even consider cancelling my subscription and using something else.

**Comment by lramos15** [comment]
Please include screenshots of your question and answer plus the logs from `CMD/CTRL + SHIFT +U -> GitHub Copilot Chat`

**Comment by AdrianCarreno** [comment]
Here's my chat history:
![image](https://github.com/user-attachments/assets/9456edd3-4e50-48b9-9257-1578a25c1888)

The logs for this message are these:

```log
2024-08-02 12:51:40.509 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 687 ms
2024-08-02 12:51:44.915 [info] [streamMessages] message 0 returned. finish reason: [content_filter]
2024-08-02 12:51:44.916 [info] [streamChoices] request done: requestId: [1691d64e-862e-4c8a-8be1-58eb0ec560f8] model deployment ID: []
```

I have allowed the suggestions matching public code:
![image](https://github.com/user-attachments/assets/84da9bf9-318a-4647-a3e7-3dc1aa4b5c87)

**Comment by lramos15** [comment]
Thanks @AdrianCarreno. This was actually filtered incorrectly by our profanity filter and we're working in the background to tune the filter so this doesn't happen again. Additionally I have made a change so that the UI message does not incorrectly state this matches public code when that was not the filter applied here.
