### ISSUE TITLE
Two steps answers = focus on the explanations

### ISSUE THREAD

**Issue by ccrica** [microsoft/vscode-copilot-release#1440]
First of all, thanks a lot for this wonderful tool that changed my programming life. as non-expert in programmation, you've made POCs available for me and this is great.

The replies are always quick and verbose, most of the time you share some code, immediately as an example. This is fine but makes the result difficult to be read.
**Proposal :** Divide the answers in 2 steps : 1. explanations as now 2. integrated button "show code" that shows the code only if asked. In this way I get same result with first focus on explanations instead of the code.
Thanks a lot.

**Comment by roblourens** [comment]
I'd recommend asking the model to focus on an explanation in your prompt. Other people may want a focus on code. https://github.com/microsoft/vscode-copilot-release/issues/563 could also help you in the future
