### ISSUE TITLE
Copilot does not reference all files specified by #file

### ISSUE THREAD

**Issue by mfanegg** [microsoft/vscode-copilot-release#1443]
- Copilot Chat Extension Version: v1.219.0
- VS Code Version: 1.91.1 
- OS Version: macOS Sonoma 14.5
- Logs: I don't think I can attach these b/c of corporate data policies, but I'm hoping this is a user error instead of a technical error

## Steps to Reproduce:

So, we've got a pretty large codebase with a couple thousand files. When I use `@workspace`, it never references the files I've specified in my prompt, since I only care about seven files. Thus, I use #file, but this doesn't seem to be working as expected earlier.

step 1: enter something like the following prompt:

"
Hello. I am migrating files from a certain format to a certain format. I am trying to migrate #file:'z.tsx'. 

Please see #file:'a.tsx' for an example of before, and #file:'b.tsx' for an example of after. 

Those files don't cover all the cases needed by z.tsx, so please see #file:'c.tsx' for an example of [how to do something the old way], and #file:'d.tsx' for an example of [how to do something the new way]. 

Those files still don't cover all the cases needed by z.tsx, so please see #file:'e.tsx' for an example of [how to do something else the old way], and #file:'f.tsx' for an example of [how to do something else the new way]. 

With all that being said, please migrate #file:'z.tsx' and print the result. Thanks!

"

step 2: observe Copilot's answer:

"
used 3 references:
z.tsx
a.tsx
b.tsx

[answer which doesn't really make sense, because d.tsx, e.tsx, f.tsx, and z.tsx were not referenced]
"

How come Copilot doesn't recognize the other files I've specified in my answer? Is there a max file limit of 3? Any way to change it? Maybe I'm doing something wrong in my prompt? 

Again (since I suspect this will come up), I cannot use `@workspace` because it doesn't capture all seven files either, even if I use `@workspace` in addition to the #file command.

Thanks for any and all clarity.

**Comment by roblourens** [comment]
We have limited room for context that can be sent to the LLM. We include as much as we can fit but may not be able to fit everything, depending on the size. In the latest release that just went out next week, we also try to do a slightly better job in fitting part of a file if the entire thing can't fit, and we show a more helpful message on files that weren't able to fit. Sorry for the annoyance and hope that helps.
