### ISSUE TITLE
i can't use copilot in visual studio code

### ISSUE THREAD

**Issue by flcYtb** [microsoft/vscode-copilot-release#1444]
Type: <b>Bug</b>

hello. i can't use copilot chat in visual studio code.

error log is here

[Extension Host] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1230
fire @ event.ts:1261
fire @ ipc.net.ts:652
K.onmessage @ localProcessExtensionHost.ts:378
log.ts:439   ERR [Extension Host] [LanguageModelAccess] Error: GitHubLoginFailed
    at RS.authShowWarnings (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:633:13828)
    at RS.getCopilotToken (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:633:11894)
    at Q_.getCopilotToken (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:144:2645)
    at PS._getAuthSession (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:634:2188)
    at r (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:634:627)
    at PS._registerLanguageModels (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:634:1513)
    at async Promise.all (index 0)
    at async Promise.allSettled (index 0)
    at Zct (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1365:4403)
    at Xct (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1365:3372)
    at m.n (c:\Users\s-uwa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
    at m (c:\Users\s-uwa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
    at m.l (c:\Users\s-uwa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
console.ts:137 [Extension Host] [LanguageModelAccess] Error: GitHubLoginFailed
    at RS.authShowWarnings (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:633:13828)
    at RS.getCopilotToken (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:633:11894)
    at Q_.getCopilotToken (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:144:2645)
    at PS._getAuthSession (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:634:2188)
    at r (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:634:627)
    at PS._registerLanguageModels (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:634:1513)
    at async Promise.all (index 0)
    at async Promise.allSettled (index 0)
    at Zct (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1365:4403)
    at Xct (c:\Users\s-uwa\.vscode\extensions\github.copilot-chat-0.18.1\dist\extension.js:1365:3372)
    at m.n (c:\Users\s-uwa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
    at m (c:\Users\s-uwa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
    at m.l (c:\Users\s-uwa\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)

my plan is here, i have right of using copilot.

Copilot policies
Copilot in the CLI
Enabled
You can use GitHub Copilot for assistance in terminal.

Copilot Chat in the IDE
Enabled
You can use GitHub Copilot Chat in the IDE to explain a piece of code, propose bug fixes, or generate unit tests in a chat interface from your editor.

Copilot Chat in GitHub Mobile
Enabled
You can use Copilot Chat in GitHub Mobile personalized to a codebase.

Suggestions matching public code (duplication detection filter)
Copilot can allow or block suggestions matching public code. Learn more about code suggestions.

please tell me what do i do. thanks.

Extension version: 0.18.1
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7735HS with Radeon Graphics         (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.25GB (15.76GB free)|
|Process Argv|--crash-reporter-id 0f58a6c2-6e53-4ca4-a70c-0c953dbbb28f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
ccpltc:31103427
pythonrstrctxtcf:31103194
1iic9185:31097392

```

</details>

**Comment by flcYtb** [comment]
i already tried these.

- In the bottom left corner of the Visual Studio Code window, click the Accounts icon, hover over your GitHub username, and click the Sign out button.
- To reload Visual Studio Code, press F1 to open the command palette, and select Developer: Reload Window.
- After Visual Studio Code reloads, sign back in to your GitHub account.

but, the issue persists, and my vscode and copilot extenton's versions are latest.

**Comment by flcYtb** [comment]
I found such tweet. My situation is same this tweet.

https://x.com/uYRpiPGFGDQULRp/status/1819327025309794440

In VS Code 1.92, the Copilot column does not appear when right-clicking, and the Chat in the left column does not respond. It seems that Github Copilot Chat 0.18.1 and 0.18.0 do not work. It works when I update to 0.17.1 (the GPT-4o conversion of Copilot applied in 1.92 seems to be applied in 0.17 and above).

VS Code 1.92で、右クリックで Copilot の欄が出なくなり、左欄の Chat も反応しない。どうやら、Github Copilot Chat 0.18.1, 0.18.0 が動かないもよう。0.17.1 に落としたら動く(一応 1.92で適用されたCopilotのGPT-4o化は、0.17以上ならされてるらしい)。

I downgradeed to v0.17.1, Copilot Chat works .
Do you know why? Can't I use v0.18.3 or latest?

**Comment by sunnymsgCEO** [comment]
I experienced the same issue. @flcYtb 
VSCode 1.92, Copilot Chat didn't work (it kept asking me to log in...)  
So, I installed VSCode 1.91 and reinstalled Copilot Chat (for version 1.91), and it worked perfectly.
It seems to be an issue with the versions of VSCode and Copilot Chat extension

**Comment by livinsunny519** [comment]
This worked for me: 
https://github.com/orgs/community/discussions/134876#discussioncomment-10257723

**Comment by flcYtb** [comment]
@livinsunny519 
Thank you for the info, but it didn't solve my problem.....

> This worked for me: https://github.com/orgs/community/discussions/134876#discussioncomment-10257723

**Comment by flcYtb** [comment]
for now, I installed VSCode 1.91, and Copilot Chat 0.17.1.

Someone emailed me and told me about it, but I can't find them in this issue 😖

**Comment by CarlosaBauti** [comment]
Same issue here. I updated both VSCode and Copilot chat to the latest version and the chat stopped working. The error showed in the chat was: certificate has expired. I tried each one of the previously suggested solutions and nothing worked. Also had to comeback to the same versions @flcYtb mentioned and it is working again

**Comment by KaliaHayes** [comment]
Installing Copilot v17.2 worked for me. v19 is acting up.

I'm running VSC Insiders Version: 1.93.0-insider (Universal) btw!

**Comment by kennyr3221** [comment]
Had to revert to version v1.201.0 for copilot and revert github chat to v0.17.0. If i both to the latest version it doesn't work at all.
this seems to be the only work around

**Comment by TylerLeonhardt** [comment]
@flcYtb @CarlosaBauti @KaliaHayes @kennyr3221 

Can you please tell me what the value of [the github.copilot.preferredAccount setting is](https://vscode.dev/redirect?url=vscode://settings/github.copilot.preferredAccount) (VS Code Insiders users, [click this link instead](https://vscode.dev/redirect?url=vscode-insiders://settings/github.copilot.preferredAccount))? If you remove the value, does that fix the issue for you?

**Comment by flcYtb** [comment]
@TylerLeonhardt 
Thank you for the info, my value of the github.copilot.preferredAccount setting is my GH account( s-***@***c.jp Should I just write the correct account name here...? ), I have verified that I can sign out of GH and then sign back in to GH with that account.

And, i install latest vsCode( 1.92 ) and GitHub Copilot Chat( 0.18.1 ), copilot chat seems to be working correctly.

**Comment by TylerLeonhardt** [comment]
What's odd here is that preferredAccount shouldn't ever be _an email address_, but instead your username. Clearly several users are hitting this same behavior where it ends up being an email address instead of the username ...but it's odd to me how this happens... more to investigate.

**Comment by flcYtb** [comment]
@TylerLeonhardt 
This problem started after the vsCode update notice was released this month( 2024/08 ) .
Could it be that the value was entered at that time?

I don't use Codespaces.

These are my extensions. I narrowed it down by '@enabled git', 
so I'm listing the ones that are not related to github.

mhutchie.git-graph
GitHub.copilot
GitHub.copilot-chat
GitHub.vscode-pull-request-github
GitHub.github-vscode-theme
eamodio.gitlens

**Comment by kennyr3221** [comment]
> @flcYtb @CarlosaBauti @KaliaHayes @kennyr3221
> 
> Can you please tell me what the value of [the github.copilot.preferredAccount setting is](https://vscode.dev/redirect?url=vscode://settings/github.copilot.preferredAccount) (VS Code Insiders users, [click this link instead](https://vscode.dev/redirect?url=vscode-insiders://settings/github.copilot.preferredAccount))? If you remove the value, does that fix the issue for you?

the value for preferred account was empty on the latest update for github copilot , but when i revert back to  version v1.201.0 for copilot and revert github chat to v0.17.0 it shows up as my Email rather than my username.  As far as extensions related to git. actions, Code Space, copilot, pull request, repositories, and git theme.

**Comment by Martianing** [comment]
I couldn't use my extension in vscode until now, did anyone solve the problem?😭

**Comment by flcYtb** [comment]
@Martianing 
Have you tried this method?
Of course, you need to enable github copilot (https://github.com/settings/copilot),
but if you've already done that, just leave the field blank.
↓↓↓↓↓
> @flcYtb @CarlosaBauti @KaliaHayes @kennyr3221
> 
> Can you please tell me what the value of [the github.copilot.preferredAccount setting is](https://vscode.dev/redirect?url=vscode://settings/github.copilot.preferredAccount) (VS Code Insiders users, [click this link instead](https://vscode.dev/redirect?url=vscode-insiders://settings/github.copilot.preferredAccount))? If you remove the value, does that fix the issue for you?

**Comment by Martianing** [comment]
@flcYtb 
Now there is still a problem, I don't even know what went wrong, it's just that when I open the vscode extension again there is nothing, and there is no response to sending messages！
![image](https://github.com/user-attachments/assets/2b69a683-9ec2-4e3f-bcab-8808caa9703a)

**Comment by flcYtb** [comment]
@Martianing 
If leaving github.copilot.preferredAccount blank doesn't solve your problem, it's probably a different issue than mine, so you might want to create a new issue and report it as a different problem.

**Comment by Martianing** [comment]
@flcYtb 
thank you！I will try to find some other way.

**Comment by AlexeiEvenepoel** [comment]
> I found such tweet. My situation is same this tweet.
> 
> https://x.com/uYRpiPGFGDQULRp/status/1819327025309794440
> 
> In VS Code 1.92, the Copilot column does not appear when right-clicking, and the Chat in the left column does not respond. It seems that Github Copilot Chat 0.18.1 and 0.18.0 do not work. It works when I update to 0.17.1 (the GPT-4o conversion of Copilot applied in 1.92 seems to be applied in 0.17 and above).
> 
> VS Code 1.92で、右クリックで Copilot の欄が出なくなり、左欄の Chat も反応しない。どうやら、Github Copilot Chat 0.18.1, 0.18.0 が動かないもよう。0.17.1 に落としたら動く(一応 1.92で適用されたCopilotのGPT-4o化は、0.17以上ならされてるらしい)。
> 
> I downgradeed to v0.17.1, Copilot Chat works . Do you know why? Can't I use v0.18.3 or latest?

Gracias me ayudaste a resolverlo

**Comment by TylerLeonhardt** [comment]
I believe I tracked this down. You can try the fix in the:
* [VS Code Insiders](http://code.visualstudio.com/insiders/#win) build
* The prerelease version of the Copilot Chat extension

**Comment by flcYtb** [comment]
@TylerLeonhardt 

Thank you✨️

Is there anything I can try?

I installed the VS Code Insiders build and the pre-release version of Github Copilot Chat.

I confirmed that Github Copilot Chat works properly when I leave github.copilot.preferredAccount blank or enter an account name, but does not work when I enter an email address.

**Comment by TylerLeonhardt** [comment]
@flcYtb Hi! Thanks for being willing to try! You actually need _tomorrow_'s prerelease of the Copilot Chat extension. Sorry about that.

Would you mind trying tomorrow? I believe the extension will be released in like... 6hrs or so.

**Comment by flcYtb** [comment]
@TylerLeonhardt 
Okay, thanks for the info! I'll try it tomorrow.

**Comment by TylerLeonhardt** [comment]
@flcYtb should be available to test now! You need `v0.20.2024082101` of Copilot Chat.

**Comment by flcYtb** [comment]
@TylerLeonhardt 
I checked it! It seems to work without any problems.

GitHub Copilot works when github.copilot.preferredAccount is blank or is the name of an account already logged in to GitHub.

If for some reason a string that is not an account name (such as an email address or a meaningless string like "aaa") is entered, I am prompted to log in to GitHub, and once I log in it is replaced with my account name and GitHub Copilot starts working.

Thank you!!

**Comment by mjkokid** [comment]
Same issues after 30 mins using copilot. issues happen every 30 mins using and have to restart extention copilot again :

2024-09-10 **15:06:56.257** [info] [auth] Got Copilot token for mjkokid
2024-09-10 15:06:56.266 [info] [chat] copilot token chat_enabled: true
2024-09-10 15:06:56.266 [info] [githubTitleAndDescriptionProvider] GitHub.vscode-pull-request-github extension is not yet activated.
2024-09-10 15:06:59.008 [info] [contributions] activationBlocker from 'languageModelAccess' took for 8596ms
2024-09-10 15:07:25.978 [info] [chat fetch] request.response: [https://api.business.githubcopilot.com/chat/completions], took 2040 ms
2024-09-10 15:07:26.002 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-09-10 15:07:26.003 [info] [streamChoices] request done: requestId: [5d78769c-10ad-4121-beee-1108c7357a53] model deployment ID: []
2024-09-10 15:07:28.060 [info] [chat fetch] request.response: [https://api.business.githubcopilot.com/chat/completions], took 2051 ms
2024-09-10 15:07:28.062 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-09-10 15:07:28.063 [info] [streamChoices] request done: requestId: [531d51a2-39f3-4ede-9a42-7f5ebd978ea1] model deployment ID: []
2024-09-10 15:31:56.332 [info] [auth] Logged in as mjkokid
2024-09-10 15:36:59.159 [info] [auth] Logged in as mjkokid
2024-09-10 **15:37:00.215** [info] [LanguageModelAccess] LanguageModel/Embeddings are not available without auth token
2024-09-10 15:37:00.215 [info] [LanguageModelAccess] SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON

**Comment by flcYtb** [comment]
@mjkokid 
Are you using version 0.18.2?
The current version is 0.20.0, so why not try updating to the latest version?
I'm using the current version (0.20.0) and it's working fine.

**Comment by mjkokid** [comment]
@flcYtb 
I have uninstall and re-install Copilot but it's still 0.18.2

**Comment by flcYtb** [comment]
@mjkokid 
According to https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat&ssr=false

The latest version seems to be 0.20 or 0.21.

If you uninstall and reinstall it and it still shows 0.18.2, then I think it's a different problem, so I think it would be better to open a separate issue.
