### ISSUE TITLE
list of problems with copilot so far

### ISSUE THREAD

**Issue by chancels** [microsoft/vscode-copilot-release#1445]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

I'm mostly just venting so delete this if you want but it constantly deletes functional code and has no idea how to revert changes.  Seems like a bare minimum feature for an AI.  Might as well just delete the "apply in editor" button, it doesn't apply or change anything just straight up adds the code causing duplicates.  Very routinely claims to have edited code but constantly repeats the same non-functional code back at you no matter how many times you show it that the code and the error messages are unchanged.  Hard to believe they're charging for this - can I get a refund?

**Comment by craftzneko** [comment]
I just want to add to this, that i 100% agree. I see the exact same issues and at least objectively seems to have gotten worse in the last few months. The most irritiating is the hallucination that its made changes and if you ask it to detail the exact change its made it shows you the same code you provided to it. It happens so often now that everyone must have noticed this and just a few conversations with copilot should reveal this behaviour

**Comment by fisforfaheem** [comment]
Agree, The copilot support team dont reply as they should, millions of devs are using this and billions are being earned, and this AI is still afr behind small startups like Cody AI and tabnine and cursor editor

**Comment by digitarald** [comment]
While we read every issue, it is hard to triage catch-all issues for us as they are not actionable for the team. One recommendation is to use the thumbs-down button, which in the next release will also show a list of reasons and shows up in our quality metrics.

Can you clarify if most of the issue above is about the new _Apply Code_ on chat panel code blocks; or _Inline Chat_, or some mix?
