### ISSUE TITLE
已经登陆github账号, 但是chat却未登录, 无法聊天.

### ISSUE THREAD

**Issue by 592774447** [microsoft/vscode-copilot-release#1446]
![image](https://github.com/user-attachments/assets/99882bf1-99a6-4b52-a4d1-127e87e635ef)

**Comment by aiday-mar** [comment]
Hi could you please write the issue in English in detail? Thank you.

**Comment by 592774447** [comment]
Hello, I am using VSCode Copilot Chat. After updating to the latest version, my account cannot log in. After logging in, Copilot can be used normally, but Copilot Chat still shows the need to log in, as indicated by the red arrow in the picture. My GitHub account has already logged in, but Chat cannot be used

**Comment by 592774447** [comment]
Thank you very much for your reply. After checking my settings, I did indeed enable the GitHub. Copilot. PreferredAccount setting. After I turned it off, there were no more issues. Thank you again

**Comment by TylerLeonhardt** [comment]
@592774447 do you know why you set that setting in the first place?

**Comment by HongHaiyang** [comment]
Try installing the specific version 0.17.1 to solve the problem.

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode-copilot-release/issues/1444#issuecomment-2278793021
