### ISSUE TITLE
Stop scrolling when AI response reaches the top of the chat window

### ISSUE THREAD

**Issue by MikeTheGreat** [microsoft/vscode-copilot-release#1447]
_Please search existing issues to avoid creating duplicates_: Done!  I might have missed something, though
_Please test using the latest insiders build to make sure your issue has not already been implemented_: Done!

_Describe the feature you'd like._
When I ask Copilot a question it pretty routinely gives me a very long answer.  So long that it doesn't fit in my chat window (the panel on the left).  As it generates more and more text the starting text is pushed upwards, scrolling off the screen.  When it finishes I'm left looking at the end of Copilot's response even though I, as a human, need to start reading at the beginning of CoPilot's response.

**Would it be possible to set things up so that once the text has been pushed up to the top of the chat window that the scrolling stops?**  That way the start of the response is at the top of the window and I can start reading it (while Copilot keeps filling in more of it's response below, and now off-screen).

**Here's an example of what I'd like to see:**
![image](https://github.com/user-attachments/assets/5b823da6-b672-4419-b0b4-c7d651a4d170)

**However, here's the current default behavior:**
![image](https://github.com/user-attachments/assets/3314631c-a637-45b5-8bc3-d52bac0fddf5)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/138
