### ISSUE TITLE
Extension is using an API proposal 'lmTools' that is not compatible with the current version of VS Code

### ISSUE THREAD

**Issue by muendelezaji** [microsoft/vscode-copilot-release#1452]
- Copilot Chat Extension Version: v0.18.1
- VS Code Version: 1.93.0-insider
- OS Version: 14.5 (23F79)
- Logs:
- GitHub Copilot Extension Version: v1.220.0
- Other system information:
```
Version: 1.93.0-insider
Commit: ff8504ae52f8e0d0e9a33e6cb326efc21e42db3e
Date: 2024-08-06T05:03:52.944Z (6 hrs ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.5.0
```

**Steps to Reproduce:**

1. Just updated VS code insiders to the version above (`1.93.0-insider`) and started getting the error (screenshot below). The extension is not loaded and copilot chat view no longer appears in the activity bar.
2. I have tried restarting the extension, reloading the window, restarting the application as well as switching to the pre-release version of Github Copilot (`v1.220.1032 (pre-release)`) but none of that worked.

**Screenshots**:

- Extension page
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/fd84e74e-d650-4266-80a1-d51cfea3abb2">

---

- Startup error
![image](https://github.com/user-attachments/assets/58b565de-e5d6-4bf5-9dd0-6e69fc0fcf5e)

**Comment by lramos15** [comment]
Please switch to pre-release of GitHub Copilot Chat. With insiders you must use the pre-release version of copilot chat

**Comment by roblourens** [comment]
I can probably get the message to mention this.

**Comment by Polymath-Saksh** [comment]
Updating the VS Code Insiders to the current build fixes the issue! Guess the issue can be closed now.

**Comment by GiladShoham** [comment]
> Please switch to pre-release of GitHub Copilot Chat. With insiders you must use the pre-release version of copilot chat

how to do this?
Thanks

**Comment by shefmarkh** [comment]
I started seeing this message after updating VS Studio Insiders to the latest version this morning. I am using GitHub CoPilot Chat v0.19.2024080501 (pre-release). So I suppose updating VS Studio Insiders is not an option, given I have the latest version and this causes the problem?

**Comment by flowen** [comment]
> I started seeing this message after updating VS Studio Insiders to the latest version this morning. I am using GitHub CoPilot Chat v0.19.2024080501 (pre-release). So I suppose updating VS Studio Insiders is not an option, given I have the latest version and this causes the problem?

I uninstalled and re-installed using the specific version option. I picked one version older and it works again. Just wait to update again after a new version comes up

**Comment by strophy** [comment]
I started seeing this today as well in VS Code Insiders. I tried uninstalling both GitHub Copilot and GitHub Copilot Chat, then successfully installed GitHub Copilot v1.223.1064 (pre-release) but failed to install GitHub Copilot Chat v0.20.2024082301 (pre-release) with error `Can't install 'Github Copilot Chat' extension. Extension is using an API proposal 'lmTools' that is not compatible with the current version of VS Code.`

My VS Code version is:
```
Version: 1.93.0-insider
Commit: c2aa3c4625ed4b46448fa546ac5f2e93b0757718
Date: 2024-08-22T05:03:56.076Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Linux x64 6.10.6-061006-generic
```

**Comment by rainmanjam** [comment]
I'm getting the same error. 

<img width="1017" alt="image" src="https://github.com/user-attachments/assets/6ab0b8de-db27-476a-914a-9850dde04d4f">

**Comment by blundin** [comment]
I'm seeing this as well with VSCode Insiders build.

**Comment by roblourens** [comment]
@sandy081 It sounds like when the vscode build doesn't support the api version of the latest extension, maybe it's not finding the compatible pre-release version in the marketplace? Is that possible?

**Comment by roblourens** [comment]
@sandy081 I installed `c2aa3c4625ed4b46448fa546ac5f2e93b0757718`, one build before Friday's build which had an API version increase, and I can repro the issue.

![Image](https://github.com/user-attachments/assets/6c75beff-9008-40eb-b3e6-90cfdc7ef5fb)

**Comment by josephdaw** [comment]
I am on the following version of VS Code Insiders: 

```
Version: 1.93.0-insider (Universal)
Commit: c2aa3c4625ed4b46448fa546ac5f2e93b0757718
Date: 2024-08-22T05:03:56.076Z
Electron: 30.3.1
ElectronBuildId: 9960165
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

```
I have the GitHub Copilot extension installed: `v1.223.1065 (pre-release)`

But when I try to install GitHub Copilot Chat v0.20.2024082301 (pre-release) I get the following error message: 

`'Can't install 'GitHub Copilot Chat' extension. Extension is using an API proposal 'lmTools' that is not compatible with the current version of VS Code.'`

**Comment by roblourens** [comment]
@josephdaw  You can update vscode or go back an extension version to get unstuck.

**Comment by MarvinBo** [comment]
I updated VS Code Insider to 1.93.0-insider and the GitHub Copilot extension to v1.223.1066 (pre-release). There is now error message any more, but the Copilot chat has disappeared.

**Comment by sandy081** [comment]
> maybe it's not finding the compatible pre-release version in the marketplace? Is that possible?

That's true. I am not going back in versions to find the one that is api compatible. I do not remember the reason, it could be an oversight.

Fixing it.

**Comment by CharlonTank** [comment]
> > Please switch to pre-release of GitHub Copilot Chat. With insiders you must use the pre-release version of copilot chat
> 
> how to do this? Thanks

<img width="616" alt="image" src="https://github.com/user-attachments/assets/e40d96e3-21b9-4c2c-9bf6-e00da1af1c68">

**Comment by TerryHarker** [comment]
I haven't even really initiated Insiders, but hat this too. After a few checks I saw a button to "restart extension" at the gitGub Copilot. After klicking that it was fine.

**Comment by benlavender** [comment]
Also an issue for me once I updated to this months release:

![image](https://github.com/user-attachments/assets/f6d8f69f-ecc9-4e04-bb50-58e8f8e85cc3)

**Comment by bibaswan-bhawal** [comment]
Currently facing the same issue
github copilot chat: v0.20.3
VSCode: 1.94.0 (Universal)
