### ISSUE TITLE
Add horizontal scroll bar

### ISSUE THREAD

**Issue by MikeTheGreat** [microsoft/vscode-copilot-release#1453]
The Copilot Chat window does an excellent job of flowing text to match the available width of the chat window, except when it's displaying source code.  The source code frequently goes past the right edge of the chat window in order to maintain readable formatting (this is all good).

**Would you mind adding a horizontal scroll bar to the chat window so that one can scroll left and right to see all the source code, without having to resize the chat window?**

**Comment by mjbvz** [comment]
You should already be able to scroll the code block themselves. The scrollbar may not show until you scroll or you place your cursor at the bottom of the code block in chat

![Image](https://github.com/user-attachments/assets/2967161f-b896-4b86-a302-ba446b3cdc27)


Opening an issue to see if we should also respect `editor.scrollbar.horizontal` here

The other option is to set `"chat.editor.wordWrap": "on"` which will wrap the contents of the code block to fit the available area

**Comment by MikeTheGreat** [comment]
Sorry!  I didn't see the scrollbar appear, but now that I went back, tried it, and looked for it it's definitely there.

Thanks!
