### ISSUE TITLE
El servicio de lenguaje JS/TS se bloqueó 5 veces en los últimos 5 minutos.

### ISSUE THREAD

**Issue by Rafaamaya** [microsoft/vscode-copilot-release#1454]
Type: <b>Bug</b>

Inicialización de características del lenguaje JS/TS

Extension version: 0.17.2024062801
VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 6, 5|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 1b37cb94-4fe0-49ce-b756-a781aad91b49|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31104043
refactorc:31101458
ccpltc:31103427
pythonrstrctxt:31103193
wkspc-onlycs-c:31102393

```

</details>

**Comment by mjbvz** [comment]
This doesn't seem to be copilot related. Please file an issue against VS Code in English. Be sure to include additional context such as steps to reproduce the problem or the type of project you are working on
