### ISSUE TITLE
Chat participant raise error Message exceeds token limit

### ISSUE THREAD

**Issue by ashrafulrelx** [microsoft/vscode-copilot-release#1456]
- Copilot Chat Extension Version: v0.18.1
- VS Code Version: 1.92.0
- OS Version: MacOS 14.5
- Logs: Error: Message exceeds token limit.\n    at VR._provideLanguageModelResponse (/Users/myuser/.vscode/extensions/github.copilot-chat-0.18.1/dist/extension.js:634:4090)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Steps to Reproduce:

1. Chat participant is using copilot model id: `github.copilot-chat/2/gpt-4`
2. Context size: 18591 character
3. The error shows at the time of displaying the response`for await (const fragment of chatResponse.text)`

**Comment by roblourens** [comment]
You will need to trim your prompt to fit in the context window. You can use `countTokens` and `maxInputTokens` on the `LanguageModelChat` to do this. You also might be interested in https://github.com/microsoft/vscode-prompt-tsx to do this for you with nice dynamic prompt sizing behavior.
