### ISSUE TITLE
Add Scroll-to-Bottom Button in Chat Box

### ISSUE THREAD

**Issue by dioro** [microsoft/vscode-copilot-release#146]
Please consider adding a scroll-to-bottom button in Copilot Chat. It would improve the user experience by allowing quick navigation to the latest messages. Currently, scrolling manually becomes tedious when the chat history is long.

**Comment by roblourens** [comment]
You can also grab the scrollbar. I disagree that there should be a button for this. It's the same for every scrollable element in VS Coded
