### ISSUE TITLE
Make it easy to compare the code on chat window and a file

### ISSUE THREAD

**Issue by gamousquesORT** [microsoft/vscode-copilot-release#147]
I am getting to know copilot chat, a fantastic tool! I use copilot chat trying to follow some prompt engineering tips, like following a Chain of Thought. 
In this process, I frequently ask the copilot to refactor or to improve selected code. I am having a hard time finding the difference between the selected code and the one on the copilot chat window. May having a feature like diff between both windows might help.

Thank you

**Comment by bsparks** [comment]
I agree, and you can do it right now by picking the "insert into new file" and then manually doing a diff vs the active one. I think it would be good to add a single click option "diff with active" or something that does that automatically

**Comment by OptionalLion411** [comment]
This could be a great addition to the comparison view available when using inline hints (CTRL+I), as the chat window often provides more context.

**Comment by roblourens** [comment]
Using inline chat is the best way to work on code in an editor, and it can show a diff when it makes changes
