### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by maciek324** [microsoft/vscode-copilot-release#1473]
For every question i'm just getting the answer "Oops, your response got filtered. Vote down if you think this shouldn't have happened.". Even if i just type "Hello" in the Chat.

- Copilot Chat Extension Version: v0.7.1
- VS Code Version: v1.82.0
- OS Version: Windows 10 Enterprise 19045.4717

**Comment by lramos15** [comment]
Please update your VS Code + Copilot chat then attach your logs via `CMD / CTRL + SHIFT +U` -> Github Copilot Chat.

Thanks!
