### ISSUE TITLE
Please check your firewall rules and network connection then try again. Error Code: ERR_HTTP2_STREAM_CANCEL.

### ISSUE THREAD

**Issue by dkumarbaug** [microsoft/vscode-copilot-release#1475]
- Copilot Chat Extension Version: 
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
What version of VS Code and the Github Copilot Chat extension are you using?

Can you add the GitHub Copilot Chat log (F1 > Output: Show Output Channels... > GitHub Copilot Chat) and the diagnostics output (F1 > Developer: GitHub Copliot Chat Diagnostics) using the latest VS Code Insiders and GitHub Copilot Chat versions?
