### ISSUE TITLE
gets stuck in loading, does not generate any code or text in the chat or on the window. 

### ISSUE THREAD

**Issue by Gonzo-Gonzo-Gonzo** [microsoft/vscode-copilot-release#1477]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by lramos15** [comment]
Can you include a screen recording and ensure you're on the latest versions? Your issue body is quite empty so I cannot further troubleshoot.

**Comment by Gonzo-Gonzo-Gonzo** [comment]
Hi.
All good, this stopped happening. A
