### ISSUE TITLE
Keyboard navigation to scroll the response

### ISSUE THREAD

**Issue by hron** [microsoft/vscode-copilot-release#1482]
It is not impossible to scroll up/down a long response in Github Copilot Chat window. I know that shift+tab moves the cursor to previous code blocks, but this is not enough. Furthermore, when a code block outside of the current view the cursor moves to a code block which is invisible.

Ideally, I would love to have something like caret mode from Firefox/Chrome, so I can freely navigate the response (even outside of code blocks). Having vscode commands to just scroll up/down by page is something minimal, but functional.

[Screencast from 2024-08-18 13-52-48.webm](https://github.com/user-attachments/assets/1eacd547-f153-45d0-a3f5-21dfd4aa23ad)

**Comment by roblourens** [comment]
There are commands for this, `list.scrollUp`/`list.scrollDown`

**Comment by hron** [comment]
I don't think `list.scrollUp` / `list.scrollDown` is a real solution. The scrolling speed is to slow. Check the demo:

[Screencast from 2024-08-20 10-20-23.webm](https://github.com/user-attachments/assets/18fa6842-a017-4d0f-86f1-65020b261064)

Also, I couldn't figure out a `when` context I can use to limit the key bindings to the chat window. I have tried `listFocus`, but it doesn't work. Any suggestions? In my case Copilot Chat window is on the panel, not sidebar, so I assume it should be something like `panelFocus && activePanel == 'workbench.view.???'`?

```json
  {
    "key": "pageup",
    "command": "list.scrollUp",
    // "when": "listFocus" 
  },
  {
    "key": "pagedown",
    "command": "list.scrollDown",
    // "when": "listFocus"
  }
```

**Comment by roblourens** [comment]
It seems reasonable to me, do you want something that would scroll by page, or the same as here but faster?

You could use the `inChat` context key

**Comment by hron** [comment]
Thank you for `inChat` hint, it works!

> It seems reasonable to me, do you want something that would scroll by page, or the same as here but faster?

If you ask me I believe there several improvements need to be done:

1. Scrolling by page is must have
2. Commands to scroll to the previous next answers, similar to `workbench.action.terminal.scrollToPreviousCommand` / `workbench.action.terminal.scrollToNextCommand`
3. The chat window should scroll automatically when the cursor goes out of the view via Tab/Shift+Tab shortcuts (in chat window these keys move the cursor to next/previous code blocks)

**Comment by roblourens** [comment]
For 1, I opened https://github.com/microsoft/vscode/issues/226194

For 2, you can just use the arrow keys, or do I misunderstand?

Also agree for 3, there are some oddities with focus handling here, there is an open issue for this

**Comment by hron** [comment]
> For 2, you can just use the arrow keys, or do I misunderstand?

I don't think arrow keys are related. Let's imagine you talk to Copilot and it generated several responses, so the chat window looks like this:

```txt
Response 1 
...long body of Response 1...

Response 2
...long body of Response 2...

Response 3
...long body of Response 3...
```

So, it would be great to have commands to scroll the chat window to previous/next Response.

**Comment by roblourens** [comment]
Yeah, so you can use cmd+up to move focus from the input to the chat list, then arrow keys to navigate by response
