### ISSUE TITLE
GitHub Co-Pilot commit messages not synchronized / lags behind

### ISSUE THREAD

**Issue by spacecat** [microsoft/vscode-copilot-release#1483]
I'm always using the latest (stable) build of VS Code and I've been using AI to generate commit messages for about a year now.

I think it's fantastic that I can save time by not having to come up with a clever commit message every time I need to make a commit. But the problem I'm facing is that a lot of the times (I would say 50% of the time) when clicking the "magic" icon in the commit message textarea box, the message that is generated is from old context; i.e. from code changes that I maybe did a few moments ago. It's as if the previous code changes are cached or something and then I have to click the magic icon 7-9 times before it realizes that I'm looking for a commit message for my latest code changes and not from the changes I did 10-30 minutes ago. And sometimes I'm force to type the message manually because it seems it's incapable of understanding what changes I've just made.

All in all it's a fantastic features that saves me tons of time but if this strange behavior would not exist it would be even better.

I hope you can take a look at it.

**Comment by Gami13** [comment]
this still happens

**Comment by spacecat** [comment]
> this still happens

And I thought I was the only one! 😁

**Comment by lszomoru** [comment]
Since the issue has been filed we have switched to a better model, improved the context and in the latest Copilot Chat release added support for custom instructions through the github.copilot.chat.commitMessageGeneration.instructions setting. All this should result in better commit messages so I am optimistically closing this issue.
