### ISSUE TITLE
WSL: Error Code: ETIMEDOUT

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-copilot-release#1484]
> @chrmarti I am running latest VSCode 1.92.0 connected to WSL. I am getting the following error sporadically (Yesterday it worked most of the time and today it worked once or twice): 
> 
> 
> 
> **Please check your firewall rules and network connection then try again. Error Code: ETIMEDOUT**
> 
> 
> 
> Here is the log (Github Copilot: Open Logs):
> 
> 
> 
> ```
> 
> 2024-08-08 14:21:52.490 [info] [streamChoices] request done: headerRequestId: [5b4d17fa-b6d2-4e53-b564-98108264bfcf] model deployment ID: [d086-20240807144915]
> 
> 2024-08-08 14:22:28.198 [error] [default] Error sending telemetry FetchError: 
> 
>     at fetch (/home/arnabb/.vscode-server/extensions/github.copilot-1.221.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:99:11)
> 
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at cachingFetch (/home/arnabb/.vscode-server/extensions/github.copilot-1.221.0/node_modules/@adobe/helix-fetch/src/fetch/index.js:288:16)
> 
>     at OO.fetch (/home/arnabb/.vscode-server/extensions/github.copilot-1.221.0/lib/src/network/helix.ts:96:22) {
> 
>   type: 'system',
> 
>   _name: 'FetchError',
> 
>   code: 'ETIMEDOUT',
> 
>   errno: undefined,
> 
>   erroredSysCall: undefined
> 
> }
> 
> ```
> 
> # Output of "Developer: GitHub Copilot Chat Diagnostics" when things are NOT working:
> 
> 
> 
> ## GitHub Copilot Chat
> 
> 
> 
> - Extension Version: 0.18.1 (prod)
> 
> - VS Code: vscode/1.92.0
> 
> - OS: Linux
> 
> - Remote Name: wsl
> 
> 
> 
> ## Network
> 
> 
> 
> User Settings:
> 
> ```json
> 
>   "github.copilot.advanced": {
> 
>     "debug.useElectronFetcher": true,
> 
>     "debug.useNodeFetcher": false
> 
>   }
> 
> ```
> 
> 
> 
> Connecting to https://api.github.com:
> 
> - DNS Lookup: 20.207.73.85
> 
> - Electron Fetcher: Unavailable
> 
> - Node Fetcher: HTTP 200
> 
> - Helix Fetcher (configured): HTTP 200
> 
> 
> 
> Connecting to https://api.githubcopilot.com/_ping:
> 
> - DNS Lookup: 140.82.112.21
> 
> - Electron Fetcher: Unavailable
> 
> - Node Fetcher: timed out after 10 seconds
> 
> - Helix Fetcher (configured): timed out after 10 seconds
> 
> 
> 
> ## Documentation
> 
> 
> 
> In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
> 
> 
> 
> # Output of "Developer: GitHub Copilot Chat Diagnostics" when things are working:
> 
> 
> 
> ```
> 
> ## GitHub Copilot Chat
> 
> 
> 
> - Extension Version: 0.18.1 (prod)
> 
> - VS Code: vscode/1.92.0
> 
> - OS: Linux
> 
> - Remote Name: wsl
> 
> 
> 
> ## Network
> 
> 
> 
> User Settings:
> 
> ```json
> 
>   "github.copilot.advanced": {
> 
>     "debug.useElectronFetcher": true,
> 
>     "debug.useNodeFetcher": false
> 
>   }
> 
> ```
> 
> 
> 
> Connecting to https://api.github.com:
> 
> - DNS Lookup: 20.207.73.85
> 
> - Electron Fetcher: Unavailable
> 
> - Node Fetcher: HTTP 200
> 
> - Helix Fetcher (configured): HTTP 200
> 
> 
> 
> Connecting to https://api.githubcopilot.com/_ping:
> 
> - DNS Lookup: 140.82.113.21
> 
> - Electron Fetcher: Unavailable
> 
> - Node Fetcher: HTTP 200
> 
> - Helix Fetcher (configured): HTTP 200
> 
> 
> 
> ## Documentation
> 
> 
> 
> In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).
> 
> 
> 
>  

 _Originally posted by @arnabbiswas1 in [#541](https://github.com/microsoft/vscode-copilot-release/issues/541#issuecomment-2275370116)_

**Comment by chrmarti** [comment]
@arnabbiswas1 Are you changing WSL distros or maybe moving your machine between networks (e.g., home and office) between the two?

**Comment by purp1e-ace** [comment]
same here

**Comment by nitinsanatan1** [comment]
I was also facing this issue, turned out that my network proxy DNS was unable to resolve the github. 
I made changes in my network DNS & changed it to google DNS (primary: 8.8.8.8, secondary 8.8.4.4).
Works for me now.

**Comment by Amroning** [comment]
> I was also facing this issue, turned out that my network proxy DNS was unable to resolve the github. I made changes in my network DNS & changed it to google DNS (primary: 8.8.8.8, secondary 8.8.4.4). Works for me now.

thanks bro.it works

**Comment by arnabbiswas1** [comment]
> [@arnabbiswas1](https://github.com/arnabbiswas1) Are you changing WSL distros or maybe moving your machine between networks (e.g., home and office) between the two?

Sorry for not noticing this thread!

Yes. I connect from both office and home network. Office it's behind corporate firewall.

**Comment by chrmarti** [comment]
@arnabbiswas1 This looks like an issue with the corporate firewall. Please check with your IT that they allow connections to all required hosts: https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot

**Comment by arnabbiswas1** [comment]
> [@arnabbiswas1](https://github.com/arnabbiswas1) This looks like an issue with the corporate firewall. Please check with your IT that they allow connections to all required hosts: https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot

But, it happens to the "VSCode github copilot" instance which is running on the WSL. The instance which is running on the host (Windows) operating system, does not face any connectivity issue.

**Comment by chrmarti** [comment]
@arnabbiswas1 Not sure what could make the difference between github.com and githubcopilot.com then. You could install VS Code Insiders with the latest GitHub Copilot Chat pre-release version and rerun the diagnostics command to get some additional insights. (Stable versions with the additional diagnostics are expected next week.)
