### ISSUE TITLE
Add setting to disable renaming the Chat window in the editor

### ISSUE THREAD

**Issue by felipefcm** [microsoft/vscode-copilot-release#1485]
When you open the Chat window in the editor, it renames the tab with a summary of the discussion, which is usually long and takes too much space.
It would be nice to have a setting to control this behaviour and keep it always something short like "Chat".

**Comment by mannfuri** [comment]
I have opened multiple Copilot chat tabs to handle different tasks. 
However, I am not satisfied with the automatically generated names and would like to customize these tab names myself.

**Comment by roblourens** [comment]
You can now rename chat sessions manually by running the command "Show Chats" or clicking it in the chat panel, and clicking the pencil icon by the chat session.
