### ISSUE TITLE
Content exclusions for entire endpoints does not work / not available

### ISSUE THREAD

**Issue by rajbos** [microsoft/vscode-copilot-release#1487]
According to the [docs](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/setting-policies-for-copilot-in-your-organization/excluding-content-from-github-copilot#configuring-content-exclusions-for-your-organization) you can configure repositories as content exclusions:

```
http[s]://host.xz[:port]/path/to/repo.git/

git://host.xz[:port]/path/to/repo.git/

[user@]host.xz:path/to/repo.git/

ssh://[user@]host.xz[:port]/path/to/repo.git/
```

This also works if you configure the url without `.git`, although that is not in de docs (if supported, this should be updated). So the example below works as well:

```
https://my-bitbucketserver.domain/folder/repo: 
- "*"
```

As indicated in the code example in the docs [here](https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/setting-policies-for-copilot-in-your-organization/excluding-content-from-github-copilot#example-of-repositories-and-paths-in-organization-settings) you can also do wildcards on a host:
```
# In the `copilot` repository of any GitHub organization:
git@github.com:*/copilot:
- "*"
```

From this I want to exclude the entire host:
```
https://my-bitbucketserver.domain:
- "*"
```

I validated the same behavior with the reference below, although that should not matter according to the docs. It is stored as well, but does not work.
```
git@my-bitbucketserver.domain:
- "*"
```

This is stored by the UI, so it seems valid. During testing with Copilot suggestions it is not used and repos on that host are not excluded. Excluding a single repo does work.

|Tool|Version|
|---|---|
|Copilot Chat Extension|v0.18.2|
|VS Code|1.92.0|
|OS|Linux x64|

I tested these options by following these steps:
- Configure the exclusions
- Go to VS Code
- Run Developer Reload window (as indicated by the docs)
- Opened a file in the current workspace that is coming from the excluded host
- The Copilot Icon shows it is using the file and is NOT showing the strikethrough icon and message indicating "this file is excluded"
- Copilot chat happily used the file for context and explains the file

**Comment by lramos15** [comment]
@rajbos Can you try wildcarding the end of the domain i.e

```
https://my-bitbucketserver.domain/*:
- "*"
```

**Comment by rajbos** [comment]
Forgot to mention that, I tried wildcards already, both with one and two '*'. Same result.

**Comment by lramos15** [comment]
Can you do `F1 -> Set Log Level -> Github Copilot Chat -> Trace` and then reload your window and see what the output channel shows. You will need vscode insiders + GH Copilot Chat pre-release for the most up to date info.

I tested with a Azure Dev Ops path and it appears to work. I do not have a bitbucket domain to test with
```
git://dev.azure.com/microsoft/test/*:
- '*.ts'
- ```

**Comment by rajbos** [comment]
Thanks! I'll try that tomorrow. 

From your example it is excluding still a part of the server, which we have seen working before. 

The goal is to run this with just the domain itself. So that would be:
``` 
git://dev.azure.com/*:
- '*.ts'
```

In your case `microsoft` is already an organization, and `test` a project in that org.

**Comment by rajbos** [comment]
That's interesting. I tried this once more with our current extension versions (we're still on VS Code 1.92.0 at the moment, waiting for 1.93.0 to become stable).

|Extension|Version|
|---|---|
|Copilot|v1.223.0|
|Chat|v0.18.2|

And with this config the exclusion for repos on that host works:
``` 
git://bitbucket.domain.com/*:
- "*"
```

Our test was with the https setup where it does not work (documentation states you only need one config):
``` 
https://bitbucket.domain.com/*:
- "*"
```

**Comment by lramos15** [comment]
Thanks for the info. I'll see if we are able to get both rules to properly apply as the protocol should not matter.

Does this at least unblock your use case of blocking an entire domain?

**Comment by rajbos** [comment]
Yes it does!

**Comment by rajbos** [comment]
Closing this issue because the workaround is configured. Should be addressed by product of course to make it work the same across all protocols.
