### ISSUE TITLE
Content exclusion session info window does not work most of the time

### ISSUE THREAD

**Issue by rajbos** [microsoft/vscode-copilot-release#1488]
- Copilot Chat Extension Version: v0.18.2
- VS Code Version: 1.92.0
- OS Version: Linux x64
- Logs: Nothing shows up in the output window of any of the Copilot extensions

Steps to Reproduce:

1. Open the chat
2. Click on "content exclusion session info"
3. Nothing happens (most of the time, sometimes it does work)
4. Nothing visible in any of the logs of the Copilot Extensions

**Comment by lramos15** [comment]
I intended to remove this view when the logging framework backing Copilot chat was improved upon so we could just log the appropriate info in the output channel. I have gone ahead and removed `Content exclusion session info`
