### ISSUE TITLE
I can't see the Copilot chat window  

### ISSUE THREAD

**Issue by lafredi** [microsoft/vscode-copilot-release#149]
I got access to test Copilot X Beta, so I installed Copilot Nightly and uninstalled my classic Copilot from GitHub. However, I can't see the chat window. I don't get any logs error, but I'm sure Copilot works well because code comments trigger copilot code suggestions. the probleme it just don't see the Copilot chat window yet as expected in the copilot X version.
VS Code Version: 1.87.11
OS Version: Windows 10
Logs: I didn't get any logs

**Comment by golam71** [comment]
You need vs code insiders (igreen logo)
and install the copilot nightly (not the regular extension) 

> I got access to test Copilot X Beta, so I installed Copilot Nightly and uninstalled my classic Copilot from GitHub. However, I can't see the chat window. I don't get any logs error, but I'm sure Copilot works well because code comments trigger copilot code suggestions. the probleme it just don't see the Copilot chat window yet as expected in the copilot X version. VS Code Version: 1.87.11 OS Version: Windows 10 Logs: I didn't get any logs

**Comment by lafredi** [comment]
thank you very much, 
yes  it works only with vs code **insiders**
