### ISSUE TITLE
Let me set a base prompt

### ISSUE THREAD

**Issue by mythemeria** [microsoft/vscode-copilot-release#1493]
I like to have my tabs 2 spaces wide. I have found it incredibly frustrating having to remind copilot to do this. Please let me set some basic info like "use 2 space tabbing" to be included in all my prompts. Note that this is just one use-case! I have a number of other ways I would use this, and it would be very cool if this could be set on a per-workspace basis. For eg, I have certain libraries I have issues with that I want copilot to not recommend using, and certain codebases I work on often require me to remind copilot of the context to get a helpful response.

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode-copilot-release/issues/563
