### ISSUE TITLE
Line numbers are off by one

### ISSUE THREAD

**Issue by shreyasm-dev** [microsoft/vscode-copilot-release#150]
Version: 1.79.0-insider (Universal)
Commit: 2dfb838f494f035099e999f0cd0eff5f1f488a30
Date: 2023-05-26T05:24:15.292Z (1 day ago)
Electron: 22.5.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

- Logs:
> **Prompt** (on line 44)
> Which line am I on?
>
> **GitHub Copilot**
> The cursor is on line 43.

> **Prompt** (on line 1)
> Which line am I on?
>
> **GitHub Copilot**
> The active selection is not highlighting any specific line. Could you please provide more context or information about the file you are working on?

Steps to Reproduce:

1. Open an editor and put your cursor on any line
2. Ask it "Which line am I on?"
3. If the cursor is on line 1, it will get confused, otherwise it will answer the line number minus one (perhaps zero-indexed?)

**Comment by digitarald** [comment]
Seems to work, but using lines in natural language doesn't seem very reliably. Re-open if you have a use case.

<img width="1519" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/9fb4d51f-67a5-496e-86e7-15e014741d7e">
