### ISSUE TITLE
random names/emails auto-complete, circumventing blocks, generic responses to specific code

### ISSUE THREAD

**Issue by klapenotiere** [microsoft/vscode-copilot-release#1501]
Local Machine:
Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Sometimes running over SSH
Remote:
VS Code Version: 1.82.0  
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6  
Date: 2023-09-06T09:56:24.653Z  
Electron: 25.4.1  
ElectronBuildId: 23467194  
Chromium:114.0.5735.289  
Node.js: 18.16.0  
V8 11.4.183.29-electron.0  
OS: Ubuntu 22.04 LTS  
GitHub Copilot Version: 1.116.0  

A list of a few issues after my first month. I can separate them out.

1. Consistently recommends deprecated functions/methods, and even after explicitly prompting "method_x() is deprecated, do not recommend it again" it will continue to proved it in autocompletes and chat suggestions.
2. When provided with a prompt like "Using specific references to the selected code at line 50 in the attached file, how would I..." it will then respond with generic, hypothetical code. I have tried many variations of attaching files, and selected code to the prompt, but this is very common and frequent.
3. "Sorry, I can't help with that" when asking about certain files, like putting variable output into a json format and writing to file, then attaching it to the prompt, to help with analysis, it will say "can't help with that", but if you rename the file to somevar.py and then ask the same question it will do it.
4. Unable to view cell output in jupyter notebooks, but can few the exceptions and errors, this is not super helpful and requires lots of work arounds for helpful debugging.
5. **Auto-completes other people's names and email addresses.** I turned of the other peoples' code option but this still happens.
6. Copy, Copy All context menus often don't work appropriately, always just copy-all.

**Comment by isidorn** [comment]
This should work much better with the latest VS Code Stable and GH Copilot. If you still see issues like this feel free to open a new one with reproducible steps. Thank you
