### ISSUE TITLE
Golang code randomly prompts

### ISSUE THREAD

**Issue by erdong01** [microsoft/vscode-copilot-release#1502]
It’s okay if it’s not smart enough, but at least the basic code prompts should be correct. Always giving wrong prompts really affects the programming experience. Please fix it.

- Copilot Chat Extension Version: v1.223.0
- VS Code Version:  1.92.2
- OS Version: Mac OS 15
- Logs:

Steps to Reproduce:

1.   New(). All subsequent chain calls are error prompts
2. Functions can introduce inferences, but they are all wrong

**Comment by rebornix** [comment]
@erdong01 can you please share more information to help troubleshoot? For example, an example file along with a screen recording to help me reproduce this locally would be very helpful, thank you!
