### ISSUE TITLE
Errror ERR_HTTP2_STREAM_CANCEL in Visual Studio Code with Github Copilot

### ISSUE THREAD

**Issue by MatthiasGanz** [microsoft/vscode-copilot-release#1503]
We encounter a problem when using Github Copilot with Visual Studio Code. "Please check your firewall rules and network connections. Error Code: ERR_HTTP2_STREAM_CANCEL This error happens only whith Visual Studio Code. With Visual Studio Pro/Enterpries or other IDEs (e.g. Jetbrains) everything works fine.

I found a workaround wich may solve the problem 
[ERR_HTTP2_STREAM_CANCEL · Issue #741 · microsoft/vscode-copilot-release (github.com)](https://github.com/microsoft/vscode-copilot-release/issues/741)

I set in my environment the following parameter:
![image](https://github.com/user-attachments/assets/37e8b3e4-5484-4165-8f34-d0d6c5c4bab5)

Now I can't reproduce the issue. In the article it is mentioned that it's only an experimental setting.
Could you please advice how to fix the problem for productive environments.

**Comment by chrmarti** [comment]
The Electron fetcher you enabled is the new default locally (starting with the upcoming release). The Helix fetcher was the previous default and remains the default in Remote Development setups for now.

**Comment by chrmarti** [comment]
Continuing to track as https://github.com/microsoft/vscode-copilot-release/issues/741.
