### ISSUE TITLE
Typescript Language Mode (5.5.4) hangs

### ISSUE THREAD

**Issue by stevenrobson** [microsoft/vscode-copilot-release#1505]
Type: <b>Bug</b>

When working with a large Angular 18.2.1 project, Copilot Chat is causing the TypeScript Language Mode to hang. The status bar shows a refresh spinner spinning indefinitely next to 'TypeScript 5.5.4'. Using Extension Bisect in vscode narrowed it down to the Copilot Chat extension.

I'll look for filters or exclusion options in Copilot Chat settings as I am sure the project is simply too large for Copilot to fully reference. A nice to have option would be a right-click on file/folder -> Copilot -> include/exclude from Copilot.

Virtual Machine:
Processor: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz   2.59 GHz
Installed RAM: 32.0 GB
OS build: 19045.4780

Extension version: 0.18.2
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31111718
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562cf:31125794

```

</details>

**Comment by mjbvz** [comment]
I'm somewhat doubtful it's actually chat but does disabling it and restarting VS Code fix the issue?

**Comment by stevenrobson** [comment]
Yes, disabling it does fix the issue in our Angular project, even without restarting VS Code. I wouldn't have guessed it was chat, but when using the 'Help: Start Extension Bisect' feature of VS Code, it narrowed it down to chat. When Bisect disabled chat the TypeScript service started working again within a few seconds. The only other thing I've noticed that slows down the TypeScript service is when enabling 'Settings >TypeScript > References Code Lens', but that feature never completely hangs the service.

To give you an idea, our project is up to 150 Angular components. The issue could be a combination of many factors. The issue occurs in VS Code Insiders Edition as well. We have no issues in our .NET and Python projects, which are considerably smaller.

**Comment by mjbvz** [comment]
Thanks. Can you also check if this only happens if you start a chat? For example, try clearing the current chat and then reloading VS Code. Interested to know if the problem also happens in that case

**Comment by stevenrobson** [comment]
I didn't think about starting a new chat. :/

After starting a new chat, another error that I have been getting popped up stating "The JS/TS language service crashed 5 times in the last 5 minutes". However, after that message cleared the TypeScript service stopped refreshing and properly showed the version the project is using. Everything has been working fine for about 5 hours. I have not used the new chat session yet. I'll hold off from using it for the rest of the week to see if the problem returns with an unused chat session. I'll update this issue with my findings.

**Comment by stevenrobson** [comment]
No TypeScript hangs for two days with an empty chat in the side bar. I'll start chatting a lot with it next week.

**Comment by stevenrobson** [comment]
No issues last week. Starting a new chat seems to have resolved the issue. I'll use @workspace heavily and call it fixed after a couple more days.

**Comment by mjbvz** [comment]
Thanks for checking. Tentatively closing but let me know if this comes back
