### ISSUE TITLE
accept persistent instructions

### ISSUE THREAD

**Issue by macMikey** [microsoft/vscode-copilot-release#1513]
i would like some instructions to remain persistent, especially when i tell copilot to remember the instructions. it seems that copilot forgets instructions i tell it to always remember, sometimes even within the same session.
example: when providing me suggestions to modify my code, retain all the comments that were in the code snippet i gave you.

**Comment by thegrince** [comment]
+1. Examples where it could be useful for me: 
"Always generate code with indents as tabs, not spaces", 
"Don't modify my code, only show references and examples, unless I ask explicitly for code",
...

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/563

Also see `github.copilot.chat.experimental.codeGeneration.instructions` (currently in Insiders/pre-release)
