### ISSUE TITLE
unhandled status from server: 404 404 page not found

### ISSUE THREAD

**Issue by truongtamthanh2004** [microsoft/vscode-copilot-release#1514]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by lramos15** [comment]
Can you please include your logs via `CMD / CTRL + SHIFT + U` -> `GitHub Copilot Chat` as well as ensure you're on the most up to date versions.
