### ISSUE TITLE
Github Copilot is deadnaming

### ISSUE THREAD

**Issue by leanneurb** [microsoft/vscode-copilot-release#1519]
- Copilot Chat Extension Version: 
- VS Code Version: v1.224.0
- OS Version: Windows 11
- Logs:

Steps to Reproduce:

1. Install Github Copilot in VS Code
2. Go to the Chat tab
3. Where it says, "Welcome, @xyz, I'm your Copilot" at the top, xyz is not the current github username, but is an older one. In my case, it's a deadname I deleted and shouldn't even be accessible by Copilot.

**Comment by lramos15** [comment]
Can you try signing in and out of the GH account in VS Code and then restart the application? It may just have a stale token. The username comes right from GH.

**Comment by leanneurb** [comment]
This has worked thank you. Had to also use the `/clear` command!
