### ISSUE TITLE
Newline chars not displayed consistently when in message textbox and when the message is sent and displayed back

### ISSUE THREAD

**Issue by smapelli** [microsoft/vscode-copilot-release#1521]
- Copilot Chat Extension Version: v0.18.2

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Text with rows closed by a newline char only (no carriage return char)
2. Copy text in message textbox in copilot chat within VS Code - each row is displayed correctly honoring newlines
3. Send message and message is echoed back on screen with all rows appended one after the other (with no newlines in place) making the overall thing unreadable

**Comment by roblourens** [comment]
The request is rendered as markdown, which typically has this behavior. You can start a new paragraph with new newlines. Or maybe you want a list or a codeblock
