### ISSUE TITLE
Giving extra answers even when asked not to give them

### ISSUE THREAD

**Issue by faheemstepsharp** [microsoft/vscode-copilot-release#1522]
See these images:

![Screenshot 2024-09-04 010435](https://github.com/user-attachments/assets/7346bedc-fad6-4d23-a2c4-a019d433153d)
![Screenshot 2024-09-04 010452](https://github.com/user-attachments/assets/4009cced-0839-4d0b-9bf6-2a9723ecfba6)

**Comment by ulugbekna** [comment]
Thank you for your feedback.
