### ISSUE TITLE
Yet another Unhandled status from server:, 400, Bad Request

### ISSUE THREAD

**Issue by montanel** [microsoft/vscode-copilot-release#1523]
Inline Copilot chat has completely stopped working on Jupyter. It used to work find but now just says "Failed to make request" as soon as I evaluate any cells. If I don't evaluate any cells then I can use it fine.

![Capture](https://github.com/user-attachments/assets/d83fabdc-efe8-4358-b772-155382451ca8)
![Capture 2](https://github.com/user-attachments/assets/5f8e8397-4dbb-4c6a-8d2c-9ad9ec8d6c3e)

On top of that, the chat side window work fine, it's really only the inline quick fix that doesn't work. I've tried other fixes but nothing worked so far.

- Copilot Chat Extension Version: Copilot v1.225.0 and Chat v0.18.2
- VS Code Version: 1.92.2
- OS Version: Windows 10 2H22 19045.4780
- Logs: [copilot.log](https://github.com/user-attachments/files/16856816/copilot.log)

Thank you for your help !

**Comment by montanel** [comment]
Update: in the meantime, while publishing the issue I tried uninstalling and reinstalling both VScode and the Copilot extensions. However, now the side window never works and is stuck in the generating phase. The inline still only works when I haven't evaluated any cells.

**Comment by montanel** [comment]
Sorry, misclick

**Comment by joyceerhl** [comment]
When you say 'evaluate cell' do you mean executing the cell in the Jupyter notebook?

**Comment by montanel** [comment]
Yes. Usually it's the first cell where I import packages. Depending on what I import, the quick fix window fails. But there hasn't been any consistency in that. As in I can remove an import and it works, then add it back and it works, and then removing it and it doesn't work.

**Comment by montanel** [comment]
Hello, yes it seems to be working. I haven't tested it for very long but no issues so far.
