### ISSUE TITLE
 Extension is using an API proposal 'lmTools' that is not compatible with the current version of VS Code. Cannot activate, becase ./dist/extension not found

### ISSUE THREAD

**Issue by benlavender** [microsoft/vscode-copilot-release#1526]
- Copilot Chat Extension Version: v0.17.1

- VS Code Version:

Version: 1.93.0 (user setup)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

- OS Version:

Windows 10 Pro (10.0.19045 N/A Build 19045)

- Logs: as per title.

Steps to Reproduce:

1. Update to latest release.
2. Attempt to load extension.

**Comment by benlavender** [comment]
I am **not** running insiders as per the bug https://github.com/microsoft/vscode-copilot-release/issues/1452

**Comment by roblourens** [comment]
> Copilot Chat Extension Version: v0.17.1

This is an old version of the extension, you need to update it
