### ISSUE TITLE
Help with functionalisty or workaround

### ISSUE THREAD

**Issue by KeFur-Clone** [microsoft/vscode-copilot-release#1528]
Type: <b>Feature Request</b>

Gentlefolks I need to be able to add files from computer for copilot to analyse for me. Paperclip doesnt do it. Please advise

Extension version: 0.20.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

```[tasklist]
### Tasks
```

**Comment by mjbvz** [comment]
>  Paperclip doesnt do it

Can you explain the issue in more detail. Does attaching the file not work or is the response not what you wanted?
