### ISSUE TITLE
I can't add Codebase as a chat context

### ISSUE THREAD

**Issue by kpripper** [microsoft/vscode-copilot-release#1530]
<img width="619" alt=" 2024-09-07 о 08 21 22" src="https://github.com/user-attachments/assets/e6a436cf-7fb9-4e34-a1d9-eef91c3dd1dc">

- Copilot Chat Extension Version: v0.20.0
- VS Code Version: 1.93.0 (Universal)
- OS Version: macOS 12.5.1

**Comment by joyceerhl** [comment]
I can repro in stable but not in insiders. Not sure what changed here, cc @roblourens

**Comment by faheemstepsharp** [comment]
still having same issues??? while cursor AI can do this with no issues? Please see why cant this extension behave as intended and marketed

**Comment by faheemstepsharp** [comment]
I am already Using vscode insiders and prerelease copilot!!  Context is the biggest issue also why there is no limit shown??
