### ISSUE TITLE
stuck on generating

### ISSUE THREAD

**Issue by Tom89757** [microsoft/vscode-copilot-release#1531]
Type: <b>Bug</b>

Inline suggestion is available. When chatting with it, it stuck on Generating.... 

Extension version: 0.20.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.61GB free)|
|Process Argv|D:\\Desktop\\RefRepos\\RK3588-55inch-rotate\\SkgFileManager --crash-reporter-id 1ef9292a-b7b1-45fb-887a-ac3236260cff|
|Screen Reader|no|
|VM|29%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
ei213698:31121563

```

</details>

**Comment by Tom89757** [comment]
just like this. 
![image](https://github.com/user-attachments/assets/374e4e1b-54fa-421a-bc46-8f90f36c7ae0)

**Comment by Tom89757** [comment]
Copilot encountered the same issue on both local VSCode on two computers, but it works fine when connected to the remote server.

**Comment by lramos15** [comment]
Can you include your logs via `CMD / CTRL + SHIFT +U` -> `Github Copilot Chat`

**Comment by Tom89757** [comment]
> Can you include your logs via `CMD / CTRL + SHIFT +U` -> `Github Copilot Chat`

It outputs nothing.
![image](https://github.com/user-attachments/assets/d9037fbe-a2b2-4c19-8a7d-d369d443ec61)

**Comment by Tom89757** [comment]
> > Can you include your logs via `CMD / CTRL + SHIFT +U` -> `Github Copilot Chat`
> 
> It outputs nothing. ![image](https://private-user-images.githubusercontent.com/44827483/365853768-d9037fbe-a2b2-4c19-8a7d-d369d443ec61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5Mjk5NjEsIm5iZiI6MTcyNTkyOTY2MSwicGF0aCI6Ii80NDgyNzQ4My8zNjU4NTM3NjgtZDkwMzdmYmUtYTJiMi00YzE5LThhN2QtZDM2OWQ0NDNlYzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAwNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4Nzc5ZDFhZDY4NzFmNzdjYTgyYTRhOGY2ZDQyNmZkZTUwYTViMjAwZmU2OWY1MjU1MmJkYTBhOTA1ODdhNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J73R7-bXG_F0hvW0DipGmswVcil_gjHc53-v7VCzDRU)

![image](https://github.com/user-attachments/assets/534b45cf-c60b-436d-a555-85d8a541f120)

**Comment by Tom89757** [comment]
> Can you include your logs via `CMD / CTRL + SHIFT +U` -> `Github Copilot Chat`

It outputs nothing.
![image](https://github.com/user-attachments/assets/7e8c265a-5ef2-4051-aab0-26dd7a8da05b)
The same issue is now occurring when connecting to remote servers.
![image](https://github.com/user-attachments/assets/6dedee3a-89b3-4fa0-b945-32c163ec3330)

**Comment by Tom89757** [comment]
> > Can you include your logs via `CMD / CTRL + SHIFT +U` -> `Github Copilot Chat`
> 
> It outputs nothing. ![image](https://private-user-images.githubusercontent.com/44827483/365856400-7e8c265a-5ef2-4051-aab0-26dd7a8da05b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzI0NzAsIm5iZiI6MTcyNTkzMjE3MCwicGF0aCI6Ii80NDgyNzQ4My8zNjU4NTY0MDAtN2U4YzI2NWEtNWVmMi00MDUxLWFhYjAtMjZkZDdhOGRhMDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAxMzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZmY4NWY4ZTc1OTliN2Q3YTkzZjM4YWVjNTAxNTNhOWM4YjNjNzMyZDFhN2Q2Y2RiY2MxMjg5MTliYjAxMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-gt5GfJsVUe0k4S0P7u4byctZQuWHT4-kWm_N3tOYcg) The same issue is now occurring when connecting to remote servers. ![image](https://private-user-images.githubusercontent.com/44827483/365856594-6dedee3a-89b3-4fa0-b945-32c163ec3330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MzI0NzAsIm5iZiI6MTcyNTkzMjE3MCwicGF0aCI6Ii80NDgyNzQ4My8zNjU4NTY1OTQtNmRlZGVlM2EtODliMy00ZmEwLWI5NDUtMzJjMTYzZWMzMzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDAxMzYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwYmUwZDlhNjAxYjQ3YjNiYWQ4MGZlYzk0NTNmYzZlN2UyYjRiNzczYmU5OGFkN2JjNDRmYTZjMTI4YjNhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zjjuM1c8_mPW3tUSFl9s6PiBgI8QVNmpygvlT2cHaNI)

Now it works fine on the server, but it takes a long time to respond on the local computer and still gets stuck at 'generating'
![image](https://github.com/user-attachments/assets/1c3ab741-236b-40bc-8367-6f01ddc96758)
![image](https://github.com/user-attachments/assets/35a87836-b17a-443d-8f10-fa78f5936065)

**Comment by lramos15** [comment]
And I assume locally you're using 0.20.0 just like you are on the server?

Do you have any interesting network or proxy configuration?  Can you try `F1 -> Chat Diagnostics` as well

**Comment by Tom89757** [comment]
> And I assume locally you're using 0.20.0 just like you are on the server?
> 
> Do you have any interesting network or proxy configuration? Can you try `F1 -> Chat Diagnostics` as well

On one of my local computers, no proxy is configured, and it shows as follows:
<img width="1873" alt="Snipaste_2024-09-11_09-29-44" src="https://github.com/user-attachments/assets/1c3dcbc8-5f80-4b88-93ac-d9f7cc34e667">
On the server, no proxy is configured either, and it shows as follows:
<img width="1873" alt="Snipaste_2024-09-11_09-28-47" src="https://github.com/user-attachments/assets/525ebcb1-9687-4d8f-9da6-4cf8b0013134">
On my other local computer, I usually use a proxy. I will post the results as soon as possible.

**Comment by Tom89757** [comment]
On a computer where I use a proxy(I have Clash for Windows enabled, but I haven't configured http_proxy in VSCode.), it displays as follows:
![image](https://github.com/user-attachments/assets/f0a502e6-d2aa-487a-9ebf-2bb7cd93a829)

**Comment by Tom89757** [comment]
On the local computer using a proxy: 
![Snipaste_2024-09-12_12-22-57](https://github.com/user-attachments/assets/104d6a2d-a9f8-4d0a-8a3d-8932f7de6fe8)

**Comment by chrmarti** [comment]
@Tom89757 Could you start VS Code with `--log-net-log=netlog.json`, retry asking Copilot (locally) and then share the created netlog.json here?

**Comment by Tom89757** [comment]
The output from the local computer using a proxy is as follows:
[netlog.json](https://github.com/user-attachments/files/16994924/netlog.json)

**Comment by chrmarti** [comment]
It picks up the proxy configuration from the OS. Could you also append a netlog from the machine showing the problem without proxy, so we are sure it is not the proxy causing any issues?

**Comment by Tom89757** [comment]
> It picks up the proxy configuration from the OS. Could you also append a netlog from the machine showing the problem without proxy, so we are sure it is not the proxy causing any issues?

The output without the proxy is as follows:
[netlog.json](https://github.com/user-attachments/files/17011838/netlog.json)

**Comment by chrmarti** [comment]
Not sure what might be the issue here. The first `SSL_CONNECT_JOB` to `api.githubcopilot.com` fails, but the second one succeeds. Maybe that is an indication for an underlying problem.

On the machine without proxy, could you try adding the following to your user settings (`F1` > `Preferences: Open User Settings (JSON)`:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": false,
    "debug.useNodeFetcher": true
  }
```

Then reload the window to make the updated settings apply and the retry the Chat.

**Comment by Tom89757** [comment]
> Not sure what might be the issue here. The first `SSL_CONNECT_JOB` to `api.githubcopilot.com` fails, but the second one succeeds. Maybe that is an indication for an underlying problem.
> 
> On the machine without proxy, could you try adding the following to your user settings (`F1` > `Preferences: Open User Settings (JSON)`:
> 
> ```json
>   "github.copilot.advanced": {
>     "debug.useElectronFetcher": false,
>     "debug.useNodeFetcher": true
>   }
> ```
> 
> Then reload the window to make the updated settings apply and the retry the Chat.

Thanks for your reply. It works!!!

**Comment by chrmarti** [comment]
Could you check if the following variation also works:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": false,
    "debug.useNodeFetcher": false
  }
```

**Comment by deepak1556** [comment]
Just looked into the logs, couple of data points extracted from them.

*In the proxy server case:*

All HTTP2 sessions irrespective of the remote host end up getting closed from the proxy server `127.0.0.1:7890` after 60s of starting the session. I wonder if the proxy has some timeout configuration or it cannot handle h2 sessions well.

<img width="653" alt="Screenshot 2024-09-18 at 16 29 22" src="https://github.com/user-attachments/assets/a66c0de4-c4f6-4e74-9d26-ac1a2801b58c">

*In the direct connection case:*

SSL_CONNECT_JOB failure was due to SSL handshake failure (event entry 264) on the first request to `https://api.githubcopilot.com/agents`, I wonder if it has to do with the TCP port used for connection `58021`.

@Tom89757 couple of followups, with the following settings

```
"github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }
```

1) On the machine with proxy server, can you restart the application with `--disable-http2` and see if connection works. If it fails please provide the netlog for this case.
2) On the machine without proxy server, can you capture another fresh netlog.

**Comment by Tom89757** [comment]
> Could you check if the following variation also works:
> 
> ```json
>   "github.copilot.advanced": {
>     "debug.useElectronFetcher": false,
>     "debug.useNodeFetcher": false
>   }
> ```

It also works.

**Comment by Tom89757** [comment]
> Just looked into the logs, couple of data points extracted from them.
> 
> **In the proxy server case:**
> 
> All HTTP2 sessions irrespective of the remote host end up getting closed from the proxy server `127.0.0.1:7890` after 60s of starting the session. I wonder if the proxy has some timeout configuration or it cannot handle h2 sessions well.
> 
> <img alt="Screenshot 2024-09-18 at 16 29 22" width="653" src="https://private-user-images.githubusercontent.com/964386/368464828-a66c0de4-c4f6-4e74-9d26-ac1a2801b58c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MDgyNzAsIm5iZiI6MTcyNjcwNzk3MCwicGF0aCI6Ii85NjQzODYvMzY4NDY0ODI4LWE2NmMwZGU0LWM0ZjYtNGU3NC05ZDI2LWFjMWEyODAxYjU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMTA2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGQ3NjZjNDA4NTc3NGM2MmZjOTJkNjYyNjA0NDc5YjFkNjI1M2UxNTYyNTc1NWNlNDJlMTE0MThiMDBhNzUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E2qAsBSM643ydINqYIXd4ZwUVnLCzV9bqwKPGLt6f7w">
> **In the direct connection case:**
> 
> SSL_CONNECT_JOB failure was due to SSL handshake failure (event entry 264) on the first request to `https://api.githubcopilot.com/agents`, I wonder if it has to do with the TCP port used for connection `58021`.
> 
> @Tom89757 couple of followups, with the following settings
> 
> ```
> "github.copilot.advanced": {
>     "debug.useElectronFetcher": true,
>     "debug.useNodeFetcher": false
>   }
> ```
> 
> 1. On the machine with proxy server, can you restart the application with `--disable-http2` and see if connection works. If it fails please provide the netlog for this case.
> 2. On the machine without proxy server, can you capture another fresh netlog with the issue reproing.

On the machine without proxy server, the problem has occurred again. Here is the log:
[netlog.json](https://github.com/user-attachments/files/17052045/netlog.json)
I will try it on another computer as soon as possible and provide feedback

**Comment by Tom89757** [comment]
> Just looked into the logs, couple of data points extracted from them.
> 
> **In the proxy server case:**
> 
> All HTTP2 sessions irrespective of the remote host end up getting closed from the proxy server `127.0.0.1:7890` after 60s of starting the session. I wonder if the proxy has some timeout configuration or it cannot handle h2 sessions well.
> 
> <img alt="Screenshot 2024-09-18 at 16 29 22" width="653" src="https://private-user-images.githubusercontent.com/964386/368464828-a66c0de4-c4f6-4e74-9d26-ac1a2801b58c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTk4MjksIm5iZiI6MTcyNjcxOTUyOSwicGF0aCI6Ii85NjQzODYvMzY4NDY0ODI4LWE2NmMwZGU0LWM0ZjYtNGU3NC05ZDI2LWFjMWEyODAxYjU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNDE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWJhZjMxYThmMGJkMDg5MTM3ZWJmYzdlNGFkODUyMzNjOWI1YmYyZTEwMzk0YmU3OTgyN2UzZmRiNWI1Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WQTjnU7JT57BSk6TbuXn-YICiVwmsTCnmLlqNEf8Hu0">
> **In the direct connection case:**
> 
> SSL_CONNECT_JOB failure was due to SSL handshake failure (event entry 264) on the first request to `https://api.githubcopilot.com/agents`, I wonder if it has to do with the TCP port used for connection `58021`.
> 
> @Tom89757 couple of followups, with the following settings
> 
> ```
> "github.copilot.advanced": {
>     "debug.useElectronFetcher": true,
>     "debug.useNodeFetcher": false
>   }
> ```
> 
> 1. On the machine with proxy server, can you restart the application with `--disable-http2` and see if connection works. If it fails please provide the netlog for this case.
> 2. On the machine without proxy server, can you capture another fresh netlog with the issue reproing.

On the machine with proxy server, it fails. Here is the log:
[netlog.json](https://github.com/user-attachments/files/17053557/netlog.json)

**Comment by Tom89757** [comment]
> > Just looked into the logs, couple of data points extracted from them.
> > **In the proxy server case:**
> > All HTTP2 sessions irrespective of the remote host end up getting closed from the proxy server `127.0.0.1:7890` after 60s of starting the session. I wonder if the proxy has some timeout configuration or it cannot handle h2 sessions well.
> > <img alt="Screenshot 2024-09-18 at 16 29 22" width="653" src="https://private-user-images.githubusercontent.com/964386/368464828-a66c0de4-c4f6-4e74-9d26-ac1a2801b58c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTk4MjksIm5iZiI6MTcyNjcxOTUyOSwicGF0aCI6Ii85NjQzODYvMzY4NDY0ODI4LWE2NmMwZGU0LWM0ZjYtNGU3NC05ZDI2LWFjMWEyODAxYjU4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwNDE4NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWJhZjMxYThmMGJkMDg5MTM3ZWJmYzdlNGFkODUyMzNjOWI1YmYyZTEwMzk0YmU3OTgyN2UzZmRiNWI1Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WQTjnU7JT57BSk6TbuXn-YICiVwmsTCnmLlqNEf8Hu0">
> > **In the direct connection case:**
> > SSL_CONNECT_JOB failure was due to SSL handshake failure (event entry 264) on the first request to `https://api.githubcopilot.com/agents`, I wonder if it has to do with the TCP port used for connection `58021`.
> > @Tom89757 couple of followups, with the following settings
> > ```
> > "github.copilot.advanced": {
> >     "debug.useElectronFetcher": true,
> >     "debug.useNodeFetcher": false
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. On the machine with proxy server, can you restart the application with `--disable-http2` and see if connection works. If it fails please provide the netlog for this case.
> > 2. On the machine without proxy server, can you capture another fresh netlog with the issue reproing.
> 
> On the machine with proxy server, it fails. Here is the log: [netlog.json](https://github.com/user-attachments/files/17053557/netlog.json)

The Screenshot may be helpful:
![image](https://github.com/user-attachments/assets/6d843aa3-a3d2-4211-8c9f-9a64b4304c61)

**Comment by deepak1556** [comment]
In both the new logs, 101 (ERR_CONNECTION_RESET)  is only seen for telemetry related requests. All requests from copilot seem to complete fine. 

@Tom89757 can you attach the trace log from copilot chat extension when running with `--disable-http2`. Also I will delete your last two logs since the headers contain github tokens.

**Comment by Tom89757** [comment]
> In both the new logs, 101 (ERR_CONNECTION_RESET) is only seen for telemetry related requests. All requests from copilot seem to complete fine.[ 重试    错误原因 ](javascript:void(0))
> 
> @Tom89757 can you attach the trace log from copilot chat extension when running with `--disable-http2`. Also I will delete your last two logs since requests succeeded and the headers contain github tokens.

Do you mean with previous settings you give? Here is the log:
![image](https://github.com/user-attachments/assets/3acdc132-a96e-453b-896e-b5c065b2c79b)

**Comment by Tom89757** [comment]
> > > Could you check if the following variation also works:
> > > "github.copilot.advanced": {
> > > "debug.useElectronFetcher": false,
> > > "debug.useNodeFetcher": false
> > > }
> > 
> > 
> > It also works.
> 
> @Tom89757 Just to make sure the setting was properly applied: Did you reload the VS Code window after changing the setting before you checked if it works? (Reloading the window is required to make the settings change effective.)

I reload the window and it also works.
