### ISSUE TITLE
Can support reading the context of the command line, giving possible commands to be executed

### ISSUE THREAD

**Issue by Aoyia** [microsoft/vscode-copilot-release#1536]
As the title suggests, I would like the system to suggest command lines based on my command history when I execute commands. For example, I often execute the following commands:

```
git add .
git commit -m 'fix: loading fix'
git push origin my-branch-name
```

When the AI detects that I have entered `git add .`, it should understand that I am highly likely to follow up with `git commit -m`, and then proceed with `git push`. It should also be able to provide suggestions that better match the user's behavior based on the execution history. The data involved is not extensive, but it would make executing commands much simpler and smarter.

**Comment by Tyriar** [comment]
We already have a system in place for this called quick fixes, of which copilot contributes some but only when the command fails. Currently we have a few non-Copilot git ones:

- Provide similar commands when it fails https://github.com/microsoft/vscode/blob/b2c21ec7558bb7d91d08f7dac097550f51a00352/src/vs/workbench/contrib/terminalContrib/quickFix/browser/terminalQuickFixBuiltinActions.ts#L27-L62
- Pull again when fast forward is available https://github.com/microsoft/vscode/blob/b2c21ec7558bb7d91d08f7dac097550f51a00352/src/vs/workbench/contrib/terminalContrib/quickFix/browser/terminalQuickFixBuiltinActions.ts#L27-L62
- Convert `-` to `--` for flag https://github.com/microsoft/vscode/blob/b2c21ec7558bb7d91d08f7dac097550f51a00352/src/vs/workbench/contrib/terminalContrib/quickFix/browser/terminalQuickFixBuiltinActions.ts#L88-L114
- Set upstream for new branch https://github.com/microsoft/vscode/blob/b2c21ec7558bb7d91d08f7dac097550f51a00352/src/vs/workbench/contrib/terminalContrib/quickFix/browser/terminalQuickFixBuiltinActions.ts#L147-L211
- Create PR after push to new GH branch https://github.com/microsoft/vscode/blob/b2c21ec7558bb7d91d08f7dac097550f51a00352/src/vs/workbench/contrib/terminalContrib/quickFix/browser/terminalQuickFixBuiltinActions.ts#L213-L256

We could, but currently we do not add partial commands like `git commit -m` and that case also isn't very likely what the user will do. Often the user will simply run `git commit` for example. Similarly with git push, the user may be on a different branch already.

There's no need to bring AI into this imo. You are able to create an extension to accomplish exactly what you're after, but imo it's not high enough confidence for us to bring it into the core built-in quick fixes.

You might also be interested in the similar feature auto replies which is another method to automate away user input https://github.com/microsoft/vscode-docs/blob/vnext/docs/terminal/advanced.md#auto-replies
