### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by ncds42** [microsoft/vscode-copilot-release#1545]
Type: <b>Bug</b>

Infinite looped on rider directories

Extension version: 0.20.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (2.61GB free)|
|Process Argv|--crash-reporter-id 3c9cc96e-bb1d-47ee-a561-01a04e2dc938|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31134654
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-c:31125598
defaultse:31133495
fje88620:31121564

```

</details>

Printed: 

.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml
.idea/.idea_modules/
.idea/.idea_modules.xml

Continuously until stopped.

**Comment by bhavyaus** [comment]
Dupe: https://github.com/microsoft/vscode-copilot-release/issues/1516
