### ISSUE TITLE
Significantly worse performance than GPT 4

### ISSUE THREAD

**Issue by scode-cmd** [microsoft/vscode-copilot-release#155]
Hi!

Since this was advertised as powered by "GPT 4", I find it very frustrating that the chat feature is powered by GPT 3 and not GPT 4.

GPT 3 performance makes it basically useless, the reasoning capacity of GPT 4 is significantly more advance. GPT 4 gets the job done in almost all situations and is able to perform the most advance of tasks, for example refactoring complex code structures or explaining a particularly difficult to read snippet of code.

GPT 3 used by Chat fails almost everytime, introducing issues in the generated code, hallucinating, and having very poor reasoning skills.

GPT 3 ends up wasting your time introducing issues in your code and incorrectly understanding the task.

The chat feature is not worthwhile until it's actually powered by GPT 4, and there is clear communication that it's the model being used for inference.
```[tasklist]
### Tasks
- [ ] Provide clear communication in the Chat window on which model is being used
- [ ] Upgrade chat to use GPT 4
```

**Comment by scode-cmd** [comment]
Have to follow up on this: new comers whose first experience with "AI powered code assistant" is chat will get bad impression, kinda like when people who tried cardboard VR got a bad taste since it wasn't actually representative of the proper VR experience available with high end headsets. I would have to say it's sadly the same here for GPT 3.5 vs GPT 4.

**Comment by Rafcin** [comment]
I've been doing some testing. I would have to agree, OpenAI GPT-4 8k seems to perform much better than copilot in most situations. Most of the time I can't get it to understand the task at hand on small or large sections of code.

**Comment by outgaze** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/44008063/eb1aa763-9500-4191-ae0a-2521aefc50a7)

**Comment by andraz** [comment]
I agree with the notion that we should question the necessity of paying monthly for a toy when we have access to GPT4 at no cost elsewhere.

**Comment by CannibalKush** [comment]
+1 for this in general, but also I'd add that it would be great to be able to choose what model you'd like to use, so that we can switch providers and potentially even bring-your-own-model somehow.

**Comment by andraz** [comment]
I recently discovered that we can get a high quality response by prompting Bing Chat "_Simplify this code into javascript code, remove all not needed parts, add inline comments, reply in codeblock: <raw ts source>_".  It removes unnecessary clutter and enhances unannotated code with appropriate explanations.

It would be highly beneficial if Microsoft could internally explore how to internally direct this particular service provider to Copilot, as it would be an ideal match.

**Comment by andraz** [comment]
I recently discovered that we can get a high quality GPT4 response by prompting Bing Chat "_Simplify this code into javascript code, remove all not needed parts, add inline comments, reply in codeblock: <raw ts source>_".  It removes unnecessary clutter and enhances unannotated code with appropriate explanations.

It would be highly beneficial if Microsoft could internally explore how to internally direct this particular service provider to Copilot, as it would be an ideal match.

**Comment by scode-cmd** [comment]
It has been proven that Bing Chat does not actually use GPT 4 for most queries, only for some queries deemed complex. And this was quoted too by some Microsoft exec a while ago.

The only way guarantee GPT 4 is through OpenAI's API or paying for the ChatGPT plus subscription and then choosing "GPT 4" as the model. Only then you guarantee responses are always generated by GPT 4 and then you will notice the quality of responses is significantly better than anything else on the market, including Copilot Chat and Bing Chat.

**Comment by andraz** [comment]
The concept of only using the strongest model when necessary applies seamlessly to Copilot as well, indicating that we don't require the most powerful model for every task. Inheriting web searching feature from Bing Chat would make it even better.

**Comment by digitarald** [comment]
Duplicate of #6

**Comment by julian-shalaby** [comment]
[Here's](https://plugins.jetbrains.com/plugin/22895-chatwindow) an alternative which lets you use GPT4 with your own API key

**Comment by digitarald** [comment]
Update from #6: All responses in panel/quick chat are served by GPT-4 since Copilot Chat 0.10 (part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_github-copilot)). 3.5 is still used for other messages.

Please give it a try and file new issues for any follow-up feedback!
