### ISSUE TITLE
Copilot asks me to update

### ISSUE THREAD

**Issue by amirhadibi** [microsoft/vscode-copilot-release#1550]
- Copilot Chat Extension Version: 29.2.420906002
- VS Code Version: 
- OS Version: ios 17.6.1
- Logs:

Steps to Reproduce:

1. open the app
2. 
![copilot-update](https://github.com/user-attachments/assets/ec8b2026-e4b2-43da-a143-d27678fb1bad)

when i open copilot on my iPhone, it shows the attached screen. when i tap on Update button, it takes me to App Store, which the only option there is Open button. when I tap on Open, I go back to Copilot and I cannot update or open Copilot app on my iPhone.

**Comment by andreamah** [comment]
This is not the same copilot product. I believe that, for Windows Copilot, you can discuss this on the public forum for Windows https://techcommunity.microsoft.com/t5/windows/ct-p/Windows
