### ISSUE TITLE
Copilot does not work

### ISSUE THREAD

**Issue by KenoAlbrecht** [microsoft/vscode-copilot-release#1556]
Type: <b>Bug</b>

Ask a question regarding a function or method (using the "Chat" button which is located in the side bar) that is defined somewhere in a folder in a project..

The Github Copilot is not able to answer these types of questions at least in my case. Do I have to wait for it to finish some process or am I doing something wrong?

Extension version: 0.20.0
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.8.0-40-generic
Connection to 'ssh-remote+work2' could not be established
Remote OS version: Linux x64 6.8.0-40-generic
Remote OS version: Linux x64 6.8.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: work2|
|OS|Linux x64 6.8.0-40-generic|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor (16 x 4782)|
|Memory (System)|61.77GB (28.46GB free)|
|VM|0%|

Connection to 'ssh-remote+work2' could not be established

|Item|Value|
|---|---|
|Remote|SSH: work2|
|OS|Linux x64 6.8.0-40-generic|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor (16 x 4783)|
|Memory (System)|61.77GB (28.46GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: work2|
|OS|Linux x64 6.8.0-40-generic|
|CPUs|AMD Ryzen 7 7800X3D 8-Core Processor (16 x 4785)|
|Memory (System)|61.77GB (28.46GB free)|
|VM|0%|
</details>

**Comment by KenoAlbrecht** [comment]
Update: My issue still exists. Almost nothing I tried so far really worked. The only thing that was helpful for me was the answer to the question "How do I set the working dir in Python". But nothing related to my (selected and not selected) code was helpful. Using Microsoft Copilot in a browser does work much better and is not much more work. This situation is very frustrating as this could be such a great and useful tool!

Why does this cost money? I don't think it is ready enough to demand money from anyone using it. Or am I doing something totally wrong? An answer would be very appreciated! If you need more information to help me fixing this issue please tell me!

**Comment by roblourens** [comment]
You can open the definition of that function in an editor, and then copilot will see it. Or you can select it and add it as context manually. Or you can use `@workspace` which is able to search your workspace.
