### ISSUE TITLE
Always Failed to log in in Sidebar

### ISSUE THREAD

**Issue by ProudBenzene** [microsoft/vscode-copilot-release#1566]
- Copilot Chat Extension Version: v0.21.2024090602 (pre-release)
- VS Code Version: 1.93.1
- OS Version: macOS 14.6.1
- Logs:

Steps to Reproduce:

1. Open VSCode and click Copilot Chat Extension icon on the sidebar
2. It always says that you need to be logged into GitHub, but you can see from the bottom left corner of the screenshot that you're already logged in

Tried reinstalling the extension, no change. Could anyone help me?

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/9929c689-6b31-4e30-b9bb-ecca4ed62096">

**Comment by TylerLeonhardt** [comment]
@ProudBenzene can you try with the latest VS Code Insiders and also latest pre-release of Copilot Chat? We have done some work here that hopefully cleaned this up.

**Comment by TylerLeonhardt** [comment]
Let's continue this in https://github.com/microsoft/vscode-copilot-release/issues/1644 since it's the same issue.
