### ISSUE TITLE
Add OpenAI o1 to copilot

### ISSUE THREAD

**Issue by lyc280705** [microsoft/vscode-copilot-release#1567]
OpenAI o1 uses chain of thought. It has large improvement in coding. I can't wait to see what will happen if you can bring this model to copilot.

**Comment by brunofelixns** [comment]
Is there any news on when it will be implemented?

**Comment by lramos15** [comment]
No updates yet, but it's something actively being investigated. 

The O1 API has some limitations compared to other models such as:
- No system message
- No tool calling
- No support for parameters such as temperature
- No streaming of responses

These limitations of course present unique implementation challenges that we must work through.

**Comment by brunofelixns** [comment]
We already have news about the implementation and a waiting list: [Try out OpenAI o1 in GitHub Copilot and Models](https://github.blog/news-insights/product-news/try-out-openai-o1-in-github-copilot-and-models/?utm_source=insider&utm_medium=email&utm_campaign=2024q1-em-GitHub-Insider-Sept-19)

**Comment by lyc280705** [comment]
Is o1 available to everyone now?
![Image](https://github.com/user-attachments/assets/30f82743-93a2-4de1-9b0d-cb81372327dc)
