### ISSUE TITLE
Copilot chat could not give any answer after inputing  any command in copilot chat extension, always show me "it is generating"

### ISSUE THREAD

**Issue by liyuerich** [microsoft/vscode-copilot-release#1569]
- Copilot Chat Extension Version: GitHub Copilot Chat
v0.20.1
- VS Code Version: 1.93.1
- OS Version: macos Sonoma 14.5 (23F79)
- Logs:

Steps to Reproduce:

1. click the Copilot chat button in vscode ,  it works fine before. 
2. from yesterday ,  it could not give any answer after inputing  any command in copilot chat extension
3. always show me "it is generating"

please help, thanks.

**Comment by roblourens** [comment]
Can you check the logs in the Copilot Chat output channel and share them? A screenshot might help too.

**Comment by liyuerich** [comment]
sorry for late reply, how to reopen it?
