### ISSUE TITLE
GitHub Copilot Chat VS Code Extension: Repeated Sign-In Prompts

### ISSUE THREAD

**Issue by Santosh-Baliarsingh** [microsoft/vscode-copilot-release#1573]
### Issue Description

Hello, I am experiencing an issue with the GitHub Copilot Chat VS Code extension. After signing in to GitHub, the extension works fine. However, after a few hours, it prompts me to sign in to GitHub again. I have to reload VS Code to make it work again.

### ScreenShot
![Screenshot 2024-09-15 221146](https://github.com/user-attachments/assets/b8de61b0-c01b-4081-8caf-36f79a59c6e9)

### Steps to Reproduce

1. Install the GitHub Copilot Chat VS Code extension.
2. Sign in to GitHub when prompted.
3. Use the extension (it works fine at this point).
4. Wait for a few hours.
5. The extension prompts to sign in to GitHub again.
6. Reload VS Code to make it work again.

### Expected Behavior

The extension should retain the sign-in session and not prompt for GitHub sign-in after a few hours.

### Actual Behavior

After a few hours, the extension prompts for GitHub sign-in again. Reloading VS Code makes it work again.

### Environment

- **VS Code Version**: v1.93.1
- **GitHub Copilot Version**: v1.229.0
- **GitHub Copilot Chat Version**: v0.20.1
- **Operating System**: windows 11

**Comment by TylerLeonhardt** [comment]
We've changed this code quite a bit in the pre-release... Can you give it a try?
* Grab the Insiders build of VS Code: http://code.visualstudio.com/insiders/
* Grab the pre-release version of GitHub Copilot Chat

Then try logging in again.

**Comment by Santosh-Baliarsingh** [comment]
Ok sure I'll try.

**Comment by TylerLeonhardt** [comment]
Let's continue this in https://github.com/microsoft/vscode-copilot-release/issues/1644 since it's the same issue.
