### ISSUE TITLE
LOOPING, WHEN GETTING ASKED AGAIN EDITS COMMENT NOT THE CODE

### ISSUE THREAD

**Issue by ermigebriel** [microsoft/vscode-copilot-release#1578]
This is a very frustruating issue. I have no idea how to ask this but copilot is looping forever and being disrespectful by simpy editing a comment, for example

![image](https://github.com/user-attachments/assets/cab0f672-3248-4a9a-a4e8-f3ab35e4f79c)

So when i reported some issue it edited that line

So i told copilot
You send the same code
and response was 

Plan
Setup the Test Environment:

Mock the psycopg2.connect to avoid actual database connections.
Mock the cursor and its methods to simulate database operations.
Test Cases:

Test ..... with no expired users.
Test .......with some expired users.
Ensure that the [users_data]...... dictionary is updated correctly for expired users.

Then the change was

![image](https://github.com/user-attachments/assets/e4b2b4ba-29e0-4fbd-9990-7a9d28202eb1)

It will loop forever like this and at the end it will send a very unrelated code that is unrelated to my question

![image](https://github.com/user-attachments/assets/7a4d9604-e584-4836-b28e-e1e6b4f95eac)

How is this even possible? The problem can be solved in simple way but why is it looping answering the same question and editing a comment instead of analyzing the code? 

is it looping because of some usage limit or what? Please explain this to me so i can simply cancel my subscription and move on to another service cause this is so disrespectful and it makes copilot untrustworthy

**Comment by ermigebriel** [comment]
This has been happening the whole day, At some point i even explained the answer can be resolved this way and yet copilot answers the same useless answer without changing a single line of code almost 15+ times, And the moment it starts looping it generates very unrelatable code in auto complete

**Comment by jrieken** [comment]
@ermigebriel Sorry, but I am having to understand how you got into this. Can you describe the steps that lead you here? Is this editing and get ghost text suggestions or are these changes from chat (panel or inline)?
