### ISSUE TITLE
Codeblock scrollbar position stays locked to bottom of chat window

### ISSUE THREAD

**Issue by JohnnyFactor** [microsoft/vscode-copilot-release#1580]
The horizontal scrollbar position in the chat window stays locked to the bottom of the chat window. When scrolling the window up, the scrollbar disappears off the page and is no longer accessible when reviewing long chats.

- Copilot Chat Extension Version: 0.20.1
- VS Code Version: 1.93.1
- OS Version: Windows 10 Pro, build 19045.3930

**Comment by roblourens** [comment]
Which horizontal scrollbar, can you share a screenshot?

**Comment by JohnnyFactor** [comment]
From the chat window on the left hand side. The code response was several hundred lines. Scrolling up results in the horizontal bar "sticking" to the bottom of the window rather than staying on screen:

![vscode](https://github.com/user-attachments/assets/64ad8b89-e28d-4e4e-8eef-223eefd7f93b)

**Comment by roblourens** [comment]
Oh, on a codeblock editor, I see

**Comment by roblourens** [comment]
We might do something anyway to make tall codeblocks easier to handle
