### ISSUE TITLE
Highlighted

### ISSUE THREAD

**Issue by cairnsturnbull** [microsoft/vscode-copilot-release#1585]
Type: <b>Bug</b>

Prompt to explain highlighted line results in a stall

Extension version: 0.20.1
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux x64 4.18.0-477.27.1.el8_8.x86_64
Connection to 'SSH: bach' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|18.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id bc24b868-f4de-4dfe-88f3-84da394ff8d4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: prospero|
|OS|Linux x64 4.18.0-477.27.1.el8_8.x86_64|
|CPUs|AMD EPYC 7502P 32-Core Processor (32 x 0)|
|Memory (System)|251.12GB (240.20GB free)|
|VM|0%|

Connection to 'SSH: bach' could not be established  Canceled
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
fje88620:31121564
iacca2:31138163

```

</details>

**Comment by joyceerhl** [comment]
Please give more details of how we can repro this, and a screenshot or screen recording would help a lot, thanks
