### ISSUE TITLE
Make copy more accessible for large code blocks

### ISSUE THREAD

**Issue by CH-PatrickWalmsley** [microsoft/vscode-copilot-release#1588]
@daviddossett / UX

This is a usability enhancement suggestion.

When iterating on existing files I will often ask copilot to "retain the existing file structure" so it outputs all of the code with the changes I need.  While this is slightly slower it beats pulling bit by bit out of it's response or manually making changes.  I then review the changes with a diff.

This takes a little bit to generate.  I can keep my window position by scrolling away from the bottom.  But trying to copy too early gives me some junk (to debug ?).  If I scroll to the bottom or let copilot scroll as it outputs copying becomes difficult.  I try and highlight to copy but the screen scrolls to fast and I select stuff I don't need.  Or I scroll back to the start of the block to copy the output - better but still inconvenient.  There should be an easier way to copy a code block.  

There are a handful of potential solutions.  Perhaps double or triple click to copy.  Alternatively, you could make the actions more accessible.  Ie. actions available from the bottom of the block, available from both the top and bottom of the block, or available from the bottom of the block only when the top of the block is off screen.

Existing actions location at the top of the code block:
<img width="710" alt="to" src="https://github.com/user-attachments/assets/1359bbeb-19d7-4f8b-9a4d-5b982851b1ab">

Potentially more accessible location at the bottom of the code block:
<img width="709" alt="from" src="https://github.com/user-attachments/assets/ee3332d3-dfa9-43a2-9233-f6a3f3c475fa">

BTW I was not able to send this enhancement request using the "Send feedback" button in the chat.  Perhaps related to my large request / response.  An error appears at the bottom right of the screen which reads "Converting circular structure to JSON --> starting at object with constructor 'K' | property 'c' -> object with constructor 'N' --- property 'd' closes the circle"

**Comment by daviddossett** [comment]
Thanks for the feedback! Some great points here. Maybe we should _also_ show the toolbar at the bottom of the code block on hover/focus if it exceeds some minimum height.
