### ISSUE TITLE
Width changes on chat editor

### ISSUE THREAD

**Issue by kinglau66** [microsoft/vscode-copilot-release#159]
Current Feature:
1. Open In Editor
2. Show Chat in Editor
3. Chat Width Constrained to Max Sidebar Width: The chat interface is currently limited to the maximum width 

## Proposed width change feature in editor mode
allow width adjustment or full width in editor mode.
Current Feature:
1. Open In Editor
2. Show chat in editor 
3. chat in editor shows full width or allow width changes

![image](https://github.com/microsoft/vscode-copilot-release/assets/15945904/c667dfe3-35c5-4e5a-bb6d-b66223d45dd5)

**Comment by roblourens** [comment]
Most people prefer reading text in columns, not a long line stretching across the screen, so most websites wrap text in a column. Comments on your preference are welcome here though:

https://github.com/microsoft/vscode-copilot-release/issues/60
