### ISSUE TITLE
Sorry, your request was rate-limited. Please wait and try sending again later.

### ISSUE THREAD

**Issue by namangaurmbd99** [microsoft/vscode-copilot-release#1596]
Getting this error while I am using the chat.
GitHub Copilot
Sorry, your request was rate-limited. Please wait and try sending again later.

**Comment by lramos15** [comment]
We deployed a server side fix, let me know if you're still seeing this

**Comment by namangaurmbd99** [comment]
No, now it is fixed and I am not seeing this issue now. Thanks for resolving.

**Comment by margivyas99** [comment]
Receiving the same error: Sorry, your request was rate-limited. Please wait and try sending again later.

**Comment by lramos15** [comment]
@margivyas99 Our telemetry indicates that you have actually exceeded your rate limit and that there is no bug here. Can you describe a bit about how you're using Copilot Chat so I can understand why you have such high usage.

**Comment by bradke73** [comment]
Still seeing this issue on my end. Using VSC with extension.

**Comment by apersonismelolz** [comment]
I am having this issue and am a business customer
