### ISSUE TITLE
Where to find the new model selector

### ISSUE THREAD

**Issue by niyue** [microsoft/vscode-copilot-release#1604]
- Copilot Chat Extension Version: v0.21.2024090602 (pre-release)/v0.20.3
- VS Code Version: 1.93.1
- OS Version: macOS 14.0

I read the blog post about the new openai o1 model in github copilot chat (https://github.blog/news-insights/product-news/try-out-openai-o1-in-github-copilot-and-models/), and I applied for the preview access and got an email saying I've been granted access to the preview.

But I tried both the latest release and pre-release version of Copilot Chat Extension in VS Code (from the blog and the email, it is not clear to me whether I need to use the pre-release version of Copilot Chat or not to use the previewed model feature), and I am not able to find the new model selector. How can I enable it? Thanks.

About the access granted email I received:
* the `Discussions` link in the access grant email links to https://gh.io/model-picker-discussion, which redirects to `example.com` currently (initially I would like to navigate to the discussions website to see if there are other people running into this issue)
* the email told me `you'll be able to experiment with the o1 models via [GitHub Models](https://docs.github.com/en/github-models/prototyping-with-ai-models)`, however, when I navigate to github models, I was prompted to sign up another wait list, which is unexpected

**Comment by fisforfaheem** [comment]
+1 no  option availble, instead this is what i am getting:
![image](https://github.com/user-attachments/assets/fc671b18-ad62-4f6e-bee2-9cd661baa77f)

**Comment by lramos15** [comment]
You will need VS Code insiders + the latest pre-release to test. At the time of writing this it would be Copilot chat pre-release `v0.21.2024092002` 

@fisforfaheem It will be a picker shown in the chat UI. there is no need to say "use xyz"

![Image](https://github.com/user-attachments/assets/b9497b7a-665c-4d71-9850-594f748ed0bd)

I will pass the feedback along so that we can improve the onboarding instructions here.

**Comment by fisforfaheem** [comment]
Thanks please also make sure to ONLY USE chatgpt 4o + models not older

**Comment by lramos15** [comment]
@fisforfaheem I've answered in your other issue about your concerns involving us using an older model and I can assure you that we are not. As you can see in the picker there isn't even an option for an older model than 4o.

**Comment by fisforfaheem** [comment]
I just updated to latest vs insider and also pre release version of extension, still no picker available

**Comment by lramos15** [comment]
@fisforfaheem Have you been let off the waitlist? It's a waitlisted feature that only select individuals are receiving at this time

**Comment by fisforfaheem** [comment]
I applied though, but didn't get any Mail

**Comment by lramos15** [comment]
You will get an email when you're let off the waitlist. Hang tight!

**Comment by 2percentsilk** [comment]
Just a note that we've updated the link (thanks for catching that!) and the email messaging to be more clear. 
GitHub Models is in preview as well but we're looking to accept folks as quickly as we can from that waitlist in order to give you multiple areas to try out the new models.

As `lramos15` said, you'll get an email when you're off the waitlist so hang tight until then!

**Comment by safwan188** [comment]
I just updated to latest vs insider and also pre release version of extension, still no picker available i got the email that iam off the wait list 

also i tried running it from the playground but i got Error code: 401 - {'error': {'code': 'unauthorized', 'message': 'On Waitlist, currently waiting for approval', 'details': None}}

**Comment by niyue** [comment]
UPDATE:
It worked for me after using VS code insider + the latest pre-release version of GitHub Copilot Chat (0.21.2024092003). Thanks for the help.
1) VS code insider: https://code.visualstudio.com/insiders/
2) GitHub Copilot Chat, https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat

**Comment by andremolnar** [comment]
Model selector is not showing up for me either: VS CODE Insiders 1.94 and pre-release Copilot Chat v0.21.2024092501, and the "You now have access to OpenAI o1 models on GitHub!" welcome email.

**Comment by andremolnar** [comment]
And no sooner did I post my previous message and restart the vscode window : the selector showed up.

**Comment by g0t4** [comment]
RESTART VSCODE insiders worked for me too
