### ISSUE TITLE
Copillot is still USING Gpt-4 instead of 4-0 or o1 and here is the proof

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#1606]
please see:
![image](https://github.com/user-attachments/assets/4cee5095-cdb1-4e4c-9aac-52c18f28ff1c)

**Comment by lramos15** [comment]
Chat GPT must be lying too ![Image](https://github.com/user-attachments/assets/14102dc9-af8c-4f26-8fad-ba735bb94460)


We're working on better UX here to indicate the model being used, but I can assure you 4o is being used. Is there some other reason you believe it is not being used?

**Comment by fisforfaheem** [comment]
I think it's because using old flutter suggestion form 3 years ago
