### ISSUE TITLE
Version 0.21.2024092002 is not compatible with VScode '1.93.1'

### ISSUE THREAD

**Issue by MrDalo** [microsoft/vscode-copilot-release#1608]
- Copilot Chat Extension Version: 0.21.2024092002
- VS Code Version: 1.93.1
- OS Version: Windows 11
- Logs: Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.93.1'.

Steps to Reproduce:
I have to install my extensions manually because of company proxy and I can't load extenstion tab in VSCode. for Github Copilot it worked manually but for Github Copilot Chat it does not 
1. Download latest version from microsoft store
2. Install in VScode  from VSIX file

```[tasklist]
### Tasks
```

**Comment by hediet** [comment]
The latest pre-release version of copilot-chat is usually only compatible with the latest insiders of vscode!

Try either installing/updating VS Code insiders or using the last stable copilot-chat.
