### ISSUE TITLE
Sorry, your request was rate-limited. Please wait and try sending again later.

### ISSUE THREAD

**Issue by bradke73** [microsoft/vscode-copilot-release#1613]
Receiving `Sorry, your request was rate-limited. Please wait and try sending again later.` while using Visual Studio Code's extension. This is what I see in output:

`2024-09-20 15:39:16.829 [info] message 0 returned. finish reason: [stop]
2024-09-20 15:39:16.830 [info] request done: requestId: [2c61c9b0-ae03-4ab2-ab4a-ae48ccbf8cb7] model deployment ID: []
2024-09-20 15:39:17.205 [info] Request ID for failed request: f7ad2e5b-1bc9-4d97-b511-9a9102bf0e08`

**Comment by zbayle** [comment]
Same, I thought this was fixed a few days ago. Now its happening on the release version. Hope I don't have to restart my vscode all night long to get my work done.

`Sorry, your request was rate-limited. Please wait and try sending again later.`

**Comment by lramos15** [comment]
@bradke73 I've looked at our rate limit metrics and everything appears to be performing properly. Please read https://github.com/microsoft/vscode-copilot-release/issues/1610#issuecomment-2368508923 for some tips and updates. The error message is being improved to clarify "try again later".

**Comment by abdbfan** [comment]
How long do i wait till i try again later?

**Comment by zbayle** [comment]
Yeah, that doesnt work for the majority of your users. We use this tool all day to work. Im dead in the water until some timer is up???? Then make the tool free if I cant use it. I pay for this.
