### ISSUE TITLE
Sorry, the response hit the length limit. Please rephrase your prompt.

### ISSUE THREAD

**Issue by gmcosta100** [microsoft/vscode-copilot-release#1615]
**- Copilot Chat Extension Version:** v0.20.3
**- VS Code Version:** 1.93.1
**- OS Version:** Windows 11 Pro / 10.0.22621 Build 22621
**- Logs:** "2024-09-21 17:21:28.038 [info] [certificates] Removed 13 expired certificates
2024-09-21 17:21:28.376 [info] [fetcher] Using Helix fetcher.
2024-09-21 17:21:28.376 [info] [code-referencing] Public code references are enabled.
2024-09-21 17:21:28.395 [info] [auth] Successfully authenticated"

Steps to Reproduce:

1. I asked to output the files from the plugin structure and it shows this message: "Sorry, the response hit the length limit. Please rephrase your prompt.". If I ask to reissue the file that it was stopped, then it shows a different output.

**Comment by zbayle** [comment]
Same issue, I get rate limited

**Comment by lramos15** [comment]
@gmcosta100 The current version of 4o we're using has a limit of 4096 output tokens which is roughly 16,000 characters. If the model outputs more than that the response will get truncated. Our metrics indicates that this doesn't occur often but if many edits are being spit out then this can happen. There's not much we can do here except work in the background to update to newer models with larger output windows which is something we're constantly doing.

@zbayle This isn't a rate limit.
