### ISSUE TITLE
Thank you for keeping the world safe

### ISSUE THREAD

**Issue by LEXNY** [microsoft/vscode-copilot-release#1619]
Type: <b>Bug</b>

I had to ask GitHub copilot to format this string for me four times, the first 3 of which it told me the response was filtered by the Responsible AI Service.

```
        return FName(R"(
            When you BARRAGE, you attack with two weapons, or with one SUPERHEAVY weapon.\
            To BARRAGE, choose your weapons and either one target or different targets – within range – then make an attack with each weapon.\
            • In addition to your primary attacks, you may also attack with an AUXILIARY weapon on each mount that was fired,\
              so long as the AUXILIARY weapon hasn't yet been fired this action. These AUXILIARY weapons don't deal bonus damage.\
            • SUPERHEAVY weapons can only be fired as part of a BARRAGE.\
        )");
```

Yeah, please tell me more about how descriptions of scifi weapons are something that needs to be filtered.

Claude doesn't balk about this.  Better put an end to Claude before everyone gets their hands on antimatter cannons.

Extension version: 0.20.3
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
