### ISSUE TITLE
Attach a knowledge base from Copilot Enterprise like in the Copilot Chat on Github.com

### ISSUE THREAD

**Issue by mla-v-office** [microsoft/vscode-copilot-release#1629]
On github.com you can attach a knowledge base from Copilot Enterprise to the Copilot Chat. 
I would like to do this in vscode.

![image](https://github.com/user-attachments/assets/402b5b8c-a6ac-4f20-ac09-c67f27309c29)

**Comment by joyceerhl** [comment]
This is supported: https://github.blog/changelog/2024-06-14-new-copilot-enterprise-features-in-vs-code-preview/#access-your-copilot-knowledge-bases
