### ISSUE TITLE
Suggestions often include invalid characters for the file extension

### ISSUE THREAD

**Issue by samir-jorge-araujo** [microsoft/vscode-copilot-release#163]
Most of the time it shows invalid suggestions for .ini file extension, even though the characters are invalid.

Version: 1.79.0-insider
Commit: 667d4629dee90744edd5054f13bc2452c8c14490
Date: 2023-05-29T05:39:27.608Z
Electron: 22.5.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

Steps to Reproduce:

1. Open an .ini with PHP configuration
2. Type a new setting
3. It will suggest the correct setting, but with ``` at the end

Screenshot:
![Screenshot 2023-05-29 at 17 14 36](https://github.com/microsoft/vscode-copilot-release/assets/24610866/1d233bd6-8b78-49a2-afa9-47e443163ceb)

**Comment by xa-m** [comment]
I had exact same problem in JSON couple times. I think it only happens in config files.

**Comment by digitarald** [comment]
Completion issues are best to file https://github.com/orgs/community/discussions/categories/copilot?discussions_q=label%3ACopilot+label%3ABug+sort%3Atop+category%3ACopilot
