### ISSUE TITLE
Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. Learn more.

### ISSUE THREAD

**Issue by hushino** [microsoft/vscode-copilot-release#1632]
Since this is not resolved and there does not seem to be a follow-up on this case, I will open it as many times as necessary.

- Copilot Chat Extension Version: v0.21.2024090602 (pre-release)
- VS Code Version: 1.93
- OS Version: w11
- Logs:

Steps to Reproduce: 

1. copy the shadcn ui.shadcn.com/blocks#dashboard-03 
2. use the SDK AI from vercel as common 
3. in vscode chat copilot "@workspace #file:page.tsx  #file:route.ts" route.ts is part of api/chat example and page is the shadcn block
4. write "@workspace #file:page.tsx  #file:route.ts make the form works and send the model,temperature,top, role, content"

and get the message 
Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. [Learn more]

I hope this will be resolved this week, should be your top priority.

**Comment by hushino** [comment]
OK, just use the example block of shadcn dashboard03, and write that you want to validate the form with zod.
And you get "Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again".
I don't have logs

**Comment by thewoosh1** [comment]
This is rubbish - I am getting this error almost every time I ask for a suggestion for HTML/CSS - I can see the answer as it is being generated but as soon as it finishes it removes it and displays the error...

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
