### ISSUE TITLE
Failed to compute args for tool: "cpptools-lmtool-configuration"

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-copilot-release#1634]
Type: <b>Bug</b>

I type "#cpp" and it gives "Failed to compute args for tool: "cpptools-lmtool-configuration". It only repros with certain workspace folders (I don't know what triggers it).

Extension version: 0.21.2024092402
VS Code version: Code - Insiders 1.94.0-insider (f35c3823e3b7ea4c52f7fee4659bcce39b42ce9e, 2024-09-24T05:04:12.797Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.85GB (34.33GB free)|
|Process Argv|--crash-reporter-id baf1f71c-33c3-4cfd-b192-986653a51161|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 0)|
|Memory (System)|31.27GB (26.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 0)|
|Memory (System)|31.27GB (26.96GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31144450
e80f6927:31120813
fje88620:31121564
12bdf347:31141542
iacca2:31144504
notype1:31143044
b50ed353:31138333
showchatpanel:31139797
f8igb616:31140137

```

</details>

**Comment by sean-mcmanus** [comment]
My repro is with the pending 1.22.5 release of the C/C++ extension.

**Comment by sean-mcmanus** [comment]
The GitHub Copilot Chat logging window says "[error] Request Failed: 400 {"error":{"message":"prompt token limit exceeded","param":"","code":"","type":""}}" before the previously mentioned failure, so it seems like that's the root cause.

**Comment by sean-mcmanus** [comment]
@benmcmorran The bug still repros with the latest C/C++ and GitHub Copilot extension: 

![image](https://github.com/user-attachments/assets/8dd6c267-64b1-4316-b975-0b7a97807af2)

**Comment by roblourens** [comment]
> The GitHub Copilot Chat logging window says "[error] Request Failed: 400 {"error":{"message":"prompt token limit exceeded","param":"","code":"","type":""}}" before the previously mentioned failure, so it seems like that's the root cause.

Is this in an existing chat conversation with a lot of history? It's possible we're not counting tokens correctly for the tool call

**Comment by sean-mcmanus** [comment]
@roblourens Yes, it's an existing chat conversation with a lot of history.

**Comment by sean-mcmanus** [comment]
I just hit this error in our TypeScript repo, so it's unrelated to the `#cpp` mentioned in the original issue (although that might be a different repro).

2024-10-03 13:04:05.722 [error] Request Failed: 400 {"error":{"message":"prompt token count of 19378 exceeds the limit of 12288","param":"","code":"","type":""}}

2024-10-03 13:04:05.724 [error] Error: Failed to compute args for tool: "cpptools-lmtool-configuration"

![image](https://github.com/user-attachments/assets/70141178-3f07-429f-ab2a-72710ae7a756)

It worked when I asked it to try again.

**Comment by roblourens** [comment]
Have you seen this again? I think it should be gone now

**Comment by TylerLeonhardt** [comment]
We saw this once in `#websearch` and haven't seen it since. I'll mark this as verified.
