### ISSUE TITLE
一直显示正在生成

### ISSUE THREAD

**Issue by amybaialder** [microsoft/vscode-copilot-release#1636]
Type: <b>Bug</b>

一直hang在正在生成，hang了很久

Extension version: 0.20.0
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (5.86GB free)|
|Process Argv|--crash-reporter-id 53a4c461-a638-48f7-9692-9bfd377abb8e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
cf971741:31144450
pme_test_t:31118333
fje88620:31121564
iacca2:31144504
cc771715:31140165

```

</details>

**Comment by lramos15** [comment]
Please do `F1 -> Set Log level -> Trace` then press `CMD + SHIFT + U` and attach the GitHub Copilot Chat logs.


Also do `F1 -> GitHub Copilot Chat Diagnostics`

**Comment by ArvinGitHubSource** [comment]
2024-09-30 16:01:10.774 [debug] onDidChangeSessionsHandler has token: true
2024-09-30 16:01:10.779 [debug] [LanguageModelAccess] UPDATING language models
2024-09-30 16:06:14.716 [info] Fetched model metadata in 3763ms 6456222e-d811-4804-bb09-054186d232df
2024-09-30 16:06:14.717 [debug] [LanguageModelAccess] UPDATING language models
2024-09-30 16:16:10.784 [debug] [LanguageModelAccess] UPDATING language models
2024-09-30 16:21:15.707 [info] Fetched model metadata in 971ms 90902448-9630-4950-a867-ac328f7d08a5
2024-09-30 16:21:15.714 [debug] [LanguageModelAccess] UPDATING language models****
