### ISSUE TITLE
Inline Chat prompt automatically submits after the first letter

### ISSUE THREAD

**Issue by simonknittel** [microsoft/vscode-copilot-release#1638]
For some time already I've got some weird behavior when using the Inline Chat. When I open the Inline Chat and start entering my prompt, it gets submitted immediately after entering the first letter. Usually that doesn't result in any response, but makes the input loose focus and therefore is pretty annoying.

Video:
https://github.com/user-attachments/assets/75c31369-2645-4487-a223-f5615f3ae21d

- Copilot Chat Extension Version: v0.21.2024090602 (pre-release)
- VS Code Version: 1.93.1
- OS Version: macOS 14.6.1
- Logs:

Steps to Reproduce:

1. Open the Inline Chat
2. Enter anything

**Comment by jrieken** [comment]
@simonknittel Do you have the speech extension (`ms-vscode.vscode-speech`) installed and would you mind trying with that disabled? Background: we have a feature that long pressing `cmd+i` goes directly to "dictate mode". Maybe those timings aren't working for you

**Comment by simonknittel** [comment]
Hi @jrieken
No, I don't have the extension installed.

However.... I had this issue for several weeks. I now wanted to reproduce it with all extensions disabled (except Copilot) and suddenly can not reproduce it anymore at all. It's not an issue anymore even though I didn't change anything.

I will close this issue. Thanks anyways 🙂

**Comment by jrieken** [comment]
Ok, please keep an eye open and feel free to reopen this issue if this happens again.

**Comment by simonknittel** [comment]
I think I've figured out the issue. It somehow results from my unconventional setup.

I have two separate computers running at the same time: A MacBook and a Windows. However, since I only want to use a single pair of keyboard+mouse I'm using the tool [Synergy](https://symless.com/synergy). With that tool I can connect my MacBook to my Windows and use the keyboard+mouse of my Windows on both machines. I can move the mouse to the MacBook just like an additional screen.

When I use the keyboard of my MacBook directly and therefore not making use of Synergy, everything works fine.
However, when I use the keyboard which is connected to my Windows but made available on my MacBook by Synergy, it breaks.

If I use my Windows keyboard on a VSCode on Windows, it also works fine.

So it seems like the issue stems from Synergy. I never experienced any similar issues with Synergy.

I won't reopen this issue since I don't think it's the fault of your extension.
