### ISSUE TITLE
In Editor window, Accept button disappears  

### ISSUE THREAD

**Issue by gamousquesORT** [microsoft/vscode-copilot-release#164]
- VS Code Version: 1.79.0-insider
- OS Version: Windows_NT x64 10.0.19043
- Logs: [logsessionineditorchat.md](https://github.com/microsoft/vscode-copilot-release/files/11593120/logsessionineditorchat.md)

Steps to Reproduce:

1. Using the in editor chat window, I asked copilot to replace some code. The first time it displayed an accept button as showed in the followin screenshot. 

![change several lines of code](https://github.com/microsoft/vscode-copilot-release/assets/27827078/7e71db6d-4df7-40d8-957c-c3972ae01558)

3. __After that, I asked for another replacement, and it didn't ask me to accept,  it just changed all occurrences.__

4. I tried again and worked as expected asking.

5. I couldn't make it repeat the behavior. I understand that probably it isn't an appropriate command for the bot, but someone could use it.

**Comment by jrieken** [comment]
closing as stale
