### ISSUE TITLE
Encountered an error while deciding what workspace information to collect: (failed) Prompt failed validation with the reason: No messages provided. Please file an issue.

### ISSUE THREAD

**Issue by faheemstepsharp** [microsoft/vscode-copilot-release#1647]
Encountered an error while deciding what workspace information to collect: (failed) Prompt failed validation with the reason: No messages provided. Please file an issue.

![image](https://github.com/user-attachments/assets/795664eb-037f-4405-9e89-f780ce1c963c)
![image](https://github.com/user-attachments/assets/49624c9a-37f2-4590-b4d2-6cfbe452871b)

**Comment by mjbvz** [comment]
Please share the full text of your prompt. I suspect it may be too long and getting filtered out

**Comment by mjbvz** [comment]
Thanks. I'm not sure what the expected response is but if I paste that exact text into chat, I don't see this error. Can you please try in the latest Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) build with that latest copilot chat nightly release to see if this has already been fixed

**Comment by faheemstepsharp** [comment]
fixed after i reisntalled cursor :( I hope vscode and github team really  come and see issues

**Comment by mjbvz** [comment]
Closing as not reproducible
