### ISSUE TITLE
Increase limit for the message text in chat PLEASE

### ISSUE THREAD

**Issue by faheemstepsharp** [microsoft/vscode-copilot-release#1648]
I FEEL VERY constrained here

**Comment by lramos15** [comment]
Please provide an example

**Comment by faheemstepsharp** [comment]
when i try to copy code or select large code its gives errors:import 'package:equatable/equatable.dart';

class KdsOrderResponse extends Equatable {
  final List<StatusModel> statuses;
  final Map<String, List<KdsOrderModel>> ordersByStatus;
  final String filterStatus;
  final Map<String, int> totalOrdersByStatus;

  const KdsOrderResponse({
    required this.statuses,
    required this.ordersByStatus,
    required this.filterStatus,
    required this.totalOrdersByStatus,
  });

  factory KdsOrderResponse.fromJson(Map<String, dynamic> json) {
    final data = json['data'];
    return KdsOrderResponse(
      statuses: (data['statuses'] as List)
          .map((item) => StatusModel.fromJson(item))
          .toList(),
      ordersByStatus: (data['orders_by_status'] as Map<String, dynamic>).map(
        (key, value) => MapEntry(
            key,
            (value as List)
                .map((item) => KdsOrderModel.fromJson(item))
                .toList()),
      ),
      filterStatus: data['filter_status'],
      totalOrdersByStatus:
          Map<String, int>.from(data['total_orders_by_status']),
    );
  }

  @override
  List<Object?> get props =>
      [statuses, ordersByStatus, filterStatus, totalOrdersByStatus];
}

class StatusModel extends Equatable {
  final int id;
  final String name;
  final int businessId;

  const StatusModel({
    required this.id,
    required this.name,
    required this.businessId,
  });

  factory StatusModel.fromJson(Map<String, dynamic> json) {
    return StatusModel(
      id: json['id'],
      name: json['name'],
      businessId: json['business_id'],
    );
  }

  @override
  List<Object?> get props => [id, name, businessId];
}

class KdsOrderModel extends Equatable {
  final int id;
  final int contactId;
  final int waiterId;
  final int tableId;
  final int transactionId;
  final int businessId;
  final int locationId;
  final String bookingStatus;
  final String type;
  final TransactionModel transaction;

  const KdsOrderModel({
    required this.id,
    required this.contactId,
    required this.waiterId,
    required this.tableId,
    required this.transactionId,
    required this.businessId,
    required this.locationId,
    required this.bookingStatus,
    required this.type,
    required this.transaction,
  });

  factory KdsOrderModel.fromJson(Map<String, dynamic> json) {
    return KdsOrderModel(
      id: json['id'],
      contactId: json['contact_id'],
      waiterId: json['waiter_id'],
      tableId: json['table_id'],
      transactionId: json['transaction_id'],
      businessId: json['business_id'],
      locationId: json['location_id'],
      bookingStatus: json['booking_status'],
      type: json['type'],
      transaction: TransactionModel.fromJson(json['transaction']),
    );
  }

  @override
  List<Object?> get props => [
        id,
        contactId,
        waiterId,
        tableId,
        transactionId,
        businessId,
        locationId,
        bookingStatus,
        type,
        transaction
      ];
}

class TransactionModel extends Equatable {
  final int id;
  final int businessId;
  final int locationId;
  final int noOfPersons;
  final String status;
  final String paymentStatus;
  final String finalTotal;
  final List<SellLineModel> sellLines;
  final TypesOfServiceModel typesOfService;

  const TransactionModel({
    required this.id,
    required this.businessId,
    required this.locationId,
    required this.noOfPersons,
    required this.status,
    required this.paymentStatus,
    required this.finalTotal,
    required this.sellLines,
    required this.typesOfService,
  });

  factory TransactionModel.fromJson(Map<String, dynamic> json) {
    return TransactionModel(
      id: json['id'],
      businessId: json['business_id'],
      locationId: json['location_id'],
      noOfPersons: json['no_of_persons'],
      status: json['status'],
      paymentStatus: json['payment_status'],
      finalTotal: json['final_total'],
      sellLines: (json['sell_lines'] as List)
          .map((item) => SellLineModel.fromJson(item))
          .toList(),
      typesOfService: TypesOfServiceModel.fromJson(json['types_of_service']),
    );
  }

  @override
  List<Object?> get props => [
        id,
        businessId,
        locationId,
        noOfPersons,
        status,
        paymentStatus,
        finalTotal,
        sellLines,
        typesOfService
      ];
}

class TypesOfServiceModel extends Equatable {
  final int id;
  final String name;
  final int preparationTime;

  const TypesOfServiceModel({
    required this.id,
    required this.name,
    required this.preparationTime,
  });

  factory TypesOfServiceModel.fromJson(Map<String, dynamic> json) {
    return TypesOfServiceModel(
      id: json['id'],
      name: json['name'],
      preparationTime: json['preperation_time'],
    );
  }

  @override
  List<Object?> get props => [id, name, preparationTime];
}

class SellLineModel extends Equatable {
  final int id;
  final int transactionId;
  final int productId;
  final int quantity;
  final List<ModifierModel> modifiers;
  final String unitPriceIncTax;
  final String sellLineNote;

  const SellLineModel({
    required this.id,
    required this.transactionId,
    required this.productId,
    required this.quantity,
    required this.modifiers,
    required this.unitPriceIncTax,
    required this.sellLineNote,
  });

  factory SellLineModel.fromJson(Map<String, dynamic> json) {
    return SellLineModel(
      id: json['id'],
      transactionId: json['transaction_id'],
      productId: json['product_id'],
      quantity: json['quantity'],
      modifiers: (json['modifiers'] as List)
          .map((item) => ModifierModel.fromJson(item))
          .toList(),
      unitPriceIncTax: json['unit_price_inc_tax'],
      sellLineNote: json['sell_line_note'] ?? '',
    );
  }

  @override
  List<Object?> get props => [
        id,
        transactionId,
        productId,
        quantity,
        modifiers,
        unitPriceIncTax,
        sellLineNote
      ];
}

class ModifierModel extends Equatable {
  final String gmodifier;
  final String modifier;
  final double price;
  final int count;

  const ModifierModel({
    required this.gmodifier,
    required this.modifier,
    required this.price,
    required this.count,
  });

  factory ModifierModel.fromJson(Map<String, dynamic> json) {
    return ModifierModel(
      gmodifier: json['gmodifier'],
      modifier: json['modifier'],
      price: json['price'].toDouble(),
      count: json['count'],
    );
  }

  @override
  List<Object?> get props => [gmodifier, modifier, price, count];
}

**Comment by lramos15** [comment]
What are the errors it gives? I can past that above code just fine

![Image](https://github.com/user-attachments/assets/b586b0c2-321b-4a30-a00c-8f786e772913)
