### ISSUE TITLE
copilot chat still using GPT4 TURBO  instead of 4o

### ISSUE THREAD

**Issue by faheemstepsharp** [microsoft/vscode-copilot-release#1649]
![image](https://github.com/user-attachments/assets/8616cd32-b759-4c45-932b-ca55ee7d1c47)

after that it gives weird answers and not focus on question :
![image](https://github.com/user-attachments/assets/6c334229-53ff-4c66-bbfb-af0194e81f77)

**Comment by lramos15** [comment]
I've already answered this issue from you multiple times, please do not continue to file duplicates

**Comment by faheemstepsharp** [comment]
Ok  as a customer, In the blogpost github said we are now using GitHub 4o then why cant  i see that i nthe chat? PLEASE TELL
