### ISSUE TITLE
Session history cannot be opened in the side panel, only as a tab

### ISSUE THREAD

**Issue by shimonsalamon** [microsoft/vscode-copilot-release#165]
Session history cannot be opened in the side panel, only as a tab

### Steps to Reproduce

1. Open Visual Studio Code.
2. Open the Copilot chat.
3. Click on the "Show History" button in the chat window.
4. Notice that the session history opens as a tab instead of in the side panel.

### Expected Results

The session history should open in the side panel when the "Show History" button is clicked.

### Actual Results

The session history opens as a tab instead of in the side panel.

**Comment by roblourens** [comment]
What should happen if you already have a session going in the sidebar? You can at least use the "Open session in sidebar" command to switch it over explicitly.

**Comment by roblourens** [comment]
This is changed now
