### ISSUE TITLE
Request failed

### ISSUE THREAD

**Issue by matrix303** [microsoft/vscode-copilot-release#1652]
Type: <b>Bug</b>

Request ID: 55c66c69-8f4f-4cf9-9bcc-7ba79961ad1e

Extension version: 0.21.2024092501
VS Code version: Code - Insiders 1.94.0-insider (be2747e47e127ec674148b78dd9556c6317d18bd, 2024-09-25T05:04:31.141Z)
OS version: Darwin x64 23.6.0
Modes:
Remote OS version: Linux x64 6.8.4-3-pve

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 7ab92fa2-161f-4187-a987-f0c1275bec0a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vedgeLocal|
|OS|Linux x64 6.8.4-3-pve|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (16 x 4400)|
|Memory (System)|8.00GB (3.79GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vsc_aa:30263845
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialogc:30812479
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-c:31125598
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
fje88620:31121564
12bdf347:31141542
iacca2:31144504
notype1:31143044
b50ed353:31138333
showbadge:31139796
f8igb616:31140137

```

</details>

**Comment by joyceerhl** [comment]
Please track https://www.githubstatus.com/ for updates on service availability
