### ISSUE TITLE
"Request failed" message for all response using VSCode Insider

### ISSUE THREAD

**Issue by DiarCyborg** [microsoft/vscode-copilot-release#1653]
Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id 5b57a3da-1e05-4923-887d-1c690b4c0c81 and try again

Extension version: 0.21.2024092501
VS Code version: Code - Insiders 1.94.0-insider (Universal) (be2747e47e127ec674148b78dd9556c6317d18bd, 2024-09-25T05:04:31.141Z)
OS version: Darwin arm64 24.0.0
Modes:

**Comment by joyceerhl** [comment]
Please track https://www.githubstatus.com/ for updates on the ongoing Copilot service disruption.

**Comment by lramos15** [comment]
There was an incident that has since been resolved, please let us know if you have any other issues.

**Comment by sasiksk** [comment]
Sorry, your request failed. Please report the following request id 07edbb29-af8d-4137-be60-e4e6e814afde and try again i am getting error for all the queris what happed?
