### ISSUE TITLE
Server error, please report the following request id

### ISSUE THREAD

**Issue by suisbuds** [microsoft/vscode-copilot-release#1656]
Type: **Bug**

Description: Server error, please report the following request id: 782de57e-c3bc-4da2-8bb7-5eb5d65de386

- Copilot Chat Extension Version: v1.234.0
- VS Code Version: Visual Studio Code 1.93.1
- OS Version: Linux 6.10.10-arch1-1
- Logs:
deployment ID: []
2024-09-26 10:51:00.651 [info] Request ID for failed request: 8b7ce48d-1f5d-4409-b2ca-a168715f9641
2024-09-26 10:51:00.652 [error] Server error: 500 Internal Server Error

2024-09-26 10:51:39.942 [info] Request ID for failed request: 782de57e-c3bc-4da2-8bb7-5eb5d65de386
2024-09-26 10:51:39.943 [error] Server error: 500 Internal Server Error

Server error, please report the following request id: 2042e6f3-604b-4bea-a0c6-cb04c105c9bc

**Comment by Deepan-kishore** [comment]
same here with this :  please report the following request id: b9a548f9-ada0-407e-b096-ed65eded9138
facing this often.. 6 out of 10 prompts fails and is showing this!!

**Comment by EricYip8946** [comment]
Same. I simply entered "hi" and received this: 
Server error, please report the following request id: 83a77cef-0ea8-4ca3-a90b-105a9d7d2a17

**Comment by Deepan-kishore** [comment]
I installed the pre release version in extension.... closed the vs code then opened it. Its working now!!
But not sure if  the issue will appear again

**Comment by EricYip8946** [comment]
> I installed the pre release version in extension.... closed the vs code then opened it. Its working now!! But not sure if the issue will appear again

I followed these steps but still not working. I received pop-up message "getaddrinfo ENOTFOUND api.github.com"

**Comment by EricYip8946** [comment]
> I installed the pre release version in extension.... closed the vs code then opened it. Its working now!! But not sure if the issue will appear again

Thank you! It works.
