### ISSUE TITLE
Server error, please report the following request id: 65b02b79-277f-4310-bb17-e01a6c165bd4

### ISSUE THREAD

**Issue by SoftSisPro** [microsoft/vscode-copilot-release#1657]
Server error, please report the following request id: 65b02b79-277f-4310-bb17-e01a6c165bd4

**Comment by aiday-mar** [comment]
Hi could you please provide more information as to when you saw this message. What were you dong, where did you see the message? A screen recording would be helpful.

**Comment by lramos15** [comment]
There was an incident that has since been resolved, please let us know if you have any other issues.
