### ISSUE TITLE
Completely forgets about chat context, and generally feels dumber than ChatGPT4

### ISSUE THREAD

**Issue by mnj** [microsoft/vscode-copilot-release#166]
Version: 1.79.0-insider (system setup)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:18:53.811Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22623
Github Copilot Nightly: v1.86.118

Steps to Reproduce:

1. Ask a general question, in this case about whether some events used with event-driven architecture (EDA) could be improved
2. It lists some general suggestions but doesn't feel like it's even looking at the 3 (simple) interfaces I have open in VS Code, but it does list 5 points, in numbered points.
3. Ask follow-up questions about how to do points 3,4,5 it suggested
4. It starts talking about something completely irrelevant, in this case about code folding?!?
![Copilot1](https://github.com/microsoft/vscode-copilot-release/assets/84253/0f3f4a0a-f038-4361-91b5-6a3fcd585c3b)

Was really excited about this new Copilot, but it really feels 10x dumber than even ChatGPT 3.5, not sure if it's because you are not feeding it enough context of the open files, or if you just have way too aggressive GPT parameters running.

Meanwhile, if you ask ChatGPT4, the same question, it answers clearly, and as intended, a similar question is asked in ChatGPT4 here: https://chat.openai.com/share/c30f92f3-461f-4441-9de3-f9affa239404, it understands you are talking about the previous points.

Not sure what has happed to GPT4 in Microsoft, it's the same problem on bing, it always feels more like GPT3.5 than GPT4 for coding related things, while it's extremely rare, that ChatGPT4 gets things wrong, or doesn't understand the context, even after 20+ Q/A's down the line in a conversation.

This is not the first time I have seen it being completely lost:
![copilot-issues-1](https://github.com/microsoft/vscode-copilot-release/assets/84253/42094198-46e8-41a2-985b-56cd4e8da23e)

And when you actually do get it to write unit tests in xUnit, they often don't even compile, meanwhile ChatGPT4 even with less knowledge/context, is able to generate them without issues.

I'm fully aware this is an early preview, but I just don't get how the Microsoft "GPT4" implementation, is so much worse compared to ChatGPT, if it's a cost issue just let us pay for it.

**Comment by giuricich** [comment]
skill issue

**Comment by Meathelix1** [comment]
I am at the point of needing to give it nearly everything, where I might aswell just code it myself. 
Too add to that I am getting a lot of "Your Response Got Filtered" 

I feel like you have to Tablespoon feed Github Copilot, while GPT 4 API you only need a Teaspoon.

**Comment by rosmcmahon** [comment]
it appears to be using gpt 3.

**Comment by julian-shalaby** [comment]
[Here's](https://plugins.jetbrains.com/plugin/22895-chatwindow) an alternative which lets you use GPT4 with your own API key

**Comment by rosmcmahon** [comment]
> [Here's](https://plugins.jetbrains.com/plugin/22895-chatwindow) an alternative which lets you use GPT4 with your own API key

looks nice, but this doesn't work with vscode, so not really an alternative ?

**Comment by digitarald** [comment]
Update from #6: All responses in panel/quick chat are served by GPT-4 since Copilot Chat 0.10 (part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_github-copilot)). 3.5 is still used for other messages.

Please give it a try and file new issues for any follow-up feedback!

**Comment by binaryfire** [comment]
@digitarald Still seeing GPT-3 in v0.10.0:
<img width="643" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5361908/0dc8481c-c688-490d-adf5-ab23ca68ff11">
<img width="391" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5361908/4b194073-11f0-4e97-816f-2eb715d68f3e">

**Comment by binaryfire** [comment]
@digitarald Can confirm the answers are still GPT-3 level too. They aren't anywhere near as good as the GPT-4 model in ChatGPT
