### ISSUE TITLE
Gighub copilot chat for vscode on linux through OOD Apps

### ISSUE THREAD

**Issue by Sapanasoni** [microsoft/vscode-copilot-release#1666]
- Copilot Chat Extension Version: GitHub.copilot-chat-0.21.2024092601.vsix
- VS Code Version: 1.92.2
- OS Version: Rocky-8-Linux
- Logs:
[spsoni@ln003 ~]$ code-server --install-extension GitHub.copilot-chat-0.21.2024092601.vsix
Installing extensions...
Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.92.2'.
    at G.install (/global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:172:75857)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async a.h (/global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:145:1092)
    at async /global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:144:9774
    at async Promise.all (index 0)
    at async a.installExtensions (/global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:144:9711)
    at async /global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:186:76641
    at async se.run (/global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:186:76404)
    at async Q (/global/home/users/spsoni/.local/lib/code-server-4.92.2/lib/vscode/out/vs/server/node/server.main.js:186:78861)
Failed Installing Extensions: file:///global/home/users/spsoni/GitHub.copilot-chat-0.21.2024092601.vsix

Steps to Reproduce:

1.Installed VS Code using following steps
VERSION=4.92.2
mkdir -p ~/.local/lib ~/.local/bin
curl -fL https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz \
  | tar -C ~/.local/lib -xz
mv ~/.local/lib/code-server-$VERSION-linux-amd64 ~/.local/lib/code-server-$VERSION
ln -s ~/.local/lib/code-server-$VERSION/bin/code-server ~/.local/bin/code-server
PATH="~/.local/bin:$PATH"
code-server
# Now visit http://127.0.0.1:8080. Your password is in ~/.config/code-server/config.yaml
2.Downloaded githubchat vsix file on my mac moved it to linux server and used command "code-server --install-extension GitHub.copilot-chat-0.21.2024092601.vsix"

**Comment by jrieken** [comment]
> Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.92.2'.

Looks like you use the prerelease version of chat with stable vscode. That isn't supported and you should use the extension's release version or vscode insiders

**Comment by Sapanasoni** [comment]
I am using code-server version 4.91.1 and copilot-chat 0.21. I fixed above using by changing the project.json file. Modified vscode:'^4.94.1' with lower version. Now I am getting another issue. Chat is not working properly and give me the error message "Right-hand side of 'instanceof' is not an object" when I ask any questions.

**Comment by Sapanasoni** [comment]
How do I download specific version of copilot chat vsix file?
