### ISSUE TITLE
Option to see the whole code suggestion when copilot chat and code editor opened simultaneously

### ISSUE THREAD

**Issue by kantarogit** [microsoft/vscode-copilot-release#168]
```
Version: 1.79.0-insider (user setup)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:18:53.811Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

When code suggestions appears in chat extension on the left side, while the code editor opened at the same time, some of the code (if line so long) would not be visible unless the whole extension window expanded to the right.

This is an issue to small view-port devices (the screenshot is taken on a 14 inch screen, 1920x1080 resolution, at a scale of 125%, Windows 11). The code on the left window is cut-off and the lines are not completely visible.

One of the solutions is to have an on-hover popup that would be on top of the chat and code editors so the user can see the suggestions as a whole before accepting/rejecting the code suggestion.
Word wrapping might be a solution as well but it might add even more difficulties reading the suggestion when copilot chat window shrank more.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24574892/24ee5c7b-7e00-4281-927a-b52cace3d77a)

Additional screenshot with long function definition:

![image](https://github.com/microsoft/vscode-copilot-release/assets/24574892/07926b74-9108-4ecd-82a4-cbab203a1c04)

**Comment by kantarogit** [comment]
Once updated to latest version of VS Insider a horizontal scroll appears, which is a nice way to preview small piece of code, however, when several indentations exist, it becomes a mess to read the suggested code because the user needs to go back and forth to understand the suggested code.

While the code might be accepted and then rejected in the actual code editor, it just adds several extra steps making this as a workaround.

initial situation

![image](https://github.com/microsoft/vscode-copilot-release/assets/24574892/01047b18-fa5a-425a-96e2-14efa7e3d41a)

scroll to the right

![image](https://github.com/microsoft/vscode-copilot-release/assets/24574892/d19fc8ae-4f17-4b13-8427-635508af4211)

**Comment by roblourens** [comment]
You can enable word wrapping if you want with the setting `chat.editor.wordWrap`. You can also now open chat sessions in the editor to get the full width. Do you have a suggestion for how a hover would work? This shows up whenever you hover the codeblock? That could be helpful but also sounds possibly disruptive.

**Comment by kantarogit** [comment]
@roblourens i was not aware of that setting. I think the default value should be `"chat.editor.wordWrap": "on"` because it simply feels better with word wrapping on small screens.

While working with the chat in a separate editor might help with the better preview of the suggested code, it is just annoying switching between tabs all the time.

I was thinking of some popup window like this:

![image](https://github.com/microsoft/vscode-copilot-release/assets/24574892/c32d388d-0137-43e7-aa82-5f835d30003e)

with all the options in the menu as in the regular chat (Copy, Insert at Cursor, Run in console etc).
Now the question is, how long should the mouse stay still over the codeblock to "activate" the popup. And what will be the close event (one might be leaving the popup area, ESC the other i.e.).

The main chat area (previous conversation etc...) might be blurred as well to emphasize the code suggestion in the popup.

Is this feature better over the current solution with the word wrapping? Debatable, i think it is personal preference and some form of A/B test might give the right answer :)

**Comment by NikiLentz** [comment]
I think a small "pop out" button for that use case would be better than hover.

**Comment by kantarogit** [comment]
@NikiLentz it might work as well..
it looks like more of a UX problem here i think...

do you think that 2 actions: (pop out -> accept) will be more useful than (accepting first -> undo in the main code editor later)?
because at the moment the buttons are not floating so in a case of long code suggestion which is too wide to be shown at the chat window, it will require going to top to click that pop-out button.
What about double click in the suggestion area?
