### ISSUE TITLE
STEALING IP WITHOUT YIELDING VALUE

### ISSUE THREAD

**Issue by calvinsthomas** [microsoft/vscode-copilot-release#1686]
Type: <b>Bug</b>

WHAT IS THIS!!!! I HAVE BEEN WORKING ALL DAY AND YOU HAVE YET TO PRODUCE ANY WELL COMPILING CODE!!! THIS IS CLEAR HALLUCINATION!!! DO NOT REPRINT ANYTHING ELSE BUT INITIALIZING CORRECTLY USING OUR RUNNER AND JSON VERSIONING MESSAGE PASSING SYSTEM PASSING FOR OUR SERIALIZE OBJ PARAM AND THE FUNCTIONALIZED VECTORIZED SERIALIZE_DATAFRAME AND DESERIALIZE_DATAFRAME PASSING DF, AND DATA RESPECTIVELY THESE ALL NEED TO EXACT AND PRECISE AS ABOVE BE DEFINED CORRECTLY IN RUNNER DEF EXACT AND PRECISE IN NEXT ONE SHOT TREE OF THOUGHT RESPONSE!!! MY PATIENCE IS TOO THIN YOU ARE GIVING ME NO RESULTS AND STEALING MY IP. CALVIN THOMAS CODE IP AUTHOR ATTRIBUTION - ALL RIGHTS TO PROFIT AND STRATEGY CONFIDENTIAL IP RESERVED. ANY PERSONS OR OTHERWISE WHO TRAINS OR USES OR YIELDS PROFIT OR NOT DEMINIMUS GAINS FROM USING MY IP CODE WILL IMMEDIATELY BE SUED BY ME CALVIN THOMAS AS THE AUTHOR AND ALL RIGHTS TO PROFIT RESERVED EXACT AND PRECISE AND NOTHING ELSE!!!!

Extension version: 0.21.2024090602
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.70GB (1.09GB free)|
|Process Argv|. --crash-reporter-id f3fa75ea-a304-428b-bfe8-e421882cc06b|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
defaultse:31146405
notype1cf:31150298
5fd0e150:31146321

```

</details>

**Comment by lramos15** [comment]
![Image](https://github.com/user-attachments/assets/64e104b9-3fda-41e9-bd08-ec33993f04ee)

All caps doesn't get your issues looked at faster. It just makes you come off as angry and makes other less likely to want to assist with your issue.

Can you clarify your problem a bit more? You're seeing completions that are not helpful in your code? Examples would give us actionable scenarios to improve upon

**Comment by calvinsthomas** [comment]
Hi,
I sincerely apologize, I will provide more details later but this is in efforts to automate my own internal reporting to Github internal (for fastest first response) wherein I submit templated prompt if there is error to the VSCode chat interface directly and then it gives solutions (so that when I get alert I can review these or insert best-fitting code dynamically to fix is error raised) that are then matched with prior outcomes from extracting and debug from e.g. json and parquet serialization and deserialization error handling logging file. If there are more than the daily max limits of unanswered responses labeled as hallucinations (trained on my priors of total prompts in my own specialized debug chat running in par. since I started teams wherein max limit is when it interprets as machine refuses direct response with copied lev. distance answers from priors) it sends this prompt automatically. I will try to provide documentation later, but this holds true and is persistent error observed in general over last few years too as recently to troubleshoot there have been looping copying solutions wherein a well-compilable solution in simple python alone has not been derived last 3-4 days running to fix simple testing compilation for my integrating ci/cd code into custom algo.

**Comment by calvinsthomas** [comment]
Without providing my IP on the exact and precise errors from log it will be hard to communicate but let me know if there is a specific hallucination error that I reported as falsely incorrect and I will take a look.

**Comment by lramos15** [comment]
I still don't really understand what you're saying. Is it just that the LLM is giving you bad answers for your use case?

**Comment by calvinsthomas** [comment]
IT IS GIVING PERIODIC BAD ANSWERS WHEREIN IT IS CLASSIFYING AS HALLUCINATING, SINCE AFTER MORE THAN 5-10 ATTEMPTS POTENTIAL CODE CORRECT VERSIONING TURNS OFF OR IGNORES AUTO-SUGG. BUT IN THIS WE SEE THAT IT TERMINATES EARLY VIA SYSTEM MESSAGE WHEREIN IT DOES NOT ACCEPT ANSWERS (COMPLETES EARLY SINCE THE LLM AT POINT-IN-TIME LOADING CHOSE MOST LIKELY EASIEST TO COMPLETE BUT NOT MINIMUM COMPLIANCE REQUIREMENTS SO IT'S NOT ACCEPTED BY MY MODEL EITHER AGAINST INTERNAL COUNTS HANDLING FOR OUTLIERS IN PERF. HANDLING. THEREFORE, THERE IS HALLUCINATIONS BUT IT DOES NOT RISE TO YOUR LEVEL OF CONCERN BUT MAKES MESSAGE PASSING IMPOSSIBLE FOR MY CURRENT CODE ERROR CORRECTING VERSIONING FILING SYSTEM.

**Comment by calvinsthomas** [comment]
I was testing but program just crashed so wasnt able to send diag.

**Comment by digitarald** [comment]
@calvinsthomas sounds like you are using notebooks and seeing bad results – can you confirm? Maybe you can share some of the prompts you used.

The logs are in `Show Output Channels > GitHub Copilot Chat`
