### ISSUE TITLE
if the code line is indented, it automatically shifts to extreme left if I try to edit something within the line.

### ISSUE THREAD

**Issue by Neural-Net-Ninja** [microsoft/vscode-copilot-release#169]
- VS Code Version: `1.78.2
b3e4e68a0bc097f0ae7907b217c1119af9e03435
x64`
- OS Version: Windows-10-10.0.22621-SP0
- Logs:

Steps to Reproduce:

1.  In a indented line in python, try to add something or edit something, for example  adding (device="cuda:0" ).
2. as soon i start making changes, or start typing something in code line, whole code starts shifting to left, and now the indentation is wrong.

**Comment by Neural-Net-Ninja** [comment]
https://github.com/microsoft/vscode-copilot-release/assets/75391695/22fde4a1-2f27-4457-acbf-82f06bbf6552

**Comment by zhangyiy0223** [comment]
same problem
