### ISSUE TITLE
Generated Makefiles use spaces instead of tabs

### ISSUE THREAD

**Issue by topfunky** [microsoft/vscode-copilot-release#1692]
Type: <b>Bug</b>

Makefiles must use tabs, not spaces. Everytime Copilot generates a Makefile, it uses spaces instead of tabs.

For example,

> Create a Makefile that runs my tests in Docker

Extension version: 0.20.3
VS Code version: Code 1.93.1 (Universal) (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.88GB free)|
|Process Argv|/Users/geoffrey.grosenbach/Documents/Working/2024/TODO/39.todo --crash-reporter-id f956b6f1-025b-4f9f-b34f-e95180772fd5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by topfunky** [comment]
Related but not a fix https://github.com/microsoft/vscode-copilot-release/issues/527

All Makefiles must use tabs in order to be valid. This should not be impacted by my editor settings. All generated Makefiles should always use tabs.

https://openjdk.org/groups/build/doc/code-conventions.html#:~:text=Indentation%2C%20required%20use&text=Recipes%20in%20makefile%20rules%20must,around%20it%2C%20use%20additional%20tabs.

**Comment by dawnerd** [comment]
Seems like copilot uses spaces, no matter what I've tried it uses 4 spaces for indents.

**Comment by ulugbekna** [comment]
Thank you for filing the issue! How are you interacting with Copilot, ie through inline chat (cmd+i), panel chat (cmd+ctrl+i), or quick chat (cmd+shift+i) ? 

Trying to understand why Copilot wouldn't have workspace indentation info. If you could provide a detailed steps you take, that'd be very helpful. Possibly, your workspace files are indented with spaces? Open a random file in the workspace, you see at top bottom if tabs or spaces are used.
