### ISSUE TITLE
Responsible AI Service blocks all my prompts 

### ISSUE THREAD

**Issue by mariavpavlova** [microsoft/vscode-copilot-release#1699]
Type: <b>Bug</b>

Whatever I ask Copilot, I never get a response. It says "Sorry, the response was filtered by Responsible AI Service". All I asked was to help me finish a code snippet in the context of my notebook. I'm paying money for something that doesn't work. I don't see anything wrong with my prompts. Please fix this asap. 

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.34GB free)|
|Process Argv|--crash-reporter-id 78b8e886-69c2-4fee-9f97-f2a0859eed8f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
cc771715:31146322

```

</details>

**Comment by X1nLi** [comment]
Same happening

**Comment by Janus-Aurelius** [comment]
i think you should create a new chat and delete all the previous chat history, the copilot chat still remember the history chat, and it seems it only works the first time of each chat (with history erased), or it will get into a loop of denying every prompt even the suggested prompt of itself lol :D

![image](https://github.com/user-attachments/assets/ea018c10-798c-4f41-b3f8-daf861d01f54)

**Comment by X1nLi** [comment]
I've deleted the history, but it still doesn't show the answer. (Did I delete it the wrong way?)
<img width="981" alt="image" src="https://github.com/user-attachments/assets/33ac57de-57e0-49b9-9c72-fa1a2c38b508">

**Comment by X1nLi** [comment]
I rolled back the version of copilot. It's working.

**Comment by lramos15** [comment]
I recommend always keeping your VS Code up to date as well as your copilot chat extension. If you could include your logs via `CMD/CTRL + SHIFT + U` -> `GitHub Copilot Chat`. That would help us diagnose the issue.
