### ISSUE TITLE
Add ability to configure Copilot Chat responses with implicit query modifications

### ISSUE THREAD

**Issue by zefirka** [microsoft/vscode-copilot-release#170]
HI! First of all thanks for awesome product!

I'd like to receive maximally short answers from Copilot Chat, to avoid reading meaningless "As an AI programming assistant...", "I apologize if my previous response...", redundant code explanations and other blah-blah stuff, which is really annoying when I work intensively with Chat and asking simple short questions about libraries' methods or APIs. But currently I need manually ask for short answers in every query. That's really frustrating. 

I can see some simple solutions like config file where I can say "implicitly include this text into the end/start of every query", this will help me to preconfigure every query as currently model doesn't support state storage per user.

**Comment by digitarald** [comment]
Great points and I agree with the overhead of prose. Should be covered by https://github.com/microsoft/vscode-copilot-release/issues/180 and  https://github.com/microsoft/vscode-copilot-release/issues/179
