### ISSUE TITLE
Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again.

### ISSUE THREAD

**Issue by mag00s** [microsoft/vscode-copilot-release#1700]
Type: <b>Bug</b>

It never stops saying

Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again.

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.04GB free)|
|Process Argv|--crash-reporter-id 9de2f92a-5a93-40b7-8583-8a6109bff634|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1:31151523
5fd0e150:31146321

```

</details>

**Comment by X1nLi** [comment]
Same happening

**Comment by swmiller** [comment]
I keep receiving the same message whenever I ask Copilot to analyze my code or use the "/fix" command. Copilot keeps saying:

"Sorry, the response was filtered by the Responsible AI Service."

The setting to allow the use of public code is enabled, which is very annoying, especially since it is code that I wrote.

**Comment by X1nLi** [comment]
Could try rolling back Copilot version

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
