### ISSUE TITLE
no content being shown in answer.

### ISSUE THREAD

**Issue by pranaydubeymicrosoft** [microsoft/vscode-copilot-release#1702]
Type: <b>Bug</b>

Ask copilot any question and attach a file. Does not give any output.

Extension version: 0.22.2024100401
VS Code version: Code - Insiders 1.94.0-insider (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:10:18.718Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (10.62GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/pradubey/wd/LogicAppsUX --crash-reporter-id 5dc6e12f-65e3-4cb5-9bab-b82eef3e58d4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
f3je6385:31013174
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
i21gd607:31141543
iacca1:31150324
notype1:31143044
b50ed353:31138333
showchatpanel:31139797
f8igb616:31140137

```

</details>

**Comment by ReedGraff** [comment]
Duplicate: https://github.com/microsoft/vscode-copilot-release/issues/1723#issue-2568313295

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/1723
