### ISSUE TITLE
Never finishes "Filtering to most relevent information"

### ISSUE THREAD

**Issue by troykelly** [microsoft/vscode-copilot-release#1704]
Type: <b>Bug</b>

Ask @workspace something...
.... never get a response.

Extension version: 0.20.3
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Darwin x64 23.6.0
Modes:
Remote OS version: Linux x64 6.10.4-linuxkit
Remote OS version: Linux x64 6.10.4-linuxkit
Remote OS version: Linux x64 6.10.4-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|26, 38, 51|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id f6e7a5b4-1346-4dd7-8099-93bb11909a04|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 @ desktop-linux|
|OS|Linux x64 6.10.4-linuxkit|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 0)|
|Memory (System)|7.75GB (1.59GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Docker outside of Docker @ desktop-linux|
|OS|Linux x64 6.10.4-linuxkit|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 0)|
|Memory (System)|7.75GB (1.59GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3 @ desktop-linux|
|OS|Linux x64 6.10.4-linuxkit|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 0)|
|Memory (System)|7.75GB (1.59GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31125599
fje88620:31121564
iacca1:31138162

```

</details>

**Comment by mjbvz** [comment]
Please update to the latest copilot and VS Code versions and let us know if you still see the issue
