### ISSUE TITLE
Copilot is broken and does not respond

### ISSUE THREAD

**Issue by felixnext** [microsoft/vscode-copilot-release#1717]
Type: <b>Bug</b>

Not sure what happens here, but copilot is completely broken. I am on beta for o1, but it appears not to answer to any request anymore.
This seems like an error in the UI layer, where something cannot be rendered correctly?

Extension version: 0.22.2024100401
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|8, 5, 4|
|Memory (System)|64.00GB (1.00GB free)|
|Process Argv|--crash-reporter-id c4bc4dad-5b02-4dfb-9e6c-8136acdea4a2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
cc771715:31146322

```

</details>

**Comment by felixnext** [comment]
![2024-10-05 14 51 41](https://github.com/user-attachments/assets/bc9b94b9-1cc9-4281-9438-ec99ff4f9f42)
Here is a gif

**Comment by tboxfinn** [comment]
same problem, has anyone fixed it yet?

**Comment by LobaDK** [comment]
It's not a fix, but switching from the pre-release version to the release version appears to have reverted whatever breaking code they added. Currently, the release version is `v0.21.0`, which works for me.

**Comment by nanotecheg** [comment]
same problem, has anyone fixed it yet?

**Comment by ReedGraff** [comment]
Duplicate: https://github.com/microsoft/vscode-copilot-release/issues/1723#issue-2568313295
