### ISSUE TITLE
when hitting button to apply in editor new generated code into old code on the right, doesnt do anyth

### ISSUE THREAD

**Issue by phelix001** [microsoft/vscode-copilot-release#1718]
Type: <b>Bug</b>

when hitting button to apply in editor new generated code into old code on the right, it says it sending to copilot to merge, but then nothign happens and nothing to approve. I have to copy and paste. 

This happens quite often, and once it happens once, I have to quit out of vs code and restart to get it to start working again.

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux x64 6.11.0-061100-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 155H (22 x 4299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.95GB (22.87GB free)|
|Process Argv|. --crash-reporter-id e5d8647e-3dda-42bb-928d-123838c6c86f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by aeschli** [comment]
With the latest release you should now see an error dialog with more information
