### ISSUE TITLE
Generation of complete markdown in chat with code block break the ability to copy paste properly snippets

### ISSUE THREAD

**Issue by flegare** [microsoft/vscode-copilot-release#1719]
Type: <b>Bug</b>

Scenario A:

Step 1) In a typical project (python or web) ask to generate a readme.md
Step 2) It will proceed to generate the markdown and instructions in codeblock.
Step 3) Realise that only the code block instruction can be copy pasted into the readme.md vs the whole readme.md that was the initial intention.

Even if i ask to generate the markdown in a big codeblock. the ui will prevent and prefer to show individual code blocs.

Ideal state: Inner code blocks shouldn't be rendered and whole code blocs
Better ideal state: Allow copilot to create/modify files directly (uppon approval/review)
Alternative found : Ask to generate the markdown in a codeblock but escape the ` with \`, proceed to copy paste into the readme.md and find and replace the \` to `

Extension version: 0.21.0
VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 7, 8|
|Memory (System)|32.00GB (6.99GB free)|
|Process Argv|--crash-reporter-id 6129b443-99eb-4848-8c47-5676643ded35|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31150322
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/793
