### ISSUE TITLE
Add plugins to GH Copilot?

### ISSUE THREAD

**Issue by chagong** [microsoft/vscode-copilot-release#172]
Hi, I'm from Mircosoft DevDiv.
I learned it from Microsoft Build that all the copilot products are built on top of Copilot stack. And should support adding plugins.
Do we currently have plan for it?

I also can see you have some slash commands like '/vscode' and 'ext' for vscode questions and vscode extension development, which is quite cool. And I am also building dev tooling in Microsoft. Is it possible for us to add more slash commands like these?

**Comment by PaulLockett** [comment]
This would be cool!

**Comment by digitarald** [comment]
Closing as we since shipped extensions API for tooling
