### ISSUE TITLE
Get filtered by the Responsible AI Service for no reason

### ISSUE THREAD

**Issue by benja-iag** [microsoft/vscode-copilot-release#1722]
Type: <b>Bug</b>

Que problema tengo ahora? estoy obteniendo este error: index.js:15941 Uncaught TypeError: Cannot read properties of undefined (reading 'finish') at MicRecorder.getMp3 (index.js:15941:42) at stopRecord (Chat.js:48:8) at onClick (Chat.js:128:21) at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14) at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16) at invokeGuardedCallback (react-dom.development.js:20689:29) at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25) at executeDispatch (react-dom.development.js:32128:3) at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7) at processDispatchQueue (react-dom.development.js:32173:5) at dispatchEventsForPlugins (react-dom.development.js:32184:3) at eval (react-dom.development.js:32374:12) at batchedUpdates$1 (react-dom.development.js:24953:12) at batchedUpdates (react-dom.development.js:28844:12) at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3) at dispatchEvent (react-dom.development.js:30141:5) at dispatchDiscreteEvent (react-dom.development.js:30112:5) stopRecord @ Chat.js:48 onClick @ Chat.js:128 Show 15 more frames

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|. --crash-reporter-id f3deccd2-3fd5-473a-831a-ade9f5b44e73|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1cf:31151524
5fd0e150:31146321

```

</details>

**Comment by hediet** [comment]
Please add more details and ask your question in English. Thanks for understanding!
