### ISSUE TITLE
Too verbose and not value added

### ISSUE THREAD

**Issue by nick-toro** [microsoft/vscode-copilot-release#1724]
Type: <b>Bug</b>

Copilot is a waste of time.  In debugging code, it regurgitates code instead of concentrating on highlighting the fix.  I'm wasting more time reviewing code than this product is worth.  Very disappointing

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by jrieken** [comment]
Sorry, but we need more concrete input in order to help you here

**Comment by VadarVillage** [comment]
I don't know that it is a VSCode problem, but I agree that Co-Pilot has become too verbose and I only use it within VSCode.
- If I have some code open and I ask Co-Pilot a question, it will repeat the entire code block every time. It did not do this before...
- I typically start a new chat and use a prompt like "Do not repeat all of my code, just provide a small example of code to answer my question"
- This is a recent behavior. It was not like this a few months ago... I find it very frustrating to remind Co-Pilot to stop repeating my code

**If I have an editor open and I ask a question, Co-Pilot will repeat 200 lines of code with a small example somwhere in the middle.**

If I then remind it, yet again, not to repeat all the code - it will then repeat 200 lines of code again. It's quite frustrating.

**Comment by jrieken** [comment]
Closing as not actionable
