### ISSUE TITLE
Chat can't see code when text selection is too large

### ISSUE THREAD

**Issue by PhillippPatzelt** [microsoft/vscode-copilot-release#173]
Usually i want to refactor some parts of legacy code and want to optimize it.
When I write it in the chat window to optimize the code CoPilot sometimes see/know the code which is open and sometimes don't

**Comment by bigr00** [comment]
Same happens to me. Sometimes it sees the current file, while other times some past file.

More reliable way is to select the text and then Start Code Chat (command + I in Mac).

**Comment by kamranayub** [comment]
Just happened to me right now, but I updated to the nightly 30 mins ago. Yesterday it was working fine on the whole file without providing any selections. Thanks for the workaround!

**Comment by alexmerm** [comment]
Still happening for me. Its giving the following response every time:
```
I'm sorry for any confusion, but the text you provided, "python -pip", is not a valid Python command or code snippet.

If you're referring to Python's package manager, pip, it's used to install and manage software packages written in Python. You can use it to install packages from the Python Package Index and other indexes.

To install a package, you would use the command pip install package_name. To check the version of pip you have installed, you can use pip --version.

If you're trying to run a Python script with the command python script.py, you need to replace script.py with the name of your Python file.

If you need help with something else, could you please provide more details or context? I'm here to assist you.
```

**Comment by Festivejelly** [comment]
Yeah im getting this:

I apologize for any confusion, but as an AI developed by OpenAI, I don't have access to any files or external systems. I can only provide assistance based on the information you provide in the conversation.

By default it will only talk about code in my open window. It doesnt seem to be able to talk about the file as a whole even though it references it.

**Comment by IgorReidler** [comment]
Same here (version v1.147.0).
When prompted "help optimize this code" with main.py open (289 lines),  the response is showing "Used 1 reference main.py: 1-289"
Followed by:
I'm sorry for any confusion, but as an AI, I don't have the ability to directly access or interact with your files. I can provide assistance based on the information you provide to me. If you have specific parts of your code you'd like to optimize or questions about, feel free to share them and I'll do my best to help.

There are 2 issues here, as mentioned.
Main issue - copilot is unable to provide the required answers.
Secondary issue - copilot falsely declares it is referencing all lines of the code.
<img width="197" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/6610280/f7e549bb-0536-4405-b5f4-5c9886a44643">

**Comment by RaidFourms** [comment]
Any fix for it yet? I'm on prerelease v1.149.652 (chat is v0.12.2023120701)

**Comment by SametOzenc** [comment]
The same things happened to me.

**Comment by alessandro-neon** [comment]
Same here and I would like to point out that the misleading message is a horrible "solution".

I think it's ok to have limitations on the size of the selected code, but I see no reason not to make this clear to the user, as happens when we try to paste large content into the chat (in addition to passing the image that the copilot is programmed to lie).

**Comment by jecraig** [comment]
Copilot doesn't seem to check it's capabilities before making suggestions. It just recommended I use a gist link to share large code, but it's unable to source online files so it failed there. Really does look like there's no way to share a large context with copilot, but it would be nice if the bot wasn't giving garbage advice.

**Comment by roymasad** [comment]
Neither copilot or other free alternatives seems capable of referencing functions/files bigger than a certain size. I am supposing their prompt context token limit. But i have failed to find official posts online of the abilities and limits of copilot. I assuming for now that if a function is more than 200-250 lines or so it starts to stop being able to read it to analyze it, which is rather limiting for many scenarios. By default it looks for around 30 line references around your cursor position, but that would give it a very narrow vision of knowledge to answer things reliably in my opinion.

**Comment by digitarald** [comment]
Work is happening here #1083

**Comment by digitarald** [comment]
Duplicate of #1083
