### ISSUE TITLE
Cannot see outcome while: I'm refactoring my own code that I publish publicly

### ISSUE THREAD

**Issue by renoirb** [microsoft/vscode-copilot-release#1730]
Type: <b>Bug</b>

I'm trying to refactor code I publish publicly on GitHub. From HTML to markdown. And Co-Pilot refuses saying I shoudl re-prompt.

Here are a few requestIds:
- 401f715f-83b5-4ef6-b688-8dc871cc230b

Input file to use: [source](https://github.com/renoirb/site/blob/cf82398c/content/blog/2010/02/realisation-dune-application-dechange-de-cadeau-avec-red-lagence.md)

Extension version: 0.21.0
VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.33GB free)|
|Process Argv|--crash-reporter-id 709d17c1-02f0-4614-a36c-55452be4172d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31125599
pme_test_c:31118331
defaultse:31133495
ei213698:31121563

```

</details>

**Comment by mjbvz** [comment]
Can you please share an example prompt too so we can try to reproduce the issue

**Comment by renoirb** [comment]
Sorry for the delay. The only thing I can do with copilot is the auto complete, it's kinda nice. But nothing much.

Here is an example of something I've asked.

## 1. Find duplicate lines

PS: [Created Bug reporter with Diagnosis](https://github.com/) microsoft/vscode-copilot-release/issues/2100

(Yes, I could `sed` out commented lines, and `sort -u` in vim. But why not trying this)

In a [file on my project, with lines](https://github.com/renoirb/site/blob/69c4955a/static/_redirects) like the following, I asked:

> In the current file do you see matches of the same URL on the first part of the space separated files
>
> <URL> <Redirect URL> <Status Code>

And it blocked what it was doing with 

> Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. (...)

I wonder what it's supposed to filter. That must not be an easy problem to solve: Trying to block Intellectual Property misuse.
![Image](https://github.com/user-attachments/assets/0926e98d-258c-4f55-9fec-b66fbc3fee5f)

```
#
# Redirects
#
# Format:
#
# [source] [destination] [code?]
#
# source required
#     A file path.
#     Can include wildcards (*) and placeholders.
#     Because fragments are evaluated by your browser and not Cloudflare’s network, any fragments in the source are not evaluated.
#
# destination required
#     A file path or external link.
#     Can include fragments, query strings, splats, and placeholders.
#
# code default: 302
#     Optional parameter
#
#
# A project is limited to 2000 static redirects and 100 dynamic redirects,
# for a combined total of 2100 redirects.
# Each redirect declaration has a 1000-character limit.
#
# Bookmarks:
# - https://developers.cloudflare.com/pages/configuration/redirects/
#
# REWRITING URL TO SOMETHING BETTER ----------
#
/blog/2009/08/inexis-net-2004-sur-flickr/ /blog/2009/08/realisation-site-web-inexis-solution-web-2004/ 301
/blog/2009/11/realisation-du-site-et-de-limage-«branding»-de-beebox-2008/ /blog/2009/11/realisation-du-site-et-de-image-produit-de-beebox/ 301
/blog/2009/11/realisation-du-site-et-de-limage-%c2%abbranding%c2%bb-de-beebox-2008/ /blog/2009/11/realisation-du-site-et-de-image-produit-de-beebox/ 301
/blog/2010/01/le-defi-«project52»-un-billet-par-semaine-minimum/ /blog/2010/01/le-defi-project52-un-billet-par-semaine/ 301
/blog/2010/01/le-defi-%c2%abproject52%c2%bb-un-billet-par-semaine-minimum/ /blog/2010/01/le-defi-project52-un-billet-par-semaine/ 301
/blog/2010/01/le-manifeste-open-cloud-pour-standardiser-linformatique-«dans-les-nuages»/ /blog/2010/01/le-manifeste-open-cloud-pour-standardiser-info-nuagique/ 301
/blog/2010/01/le-manifeste-open-cloud-pour-standardiser-linformatique-%c2%abdans-les-nuages%c2%bb/ /blog/2010/01/le-manifeste-open-cloud-pour-standardiser-info-nuagique/ 301
/blog/2010/02/realisation-dune-application-dechange-de-cadeau-avec-red-lagence-le-«club-echangiste»-2009/ /blog/2010/02/realisation-dune-application-dechange-de-cadeau-avec-red-lagence/ 301
/blog/2010/02/realisation-dune-application-dechange-de-cadeau-avec-red-lagence-le-%c2%abclub-echangiste%c2%bb-2009/ /blog/2010/02/realisation-dune-application-dechange-de-cadeau-avec-red-lagence/ 301
```

**Comment by renoirb** [comment]
Another example of usage was a request to make manipulations to a Markdown file that has HTML.

Basically doing what [this commit does](https://github.com/renoirb/site/commit/193b238d)

I started using ClaudeAI instead to do the conversion instead.

PS: I understand responsible AI. But that code and article is something I wrote many years ago, [it's public](https://renoirboulanger.com/blog/2012/08/comment-je-valide-et-convertit-des-documents-html-trop-charges-ou-provenant-de-microsoft-word-en-html-valide-et-simplifie/) some for many years, even two decades sometimes.

The prompt was something like:

```
Adjust contents of text files and reorganize contents from Markdown to an uniform format

Key Tasks: (1) Reformat HTML content to Markdown (2) Normalize the provided front matter (3) Ensure title hierarchy makes sense when possible (4) Standardize front matter with the a provided key order (5) Take into account images and links to them into a new pattern of provided HTML tags (6) When you see at the top of the content an image, that's going to be the page's "cover image" that should be used for front matter coverImage that'll describe further. For each file you rewrite, show your writing as artifacts as Markdown.
```

and a few more lines like this.

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
