### ISSUE TITLE
Answer went into an infinite loop

### ISSUE THREAD

**Issue by nox-interior** [microsoft/vscode-copilot-release#1731]
Type: <b>Performance Issue</b>

I asked a question to clarify the previous ones, which, by the way were not great, and it went into an infinite loop of the "Example implementation"  that I stopped manually. 

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Linux arm64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (2 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.81GB (1.03GB free)|
|Process Argv|--crash-reporter-id b45b764f-327b-401a-a222-a565c829b58a|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (camel_to_snake.c - Untitled (Workspace) - Visual Studio Code)
|    Folder (42_Exams): 34 files
|      File types: c(29) txt(1)
|      Conf files:
|    Folder (42-EXAM): 1147 files
|      File types: c(250) txt(202) sh(129) DS_Store(46) cpp(27) hpp(18) h(10)
|                  md(4) out(4) trace(3)
|      Conf files: makefile(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by ulugbekna** [comment]
Thank you for filing the issue!

Do you still have that chat in chat history? Screenshots would help with debugging.

**Comment by nox-interior** [comment]
Hi! Thanks! I got some screenshots, I am not sure they are useful, I hope they help, let me know if those are ok, please :)
![Screenshot from 2024-10-06 15-04-18](https://github.com/user-attachments/assets/75bf0643-f2ec-48c1-8227-60a677254941)
![Screenshot from 2024-10-06 15-04-36](https://github.com/user-attachments/assets/0019c603-77d0-42d6-9192-17d8b21931e2)
![Screenshot from 2024-10-06 15-03-37](https://github.com/user-attachments/assets/a5e099af-60ce-4187-86bc-de547eb1e542)

**Comment by ulugbekna** [comment]
Thank you for the screenshots!

Can you reproduce this behavior often or was it a one-time thing? If you can reproduce, could you tell use steps how you do it?
