### ISSUE TITLE
Incorrect off-topic detection for arithmetic

### ISSUE THREAD

**Issue by AuracleTech** [microsoft/vscode-copilot-release#174]
GitHub Copilot
```
Hi @AuracleTech, how can I help you?
```

AuracleTech
```rs
On my selection why does copilot recommends this : cost / (2.0 * ti.rows as f32)
instead of this : cost / ti.rows as f32
```

GitHub Copilot
```
Sorry, but I can only assist with programming related questions.
```

_???_

**Comment by sharonlo** [comment]
@AuracleTech  thanks for your patience. We've deployed an update that hopefully addresses this. We're still working on better understanding of context but please let us know if you're still hitting these issues!

**Comment by digitarald** [comment]
Closing for now, as a new offtopic detection got deployed and your provided questions pass. Please file new issues for follow-up reports.
