### ISSUE TITLE
Answers disapering

### ISSUE THREAD

**Issue by Alex-R-Underwood** [microsoft/vscode-copilot-release#1742]
Type: <b>Bug</b>

answer is dissapering after a second and all that is displayed is "GitHub Copilot" Not clickable or anything.

Extension version: 0.22.2024100401
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.94GB (2.43GB free)|
|Process Argv|--crash-reporter-id d583b9fc-8fd4-42d3-a4bf-9eea25391d7b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
cc771715:31146322

```

</details>

**Comment by DevAzn** [comment]
This is happening to me as well

**Comment by stollero** [comment]
Same issue, rolling back to stable Release helped.

```
## Copilot

- Version: 1.235.1137
- Build: nightly
- Editor: vscode/1.94.0
```

**Comment by Petemir** [comment]
Have the same problem. Additionally, if I try to give chat feedback, I get the following error:

```
Converting circular structure to JSON --> starting at object with constructor 'H0e' | property 'c' -> object with constructor 'iri' --- property 'd' closes the circle
```

**Comment by MaxOstrowski** [comment]
Same problem here. Given that CoPilot is a paid feature, please fix.

> Version: 1.94.0
> Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
> Date: 2024-10-02T13:08:12.626Z
> Electron: 30.5.1
> ElectronBuildId: 10262041
> Chromium: 124.0.6367.243
> Node.js: 20.16.0
> V8: 12.4.254.20-electron.0
> OS: Linux x64 6.8.0-45-generic snap

**Comment by roblourens** [comment]
Merging to https://github.com/microsoft/vscode-copilot-release/issues/1723
