### ISSUE TITLE
copilot text disappears

### ISSUE THREAD

**Issue by sorrento** [microsoft/vscode-copilot-release#1746]
Type: <b>Bug</b>

since the recent update. I cannot use it 

Extension version: 0.22.2024100701
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.24GB free)|
|Process Argv|--crash-reporter-id 7c69f056-13e4-45bb-8662-e95def20f859|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31150322
notype1cf:31151524
cc771715:31146322

```

</details>

**Comment by JM9CrazyCode** [comment]
I just had this same problem moment ago, then I found out I was using pre-release version of the extension.
Switched back the version to Release then the chat works again.(v.0.21.0)
![image](https://github.com/user-attachments/assets/b56baf64-0a5d-4039-8a49-6e225b790d50)

**Comment by aiday-mar** [comment]
Hi could you please include a screen recording for us to better understand the problem?

**Comment by qtchaos** [comment]
![gh_example](https://github.com/user-attachments/assets/0f0941e2-23c8-4740-a4c0-5cd43f0674ec)

**Comment by roblourens** [comment]
This should be fixed now
