### ISSUE TITLE
ahmedabdelhady240697@gmail.com

### ISSUE THREAD

**Issue by AhmedAbdelhady24** [microsoft/vscode-copilot-release#1748]
- Copilot Chat Extension Version:
- VS Code Version: 1.94.0
- OS Version: ubuntu 24.04.1 LTS
- Logs:

Steps to Reproduce:

1.open chat sidebar 
2. send prompt 
3. after i receive the reply the response disappears 
![image](https://github.com/user-attachments/assets/2d05d8ac-415d-4860-ac40-ab91c59871ef)
[Screencast from 2024-10-07 13-33-02.webm](https://github.com/user-attachments/assets/5f5ea8ee-4070-4576-aba9-fb8f943253bb)

**Comment by AhmedAbdelhady24** [comment]
i tried switching between release and pre-release version but same bug still persists

**Comment by roblourens** [comment]
Had an issue like this that was fixed- lmk if you still see it
