### ISSUE TITLE
Generate code inplace stopped working

### ISSUE THREAD

**Issue by bebuch** [microsoft/vscode-copilot-release#1749]
Version: 1.94.0 (user setup)
Commit: d78a74bcdfad14d5d3b1b782f87255d802b57511
Date: 2024-10-02T13:08:12.626Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Name: GitHub Copilot
Id: GitHub.copilot
Description: Your AI pair programmer
Version: 1.235.0
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot

In the past, I was able to use ctrl+i in the editor window to enter a prompt that then generated code inplace at this location. Now the code is generated in a new tab and the entire file is also re-output in this tab.

Is this new behaviour intentional? Can I restore the old behaviour?

**Comment by aeschli** [comment]
> Now the code is generated in a new tab and the entire file is also re-output in this tab.

That should not happen. Can you give an example of a prompt where that happens?

**Comment by bebuch** [comment]
I can no longer reproduce this at the moment. Something probably got stuck and was solved by an update.
