### ISSUE TITLE
rate limits

### ISSUE THREAD

**Issue by spicy-bear** [microsoft/vscode-copilot-release#1753]
Type: <b>Bug</b>

rate limits even after waited times. 

Extension version: 0.21.0
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lramos15** [comment]
Please give VS Code insiders + pre-release a try. We've done some token optimizations there that should make it less likely for you to hit the rate limit.
