### ISSUE TITLE
It refuses to do anything, it is completely and utterly useless, I have no idea what changed but it didn't used to act like this.

### ISSUE THREAD

**Issue by corvoswsattano** [microsoft/vscode-copilot-release#1765]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Ask it to analyze a text file with a selection of network packets from a Wireshark pcapng file
2. It just says "Sorry, I can't assist with that."

I am trying to use it to see if it can notice a needle in a haystack, I'm having network issues and I can't manually read 1,512 packets, it's worked for me before so I have no idea why it isn't now.

**Comment by ulugbekna** [comment]
Could you please provide files to reproduce? Possibly, files are large and fill up context window
