### ISSUE TITLE
Freezing and I need to force shutdown vscode 

### ISSUE THREAD

**Issue by Sopheakzz** [microsoft/vscode-copilot-release#1778]
Type: <b>Performance Issue</b>

Sometimes when I open copilot chat tab ,  it wouldn't load and just froze and this usually happen I open freshly open vscode and go to copilot chat 

Extension version: 0.21.1
VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Linux x64 6.8.0-45-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 3990)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|15.00GB (9.00GB free)|
|Process Argv|--crash-reporter-id 81f519d9-9e9d-4143-bdb4-3ec58bb226a1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   184	 36204	code main
    0	    46	 36208	   zygote
    2	   169	 36245	     gpu-process
    0	    46	 36209	   zygote
    0	     0	 36211	     zygote
   12	   599	 36263	window [1] (pdf_helper.php - InvoicePlane - Visual Studio Code)
    0	    61	 36247	   utility-network-service
    1	   415	 36343	extensionHost [1]
    0	   138	 36443	     electron-nodejs (intelephense.js )
    0	   783	 36444	     /home/sopheakss/.vscode/extensions/devsense.intelli-php-vscode-0.12.15062-linux-x64/out/server/intelliphp.ls
    0	   261	 36470	     /home/sopheakss/.vscode/extensions/devsense.phptools-vscode-1.51.16099-linux-x64/out/server/devsense.php.ls
    0	    92	 36564	     electron-nodejs (index.js )
    0	    92	 36608	     /usr/share/code/code /usr/share/code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=36343
    0	    61	 36609	     /usr/share/code/code /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=36343
    0	   123	 36754	     electron-nodejs (tsserver.js )
    0	   138	 36755	     electron-nodejs (tsserver.js )
    0	    92	 36770	       electron-nodejs (typingsInstaller.js typesMap.js )
    0	    77	 36817	     /usr/share/code/code /usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=36343
    0	    61	 36818	     electron-nodejs (server.js )
    0	    61	 36826	     electron-nodejs (server.js )
    0	   123	 36353	shared-process
    0	     0	 36902	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 36903	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    92	 36354	fileWatcher [1]
    0	    92	 36410	ptyHost
    0	     0	 36426	     /usr/bin/bash --init-file /usr/share/code/resources/app/out/vs/workbench/contrib/terminal/common/scripts/shellIntegration-bash.sh
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (pdf_helper.php - InvoicePlane - Visual Studio Code)
|    Folder (InvoicePlane): 3521 files
|      File types: php(1971) js(159) txt(145) json(89) ttf(70) html(67) md(64)
|                  htm(59) scss(50) sql(38)
|      Conf files: dockerfile(6) grunt.js(1) package.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
showchatpanel:31153267
cc771715:31146322

```

</details>

**Comment by aiday-mar** [comment]
possibly related https://github.com/microsoft/vscode-copilot-release/issues/1423

**Comment by syedahmedhaidershah** [comment]
Samething happens with me.
Whether I use the chat drop down or from Chat, the generation halts without any message or error, just a blank process that took place.

Started just today.

![Image](https://github.com/user-attachments/assets/502996f0-36a5-47b2-ba69-c856f2cb3434)

**Comment by roblourens** [comment]
We fixed an issue like this earlier this week so please make sure you're on the latest update of the extension

**Comment by roblourens** [comment]
@syedahmedhaidershah I see you leaving this comment on different unrelated issues, you can open your own issue if needed.

@Sopheakzz I don't understand the full issue, please describe in detail

**Comment by Sopheakzz** [comment]
When I freshly opened Vscode then go chatgpt  tab sometimes it's froze like the image below: 
![Image](https://github.com/user-attachments/assets/e348a719-7576-4cd8-b697-a4ce3d6ca433)

Here's the crash log : 
https://termbin.com/j4xt
