### ISSUE TITLE
Inline Copilot Chat with code selection incorrectly aborts when hitting "```"

### ISSUE THREAD

**Issue by 19h** [microsoft/vscode-copilot-release#178]
- VS Code Version: Version: 1.79.0-insider
- OS Version: macOS 13.4 Beta (22F5027f)
- Logs:

Reproduction:

1. Select code block with "```" in a string.
2. Converse with Copilot.

Presumably, Copilot will interpret the input text as markdown and incorrectly interpret the sequence as end-of-code-block.

![CleanShot 2023-05-30 at 18 53 16@2x](https://github.com/microsoft/vscode-copilot-release/assets/280212/d1f00b15-938b-41f7-8523-1cd6e0cb0e10)

**Comment by jrieken** [comment]
Seems to be working by now (this issue is kinda old)

Steps

* have the code below
* ask it to rename `source` to `code`

```
export function asCodeBlock(source:string):string {
    return '```' + source + '```';
}
```

https://github.com/microsoft/vscode-copilot-release/assets/1794099/2952ee6f-b42d-4fac-b379-cc2a7b72e6f2
