### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Hesham942** [microsoft/vscode-copilot-release#1793]
- Issue Type: `Performance`
- Extension Name: `copilot-chat`
- Extension Version: `0.22.2024100702`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.94.1`

:warning: Make sure to **attach** this file from your *home*-directory:
[GitHub.copilot-chat-unresponsive.cpuprofile.txt](https://github.com/user-attachments/files/17316783/GitHub.copilot-chat-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rebornix** [comment]
![Image](https://github.com/user-attachments/assets/c4d44c04-1516-46af-af32-cdaef576d9cf)


From the perf log it seems the extension host is not blocked or busy, can you provide more details on what you were seeing?
