### ISSUE TITLE
Stuck at 'Generating' - With o1-preview model

### ISSUE THREAD

**Issue by pkuppens** [microsoft/vscode-copilot-release#1804]
Type: <b>Bug</b>

Probably one of the most complex pieces of code in my project, and a complex query on top of it, but this request was 'Generating', after finding 18 references in code, for a few minutes, before I cancelled:

@workspace /explain Explain this code with inline code comments. Suggest how I can refactor the code to Clean Code principles with inline #TODO: items

Extension version: 0.21.1
VS Code version: Code 1.94.1 (e10f2369d0d9614a452462f2e01cdc4aa9486296, 2024-10-05T05:44:32.189Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.90GB (10.27GB free)|
|Process Argv|--folder-uri file:///d%3A/Repos/Rentapin/paklijsten_generator --crash-reporter-id 7a54e7d0-2187-4543-aa4f-61f4ffc9c709|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31134774
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31150323
notype1:31151523
cc771715:31146322

```

</details>

**Comment by pkuppens** [comment]
Suggested solutions:

1. expectation management, tell if it is supposed to take seconds, minutes, or even more
2. progress reporting, e.g. count the streamed bytes, compare to expected/maximum count, report in progress bar

**Comment by pkuppens** [comment]
For reference, GPT-4o model takes seconds to start

**Comment by lramos15** [comment]
1. O1 can take upwards of 10 minutes
2. O1 does not support streaming at this time so there is nothing we can show you

**Comment by lramos15** [comment]
I agree. You only get a dozen requests or so a day to O1 due to the high compute costs. It is best for complex and difficult tasks that you find 4o is not capable of answering well. It is something you have to be willing to wait for the response for, especially if a lot of context is being included.
