### ISSUE TITLE
Question deflection

### ISSUE THREAD

**Issue by lcpichette** [microsoft/vscode-copilot-release#181]
- Version: 1.79.0-insider (Universal)
- Commit: 667d4629dee90744edd5054f13bc2452c8c14490
- Date: 2023-05-29T05:24:34.999Z (1 day ago)
- Electron: 22.5.3
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin arm64 22.4.0

Issue: When I ask Copilot to generate unit tests for selected code, it doesn't answer the question, and instead gives me a suggestion for a new question.

Steps to Reproduce:

1. Create Angular@14 project with Jest@28
2. Select code snippet
3. Ask GitHub Copilot "Generate unit tests for the selected code"

Code is smudged to protect the security codebase I'm working on, but it shows that code is selected, and the response from GitHub Copilot being a redirect-prompt of: "How can I install Jest in my project?"
![Screenshot 2023-05-30 at 11 13 14 AM](https://github.com/microsoft/vscode-copilot-release/assets/54318714/bf6994de-1f35-4a64-8db0-f968b2255e59)

**Comment by lramos15** [comment]
That blue piece is a actually a follow up question (basically a question that Copilot thinks you might want to ask next). It looks like copilot chat didn't respond at all. Is there anything in the `GitHub Copilot Chat` output channel?

**Comment by lcpichette** [comment]
Is that something different from what's shown in the image? If so, how can I access it?

**Comment by lramos15** [comment]
This is likely fixed. Can you confirm if you're still seeing the issue?
