### ISSUE TITLE
AI Responsible Use Service Keeps Filtering Normal Responses

### ISSUE THREAD

**Issue by DylanDevelops** [microsoft/vscode-copilot-release#1817]
- Copilot Chat Extension Version: v0.21.1
- VS Code Version:
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.1.0

- OS Version: macOS Sequoia 15.1 Beta (24B5055e)
- Logs: Not sure where you find this.

All day today, while working on a Next.js project, I have been getting responses filtered that are completely harmless, such as help with creating a function that does something simple. How do I stop these from happening?

![Image](https://github.com/user-attachments/assets/c064cbcd-d3b4-4acf-b470-e8e267459f5e)

**Comment by isidorn** [comment]
@albaloo might be able to help here

**Comment by DylanDevelops** [comment]
Let me know! Thank you!

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
