### ISSUE TITLE
Not able to get the reponse, looks something is blocking the request or IP

### ISSUE THREAD

**Issue by girishvisaero** [microsoft/vscode-copilot-release#1824]
Type: <b>Bug</b>

I just started working around, and i was testing but facing this issue again and again, the issue is not able to get the repsones looks something is blocking my IP or copilet ping. 

Extension version: 0.22.2024100702
VS Code version: Code 1.94.0 (Universal) (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 363a966b-556d-4067-8eae-36241e49d97d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1:31151523
controlgs:31153265
5fd0e150:31155592

```

</details>

**Comment by joyceerhl** [comment]
Please update to the latest VS Code stable build (1.94.2) and let us know if it still repros.

**Comment by girish-chaudhari** [comment]
I have latest vs code upgraded but facing the same issue. When I try to use vs code copilot it’s like a proxy or dns issue. I am happy to use this extension cause it helped me a lot currently using free first month premium and going to subscribe the plan due to dns or the same issue I’m not able to continue or use this extension

**Comment by lramos15** [comment]
Can you include a screen recording and your logs via CMD / CTRL + SHIFT + U -> GitHub Copilot Chat
