### ISSUE TITLE
Have a more visible separator between messages

### ISSUE THREAD

**Issue by andrewcbuensalida** [microsoft/vscode-copilot-release#1827]
In the chat view, it's hard see where my message starts. Please make it more visible maybe by having alternating colors between the messages.

![Image](https://github.com/user-attachments/assets/7f309738-c7f1-4e82-9206-f1e43e8b3c69)

**Comment by roblourens** [comment]
We did just change this recently, giving it a more lightweight feel without a separator, the idea being that the toolbar provides some space between a request+response and the next request. Maybe there's room for more tweaking.

**Comment by isidorn** [comment]
This is better in the latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
 I will go ahead and close this issue.
Thank you for your understanding
