### ISSUE TITLE
Tools sample seems to be broken by latest pre-release (v0.22.2024101101 (pre-release))

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-copilot-release#1830]
- Copilot Chat Extension Version: v0.22.2024101101 (pre-release)
- VS Code Version: 1.95.0-insider
- OS Version: Mac Sequoia 15.0.1
- Logs: N/A

Steps to Reproduce:

1. Build the tools sample here: https://github.com/microsoft/vscode-extension-samples/tree/roblou/tool-user/chat-tools-sample
2. Prompt: "@tools How many tabs do I have"
3. ![Image](https://github.com/user-attachments/assets/a60e8d15-bab9-4a64-b80d-3684afccd49c)

This seems to be broken by latest pre-release.

CC @roblourens

**Comment by roblourens** [comment]
Sorry, there has been some churn in the API, it's possible that the sample was out of sync with the released insiders. Should be good now but I'm about to make more breaking API changes too
