### ISSUE TITLE
Cannot Properly Render Complex README.md markdown.

### ISSUE THREAD

**Issue by mrteye** [microsoft/vscode-copilot-release#1844]
Type: <b>Bug</b>

Without giving you my exact markdown file I cannot give you the steps to reliably reproduce this script.     The render broke out at several points.  I had the AI remove the broken section and it broke again at a future section.  Once after an "Example module srtructure:"  and once after a JSON ``` code snippet.  I am working through it now, but I anticipate I will have to find a new way to get the markdown from the AI.

Extension version: 0.21.1
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.10.10-200.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (7.64GB free)|
|Process Argv|--crash-reporter-id 0ebb79f2-2a0f-4483-8f92-eef3b1426660|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
cp13037c-prod:31155933
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1:31157159
controlgs:31153265
5fd0e150:31155592

```

</details>

**Comment by mrteye** [comment]
I figured it out.  The render of the README.md file breaks down at the code snippets: ```example```.  My workaround was to have the AI escape the code snippets which renders much better and in one file section.  I'll have to search and replace or have the AI fix the escaping creating the README.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/793
