### ISSUE TITLE
Sorry, your request was rate-limited. Please wait 3 seconds before trying again. gives error

### ISSUE THREAD

**Issue by hannaszalai** [microsoft/vscode-copilot-release#1846]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2627. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
