### ISSUE TITLE
Copilot Chat Raises Error when Given README file contents

### ISSUE THREAD

**Issue by boveus** [microsoft/vscode-copilot-release#185]
- VS Code Version: Version: 1.79.0-insider (Universal)
- OS Version:  Darwin arm64 22.5.0
- Logs: GitHub Copilot
unhandled status from server: 400 Bad request: bad request: role must be "user", got "assistant"

Steps to Reproduce:

1. Paste the contents of the README file [here](https://github.com/github/onslaught/tree/master#readme) into a chat prompt
2. View the response.

It also appears to have trouble parsing this particular README file, as it cannot answer particular questions about it.
1.  Ask Copilot questions about the README file such as "according to the README.md file for this project, how do I run the test suite?"
2. View the response.

**Comment by digitarald** [comment]
Afaik the issue is with large requests, but need to confirm.

**Comment by d3vilh** [comment]
> Afaik the issue is with large requests, but need to confirm.
probably, but it works fine with the larger requests before.
Have the same issue.

**Comment by bhavyaus** [comment]
Verified that we're now seeing the below error message when context is too large: 
<img width="261" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/25044782/2cae80b4-7ee3-427d-8de4-cdf2ec83b0c6">
