### ISSUE TITLE
Experiences and challenges in using chat to modify projects and test linguistic and technical limitations.

### ISSUE THREAD

**Issue by YhonaPeguero** [microsoft/vscode-copilot-release#187]
I have been using the chat to modify some projects and to test some language and technical limitations in the chat. Unfortunately there is a big difference when you write in Spanish as opposed to English, sometimes it doesn't even answer your questions when you write in Spanish.

He has also had many problems with not being very specific when you write him a query (regardless of the language, either English or Spanish). He is usually fast but his answers are not so accurate in many occasions.

**Comment by Jenverse** [comment]
@YhonaPeguero Thank you for your feedback. Would it be possible for you to share some specific examples with us on langugae support and inaccurate answers?

**Comment by bhavyaus** [comment]
Closing. Please feel free to open another issue if you're still seeing this issue.
