### ISSUE TITLE
VSCode can't save file. Notification "Saving '+page.svelte': Waiting for Inline Chat changes to be Accepted or Discarded..."

### ISSUE THREAD

**Issue by logicthread** [microsoft/vscode-copilot-release#1872]
VSCode is stuck when i applied the code in editor, which had 0 suggestion/changes. When trying to save the file i am stuck with the notification "Saving '+page.svelte': Waiting for Inline Chat changes to be Accepted or Discarded..."

- Copilot Chat Extension Version: Latest
- VS Code Version: Latest
- OS Version: Ubuntu 24.04
- Logs:

Steps to Reproduce:

1. apply the code to editor once, accept all changes.
2. generate a new response from prompt with exact same code as the first time.
3. apply code in editor
4. try to save ( Ctrl + S or otherwise )

**Comment by jrieken** [comment]
So, is it that no more inline chat UI is visible at that point?

**Comment by logicthread** [comment]
> So, is it that no more inline chat UI is visible at that point?

when i try to save after applying code in editor, if there are no changes to be applied sometimes gets stuck while being saved, sometimes doesn't let new code apply. attaching video for reference first for latter case. 

https://github.com/user-attachments/assets/e717e62c-81ba-408c-8040-674bf5503d1b

**Comment by jrieken** [comment]
![Image](https://github.com/user-attachments/assets/7e748f05-fc2b-4df9-9558-16b14d5e4ee2)

**Comment by jrieken** [comment]
@aeschli - it looks like a bulk edit is being previewed but not finished. Do you have a clue why that is?

**Comment by jrieken** [comment]
Well, it's headless so no UI at all... I guess what happens is that no edits happens, so no accept/reject shows. Now, the UI that shows "no results, refine query" is invisible and therefore the run hangs

**Comment by jrieken** [comment]
I can add logic for the "no edits" case but @aeschli you should also drive the controller from those messages. Like, add accept/discard to the modal and hook those up the controller methods

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/blob/f5b85429639e2ade384f0a77e439cce05898c5c6/src/vs/workbench/contrib/chat/browser/actions/codeBlockOperations.ts#L273

@aeschli Are you sure no edits happen? Could you be pushing no-op edits?
