### ISSUE TITLE
Questions with an open test file

### ISSUE THREAD

**Issue by scvsoft-jjevangelista** [microsoft/vscode-copilot-release#1879]
Type: <b>Feature Request</b>

If I ask a question with a test file in my editor, it tries to write a whole test suite instead of answering my question. I would like to disable that, or better only generate the test suite if I ask for that

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 23.5.0
Modes:
Remote OS version: Linux x64 6.1.91-060191-generic
Remote OS version: Linux x64 6.1.91-060191-generic

**Comment by isidorn** [comment]
This issue does not satisfy the minimal quality standards for an issue that we would like to see in this repository.
Reproducible steps using English with latest VS Code are what helps us a lot. So please feel free to open a new issue with steps. 
Thus I will go ahead and close this one. 
Thank you
