### ISSUE TITLE
The context sent to GitHub Copilot Chat should be clear

### ISSUE THREAD

**Issue by sbracegirdle** [microsoft/vscode-copilot-release#188]
There appears to be a great amount of confusion (see #173) as to what editor/project context is provided to Copilot Chat. I've heard it mentioned that it can "see" all open files, but in my testing it appears to only see the current active file OR the selected text. For example if I have two files open `TodoList.js` and `TodoList.test.js` , if `TodoList.js` is currently active and I ask it to explain the test cases written in TodoList.test.js , it will refuse. In some cases it will hallucinate the contents of other files (see #184).

This is problematic as users expect Copilot Chat to understand the broader context of their project. For example, if our tests are written in a particular style, and I ask Copilot to generate tests for `TodoList.js`, it will use a generic test style rather than the tests demonstrated in `TodoList.test.js`.

In addition to the many suggestions (see #14, #16, #32, #61, #62, #95) to increase context, my proposal is that we make it clearer exactly what context is provided to Copilot Chat. For example, perhaps at the start of the chat response, it lists the files and lines provided:

```
GitHub Copilot
Context: TodoList.js:20-40

... agent response here ...
```

I believe this added feedback will help users to understand how the agent is responding to their input, and therefore lead to a more positive interaction with your product.

**Comment by digitarald** [comment]
@sbracegirdle great research on related issues. We did have related UX discussions that I'll pull in this issue.

**Comment by NikiLentz** [comment]
sometimes it doesn't even seem to have context for the open file. For example i have an interface called Ship  in a file in Typescript. 
I have it open and in focus.

I ask: "Can you generate a few ships for me"

What i expect a few random initialized calls for ships so i can test a small interface.

What i get is either:
1) The random calls with almost completely halluzinated attributes or
2) "I can only help with programming questions".

At this point i just use it as chatgpt in editor, which is fine, but i am missing a lot of the promised advantages over just using chatgpt in a different window.

**Comment by digitarald** [comment]
Closing as file context is shown via _"used referenced"_ since Copilot Chat 0.10 (part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_workspace)).

<img width="641" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/eb41cc4e-2c4a-4376-bfbf-e39f295380fa">

Please give it a try and file new issues for any follow-up feedback!

**Comment by sbracegirdle** [comment]
Wow, thanks for taking the feedback on board!

**Comment by jyavorska** [comment]
What's still a bit unclear is why sometimes it included a reference or not. Sometimes I ask a question with a single file open and the entire text highlighted, but there's no context. It's hard to predict what it's going to do or why.
