### ISSUE TITLE
After pay 10/month and setup, I cannot find copilot chat in the view menu and right click menu

### ISSUE THREAD

**Issue by kskennyus** [microsoft/vscode-copilot-release#189]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by kskennyus** [comment]
After paymnet 10/month and setup copilot extension, i cannot find copilot chat in either view menu or right click menu inside editor

**Comment by jensd0e** [comment]
You need to sign up for chat here: https://github.com/github-copilot/chat_waitlist_signup

**Comment by Cosmo997** [comment]
I have the same problem, and i'm already whitelisted

**Comment by kskennyus** [comment]
I solved the problem by reinstall pre-release https://aka.ms/VSXGHCopilot
