### ISSUE TITLE
Public code matching should reference the public code

### ISSUE THREAD

**Issue by jonasatgit** [microsoft/vscode-copilot-release#1892]
Type: <b>Feature Request</b>

Public code matching should reference the public code. I could then check the public code to properly rephrase my question or ask. It woul also be helpful to be able to mark public code as demo or owned code. Because in most of the VSCode demos the code is public and the demo is broken because of the blocked response.

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.27723
Modes:

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
