### ISSUE TITLE
[BUG] Sometimes the Inline Chat is getting stuck and doesn't go away until a full window reload

### ISSUE THREAD

**Issue by GuyGooL5** [microsoft/vscode-copilot-release#19]
- OS: Windows 11
Sometimes the inline Chat (`Ctrl + I` for Windows) is getting stuck. 
It's not responding and sticks to the screen at the same absolute screen position even when switching tabs.
It happens when It's thinking and I try to close it in this while.

Steps to Reproduce:

1. Start a chat session in the code (`Ctrl + I`)
2. Enter a prompt that suggests a code edit (with a split window).
3. Ask another question and immediately close by pressing `Esc`. 
4. Now it sometimes gets stuck. Happens to me a lot with python files `.py` (if that matters).

**Comment by kittymyt** [comment]
It always stuck in "thinking" and no responses anymore after I asked 2 or 3 questions. It can only get back to life when I clear the chat and start a new conversion. 

It seems the maximum num of chat available for each 'thread' is 2 or 3

**Comment by pan93412** [comment]
I also encountered it. Screencast here:

https://github.com/microsoft/vscode-copilot-release/assets/28441561/4a709ebb-20c0-43a6-9f20-738a8b1fb1a2

**Comment by pan93412** [comment]
Seems like it has been fixed in `v0.1.2023060101` 🎊 !

**Comment by digitarald** [comment]
Please re-open it still happens for you
