### ISSUE TITLE
Copilot quick actions hide other quick actions and refactorings

### ISSUE THREAD

**Issue by dasMulli** [microsoft/vscode-copilot-release#190]
- VS Code Version:
Version: 1.79.0-insider (user setup)
Commit: c3867859cf3e1a73f3ddce5ad36b3791b7883d88
Date: 2023-06-01T05:24:05.541Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
- OS Version: Windows 11 10.0.22621.1194
- Logs:

Neither in Typescript or C# files I get quick actions from the Typescript or C# Plugins.

The plugins run fine but Refactorings menu (ctrl+shift+R) or quick actions lightbulb on errors (e.g. in C# where the Plugin would suggest adding a using staement) only show Copilot related actions ("Document using Copilot" or "Fix using Copilot").

I would like to continue using existing VSCode Plugin functionality next to Copilot Chat

**Comment by roblourens** [comment]
Can you share an example/screenshot?

**Comment by jordancarney1** [comment]
I'm experiencing the same issue.

VS Code Insiders w/ copilot
![Screenshot 2023-06-15 at 9 44 03 AM](https://github.com/microsoft/vscode-copilot-release/assets/2120423/083b658c-3117-4eb5-bbb8-6992ed71fb5b)
![Screenshot 2023-06-15 at 9 44 12 AM](https://github.com/microsoft/vscode-copilot-release/assets/2120423/4aad2828-8586-4a4a-8071-abf9c773b1ce)

VS Code
![Screenshot 2023-06-15 at 9 44 33 AM](https://github.com/microsoft/vscode-copilot-release/assets/2120423/21679fd8-0b8d-4e16-926f-ca24c3c48937)

**Comment by dasMulli** [comment]
It seems to work again now.

However I also switched to the new C# Dev Kit extension.

![image](https://github.com/microsoft/vscode-copilot-release/assets/6129250/4873d712-00d1-4f13-b9bd-f3ed6a7b2bb6)

Version: 1.80.0-insider (user setup)
Commit: 6545c4c2671127c323182225963fcd732e1fbcc5
Date: 2023-06-15T05:33:30.720Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Copilot Chat v0.3.2023061501
Copilot Nightly v1.89.161

**Comment by dasMulli** [comment]
@jordancarney1 I'd be interested if updating to 1.80.0-insider, latest extensions and possibly C# Dev Kit fixes it for you as well. Will close this issue then.

**Comment by jordancarney1** [comment]
Update to 1.80.0-insider - no change.

Installed C# Dev Kit, and it's fixed! No idea why that fixed it though 😆

**Comment by jordancarney1** [comment]
> @jordancarney1 I'd be interested if updating to 1.80.0-insider, latest extensions and possibly C# Dev Kit fixes it for you as well. Will close this issue then.

Update to 1.80.0-insider - no change.

Installed C# Dev Kit, and it's fixed! No idea why that fixed it though 😆
