### ISSUE TITLE
broken references

### ISSUE THREAD

**Issue by sinappsus-agency** [microsoft/vscode-copilot-release#1902]
Type: <b>Bug</b>

i am in a class/controller in laravel based on an openAi integration 

i highlight all the functions and ask it to generate a set of api routes based on the functions inside this class

it then starts to make up paths and objects that do not exist in the highlighted file but do exist in the project.
it repeats this behavior no matter how many times i ask or how i rephrase the question

---EDIT---
after questioning it in the chat to explain its reasoning behind these choices it corrected itself
-----------

Extension version: 0.22.2024101701
VS Code version: Code - Insiders 1.95.0-insider (6cf71eaab2600e2e1db3642aea3ad91aa6be3f7f, 2024-10-14T05:04:18.543Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (8.24GB free)|
|Process Argv|--crash-reporter-id 75546be1-49ab-4a3a-9127-3e7149b90ffc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
cppperfnew:30980852
pythonait:30973460
bdiig495:31013172
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
12bdf347:31141542
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137
dwcopilot:31158714
g7688163:31155431
iconenabled:31158249

```

</details>

**Comment by mjbvz** [comment]
Please share some example code that causes the issue plus an example question so we can try to investigate. Thanks
