### ISSUE TITLE
Getting some strange endings to my responses

### ISSUE THREAD

**Issue by Peaceteddie** [microsoft/vscode-copilot-release#191]
Since this is my first time making an issue, please excuse me if I'm doing this wrong.
Everything is updated as of writing this and I haven't tried anything special like restarting or anything.
Please close this if its an isolated incident.

Version: 1.79.0-insider (user setup)
Commit: c3867859cf3e1a73f3ddce5ad36b3791b7883d88
Date: 2023-06-01T05:24:05.541Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Copilot Chat: v0.1.2023060101
![image](https://github.com/microsoft/vscode-copilot-release/assets/5207739/addfc76d-9b22-4cc6-afd7-f13bfdb321ca)

Steps to Reproduce:

1. Not sure, asked if the selected code could be refactored.
2. Told me there was a command for that in my context menu
3. I then asked if it could refactor my code for me.
4. It kept ending its responses in "Here are the commands I referenced:" without adding anything

**Comment by roblourens** [comment]
Is that related to us asking for vscode commands, or is it just a weird response @lramos15 @sbatten ?

**Comment by sbatten** [comment]
yes I believe you are correct

**Comment by lramos15** [comment]
This should be fixed now
