### ISSUE TITLE
Copilot gives unproductive responses to information placed in front of it

### ISSUE THREAD

**Issue by ResCXsention** [microsoft/vscode-copilot-release#192]
VS Code Version: 1.70.0
OS Version: Debian 11

Here's a situation:

![image](https://github.com/microsoft/vscode-copilot-release/assets/107906006/c3ae45ba-054c-42b9-a527-f1a82f9acd9b)

It's a little alarming that Copilot is unable to even make assumptions about the language or purpose of the file, and will instead outright ask you for that information. Ideally, as outlined in countless other issues, Copilot needs to be aware of the open workspace as a whole, but it's worrying that Copilot cannot interpret information that has already been provided to it (at least, in this context). Rephrasing the same question, and asking about other files -- regardless of their existence -- will usually result in similar responses.

I am still not entirely sure what other phrases will cause Copilot to behave in such a manner -- I would post more examples if I could.

**Comment by ResCXsention** [comment]
@digitarald I had nothing selected, no.

Actually, I though the AI still has no awareness of the workspace at all besides what's on your screen.

**Comment by leonambeez** [comment]
The chat says it does not have access to the current code, even with the code selected.

<img width="289" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/67030878/189486b5-fcb7-4fd4-8639-fb4acc0b4bee">

**Comment by symbion6** [comment]
Same here. Responses are not very useful, it keeps responding with very generic comments, not aware of any code in my repository at all, not even of the currently opened file or code selection.

**Comment by mjbvz** [comment]
In the insiders version of Copilot Chat, you can use `#file` to include a specific file in the chat context. This feature should become available in the stable version of chat shortly

Alternatively you can use `@workspace` to include context from the workspace in the question. Unlike with `#file`, this context is automatically determined. It's most useful for asking a general question about the workspace or finding where something in the workspace exists
