### ISSUE TITLE
/explain command sorting

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-copilot-release#1923]
A nit, but when using the /explain command, then "/explain @terminal' is sorted before "/explain @workspace". See screenshot below. 

I suggest that '/explain @workspace' is prioritised over '/explain @terminal' since it is the more common operation. 

![Image](https://github.com/user-attachments/assets/1b540baf-061e-40cb-b391-df21446f7016)

**Comment by roblourens** [comment]
Got me- it always worked that way, then I refactored this menu for the 10th time and kept it for @ but lost it for /

**Comment by joshspicer** [comment]
✅  `@workspace` is back on top 

![Image](https://github.com/user-attachments/assets/074af40f-9935-4e9d-b788-0894095ac95d)



```
Version: 1.95.0-insider (Universal)
Commit: c0f27916ad81d8de78b62bd0aa0eab3f8cd99178
Date: 2024-10-25T09:02:38.980Z (7 hrs ago)
```
