### ISSUE TITLE
rate limited

### ISSUE THREAD

**Issue by BhortmanGSU** [microsoft/vscode-copilot-release#1928]
Type: <b>Bug</b>

it seems to get stuck in a rate limited loop, where it just adds random numbers after please wait. 
Ill wait 7 mins after it say wait 3 seconds, then it will say I need to wait 15 seconds, then 3 seconds, then 1 second. 
It contiunes in this loop for an extremely long time 

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.87GB (23.36GB free)|
|Process Argv|--crash-reporter-id 16cb0f5b-70de-408b-aecd-6577600d258c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
icondisabled:31158250

```

</details>

**Comment by lramos15** [comment]
The rate limits occur when you utilize an excessive amount of tokens in comparison to other users of Copilot chat. The number of seconds shown to you is based on completing the exact same request. If the request is changed in anyway then it will not be completed as you will not have enough tokens left in your pool.

The rate limit is something we're always adjusting and not something you should be hitting often. It's also not something that can really be fixed. Let me know if you're hitting this often and how you're hitting it!
