### ISSUE TITLE
When the content starts with /, it will cause copilot to recognize it as a command and have no response

### ISSUE THREAD

**Issue by HoPGoldy** [microsoft/vscode-copilot-release#193]
Copilot will recognize everything that starts with / as a command, and if the command is invalid, it will cause copilot to have no response, which will cause confusion, especially when the user accidentally starts with / when chatting, for example:

![image](https://github.com/microsoft/vscode-copilot-release/assets/28479777/31c51790-d99c-4479-88f7-5272e0b73f25)

Is it possible to add a more friendly prompt, such as telling the user "copilot recognized your answer as a command, but this command is invalid so it was not executed"

**Comment by lramos15** [comment]
This should be fixed in tomorrow's release. Thanks for the report!
