### ISSUE TITLE
Copilot always list all complete code, even if only a single line is changed

### ISSUE THREAD

**Issue by davbeek** [microsoft/vscode-copilot-release#1935]
Type: <b>Bug</b>

When Copilot shows how to modify the code, it always lists the complete code even if it contains say 50 lines, and only a single line is changed, making it almost impossible to find what was changed.

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id 299ff1a9-c2fd-4f23-b2e1-cf234a1f49fa|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
You should try inline chat via `CMD + I` it will highlight the code changes

**Comment by davbeek** [comment]
That doesn't work. `CMD + I` only works for small changes and requires you to know in advance in which line you want that change to occur.

My problem has been solved more or less with the October VSCode update introducing `Copilot Edits`, which works across multiple files and displays the changes in a diff manner in the file. Just what I needed.

**Comment by lramos15** [comment]
Thank you for the feedback, and we're glad you're enjoying Copilot edits! Would you like me to close out this issue then?

**Comment by davbeek** [comment]
Yes!
