### ISSUE TITLE
The session tab in the editor is very large

### ISSUE THREAD

**Issue by Yolziii** [microsoft/vscode-copilot-release#194]
Hey guys. I've opened my session in the editor and got this:

![image](https://github.com/microsoft/vscode-copilot-release/assets/16403393/2f2aa062-d038-4ba9-a37a-d952a594932f)

The session tab occupies all available space and makes it impossible to switch to other tabs. My question had 2 code snippets with markdown-style code blocks:
```python
# some peace of code
```

**Comment by jrieken** [comment]
@roblourens `verified` but also a little underwhelmed. There is `...` (see [truncate](https://github.com/microsoft/vscode/blob/fb2354b794ff063cb17c21dc6dfdd32d9ce8d544/src/vs/base/common/strings.ts#L84)) and the cutoff points could be aligned with word stops (similar to [lcut](https://github.com/microsoft/vscode/blob/fb2354b794ff063cb17c21dc6dfdd32d9ce8d544/src/vs/base/common/strings.ts#L711))
