### ISSUE TITLE
Response got filtered when tried to change a pom.xml

### ISSUE THREAD

**Issue by showpune** [microsoft/vscode-copilot-release#1940]
- Copilot Chat Extension Version:
- VS Code Version: v1.239.0
- OS Version: Windows 11
- Logs: 

Steps to Reproduce:

I tried to use the copilot to change a pom.xml, but got the response filter error, you can just input the following text to chat with copilot

Change the required dependencies in the given pom.xml 
1. Add Managed dependency:
groupId: com.azure.spring
artifactId: spring-cloud-azure-dependencies
version: 5.17.1
scope: import
type: pom
Note: If you're using Spring Boot 2.x, be sure to set the spring-cloud-azure-dependencies version to 4.19.0.
2. Add Dependencies:
groupId: com.azure.spring
artifactId: spring-cloud-azure-starter
groupId: com.azure.spring
artifactId: spring-cloud-azure-starter-storage-blob
3. Remove the aws s3 dependencies:
groupId: io.awspring.cloud
artifactId: spring-cloud-aws
GroupId: io.awspring.cloud
ArtifactId: spring-cloud-aws-starter-s3

Given pom.xml as below:
```xml
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<project xmlns=\"http://maven.apache.org/POM/4.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
  xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd\">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.0</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
  <groupId>com.example</groupId>
    <artifactId>s3-client</artifactId>
  <version>0.0.1-SNAPSHOT</version>
    <name>s3</name>
  <description>Demo project for Spring Boot</description>
  <properties>
    <java.version>17</java.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.awspring.cloud</groupId>
        <artifactId>spring-cloud-aws</artifactId>
        <version>3.1.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.awspring.cloud</groupId>
      <artifactId>spring-cloud-aws-starter-s3</artifactId>
    </dependency>
   </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>
```

You will get the error as below:
![Image](https://github.com/user-attachments/assets/0befbf1a-dc2d-4c35-9c2e-8b2e95c305da)

**Comment by showpune** [comment]
According to https://docs.github.com/en/copilot/managing-copilot/managing-copilot-as-an-individual-subscriber/managing-copilot-policies-as-an-individual-subscriber#enabling-or-disabling-duplication-detection, customer public code setting is set by organization and can't be changed

I use the Microsoft account setting and it doesn't work

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
