### ISSUE TITLE
@workspace Sends Deleted File to Copilot

### ISSUE THREAD

**Issue by LogicDX342** [microsoft/vscode-copilot-release#1948]
ADD ISSUE DESCRIPTION HERE

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0
Embedder: codespaces

Extension version: 0.21.2

![Image](https://github.com/user-attachments/assets/dba3748f-4c74-407d-ab88-9599fe5b2fcd)
![Image](https://github.com/user-attachments/assets/77a10bb2-8383-4990-8a6f-19d39790dc84)

**Comment by mjbvz** [comment]
Pretty sure I just fixed this. Please test out the next insiders build or the upcoming stable `v0.22` release and let me know if you're still seeing this
