### ISSUE TITLE
Languages for /explains etc

### ISSUE THREAD

**Issue by netskillzgh** [microsoft/vscode-copilot-release#195]
Adding an option to change the command language could be beneficial. Currently, the /explain command returns results in English. However, with a language option in Visual Studio Code, users could modify the language, allowing commands to be executed as follows on your server: "/Explain in French xxx."

**Comment by roblourens** [comment]
I think that usually if you ask a question in french, it will answer in french, have you tried that?

**Comment by roblourens** [comment]
I see, good point

**Comment by lramos15** [comment]
This should now respect your VS Code locale thanks to @joyceerhl 

So if you have your VS Code in French copilot should answer you in French
