### ISSUE TITLE
Terminal copilot in-line chat window doesn't disappear

### ISSUE THREAD

**Issue by EZZERG** [microsoft/vscode-copilot-release#1962]
Type: <b>Bug</b>

This issue is not conssitent. Sometimes the in-line chat of github copilot in the terminal (triggered by pressing ctrl+i) doesn't disappear from the screen regardless of which button I press next.
The chat only disappear if I delete the terminal altogether.

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.14.0-427.22.1.el9_4.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13980HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.62GB (40.79GB free)|
|Process Argv|--crash-reporter-id 2beaecbc-3630-4f55-92e5-c783f8e14def|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: turin|
|OS|Linux x64 5.14.0-427.22.1.el9_4.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz (128 x 0)|
|Memory (System)|375.85GB (334.75GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31161677
icondisabled:31158250

```

</details>

**Comment by Tyriar** [comment]
We made a lot of improvements to terminal chat recently so hopefully this is fixed. If not, please provide a gif of what's happening https://gifcap.dev/
