### ISSUE TITLE
Error for large requests `400 Bad Request: role must be "user", got "system"`

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-copilot-release#20]
Seeing this error:

<img width="432" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/25514145/57e78b3f-41a1-47fb-a8a8-3eebadddddaa">

_____

Version: 1.79.0-insider
Commit: 9084e081d4e89ed8ab67fce340d573c4e1378939
Date: 2023-05-15T05:24:19.845Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

Steps to Reproduce:

1. Prompt with below:
    > Read the below PowerShell Script:
    > ```PowerShell
    > ... long script with 500+ lines (23398 characters) ...
    > ```
2. See the error

**Comment by akpi816218** [comment]
Got similar error with a long TypeScript file (under 200 lines though)
A 50-line JSON file seems fine though, no error

**Comment by digitarald** [comment]
This should be fixed a while ago, but was [VS Code's October release (Copilot Chat 0.10)](https://code.visualstudio.com/updates/v1_84#_github-copilot) further improve staying within the context window.
