### ISSUE TITLE
Use Bing to browse the web to generate better answers

### ISSUE THREAD

**Issue by akashrajum7** [microsoft/vscode-copilot-release#200]
Currently, the GitHub Copilot Chat feels much dumber when compared to any other solution like [Perplexity](https://perplexity.ai/), [Phind](https://www.phind.com/ ) or [Bing Chat](https://bing.com/chat) for that matter, due to the lack of a mix of search results along with the existing context when generating results. This could be easily improved by using Bing API integration to allow for more up-to-date and accurate answers.

Since both projects are owned by Microsoft (GitHub and Bing), please collaborate and integrate Bing into GitHub Copilot Chat to provide better results.

Thank you.

**Comment by outgaze** [comment]
Right on the spot. That's literally the main issue with copilot right now well that and the ai model.

**Comment by suharnikov** [comment]
Agree. I can't ask something useful related to programming because "it's not a programming question"

**Comment by bhavyaus** [comment]
Please see https://github.blog/changelog/2024-10-29-web-search-in-github-copilot-chat-now-available-for-copilot-individual/
