### ISSUE TITLE
Add reset connection button instead of: Error on conversation request. Check the log for more details.

### ISSUE THREAD

**Issue by franchesoni** [microsoft/vscode-copilot-release#201]
Sometimes when starting an interaction with the chat I get `Error on conversation request. Check the log for more details.`.
The logs aren't very descriptive and more importantly a solution doesn't immediately come to mind:
```
[INFO] [default] [2023-06-03T09:37:10.230Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[ERROR] [default] [2023-06-03T09:37:12.360Z] Request Error: Client network socket disconnected before secure TLS connection was established
```
Better diagnostics and some button to repair this could be of great help. In particular checking once in a while that the socket can be established can be useful to show the user an "I'm ready" state. Without this one writes messages expecting the chat to work and then it doesn't and it's annoying. To solve this I usually send "hi" many times until the connection is correctly established, but this should be done automatically

**Comment by lramos15** [comment]
We've worked hard to improve many connection issues, including retrying failed requests. Let us know if you're still seeing issues!
