### ISSUE TITLE
Expanding Copilot's Code Access: Enabling Cross-File Repository Context in Chat Assistance

### ISSUE THREAD

**Issue by matteocirca** [microsoft/vscode-copilot-release#202]
When writing in the chat Copilot seems to have access only to the code of the current file, instead of the code of the entire repository. This is extremely limiting in that you cannot ask it to implement something specific by also looking at other files within the repository.

**Comment by uzunvg** [comment]
I want to add, that basing on my experience and the demos I have seen in github channel on youtube, Copilot chat should have access to the open files you have in your editor, but basing on its answers it has small context window which doesn't cover more then 100 lines of code in all open files cumulatively

**Comment by bhavyaus** [comment]
Please see: https://code.visualstudio.com/docs/copilot/workspace-context
