### ISSUE TITLE
o1-preview (Beta) policy acknowledgement

### ISSUE THREAD

**Issue by stanojevicbojan** [microsoft/vscode-copilot-release#2021]
Type: <b>Bug</b>

Keeps asking to agree o1-preview (Beta) policy acknowledgement, i can't use the chat

Extension version: 0.22.2024102401
VS Code version: Code - Insiders 1.95.0-insider (e1de28e4eeaf685668c21bac9b2a0f3a68608c44, 2024-10-24T10:32:45.203Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1235U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (0.95GB free)|
|Process Argv|--crash-reporter-id 9ff0165b-ae15-48aa-b8a6-915bda0de24c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by lramos15** [comment]
Server side issue. We have since resolved this. Thanks for the report and let me know if you are still having issues.
