### ISSUE TITLE
Cannot clear messages

### ISSUE THREAD

**Issue by agecode-debug** [microsoft/vscode-copilot-release#2051]
- Copilot Chat Extension Version: v0.21.2
- VS Code Version: 1.94.2.0
- OS Version: Windows 23H2

Steps to Reproduce:

1. Send messages to copilot
2. Type /clear or click "+" in upper right
3. Nothing appends, sometimes an error:
![Image](https://github.com/user-attachments/assets/99c03924-05e6-4fc5-91fe-fc758d4f8bf3)

**Comment by roblourens** [comment]
That's interesting, are you able to copy the conversation? Right click > Copy All

Can you tell me about what sort of content is in the conversation? 

Are there any more error details in the Window output channel?

**Comment by agecode-debug** [comment]
Sorry for the delay in replying, so "copy all" actually works perfectly, and the bug occurs for any type of conversation, no matter the conversation. And I haven't found any other details, knowing that even the error message doesn't always appear during the bug

**Comment by roblourens** [comment]
> for any type of conversation, no matter the conversation

Are you saying that it always happens, and happens in every window? Even a fresh one with no previous chat content?

**Comment by roblourens** [comment]
For my own reference, from the error, seems like there is a context key/ContextKeyExpression in the chat session, which probably comes from a widget or service that shouldn't be in there, but I don't know how it got in there.

**Comment by agecode-debug** [comment]
> > for any type of conversation, no matter the conversation
> 
> Are you saying that it always happens, and happens in every window? Even a fresh one with no previous chat content?

Now, after the updates, the button works, but every in every window, every restart of my pc, the "/clear" command don't work. But I don't see any error for this command

**Comment by roblourens** [comment]
Hm, you don't see any errors in the Window output channel when running clear? Do you see the request with `/clear` rendered in the chat list? Can you send a screenshot?

**Comment by roblourens** [comment]
I think all these problems are related, but I really don't know what's happening

> every restart of my pc, the "/clear" command don't work

Are you saying that if you use the + button, then chat, then do `/clear`, it works? But if you restart your pc (or just reload the VS Code window) then it doesn't work? I can sort of imagine the kind of problem that would lead to this.

But do you see any errors in the WIndow output channel? 

Also, could you do this

- F1 > Set Log Level > Trace
- F1 > Reload Window
- Run `/clear` in chat
- Share the log from the Window output channel

That would help me understand how the chat service got out of sync and is not able to find and clear your chat session.

**Comment by agecode-debug** [comment]
even without restarting my computer, /clear does not work, and I followed the steps for the logs, I see them but when I command there is no new log that appears, I mean, the logs before and after the command do not change
