### ISSUE TITLE
Copying from Copilot Chat's response fails to copy while Copilot is still adding text, even offscreen

### ISSUE THREAD

**Issue by vintagedave** [microsoft/vscode-copilot-release#2058]
- Copilot Chat Extension Version: 0.21 (2024-10-02)
- VS Code Version: 
Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z (2 wks ago)
- OS Version:  macOS Sonoma 14.4.1
- Logs: (attached.)[GitHub Copilot.log](https://github.com/user-attachments/files/17534480/GitHub.Copilot.log)
[GitHub Copilot Chat.log](https://github.com/user-attachments/files/17534481/GitHub.Copilot.Chat.log)

### Steps to Reproduce:

1. Using VSCode on macOS, write a query where Copilot will write a lot of text in answer. I find a 'what's wrong in this code' one does the trick because it will then repeat the entire file to you, especially if it helped you build it (which is probably worth a separate bug report, it makes finding what it changed very difficult.)
2. _While it's still adding content_ hover over a code sample. Select using the mouse, press Cmd+C, toggle to the code editor, Cmd+V.
**Expected:** what you selected is pasted
**Observed:** whatever was in the clipboard already is pasted

I have seen the Copy button hovering over a code snippet fail too with the same symptoms as above.

Related is that the set of buttons that appear while hovering over a code snippet flicker a lot while it's adding text.  I get the feeling that rather than appending text, it's rewriting the entire HTML or something for every token. I don't know, but it's a suspicion.

My expected behaviour is that anything onscreen should be copyable, especially if I scroll upwards and I can't even see that Copilot is still adding content.

Thankyou :)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/208191
