### ISSUE TITLE
Inline chat: Could not process response without a reply interpreter!

### ISSUE THREAD

**Issue by fritz-trawa** [microsoft/vscode-copilot-release#2060]
- Copilot Chat Extension Version: v0.21.2
- VS Code Version: 
Version: 1.95.0-insider
Commit: 38dc6ac5a771cc94bde1344722bb2d02c80096ea
Date: 2024-10-25T22:08:52.005Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
- Logs: No logs of any type

Steps to Reproduce:

1. Start the inline chat with CMD-I
2. Ask anything
3. Response is always "Could not process response without a reply interpreter!"
4. When I asked in the main chat what a "reply interpreter" is Copilot had no idea what I was talking about

I am beginning to get fed up with this plugin

**Comment by elizalucas** [comment]
I am experiencing the same thing for any inline chat I try to start

**Comment by lramos15** [comment]
Can you attach the logs via CMD + SHIFT + U -> GitHub Copilot Chat please

**Comment by jrieken** [comment]
@elizalucas @fritz-trawa Do you or your organisation use copilot-ignored files?

**Comment by fritz-trawa** [comment]
I was briefly, but not at the time I was getting the error. It has since stopped, so it may have been related

**Comment by jrieken** [comment]
Thanks @fritz-trawa - I am confident that this is due to ignored files. That's what the code suggests and this is how I could repro. To verify

* have `.copilotignore`-file and ignore `test.html`
* open `test.html` and make an inline chat request
* make sure the request fails gracefully and shows a nice message
