### ISSUE TITLE
Secondary sidebar shifts editor when located on the left

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/vscode-copilot-release#2062]
The latest extension update has moved the Chat window out of the Primary Side Bar into the Secondary, and in doing so, the UX experience is degraded (IMO).

I have the Primary Side Bar on the right so that the experience of show/hide does not reposition the left side of the editor window, but the secondary side bar now has to be on the left, resulting in a repositioning of the editor area.

Here's an example of the change in action, and as you can see the left-alignment now moves around with the side bar being open/closed often (which I'd find common with Copilot Chat).

![VS Code with side bars opening and closing](https://github.com/user-attachments/assets/e5f12d6f-ebcf-4c85-bcca-951b2a63e3a1)

I can't find a setting that would merge them together, but that is what ideally would exist.

**Extension version:** `v0.22.2024102603 (pre-release)`
**VS Code version:**
```
Version: 1.95.0-insider (system setup)
Commit: 38dc6ac5a771cc94bde1344722bb2d02c80096ea
Date: 2024-10-25T22:08:52.005Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26120
```

**Comment by aaronpowell** [comment]
ok, so I just realised you can drag the icon across to the other side bar and now I'm back to my original experience, but that wasn't an obvious/discoverable option.

**Comment by aaronpowell** [comment]
It did pop up and I'll admit to having not really paid attention, then couldn't get it back or find the info again when I realised I *should* have read it.

**Comment by zivgit** [comment]
Why can the VSCode extension GitHub Copilot register the position of viewsContainers in the Secondary Sidebar?
I am developing a VSCode extension and would like to learn more. Thank you.
#143037

**Comment by whmms** [comment]
> ok, so I just realised you can drag the icon across to the other side bar and now I'm back to my original experience, but that wasn't an obvious/discoverable option.

agree! and they should NOT have set it to be the 2nd side bar by default

**Comment by RebelSoftware** [comment]
I saw the popup and thought I'd try it on the right side.

Once done there appeared to be no way to undo it. That is a very poor experience.

I had to come here to find the hint of grabbing an icon to move it which is simply in my opinion nonsensical. However this appears to be a vscode issue not a copilot issue. 
To move windows you always grab the title bar or what serves as a title bar. grabbing an icon or text within a title bar is not a good user interface decision as it is a not standard.

**Comment by wildan-m** [comment]
I typically code on a small screen (MacBook Air) with VSCode adjusted next to an emulator. When Copilot is on the secondary sidebar, it shrinks the main code editor window a lot. I prefer having it on the primary sidebar by default, with the option to move it to the secondary sidebar. If not, at least please don't remove the ability move it back to the primary sidebar.

**Comment by bpasero** [comment]
It is easy to bring the chat back to the primary sidebar, just drag and drop it over:

https://github.com/user-attachments/assets/eadb8493-cec8-4848-81d2-4f980e1bae54

**Comment by tim-mukhin** [comment]
+1 
My top panel disabled at all as I don't use it, so I lost all connections to copilot chat except turning on from the menu
#2167

**Comment by jeffcovey** [comment]
@bpasero Nothing happens when I drag on that icon. I don’t get a floating icon that can be dropped somewhere like you do.

**Comment by PancakeTAS** [comment]
I can't move the chat back either. Dragging the chat icon and hovering over the
primary sidebar makes it appear as it should be dockable, but it simply stays on the wrong side of the screen. Arch Linux, using visual-studio-code-bin. Installing older versions does not work either.

**Comment by bpasero** [comment]
Ok that sounds like a bug to me, how about other things, like editor tabs, can you drag those?

**Comment by alessandro-neon** [comment]
I believe the copilot developers should be aware that they shouldn't force modifications on users who do not ask for them. We have important deliveries to make, and the main feature we expect from a tool is stability. We don't have time to waste getting used to aesthetically irrelevant modifications.

**Comment by PancakeTAS** [comment]
> Ok that sounds like a bug to me, how about other things, like editor tabs, can you drag those?

Oh, my bad, I should have totally tried this. I can drag editor tabs, but other icons like the explorer also don't let me move them. I'd love to know of a workaround but this doesn't seem to be an issue related to this extension :P

**Comment by sbatten** [comment]
@PancakeTAS any chance you can upload a screen recording of the issue?

**Comment by PancakeTAS** [comment]
> [@PancakeTAS](https://github.com/PancakeTAS) any chance you can upload a screen recording of the issue?

sure here you go

https://github.com/user-attachments/assets/1b1429a4-e9a7-4ef8-be74-1d02ee9c6273

**Comment by sbatten** [comment]
@PancakeTAS Are you using Wayland?

@deepak1556 Known issue on linux? They are using arch.

**Comment by PancakeTAS** [comment]
> [@PancakeTAS](https://github.com/PancakeTAS) Are you using Wayland?
> 
> [@deepak1556](https://github.com/deepak1556) Known issue on linux? They are using arch.

Yes I am on Wayland, more specifically Hyprland

**Comment by bpasero** [comment]
There is an alternative way of moving the chat view back via the "Move View" command, that should always work:

![Image](https://github.com/user-attachments/assets/dfdf35a2-43cf-4b49-b7a7-43c580c42938)

**Comment by jeffcovey** [comment]
Instead of posting workarounds that restore the layout the way it was, wouldn’t it be simpler to just undo this change that no one asked for and which seems to be universally hated? 🤷‍♂️

**Comment by Sebastriani** [comment]
Aweful change, what a relief to find out thanks to @aaronpowell that it can be changed by dragging the icon.

**Comment by Shadow-gitizen** [comment]
Took me more than an hour digging through all the settings , asked the copilot itself  , searched on google  didn't find anything .
I thought i messed up something that it is not appearing there (recently reinstalled my os) , 
Fortunately landed here , completely unnecessary change

**Comment by dikelps** [comment]
On Arch Linux with KDE Wayland, couldn't drag and dock. Reverted to X11 and drag and dock worked, then went back to Wayland and layout stayed.

**Comment by deepak1556** [comment]
@sbatten yes dnd issue with wayland is tracked in https://github.com/microsoft/vscode/issues/227897

**Comment by alexx855** [comment]
> ok, so I just realised you can drag the icon across to the other side bar and now I'm back to my original experience, but that wasn't an obvious/discoverable option.

after searching for every setting copilot has, it was just a drag and drop 🥲

please do not suggest layout changes as default selection for further updates, the default should be the current layout, no need to mess up the UX like that 🙏🏻

**Comment by bpasero** [comment]
The secondary side bar is the default location for Chat and Copilot Edits since our November release. There are ways to move these views to side bar or panel as needed. 

If you see usability issues with the secondary sidebar, please report them as issues to https://github.com/microsoft/vscode/issues and we are happy to take it from there. Our plan is to make the secondary sidebar easier to use and better. It is also the first time for us to ship a view there by default, so we are happy to learn how to improve that.

I am going ahead and close this issue 🙏
