### ISSUE TITLE
perform action on selected code only

### ISSUE THREAD

**Issue by rleertg** [microsoft/vscode-copilot-release#2071]
Type: <b>Bug</b>

When highlighting a section of code and attempting to perform copilot action on it or add it to copilot chat dialogue, it attempts to perform request on entire file instead of selected code only.

Extension version: 0.21.2
VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 1, 2|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 35589a99-d536-4138-8209-dcff6a1dfbdc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Do you have some example recordings for us to reproduce and refine this issue?
