### ISSUE TITLE
Add Labels or tags on chat history to help Engineer the prompt

### ISSUE THREAD

**Issue by gamousquesORT** [microsoft/vscode-copilot-release#208]
I had learned that engineering the prompt is key to getting better results. Adding tags or labels to the chat history could help to iterate while building the prompt. Labeling prompt steps, formats, etc. could improve the prompt.

**Comment by roblourens** [comment]
You can certainly do this yourself with text. Not sure I would add any UI or other builtin mechanism for this though.
