### ISSUE TITLE
Cannot add whole code base with single-click?

### ISSUE THREAD

**Issue by AntDX316** [microsoft/vscode-copilot-release#2092]
![Image](https://github.com/user-attachments/assets/bf856405-2a47-42b5-b981-1f5229fb6576)

This has to happen.

**Comment by joyceerhl** [comment]
This is available:

![Image](https://github.com/user-attachments/assets/2c189c39-2d6c-4356-b2fd-ed3fa0445a6a)

**Comment by mjbvz** [comment]
Closing as I believe this already exists, either using the shortcut or by explicitly asking `@workspace`
