### ISSUE TITLE
Suggestion can't include code from my own code-base

### ISSUE THREAD

**Issue by bbangert** [microsoft/vscode-copilot-release#2095]
Type: <b>Bug</b>

When the organization setting doesn't allow 'public code', but my repo itself is open-source and thus 'public code', suggestions can't include code that already exists in the code I'm working on as it matches public code.

Extension version: 0.22.2024100702
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2
Connection to 'dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f6262616e676572742f6d65676168616c2e6769742f747265652f6d61696e222c22766f6c756d654e616d65223a225f5f554e495155455f5f222c22666f6c646572223a226d65676168616c222c2273657474696e6773223a7b22636f6e74657874223a226465736b746f702d6c696e7578227d2c22636c6f6e65496e666f223a7b2275726c546f436c6f6e65223a2268747470733a2f2f6769746875622e636f6d2f6262616e676572742f6d65676168616c2e676974222c22726566223a226d61696e227d2c22696e7370656374566f6c756d65223a66616c73657d' could not be established
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
