### ISSUE TITLE
github.copilot.chat.experimental.codeGeneration.instructions does not seem to be working in workspace settings.json file

### ISSUE THREAD

**Issue by brianpajak-intel** [microsoft/vscode-copilot-release#2096]
Does this issue occur when all extensions are disabled?: No (because then copilot would not work)

- VS Code Version: 1.93.1
- OS Version: Windows 11

Steps to Reproduce:

1. Open a workspace
2. Create a .vscode/settings.json file
3. Add the following to the file
{
    "github.copilot.chat.experimental.codeGeneration.instructions": [
        {
          "file": ".vscode/codestyle.md"
        },
    ],
}

4. Add some code style guidelines to the codestyle.md
5. Ask Copilot to generate code which should trigger a reference to codestyle.md

Copilot does not seem to be respecting the github.copilot.chat.experimental.codeGeneration.instructions property in my workspace .vscode/settings.json file.  If I put the same thing in my user settings.json file it works just fine, but it does not work when this option is in a workspace settings.json file.

**Comment by aeschli** [comment]
The setting name has changed. It is now 'github.copilot.chat.codeGeneration.instructions'.

We look at both the user settings and the workspace settings for that setting and merge all entries.
All file paths are relative to the currently open workspace folder.

Can you check whether the references section ('Use x reference') contains the '.vscode/codestyle.md'?

I just tested that this works also wrong the workspace settings.

Do you have a single folder open or a workspace with multiple roots?

**Comment by brianpajak-intel** [comment]
Are you sure the name has changed in the released version?  I have the latest update of VSCode and the Copilot extensions, but when I try and change the properties from experimental to the ones without experimental in the name the property is grayed out which means it is not valid in the version I am using.  Could these changes still be in your pre-release code only?

**Comment by aeschli** [comment]
The change comes in 0.22.0 (stable) which you will get with the latest VS Code stable (1.95.0)
