### ISSUE TITLE
Matches the copyright banner with public code and declines to answer

### ISSUE THREAD

**Issue by csgurel** [microsoft/vscode-copilot-release#2097]
Type: <b>Bug</b>

By default, all Copyright banners in the files are similar and there are many overlaps with public code. The copilot extension tries to generate the full code script, finds a match with public code and declines to answer to prompts that don't even require the full code. It works fine if I force it to generate a snippet and not an entire script.

"Sorry, the response matched public code so it was blocked. Please rephrase your prompt."

Extension version: 0.21.2
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.0-119-generic

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
