### ISSUE TITLE
Sorry, the response matched public code so it was blocked. Please rephrase your prompt.

### ISSUE THREAD

**Issue by houk-ms** [microsoft/vscode-copilot-release#2105]
It occurs with such a high frequency, making people frustrated

**Comment by houk-ms** [comment]
Is there any config i can turn on to accept public code?

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
