### ISSUE TITLE
Provide a quick way to move chat and copilot edits to primary sidebar

### ISSUE THREAD

**Issue by synthmusic** [microsoft/vscode-copilot-release#2111]
Few things automatically pop up in the secondary side bar, and there should be an obvious, quick way (setting or context click) to tell copilot and its new edit friend to all go back to the primary side bar, and/or set primary side bar as default.

- Copilot Chat Extension Version: 1.243.0

Steps to Reproduce:
1. Update copilot
2. It now lives in the secondary side bar

**Work Around / Fix**

Click and drag the icons of the secondary side bar (probably on the top):
![Image](https://github.com/user-attachments/assets/1cc96ecf-ce6c-4b62-8c6a-91f26617e105)

Over to the activity bar (primary side bar icon area, probably on the left side):
![Image](https://github.com/user-attachments/assets/e1018c85-3d04-455b-9c3f-cced387f8c20)

to 

![Image](https://github.com/user-attachments/assets/365c290c-5f82-4943-9495-5b8b51c10ad6)

**Comment by bpasero** [comment]
We plan on making this easier without drag and drop. Please upvote / comment in: https://github.com/microsoft/vscode/issues/232797
