### ISSUE TITLE
Unsafe terminal insertion and execution

### ISSUE THREAD

**Issue by gund** [microsoft/vscode-copilot-release#2112]
Type: <b>Bug</b>

When AI returns any shell script - extension shows the button to "Insert into terminal" but once clicked it immediately executes it which is not stated in the action of the button, unexpected and potentially is unsafe to run as a modification to the script may be necessary before it's execution.

Either clearly state that it will run the command immediately or better - only paste it in the terminal and let the user execute it when ready.

Thanks!

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by Tyriar** [comment]
For me this button definitely works as intended and only writes the content:
![Image](https://github.com/user-attachments/assets/c4e9e29b-6665-4eef-82ff-f9b0824420cb)

Any more details on a repro?

**Comment by gund** [comment]
I used this from the context of the editor by getting autofix for the code: the file contained carriage returns line endings and my linter was complaining and wanted to remove those, and when I asked copilot to fix it from the editor it suggested in a popup a `sed` script that removes those, that is when I clicked the button to "insert into terminal" but to my surprise it executed it immediately after the click.
Thankfully the command was simple and worked just fine but you can imagine if copilot hallucinates something weird and if this goes into terminal and executes immediately bad things might happen.
I do not know what triggers the immediate execution per se but that is what happened in my case.

**Comment by Tyriar** [comment]
I tried in the chat view too here and it works as expected:

![Image](https://github.com/user-attachments/assets/b5e40067-c7e8-4079-854d-b8bb955dae1a)

Not sure where else it can show up 🤔 

Can you take a screenshot or [gif](https://gifcap.dev/) of the problem to make it clear?
