### ISSUE TITLE
Suggestion for "Report response error" button

### ISSUE THREAD

**Issue by nmkiencmc** [microsoft/vscode-copilot-release#212]
Hello,
I am asking copilot chat write for me an ESP8266 C++ script but it only answer it can only answer for programming related problem,
Then I find out where is the button to report this error to development team, but turn out there is no Report problem about Backend (Only problem for extension only). I think it should be better to collect data about how bad of copilot is to improve on its model.
Hope to have it soon

**Comment by digitarald** [comment]
Added a menu for thumbs down since
