### ISSUE TITLE
Duplicates entire code when using the rename symbol option in vs code

### ISSUE THREAD

**Issue by RaulMelendez23** [microsoft/vscode-copilot-release#2120]
- Copilot Chat Extension Version: 1.243.0
- VS Code Version: 1.95.0
- OS Version: 23H2
- Logs: 

Steps to Reproduce:

1. have both copilot extensions running 
2. create a variable or function in python
3.  right click variable name and select rename symbol

This duplicates the code, if i disable copilot chat extension the problem is resolved

**Comment by ulugbekna** [comment]
Could you run command "Toggle screencast mode" and provide a screencast? Thank you!

**Comment by RaulMelendez23** [comment]
sorry for the late reply but i tried recreating the problem now, but it seems to work just fine it, it doesn't duplicate my code anymore
