### ISSUE TITLE
Made-up URL for made-up class

### ISSUE THREAD

**Issue by solomonshorser** [microsoft/vscode-copilot-release#2121]
Type: <b>Bug</b>

It made up a URL for a class that does not exists (at least not as far as I can tell).

Extension version: 0.21.2
VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 5|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 80d31bff-1db9-4b64-8b43-24c5c0c0e649|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
autoexpandse:31146404
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
icondisabled:31158250

```

</details>

**Comment by solomonshorser** [comment]
Details: I asked for information about deferring a PythonSensor in Airflow. It provided information about `DeferrablePythonSensor` which I don't think exists. I asked very directly for a link to info about that class. It made up a URL (https://airflow.apache.org/docs/apache-airflow-providers-sensors/latest/operators/deferrable_python_sensor.html) that followed he structure of other Airflow operators, but the link it provided does not exist.

CoPilot even wrote code examples using this class, as if it existed.

**Comment by digitarald** [comment]
Hallucinated code can happen with AI.
