### ISSUE TITLE
Attach an image by pasting it in the chat text field

### ISSUE THREAD

**Issue by WillJub** [microsoft/vscode-copilot-release#2127]
Add an image in the chat input by pasting it or through a file dialog.

**Comment by Qualzz** [comment]
I think this is a very important feature, as sometimes an image is worth hundreds of words

**Comment by justschen** [comment]
@WillJub @Qualzz check out the [Copilot Vision Preview Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-copilot-vision&ssr=false#overview)! 

The extension will be deprecated in favor of a built in support from chat, but is intended to be an example of what that might look like in the future.
