### ISSUE TITLE
PerplexityAI callback URL issue

### ISSUE THREAD

**Issue by privetin** [microsoft/vscode-copilot-release#2129]
Type: <b>Bug</b>

Perplexity: "Please complete authorization in your browser and resend your question."
Browser: "This GitHub App must be configured with a callback URL"

Extension version: 0.20.3
VS Code version: Cursor 0.42.3 (949de58bd3d85d530972cac2dffc4feb9eee1e40, 2024-10-16T17:56:07.754Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-copilot-release/issues/2093
