### ISSUE TITLE
Language model unavailable

### ISSUE THREAD

**Issue by innovimia-cto** [microsoft/vscode-copilot-release#2132]
Type: <b>Bug</b>

Copilot keeps sayig: Language model unavailable

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (1.13GB free)|
|Process Argv|--crash-reporter-id d24976c0-a732-4e5f-9cfb-d248c8b0e251|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by roblourens** [comment]
Please share any logs in the "Copilot Chat" output channel, and if you know how you got in this state, please share: https://github.com/microsoft/vscode-copilot-release/issues/2116

Restarting VS Code may work around this for you

**Comment by innovimia-cto** [comment]
Yes! Restart worked! Thanks!On Nov 1, 2024, at 8:58 AM, Rob Lourens ***@***.***> wrote:﻿
Please share any logs in the "Copilot Chat" output channel, and if you know how you got in this state, please share: #2116
Restarting VS Code may work around this for you
