### ISSUE TITLE
Setting for default model

### ISSUE THREAD

**Issue by alexander-kastil** [microsoft/vscode-copilot-release#2134]
Now that you have different LLM's like o1-preview, cloude-sonnet, ... available, it would be great to be able to set a default model in the settings of VS Code. Currently, I have to re-select if on each start.

**Comment by alexander-kastil** [comment]
> We don't plan to add a setting as this is treated as view state, but I do not have re-select on each start.
> 
> 1. I select Claude
> 2. I reboot VS Code
> 3. Claude is still selected.
> 
> Are you not seeing this?

No ... that's why I introduced this request ... on my VS Code after closing and opening the default model is always GPT 4o ... I have to re-set it all the time, which is very annoying

**Comment by lramos15** [comment]
@roblourens Not sure if that is expected or not. it is not what I'm seeing 🤔

**Comment by alexander-kastil** [comment]
> [@roblourens](https://github.com/roblourens) Not sure if that is expected or not. it is not what I'm seeing 🤔

can i provide some debug info? instruct me on how to collect it

**Comment by roblourens** [comment]
Hm, do you have multiple VS Code windows open?

**Comment by alexander-kastil** [comment]
@roblourens After executing "F1 > Reload Windows" once, the selected model (Claude) remained. Now it stays selected even if I "x"-close VS Code and re-open it. That resolved the issue
