### ISSUE TITLE
Copilot chat small list of bugs

### ISSUE THREAD

**Issue by jccastro94** [microsoft/vscode-copilot-release#214]
A few different small bugs on Copilot chat:
First off, splendid work with Copilot chat. It's super useful to have this chatbot to help with code.

Seems this is the only way to give feedback, so I hope this helps a bit :)

Bugs:

1. Suggests different libraries that do the same thing, ignoring what we are using. (Might suggest PyPDF2 and later will use pdfMiner in another function)

2. I'm not sure what the context window is (8k?) but after using it for a while, it becomes more likely to get stuck in loops such as 
"User: Can you help me join these 2 objects by id?"
"CoPilot: Sure: ... 
`const source result.content.find((item) => item.id === interviewID);`"
"User: Thanks, but the interviewID is found in the "groupedInterviews" object"
"CoPilot: Sorry...  
`const sources = groupedSources[interviewID];`"
"User: Thanks, but I need to find those ID's in the content object to join them"
"CoPilot: Sorry...  
`const source result.content.find((item) => item.id === interviewID);`"

Feels like it ran out of context tokens, tries and fails to find relevant context and does the same answer again. Clearing chat or more detailed prompting helps but it's a bit annoying.

3. Copy pasting is awful. Not sure if it is meant to be on purpose, but sometimes I cannot copy anything from inside the copilot chat, unless I use the "copy" button inside the code snippet. And that copy button copies the full snippet when I just might need a line or two. 

Seems to be cause the chat is made from different containers, and one must "select" the container first, to get inside, to copy things within it. (Image attached showing the outer container selected and how one can only select and copy things out of the outer container.)

4. Depending on the data I'm working on (I work with lots of text) I will get the "I can only answer code questions" response. 
E.g. 
User: "I need to debug this, however not sure which variables will help me get to the issue faster. here's my snippet:
`data = "This is some random text I need to work with. I work with transcripts, so questions are common. Why does CoPilot think this is part of my question?"
const foo = data. Split(". ")`"
Copilot: "I'm sorry, I can only answer questions about code..."

That would be it for right now. Hope this helps Copilot Chat improve. I'm a fan. And thanks for your hard work!

>  Onward
>  Julio Castro

VS Code Version: Latest Insiders (1.79)
OS Version: Windows 11
Logs: NA

![image](https://github.com/microsoft/vscode-copilot-release/assets/73132288/e3e0ecb6-9555-4cba-b2b5-af38f005a9a2)

**Comment by bhavyaus** [comment]
Thank you for your feedback. We've made several updates in areas which impact the scenarios you have described. Please give it a try in our newer releases.
