### ISSUE TITLE
Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again

### ISSUE THREAD

**Issue by varoudis** [microsoft/vscode-copilot-release#2140]
Type: <b>Bug</b>

what is this??? its just python code!

Extension version: 0.23.2024102903
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 24.1.0
Modes:

**Comment by nicsuzor** [comment]
I've been regularly hitting these messages out of nowhere over the last few days too, when I didn't before.

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
