### ISSUE TITLE
Edits did not add code to file

### ISSUE THREAD

**Issue by Rhugan** [microsoft/vscode-copilot-release#2144]
Type: <b>Bug</b>

Edits has suggested code updates to my README.md, but has only provided them in the chat window rather than adding them to the file itself

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (13.69GB free)|
|Process Argv|--crash-reporter-id a03f473d-90b7-4860-9f1b-c01b6f7c34c7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31164048
iconenabled:31158251

```

</details>

**Comment by joyceerhl** [comment]
Just to confirm, are you using the Chat view or the Copilot Edits view? A screenshot or screen recording would be helpful.

**Comment by pedrobergaglio** [comment]
Same issue here with python notebooks. I accept the updates but nothing changes
![Image](https://github.com/user-attachments/assets/851aafe2-7f48-466c-b20d-0e6df728beb6)

**Comment by pedrobergaglio** [comment]
Using this results in an update, but not in the place it's needed:
![Image](https://github.com/user-attachments/assets/f328baa0-ae91-47e0-b49e-bf7bf8138b17)

**Comment by joyceerhl** [comment]
@pedrobergaglio we just shipped support for editing notebooks using Copilot Edits, please let us know if it still repros. cc @DonJayamanne
