### ISSUE TITLE
Rate Limit Issue

### ISSUE THREAD

**Issue by BrianMwengi** [microsoft/vscode-copilot-release#2147]
Type: <b>Bug</b>

Sorry, your request was rate-limited. Please wait 45 minutes before trying again.

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.67GB free)|
|Process Argv|--crash-reporter-id 4a67a221-c14a-4254-b6ef-32c544d79857|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by lramos15** [comment]
The rate limits are based on tokens and you must've sent some large requests to Copilot Chat for a sustained period of time. We see barely anyone hit these rate limits but are constantly tweaking them on our end to ensure we maintain the integrity of the Copilot service while providing a usable Copilot experience.

I would be interested in learning more how you use Copilot that is utilizing so many tokens

**Comment by surajssc1232** [comment]
i just did less than 10 requests still gave me the rate limit error

**Comment by Tigerpoint** [comment]
Same here! And my token count is not large.

**Comment by BrianMwengi** [comment]
I am using the o1-preview model. I did sent several requests. However there were not many. The other models are okay but I am being rate limited on this one.

**Comment by lramos15** [comment]
O1-preview has a small rate limit of just 10 requests per day due to being an expensive model. Please utilize the other models after you hit the rate limit.

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2627. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
