### ISSUE TITLE
Sorry, no response was returned after returning response

### ISSUE THREAD

**Issue by juanfadev** [microsoft/vscode-copilot-release#2157]
Type: <b>Bug</b>

Calling claude sonnet, it returned a response; but in the middle of the process of editing a file, it suddenly showed "Sorry. no response was returned" and all the progress on that file was lost.

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (10.03GB free)|
|Process Argv|--crash-reporter-id 168a6030-29a0-424a-8b20-1c8109cbef2c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor (2 x 0)|
|Memory (System)|3.83GB (0.35GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca2:31156134
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by lramos15** [comment]
Do you have a reliable repro for this?

**Comment by craigphicks** [comment]
Just switched it on (Claude Sonnet 3.5 Preview), and response to the first question is 
> Sorry, no response was returned

**Comment by craigphicks** [comment]
I started a new chat and at least it began to return a reply.

**Comment by lramos15** [comment]
Can you include your logs via CTRL + SHIFT + U -> GitHub copilot Chat

**Comment by andeeplus** [comment]
I've got the same issue.

`[error] CodeExpectedError: cannot open xxx (Error: Unable to resolve nonexistent file xxx)`

The error is triggered for several files that has been deleted in the past and they are not related with the current file context selected.

After all the errors I have this info message

`2024-11-06 21:40:15.947 [info] request done: requestId: [3b272269-fdaa-43a0-937e-06578361e1c5] model deployment ID: []`

---

Just for debugging purpouse I've tried to check the logs os the same message using GPT 4o

It logs the same errors and the same info at the end, this time preceded by, but it works.

```
2024-11-06 21:45:59.729 [info] message 0 returned. finish reason: [stop]
2024-11-06 21:45:59.730 [info] request done: requestId: [0be3a8ae-a7e2-4653-bb46-d98d71696e6c] model deployment ID: []
```

I'm on a npm workspace.

---

The fun thing is that if I open a new vscode instance, empty one, and I try to use Claude 3.5 it works without any issue.

---

If I open a different monorepo I get the same issue.

---

Tried with another project a simple one, no monorepo, new chat. It starts with this message:

```
Workspace(rerun without)...
Still building the workspace index, response may be less accurate.
````

It took 1/2 minutes to give the response but it worked

---
[SOLVED] **Last shoot** 
I went back to the first project, **opened a new chat** (before I was using the already active chat, I do not change it often, I use to keep always the same opened and use it - btw is it a good or  bad practice?) and now Claude 3.5 is working again.

Not so intuitive but at the end looks like I can use it. I hope you can find this live debugging session helpful, I'm not an expert on this field but looks like there is a bug for sure on how chat sessions are handled with different models.

Also this should explain why it trigs the errors above, the chat is probably referencing to indices that has been previously removed. Thinking about this I'd say I should start new chats more often.

**Comment by lramos15** [comment]
Closing for now, it appears Claude may be a little bit unhealthy at times. Starting a new chat / trying again tends to fix it. Thank you for your patience.

**Comment by MoParsley** [comment]
> same here. claude is much lower than gpt-4o...

I would agree, but Claude doesn't get stuck like gpt-4o. Sometimes chat gpt-4o says it does things and does nothing. Claude is what I use to break through walls and them use gpt to build code more with more stability.
