### ISSUE TITLE
Language model unavailable

### ISSUE THREAD

**Issue by KaarloosT** [microsoft/vscode-copilot-release#2159]
Type: <b>Bug</b>

i wanna ask questions, but all the time i get the same message

Extension version: 0.22.0
VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 6.8.0-44-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.94GB (10.91GB free)|
|Process Argv|--crash-reporter-id f4b67d37-7052-430b-a9cd-a1e4219ac93e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: dev.kaarloost.es|
|OS|Linux x64 6.8.0-44-generic|
|CPUs|AMD EPYC-Milan Processor (2 x 0)|
|Memory (System)|3.78GB (1.21GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
iacca2:31156134
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by lramos15** [comment]
Can you include your logs via CTRL + SHIFT +U -> GitHub Copilot Chat

**Comment by KaarloosT** [comment]
2024-11-01 00:21:23.136 [info] Logged in as *******
2024-11-01 00:21:23.934 [info] Got Copilot token for *******
2024-11-01 00:21:24.117 [info] copilot token chat_enabled: true, sku:
monthly_subscriber
2024-11-01 00:21:24.302 [info] Fetched model metadata in 86ms
3a8a969c-964e-4727-89b2-05ccecda4f59

**Comment by roblourens** [comment]
Please share any logs in the "Copilot Chat" output channel, and if you know how you got in this state, please share: https://github.com/microsoft/vscode-copilot-release/issues/2116

Restarting VS Code may work around this for you
