### ISSUE TITLE
Attach error output as context

### ISSUE THREAD

**Issue by golergka** [microsoft/vscode-copilot-release#2169]
I'm using Aider and Copilot chat on and off. I like the fact that Copilot chat has nicer UI and integration with the editor. However, running tests and then piping the results is much easier in Aider — just type !, and then you got a command line, without having to switch between any views and typing any additional commands. Copilot Chat, of course, also allows sending terminal output to chat, but it's not as pleasant in terms of UI for a vim-liking user who tries to never lift his hands from the keyboard.

However, VSCode has an advantage of being a text editor with integrated plugins for such tasks as typechecker, test runner, and so on. And these plugins direct all their output to unified destination — error view. Copilot Chat can easily utilize it. It already has "Attach context" command which allows to select different files or other data from the editor. Adding another option there, which access the error list, shouldn't be that hard.

If this project is open to third-party contributions and maintainer greenlits this feature, I would be happy to implement it. I have experience developing electron and monaco-based IDEs, so I think I would met this project's quality bar.

**Comment by isidorn** [comment]
Thank you for your offer and sharing your thoughts. 
We are thinking about exposing the problems view in chat as context. However this area is currently not open for contributions. If you would like to. contribute to VS Code in other ways I suggest you check out the vscode repo https://github.com/microsoft/vscode and the contributing section in the wiki
