### ISSUE TITLE
Model not available

### ISSUE THREAD

**Issue by usoni1** [microsoft/vscode-copilot-release#2172]
Type: <b>Bug</b>

When I try to talk to the model, it just says model not available. 

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'amlext+2f737562736372697074696f6e732f38313031393064332d633737392d343736382d616665632d3363313538656339383533612f7265736f7572636547726f7570732f696875622d6c74632d6d6c2d7561742d72672f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f696875622d6c74632d7561742d6d6c2f636f6d70757465732f6c7463736f6e75746b613031' could not be established
Remote OS version: Linux x64 5.15.0-1064-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.39GB (2.56GB free)|
|Process Argv|--crash-reporter-id c86814e9-f06c-4af1-ae82-da90a248026e|
|Screen Reader|no|
|VM|0%|

Connection to 'amlext+2f737562736372697074696f6e732f38313031393064332d633737392d343736382d616665632d3363313538656339383533612f7265736f7572636547726f7570732f696875622d6c74632d6d6c2d7561742d72672f70726f7669646572732f4d6963726f736f66742e4d616368696e654c6561726e696e6753657276696365732f776f726b7370616365732f696875622d6c74632d7561742d6d6c2f636f6d70757465732f6c7463736f6e75746b613031' could not be established

|Item|Value|
|---|---|
|Remote|Azure ML: ltc-lab-sonutka|
|OS|Linux x64 5.15.0-1064-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 0)|
|Memory (System)|6.77GB (3.44GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc1:31134641
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-copilot-release/issues/2174
