### ISSUE TITLE
Right-to-Left (RTL) Support for Persian and Arabic Languages

### ISSUE THREAD

**Issue by hesami** [microsoft/vscode-copilot-release#2175]
Hello Team,

I would like to request the addition of right-to-left (RTL) support for Persian and Arabic languages in the GitHub Copilot Chat assistant. This feature is essential for users who write in these languages to have a better and more intuitive user experience.

Thank you for considering this request.

Best regards,

**Comment by TylerLeonhardt** [comment]
This would need to be supported by the platform, in other words, by VS Code. Marking as a duplicate of https://github.com/microsoft/vscode/issues/11770
