### ISSUE TITLE
Requet Failed

### ISSUE THREAD

**Issue by joyful0920** [microsoft/vscode-copilot-release#2178]
Type: <b>Bug</b>

All Copilot chat requests are failing now.

Extension version: 0.22.1
VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin x64 23.2.0
Modes:

**Comment by joyceerhl** [comment]
I'm unable to reproduce the request failures, can you please share a screenshot?

**Comment by joyful0920** [comment]
Hello, @joyceerhl 

Now it works. I think it was a temporary problem.
Thank you.
