### ISSUE TITLE
Rejecting edits does not correctly revert to previous state

### ISSUE THREAD

**Issue by michael-heinrich** [microsoft/vscode-copilot-release#2182]
Type: <b>Bug</b>

1. Open the new edits window with existing code. Make sure everything is saved.
2. Request a change
3. Reject the proposal
4. There are now unsaved edits in the editor window where the rejected proposal should have reverted everything to the saved state.

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 7950X3D 16-Core Processor           (32 x 4192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|95.71GB (76.22GB free)|
|Process Argv|--crash-reporter-id 92c59416-2ee1-4511-8fb5-e5a49e93dd29|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.153.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 7950X3D 16-Core Processor (32 x 0)|
|Memory (System)|46.90GB (42.41GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by joyceerhl** [comment]
This happens if you don't have the following settings

```
{
  files.autoSave": "afterDelay",
  "chat.editing.alwaysSaveWithGeneratedChanges": true
}
```

**Comment by joyceerhl** [comment]
@bpasero I am wondering if this is again hot exit kicking in to preserve unsaved file changes from the LLM even when they have been reverted by the user via the chat editing widget. What is the best way forward here? One stopgap is that we could close out the tabs that we opened, which would trigger a modal dialog asking whether to save the changes, which IMHO is redundant but AFAIK this is the only way to get the backup discarded today.

**Comment by bpasero** [comment]
@joyceerhl I am not sure I follow, note that hot exit really only plays a part when you restart or reload the window, it would not do anything within a session.

**Comment by joyceerhl** [comment]
We're setting the content of the text model directly: https://github.com/microsoft/vscode/blob/1a695f29e7b1577ebbc5b94f72d71025b97083c7/src/vs/workbench/contrib/chat/browser/chatEditing/chatEditingModifiedFileEntry.ts#L373-L378

**Comment by bpasero** [comment]
@joyceerhl if you do edits on the `vs/editor` text model, then for the workbench editor it will always show up as a change that will cause us to believe the editor is dirty (because we cannot distinguish if this change was done by the user or programmatically for a certain reason).

If you work with the workbench text editor model, then you have higher level APIs, such as `revert`, which would clear the dirty flag. 

To give an example of a method that does this, while applying edits to the underlying text model:

https://github.com/microsoft/vscode/blob/6f2d4781e857a550b7e9b05d40b969c840e264db/src/vs/workbench/contrib/search/browser/replaceService.ts#L168

If you cast the reference to `ITextFileEditorModel`, you get access to methods such as `revert`:

```ts
this.textModelService.createModelReference(this.resource) as IReference<ITextFileEditorModel>
```

It is important to `dispose` this reference after usage.
