### ISSUE TITLE
Copilot should be able to actually search files online, such as changelogs for large projects

### ISSUE THREAD

**Issue by foxieproducts** [microsoft/vscode-copilot-release#2185]
Here's a challenge: Try to get copilot to tell you the actual correct date that Python 2.7 support was removed from buildroot and which release last supported it. 

The answer is in this file: https://github.com/buildroot/buildroot/blob/master/CHANGES

According to that file, the 2022.02-rc1 release removed Python 2.7 support (February 13th, 2022), and the 2021.11.3 release was the last one that contained it, released on March 24th, 2022.

Asking copilot any variation of questions doesn't get the right answer, which tells me it isn't actually looking at the changes file. Which is odd, considering most developers would look for release notes or changelogs to find information on things like this.

**Comment by roblourens** [comment]
Copilot doesn't search the web by default, but you can do that either by using `@github #web` or installing an extension like https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-websearchforcopilot
