### ISSUE TITLE
Copilot Edits gets stuck creating readme documentation

### ISSUE THREAD

**Issue by rbalsleyMSFT** [microsoft/vscode-copilot-release#2196]
Type: <b>Bug</b>

I want edits to write me a readme.md based on the code in a folder in my repo. The chat pane seems to have a good idea of what I want, however whenever it needs to generate any usage examples, which I assume is generating a code block in markdown, edits stops and I end up with a **Usage:** heading, but no code example. 

If I do the same thing with inline editing on a new readme.md file and attach the files I want it to generate the readme.md from, it's able to do it. 

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (4.55GB free)|
|Process Argv|--crash-reporter-id 0f6c0c17-3f63-4be2-b680-ed688d88edc1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by joyceerhl** [comment]
@rbalsleyMSFT we think we have a fix for this in the latest VS Code Insiders + Copilot Chat prerelease, does it repro there still?

**Comment by aeschli** [comment]
Marking the issue as closed. If you still see a problem, we can reopen. If not, please add the 'verified' tag.

**Comment by rzhao271** [comment]
Copilot Edits finishes generating the sample README file, but it does not create a new README in the project. I'm unsure whether it is confused by the triple backticks:

![Image](https://github.com/user-attachments/assets/62560e6d-6571-4ef2-a707-bab0ddc0982c)

**Comment by hexeth** [comment]
I note that copilot edits will _start_ to write a README.md file for me, but halfway through jumps back into the editor to complete the readme, leaving some of the work the work in the markdown file and the rest of it in the chat.
![Image](https://github.com/user-attachments/assets/fce1c3b7-b041-4e6b-9e05-4b6a242129c7)

**Comment by joyceerhl** [comment]
@hexeth could you please try VS Code Insiders and the prerelease of Copilot Chat? We believe we have a fix for this there. Otherwise you can wait for the fix to come to Stable next week
