### ISSUE TITLE
Response contained no choices.

### ISSUE THREAD

**Issue by themortalcoil** [microsoft/vscode-copilot-release#2198]
Type: <b>Bug</b>

Any question to @perplexityai results in:
"Response contained no choices."

Extension version: 0.22.2024100702
VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|24.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id fc56dc7f-0982-4a1e-ba51-89d75962c439|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by themortalcoil** [comment]
Just installed the CoPilot vscode extension with the perplexity.ai copilot extension.

**Comment by yanis112** [comment]
> Type: Bug
> 
> Any question to [@perplexityai](https://github.com/perplexityai) results in: "Response contained no choices."
> 
> Extension version: 0.22.2024100702 VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z) OS version: Darwin arm64 24.1.0 Modes:
> 
> System Info
> A/B Experiments

Same error.

**Comment by themortalcoil** [comment]
I've completely reset my VSCode, removing the app, user settings, cache, etc., and then reinstalling a fresh copy with just the CoPilot extensions, with the same results. Perplexity gives this for any question: "Response contained no choices." and the copilot logs gives this warning for any language "[warning] [relatedFiles] unknown language go" just replace go with such complexities as markdown or makefiles and you get the gist.

**Comment by Jasmin68k** [comment]
Same problem here: VSCode V1.95.1, GitHub Copilot Chat extension V0.22.1, using Debian Sid on x86_64.

**Comment by themortalcoil** [comment]
If you pay for this service (as all complaints appear to be from gh pro accounts at the moment) and cannot use it, consider the refund option for Copilot when you feel you've waited long enough for support to do anything, even acknowledge this issue. It's easy: [Refund Copilot Individual](https://support.github.com/contact/account?flow=refund_copilot_individual). There's a bot that'll take care of this failure promptly.

**Comment by kinopeee** [comment]
The same problem remains unresolved. 

- VSCode 1.95.1 (Universal)  macOS 
- GitHub Copilot Chat extension v0.23.2024102903 (pre-release)

**Comment by roblourens** [comment]
This should now be fixed, let me know if not

**Comment by Jasmin68k** [comment]
From a quick test, it seems to work now. Thank you!

**Comment by themortalcoil** [comment]
Working again here as well. Thank you
