### ISSUE TITLE
chat logo missing in left panel

### ISSUE THREAD

**Issue by yxj-pri** [microsoft/vscode-copilot-release#2211]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.The "chat" logo appears to be missing from the left activity panel and cant be found.
2.

**Comment by yohames** [comment]
It is by default moved to the secondary bar so you can open the secondary bar by pressing `Alt + Ctrl + B`
there you can find copilot then follow this [video](https://github.com/microsoft/vscode-copilot-release/issues/2062#issuecomment-2449241868)
