### ISSUE TITLE
Deleting the first message confuses Copilot to ask about the previous question

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#222]
STR:
1. Ask a question
2. Delete it
3. Ask a new question

<img width="227" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/e7a9ab65-0741-4f7d-9cb5-7e2c0c36fd2e">

> Regarding your previous question, are you asking for an explanation of the code excerpt you provided or do you have a specific question about it?

> Regarding your current question, I'm not sure what you're asking for. Could you please clarify?

Seems like the conversation the service gets still has history.

**Comment by roblourens** [comment]
Not seeing this, are you sure you have the latest version of the extension? Can you share the conversation log?
