### ISSUE TITLE
Claude 3.5 sonnet error

### ISSUE THREAD

**Issue by vibheksoni** [microsoft/vscode-copilot-release#2229]
Type: <b>Bug</b>

 request id d5fc1c54-5d76-4adc-a6d2-54bbd607f6da

The claude sonnet 3.5 model isnt responding to the inline chat or the chat I think there is a request error occuring.

I just asked to change/fix code and it gave an error.

Sorry, your request failed. Please report the following request id d5fc1c54-5d76-4adc-a6d2-54bbd607f6da and try again

Tried a few times

Extension version: 0.23.2024102903
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.32GB free)|
|Process Argv|D:\\LlmEndpoint --crash-reporter-id dc49185a-7903-420e-9548-a26e72e78dba|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by vibheksoni** [comment]
Log Output (Copilot Chat)
```
2024-11-03 18:21:36.517 [info] Logged in as vibheksoni
2024-11-03 18:21:37.129 [info] Got Copilot token for vibheksoni
2024-11-03 18:21:37.139 [info] copilot token chat_enabled: true, sku: free_educational
2024-11-03 18:24:33.445 [info] message 0 returned. finish reason: [stop]
2024-11-03 18:24:33.446 [info] request done: requestId: [d812137a-8cc4-4f93-ba20-64982b2ef84e] model deployment ID: []
2024-11-03 18:24:45.364 [info] message 0 returned. finish reason: [stop]
2024-11-03 18:24:45.364 [info] request done: requestId: [3707b441-ba8c-4697-b991-1941e3848e3b] model deployment ID: []
2024-11-03 18:24:45.920 [info] Request ID for failed request: 1d142f9f-4feb-4eb8-91be-0979f69ef72b
2024-11-03 18:24:45.920 [error] Server error: 500 Internal Server Error
```

**Comment by vibheksoni** [comment]
Seems like everyone is having this issue not only me this might be a backend issue or on claudes end.

**Comment by HendricksJudy** [comment]
same here

**Comment by vibheksoni** [comment]
I fixed it by restarting vs code saw a update on pre release. Then updated and clicked the + button for new chat since the old chat was t working.

**Comment by lxyesa** [comment]
Is this still an issue? I used it today and didn't experience any unresponsiveness

**Comment by HendricksJudy** [comment]
> Is this still an issue? I used it today and didn't experience any unresponsiveness

Hi, thanks for your comment. It works but is ultra-slow and stuck when the output response

**Comment by lxyesa** [comment]
> > Is this still an issue? I used it today and didn't experience any unresponsiveness
> 
> Hi, thanks for your comment. It works but is ultra-slow and stuck when the output response

yeah, i think its response speed is nowhere near as fast as GPT4o

**Comment by vibheksoni** [comment]
If it starts getting slow just click the plus icon for new chat it speeds it up a lot

**Comment by HendricksJudy** [comment]
> If it starts getting slow just click the plus icon for new chat it speeds it up a lot

This action helps to new chat but it still getting slow when it begin to response

**Comment by tornade76** [comment]
I have the same problem with Visual Studio Code + Claude 3.5. Often the message: Sorry, no response was returned. And above all, it's very slow to get the response.

**Comment by digitarald** [comment]
A fix was deployed this morning. Please re-open if this persists, posting with your request id

**Comment by tornade76** [comment]
I constantly get this message with the use of Claude 3.5 Sonnet. "Sorry, no response was returned."

**Comment by lramos15** [comment]
@tornade76 Can you attach your Copilot Chat logs when you get that. It should be via `CTRL + SHIFT + U -> GitHub Copilot Chat`. Or clicking `Output` on the bottom panel and clicking "GitHub Copilot Chat" in the dropdown

**Comment by tornade76** [comment]
![Image](https://github.com/user-attachments/assets/d0b0fa55-1851-4af5-9cf2-3ef04fd4abfe)

**Comment by ai-slave** [comment]
@lramos15 

`2024-11-25 11:04:30.397 [info] message 0 returned. finish reason: [stop]
2024-11-25 11:04:30.397 [info] request done: requestId: [c731e1e2-2a57-450f-bf9c-f87071a6cd7e] model deployment ID: []
2024-11-25 11:04:30.786 [info] Request ID for failed request: fad5ec24-49ed-493d-a33f-238aaedfa4d4
2024-11-25 11:04:30.787 [error] Server error: 500 Internal Server Error`

**Comment by jaburges** [comment]
same here  - claude 3.5 sonnet is not having an outage as it works via Cursor AI VSCode Fork
