### ISSUE TITLE
Copilot chat disappear after upgrade of Github Copilot and Github Copilot chat extensions

### ISSUE THREAD

**Issue by SashaRabinovich** [microsoft/vscode-copilot-release#2234]
Copilot chat disappear after upgrade of Github Copilot and Github Copilot chat extensions

- Copilot Chat Extension Version:
Name: GitHub Copilot Chat
Id: GitHub.copilot-chat
Description: AI chat features powered by Copilot
Version: 0.22.1
Publisher: GitHub
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat

- VS Code Version:
1.95.1
65edc4939843c90c34d61f4ce11704f09d3e5cb6
arm64

- OS Version:
14.0 (23A344)
- Logs:

Steps to Reproduce:

1. Open vscode 
2.Observe vscode activity bar - all enabled plugins available but not chat
3. Auto completion does work
4. It work before upgrading to current release version , tried to downgrand to lower versions but issue remained
![Image](https://github.com/user-attachments/assets/0ffe0abb-01b1-4c4d-95e8-0aa371c904e4)

**Comment by T-naul** [comment]
No, it change to icon ...
![Image](https://github.com/user-attachments/assets/f0c3e018-6677-4fd8-871c-a7bf51187551)
![Image](https://github.com/user-attachments/assets/3a5093f3-143a-48c3-a20a-074b661f95aa)

**Comment by bpasero** [comment]
Please see https://code.visualstudio.com/updates/v1_95#_chat-in-the-secondary-side-bar
