### ISSUE TITLE
Inline editor got stuck

### ISSUE THREAD

**Issue by khpbvo** [microsoft/vscode-copilot-release#2237]
Type: <b>Bug</b>

Inline editor got stuck

Extension version: 0.21.2024090602
VS Code version: Cursor 0.42.4 (b1e87884330fc271d5eb589e368c35f14e76dec0, 2024-10-29T17:17:29.347Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
What do you mean by the 'Inline Editor'?
