### ISSUE TITLE
Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.95.1'.

### ISSUE THREAD

**Issue by CrankyRambo** [microsoft/vscode-copilot-release#2243]
Unable to install Github Copilot chat extension in VS Code v1.95.1

Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.95.1'.

Set up version:
- Version: 1.95.1
- Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
- Date: 2024-11-01T17:20:55.708Z
- Electron: 32.2.2
- ElectronBuildId: undefined
- Chromium: 128.0.6613.186
- Node.js: 20.18.0
- V8: 12.8.374.38-electron.0
- OS: Linux x64 6.11.3-arch1-1

- Copilot Extension Version: v1.243.1193

 - Copilot Chat Extension Version: (tried most recent VSIX  available)
 - - GitHub.copilot-chat-0.23.2024110401
 - - GitHub.copilot-chat-0.23.2024110101
 - - GitHub.copilot-chat-0.23.2024103101
 - - GitHub.copilot-chat-0.23.2024103002

Steps to Reproduce:

1. Search for "GitHub.copilot-chat" extension in VS Code Extensions marketplace - no results
2. Manually download vsix from https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat 
3. In VS Code, select Extensions menu and click "Install from VSIX" 
4. Select vsix file downloaded. Error shown in pop up:  "Error: Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.95.1'."

No additional logs

**Comment by CrankyRambo** [comment]
Some additional info - the Github Copilot Chat option is available on the VS Command  Palette (available following installing the Copilot extension). Selecting this does nothing (nothing logged to Copilot logs). Hence trying to install chat extension with VSIX. I also had to install the Copilot extension from the VSIX file as the extension was not showing up in the extensions search either.  I can successfully call Copilot Suggestions from within VS Code.

**Comment by joyceerhl** [comment]
That VSIX requires VS Code Insiders: https://code.visualstudio.com/insiders
