### ISSUE TITLE
我的vscode 中Claude 3.5 Sonnet in Copilot 不可用（没看到）

### ISSUE THREAD

**Issue by chenlip** [microsoft/vscode-copilot-release#2249]
我的vscode 中Claude 3.5 Sonnet in Copilot 不可用（没看到）
- Copilot Chat Extension Version: v0.23.2024102903 (pre-release)
- VS Code Version: 1.95.1 (system setup)
- OS Version: windos 10
- Logs: 

![Image](https://github.com/user-attachments/assets/47b8f28d-3fec-49eb-8545-9b7076b3ac48)

- 其他：
确认网络访问正常
我是github Copilot的订阅用户（每月付费）
确认了我的github上已经启用 “Anthropic Claude 3.5 Sonnet in Copilot” 
确认已经在 GitHub 上成功启用了 Copilot，并且与 VS Code 正确关联。
确认已经登录到 VS Code 中的 GitHub Copilot 扩展，并且使用的是相同的 GitHub 账户。
GitHub Copilot 已启用。
重新启动 VS Code

（卸载VSCODE,从新安装了还是不可用 ）

**Comment by lramos15** [comment]
Anthropic has restrictions in China that do not apply to the rest of the Copilot Chat product. Unfortunately Claude 3.5 Sonnet is not available in China.

**Comment by Phizumi** [comment]
> Anthropic has restrictions in China that do not apply to the rest of the Copilot Chat product. Unfortunately Claude 3.5 Sonnet is not available in China.

That's too terrible. I subscribed just for this.

**Comment by AurevoirXavier** [comment]
Either do not work in Hong Kong, China.

**Comment by developbiao** [comment]
Hope to be used in China as sonn.

**Comment by git45016683** [comment]
That's too terrible. I subscribed just for this too.   T_T

**Comment by git45016683** [comment]
but why cursor can used Claude 3.5 Sonnet in China？come on。。。

**Comment by 4kword** [comment]
你可以通过设置vscode proxy或者系统代理,就可以开启，我就是这么做的

**Comment by XuanofXXX** [comment]
I can use claude 3.5 locally, but I can't use it in my remote server. Has anyone meet this problem?

**Comment by jxrjlxc02** [comment]
> 你可以通过设置vscode proxy或者系统代理,就可以开启，我就是这么做的

我是ubuntu，点击网页端配置global后，无效，请问有没有教程？

**Comment by sunainasrivastav** [comment]
Can turn on the US proxy. Then, switching to other proxies can still be used.

**Comment by eret9616** [comment]
开美国代理有些公司内网资源就访问不了了， 有没有好心人能提供一下需要单独代理那些东西，就能支持sonnect吗
