### ISSUE TITLE
Copilot isn't working

### ISSUE THREAD

**Issue by anairax28** [microsoft/vscode-copilot-release#2257]
Type: <b>Bug</b>

Can't run copilot

Extension version: 0.22.1
VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 5, 4|
|Memory (System)|32.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 49f7c040-9f9e-4c6f-a2e8-9bed465ff6ae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by aeschli** [comment]
Can you give or details what is not working?
- installing the extension
- logging in with your GitHub Account
- asking a question in the Chat View?
See https://code.visualstudio.com/docs/copilot/getting-started for the steps

**Comment by anairax28** [comment]
When I try to use copilot : Language model unavailable
Even when I put in the chat view. I get the same message language model unavailable

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode-copilot-release/issues/2116, would appreciate more details

**Comment by roblourens** [comment]
Also make sure you install the update to get the latest VS Code version
