### ISSUE TITLE
"Start code chat" not scrolled to when you're typing

### ISSUE THREAD

**Issue by asportnoy** [microsoft/vscode-copilot-release#226]
- VS Code Version: 1.79.0-insider microsoft/vscode@666396ddec7708df2b986dcc178863faaa67c14d
- OS Version: macOS ventura
- Logs: N/A

When the code chat box (Cmd + I) is off screen and you start typing, it should scroll it into view, like it would if you were typing anywhere else

Steps to Reproduce:

1. Press Cmd I
2. Scroll it off screen
3. Start typing, observe it is not scrolled into view

**Comment by jrieken** [comment]
This is fixed in 1.80.0-insiders
