### ISSUE TITLE
Generate Commit Message with Copilot - number of characters

### ISSUE THREAD

**Issue by eStasicki** [microsoft/vscode-copilot-release#2268]
Hello! 

If possible, please add the ability to configure the number of characters generated using the “Generate Commit Message with Copilot” tool. 

Currently, this tool generates very long sentences - a great option would be to add the ability to, for example, limit the length of the proposed commit to 50 characters - where the “50” value can be varied freely, e.g. per project.

In addition, it would also be super to, for example, add a prefix that would always be included before the content of the commit:

{prefix_regex}{generated_commit_msg_from_ai}.

Greetings!

**Comment by lszomoru** [comment]
Please see [this comment](https://github.com/microsoft/vscode-copilot-release/issues/526#issuecomment-2509017787) that contains details about specifying custom instructions when generating a commit message.
