### ISSUE TITLE
Allow ESC key to close GitHub Copilot panel

### ISSUE THREAD

**Issue by bobby169** [microsoft/vscode-copilot-release#2271]
If GitHub Copilot is open, we can press the ESC key to close it. This way, we don't have to manually click the 'X' button in the upper right corner, making it faster to close.

**Comment by roblourens** [comment]
You can run the command "Toggle Side Bar Visibility" for the primary/secondary sidebar, wherever you have it, and you can even bind your own keybinding to it for 'esc'

**Comment by areding99** [comment]
Secondary sidebar is the 'auxiliary' bar for anyone else searching. My binding:

  ``` json
{
    "key": "shift+cmd+i",
    "command": "workbench.action.toggleAuxiliaryBar",
    "when": "workbench.panel.chat.view.copilot.visible"
  }
```
