### ISSUE TITLE
Ctrl-Shift-i shows "Edit with copilot" tab, but pressing it again doesn't hide it.

### ISSUE THREAD

**Issue by lennver** [microsoft/vscode-copilot-release#2279]
With ctrl-alt-i you show/hide the chat tab, so I would expect the same happening here.

- Copilot Chat Extension Version: v0.23.2024102903 (pre-release)
- VS Code Version: 1.95.1
- OS Version: Windows_NT x64 10.0.26100 (win 11)
- Logs:

Steps to Reproduce:

1. Press ctrl-shift-i so you see the Edit with copilot tab.
2. Press ctrl-shift-i again, and nothing happens

**Comment by joyceerhl** [comment]
@bpasero fixed this in https://github.com/microsoft/vscode/pull/233070/
