### ISSUE TITLE
Language Model

### ISSUE THREAD

**Issue by balajimandava-eaton** [microsoft/vscode-copilot-release#2284]
@joyceerhl  - Please see the details

- Copilot Chat Extension Version:v1.243.0 
- VS Code Version:
- Version: 1.95.1 (user setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631
- Logs:

Steps to Reproduce:

1.Add the extension and try it
2. Error: language Model Unavailable

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode-copilot-release/issues/2116, would appreciate more details
