### ISSUE TITLE
This extension is using the API proposal 'lmTools' that is not compatible with the current version of VS Code.

### ISSUE THREAD

**Issue by Rawalanche** [microsoft/vscode-copilot-release#2285]
- Copilot Chat Extension Version: v0.22.1
- VS Code Version: 1.95.1
- OS Version: Windows 11
- Logs:
2024-11-05 10:06:46.233 [error] [/c:/Users/rawal/.vscode/extensions/github.copilot-chat-0.21.2]: This extension is using the API proposal 'lmTools' that is not compatible with the current version of VS Code.
[CopilotChatLog.txt](https://github.com/user-attachments/files/17629871/CopilotChatLog.txt)

Latest VSCode version (not custom, not pre-release or insider) and latest Copilot Chat (not pre-release). Getting the ImTools error repeatedly when using the copilot chat. Tried updating VSCode and Copilot/Copilot Chat extensions. No success.

**Comment by aeschli** [comment]
From the log, it seems that you are still on `github.copilot-chat-0.21.2`. Can you make sure that 0.22.1 is used?

**Comment by Rawalanche** [comment]
> From the log, it seems that you are still on `github.copilot-chat-0.21.2`. Can you make sure that 0.22.1 is used?

This is confusing. The Extension page says I am on v0.22. Manually checking for updates says all extensions are up to date. The log still says v0.21.2 but I don't know why.

I don't use any custom setup. It's vanilla VSCode with the extension acquired through the built-in extension manager.

**Comment by sandy081** [comment]
The log you are seeing is not the current window log. This might have been recorded before you updated the extension to the latest. So please check how recent are the logs you are seeing
