### ISSUE TITLE
Problem in responsible AI service

### ISSUE THREAD

**Issue by chakib-heraoui** [microsoft/vscode-copilot-release#2286]
Type: <b>Bug</b>

I m writing a request for the copilot to help me code but it consider it as a irresponsible request and gives me this response 

Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. Learn more.

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by lramos15** [comment]
Can your provide more context about the request?
