### ISSUE TITLE
Sorry, your request failed

### ISSUE THREAD

**Issue by JungeWerther** [microsoft/vscode-copilot-release#2289]
Type: <b>Bug</b>

this happens all the time

Extension version: 0.23.2024102903
VS Code version: Code - Insiders 1.95.0-insider (38dc6ac5a771cc94bde1344722bb2d02c80096ea, 2024-10-25T22:08:52.005Z)
OS version: Linux x64 6.8.0-47-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900HX (32 x 3000)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off<br>webnn: unavailable_software|
|Load (avg)|6, 7, 7|
|Memory (System)|31.05GB (8.90GB free)|
|Process Argv|--no-sandbox --force-user-env|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by isidorn** [comment]
Duplicate
