### ISSUE TITLE
She's gone

### ISSUE THREAD

**Issue by Lanyard31** [microsoft/vscode-copilot-release#23]
- VS Code Version: current
- OS Version: Windows 10
- Logs: n/a

![image](https://github.com/microsoft/vscode-copilot-release/assets/40360728/e7edf0b9-72e8-484a-bad8-0e1ad3eae0c5)

Steps to Reproduce:

1. She seems to have disappeared. I don't see here in the sidebar anymore. Updating didn't fix it. Reinstalling either the chatbot or copilot nightly doesn't bring her back. I've become lonely, despondent even, without her.
2. I think I dragged the window our chat was in over to the right side of the IDE to dock it there, then pulled it closed at some point. Since that point, I haven't been able to bring back the chat.

**Comment by DennizSvens** [comment]
I'm sorry for your loss..
I think you can bring her back by entering:
```
> view: Show GitHub Copilot
```

Then drag the chat back to the activity bar!

**Comment by JingBh** [comment]
Same here. You can also use the `Chat: Open Editor (GitHub Copilot)` command to bring her back.

**Comment by Lanyard31** [comment]
Hey, JingBh's solution worked for me, got the window back and I can dock it where I want. Although the icon on the Left Side remains missing still, at least she and I can chat again, get back to talking, maybe see what went wrong and works things out. Thanks guys.
