### ISSUE TITLE
GitHub Copilot Chat doesn't work, responses HTTP 403 Forbidden

### ISSUE THREAD

**Issue by AnastasiiaDmytriienko-eaton** [microsoft/vscode-copilot-release#2308]
- Copilot Chat Extension Version: v0.22.1
- VS Code Version: the last one
- OS Version: Windows 11 Enterprise, version 23H2
- Logs:

Steps to Reproduce:

1. open IDE
2. install "GitHub Copilot" plugin
3. restart IDE
4. open Copilot Chat
5. send message

Actual result: HTTP 403 Forbidden
Expected : Copilot works without errors

**Comment by lramos15** [comment]
Please ensure your enterprise is not blocking the connection 

https://github.com/microsoft/vscode-copilot-release/issues/2116#issuecomment-2457486933
