### ISSUE TITLE
Language Model unavailable

### ISSUE THREAD

**Issue by GomezFran** [microsoft/vscode-copilot-release#2309]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.Write code
2.Ask Copilot

**Comment by shhintbw** [comment]
![Image](https://github.com/user-attachments/assets/bd4318cf-41b4-4017-b7ce-2f7ed7560352)

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode-copilot-release/issues/2116, would appreciate more details
