### ISSUE TITLE
Filtering UI and CSS design code 

### ISSUE THREAD

**Issue by Kindaah** [microsoft/vscode-copilot-release#231]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by Meathelix1** [comment]
I assume they mean that when they ask for certain code for CSS Co-Pilot spits out "Sorry but that has been filtered" response.

If that is the case I am also getting this with just html / css code.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/89 and some others tracking these issues
