### ISSUE TITLE
Ridiculously slow

### ISSUE THREAD

**Issue by pyromage** [microsoft/vscode-copilot-release#2310]
Type: <b>Bug</b>

Since the last update the co-pilot extension has been unusable and it slows down all my visual studio code to make it unusable.

It take minutes to respond and locks up my whole VSC while generating

Extension version: 0.22.1
VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|--crash-reporter-id 758de61d-7b5a-44c2-ac96-11a2ada21df2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by vibheksoni** [comment]
This issue seems to be occuring for me as well seems like after 1-3 responses copilot becomes extremly slow taking minutes to respond and sometimes never even responds. My vscode doesnt become slow but copilot is way slower than before something seems to have changed.

**Comment by aceslick911** [comment]
Also experiencing this - I ran a update on all my extensions and it kicked back into gear.

**Comment by aceslick911** [comment]
Just to clarify - this is using the sidebar chat feature, not inline text suggestions which work fine. If anyone would like some diagnostic information off me let me know, I'm having this issue once more and have tried updating and restarting everything. Macos VSCode

**Comment by hieuminh65** [comment]
I have this same problem. VSC becomes unusable because of GitHub Copilot. Even after I disable it, it still lagging a bit.

**Comment by edoardoCame** [comment]
same issue here. Extremely slow copilot on Linux while it works perfectly on windows on the same machine.

**Comment by blv-chelo** [comment]
ditto, Copilot takes ages to answer simple requests making it unusable

**Comment by kadr2022** [comment]
It occurred to me as well. 
VS code become very laggy after 2-3 conversation. I am on Macos (Sanoma 14.4.1)

I was using Copilot chat and with attached file. After 2, 3 response 


Github Copilot Chat - Version 0.23.2
Vs code version - Version: 1.96.2 (Universal)
Date: 2024-12-19T10:22:47.216Z (4 days ago)
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.4.0
