### ISSUE TITLE
Sorry, your request failed. Please report the following request id 72fb811d-9fbe-4e38-a8fa-961bf71d0d7e and try again

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-copilot-release#2314]
Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id 72fb811d-9fbe-4e38-a8fa-961bf71d0d7e and try again

It doesn't say to provide any more info so I'm not. If you want more info, you could update your error message to ask for it.

Extension version: 0.23.2024110503
VS Code version: Code - Insiders 1.96.0-insider (f87f8a56f3a30238076bee3db39c245bd69be264, 2024-11-05T05:04:15.310Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.85GB (39.98GB free)|
|Process Argv|--crash-reporter-id baf1f71c-33c3-4cfd-b192-986653a51161|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
g316j359:31013175
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by lramos15** [comment]
Interestingly that request shows as successful. Please attach your logs via the GitHub Copilot Chat output channel. I will update the message

**Comment by sean-mcmanus** [comment]
@lramos15 It wasn't a success, the text response was cutoff mid sentence. I might not have the logs anymore, but I can check tomorrow (or if I repro it again).

**Comment by yinbo-github** [comment]
me too, "Sorry, your request failed. Please report the following request id 1bcd5526-373a-4a6c-a236-2e9693cef713 and try again",   I've had this problem for three days！！

**Comment by lramos15** [comment]
@yinbo-github Are you using a VPN or corporate proxy of some sort? Your errors look more like network configuration issues

**Comment by pxp256** [comment]
Same issue here

**Comment by sean-mcmanus** [comment]
@lramos15 I don't have any logs -- the logs appear to disappear after I reload the window. Here's the screenshot of the aborted result:

![Image](https://github.com/user-attachments/assets/7cc3a606-50fc-41c5-8767-d2a7e6d4ad6a)

And after I re-asked the question:

![Image](https://github.com/user-attachments/assets/4a9b4872-6979-4673-b5a7-f1375f746e9c)

When try the same repro steps with the latest VS Code Insiders, it appears some recent change broke it such that it gives no valid response and it instead has a link to the working file with no changes it in, i.e. the "review my changelog" scenario is broken now. I don't see any useful logging. I could file a new issue if you want.

![Image](https://github.com/user-attachments/assets/0cc6b601-8ac7-4e3a-afd8-366694195674)

**Comment by lramos15** [comment]
@joyceerhl For thoughts regarding the copilot edits issue

**Comment by sean-mcmanus** [comment]
It sounds like it's supposed to add some edits or something to my changelog "Working Set" file, but there are no edits. I tried the "working set" feature in non-Insiders and it correctly updated with changelog with an edit.

![Image](https://github.com/user-attachments/assets/e9ffdbeb-7b7a-4458-a74a-c89d99783b91)

![Image](https://github.com/user-attachments/assets/7a7ca8b6-e4c0-4004-8a4a-743103b73b20)

**Comment by sean-mcmanus** [comment]
My new issue with Insiders appears to be the same as https://github.com/microsoft/vscode-copilot-release/issues/2261 .

**Comment by yinbo-github** [comment]
> [@yinbo-github](https://github.com/yinbo-github) Are you using a VPN or corporate proxy of some sort? Your errors look more like network configuration issues

you are right, it was a network problem, It's been fixed now, thank you!

**Comment by sean-mcmanus** [comment]
@lramos15 I haven't repro the problem again, so you can close this issue if you want. The other issue is being tracked by https://github.com/microsoft/vscode-copilot-release/issues/2261 which I added more repro info for.

**Comment by ringkubd** [comment]
Same here "Sorry, your request failed. Please report the following request id ca54ff19-99b6-4a0b-8220-abd99d88bbda and try again"
