### ISSUE TITLE
Copilot will take as context the open file, but only the lines visible in the viewport

### ISSUE THREAD

**Issue by enriquemorenotent** [microsoft/vscode-copilot-release#232]
- VS Code Version: 1.79.0-insider
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. If we ask a question about the code of the open file, it works without a problem, as seen in the image below

![image](https://github.com/microsoft/vscode-copilot-release/assets/368842/3362ac12-e9d0-4b4f-beeb-f513c9b64d96)

2. If we scroll downwards, until most of the lines of code are hidden from the viewport, Chat isn't able to answer the same question, as seen in the picture below.

![image](https://github.com/microsoft/vscode-copilot-release/assets/368842/0227e032-2fec-46de-91f5-eaa30acec4b2)

This must be a bug, I assume.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/14

**Comment by MichaelLorentzTR** [comment]
I had this same exact same concern. I found that if I highlight the entire file (Control + A) it is able to "see" the entire file.
