### ISSUE TITLE
chat dialog back to left

### ISSUE THREAD

**Issue by Ricky816845** [microsoft/vscode-copilot-release#2324]
Is there any chance or options to move the chat dialog back to left slide?

My screen not so big to use both side...

Thanks.

**Comment by bpasero** [comment]
It is easy to bring the chat back to the primary sidebar, just drag and drop it over:

https://github.com/user-attachments/assets/eadb8493-cec8-4848-81d2-4f980e1bae54

**Comment by Ricky816845** [comment]
Got it. Thank you !
