### ISSUE TITLE
Elements in brackets (ex: JSX, HTML elements) not appearing in Copilot Chat history

### ISSUE THREAD

**Issue by Spookywy** [microsoft/vscode-copilot-release#233]
- VS Code Version: 1.80.0-insider
- OS Version: 13.4 (22F66)
- Logs: -

Steps to Reproduce:

When asking questions to Copilot chat which include brackets such as `<head>` or `<Text>` (HTML element, JSX element ...) there are not appearing in the chat history.

Ex: If I type "What is `<header>` for?" The history will only show "What is for?"

<img width="464" alt="Capture d’écran 2023-06-11 à 16 26 26" src="https://github.com/microsoft/vscode-copilot-release/assets/109912731/31e4095e-2f0a-4c3b-be00-d42e38ecdcd6">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/107
