### ISSUE TITLE
Language model unavailable - macos

### ISSUE THREAD

**Issue by WZHRACR** [microsoft/vscode-copilot-release#2333]
Type: <b>Bug</b>

I just installed the extension added the license and everything doesnt work

Extension version: 0.22.1
VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by crisbenamck** [comment]
same error

![Image](https://github.com/user-attachments/assets/713d0432-cd1d-4ba4-a1d6-74527b2c0f34)

**Comment by roblourens** [comment]
See #2116 - could use some help grabbing logs to help us understand the issue, thanks
