### ISSUE TITLE
MD code appear in wrong format

### ISSUE THREAD

**Issue by Quentin-Gillet** [microsoft/vscode-copilot-release#2337]
Type: <b>Bug</b>

I ask the ia to give me md code, But it was interpreted by the copilot windows and wasn't copiable at all

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by aeschli** [comment]
Can you add a screenshot and paste the input and output of the chat so we can invstigate?

**Comment by Quentin-Gillet** [comment]
![Image](https://github.com/user-attachments/assets/90e93488-91b4-434b-b819-d3cf72f6791a)

Input: write a read me file in markdown, with how to use the script, lauch it with the args and what the args does a little recap of what the code do (Codebase linked)

Output:

```
# 20_recode_impact_links

This project contains scripts for processing and analyzing impact data related to vehicle models and their associated service headers.

## Usage

To use the script, run the `scheduled_checks.py` file with the required arguments.

```bash
python scheduled_checks.py -u <username> -p <password> --hmd-path <hmd_file_path> --service-info-path <service_info_file_path> --operation-data-path <operation_data_file_path> --output-path <output_directory> [--use-history] [-d <delay>]
```
Arguments
-u, --username: Username for VCN account (required).
-p, --password: Password for VCN account (required).
--hmd-path: Path to the HMD data file (required).
--service-info-path: Path to the Service Info data file (required).
--operation-data-path: Path to the Standard Times data file (required).
--output-path: Output directory for the generated Excel files (required).
--use-history: Use cached data if available (optional, for local development).
-d, --delay: Delay in seconds between each impact request (optional, default is 0.45).
Description
The script performs several checks and data processing tasks related to vehicle service data, including:

Scraping service data from the Impact online platform.
Processing data from HMD, Service Info, and Operation Data Excel files.
Generating Excel reports highlighting discrepancies and missing data between HMD and Impact data.
Checking for missing IH numbers, product classes, models, standard times, and discrepancies in titles and function groups.
Running the Script
Ensure that all required Excel files are available and provide the correct paths to these files. Then run the script with the necessary arguments.

**Comment by aeschli** [comment]
The code block that the LLM returns includes the same backticks as the code block.

We could either instruct the LLM to be more careful with nested backticks, or handle that better when rendering

**Comment by roblourens** [comment]
@aeschli this comes up somewhat often- see https://github.com/microsoft/vscode-copilot-release/issues/793. I think we could give it an example of how to do nested codeblocks but I haven't taken the time to experiment.

**Comment by roblourens** [comment]
I'll just dupe it, I saw you assigned yourself, lmk if you'd like to do something with it
