### ISSUE TITLE
Minor but somewhat annoying bug with automatic scrolling after chat message is sent

### ISSUE THREAD

**Issue by Davidasx** [microsoft/vscode-copilot-release#2340]
# Minor but somewhat annoying bug with automatic scrolling after chat message is sent
- Copilot Chat Extension Version: Copilot Chat 0.22.1
- VS Code Version: 1.95.1
- OS Version: Arch Linux x86-64 latest packages

This isn' a big problem but can be somewhat annoying at times.
![Image](https://github.com/user-attachments/assets/80b76c36-bbdd-47bc-8abf-8e175741b353)
![Image](https://github.com/user-attachments/assets/3c7b48d4-9ff6-46ac-8973-6485980469f9)

After sending a message, the chat does not scroll to exactly above my message. I know it's not very important, but it does seem to be a mysterious bug -- it's behavior is unpredictable.

Expected behavior is like this(scrolls to exactly above my message block)
![Image](https://github.com/user-attachments/assets/e5fff653-35de-4161-bf5b-6eb20e3827c0)

**Comment by roblourens** [comment]
Yeah, I don't try to scroll to a position aligned to the chat request because I want it to be clear that the rest of the chat session is still there. In a taller window, you can see some of the previous response too.
