### ISSUE TITLE
The extention keep failing with the same error

### ISSUE THREAD

**Issue by HazemAlindari** [microsoft/vscode-copilot-release#2348]
Type: <b>Bug</b>

Every time I ask copilot to make any changes in my code, it fails and gives this message with different request id: 
Sorry, your request failed. Please report the following request id 6d21f54c-eabb-4013-bf73-177e8f0c2e9c and try again

I just wake up today and this is happening, I assume it's a server side problem.

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Please include your logs via CMD + SHIFT + U -> GitHub Copilot Chat
