### ISSUE TITLE
Copilot X  - Full Project File Access 

### ISSUE THREAD

**Issue by gprethesh** [microsoft/vscode-copilot-release#235]
When I'm using Copilot X, I need to select specific code or highlight that code in order to get a solution, and sometimes it says give me the rest of the code, which I can't provide because it's in a different folder.

So it would be better if Copilot scanned all the files before answering the questions.

The engine needs to be chatgpt 4, not open AI. 

If necessary, add an option to disable or grant access to .env files.

**Comment by digitarald** [comment]
Sharing from #14: `@workspace` with _"Used references"_ landed in Copilot Chat 0.10 as part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_workspace)

<img width="657" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/9ac45254-74ae-4319-8c57-a612221b6985">

Please give it a try and file new issues for any follow-up feedback!
