### ISSUE TITLE
I am paying for Github

### ISSUE THREAD

**Issue by aysuncookie23** [microsoft/vscode-copilot-release#2351]
Type: <b>Bug</b>

How come I have to wait 6 hours? I have subscription

Extension version: 0.22.1
VS Code version: Code 1.95.0 (Universal) (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 8, 8|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 8979f77b-4812-441e-8ec7-4cdbef52961a --crash-reporter-id 8979f77b-4812-441e-8ec7-4cdbef52961a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by aiday-mar** [comment]
Hi @aysuncookie23 can you please elaborate on what you said? What do you mean by waiting for 6 hours?

**Comment by aysuncookie23** [comment]
Sure, I subscribed to Github Copilot, and I realize that I had to wait 6 hours to be able to chat with github copilot  after couple of prompts. Also why is it so slow? why when you ask it; "where is this function x located", it doesn't know?

**Comment by aiday-mar** [comment]
Concerning speed we are looking into it. Next time you hit the issue with Copilot not being able to locate code, could you please share the response with us by clicking on the thumbs down icon, which would open the context menu, in which there would be an action to share the response?
