### ISSUE TITLE
In Copilot Chat, after choosing to hide the model selection option, there is no place to bring the model picker back in the UI.

### ISSUE THREAD

**Issue by boe20211** [microsoft/vscode-copilot-release#2362]
- Copilot Chat Extension Version:  v1.243.0
- VS Code Version: Version: 1.95.1 (Universal)
- OS Version: 
- Logs:

Steps to Reproduce:

In Copilot Chat, selecting "hide" for the model selection option in the chat input hides the model picker.
There is no way to re-enable or show the model picker UI again.

**Comment by roblourens** [comment]
You can right click the run button, and check "Pick Model". You can also run "Reset all menus" to reset those hidden menu buttons

**Comment by YWzzy** [comment]
When I right-clicked the run button, there was no "Select Model" control, and cmd+shift+p did not find the "Reset All Menus" command.

**Comment by YWzzy** [comment]
OK, I ran Reset all menus, reset the menu, and now I can see the control for selecting the model, thank you
