### ISSUE TITLE
提问报错

### ISSUE THREAD

**Issue by owens493** [microsoft/vscode-copilot-release#2368]
Type: <b>Bug</b>

很抱歉，你的请求失败。请报告以下请求 ID aa71b383-64ab-4cc4-a080-a02c537cb8a6，然后重试

Extension version: 0.22.1
VS Code version: Code - Insiders 1.96.0-insider (50a2adc65b8bf6ba353c6927c2f1f19ce6701c4d, 2024-10-29T19:03:58.958Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 665f684e-aa6c-4a7f-873b-7565b8ca2753|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
parsetypescript:31116713
e80f6927:31120813
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by HendricksJudy** [comment]
3.5 Sonnet is very unstable since it released new version in the October

**Comment by lramos15** [comment]
Please utilize the latest pre-release with VS Code insiders to fix the error you're seeing.
