### ISSUE TITLE
Copy Feature

### ISSUE THREAD

**Issue by tangmcs** [microsoft/vscode-copilot-release#239]
It usually copies the whole thing, which is different from what I wanted. Sometimes I just want to copy part of the code.

**Comment by ulugbekna** [comment]
Do you mean the copy button on the code within chat? This one: 

<img width="468" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/16353531/b7ec3941-0a01-43c4-b6a8-acbac00296b0">

**Comment by tangmcs** [comment]
I mean the explanation text that I want to copy. I hit copy, but it will
copy all. But when I used ctrl C ctrl V, it was ok.
[image: image.png]

Ulugbek Abdullaev ***@***.***> 于2023年6月13日周二 17:02写道：

**Comment by ulugbekna** [comment]
Closed in favor of https://github.com/microsoft/vscode/issues/185088 because it likely needs to be fixed on the vscode side
