### ISSUE TITLE
Sorry, your request failed. Please report the following request id 1d17b4e3-0c5e-4174-9e45-bb2fe4e8a88f and try again

### ISSUE THREAD

**Issue by MarlonAEC** [microsoft/vscode-copilot-release#2394]
Not sure if it matters but I'm using VSCode Insiders:

```
Version: 1.96.0-insider (Universal)
Commit: f87f8a56f3a30238076bee3db39c245bd69be264
Date: 2024-11-05T05:04:15.310Z (2 days ago)
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.4.0
```

Also this is my prompt just in case it also matters:
```
I'm getting the following error: ERROR RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. it seems I'm implementing incorrectly this isAdmin and isLogged variables. In a nutshell what I'm trying to do is render one layout or the other in this template: #file:app.component.html
```

Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id 1d17b4e3-0c5e-4174-9e45-bb2fe4e8a88f and try again

Extension version: 0.22.1
VS Code version: Code - Insiders 1.96.0-insider (Universal) (f87f8a56f3a30238076bee3db39c245bd69be264, 2024-11-05T05:04:15.310Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 4, 4|
|Memory (System)|18.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 44114d11-43ca-48a3-b48a-2b0495055596|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
724cj586:31013169
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nb_pri_only:31057983
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
i21gd607:31141543
iacca1:31150324
notype1:31143044
dwcopilot:31158714
g7688163:31155431

```

</details>

**Comment by MarlonAEC** [comment]
Well it just re-run by himself and now it's working not sure what it was.

**Comment by lramos15** [comment]
I see you are using the stable Chat version but the insiders version of VS Code. I recommend if using insiders that you also use the pre-release of chat. Things will work much better there.
