### ISSUE TITLE
[UriError]: Scheme contains illegal characters in .cs files

### ISSUE THREAD

**Issue by Sirush** [microsoft/vscode-copilot-release#24]
Hello,
I have the following errors when sending anything in chat whenever a .cs file is the active tab :
`[UriError]: Scheme contains illegal characters`
![image](https://github.com/microsoft/vscode-copilot-release/assets/5435333/5d7af03e-46b2-4ff0-b25b-804a067c9bea)

It doesn't matter if the file has code or is empty. C# code in a file with another extension than .cs works correctly.

Version: 1.79.0-insider (user setup)
Commit: f1258a5fbed44b8f84a097c73c1799c13c5c3646
Date: 2023-05-17T05:27:38.052Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Create a file named "bug.cs"
2. Open it and interact with copilot chat

**Comment by lramos15** [comment]
<img width="747" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/20a8631d-6d1d-4a08-8fe8-1af22bda94de">


Here's the steps I did to try and repro

**Comment by ap-waaijenberg** [comment]
I have installed Copilot in combination with VS Code and I get this very same error when working on a C# file. Note this is not all the time, but most of the time. VS and every Copilot extensions are up to date, SDK is in place. Restarting VS sometimes help, but not always.
