### ISSUE TITLE
Inline chat keeps proposing to put simple code changes into new test files

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#240]
STR:
- Open [sample typescript project](https://github.com/stevencl/test-contacts)
- In user testing the task was to add validation to the `put` method, validating user.

Nearly every participant his the issue that inline chat suddenly suggested `inline.test.ts`. Even moving to different lines and rephrasing couldn't get inline chat out of the habit.

<img width="500" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/3142b55f-58ae-4c4a-8454-7295d4f34c04">

<img width="500" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/aaa545ac-48fe-4138-8e2b-73a87c519009">

cc @stevencl @isidorn

**Comment by ulugbekna** [comment]
This should have become a lot better!
