### ISSUE TITLE
Not completing using Claude preview.

### ISSUE THREAD

**Issue by Ontic-Entity** [microsoft/vscode-copilot-release#2405]
Type: <b>Bug</b>

Copilot request with claude 3.5 not completing.

Extension version: 0.22.1
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by lramos15** [comment]
Can you include the request you're trying to make and your logs.

Your logs can be accessed via CTRL + SHIFT + U -> GitHub Copilot Chat
