### ISSUE TITLE
Markdown displayed in a way that cant be copied. 

### ISSUE THREAD

**Issue by portfedh** [microsoft/vscode-copilot-release#2407]
Type: <b>Bug</b>

I asked copilot to create a readme file. 

It created a markdown of the file, however i cant copy or apply all of the info, since some of it seems to be stying the copilot window (breaking the resonse into several separte windows that cant be copy pasted. 

Extension version: 0.22.1
VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|6, 6, 6|
|Memory (System)|8.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id cf7ca913-68a3-4e9c-949b-5be945263213|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by jrieken** [comment]
> (breaking the resonse into several separte windows that cant be copy pasted.

Can't you copy-paste each response part separately? Can you ask the AI to reply with a single code chunk? You can use the `github.copilot.chat.codeGeneration.instructions` setting for this

**Comment by portfedh** [comment]
Ive tried asking for a single code chunk, to display as unformatted text etc but it doesn't really work. 

I could paste arrount 70% of the answer, but other parts simply don't copy paste  correctly. 

I wouldn't flag this as an urgent or very important feature, but ideally it shouldn't happen.

**Comment by anthony-murphy** [comment]
for me it frequently missed the closing  ` ``` ` on code blocks, which leads to the nested code block ending at the generated content end, and breaking the formatting of the chat as generated content, and chat content are no longer appropriately separated

**Comment by roblourens** [comment]
Sounds like you're hitting https://github.com/microsoft/vscode-copilot-release/issues/793

You could right click > copy the response
