### ISSUE TITLE
Pasting HTML in the chat shows as plaintext

### ISSUE THREAD

**Issue by runa** [microsoft/vscode-copilot-release#241]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. copy some HTML
2. paste it in the chatbox
3. it looks like this: 
![image](https://github.com/microsoft/vscode-copilot-release/assets/57866/b4b3f7b2-94df-4184-837d-57ca3fa234b8)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/107
