### ISSUE TITLE
Github Copilot not working - requires to sign-in to github (buttons don't work)

### ISSUE THREAD

**Issue by demiro** [microsoft/vscode-copilot-release#2430]
- Copilot Chat Extension Version: v-0.22.2
- VS Code Version: 1.95.2
- OS Version: Win 11
Steps to Reproduce:

1. Open VSCode
2. Try to type something to trigger Copilot or ctrl + alt + i to open chat

![Image](https://github.com/user-attachments/assets/0c7a7ec9-2ef7-4e22-b414-bb157f0ecf97)

Is showing me I need to log in, even though on github tab I am logged in...
If I try to click on the buttons or links to login, nothing happens

have this issue only on this repo (even though I am logged in with my personal account where I pay)... it was not working for couple of days... yesterday for a reason it was, and today not working again (don't know what changed).

**Comment by fmorenobuendia** [comment]
I have the same problem

**Comment by TylerLeonhardt** [comment]
Do you still see this?

**Comment by fmorenobuendia** [comment]
No, it solve for me now, thanks
