### ISSUE TITLE
Sorry, your request failed. Please report the following request id b8a1bcdb-fb9a-4671-bb11-a233762b19bf and try again

### ISSUE THREAD

**Issue by j-w24** [microsoft/vscode-copilot-release#2436]
Sorry, your request failed. Please report the following request id b8a1bcdb-fb9a-4671-bb11-a233762b19bf and try again

**Comment by j-w24** [comment]
The editor could not be opened due to an unexpected error: Failed to get model for chat editor. id: afb7461d-88f7-4bea-9af7-4538f2e708a6

**Comment by lramos15** [comment]
Can you include your logs please via CTRL + SHIFT + U -> GitHub Copilot Chat. Or on mac CMD + SHIFT +U -> GitHub Copilot Chat
