### ISSUE TITLE
Unable to access Chat despite meeting requirements

### ISSUE THREAD

**Issue by AlexLloyd0** [microsoft/vscode-copilot-release#244]
- VS Code Version:1.78.0-insider (Universal)
- OS Version: macOS Ventura 13.2
- Logs: No logs appear in the `GitHub Copilot Chat` extension. `GitHub Copilot` has `[INFO] [copilotIgnore] [2023-06-14T13:34:58.603Z] inactive`

**Requirements:**
> Only works with [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/).

Confirmed, running insiders 1.78.0

> [GitHub Copilot Nightly](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-nightly) must be installed alongside Copilot Chat.

Confirmed, running version from 2023-6-14

> Your GitHub account that is signed into VS Code must have an active [GitHub Copilot subscription](https://docs.github.com/en/copilot/quickstart#signing-up-for-github-copilot) and must be accepted to the GitHub Copilot Chat preview (join the [waitlist](https://github.com/github-copilot/chat_waitlist_signup/join)).

Confirmed, on this GitHub account (my only one):
<img width="488" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/14766017/c5bbc566-e917-4406-83e8-6c81b0232cd9">

Copilot suggestions work fine in the editor, but there is no chat icon in the sidebar, nor any actions in the cmd+shift+P menu under copilot chat.

**Comment by davecheney** [comment]
Please try updating insiders, 1.78 is very old, 1.79 is the current stable non insiders release.

**Comment by AlexLloyd0** [comment]
Thanks! https://github.com/microsoft/vscode/issues/7426#issuecomment-425093469 was blocking insider updates. Updating to 1.80.0 worked!

**Comment by AlexLloyd0** [comment]
Maybe worth mentioning in the requirements that it only works with recent versions of Insiders?

**Comment by AlexLloyd0** [comment]
I wasn't receiving notifications, I believe checking for updates failed because of https://github.com/microsoft/vscode/issues/7426. Not that it's particularly relevant here.

Suggestion: update

> Only works with [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/).

to 

> Only works with Visual Studio Code 1.79+

**Comment by lramos15** [comment]
That updated doc string isn't correct either. The extension will continue to break if you do not keep the extension updated to insiders just due to the rapid changes which must be done as this extension is quite new.
