### ISSUE TITLE
"Add Selection to Chat" adds entire file to chat

### ISSUE THREAD

**Issue by M1kep** [microsoft/vscode-copilot-release#2456]
- Copilot Chat Extension Version: Latest release and pre-release: v0.23.2024102903 (pre-release)
- VS Code Version:
```
Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
```
- OS Version: Linux x64 6.6.59-1-lts
- Logs: I don't see anything logged when the action is performed.

Steps to Reproduce:

1. Highlight text in a file
2. Right click -> Copilot -> Add Selection to Chat
3. See there is not line number indicator in chat attachment, model claims to see full context, and warning will appear for very large files.

**Comment by joyceerhl** [comment]
This should be fixed in the latest Insiders.
