### ISSUE TITLE
Feature Request: Add History Tracking for Copilot Edits

### ISSUE THREAD

**Issue by BobbyWang0120** [microsoft/vscode-copilot-release#2460]
**Description**
I believe that the Copilot Edits feature would greatly benefit from adding a history tracking function. Often, I use Copilot Edits to accomplish a series of related tasks. As these conversations build on each other, Copilot becomes more effective at understanding my intentions because of the context from previous interactions. If I take a break from the project and return later, it can be difficult to regain that momentum, as there’s currently no way to retrieve the prior Copilot Edits interactions. Instead, I have to open a new Copilot Edits session and re-explain my project goals to try and re-establish the same understanding.

**Proposed Solution**
A history tracking feature for Copilot Edits could resolve this issue. By allowing users to revisit past interactions, similar to the chat history provided in tools like ChatGPT or Claude’s web interfaces, users could easily resume their work without losing valuable context. This feature would make it much easier to pick up where we left off, reducing the need for redundant explanations and making Copilot more effective in ongoing projects.

**Benefits**

- Improved continuity across sessions

- Enhanced productivity by reducing the need for repetitive explanations

- Better project context retention, which allows Copilot to provide more accurate suggestions

Thank you for considering this request!

**Comment by joyceerhl** [comment]
With last week's 1.96 release, we now persist Copilot Edits sessions https://code.visualstudio.com/updates/v1_96#_restore-edit-sessions-after-restart. We don't yet allow to retrieve multiple sessions though.

**Comment by mieaw** [comment]
Hey there!
Bump! We need functionality like Cursor. We pay the same amount for Cursor, but we like Copilot because it's from Microsoft, and this big company has always built strong products. They have the entire GitHub and Azure, so we think it will have a bright future.

Example of UI:

![Image](https://github.com/user-attachments/assets/d8a1ca6e-ed88-4eee-9fbf-5d9f15efe176)

**Comment by mieaw** [comment]
+ Just add that button for history. I know it's not that simple, but I feel like this will be available in the next version:   ![Image](https://github.com/user-attachments/assets/65ef80ca-55c6-4761-8848-3a790cf57033)

**Comment by dsiervo** [comment]
I just lost an entire prompt where I explained every detail of the edits I wanted. I accidentally clicked 'done' and lost everything. Now, I can’t even follow up on the edits. This feature is urgently needed. It’s incredibly frustrating to start over after spending so much time carefully explaining every single detail

**Comment by good-dev-student** [comment]
> I just lost an entire prompt where I explained every detail of the edits I wanted. I accidentally clicked 'done' and lost everything. Now, I can’t even follow up on the edits. This feature is urgently needed. It’s incredibly frustrating to start over after spending so much time carefully explaining every single detail

same bump up

**Comment by jozefKruszynski** [comment]
Same issue, this is most frustrating

**Comment by joyceerhl** [comment]
@dsiervo does chat input history work for you? You should be able to hit the up arrow in the Copilot Edits input box to bring back a previously-submitted prompt
