### ISSUE TITLE
It keeps outputting the same thing no matter what I type.

### ISSUE THREAD

**Issue by aaronyagnik** [microsoft/vscode-copilot-release#2469]
Type: <b>Bug</b>

It keeps outputting the same thing no matter what I type.

Extension version: 0.22.2
VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 23.6.0
Modes:
Remote OS version: Linux x64 5.14.21-150400.24.111_12.0.91-cray_shasta_c

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (2.17GB free)|
|Process Argv|--crash-reporter-id d04fa892-06cc-463c-9144-34601d7b7ef3|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: perlmutter.nersc.gov|
|OS|Linux x64 5.14.21-150400.24.111_12.0.91-cray_shasta_c|
|CPUs|AMD EPYC 7713 64-Core Processor (256 x 0)|
|Memory (System)|503.14GB (304.85GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by bhavyaus** [comment]
Can you please describe what type of request you're making so we can reproduce the issue? Example files / queries will help a lot. You can also try clearing your chat history.
