### ISSUE TITLE
/doc suggests method body even when body already exists (C#)

### ISSUE THREAD

**Issue by Hefaistos68** [microsoft/vscode-copilot-release#247]
When I use the /doc on any C# method, it always suggests an, mostly empty, method body along with the usually correct XML documentation suggestion.

![doc](https://github.com/microsoft/vscode-copilot-release/assets/8855055/5154f8f8-60fd-474a-aa32-f25cc49dfa04)

Version: 1.79.1 (user setup)
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce: see image above

PS: why is this functionality not available in Copilot chat for VisualStudio 2022 ??????

**Comment by ulugbekna** [comment]
This should be fixed in today's release :-)
