### ISSUE TITLE
{"statusCode":413,"message":"request entity too large"}

### ISSUE THREAD

**Issue by Yoniiiiiiiiii** [microsoft/vscode-copilot-release#2480]
Type: <b>Bug</b>

**After any msg to the chat I get:**

"Sorry, your request failed. Please report the following request id 434ae20b-5f54-4a5c-a233-97389ca181f0 and try again"

**Log output:**
[info] message 0 returned. finish reason: [stop]
[error] Error parsing extraData for request id ad8ff1ef-b69f-4cc1-a57c-1dcb6ab4bd4f: data: [DONE]
[info] request done: requestId: [ad8ff1ef-b69f-4cc1-a57c-1dcb6ab4bd4f] model deployment ID: []
[info] Request ID for failed request: 434ae20b-5f54-4a5c-a233-97389ca181f0
[error] Request Failed: 413 {"statusCode":413,"message":"request entity too large"}

Extension version: 0.22.2
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.4.0-196-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.44GB (16.04GB free)|
|Process Argv|--crash-reporter-id 7ef2c170-a2f9-4c91-acab-b5ae94063961|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Remote-VM-Container-ioe-dev-portia|
|OS|Linux x64 5.4.0-196-generic|
|CPUs|Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz (4 x 0)|
|Memory (System)|7.73GB (5.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
nativeloc1:31134641
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by lramos15** [comment]
I am aware this issue is quite old as it is taking us longer than expected to get through all the issues. Are you still seeing this?
