### ISSUE TITLE
It Is buggy since the last update on VSCode for Mac

### ISSUE THREAD

**Issue by danilopsss** [microsoft/vscode-copilot-release#2481]
Type: <b>Bug</b>

Some requests are not being concluded.

Extension version: 0.22.2
VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|36.00GB (1.52GB free)|
|Process Argv|-n . --crash-reporter-id 8a02b6d7-91a3-4497-b652-c8d3da1ac09b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by danilopsss** [comment]
Adding more context. Since the last update some requests are failing as the following image or loading forever.
![Image](https://github.com/user-attachments/assets/8bb8c51b-0550-47b7-a3d4-5147dff1a3a4)

**Comment by lramos15** [comment]
Can you include your logs via CMD+SHIFT+U -> GitHub Copilot Chat
