### ISSUE TITLE
Sidebar can capture editor input

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode-copilot-release#2483]
- Copilot Chat Extension Version: v0.22.2
- VS Code Version: 1.95.2
- OS Version: MacOS 15.0.1

Focused editor panes began to ignore my keystrokes. I could see the caret blinking and select text, I could use keyboard shortcuts, I could still type in other panes like the terminal. But my keyboard input to the editor pane was apparently being ignored. I had to reload the window.

Later I opened the Chat sidebar… and found my missing editor input in the "Ask Copilot" text box. So somehow my keystrokes were being redirected there from the editor pane.

**Comment by roblourens** [comment]
I think you're seeing https://github.com/microsoft/vscode/issues/231082, fixed in Insiders
