### ISSUE TITLE
didnt respond failed to respond

### ISSUE THREAD

**Issue by jaitechsols** [microsoft/vscode-copilot-release#2486]
ADD ISSUE DESCRIPTION HERE

Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Embedder: codespaces

Extension version: 0.22.2

**Comment by bhavyaus** [comment]
Can you please describe what type of request you're making so we can reproduce the issue? Example files / queries will help a lot. You can also try clearing your chat history.
