### ISSUE TITLE
Copilot should not reactivate its own tab, or re-open its own window.

### ISSUE THREAD

**Issue by thclark** [microsoft/vscode-copilot-release#2488]
Whenever I rebuild a devcontainer or some other significant event, the copilot chat box activates (or re-opens). This happens whether it's in it's new location on the right, or when occupying the old old location alongside all the other tools on the left.

When you set up your IDE or activate a tab, you do it for a reason and it's incredibly annoying to have your layout reset by a plugin.

This issue is honestly contributing to Copilot beginning to feel really spammy. If it stays this way, it's unsubscribe time, particularly because [copilot is inexplicably really poor compared to using `4o` in OpenAI's web browser](https://github.com/microsoft/vscode-copilot-release/issues/2445) so we have to use that for any actually hard questions anyway. The new location is also incredibly annoying, having all of your tools in one area then this ugly stepchild out to the right taking up a load of screen space is just frictionful.

- Copilot Chat Extension Version: 0.22.2
- VS Code Version: 1.95.1
- OS Version: OSX Sonoma 14.6

Steps to Reproduce:

1. Open a devcontainer in vscode, with any tab other than CoPilot open (or with the copilot sidebar closed, if it's in the new right-hand location)
2. Rebuild the devcontainer
3. Observe that during build, the tab switches

**Comment by sbatten** [comment]
I can reproduce the issue. I wonder if this is an artifact of the first install experience triggering in dev container rebuild.
