### ISSUE TITLE
Files from #include directives are lost when chat presents C++ examples

### ISSUE THREAD

**Issue by lpintes** [microsoft/vscode-copilot-release#2489]
When C++ code is presented in chat responses, files are missing from #include directives.

For example if I ask "show me an example of critical section in C++", the reply is as follows:

A critical section in C++ is a portion of code that accesses a shared resource (data structure or device) that must not be concurrently accessed by more than one thread of execution. To protect a critical section, you can use synchronization mechanisms like mutexes.
Here is an example using std::mutex from the C++ Standard Library:

```
#include 
#include 
#include 

std::mutex mtx; // Mutex for critical section
int shared_resource = 0; // Shared resource

void increment()
{
    // Lock the mutex before accessing the shared resource
    std::lock_guard lock(mtx);
    // Critical section starts
    ++shared_resource;
    std::cout << "Shared resource incremented to " << shared_resource << " by thread " << std::this_thread::get_id() << std::endl;
    // Critical section ends
    // Mutex is automatically released when lock goes out of scope
}

int main()
{
    std::thread t1(increment);
    std::thread t2(increment);

    t1.join();
    t2.join();

    std::cout << "Final value of shared resource: " << shared_resource << std::endl;

    return 0;
}
```
In this example:
A `std::mutex` named `mtx` is declared.

The `increment` function locks the mutex using `std::lock_guard` before accessing the shared resource `shared_resource`.

The critical section is the part of the code where `shared_resource` is incremented.

The mutex is automatically released when the `std::lock_guard` object goes out of scope.

Two threads (`t1` and `t2`) are created to run the `increment` function concurrently.

The `join` method is called on both threads to wait for their completion.

This ensures that the shared resource is accessed by only one thread at a time, preventing race conditions.

**Comment by roblourens** [comment]
Is this the exact response copied from the chat? Can you share the whole conversation, by doing right click > Copy All?

I can't repro it, but if the include was supposed to be one formatted with angle brackets like `#include <iostream>` the it's possible that some html sanitization code broke down?

But it's also possible that it's just a bad LLM response.

**Comment by lpintes** [comment]
Hello I copied my question + response from "Accessible view". The 
conversation was minimalist, just a single prompt and a reply.


Dňa 12. 11. 2024 o 0:16 Rob Lourens napísal(a):

**Comment by roblourens** [comment]
I see, the `<...>` patterns get "sanitized" away because they are considered untrusted HTML tags.

@meganrogge it looks like you've fixed some related issues. I don't actually follow why we're using dompurify in `renderMarkdownAsPlaintext` because it's not running on HTML, it's running on plaintext, so what's to purify?

If we can't get rid of that, we would need to escape html characters, then unescape them on the other side.

**Comment by meganrogge** [comment]
@mjbvz would know about markdown sanitization. the work that I've done in that area has just been for accessibility purposes.

**Comment by mjbvz** [comment]
Yes we'll need to add some escaping for `renderMarkdownAsPlaintext`. Will fix this over on `vscode`
