### ISSUE TITLE
When will CoPilot support IntelliJ IDEA?

### ISSUE THREAD

**Issue by luoxiaofeng1029** [microsoft/vscode-copilot-release#250]
I am very honored to receive the testing qualification, but I write Java and do not use Visual Studio Code. I usually use IntelliJ IDEA. When will IntelliJ IDEA be supported?

**Comment by digitarald** [comment]
Good question and best suited for https://github.com/orgs/community/discussions/categories/copilot , as this is about VS Code's Copilot Chat support.
