### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ashutoshsharmaindia** [microsoft/vscode-copilot-release#2502]
Type: <b>Bug</b>

Sorry, your request was rate-limited. Please wait 1 hours 36 minutes before trying again.

Extension version: 0.22.2
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2627. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
