### ISSUE TITLE
Chat window disappeared

### ISSUE THREAD

**Issue by Tsuna58** [microsoft/vscode-copilot-release#251]
I had my chat window working and I used it, but now the chat window disappeared, impossible to get it back.
I checked all requirements : latest Visual Studio Code installed, latest Copilot Nightly, activated copilot subscription and inside private beta.

How can I get my chat window back ?

**Comment by lramos15** [comment]
Have you tried to reset your view locations `CTRL + SHIFT +P` -> `Reset View Locations`. It might've been moved

**Comment by Tsuna58** [comment]
Its working, thanks !

Le lun. 19 juin 2023, 16:20, Logan Ramos ***@***.***> a
écrit :
