### ISSUE TITLE
IntelliSense / TypeScript startup failure when Copilot enabled

### ISSUE THREAD

**Issue by Jjarrard** [microsoft/vscode-copilot-release#2517]
- Copilot Extension Version: 1.254.0
- Copilot Chat Extension: 0.22.2
- VS Code Version: 1.95.2
- OS Version: Mac Sonoma 14.6.1
- Logs: TypeScript server starting...

Steps to Reproduce:

1. Install Copilot extension on vs code for Mac.
2. Roll over an item to see "loading", and very large list of running but stuck tasks on the bottom notification bar.

Bottom of VS Code window starts analysing every file in the project but never finishes any.

Tried disabling all extensions and enabling one by one, Copilot is causing IntelliSense to get stuck. Tried restarting, reinstalling, clearing settings and local stores.

I had a little bit of success rolling back the version but now the issue affects all versions of Copilot.

**Comment by Jjarrard** [comment]
Node LTS
NPM latest
TypeScript latest
I will try attach a screenshot and get proper version numbers asap.

**Comment by Jjarrard** [comment]
![image](https://github.com/user-attachments/assets/3822db77-3529-45ed-9ed6-6a069c4a49d3)

![image](https://github.com/user-attachments/assets/8ddfd696-8be4-4a5d-ab66-57b406dca300)

![image](https://github.com/user-attachments/assets/8ddf68d9-86dc-4328-93b2-2abbce31dcd8)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) too?

**Comment by Jjarrard** [comment]
I cannot reproduce on VS Code insiders, I might have to use that for the time being.

**Comment by ThreeOneOneZero** [comment]
I got the same problem yesterday using windows.

IntelliSense keeps loading forever.
I disabled the extension and sometimes it finishes loading, if I keep coding it will eventually happen again.

Copilot Extension Version: 1.254.0
Copilot Chat Extension:  v0.23.2024102903 (pre-release) samething happens with release
I can help with more info if needed. This is very annoying.
![Image](https://github.com/user-attachments/assets/dd873cfa-6f90-4c4b-a8e4-746f28f509ec)

![Image](https://github.com/user-attachments/assets/dddd77a6-91f3-4926-a62f-26891f0161b9)

**Comment by mjbvz** [comment]
Ok based on @Jjarrard comment I think this has already been fixed. You can test it out in VS Code insiders

**Comment by ThreeOneOneZero** [comment]
Still having the issue, even with Insider version

![Image](https://github.com/user-attachments/assets/d09e0ff0-59fd-40e2-9fdc-809039830bd6)
![Image](https://github.com/user-attachments/assets/9132ff08-31fc-4111-a03d-fcd5d1355084)
![Image](https://github.com/user-attachments/assets/f9e683ed-cfc1-44ef-ba9b-7da6b7537c71)
No new updates, same thing with intellisense loading forever with copilot enabled!
![Image](https://github.com/user-attachments/assets/575dc651-d35c-4221-868d-c46c97399bb4)

**Comment by midkoukou** [comment]
Same

![Image](https://github.com/user-attachments/assets/308639c5-ace2-4495-8c9d-8320887857b4)

**Comment by mjbvz** [comment]
Hm can you please try collecting the TS Server log when this happens:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by ThreeOneOneZero** [comment]
> Hm can you please try collecting the TS Server log when this happens:
> 
> 1. Set `"typescript.tsserver.log": "verbose",`
> 2. Restart VS Code and reproduce the problem
> 3. In VS Code, run the `TypeScript: Open TS Server log` command
> 4. This should open a large log file called `tsserver.log`
> 
> Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out
> 
> > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

![Image](https://github.com/user-attachments/assets/6c4086ed-7779-4af3-b572-e9bdeb8d7327)
There is a lot of info here, does this help?
It happens with any project, even little ones.

**Comment by mjbvz** [comment]
@ThreeOneOneZero Those errors are typically not too concerning and shouldn't have cause this crash. Can you please share the full log? You can even try to reproduce this issue in a simple test workspace so that no private code is potentially in the logs
