### ISSUE TITLE
copilot chat in editor window wont resize to full window size

### ISSUE THREAD

**Issue by charlie-sans** [microsoft/vscode-copilot-release#252]
- VS Code Version: insider 1.80
- OS Version: windows 11 pro x86-64
- Logs: none atm
-
Steps to Reproduce:

1. just open github copilot chat window in full scren by clicking the hamburger menu
2. the in editor chat window doesnt scale to the full width of the editor window? is that suppost to hhappen

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/60
