### ISSUE TITLE
I asked "where is this happening in code" and it edited my code

### ISSUE THREAD

**Issue by juliaweingart** [microsoft/vscode-copilot-release#2544]
Type: <b>Bug</b>

Add some files in the "working set", I asked this question:
somehow this log mesage "A new message was received from the client." has messageId and conversationId columns. Where is that instrumented in these file?

And copilot keeps editing the files to add these columns, but I don't want to add the columns. The columns are already present and I don't understand where this is instrumented.

Extension version: 0.22.2
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|36.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id e06c7ada-0471-408b-aa23-2124c61edfa2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31179530

```

</details>

**Comment by jrieken** [comment]
> Add some files in the "working set", I asked this question:

Sorry, but where did you ask this question? In editor inline chat (`cmd+i`), panel chat. or chat edits?

**Comment by robot-ranger** [comment]
same experience here. i seem to have lost the ability to simply ask questions within the context of my files without assuming copilot will make edits.

remove working set files: copilot gives vague answers not relevant to codebase
leave working set files: copilot takes it upon itself to edit my files

**Comment by jrieken** [comment]
Copilot edits (cmd+shift+i) is really geared towards making edits, especially when adding files to the working set. For question it is preferable to use the chat panel.

**Comment by robot-ranger** [comment]
How do I access the chat panel? It seems to have disappeared from my extensions in the sidebar?

**Comment by jrieken** [comment]
You have these two buttons, one is for chat and the other is for edits

![Image](https://github.com/user-attachments/assets/ee10197e-bcc7-442c-ab7b-f87a9872b683)

**Comment by robot-ranger** [comment]
🤦 i was so used to the old panel i am just now realizing "edit with copilot" is a new feature, separate from chat.

**Comment by jrieken** [comment]
closing this as question but also know that we wanna overhaul the UI here
