### ISSUE TITLE
falsely rate limited

### ISSUE THREAD

**Issue by trevorbollinger** [microsoft/vscode-copilot-release#2551]
Type: <b>Bug</b>

I sent a request and immediately, it said sorry, no response can be given. i click retry, and it says I am rate limited... 

Extension version: 0.22.2
VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin x64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Please include your logs via CMD + SHIFT + U -> Github Copilot Chat
