### ISSUE TITLE
Markdown code is formatted, can't copy

### ISSUE THREAD

**Issue by sosafe-einar-olafsson** [microsoft/vscode-copilot-release#2555]
Type: <b>Bug</b>

When I ask the chat to generate a readme file for me, it will try to provide me with markdown code but it ends up being formatted by the chat window so I cannot copy the markdown code.

Extension version: 0.22.2
VS Code version: Code 1.95.2 (Universal) (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id b87e8afa-b9bc-47be-9790-0e2031ce2d85|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31179530

```

</details>

**Comment by aeschli** [comment]
Can you add a screenshot and an example prompt?

We instruct the language models to create Markdown code blocks when generating content. If the content itself is markdown, this can result in conflicting syntax.

What can help is to tell the LLM to use a different line delimiter:
`Create a Markdown document that contains a code block. Use ~~~ as code block delimiter`
