### ISSUE TITLE
Web search doesn't work. `@github` : is not working correctly.

### ISSUE THREAD

**Issue by a13-team** [microsoft/vscode-copilot-release#2568]
Type: <b>Bug</b>

Of the presented functionality, only one-third is operational. The chat feature is unstable and lacks a context window. I reinstated my paid subscription, which I had previously cancelled due to the same bugs. The issue persists. I remain disappointed.

Extension version: 0.23.2024102903
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26120
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (33.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (12 x 0)|
|Memory (System)|31.31GB (28.39GB free)|
|VM|0%|
</details>

**Comment by TylerLeonhardt** [comment]
@joyceerhl i believe they're referring to

```
@github #web
```

**Comment by joyceerhl** [comment]
@a13-team Can you please elaborate on what isn't working? Is there a specific question you ask that doesn't get answered correctly, and can you share the questions?

**Comment by a13-team** [comment]
1. The web search function is currently unavailable. Alwayse take response like: "I am unable to complete this task," etc.
2. The @github command returns an error message stating "I can't do this" for all requests. :) 
3. The context size is insufficient for medium-sized projects or even for several files with extensive code. Even two files with 500 lines each often do not fit into the context. GPT Plus and the API can accommodate five times more context (or possibly even more).
4. When performing an action with a large piece of code, such as refactoring in the chat, the process constantly loops, glitches, and at some point in the same response, it starts over as if from the beginning. 
5. It often breaks off at some point, either due to an error or exceeding the response size, and it’s impossible to continue from where it stopped or to start a new request from the middle. The inability to resume work from the previous point is very strange.
6. It regularly stops responding to requests and repeats the same thing in the response.

**Comment by TylerLeonhardt** [comment]
For number 1 and 2... can you give examples of what you're asking?
