### ISSUE TITLE
The copilot chat shows language model unavailable error

### ISSUE THREAD

**Issue by Deeksha-ramesh** [microsoft/vscode-copilot-release#2571]
- Copilot Chat Extension Version:v0.22.2
- VS Code Version: 1.95.2
- OS Version: 14.7.1 (23H222)
- Logs:

## GitHub Copilot Chat

- Extension Version: 0.22.2 (prod)
- VS Code: vscode/1.95.2
- OS: Mac

## Network

User Settings:
```json
  "github.copilot.advanced": {
    "debug.useElectronFetcher": true,
    "debug.useNodeFetcher": false
  }
```

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 140.82.112.5 (1 ms)
- DNS ipv6 Lookup: ::ffff:140.82.112.5 (3 ms)
- Electron Fetcher (configured): HTTP 200 (983 ms)
- Node Fetcher: HTTP 200 (948 ms)
- Helix Fetcher: HTTP 200 (1268 ms)

Connecting to https://api.individual.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.114.22 (38 ms)
- DNS ipv6 Lookup: ::ffff:140.82.114.22 (8 ms)
- Electron Fetcher (configured): Error: net::ERR_CONNECTION_CLOSED
- Node Fetcher: Error: Client network socket disconnected before secure TLS connection was established
- Helix Fetcher: Error: Client network socket disconnected before secure TLS connection was established

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub [![Image](https://github.com/user-attachments/assets/4919d6b6-07e7-436b-9475-bdcb5b182673)

![Image](https://github.com/user-attachments/assets/3352c4d0-bcb1-4e73-82fe-a5f00e4fcb29)
]([](Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).))
Steps to Reproduce:

1.
2.

**Comment by lramos15** [comment]
Yes as the diagnostics show and the notification shows. Your firewall is not configured properly and needs to be configured to allow this through 

https://github.com/microsoft/vscode-copilot-release/issues/2116
