### ISSUE TITLE
Add setting for markdown font size in chat view

### ISSUE THREAD

**Issue by dinhvankhoi-developer** [microsoft/vscode-copilot-release#258]
Copilot có thể có phần setting về font-size riêng được không , nó  lớn hơn 1 tý (có thể là 30px - 40px) , vì thanh bên của tôi rất nhiều extension hỗ trợ liên quan , tôi phóng to càng nhiều để copilot có chữ lớn , thì phần code nhìn rất xấu , có thể thiết lập phần setting copilot tuỳ chỉnh kích thước chữ được không  ?
```[tasklist]
### Tasks
```

**Comment by dinhvankhoi-developer** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/99070105/90a669fe-7390-4526-b792-0dfb8d9e4808)
khi viết bình thường copilot quá nhỏ , nếu phóng to thì extension thanh bên , và phần code nhìn rất xấu

**Comment by dinhvankhoi-developer** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/99070105/9b683d17-b49a-4c59-acff-0e09606e4d93)
 , nếu phóng to để đọc nội dung copilot !

**Comment by roblourens** [comment]
Thanks for creating this issue! 

However, as the description is not in English, it is hard for us to work on it. If you are able to, please edit this issue to be in English. Please do not add a new comment or create a new issue, but rather edit the existing issue. Unfortunately, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help translate.

**Comment by dinhvankhoi-developer** [comment]
Can Copilot have its own font-size settings, slightly larger (maybe 30px - 40px), because I have many sidebar extensions that support related features, and I zoom in a lot for Copilot to have larger text, but then the code portion looks ugly. Is it possible to customize the font size in Copilot settings?

**Comment by roblourens** [comment]
The copilot font size is the same as all other workbench text. You can customize the codeblock text size with `chat.editor.fontSize`, but the rest of the reply text should match the workbench- why do you want it to be a different size than other workbench elements?

**Comment by liam-k** [comment]
I already commented in #83, but since this issue is open I’d like to support it here too. The problem is that Copilot uses way more text than anywhere else in VSCode where the Workbench font is used. It’s okay to squint or go closer to the screen for a second or two, but not if you’re reading complex explanations for several minutes. That’s why more users feel the need to increase the font size in Copilot itself (but ultimately, the more elegant solution would be a customizable workbench font-size across VSCode, because other plugins suffer from the same issues.)

**Comment by jpongin-ethos** [comment]
@roblourens, I would LOVE to have this feature. Personally, I'd like to have my CoPilot chat window to have a larger font-size than the rest of the other elements in the IDE to make it easier to read without having to increase everything. I currently have the ability to +/- the font size of my code editor without effecting the rest of the fonts in the IDE, which is hugely convenient.

**Comment by jpongin-ethos** [comment]
> chat.editor.fontSize

This didn't work for me. It only changed the fontSize of certain elements within the CHAT: GITHUB COPILOT tab/window, but not the entire text output there.

**Comment by roblourens** [comment]
I think https://github.com/microsoft/vscode-copilot-release/issues/83 is a better issue to track this, so just switching to that one
