### ISSUE TITLE
why getting this

### ISSUE THREAD

**Issue by z7pz** [microsoft/vscode-copilot-release#2587]
Type: <b>Bug</b>

sending errors like:
A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://react.dev/link/controlled-components

Extension version: 0.22.2
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.60GB free)|
|Process Argv|. --crash-reporter-id c1dd29b7-837c-4bbf-be38-2880f787b696|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
h409b430:31179529

```

</details>

**Comment by aeschli** [comment]
Does this error come from VS Code?
Please provide a code sample and detailed steps that allow us to reproduce the problem in VS Code.

**Comment by z7pz** [comment]
it happens when i do not provide any information in the context rather i do select the file that i want to use information from. it happens in any file, i just need to copy the code inside the file and send it in the chat of the ai.

**Comment by aeschli** [comment]
We don't use React in VS Code. Are you using a clone of VS Code?

**Comment by z7pz** [comment]
this what i paste in the chat
```A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://react.dev/link/controlled-components```

**Comment by aeschli** [comment]
Sorry, I'm confused. I don't know what you are asking for or reporting.
Can you please describe all the steps, what's you see and what you expect.
Here is an example:
- open panel chat, select GPT4 4o as model
- write the following prompt
`A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://react.dev/link/controlled-components`
- Copilot replies with:
```
To resolve this issue, you need to decide whether the input should be controlled or uncontrolled for the entire lifetime of the component. Here is an example of how to handle a controlled input in a React component:

...

In this example, the input is controlled because its value is managed by the component's state. The value prop is always set to inputValue, and the onChange handler updates the state when the input changes.
```
The problem is:
  - this reply is not helpfult/wrong. I'm expecting `XY`
