### ISSUE TITLE
Make shortcut links always available

### ISSUE THREAD

**Issue by UndefinedCpp** [microsoft/vscode-copilot-release#259]
After having some dialogues, the shortcut links (such as "explain code", "propose a fix," etc.) are pushed to the top of the window. This means that when I need a quick answer, I have to either type or scroll up to click them, which makes me uncomfortable. Could you please make them into small icon buttons that float or sit somewhere in the window? This would be more convenient. Thanks

**Comment by roblourens** [comment]
The links are just examples and aren't meant to be the primary interaction point. The slash commands are there for this
