### ISSUE TITLE
Add all open files to Copilot Edit

### ISSUE THREAD

**Issue by colindembovsky** [microsoft/vscode-copilot-release#2590]
Files can be dragged/dropped into the Copilot Edit dialog. I would like to be able to add "All Open Files" or drag a folder from the solution explorer to add multiple files.

**Comment by joyceerhl** [comment]
This already exists in the current VS Code stable:
1. You can click Add Files and pick Open Editors which is the first entry.
2. If you have multiple tab groups open, the active editor from each group appears in your working set.
