### ISSUE TITLE
Rate-limited

### ISSUE THREAD

**Issue by robsonataide** [microsoft/vscode-copilot-release#2593]
qualquer pergunta retorna:
Sorry, your request was rate-limited. Please wait 71 minutes before trying again.

**Comment by lramos15** [comment]
Can you include your GitHub Copilot Chat output channel

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2627. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
