### ISSUE TITLE
started writing code in three files, then deleted it.

### ISSUE THREAD

**Issue by lennver** [microsoft/vscode-copilot-release#2594]
Type: <b>Bug</b>

"Sorry, no response was returned." after first writing out code in the three planned files. It then deleted it all. This happened with Copilot Edit

Extension version: 0.22.2
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26120
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 6800HS Creator Edition              (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.69GB (4.37GB free)|
|Process Argv|--crash-reporter-id b901897a-9912-4065-8cd0-a98f9aa2b4e1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by joyceerhl** [comment]
Is this with chat, Copilot Edits, inline chat, or something else? FYI, we will no longer roll back partial edits from responses that hit the length limit in VS Code Insiders + Copilot Chat prerelease, and this will come to the next VS Code stable in early December

**Comment by lennver** [comment]
> Is this with chat, Copilot Edits, inline chat, or something else? FYI, we will no longer roll back partial edits from responses that hit the length limit in VS Code Insiders + Copilot Chat prerelease, and this will come to the next VS Code stable in early December

This happened with Copilot Edits.

**Comment by joyceerhl** [comment]
Thanks, this should be fixed in Insiders: https://code.visualstudio.com/insiders
