### ISSUE TITLE
(Feature request) Copilot chat: Implement accordion

### ISSUE THREAD

**Issue by pavel604** [microsoft/vscode-copilot-release#2595]
Would be nice if every time you ask a new question all previous suggestions would fold accordion-style, only showing the question headers. 

Also would be nice if the question header itself had a different background so it's easier to spot the suggestion boundaries as you scroll (see Gemini code assist).

Also would be nice to be able to favorite and pin the accordion elements.

Thanks!

**Comment by roblourens** [comment]
Do you have a screenshot of the kind of thing that you're thinking of? I don't totally follow. What is the 'question header', is that the user's question?
