### ISSUE TITLE
Opinionated positioning — right location option gone

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#2596]
I'm reporting this as a bug because WTF. Copilot just updated and now it's dictating where it can be positioned. I keep everything on the right. I have good reasons for that. Forcing it left is not a call you should be making for me.  

Steps to reproduce: Update. 
Expected Behavior: Don't change my IDE settings
Behavior: Forces chat to left of code. 

Its performance has been bad enough lately, but this will push me to unsubscribe. 

Identifier
github.copilot-chat
Version
0.23.2024111401
Last Updated
2024-11-14, 13:47:59

**Comment by roblourens** [comment]
You can drag the chat view wherever you want it. We may try to make this more obvious with https://github.com/microsoft/vscode/issues/232797

**Comment by salientknight** [comment]
I figured that out and coming to post it. It was not intuitive and after I dragged the chat over it left the app window on the left and just moved the chat. After closing the app window everything was back to normal. Thank you
