### ISSUE TITLE
Neovim chat plugin

### ISSUE THREAD

**Issue by TheAndreLuiz** [microsoft/vscode-copilot-release#261]
Id like a Neovim copilot chat plugin, similar to the [existing plugin for copilot](https://github.com/github/copilot.vim).

**Comment by ulugbekna** [comment]
This repository is for issues related to the Copilot Chat in VS Code. 

Please, see [this](https://github.com/orgs/community/discussions/categories/copilot) forum for Copilot support in other editors.
