### ISSUE TITLE
claude stop working

### ISSUE THREAD

**Issue by Marvel-XYJ** [microsoft/vscode-copilot-release#2619]
Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id 01314abb-b1d9-47b5-80ba-5646b6cc7709 and try again

Extension version: 0.22.2
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Windows_NT x64 10.0.26100

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (2.54GB free)|
|Process Argv|--crash-reporter-id acde122b-a1df-44b0-912c-ef67dd468e7a|
|Screen Reader|no|
|VM|44%|

|Item|Value|
|---|---|
|Remote|SSH: Cyberwood-zyw|
|OS|Windows_NT x64 10.0.26100|
|CPUs|Intel(R) Core(TM) i7-14700K (28 x 3418)|
|Memory (System)|63.78GB (51.82GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl1:31139838
pythonrstrctxt:31112756
3ad50483:31144449
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
j44ff735:31181874

```

</details>

**Comment by ZeroCool22** [comment]
Same here.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-copilot-release/issues/2233
