### ISSUE TITLE
Feature: highlight generated and inserted code (usability) 

### ISSUE THREAD

**Issue by gamousquesORT** [microsoft/vscode-copilot-release#264]
I use a lot Copilot chat to generate code and insert it on my working file. Occasionally, the generated code has small bugs that are hard to find. Once the code is inserted, the only way to check the merged code and the original one is to check against the chat history or insert the code on a new file and make a diff.  It could be nice to have a way to identifiy the generated code on the source code file. Maybe highlight it in some way .

**Comment by roblourens** [comment]
It sounds like you come across this while using the inline chat widget, not the chat in the sidebar, is that right?

**Comment by gamousquesORT** [comment]
Hi, actually what I am suggesting is similar to what now happens when you generate from the inline window.

Using the inline chat the generated code pops on a new window between comments,  with what it looks like a hash. Then, when you accept,  it gets inserted keeping the comment with the hash.

On the other hand the chat window inserts at selected line, but without the comments and the hash.

what I think it could be nice, is to add to the code at the chat window a reference to the hash code, and also place it in the generated code. 

This way the developer can trace which prompt on the chat history generated that piece of code.
