### ISSUE TITLE
Garbled and Broken Text for code suggestions.

### ISSUE THREAD

**Issue by brian-w-worsham** [microsoft/vscode-copilot-release#2640]
Type: <b>Bug</b>

In VS Code, I'm asking Copilot to help me fixt my Jasmine Unit tests for my Angular project.  I share the relative component and spec file as context as well as the test failure message.  Copilot's response is broken and garbled up text which is completely unreadable and unusable.  Here is an example of the type of response Copilot provides:
```
import { ComponentFixture, TestBed } from '@angular/core/testing';
imimport { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';

import { AuthService } from '../services/authService';

iimport { ActivatedRoute, Router } from '@angular/router';

imimport { of } from 'rxjs';

impimport { provideHttpClient } from '@angular/common/http';

impoimport { Renderer2 } from '@angular/core';

imporimport { NgModel, FormsModule } from '@angular/forms';

importimport { EditRoleViewModel } from '../models/editRoleViewModel';

import 

import {describe('EditRoleComponent', () => {


describ  let component: EditRoleComponent;

  let comp  let fixture: ComponentFixture<EditRoleComponent>;

  let fixtu  let httpMock: HttpTestingController;

  let httpMo  let authService: AuthService;

  let authSer  let router: Router;

  let router:   let rou
ActivatedRoute;
  beforeEach(async () => {
 {
    const aut    const authSe      isLoggedIn: jasmine.createSpy('isLoggedIn').and.returnValue(of({ isAuthenticated: true, userName: 'testUser' }))
edIn: jasmine.crea    };
}))
    };

    
= {
      naviga         navigate: jasmine.createSpy('navigate')
y('navigate')
    };    };
 = {
      queryParam
' })
    };

    awa    const routeMock = {
le({
      imports: [Fo      que    };
s: [EditRoleComponent],


      pro
    await

      dec
 
        R

        {
 
        p

      ]

 

   }).c

    com
 
 

    rout

  });


  


    ex

    e
 


 


  it('s

    e
 


 


      e

    }
 


 


    exp

    c
 



 

    com

    e
 






    });


  }
 







    c


    

 






    })


  it









    re


    









  it('


    









    ex


    
```

Extension version: 0.22.2
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900HX (32 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.69GB (38.44GB free)|
|Process Argv|--crash-reporter-id 02574659-1347-4059-b892-9807bf7dba87|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt551:31179978
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by aeschli** [comment]
Is this with Copilot Edits?

**Comment by brian-w-worsham** [comment]
Hi @aeschli! Thanks for your response! This is from Copilot Chat in VS Code using the GPT 4o model. I've found that when I switch to any other model I no longer have this problem, but if I go back to using the GPT 4o model the broken text responses return immediately.

**Comment by brian-w-worsham** [comment]
I received an update to my VS Code Copilot extension this weekend and it seem to have resolved the issue.  Hence, I'm closing this issue now.
