### ISSUE TITLE
Rate limiting on paid plans is unacceptable

### ISSUE THREAD

**Issue by ozlanus** [microsoft/vscode-copilot-release#2641]
Type: <b>Bug</b>

I'm not hitting it very hard, just doing some iterative tailwind styling changes, and got this message

Sorry, your request was rate-limited. Please wait 4 minutes before trying again.

What are we paying for? Paid-for Cursor doesn't have this issue.

Extension version: 0.22.2
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by Oscar-Owlbangroup** [comment]
I should not be limited if paying.
