### ISSUE TITLE
Why when I choose Open Chat in a new Window it opens, but sidebar is still visible?

### ISSUE THREAD

**Issue by genyklemberg** [microsoft/vscode-copilot-release#2642]
As simple as that.
Why I still see chat in sidebar, while my chat window is opened.
Also it seems this window works differently than the sidebar chat

P.S. When chat was moved to right sidebar the screen became polluted. I want this chat to be as separate window to be moved even to my another monitor, but behave same as previously with linking to current open file.

**Comment by roblourens** [comment]
That's just how it works, the chat editor/new window is independent of the sidebar. You can move the chat panel to wherever you want by dragging it, if you want it back in the main sidebar. Or you can hide it by right clicking the icon.

> with linking to current open file.

This should be fixed in Insiders now
