### ISSUE TITLE
Bad experience when copy text from code and ask question

### ISSUE THREAD

**Issue by linonetwo** [microsoft/vscode-copilot-release#2664]
When you copy a variable name and ask question on it, copilot will say:

> I don't know the context of xxx, but I guess the implementation may be yyy.

This is because the selection is not cleared, and copilot is running on a variable-long context, instead of full text.

**Comment by roblourens** [comment]
Sorry I don't understand, can you give a more specific example?

**Comment by linonetwo** [comment]
Like this

![Image](https://github.com/user-attachments/assets/3569aaac-a438-4869-a522-7cc8002b0bab)

Usually you will copy a variable to ask things about it, but since you select a text to copy it, then Chat only see this selection.

**Comment by roblourens** [comment]
The context given currently is just the selection, so right now it likely just sees the name. You can have no selection so it sees the viewport, or select the whole function. Soon the implicit context will include more of the file

**Comment by linonetwo** [comment]
This is not about how it works, it is about user experience.

I can always deselect after copy, but that will require one more mouse click, very annoying.

> implicit context will include more of the file

Anyway if this is coming soon then it will be solved.
