### ISSUE TITLE
Repeated request errors

### ISSUE THREAD

**Issue by mila411** [microsoft/vscode-copilot-release#2677]
Type: <b>Performance Issue</b>

I merely submitted my request, and being shown the error over and over again makes me wonder what I'm paying for.

Sorry, your request failed. Please try again. Request id: 51950172-231f-4d0c-aa23-5a1e2a22208b

Extension version: 0.22.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (1.09GB free)|
|Process Argv|--crash-reporter-id 5c40cb9f-3a96-41b7-bd59-f66cd5743626|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   492	 87335	code main
    0	    98	 87338	   gpu-process
    0	    33	 87339	   utility-network-service
    0	  1868	 87341	window [1] (shell.rs — rernel)
    0	    98	 87462	ptyHost
    0	     0	 87587	     /bin/zsh -il
    0	     0	 87729	       /bin/zsh -il
    0	   754	 87463	extensionHost [1]
    0	   524	 87802	     /Users/kenny/.vscode/extensions/rust-lang.rust-analyzer-0.3.2188-darwin-arm64/server/rust-analyzer
    0	    33	 87868	       /Users/kenny/.rustup/toolchains/nightly-aarch64-apple-darwin/libexec/rust-analyzer-proc-macro-srv
    0	    66	 87898	     electron-nodejs (eslintServer.js )
    0	    66	 87899	     electron-nodejs (start-server.js )
    0	    66	 87924	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=87463
    0	   164	 88425	     electron-nodejs (server.js )
    0	   197	 87464	shared-process
    0	    66	 87465	fileWatcher [1]
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (shell.rs — rernel)
|    Folder (rernel): 1059 files
|      File types: o(178) json(102) timestamp(99) d(93) rmeta(76) rlib(40)
|                  bin(18) rs(12) lock(8) TAG(4)
|      Conf files:;
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
impr_priority:31102340
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31181875

```

</details>

**Comment by lramos15** [comment]
Do you have anything in your Copilot Chat output channel?
