### ISSUE TITLE
Cancelling a request inside Copilot Edits results in the extension becoming unresponsive, requiring a force quit to use again

### ISSUE THREAD

**Issue by Bdthomson** [microsoft/vscode-copilot-release#2684]
- Copilot Chat Extension Version: v0.23.2024102903 (pre-release)
- VS Code Version: Version: 1.95.3 (Universal)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.6.0
- OS Version: MacOS 14.7.1 (23H222)
- Logs:

Steps to Reproduce:

1. Use Copilot edits by asking a question along with a file in scope.
2. Cancel the request with the Square cancel button in the bottom right of VSCode.
3. Verify that you can no longer interact with Copilot edits or send new messages, as the "Send and Dispatch" button is missing, and the only button available is the "Cancel" button.

There is no way to fix this without completely killing VSCode altogether. Disabling Copilot and Copilot chat, switching to pre-release versions, etc does nothing. It's like the current state is being written to disk somewhere and not being cleared out of memory whenever the extension is disabled.

**Comment by jrieken** [comment]
Oh, very interesting but also something I fail to reproduce locally. You can help us by capturing a CPU profile. That will allows me to track down the issue in copilot. Please do the following 

* F1 > Show Running Extensions
* In the uppper right there is an action to start EH profiling
* start profile while CPU load is high, let it profile for a few seconds
* stop the profile and share the file with us here

Note that you might need to restart VS Code once to enable CPU profile, tho the process should guide you through this

https://github.com/user-attachments/assets/db7d97e9-09e3-4acd-a796-2926afe123be

**Comment by jrieken** [comment]
Pretty sure this is the same as https://github.com/microsoft/vscode-copilot/issues/11349
