### ISSUE TITLE
Sorry, your request failed. Please try again.

### ISSUE THREAD

**Issue by richardthorek** [microsoft/vscode-copilot-release#2697]
Type: <b>Bug</b>

using this general format, create expandable sections for the categories that get counted and displayed in the overlay. the top level categories are mapped in the categories.csv file. this will reduce the visual clutter of the overlay pane. use the pico css accordian styles which use the below format so that when you click a top level category it expands to reveal the content. <details open> <summary>Accordion 1</summary> <p>...</p>

</details> <hr /> <details> <summary>Accordion 2</summary> <ul> <li>...</li> <li>...</li> </ul> </details>
Categories.csv
map.js
:526
GitHub Copilot
Sorry, your request failed. Please try again. Request id: 2ada89f9-a7f1-40df-8185-75e91a4e2166

Extension version: 0.22.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.80GB free)|
|Process Argv|--crash-reporter-id 2afe99fd-f811-437d-ac65-52990ad27dd7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by richardthorek** [comment]
raised through context menu as requested

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-copilot-release/issues/2233
