### ISSUE TITLE
Ask for a "reason" when you down vote an answer.

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode-copilot-release#27]
When GitHub Copilot Chat answers your question, you may vote up or down the provided answer, depending on how accurate/useful it is, which is great!

I think a good improvement to this would be to ask the user to explain the reason why it voted down some answer. The reason could be, among other things:
* an improved answer (more detailed / succinct)
* a fix to the code snippet provided by GitHub Copilot (wrong and/or outdated)
* a totally different answer

Today instead, the only way to _correct_ the answer provided by Copilot Chat  is using the same input box you use today to ask a question.

Thank you

**Comment by ericktreichel** [comment]
That's a good ideia. 
After the negative vote, Copilot should offer a box with three or four different options for the user to choose whether the negative vote is related to any of these topics and, if desired, give the opportunity to write a comment and send it.

**Comment by digitarald** [comment]
Landed in insiders thanks to @roblourens, please hit those 👎 on messages and pick why they didn't meet your expectations.

This won't send prompt details, just the category – so if you want to make it specific and actionable for us there is a _Report Issue_ option as well.
