### ISSUE TITLE
Window for entering prompt to code modification stays there forever

### ISSUE THREAD

**Issue by NasvekL** [microsoft/vscode-copilot-release#270]
- VS Code Version: 1.80.0-insider
- OS Version: Ubuntu 20.04.6 LTS
- Logs: Idk which is the log you need.

Steps to Reproduce:

1. Select +1300 lines and ask it to do something with it
2. Press enter
![1be64170cd5b5f158ccdd048863ba52a](https://github.com/microsoft/vscode-copilot-release/assets/120234207/10d78768-0785-4c44-967a-7d4dd7dea07b)

It wont go away.

**Comment by jrieken** [comment]
Can you check the log of the window via F1 > Show Logs > Window...

**Comment by wynged** [comment]
Similar problem here.  Even when i move windows.  
![image](https://github.com/microsoft/vscode-copilot-release/assets/5872187/a5e01471-4e08-4bad-aadc-1c2be760e78e)

tried to accept the solution and this got frozen.  Here are the logs
![image](https://github.com/microsoft/vscode-copilot-release/assets/5872187/29da8a3a-72f0-461e-b023-de322b809953)

**Comment by jrieken** [comment]
> https://github.com/microsoft/vscode-copilot-release/issues/270#issuecomment-1603510749

@wynged Based on the screen captures it seems that you are used a old version of VS Code. Please update (VS Code and chat) and check if this still occurs. 

Also, for the future please include version numbers and please avoid commenting "seeing the same" until an issue is confirmed. Often same symptoms have different causes and it's best to keep them separate until we know for sure
