### ISSUE TITLE
tried to do complex prompt to create app and failed with error with properties of undefined (reading 'docunment')

### ISSUE THREAD

**Issue by tristanaburns** [microsoft/vscode-copilot-release#2702]
Type: <b>Bug</b>

Prompt:
"You are working within an existing Next.js 15 application. The mission is to expand its current capabilities into a functional template for a modular, scalable application. This template will include components for:

AI-Powered Workflows:

A primary AI page (./app/(core)/ai/page.tsx) using NextUI to manage AI-driven interactions.
An API endpoint (./app/api/(core)/ai/route.ts) to handle LangChain-based workflows for Retrieval-Augmented Generation (RAG) and OpenAI agent queries.
Authentication:

NextAuth setup with magic email, Google, and GitHub providers for authentication.
Database Integration:

The ./database directory and its subdirectories are designated for managing Mongoose models.
Pre-existing utility functions are available to connect to MongoDB database instances via Mongoose.
Additional models and schemas for CRUD operations and vector embeddings will be added to this directory.
State Management:

Redux (./state/core/redux/) to handle application props, histories, and nested data objects.
GraphQL:

A directory structure for GraphQL queries and mutations (./graphql/core/queries and ./graphql/core/mutations).
User Interface:

NextUI components, including a prompt container with sidebar navigation (./components/core/ui/libraries/nextui/prompt-container-with-sidebar/).
Styling utilities in ./styles/core/shadcn/ for global and component-specific styles.
Utility and Middleware Functions:

Utility functions (./utils) for API requests, logging, LangChain, and image handling.
Middleware logic (./middlewares/core) for API security, error handling, and input validation.
Core Providers:

A providers directory (./providers/core/) to manage authentication, analytics, theming, and toast notifications.
We will step through the setup process one step at a time. Each step will check for existing directories and files, creating any that are missing, and confirming their structure.

Step 1: Check and Create Directory and File Structure

Check if the following directories and files exist. If they do not exist, create them:

./app/(core)/ai/page.tsx
./app/api/(core)/ai/route.ts
./actions/core/ai/index.ts
./components/core/ui/libraries/nextui/prompt-container-with-sidebar/
./providers/core/
./graphql/core/queries
./graphql/core/mutations
./state/core/redux/
./styles/core/shadcn/
./database/core/models/ (for Mongoose models).
Confirm that the ./database directory contains the utility functions for connecting to MongoDB named instances via Mongoose.

If directories exist, confirm their presence. If files exist, append a comment like // File already exists. at the top of the file.

Extension version: 0.22.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13500H (16 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.63GB (1.77GB free)|
|Process Argv|--crash-reporter-id 4f52c256-9c39-4212-ab06-e54df3d7f700|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode-copilot-release/issues/2424
