### ISSUE TITLE
GIthub Copilot error "No se devolvió ninguna respuesta."

### ISSUE THREAD

**Issue by greennetsite** [microsoft/vscode-copilot-release#2705]
Type: <b>Bug</b>

En un alto porcentaje de las consultas, GIthub Copilot no brinda ningun arespuetsa y muestra el  error "No se devolvió ninguna respuesta."

No s epuede trabajar de esta forma. ya que en alguno casos hay que repetor la consulta hasta cinco veces. 

Extension version: 0.23.2024102903
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Linux x64 5.15.0-124-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1346)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off<br>webnn: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|15.49GB (7.02GB free)|
|Process Argv|--crash-reporter-id 4c81562b-5015-4979-a782-386aa8048db2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by jlsanzbreton** [comment]
Me acaba de pasar lo mismo, pero ya parece que se ha quedado bloqueado. En alguna ocasión repites una o dos veces a lo sumo y sigue funcionando. Pero ahora, ya van más de 8 y da igual. Está bloqueado ahí.
