### ISSUE TITLE
Sonnet powered Copilot no response bug

### ISSUE THREAD

**Issue by KexMax** [microsoft/vscode-copilot-release#2711]
Type: <b>Bug</b>

A code snippet was provided to the Sonnet model copilot chat, but it simply doesnt respond. This has happened multiple times, the system is highly unstable, these craches happen around 40% of the time, not to mention the cases when it is bound to happen 100%:
-giving a prompt using only instructions, and not including the modifyable code
-giving a too long code section
-refering to an answer the model just provided 1 prompt ago

From what I understand the model has no, or at least very limited memory of the previous prompts and its own answers, which makes it incredibly hard and tedious to work with.
I genuenly hope they will fix it asap, since - in case the model works - it excels in almost every aspect compared to the GPT-4o model (which by the way seem to have been degraded since the introduction of the Sonnet model to the point that it is barely recognizeable compared to the original ChatGPT 4o models capabilities).

Extension version: 0.22.3
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-1335U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.22GB free)|
|Process Argv|--crash-reporter-id b053f96c-eb08-4b0c-a613-5260a7ea03c2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31134642
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by roblourens** [comment]
Are you using chat in the panel, or inline chat in an editor, or the Copilot Edits view?

**Comment by KexMax** [comment]
I unfortunately dont know the difference between the panel and the edits, but what I can tell you is that I amusing the chat window that can be activated by the left side copilot icon, or the icon on the right side of the searchbar on the top. It is the chat window that is placed on either side of your screen.

From what i could gather I assume it is the panel, not the edit version.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/2116
