### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vip-ml** [microsoft/vscode-copilot-release#2713]
- Issue Type: `Performance`
- Extension Name: `copilot-chat`
- Extension Version: `0.22.1`
- OS Version: `Windows_NT x64 10.0.19045`
- VS Code version: `1.95.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/HP/AppData/Local/Temp/GitHub.copilot-chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by isidorn** [comment]
This issue does not satisfy the minimal quality standards for an issue that we would like to see in this repository.
Reproducible steps using English with latest VS Code are what helps us a lot. So please feel free to open a new issue with steps. 
Thus I will go ahead and close this one. 
Thank you
