### ISSUE TITLE
CoPilot Chat is a MESS

### ISSUE THREAD

**Issue by nick-toro** [microsoft/vscode-copilot-release#2723]
Type: <b>Bug</b>

When asking Co-pilot for suggested edits to fix CSS screen formatting issues, the edits suggested are non-sensicle.  It doesn't look like Co-Pilot is ready for prime time and instead of wasting the time of millions of VS-CODE users, Microsoft should fix this product!

Sooo Frustraaaated!!!

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.60GB (7.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Sorry for the trouble. Can you give some more details? What is the query, what are the suggested edits?

**Comment by nick-toro** [comment]
Hi RobThere are  too many issues to list. For starters, when working within VS code, copilot is incapable of reading code in an open editor window, so I literally need to cut and paste it into copilots dialog window for it to perform an analysis. This is simply impractical as the code base gets larger. Secondly, copilot tends to repeat itself often and doesn’t provide actual answers to the query. Instead, it simply regurgitates the code I pasted into its window. Third, when it does provide a suggested change, instead of providing just the suggested change, it replays the entire file requiring to hunt for the one or two lines that need to be edited. Very disappointing product.  Nick Sent from my iPhoneOn Dec 3, 2024, at 8:32 PM, Rob Lourens ***@***.***> wrote:﻿
Sorry for the trouble. Can you give some more details? What is the query, what are the suggested edits?
