### ISSUE TITLE
The claude ai isn't working

### ISSUE THREAD

**Issue by Dwarfzz** [microsoft/vscode-copilot-release#2724]
Type: <b>Bug</b>

I want to ask something to the claude model but it is not working

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (4.49GB free)|
|Process Argv|--crash-reporter-id 8303d02f-00be-4f3d-b036-2254e0ae7136|
|Screen Reader|no|
|VM|80%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31185842
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by roblourens** [comment]
Are you using chat in the panel, or inline chat in the editor, or the Copilot Edits view?

**Comment by Tiberriver256** [comment]
Same for me. I've been using the copilot edits view. It usually fails to come back with any kind of response. o1-preview works flawlessly.

**Comment by illGATESmusic** [comment]
same for me. I can't even get a response out of it in VSCode now :/

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-copilot-release/issues/2116
