### ISSUE TITLE
Error always thrown: r.mkdir.__promisify__ is not a function

### ISSUE THREAD

**Issue by filiprejmus** [microsoft/vscode-copilot-release#273]
- VS Code Version: 1.80.0-insider (Universal) Commit: 636dbcff557af8aa088ae118b1a094dce6632ce7
- OS Version: MacOS 14 Beta 1
- Logs: None, Chat history: 
filiprejmus: Write a Datagrid component with 5 example rows and 4 example columns with white background, rounded corners and slight shadow

GitHub Copilot: 
Chat: v0.3.2023062106
Nightly: v1.92.178

Steps to Reproduce:
1. Ask the query in chat history
2. Expect result r.mkdir.__promisify__ is not a function
<img width="570" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/22976326/70e0d513-384e-45dc-b724-7101b7cdf867">

**Comment by JayrGilUtez** [comment]
same opinion

**Comment by pault-dna-energy** [comment]
Testing on code-insiders v:
`1.80.0-insider 8c85702bca51b08005ada7fc4eaf52a61623b2b6 x64 linux`

copilot chat v0.3.2023062106

It's actually working in most (4/5) project directories I've tried and is giving this error in just one.
It's working ok in a blank project directory and newly started chat.

It started working ok again after disabling and re-enabling copilot chat plugin.

**Comment by mammuthus** [comment]
The same issue.

Copilot nightly: v1.92.179
Latest insiders:
Version: 1.80.0-insider (Universal)
Commit: 636dbcff557af8aa088ae118b1a094dce6632ce7
Date: 2023-06-21T08:23:42.803Z
Electron: 22.3.13
ElectronBuildId: 21803499
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

**Comment by lramos15** [comment]
Can you try the latest version `v0.3.2023062201`. I believe this should be fixed
