### ISSUE TITLE
Bad code insert after accepted suggested answer

### ISSUE THREAD

**Issue by godzail** [microsoft/vscode-copilot-release#2744]
Type: <b>Bug</b>

After Accepted suggested answer, the inserted code is repeated in a strange way many times and result is unamageable.
I have to come back and copy the suggested answer and close copilot interface.

Extension version: 0.23.2024112001
VS Code version: Code - Insiders 1.96.0-insider (8d1d1373cd9b8408222b51958e9688827a9e27ce, 2024-11-20T09:23:45.992Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.71GB (46.21GB free)|
|Process Argv|--folder-uri file:///d%3A/Workspace/xlsservice --crash-reporter-id e16ab8f5-ef1e-40f9-b867-875d7d375252|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
vscaat:30438846
c4g48928:30535728
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
da93g388:31013173
dvdeprecation:31040973
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
notreesitter:31116712
e80f6927:31120813
12bdf347:31141542
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
3d9ag387:31183121
c3hdf307:31184662

```

</details>

**Comment by TylerLeonhardt** [comment]
What Copilot entrypoint are you using?

* Chat
* Editor Inline Chat
* Copilot Edits
* Quick Chat

A screenshot would help a ton.

**Comment by godzail** [comment]
Editor Inline Chat, I asked fix with copilot to add a simple docstring in python.
The answer was correct but when I accept, Copilot add a lot of mixed code (docstring and my original code many times).

**Comment by godzail** [comment]
Cancel and repeat the operation gave me the same result.

**Comment by jrieken** [comment]
Please share the code and prompt that was involved here
