### ISSUE TITLE
Copilot edits doesn't stop adding the same piece of code

### ISSUE THREAD

**Issue by charl3y15** [microsoft/vscode-copilot-release#2745]
Type: <b>Bug</b>

So for example, the script is 300 lines, it will keep going and repasting the script until I close it. So it can be 12,000 lines

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1355U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.66GB (2.47GB free)|
|Process Argv|--crash-reporter-id e4f4d1df-fe3e-437d-a395-2ae17b554439|
|Screen Reader|no|
|VM|16%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by charl3y15** [comment]
I have to close VS Code since the stop button doesn't work in order for it to stop

**Comment by aeschli** [comment]
Sorry it is not clear to mefrom the description what you are doing or trying to achive.

Can you give a step by step description? Which view are ou using (panel chat?), what are your prompts.
Also screenshots can help.

**Comment by charl3y15** [comment]
1) Make request to extension for code modification
2) Extension makes changes
3) Extension hangs, sometimes taking 5-10 minutes
4) Check files included in the chatgpt query (let's say I have 1 main script and a few classes)
5) See it's not actually making changes to the code but repeating the lines over and over, as in it will keep writing the functions repeatedly instead of changing the existing  code

Let me know if that is still confusing

I can try and see if I can get a gif of it

**Comment by charl3y15** [comment]
The script it's modifying is only 853 lines but as you can see, it's just rewriting the code over and over 
![Image](https://github.com/user-attachments/assets/deb881b8-3207-4216-b1ae-b406647fb7a8)

**Comment by charl3y15** [comment]
The script it's modifying is only 853 lines, but occasionally when it changes a file, it duplicates it repeatedly. It was at about 2,000 lines before I had to close VS Code

![Image](https://github.com/user-attachments/assets/3eb37952-3faf-40be-bd74-6e836f27701f)

**Comment by aeschli** [comment]
Are you using Copilot Edits, or is it with inline chat?
Can you give an example of the prompt you are using?

**Comment by charl3y15** [comment]
Yes copilot edits. I was asking it to fix the api call because it was using the wrong value for a variable. Honestly it seems to be only affecting VS Code Insiders, haven't had the issue yet on the normal version
