### ISSUE TITLE
Sorry, your request failed

### ISSUE THREAD

**Issue by ShambreTaylor** [microsoft/vscode-copilot-release#2765]
- Copilot Chat Extension Version:
v0.22.4

- VS Code Version: 
1.95.3
f1a4fb101478ce6ec82fe9627c43efbf9e98c813
x64

- OS Version:
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Error message:
Sorry, your request failed. Please report the following request id 88c122e1-ff47-4a3f-8a89-ca385d46acc8 and try again

**Comment by bhavyaus** [comment]
Can you include your output channel for the failure via CTRL + SHIFT +U -> GItHub Copilot Chat
