### ISSUE TITLE
Sorry, your request failed. Please try again. For virtually every question.

### ISSUE THREAD

**Issue by goldngreen** [microsoft/vscode-copilot-release#2767]
- Copilot Chat Extension Version: <where do I find that?>
- VS Code Version: 1.95.3
- OS Version: Windows 11 Pro 22631.4317
- Logs: -

Steps to Reproduce:

1. Ask the question "Are you capable of answering any questions at this time?"
2. Response: Sorry, your request failed. Please try again. Request id: 0942cd45-fd72-4cf7-9be4-c4561ff19808

![Image](https://github.com/user-attachments/assets/36b072b1-4b6b-4d5b-8109-6bf2f4a4b6fc)

2024/11/21 16:31 GMT

**Comment by lramos15** [comment]
Will track and follow up in your other issue #2766
