### ISSUE TITLE
GitHub authorization not working

### ISSUE THREAD

**Issue by LarsLiden** [microsoft/vscode-copilot-release#278]
Haven't been able to get authorization to work.  I click on the "sign in" (image below) and it takes me to a blank page on github and nothing happens.  If I refresh the browser it pops me back to VSCode Insiders, but I'm still not logged in.   I've also tried logging out of github on the web first.

![image](https://github.com/microsoft/vscode-copilot-release/assets/6528486/c4ec4624-2c51-4947-bc7c-e4f0020ce2ee)

![image](https://github.com/microsoft/vscode-copilot-release/assets/6528486/65be3f89-e432-4e51-93b8-cfeaa40014a2)

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/186226 fixed tomorrow.
