### ISSUE TITLE
Github copilot

### ISSUE THREAD

**Issue by Take-A-Byte** [microsoft/vscode-copilot-release#2784]
Type: <b>Bug</b>

Even though i said yes to save the changes it made, it kept on asking me same thing again and again until I checked never ask again, though I had just made one change

VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by bhavyaus** [comment]
Can you please describe what type of request you're making so we can reproduce the issue? Example files / queries will help a lot. You can also try clearing your chat history.

**Comment by Take-A-Byte** [comment]
Sorry, its been a long time and I forgot what the issue was. But, I did not face the issue recently, so might have been solved..
