### ISSUE TITLE
Responbsible AI Service is filtering litrelly everything 

### ISSUE THREAD

**Issue by shamounmurtza** [microsoft/vscode-copilot-release#2785]
Type: <b>Bug</b>

The last thing I asked was for a print statement to be updated to do log instead - somewhow now nothing is working

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:
Remote OS version: Linux x64 6.5.0-27-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|96.00GB (32.12GB free)|
|Process Argv|--crash-reporter-id cab089c9-9055-4dc1-8e1e-a5d5d89d6b32|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: murtza.com|
|OS|Linux x64 6.5.0-27-generic|
|CPUs|AMD EPYC 7713P 64-Core Processor (128 x 3098)|
|Memory (System)|503.50GB (339.89GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by shamounmurtza** [comment]
It just worked once right now, and the moment I did the inline chat to change a print statement to a log it failed. ![Image](https://github.com/user-attachments/assets/bd671d95-15b2-4285-8179-187df817e7f4)

**Comment by shamounmurtza** [comment]
B/w do I get any refund for copilot not working?![Image](https://github.com/user-attachments/assets/07c7fc9a-8cfb-4e6e-a662-2da15974200a)

**Comment by shamounmurtza** [comment]
It worked again for like two prompts and then failed again for the same prompt it just worked for ![Image](https://github.com/user-attachments/assets/18b7b36b-e35c-4976-b46e-ecba8e1cca8a)

**Comment by ulugbekna** [comment]
Is it possible that `groq-test.py` contains something that could be detected by Responsible AI?
