### ISSUE TITLE
Cannot explain assert and static_assert (C++)

### ISSUE THREAD

**Issue by ResCXsention** [microsoft/vscode-copilot-release#279]
- VS Code Version: 1.80.0 (insiders)
- OS Version: Debian 11

With regards to C++'s assert and static_assert macros respectively, Copilot sometimes seems especially confused:

![image](https://github.com/microsoft/vscode-copilot-release/assets/107906006/a74ca434-593f-42e3-833e-8159d181d614)
![image](https://github.com/microsoft/vscode-copilot-release/assets/107906006/6e229a09-3b14-4bb7-b289-8a0cfe08352a)

However, it will then go on to properly explain their distinctions. 

Reproduction: Ask copilot the difference between assert and static_assert. If it does not reply with a noncommittal "they have different use cases", there is a very good chance that Copilot will be confused.

**Comment by ResCXsention** [comment]
No, that's it. Copilot is contradicting itself in your above prompt:

> assert and static_assert are used to check conditions at compile-time and run-time, respectively.

I'm pretty sure that it's the other way around. The contradiction, however:

> assert is a macro . . . used to check a condition at runtime and terminate the program if the condition is false.

and,

> static_assert . . . used to check a condition at compile-time and generate a compile-time error, if the condition is false.

**Comment by lramos15** [comment]
The post @ulugbekna  made shows that the model can answer this properly, and sometimes with LLMs you get variable and strange answers. His response pretty much regurgitates this stackoverflow post.

https://stackoverflow.com/questions/18210270/what-is-the-difference-between-assert-and-static-assert

Closing as complete
