### ISSUE TITLE
Allow chat extensions to register custom variables

### ISSUE THREAD

**Issue by schicks** [microsoft/vscode-copilot-release#2790]
I've started playing around with writing chat extensions. There are lots of things I think this could be useful for, but what I keep coming back to is that most of the things I want to do feel better implemented as new chat variables than as new chat participants.
- `#url:www.some-doc-site.com` to include context from a website
- `#gdoc:document-id` to include the contents of a google doc
- `#fileWhen:githash` to include the contents of a file in the repo from a past point in history

My sense is that the design requires participants to know how to handle particular sorts of variables, so it seems like these would usually be paired with a participant. But the registering of a variable also seems useful so that extension authors can provide suggestions for the variable autocomplete, and so that chat extensions don't have to willfully misinterpret things like `#file` to do what they want.

**Comment by isidorn** [comment]
Variable API is proposed. Checkout our language model tools docs as a stable replecement that should help you https://code.visualstudio.com/api/extension-guides/tools
