### ISSUE TITLE
VSCode Copilot Chat extension cannot be installed

### ISSUE THREAD

**Issue by jason-chang** [microsoft/vscode-copilot-release#28]
- VS Code Version:1.78.2
- OS Version:MasOS 13.3.1 (a) (22E772610a)
- Logs:none

Steps to Reproduce:

When I try to install the `Copilot Chat` extension I always get the following popup.

![image](https://github.com/community/community/assets/4367687/2853a2d9-d9ae-4278-8911-0b3265bcd576)

It means: The 'github.copilot-chat' extension cannot be installed because there is no published version.

But when I checked the extension's changelog, I found that there is a published version !!!

![image](https://github.com/community/community/assets/4367687/9599f4d4-b533-4405-a89d-e53a4bd5aeaf)

What happened? .

**Comment by DennizSvens** [comment]
You need to run VSCode insiders edition!

**Comment by digitarald** [comment]
Should be fixed by using Insiders.
