### ISSUE TITLE
GitHub Copilot Edits make garbled characters.

### ISSUE THREAD

**Issue by runceel** [microsoft/vscode-copilot-release#2800]
Type: <b>Bug</b>

I used Copilot Edits with Japanese markdown files.
In this case, Copilot Edits make many garbled characters.

For example:
### original
```
厳密には "Microsoft.Extensions.VectorData.Abstractions" に抽象化レイヤーのインターフェースが定義されています。
```

### copilot edits
```
厳密��は "Microsoft.Extensions.VectorData.Abstractions" に抽象化レイヤーのインターフェースが定義されています。
```

Extension version: 0.23.2024102903
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (7.27GB free)|
|Process Argv|--crash-reporter-id 7e9e7c53-c021-4ffc-9361-b0b8bc8e3bf9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
da93g388:31013173
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joyceerhl** [comment]
@runceel I have not been able to reproduce this behavior. Can you please share the prompt and file where this occurs? I tried placing the original text you provided in a console.log and asking Copilot Edits to rewrite it to Python, and it did so without garbling Unicode characters.
