### ISSUE TITLE
Inline Diff toggle check not changing

### ISSUE THREAD

**Issue by gamousquesORT** [microsoft/vscode-copilot-release#282]
- VS Code Version:
Version: 1.80.0-insider
Commit: 4649b5333370139d161e7b5d4f78ca13741efa35
Date: 2023-06-28T08:04:23.178Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 20.6.0

When you open the inline window shows the "Inline diff" is checked but now diff is showing.

<img width="739" alt="img1" src="https://github.com/microsoft/vscode-copilot-release/assets/27827078/48328e22-5c84-4480-9c01-a6535de6dae5">

If  I click the inline diff option, the diff appears.
<img width="793" alt="img2" src="https://github.com/microsoft/vscode-copilot-release/assets/27827078/6fa91fb7-1d34-4676-8580-20ea0aca4dc0">

If you keep clicking the diff button and the code toggles but not the button

**Comment by jrieken** [comment]
This has been removed. Toggling diff is now a primary action that sits with Accept and Discard
