### ISSUE TITLE
When asking anything to Copilot Chat opens 4 blank documents with "changes"

### ISSUE THREAD

**Issue by juanecl** [microsoft/vscode-copilot-release#2833]
- Copilot Chat Extension Version:
- VS Code Version: 1.95.3 (Universal)
- OS Version: macOS Sequoia 15.1.1 (24B91)
- Logs:

Steps to Reproduce:

1. Ask anything to Copilot
2. Opens four blank documents with "changes"

**Comment by lramos15** [comment]
Can you include some sort of screen recording so I can follow exactly what is happening. I have not had this happen before.

Can you reproduce with a new fresh chat via `+` in the top right?

**Comment by juanecl** [comment]
I did what you suggested to open a new fresh chat, and the bug disappear. If it happens again I'll gather further information and record the screen. Meanwhile I see no point on keep this issue open.
