### ISSUE TITLE
Copilot not working Claude

### ISSUE THREAD

**Issue by denial2238** [microsoft/vscode-copilot-release#2836]
Type: <b>Bug</b>

Sorry, your request failed. Please try again. Request id: 6c40817a-32fa-4302-9d9f-4f051ce91852

Extension version: 0.22.4
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id a8f8c8a7-6117-487d-9936-79e7e3805f94|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
vscrpc:30673769
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joyceerhl** [comment]
Does this still repro for you?

**Comment by ZeroCool22** [comment]
> Does this still repro for you?

Working fine now.

**Comment by joyceerhl** [comment]
Thanks for confirming!

**Comment by asuccurro** [comment]
I have the same issue since Friday (4 days now). Only happens with Claude 3.5

**Comment by romuloms** [comment]
I'm also still having this issue

**Comment by denial2238** [comment]
For me, just working fine. Issue can be closed
