### ISSUE TITLE
Provide an option switch whether to display copliot chat in the icon bar

### ISSUE THREAD

**Issue by PaulXu-cn** [microsoft/vscode-copilot-release#2844]
Could you please provide a switch to keep the chat entry in the icon bar? Because after I updated, I can only enter from command p, and my screen is divided into three parts, file list, code, and copilot chat, which crowds out my screen. code space.

Previously, file list and copilot chat shared the same space, allowing more code to be displayed on the screen.

So, can I move it back to the icon bar, or add this switch in the next update.

**Comment by CODY-RAY** [comment]
@PaulXu-cn you can drag it back.

The new update is a bad ui design choice imo

**Comment by PaulXu-cn** [comment]
> [@PaulXu-cn](https://github.com/PaulXu-cn) you can drag it back.
> 
> The new update is a bad ui design choice imo

Yes, this update has a big impact on me.

So, what do you mean by drag it back? I tried it and it didn't work.
