### ISSUE TITLE
Any prompt returns Sorry, the response matched public code so it was blocked. Please rephrase your prompt. Learn more.

### ISSUE THREAD

**Issue by seikit** [microsoft/vscode-copilot-release#2847]
Type: <b>Bug</b>

Any prompt returns Sorry, the response matched public code so it was blocked. Please rephrase your prompt. Learn more.

Extension version: 0.22.4
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.0-1072-aws

**Comment by edersac** [comment]
close this, testing.
