### ISSUE TITLE
FIle Interaction

### ISSUE THREAD

**Issue by Fightingpainter** [microsoft/vscode-copilot-release#286]
It would Be Really Nice if the chat Feature has way more interactebility with files,

so for the Reading part it's already somewhat Implemented but not really stable at all, because every time I asked for something in a file it had some issues, and a lot of misinformation,

it would also be Really Nice if you could tell the chat to directly modify the existing code, this would not only be more time efficient for the user but also add a lot to the feeling of working with someone.

idk this is just something I would like to see, but probably not necessary for many people.

**Comment by jrieken** [comment]
> it would also be Really Nice if you could tell the chat to directly modify the existing code, this would not only be more time efficient for the user but also add a lot to the feeling of working with someone.

@Fightingpainter Did you try the inline chat feature? Go on a line, select `ctrl+I` (or `cmd+i`) and ask question in the context of the current editor
