### ISSUE TITLE
[Feature] Cancel task `/fix` during `Fix using copilot` 

### ISSUE THREAD

**Issue by zmzlois** [microsoft/vscode-copilot-release#288]
At the moment the console lives in between code, and there is no cancellation instruction until the result is generated. But sometimes it can take very long to generate a result. Wish there is a cancellation button to cancel it before it finishes.

**Comment by alexdima** [comment]
Cancelation is possible by clicking the Stop button (the red rectangle on the right):

<img width="691" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5047891/b9d18113-fec0-4bb3-9be2-3c9111d267a6">
