### ISSUE TITLE
Why chat is so slow?

### ISSUE THREAD

**Issue by Tarpanxt** [microsoft/vscode-copilot-release#2887]
Chat is designed to slowly type response characters, which I found really annoying. I can read way faster than it types. I often type a question and go do something else (make coffee, etc), return back and check the answer.

Can it be configured to instantly spit out the answer? Or at least speed it up 5x?

Thank you

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If yes, can you provide reproducible steps. Until then I will go ahead and close this issue.
Thank you for your understanding

**Comment by Tarpanxt** [comment]
Not sure what you mean by "steps to reproduce"? Just type anything in GitHub copilot chat and watch the answer appear character-by-character.

VSCode Version: 1.95.3
Copilot chat, Last updated - 2024-11-22, 10:19:22

**Comment by isidorn** [comment]
Works great for me

https://github.com/user-attachments/assets/fd7bc7d1-2bd3-43da-af74-9d484797cec5
