### ISSUE TITLE
Answers will clean up when restart vscode

### ISSUE THREAD

**Issue by Misaka-Tang** [microsoft/vscode-copilot-release#289]
- VS Code Version: 1.79.2
- OS Version: MacOS 13.4.1
- Issues:
When I restart or quit from vscode, my conversations with copilot chat will clean up like reset.

**Comment by roblourens** [comment]
Please describe what you're asking for in more details, I don't understand

**Comment by Misaka-Tang** [comment]
I use the extension as usual, but when I restart the vscode every record is disappeared.

**Comment by roblourens** [comment]
I need more detail, maybe screenshots would help
