### ISSUE TITLE
Language model unavailable

### ISSUE THREAD

**Issue by ALaHurreau** [microsoft/vscode-copilot-release#2896]
Type: <b>Bug</b>

The only response from GitHub Copilot chat is "Language model unavailable", with absolutely no other feedback or information which might help debug the issue.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 3072)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.45GB (8.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 0)|
|Memory (System)|15.35GB (8.59GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 0)|
|Memory (System)|15.35GB (8.59GB free)|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Likely a firewall please follow the steps in this issue and add a comment with information https://github.com/microsoft/vscode-copilot-release/issues/2116#issue-2624506695
