### ISSUE TITLE
Missing Font Size Option for Non-Code Text in Copilot Sidebar Chat

### ISSUE THREAD

**Issue by hakonhk** [microsoft/vscode-copilot-release#2920]
Type: <b>Feature Request</b>

The non-code text generated by AI within the GitHub Copilot sidebar chat can be too small to read. Currently, there appears to be no way to adjust the font size of this text without resizing the entire UI. This makes it challenging to use the feature effectively for users who need larger text for readability. 
There should be an option to adjust the font size of non-code text in the sidebar chat independently.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Cweili** [comment]
This is also what I need.
