### ISSUE TITLE
Copilot workspace editor shouldn't delete message when navigating prompt history

### ISSUE THREAD

**Issue by phlyk** [microsoft/vscode-copilot-release#2929]
Hi there,

This is extremely similar to [#661](https://github.com/microsoft/vscode-copilot-release/issues/661) however it seems to have returned as a regression for the relatively new workspace editor.

Steps to reproduce issue (I realise this should be a bug):
1. Start a chat in the Workspace editor (the one on the right) ![Image](https://github.com/user-attachments/assets/ee78f891-0d92-4936-9318-7c4b1c5a95df)

2. Continue your chat with a long elaborate message
3. Press up to check if you include some detail at the beginning
4. Boom. You pressed up one too many times and now you're lost your elaborate message

**Comment by bhavyaus** [comment]
Which version of VSCode are you using? Could you try to reproduce this on a newer release?
