### ISSUE TITLE
Chat can't read my code when I have a python file in a javascript project

### ISSUE THREAD

**Issue by itsmasabdi** [microsoft/vscode-copilot-release#294]
Steps to Reproduce:

1. have a nuxt project
2. create a python file in the folder
3. ask a question about python file

This is the response:
`GitHub Copilot: The code you provided is written in Python, but you mentioned that you are working with a JavaScript project. Can you please provide the relevant code snippet in JavaScript so I can assist you better?`

**Comment by lramos15** [comment]
This should be fixed
