### ISSUE TITLE
How many times will the chat ask if I want to enable Claude 3.5??

### ISSUE THREAD

**Issue by mvrius** [microsoft/vscode-copilot-release#2941]
Type: <b>Bug</b>

Use Claude 3.5 from chat.

For every input it will ask if I agree to enable access.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 265K (20 x 3878)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|95.41GB (57.88GB free)|
|Process Argv|--crash-reporter-id 1401b335-f23c-4de7-884d-febf4f964864|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.167.4-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) Ultra 7 265K (20 x 0)|
|Memory (System)|46.76GB (34.48GB free)|
|VM|0%|
</details>

**Comment by lramos15** [comment]
Can you try it without WSL and can you also tell me what it says in https://github.com/settings/copilot
