### ISSUE TITLE
"GitHub Copilot Nightly must be installed alongside Copilot Chat" but Github Copilot Nightly is deprecated

### ISSUE THREAD

**Issue by Leigh-M** [microsoft/vscode-copilot-release#296]
When trying to set up VSCode Github Copilot Chat, instructions are to install VSCode extension Github Copilot Nightly, however it says it has been deprecated and to use Github Copilot but with Pre-Release selected? 

Very confusing/ poor UX. Unclear from the outset how to set this up correctly.

Can we use Github Copilot Pre-Release in which case please update your docs accordingly! Or do we ignore the deprecated warning?  (ideally not please)

Updated:  I got this running successfully by ignoring the docs, and do not install Github Copilot Nightly extension, instead do:

1. Update Github Copilot exentenion to pre-release version
2. Install Github Copilot Chat and select pre-release version

Done, works as expected - you should see a Chat box on the extensions panel on the left in your IDE

**Comment by roblourens** [comment]
Sorry, we got the new pre-release extension out before updating the docs. Everything should be in sync now. Let me know if you see anywhere still directing you to the deprecated extension

**Comment by cadmus-software** [comment]
I just got the "Welcome to the Copilot chat private beta!" 6 hours ago but the instructions still indicated the Nightly extension.

**Comment by cadmus-software** [comment]
It was an email, see screenshot
![image](https://github.com/microsoft/vscode-copilot-release/assets/41549161/80a3e113-fd3a-420d-83c4-c266916a6059)
