### ISSUE TITLE
No edits are generated. 

### ISSUE THREAD

**Issue by incognick** [microsoft/vscode-copilot-release#2962]
Type: <b>Bug</b>

Sometimes, after I've been using Copilot in edit mode for a bit, The model will state that it generated changes and what files it updated however no files will be changed.  This seems to only happen when the working set gets up to 10 files.  

Extension version: 0.22.4
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|--crash-reporter-id fc8345f9-a34a-45e8-b68d-5e5bb41d752d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by vladislav-klass** [comment]
same for me. Noticed that this occurs with very long files (e.g. 9k lines of code).

**Comment by joyceerhl** [comment]
> This seems to only happen when the working set gets up to 10 files

That's correct, we limit the working set to 10 files on the client side. 

@vladislav-klass does this occur for you even with <10 files in the working set?
