### ISSUE TITLE
A default keyboard shortcut to "Generate This"

### ISSUE THREAD

**Issue by elongl** [microsoft/vscode-copilot-release#298]
As far as I can tell, the _"Generate this"_ and _"Fix this"_ are the only Copilot functionalities that propose in-line changes to code rather than output it in the chat and have me copy and paste it. This is very useful compared to a chat-only experience and I think there should be a keyboard shortcut by default to support it.

Here's how I currently do it (I would also prefer that it'd open with an empty line rather than the `/generate`).

https://github.com/microsoft/vscode-copilot-release/assets/30181361/5db3c864-96bf-4b9e-a173-a41d8ebf807f

**Comment by ulugbekna** [comment]
You can simply select the code and trigger command "Inline Chat: Start Code Chat" to open the inline chat and ask it to modify your code or add some.
