### ISSUE TITLE
got error trying to get a new razor file

### ISSUE THREAD

**Issue by webreidi** [microsoft/vscode-copilot-release#2982]
Type: <b>Bug</b>

Asked it to create a razor page with a form and received "this._embeddings.filter is not a function"

![Image](https://github.com/user-attachments/assets/fbbbc95a-64be-4a38-89ac-e657f1df2cc8)

Extension version: 0.23.2024120202
VS Code version: Code - Insiders 1.96.0-insider (2ed1e9b48c8f55e1b92322a992c6c12b1e86e444, 2024-12-02T05:06:23.390Z)
OS version: Windows_NT x64 10.0.22635
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 165H (22 x 3072)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.64GB (0.52GB free)|
|Process Argv|--crash-reporter-id df9569b1-4056-47ee-b1a6-521ad1c587e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551cf:31179977
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
cf1a2727:31183122
c3hdf307:31184662

```

</details>

**Comment by bhavyaus** [comment]
This issue should be fixed in newer releases. Please give that another try.
