### ISSUE TITLE
Sorry, your request failed. Please try again. Request id: 3203f4f9-9bf9-475a-bce5-00df1c8152b3

### ISSUE THREAD

**Issue by alphaket14** [microsoft/vscode-copilot-release#2987]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Try to chat to Github Copilot
2. I can't share the repository due to security reasons

**Comment by FlyingCarlos** [comment]
same problem, i got warning in output: ```[warning] Error computing embeddings. Retrying in 1 seconds. Error: Error: Failed to compute embeddings```

**Comment by alphaket14** [comment]
Ok, I was able to resolve it with changing my credentials, logging back in
