### ISSUE TITLE
When zoomed in, the Copilot Edits UI is redered outside of the viewport

### ISSUE THREAD

**Issue by jessehouwing** [microsoft/vscode-copilot-release#3003]
- Version: 1.246.0
- Build: prod
- Editor: vscode/1.95.3
- Operating system: Windows_NT
- Operating system version: 10.0.26100
- Operating system architecture: x64

Steps to Reproduce:

1. Open copilot edits
2. ctrl-+ a couple of times

The copilot icon and hints are no longer available:
![Image](https://github.com/user-attachments/assets/d246850f-1b28-4bb7-8fa7-0afc54ccfb2d)
![Image](https://github.com/user-attachments/assets/465df18c-0834-4347-9bbe-18b5348c2efb)

**Comment by roblourens** [comment]
The "internal user" message takes up a lot of space and I think this usually doesn't happen without that
