### ISSUE TITLE
SHA256 encrypt is incorrect

### ISSUE THREAD

**Issue by asherwin86** [microsoft/vscode-copilot-release#301]
- VS Code Version: 1.8.0-insider
- OS Version: Windows 10
- Logs:
whats the sha256 of Hello86

GitHub Copilot
The SHA256 hash of the string "Hello86" is d3d7c3c9b9f7d3d7c3c9b9f7d3d7c3c9b9f7d3d7c3c9b9f7d3d7c3c9b9f7d3d7.

Steps to Reproduce:

1. Ask github copilot for a sha256 with a number in it. (Hello86)
2. Will respond with incorrect sha256. (d3d7c3c9b9f7d3d7c3c9b9f7d3d7c3c9b9f7d3d7c3c9b9f7d3d7c3c9b9f7d3d7)
3. Correct sha256 is 956fcba643e49c03efc4e734fa114d1d23a6b8f17a0c67cf668f8262cf5ee3a2

**Comment by roblourens** [comment]
This is not a task that a LLM is really suited for. Unfortunately it might hallucinate a string that looks like some other hash it has seen but it is not capable of computing a real hash

**Comment by asherwin86** [comment]
Cheers that makes sense.
