### ISSUE TITLE
Copilot with Visual Studio breaks down too often in a day

### ISSUE THREAD

**Issue by sivapge** [microsoft/vscode-copilot-release#3010]
- Copilot Chat Extension Version:
- VS Code Version:1.95.3 (Universal)
- OS Version:14.7.1 (23H222)
- Logs:

Half the time, the copilot is not available. It has become a miracle if it works continously for 24 hours. 

Steps to Reproduce:

1. Start VS Studio  
2. Type in a query. The chat is inactive. It doesn't show the AI versions either

**Comment by sivapge** [comment]
The error it says is 'Language model unavailable' - This happens too any times in a day

**Comment by sivapge** [comment]
[error] Error: net::ERR_HTTP2_PROTOCOL_ERROR
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/utility_init:2:10511)
    at SimpleURLLoaderWrapper.emit (node:events:519:28): Error on conversation request

**Comment by sivapge** [comment]
Sorry, your request failed. Please try again. Request id: d6dd1c0e-a1f6-4c36-af87-7a9874ddd842

**Comment by chrmarti** [comment]
Please check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here.
