### ISSUE TITLE
Not able to use github copilot chat

### ISSUE THREAD

**Issue by ZikraFurqan** [microsoft/vscode-copilot-release#3016]
Type: <b>Bug</b>

open copilot chat and give any prompt

Extension version: 0.23.2024102903
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.72GB (14.93GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+OSD/home/zif2kor/MPCI/repo1 --remote=wsl+OSD --crash-reporter-id e68c7f51-464d-4bea-9a7a-3068caa05465|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: OSD|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 0)|
|Memory (System)|24.46GB (22.00GB free)|
|VM|0%|
</details>

**Comment by isidorn** [comment]
This issue does not satisfy the minimal quality standards for an issue that we would like to see in this repository.
Reproducible steps using English with latest VS Code are what helps us a lot. So please feel free to open a new issue with steps. 
Thus I will go ahead and close this one. 
Thank you
