### ISSUE TITLE
History is been deleted in the sidebar after opening session in editor

### ISSUE THREAD

**Issue by youurt** [microsoft/vscode-copilot-release#302]
- VS Code Version: 1.79.2
- OS Version: macOS 13.1
- Logs: -

Steps to Reproduce:

1. Open Session in Editor
2. Close View in Editor

Now the session/history is been deleted in the sidebar.

**Comment by roblourens** [comment]
I don't follow, can you give some more detail about what exactly you see here

> Now the session/history is been deleted in the sidebar.

**Comment by youurt** [comment]
I would expect that after opening the session in the editor, the history wouldn't be deleted:
https://github.com/microsoft/vscode-copilot-release/assets/39196535/287d30a6-45a1-495a-9802-f6f8d7269328

**Comment by roblourens** [comment]
You opened it in the editor, then closed the editor. You can get it back from the _history_ list by clicking the "show history" button in the view title toolbar
