### ISSUE TITLE
정상적인 질문에서 자꾸 필터링됨

### ISSUE THREAD

**Issue by 06atria** [microsoft/vscode-copilot-release#3022]
Type: <b>Bug</b>

v-model 데이터들의 변경시 현재 코드와 리팩토링 된 코드와의 성능차이는 얼마나 날까?

라는 질문이 왜 필터링 되는가?

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.17763
Modes:

**Comment by isidorn** [comment]
This issue does not satisfy the minimal quality standards for an issue that we would like to see in this repository.
Reproducible steps using English with latest VS Code are what helps us a lot. So please feel free to open a new issue with steps. 
Thus I will go ahead and close this one. 
Thank you
