### ISSUE TITLE
it cant merge code.. ica can focus on one file.  if ii have other files in my workspace it gete confused. i told it not to look at anytyhihgn else if i had confidense i would have those copies. im trued cursro and try thius anbd waste all my time  let is promising enough to keep TESTING..   im dying form this AI AND QUANTUM GRAVITY work

### ISSUE THREAD

**Issue by damian-666** [microsoft/vscode-copilot-release#3025]
Type: <b>Bug</b>

its just not ready toi release at all. iki cannot merge fiels it takes way tooo long to do anything.  

cannot follow insturctsion.    very very sad.  it amlmost works  i should ber paid to do this..    

Extension version: 0.22.4
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Windows_NT x64 10.0.26120
Modes:

**Comment by isidorn** [comment]
This issue does not satisfy the minimal quality standards for an issue that we would like to see in this repository.
Reproducible steps using English with latest VS Code are what helps us a lot. So please feel free to open a new issue with steps. 
Thus I will go ahead and close this one. 
Thank you
