### ISSUE TITLE
Copilot response cuts off prematurely

### ISSUE THREAD

**Issue by DanSoQt** [microsoft/vscode-copilot-release#303]
Copilot seems to be unable to spit out more than a few lines when asked to "adapt" some code. Other prompts like "help me update my code" produce the same cut-off responses.

- VS Code Version: 1.80.0-insider
- OS Version: Win 11 10.0.22621
- Copilot version: 1.95.237
- Logs: Nothing of note printed to the GitHub Copilot Chat output log. 
[INFO] [streamMessages] [2023-07-05T12:10:29.400Z] message 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2023-07-05T12:10:29.400Z] request done: headerRequestId: [b8f91e49-1ac7-4106-84f3-090b274a1c4e] model deployment ID: [x1a6c73c2f862]

Steps to Reproduce:
1. Ask Copilot Chat to "adapt" a given open file. The request doesn't matter, but the issue was found asking it to adapt a ~110 line python file to switch to using urllib instead of 'requests'.
2. Copilot obliges and get through about 15 lines or so (variable) before simply stopping or even dropping out before completing formatting.

Example request:
"Please adapt my code in [filename] to use urllib requests and error handling instead of the 'requests' library."

Response:
```
Certainly! Here's an updated version of the code that uses urllib requests and error handling:

\```python import sys import json import logging import re import base64 import argparse from os import environ as envs from urllib.parse import unquote, quote from urllib.request import Request, urlopen from urllib.error import HTTPError, URLError
```

**Comment by JacobCallahan** [comment]
I'm seeing the same behavior as well. It seems like it will get stuck after it finishes import statements, no matter how short that import list is.
When this happens, additional prompting will result in an apology and no correction of the output.

Is this more an issue with rate limiting?

**Comment by Citizen-Dan** [comment]
I am seeing the same issue too. When asked a question without the need for code in the response, the answers do seem complete. However when any code is required, it stops on the first line.

**Comment by DanSoQt** [comment]
I don’t think it’s a rate-limiting issue, or at least I’m not familiar with those limits. The logs for the request only show three streamMessages events pertaining to the question, and it occurred the first time I asked chat a question.

**Comment by Neural-Net-Ninja** [comment]
instead of whole code, it just imports a library needed and that's it.

**Comment by roblourens** [comment]
Is this file open and do you have a selection in it? I think there is an issue with missing editor context here. And if the file is not open, chat can't see it.

**Comment by DanSoQt** [comment]
Yes, the file is open and the active tab in the editor. I'll do some further testing tomorrow to see if other prompts are able to grab the appropriate context or not.

As far as selection goes, no selection, but the file is just over 100 lines, and the filename is provided in the prompt.
________________________________

**Comment by Neural-Net-Ninja** [comment]
> Can someone try installing a previous version of the Copilot Chat extension to see whether it regressed in the past couple days

it's working fine with the old version!

**Comment by roblourens** [comment]
Which version?

**Comment by Neural-Net-Ninja** [comment]
> Which version?

so it caused this problem on `0.2.2`
and went I went to `0.2.1` it worked fine.

**Comment by roblourens** [comment]
@ulugbekna I think this is https://github.com/microsoft/vscode-copilot/commit/ca37a063d374113c0247e54a158520495a876cb0

**Comment by BoringApp** [comment]
I met same problem.
<img width="443" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/10597453/4d7bc8ef-ff75-4ff5-879f-53d2c2237df7">

**Comment by ChiragBusiness** [comment]
Think i was only getting the error when it was trying to output a code block, switched to a version from a week ago and it works fine

**Comment by alexdima** [comment]
Appologies for the breakage. We have shipped a new prerelease version of the extension, `v0.3.2023070602` which should contain a fix.

**Comment by DanSoQt** [comment]
Unfortunately, I'm still experiencing the same issue in v0.3.2023070602. Updated extensions this morning and restarted VS Code Insiders for good measure. The behavior appears identical. When copilot begins to write a code-block, it bombs out and fails to complete the thought. Are there any caches I can/should clear to ensure the I'm not somehow still using a cached library?

``` Here's an example of how you can adapt the code to use built-in libraries instead of the 'requests' library:
\```python import urllib.request import urllib.parse import base64
```

GitHub Copilot Chat version v0.3.2023070602
Last updated 7/6/2023, 11:23:11  (UTC+1)

GitHub Copilot version v1.95.240
Last updated 7/6/2023, 11:18:33

**Comment by alexdima** [comment]
@DanSoQt You're right, sorry again about that 😳 ! Version `v0.3.2023070603` should contain a fix.

**Comment by DanSoQt** [comment]
Confirmed working as expected in v0.3.2023070603. Thanks for the fix!

**Comment by gounthar** [comment]
I have had the same kind of behavior since yesterday.
Entering `/doc` for a simple bash script, and the answer stops abruptly after 22 lines or so.
> Your response got cut off , please continue where you left off
does not help.
