### ISSUE TITLE
"Add Selection To Chat" Adds the entire file, not just the selection.

### ISSUE THREAD

**Issue by AlfredoDinunzioTR** [microsoft/vscode-copilot-release#3035]
This issue started after a recent update in the last 1-2 months. highlight a code block and add selection to chat.  it just adds the file instead of the selection.

1. Highlight code block in a file 
2. Right click and choose Copilot > Add Selection To Chat
3. You will see that it added the whole file instead. 

![Image](https://github.com/user-attachments/assets/ab747a63-565e-4adf-8c1f-494d6efb0ade)

![Image](https://github.com/user-attachments/assets/0e1dbfb7-6e4a-4111-b878-52c35d17740f)

You can see that I have lines 88-117 selected. After I right click and choose copilot > add selection to chat, you can see that it adds the whole file, not just the selected lines.

**Comment by joyceerhl** [comment]
This should already be fixed in [Insiders](https://code.visualstudio.com/insiders) and will come to Stable next Wednesday/Thursday
