### ISSUE TITLE
/createWorkSpace command

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-copilot-release#308]
Hello devs, create work space command is so useless here is why:

- Gives too much error when its created project (you have to do 50+ edits to fix if its possible)
- It does not creates designer files.
- Some files are empty.

For someone that don't knows coding much it's not helpful.

**Comment by joyceerhl** [comment]
Thanks for your feedback, could you please provide an example of projects that you have tried creating with `/createWorkspace`?
