### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Paulo7890** [microsoft/vscode-copilot-release#3089]
Type: <b>Bug</b>

e uma vergonha paga 10 dolores para usa um limitador no qual nao conseguimos  usan 20 minutos de trabalho esse vai ser meu ultimo mes usando essa ferramente  ,  existem outras extensoes que fazer a mesma coisa  , e paga pra pra trabalhar com limite sem posibilidades Sorry, your request was rate-limited. Please wait 1 minutes before trying again.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.48GB free)|
|Process Argv|--crash-reporter-id e319a92c-001f-45c9-8dfe-d04b2919db63|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by isidorn** [comment]
This issue does not satisfy the minimal quality standards for an issue that we would like to see in this repository.
Reproducible steps using English with latest VS Code are what helps us a lot. So please feel free to open a new issue with steps. 
Thus I will go ahead and close this one. 
Thank you
