### ISSUE TITLE
Is there any possibilities to use copilot chat on mobile devices?

### ISSUE THREAD

**Issue by LikeDreamwalker** [microsoft/vscode-copilot-release#309]
Just a thought but copilot chat is very powerful and I think if we only use it in vscode on computers it will be a kind of waste.

It's like when we think about something about programming and we can ask copilot for more information, but we probably don't have a computer with full version vscode. It's sad for me that I have to remember this question and ask to copilot later or just search on internet by myself.

I also have some thoughts and solutions. One way to achieve this is use codespaces, which can work but it will cause time to load the vscode. But based on this, I think maybe we can build a basic pre-install app on mobile devices with vscode or head to vscode to run copilot chat, which It's no need to break the vscode-copiot extension. Like a headless webview app, but still need more.

It's not an urgent feature request but I am really hoping for it.

**Comment by ulugbekna** [comment]
This will be supported when the extension works on vscode.dev
