### ISSUE TITLE
The question rate is being limited.

### ISSUE THREAD

**Issue by jsolisu** [microsoft/vscode-copilot-release#3099]
Type: <b>Bug</b>

Only questions or requests are being made.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:
Remote OS version: Linux x64 5.15.146.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.146.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 0)|
|Memory (System)|15.58GB (7.30GB free)|
|VM|0%|
</details>

![Image](https://github.com/user-attachments/assets/ce9809cc-d0ca-4c11-a8d6-f2d0690fe2af)

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-copilot-release/issues/2627
