### ISSUE TITLE
/test creates tests for whole typescript file, not just selection

### ISSUE THREAD

**Issue by ThomasPe** [microsoft/vscode-copilot-release#311]
- VS Code Version: 1.81.0-insider
- OS Version: Windows 11
- Logs: -

I'm using Copilot Chat to generate tests for my react app using jest. Unfortuantley it always tries to generate tests for the whole file, not just my selection

Steps to Reproduce:

1. create typescript file with multiple methods
2. select single method and ask copilot to write tests for selected method using `/test`
3. copilot will create tests for all methods in current file disregarding the selection
<img width="532" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4225039/96f3a74e-5ec9-4bef-afb6-0bd9c4edc927">

Workaround: when I write `write tests` instead of using the `/test` command it works most of the time as expected.

**Comment by jrieken** [comment]
This should be better now, we try to only feed the current "symbol", e.g function etc into the LLM. I'll will check but @ThomasPe please also give this another try
