### ISSUE TITLE
request failed

### ISSUE THREAD

**Issue by govindharaju1342** [microsoft/vscode-copilot-release#3122]
Type: <b>Bug</b>

Sorry, your request failed. Please report the following request id 1ec16d8b-1665-4266-8270-750a81901685 and try again

Extension version: 0.22.2024100702
VS Code version: Code - Insiders 1.94.0-insider (Universal) (f35c3823e3b7ea4c52f7fee4659bcce39b42ce9e, 2024-09-24T05:04:12.797Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by lramos15** [comment]
You are on a much older version. Please update and it will fix your issue
