### ISSUE TITLE
Accessing the OpenAI Preview model without restrictions.

### ISSUE THREAD

**Issue by nghuman123** [microsoft/vscode-copilot-release#3127]
Type: <b>Feature Request</b>

 I have a separate subscription for OpenAI Preview Pro. How I can access the OpenAI Preview model without restrictions in GitHub Copilot chat?

Thanks

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

**Comment by digitarald** [comment]
@nghuman123 can you help me understand what restrictions you refer to that you would hope won't apply?

Also, I assume you are referring to your ChatGPT subscription, not using OpenAI's APIs, right?

**Comment by nghuman123** [comment]
@digitarald I have ChatGPT pro subscription, which gives unlimited usage of OpenAi preview models. I want to use same subscripting to use unlimited chats in Github copilot. I have separate subscription for Github Copilot as well.

**Comment by digitarald** [comment]
Closing as it is not feasible. ChatGPT Pro doesn't provide an API, so using it elsewhere isn't possible. Even though GH Copilot offers OpenAI models, they are not served through OpenAI's infrastructure.
