### ISSUE TITLE
Response is being filtered by the responsible AI service

### ISSUE THREAD

**Issue by Mukul1985** [microsoft/vscode-copilot-release#3136]
Type: <b>Bug</b>

Response is being filtered by the responsible AI service even though nothing is invalid or wrong with the question.

Extension version: 0.22.4
VS Code version: Code 1.95.2 (e8653663e8840adaf45af01eab5c627a5af81807, 2024-11-07T11:07:22.054Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode-copilot-release/issues/2625
