### ISSUE TITLE
Replies with a filter error to every single message, no matter what.

### ISSUE THREAD

**Issue by thedude7744** [microsoft/vscode-copilot-release#314]
- VS Code Version: 1.81.0-insider
- OS Version: Ubuntu 20.0.4
- Logs: ![image](https://github.com/microsoft/vscode-copilot-release/assets/137542830/0db4467c-ede3-464e-a798-be6919ed8b02)

**Comment by jfrancoisponcet16** [comment]
I've got the same problem...

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
