### ISSUE TITLE
Can't install pre-release version it is not compatible with the current version of Visual Studio Code (version 1.80.0).

### ISSUE THREAD

**Issue by arestrepodev** [microsoft/vscode-copilot-release#315]
- VS Code Version: 1.80.0
- OS Version: MacOS 13.4.1
- Logs: Can't install pre-release version of 'github.copilot-chat' extension because it is not compatible with the current version of Visual Studio Code (version 1.80.0).

Steps to Reproduce:

1. Install the extension
2. Click in "Switch" to pre-release version

**Comment by roblourens** [comment]
I think it should install the latest one that is compatible with your build. But, if you are not using VS Code Insiders I'd recommend the stable version anyway

**Comment by sandy081** [comment]
> Can't install pre-release version of 'github.copilot-chat' extension because it is not compatible with the current version of Visual Studio Code (version 1.80.0).

It seems there is no compatible pre-release version newer than the release version. Hence this error is thrown. We would never install the pre-release version smaller than the release version.

**Comment by roblourens** [comment]
I don't understand how that leads to this error. The latest release version was compatible with 1.80

**Comment by ONSHOR3** [comment]
same here

**Comment by sandy081** [comment]
@roblourens Assigning this back to you as the extension does not have a compatible pre-release version to be installed on latest stable release of VS Code.

**Comment by IonMironov-main** [comment]
I get the same error on Windows 10. Latest version of VS Code.
![image](https://github.com/microsoft/vscode-copilot-release/assets/97184530/9ca78113-3220-41a1-95cb-d5dd680c8fcf)

**Comment by sandy081** [comment]
This will be tracked here - https://github.com/microsoft/vscode/issues/187487 as we decided to support this in Core.
