### ISSUE TITLE
Copilot filtering out code containing SVG's

### ISSUE THREAD

**Issue by devcadotio** [microsoft/vscode-copilot-release#3153]
- Copilot Chat Extension Version: newest
- VS Code Version: newest
- OS Version: windows 10
- Logs: /

Steps to Reproduce:

1. make a file that contains this svg:
```
<svg xmlns="http://www.w3.org/2000/svg" width="24px" height="24px" fill="currentColor" viewBox="0 0 256 256">
<path d="M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z">
</path>
</svg>
```
2. prompt copilot to do something with the code
3. get filtered

**Comment by joyceerhl** [comment]
What do you mean by "get filtered"? Can you please share a screenshot?

**Comment by devcadotio** [comment]
![Image](https://github.com/user-attachments/assets/ab66b440-0474-4c49-be53-3f2859eaba6a)
that's what I mean
