### ISSUE TITLE
[Bug] Can't use "Find" in copilot chat

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode-copilot-release#3159]
- Copilot Chat Extension Version: 0.22.4
- VS Code Version: 1.95.3
- OS Version: macOS 15.1

Steps to Reproduce:

1. Use `workbench.action.chat.openInEditor`.
2. Ask questions and get responses.
3. Use `actions.find`.
4. Nothing happens.

Expected behavior:

Search widget appears.

**Comment by isidorn** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/124
