### ISSUE TITLE
Sorry, your request failed. Please try again. Request id: bda6cb7e-774a-4824-9619-bc099e43c8c0

### ISSUE THREAD

**Issue by philipheinser** [microsoft/vscode-copilot-release#3164]
Type: <b>Bug</b>

Sorry, your request failed. Please try again. Request id: bda6cb7e-774a-4824-9619-bc099e43c8c0

Extension version: 0.22.4
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (1.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by roblourens** [comment]
Which models are you using? Is this panel chat, inline chat, Copilot Edits, or something else?

**Comment by philipheinser** [comment]
got it again now. In Edits. Claude Sonnet.

```
Sorry, your request failed. Please try again. Request id: 9fed0970-ae6d-42cf-a22e-9dec028b4a7e
```

**Comment by joyceerhl** [comment]
It looks like `bda6cb7e-774a-4824-9619-bc099e43c8c0` timed out, was this also with Sonnet?

For `9fed0970-ae6d-42cf-a22e-9dec028b4a7e` it looks like this request didn't make it to our servers. The next time this happens, could you please run the Set Log Level command, choose Trace, and share the contents of the Copilot Chat output log? Thanks!
