### ISSUE TITLE
Welcome letter includes incorrect installation steps for VSCode

### ISSUE THREAD

**Issue by VanessaRussell** [microsoft/vscode-copilot-release#317]
I received the welcome letter stating that Copilot Chat was enabled for my account. Unfortunately, the installation steps for VSCode within the letter are a bit incorrect.

The letter says to install the GitHub Copilot Nightly extension:
![image](https://github.com/microsoft/vscode-copilot-release/assets/86689712/e2da1f3a-b714-41e4-a289-df20683497df)

However, that extension has been deprecated making it impossible to install:
![image](https://github.com/microsoft/vscode-copilot-release/assets/86689712/2b0f6e0b-2168-423d-9451-31c248c45214)

At this point, I double-checked that both VSCode and Github Copilot extensions were updated to the latest version. I also restarted VSCode but there still was no chat button displayed within the activity bar.

I decided to browse the list of github extension and that's when I noticed the GitHub Copilot Chat extension within the list:
![image](https://github.com/microsoft/vscode-copilot-release/assets/86689712/f81459bc-c0af-4e75-892b-805952f65ef6)

After installing that extension, the chat button appears and gives the first impression that it's working correctly.

**Comment by laurick12** [comment]
I had the same issues but I believe the new extension in the email should be "GitHub Copilot". I installed it and the chat works fine for me. GitHub Copilot nightly is no longer available

**Comment by t-prda** [comment]
I have the same issue and greet by this:
![image](https://github.com/microsoft/vscode-copilot-release/assets/81367237/6a48ed36-4113-4c8f-8bf8-40e0152911c2)

However, I do not see the chat pane after installing GitHub Copilot Chat extension :(

**Comment by ulugbekna** [comment]
I believe this has been fixed. Thank you for the heads up!
