### ISSUE TITLE
extremely poor quality compared to any other AI tool

### ISSUE THREAD

**Issue by rsxdalv** [microsoft/vscode-copilot-release#3174]
Type: <b>Bug</b>

there's no way github copilot is using GPT 4o, I have seen LLama 31b perform better than that.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31185841
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by isidorn** [comment]
Thank you for your feedback. Please try GitHub Copilot with latest pre-release extension and the latest VS Code Insdiers. There have been quite some improvements and it should work much better now.

If you still see poor quality, I would love if you can provide reproducible steps for the issues you are seeing. Thank you
