### ISSUE TITLE
Wrong line number of the referenced code

### ISSUE THREAD

**Issue by hkw2pg1** [microsoft/vscode-copilot-release#3178]
Type: <b>Bug</b>

Ask Copilot to search for TODO code in a workspace. It does find some. Two issue observed
1) it only show few results (whereas there might be many more)
2) some of the result it shown has wrong line number (ie for example, it says line 123 has todo code, but whereas the actual todo code is at different location of the same file)

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.48GB (13.32GB free)|
|Process Argv|--crash-reporter-id 7d65cace-c033-44f5-b431-722a7f0a0552|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bhavyaus** [comment]
Can you please describe what type of request you're making so we can reproduce the issue? Example files / queries will help a lot.
