### ISSUE TITLE
Unable to generate commit message

### ISSUE THREAD

**Issue by samir-jorge-araujo** [microsoft/vscode-copilot-release#318]
Version: 1.81.0-insider
Commit: 48cd8e0c1b142a46f0956b593d8331145634658e
Date: 2023-07-12T05:51:44.066Z (5 hrs ago)
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0

Details:
For days I have been receiving the error "Unable to generate commit message: 429: Too Many Requests" whenever I try to generate the commit message.

Both the extension and VSCode Insiders are in the latest version possible.
The auto complete and chat tab works as expected.

Could someone please help me with this issue?
If I can help with more details or tests, just let me know.

Steps to Reproduce:

1. Have any file staged for commiting
2. Try to generate commit message using the extension
3. You will receive the error displayed on the screenshot
![Screenshot 2023-07-12 at 12 49 26](https://github.com/microsoft/vscode-copilot-release/assets/24610866/1730fa91-18e2-46ca-99d0-cc4b9f594a46)

**Comment by digitarald** [comment]
@samir-jorge-araujo how is Copilot involved in that flow? It doesn't generate commit messages by default atm.
