### ISSUE TITLE
`copilot-debug` inject wrong arguments ( `.` instead of `./...` )

### ISSUE THREAD

**Issue by tkxkd0159** [microsoft/vscode-copilot-release#3180]
- Copilot Chat Extension Version:
- VS Code Version: 1.96
- OS Version:  Ubuntu 22.04.5
- Logs:
```
Starting: go/bin/dlv dap --log=true --log-output=debugger --listen=127.0.0.1:61066 --log-dest=3 from /user/examples
DAP server listening at: 127.0.0.1:61066
Build Error: go test -c -o /user/examples/__debug_bin796827425 -gcflags all=-N -l .
no Go files in /user/examples (exit status 1)
```

Steps to Reproduce:
my dummy project structure is
|--/cmd
|--/libs
|--go.mod

1. Run `copilot-debug go test ./...`
2. `no Go files` error occurred. I found on the debug console that the executed command was `go test -gcflags all=-N -l .` instead of `./...`
3. `go test ./...` worked fine if it runs without `copilot-debug`

**Comment by connor4312** [comment]
Thanks, can you run `copilot-debug --print go test ./...` so I can see the config it generated?
