### ISSUE TITLE
`/createWorkspace` follow up question didn't render button

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-copilot-release#319]
Take a look at the chat here:
![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/a1433ae4-5ab7-429a-b548-956ba6deed4e)

I expected that the 2nd question would give me the button to create the workspace, but it didn't.

Additionally, I asked an additional question:
![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/d3031a97-50d7-4c91-ae50-39db68026df9)

which gave me the button, but it didn't use the content from the conversation, giving me this instead:
```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
  console.log('Congratulations, your extension "my-extension" is now active!');

  let disposable = vscode.commands.registerCommand('extension.sayHello', () => {
    vscode.window.showInformationMessage('Hello World!');
  });

  context.subscriptions.push(disposable);
}

export function deactivate() {}
```

My expectation is that I was operating on the same generated workspace, but fine tuning it to what I wanted before creation but that doesn't seem to be the case.

Let me know if there's something else that I can provide that would be helpful.

**Comment by joyceerhl** [comment]
<img width="712" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/30305945/a391720f-101c-4484-80b6-dad3d58fedad">

This doesn't repro for me, should add a multiturn test to exercise this scenario though (and validate that there are always filetrees provided and therefore also followups)

**Comment by meganrogge** [comment]
cannot repro the issue
