### ISSUE TITLE
Can;t copy reponse as markdown

### ISSUE THREAD

**Issue by tobimax** [microsoft/vscode-copilot-release#3198]
Type: <b>Bug</b>

Can't copy reponse as markdown. Ask it to generate markdown documentation but you can;t copy the resulting response, only certain block. 
Extension version: 0.23.0
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 74F3 24-Core Processor                 (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|110.00GB (90.68GB free)|
|Process Argv|--crash-reporter-id 5c7ee789-ca7d-413e-a9ac-bc3fb6a76dcf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by roblourens** [comment]
This is probably https://github.com/microsoft/vscode-copilot-release/issues/793 but can you explain more? Not clear what you mean

**Comment by resatarikan** [comment]
used this prompt to generate the README.md content in a JSON format and then utilized it.

Here’s an example of the prompt and its use in Node.js or a browser developer console:
```js
// Prompt
// Can you provide the README.md content in JSON format, such as:
// { "readme": "## Installation\n ..." }

// Response
const response = { "readme": "## Installation\n ..." };

// Usage
console.log(response.readme); // Outputs: ## Installation\n ...
```

The Result:

```md
# URL Checker

This project is designed to fetch URLs from sitemaps, check their availability, and log any errors encountered during the process.

## Project Structure

```
