### ISSUE TITLE
Sorry, your request was limited to speed. Please wait 11 hours 11 minutes before trying again.

### ISSUE THREAD

**Issue by battyhal** [microsoft/vscode-copilot-release#3199]
Type: <b>Bug</b>

Copilot answer i have to wait more than 11 hours to ask again: "Sorry, your request was limited to speed. Please wait 11 hours 11 minutes before trying again." . I am a susbcriber.

Extension version: 0.23.0
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Linux x64 6.1.0-28-amd64
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by battyhal** [comment]
Sorry for the delay. I am using o1-preview(Preview). Should i use to GPT4o or Claude instead?
Thanks for your answer by the way :)

**Comment by lramos15** [comment]
You can use o1-preview no problem, but once you get limited you can switch to 4o or claude and keeping using Copilot chat since those have much higher limits!
