### ISSUE TITLE
Context-awareness of whole workspace/repository

### ISSUE THREAD

**Issue by cartermp** [microsoft/vscode-copilot-release#32]
To be blunt, chat is useless unless it has my workspace/repo as implicit context. I might as well just paste stuff into chatGPT which has a bigger UI since I have a whole page view for my browser.

Compare this to [SourceGraph Cody](https://about.sourcegraph.com/cody), in which I queue up an embedding of my repo, and then 💥 I can ask questions of my whole codebase. That's the experience I want.

*Edit*: I see nobody actually replies to the feedback anyone files 🙃

**Comment by mrtornado** [comment]
we all want this future, and yea you are right it makes no sense using it if it doesn't include workspace/repo context.

**Comment by carnuare** [comment]
This is exactly what I expected from Copilot Chat. This would be game changer.

**Comment by DMEvanCT** [comment]
This would be awesome!

**Comment by MatthewCaseres** [comment]
Copilot appears to understand some context about the folders. At least file names. cmd+shift+p indicates that there are some options that are coming in the future?

**Comment by PEZ** [comment]
I got a bit surprised asking it to use my workspace as context for my question and it answered:

> I'm sorry, but as an AI language model, I don't have access to your workspace or any other external resources. However, the code you provided is a function called ...

That last thing about ”the code you provided” seems to be because I had some code selected.

I agree this would make a huge difference. Though it probably has to be an opt-in per workspace or folder hierarchy, because people will probably have workspaces they don't want to, or don't have the right to, share with external parties.

**Comment by digitarald** [comment]
Sorry for the delay, was at a conference and we just opened this repo for feedback and are still setting up our usual triage tooling.

**Comment by jpenalbae** [comment]
I also think that being able to make questions about the workspace is a must. It would help to understand and browse large codebases. Adding the option to enable and disable per workspace also looks like a good suggestion to me.

Some example questions using the linux kernel:
- can you expand the preprocessor macro SYSCALL_DEFINE5?
- which structure is used by the key subsystem to store the keys?
- can you point me to the main function for the write syscall?
- which are the possible paths to reach the function keyctl_invalidate_key?
- can you point to structures which their size is 48 bytes?

I have included [SourceGraph Cody](https://about.sourcegraph.com/cody) output for reference:
https://imgur.com/a/Zr0WZ4v

**Comment by digitarald** [comment]
Duplicate of #14
