### ISSUE TITLE
Adding same selection to chat twice

### ISSUE THREAD

**Issue by Ironicmanx** [microsoft/vscode-copilot-release#3200]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If yes, can you provide reproducible steps?
