### ISSUE TITLE
Markdown generation escape vuln

### ISSUE THREAD

**Issue by kevinprince** [microsoft/vscode-copilot-release#3207]
Type: <b>Bug</b>

I asked CoPilot to generate a Readme but it can't output markdown correctly.

Extension version: 0.22.4
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (0.76GB free)|
|Process Argv|. --crash-reporter-id 4d8324d3-dcc4-4007-9245-837495033478|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by kevinprince** [comment]
![Image](https://github.com/user-attachments/assets/922c1000-574d-4448-ab25-f20bdf077a9f)

**Comment by joyceerhl** [comment]
What is the prompt you used?

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/793

**Comment by resatarikan** [comment]
used this prompt to generate the README.md content in a JSON format and then utilized it.

Here’s an example of the prompt and its use in Node.js or a browser developer console:
```js
// Prompt
// Can you provide the README.md content in JSON format, such as:
// { "readme": "## Installation\n ..." }

// Response
const response = { "readme": "## Installation\n ..." };

// Usage
console.log(response.readme); // Outputs: ## Installation\n ...
```

The Result:

```md
# URL Checker

This project is designed to fetch URLs from sitemaps, check their availability, and log any errors encountered during the process.

## Project Structure

```
