### ISSUE TITLE
Impossibility to check libraries

### ISSUE THREAD

**Issue by federico-pizz** [microsoft/vscode-copilot-release#3208]
Type: <b>Bug</b>

The assistant cannot provide updated info about a library. It keeps telling me to use functions that are not available since modules' updates many years ago

Extension version: 0.23.0
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22635
Modes:

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If yes, can you provide reproducible steps?
