### ISSUE TITLE
Markdown "code blocks" break Copilot Chat Answers

### ISSUE THREAD

**Issue by DanteZulli** [microsoft/vscode-copilot-release#321]
Github Copilot Chat is showing wrong the "code blocks" when asking for Markdown code with it.
- VS Code Version: 1.80.1
- OS Version: Windows 11 Pro 22H2
- Logs: (There aren't)

Steps to Reproduce:

1. Ask for Markdown code that contains some sort of "code block" enclosed with backticks (`)

![imagen](https://github.com/microsoft/vscode-copilot-release/assets/104462624/0552d128-7665-4323-981e-9060140bc404)
![imagen](https://github.com/microsoft/vscode-copilot-release/assets/104462624/2c0ce320-83c9-4965-be37-3066cb971950)

**Comment by jenshaase** [comment]
I had the same problem when I wanted to convert a latex document to markdown.

**Comment by thebleak13** [comment]
I run into this issue all the time and it is faster to just do it yourself. I really hope this bug is addressed because this could be a huge time saver!

**Comment by danielo515** [comment]
I tend to use this feature to write docs for some parts of my app, and this is quite annoying

**Comment by willwillman-kr** [comment]
Please fix this! copilot helping with documentation is a huge use case for my team and i!

**Comment by willwillman-kr** [comment]
I seem to have found a workaround by telling copilot they hecked up...

![Screenshot 2024-05-23 at 6 54 11 AM](https://github.com/microsoft/vscode-copilot-release/assets/79229197/b77bc73e-ab02-47b7-b5bc-388a50dacce8)

**Comment by alexdima** [comment]
@willwillman-kr Could you please try installing the latest [VS Code Insiders](https://code.visualstudio.com/insiders/) and the latest Copilot Chat Pre-Release extension? The latest version of the Copilot Chat Pre-Release improves the behavior of inline chat inside markdown files.

And to clarify, is your screenshot from the sidebar or from inline chat?

**Comment by alexdima** [comment]
Inline Chat should now work a lot better in markdown documents. The change is available in the latest Copilot Pre-Release and will be available with the 0.16.0 Copilot Chat version.

**Comment by willwillman-kr** [comment]
> @willwillman-kr Could you please try installing the latest [VS Code Insiders](https://code.visualstudio.com/insiders/) and the latest Copilot Chat Pre-Release extension? The latest version of the Copilot Chat Pre-Release improves the behavior of inline chat inside markdown files.
> 
> And to clarify, is your screenshot from the sidebar or from inline chat?

sorry for the delayed response! this was from the sidebar chat, once i have access to 0.16.0 i can let you know if its resolved!
