### ISSUE TITLE
wtf yall really

### ISSUE THREAD

**Issue by bi6poppa** [microsoft/vscode-copilot-release#3214]
Type: <b>Bug</b>

i asked a simple question about why my script doesnt work unless its in the head. if he cant even answer simple questions, what am i supposed to use him for

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1360P (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.81GB free)|
|Process Argv|--crash-reporter-id 05986868-6584-4ee8-b588-691f3e3ad1c5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by joyceerhl** [comment]
Can you please share the exact query you used and the response you received? Screenshots would be appreciated. Thanks!

**Comment by bi6poppa** [comment]
i didnt get screenshots of the last time, but its back at it again, about simple subjects .... best way to organize large amounts of json data this time.... i mean its not like im trying to hack the white house or something - just learning to code!!!

**Comment by bi6poppa** [comment]
i attached a screen recording, i dont see it though >.<

**Comment by joyceerhl** [comment]
Are you attaching it on Github.com? Maybe you can just share the query you used?
