### ISSUE TITLE
No way to have persistent chats

### ISSUE THREAD

**Issue by kwokcb** [microsoft/vscode-copilot-release#323]
There appears to be no way to have persistent chats, including being able to save out chats, nor even copy more than just the answer portions out.

Persistence also seems to be per-folder and not per workspace so every time I open a sub-folder in a workspace
any previous chats do not show up.

**Comment by digitarald** [comment]
To clarify, you want persistence beyond workspace, saving chats (to a file or some other way).

Context menu in chats provides _Copy_ and _Copy All_, does that solve the copy aspect you mention?

@kwokcb can you clarify the workflow of opening sub-folders of a workspace in a new VS Code session?

**Comment by kwokcb** [comment]
Hi @digitarald,
I had no idea there was a anything there until you mentioned it and I was able to figure out what mouse button to press to find copy and copy-all. For this the suggestion would be to have some visual cue otherwise I'm guessing other people will not find this functionality.

For the folder workflow, say I have this setup:
```
folderA
   +- chiild folderB
```
The edits it each are independent of each other and `folderA` is my workspace. I would have guessed that when working in a workspace that there would be some common chat log. Maybe it's hard to guess when I open `folderA` and then `folderB` -- I do this from the command line using `code .`. I guess I'd like to see it have the option to work like `github` integration works -- at the workspace level if desired.
