### ISSUE TITLE
Claude 3.5 Sonnet (Preview) works slow

### ISSUE THREAD

**Issue by qwerty2265** [microsoft/vscode-copilot-release#3236]
Type: <b>Performance Issue</b>

takes very long time to respond

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 6900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.23GB (16.18GB free)|
|Process Argv|--crash-reporter-id 12f09b77-7b26-440a-83b7-615ff3342796|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
|  Window (Separating options into a different file - ts-r_next-frontend-thaihana - Visual Studio Code)
|  Window (handler_test.go - go-chi-backend-thaihana - Visual Studio Code)
|    Folder (ts-r_next-frontend-thaihana): 274 files
|      File types: gz(44) tsx(31) js(29) webp(19) json(17) ts(10) old(6)
|                  pack(6) woff2(5) svg(4)
|      Conf files: package.json(3) settings.json(1) tsconfig.json(1)
|    Folder (go-chi-backend-thaihana): 82 files
|      File types: go(50) env(1) example(1) gitignore(1) json(1) mod(1) sum(1)
|      Conf files: settings.json(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by jakobbaumgartner** [comment]
+1

**Comment by alibalbars** [comment]
+1

**Comment by bhavyaus** [comment]
We’re currently investigating the issue. In the meantime, we recommend trying again later or starting a new chat.

**Comment by lramos15** [comment]
How slow are we talking here? Can you do F1 -> Set Log Level -> Trace. And then attach the copilot output channel via F1 -> Show output channel -> GitHub Copilot Chat

**Comment by divyam234** [comment]
I think they are deliberately limiting the use of Claude 3.5 Sonnet as Copilot is just a wrapper over open and claude api with one extra system prompt which you can find easily. There should not be any slowness unless done deliberately as opeapi models have decent response time.
