### ISSUE TITLE
Behaving like a 12 yo

### ISSUE THREAD

**Issue by HarleyVader** [microsoft/vscode-copilot-release#3244]
Type: <b>Bug</b>

Can we please just stop freaking out over every adult word used??? Its a machine, it should just ignore it & continue with the prompt... 

Why not like just CENSOR ****** the words & continue with the prompts?

Extension version: 0.23.2024102903
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|29.82GB (6.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by connor4312** [comment]
Please provide version details and steps that allow us to reproduce the issue. Thanks!

**Comment by HarleyVader** [comment]
i send it by mistake, it was a rant cuss copilot behaves like a 12 year old who has never heard swear words. its a pain to be ToS Censored by a machine whit no feelings or a real life.....



[cid:b9b25c77-eaf5-42d0-b0b9-00379269d2b5]



[LinkedIn image of LinkedIn icon][Facebook image of Facebook icon][Twitter image of Twitter icon]

    Melkanea

    (Fullstacker devOps Webmaster)

      CEO at Brandyphilias



       ***@***.***>***@***.******@***.***>

      +4367763951563



      Graz, 8020, Steiermark, Österreich

brandynette.com<https://brandynette.com/>





________________________________

**Comment by lramos15** [comment]
By using Copilot Chat you agree to the ToS and the filtering that comes with it. You will have to use an alternative AI tool if you want to make NSFW content.
