### ISSUE TITLE
Failing to every request every singlr time

### ISSUE THREAD

**Issue by UTK-a-RSH** [microsoft/vscode-copilot-release#3255]
Type: <b>Bug</b>

Whenever I put a prompt to generate the related thing around. It takes time and then responds as "Sorry, your request failed. Please try again. Request-id : xyzabcdefghjiuy.....(example)"

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Linux x64 6.8.0-50-generic
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by bhavyaus** [comment]
Can you please describe what type of request you're making so we can reproduce the issue? Example files / queries will help a lot. You can also try clearing your chat history.
