### ISSUE TITLE
Loading Forever

### ISSUE THREAD

**Issue by pathai-dborders** [microsoft/vscode-copilot-release#3257]
Type: <b>Bug</b>

Whenever I input anything to the inline input it loads forever without generating

Extension version: 0.22.4
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 24.1.0
Modes:
Connection to 'SSH: dillyscomp' could not be established 
Connection to 'SSH: dillyscomp' could not be established  Canceled
Connection to 'SSH: dillyscomp' could not be established  Timed out while waiting for the local startup lock
Connection to 'SSH: dillyscomp' could not be established 
Connection to 'SSH: dillyscomp' could not be established  Timed out while waiting for the local startup lock
Remote OS version: Linux x64 6.5.0-44-generic
Connection to 'SSH: dillyscomp' could not be established  Timed out while waiting for the local startup lock
Connection to 'SSH: dillyscomp' could not be established 
Connection to 'SSH: dillyscomp' could not be established  Canceled

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If yes, can you provide reproducible steps?
