### ISSUE TITLE
Sorry, your request failed. Please try again. Request id: 07aca431-f830-4083-a8fe-d018b6cd279d

### ISSUE THREAD

**Issue by clipecane** [microsoft/vscode-copilot-release#3297]
Type: <b>Performance Issue</b>

Sorry, your request failed. Please try again. Request id: 07aca431-f830-4083-a8fe-d018b6cd279d

Extension version: 0.23.1
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 24.1.0
Modes:

**Comment by isidorn** [comment]
Duplicate
