### ISSUE TITLE
No replying for some questions,but reply quickly for some questions

### ISSUE THREAD

**Issue by StudyingLover** [microsoft/vscode-copilot-release#33]
- Version: 1.79.0-insider (user setup)
- Commit: 2946b1ee55db1d406526d3fd1df49250b2f8322d
- Date: 2023-05-18T05:25:02.319Z
- Electron: 22.5.2
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.19045
- Logs:

My question was weird, I asked a few questions at first and got a quick response, then when I asked some other questions after a while and never got a response, I asked the original question again and got a quick response. Then I asked again and got this error
`无法删除不存在的文件 'vscode-userdata:/c:/Users/lenovo/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/api.json'` (I am a Chinese developer , this sentence means `Cannot delete non-existing file 'vscode-userdata:/c:/Users/lenovo/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/api.json'`)
![image](https://github.com/microsoft/vscode-copilot-release/assets/68844494/4d272fe9-6635-49f5-ae96-3a55ac2a557f)

Besides , copilot chat is really cool and fast

**Comment by macdovellrong** [comment]
Mark, same with me

**Comment by StudyingLover** [comment]
update a picture about this problem. I check the floder `c:/Users/lenovo/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat`, it's really empty.
![image](https://github.com/microsoft/vscode-copilot-release/assets/68844494/8f50591a-b729-451d-916c-a73d5046116a)
