### ISSUE TITLE
Unable to remove previous prompts if a message is too long

### ISSUE THREAD

**Issue by MasonKomo** [microsoft/vscode-copilot-release#330]
- VS Code Version: 1.81.0-insider (Universal)
- OS Version: macOS Ventura 13.3.1 (a) (22E772610a)
- Logs:

Steps to Reproduce:

1. Send a few messages to Copilot Chat.
2. Send a message that is too long which will trigger an error response "Sorry, this message is too long. Please try a shorter question."
3. Attempt to remove any of the prompts that were sent before the long message. (They will remain in the message history no matter how many times you click the X)

**Comment by roblourens** [comment]
This works now
