### ISSUE TITLE
User snippets popups appear when typing into copilot chat

### ISSUE THREAD

**Issue by abulka** [microsoft/vscode-copilot-release#331]
Annoying popups constantly appear whilst typing.

- VS Code Version: Version: 1.79.2 (Universal)
- OS Version: mac Ventura on M2 silicon, OS: Darwin arm64 22.5.0
- Logs: nothing in logs of relevance

Steps to Reproduce:

1. open copilot chat window
2. type a question
3. notice the popups that appear when certain words match user snippets

<img width="804" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/11467530/785f4da7-d89b-400b-b7f2-ec0d3174691e">

e.g.

<img width="790" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/11467530/a6d015aa-5f90-400b-964f-560ed8767996">

The chat seems to be matching user snippets names from all possible user snippets because I see `(User Snippet)` often in the annoying popup.

Another user with this problem https://github.com/orgs/community/discussions/58761

**Comment by roblourens** [comment]
If the snippets are properly scoped to a language, this won't happen. I'll push a fix too

**Comment by roblourens** [comment]
@jrieken is it possible to disable snippets in this editor? If I remove the SnippetController contribution, they still show up in the suggest widget but it just disables the tabbing logic.

**Comment by jrieken** [comment]
You can disable snippet completion types via the corresponding editor setting. This is how inline chat does it https://github.com/microsoft/vscode/blob/c5ccc30caf0bbf37cab5b10c78aad0937289c4dc/src/vs/workbench/contrib/inlineChat/browser/inlineChatWidget.ts#L94

**Comment by roblourens** [comment]
You just did this for me, thanks

**Comment by abulka** [comment]
Not sure what is going on re resolving this issue, or why this issue has been closed. I still get incessant popups as I type into the copilot chat window. Given the popularity of copilot, I'm suprised this issue has not gotten more attention?

Or am I missing something - is there something I can configure to stop the popups as I type?

**Comment by roblourens** [comment]
This is on the December / January milestone, and we haven't done that release yet. You should see it fixed in the Insiders build.
