### ISSUE TITLE
multiple instance  can't run on two windows

### ISSUE THREAD

**Issue by jbirbal-skydom** [microsoft/vscode-copilot-release#3313]
Type: <b>Bug</b>

`Invalid child endIndex` when using the inline chat. The sidebar works. I tried to restart vscode (exit/open) 
change the shortcode (ctl+i to alt+i)

Extension version: 0.23.1
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 6.8.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7735HS with Radeon Graphics         (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|28.75GB (16.36GB free)|
|Process Argv|--crash-reporter-id 402f75b5-058a-4745-a67e-c278bdd69d66|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: control-1s|
|OS|Linux x64 6.8.0-50-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 0)|
|Memory (System)|7.76GB (4.86GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by ulugbekna** [comment]
Could you please share the contents of the file for which you get this error?
