### ISSUE TITLE
Github Copilot Chat don't use right proxy address in wsl

### ISSUE THREAD

**Issue by ckf104** [microsoft/vscode-copilot-release#3315]
## GitHub Copilot Chat

- Extension Version: 0.23.1 (prod)
- VS Code: vscode/1.96.0
- OS: Linux
- Remote Name: wsl

## Network

User Settings:
```json
  "http.proxyStrictSSL": false,
  "github.copilot.advanced.debug.useElectronFetcher": true,
  "github.copilot.advanced.debug.useNodeFetcher": false,
  "github.copilot.advanced.debug.useNodeFetchFetcher": true
```

Environment Variables:
- https_proxy=172.22.176.1:7890
- http_proxy=172.22.176.1:7890

Connecting to https://api.github.com:
- DNS ipv4 Lookup: 20.205.243.168 (54 ms)
- DNS ipv6 Lookup: Error (4 ms): getaddrinfo ENOTFOUND api.github.com
- Proxy URL: http://127.0.0.1:7890 (0 ms)
- Proxy Connection: Error (0 ms): connect ECONNREFUSED 127.0.0.1:7890
- Electron fetch: Unavailable
- Node.js https: Error (1 ms): Failed to establish a socket connection to proxies: PROXY 127.0.0.1:7890
- Node.js fetch (configured): Error (6 ms): fetch failed
  connect ECONNREFUSED 127.0.0.1:7890
- Helix fetch: HTTP 403 (2137 ms)

Connecting to https://api.githubcopilot.com/_ping:
- DNS ipv4 Lookup: 140.82.113.21 (3 ms)
- DNS ipv6 Lookup: Error (5 ms): getaddrinfo ENOTFOUND api.githubcopilot.com
- Proxy URL: http://127.0.0.1:7890 (0 ms)
- Proxy Connection: Error (1 ms): connect ECONNREFUSED 127.0.0.1:7890
- Electron fetch: Unavailable
- Node.js https: Error (1 ms): Failed to establish a socket connection to proxies: PROXY 127.0.0.1:7890
- Node.js fetch (configured): Error (6 ms): fetch failed
  connect ECONNREFUSED 127.0.0.1:7890
- Helix fetch: HTTP 200 (1482 ms)

## Documentation

In corporate networks: [Troubleshooting firewall settings for GitHub Copilot](https://docs.github.com/en/copilot/troubleshooting-github-copilot/troubleshooting-firewall-settings-for-github-copilot).

## Problem Description
Above info is obtained by running `>Developer: Github Copilot Chat Diagnostics` in my wsl2.

Currently, I can use Github Copilot and Github Copilot Chat extension in my win11 host, and Github Copilot extension in my wsl2, but can't use Github Copilot Chat extension in wsl2.

I have a clash proxy client listening on port `7890`, so I set http proxy as `127.0.0.1:7890` in my win11 host. And wsl2 seems to automatically detect this proxy and relace it with `https_proxy=172.22.176.1:7890, http_proxy=172.22.176.1:7890`, since my win11 host has an ip address 172.22.176.1 in wsl network.

The weird thing is that Copilot Chat stick to use original `127.0.0.1:7890` proxy setting and fail to connect, which causes Copilot Chat unusable in wsl2.

I have to use a ssh forwarding to forward `127.0.0.1:7890` to `172.22.176.1:7890` each time, which is tedious.

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode/issues/219339.
