### ISSUE TITLE
rambling the same 2 sugestions over and over again

### ISSUE THREAD

**Issue by Jagoda-Cubrilo** [microsoft/vscode-copilot-release#3317]
Type: <b>Bug</b>

rambling the same 2 sugestions over and over again

Extension version: 0.23.1
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by bhavyaus** [comment]
Can you please describe what type of request you're making so we can reproduce the issue? Example files / queries will help a lot. You can also try clearing your chat history.
