### ISSUE TITLE
Follow up question blocked even though it is programming related

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-copilot-release#334]
![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/04a7478a-b74b-4aa9-b867-d09c24fd7b95)

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2625. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
