### ISSUE TITLE
Disable Inline Chat

### ISSUE THREAD

**Issue by csellis** [microsoft/vscode-copilot-release#335]
Is there a way to Disable Inline Chat?  I would really prefer to just interact on the sidebar with Chat. If not disabling, attach it to a different keybinding?

**Comment by ulugbekna** [comment]
Hi @csellis ,

Thanks for filing the issue.

You can remove or rebind the command to another shortcut. The command you want to rebind is "Inline Chat: Start Code Chat".

[more info](https://code.visualstudio.com/docs/getstarted/keybindings) 

https://github.com/microsoft/vscode-copilot-release/assets/16353531/a8960982-acb5-469e-bdad-4c8029a260c1

**Comment by csellis** [comment]
Thank you @ulugbekna 🙏. I figured it would have been in extension settings
