### ISSUE TITLE
The `@vscode /runCommand` is gone?

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-copilot-release#3350]
```
Version: 1.97.0-insider (user setup)
Commit: cf2ebd91b8e42e3bc5ab0e85e3323c886a977ffe
Date: 2024-12-18T06:50:13.779Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045
```

There is a `@vscode` Slash command called `/runCommand`. I can't find it in the latest version. Why?

![Image](https://github.com/user-attachments/assets/f4616184-ff37-479d-aa80-9229e1cdba47)

**Comment by meganrogge** [comment]
This was removed in favor of an extension https://github.com/microsoft/vscode-commander, I'll update the docs
