### ISSUE TITLE
Copilot is lying, stating it makes changes yet just repost same code

### ISSUE THREAD

**Issue by stefankinell** [microsoft/vscode-copilot-release#3351]
Type: <b>Bug</b>

There is a serious fault with copilot in terms of that it can repost the same code 10 times, each time saying it has solved the issue I asked it to adress - yet it has done nothing to the code. But still explaining in the text what changes it has done. When I ask what changes it has done - it answer "nothing" 

How do I stop copilot from lying like this? 

Extension version: 0.23.1
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|30, 32, 44|
|Memory (System)|64.00GB (5.57GB free)|
|Process Argv|--crash-reporter-id 273b31b2-853d-493b-a5c2-38327e95ec84|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by stefankinell** [comment]
this is seriously disturbing. This is a service I pay for. Yet it is just lying. why does nobody take this serious? I have reported it several times before and it seems you do not care at al?

**Comment by bhavyaus** [comment]
Could you describe the type of request you’re making so we can reproduce the issue? Providing example files or queries would be very helpful. You might also try clearing your chat history.

**Comment by stefankinell** [comment]
please look at https://github.com/microsoft/vscode-copilot-release/issues/3328 for follow up on this topic
