### ISSUE TITLE
clear chat history (just whats on the screen), and a "flush conversation and start from scratch" button.

### ISSUE THREAD

**Issue by swheettaos** [microsoft/vscode-copilot-release#3363]
I would like to clear the chat history.  Also sometimes I go a rabbit hole with the chat and it keeps referring to the old conversation and it gets confused.  Sometimes I need an "ok.. let's start over, forget everything I was talking about and start fresh" option.

**Comment by kieferrm** [comment]
Several ways you can do this:
- Use the plus in the toolbar (see picture)
- Use the `/clear` command directly (see picture)
- In the command palette (<kbd>F1</kbd>)using `Chat: New Chat` 

![Image](https://github.com/user-attachments/assets/d4d30b54-1c6b-47f7-9fca-0c2748e43409)

**Comment by swheettaos** [comment]
OK!  Thanks!
