### ISSUE TITLE
Scroll position is changed when switching editors with chat widget open

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#337]
- Open inline chat widget, scroll so that it's in centered in the editor viewport
- Switch to a different tab
- Switch back
- The editor is scrolled so that that chat widget is at the bottom. Happens every time regardless of file or scroll position

**Comment by roblourens** [comment]
Now the inline chat widget goes away when switching editors, is that right?

**Comment by jrieken** [comment]
it should only go away when you have done anything with it. As soon as you ran a prompt it should be restored
