### ISSUE TITLE
Extraneous files included in working set automatically, even when explicitly removed prior to executing a prompt

### ISSUE THREAD

**Issue by tonyketcham** [microsoft/vscode-copilot-release#3374]
Type: <b>Bug</b>

While doing feature development, it's normal to have files open in split view which are not immediately involved in the current Copilot context, because they are unrelated to the prompt I am attempting to iterate a solution on. 

Copilot automatically adds any file open in split view to the Working Set on starting a prompt from `cmd` + ` shift` + `i`. I then explicitly remove it from the Working Set. However, Copilot automatically adds it back in during execution, and then attempts to change said unrelated file first if that file is to the left of the one I am attempting to focus the prompt on. This UX is _incredibly_ frustrating as it seems the only way to avoid it is to exit my split view context entirely and lose markers about where I am in building a large feature.

Extension version: 0.23.2024102903
VS Code version: Code 1.96.0 (Universal) (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 347ab492-ea6d-4d00-8d4f-c149bbb7267b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt551:31179978
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by joyceerhl** [comment]
> However, Copilot automatically adds it back in during execution, and then attempts to change said unrelated file first if that file is to the left of the one I am attempting to focus the prompt on. 

This is not expected, but I can't reproduce this behavior. Can you please share a screen recording so I can try to repro?
