### ISSUE TITLE
Copilot's online search feature doesn't work in both the web version and the VSCode plugin

### ISSUE THREAD

**Issue by veryrichhh** [microsoft/vscode-copilot-release#3386]
- Copilot Chat Extension Version:  0.23.2
- VS Code Version: 1.96.1
- OS Version: macOS 15.1.1 (24B91)
- Logs: <img width="709" alt="Image" src="https://github.com/user-attachments/assets/f2d0a12e-33ca-4b04-88ae-dd772947a782" />

Steps to Reproduce:

1. Explicitly instruct GitHub Copilot to use online search in VSCode or on the web. 
2. Prompt indicates that online search cannot be performed."
3. I am a GitHub Copilot Pro subscriber in China, but the Copilot's online search feature doesn't work in both the web version and the VSCode plugin. According to the user guide, it should have online functionality.

**Comment by joyceerhl** [comment]
Online searches must still be related to programming, but as a workaround to explicitly trigger web search, you can write `@github #web` at the start of your query
