### ISSUE TITLE
Copilot - Can not uninstall

### ISSUE THREAD

**Issue by mdeberts** [microsoft/vscode-copilot-release#3394]
- Copilot Chat Extension Version: 1.253.0
- VS Code Version: 1.96.1
- OS Version: Windows 10 Windows_NT x64 10.0.19045
- Logs:

Steps to Reproduce:

1. Install CoPilot
2. Deinstall Copilot

I installed Copilot extension in VsCode. 
Since it did not work and I could not login to github via the VsCode Copilot Interface button I uninstalled CoPilot.
It is uninstalled if I check my extensions on the left side. But it's still displayed on the right side of VsCode so obviously its still installed.

Since it is also destroying my function hopping in Python (I dont know why but its broken since the install of Copilot) I have to get rid of your software.

Please tell me how to uninstall Copilot.
Thanks

**Comment by joaomoreno** [comment]
> It is uninstalled if I check my extensions on the left side. But it's still displayed on the right side of VsCode so obviously its still installed.

Extensions do not automatically deactivate on uninstall, but only on the next restart. If you restart VS Code, is the extension still around?

**Comment by mdeberts** [comment]
GitHub CoPilot is not installed anymore after restart as an extension.
If I go to extensions it's not shown.

But on the right side of my screen its still there 
![Image](https://github.com/user-attachments/assets/1df30be0-71e5-4000-8ac9-b834e11242d8)

**Comment by bpasero** [comment]
Use "Hide Copilot" or hide the view.

![Image](https://github.com/user-attachments/assets/3c6bbdf0-a702-4577-9bb3-70efc9418901)
