### ISSUE TITLE
On Apply on editor it's rewrite all the page instead of adding a few lines of code

### ISSUE THREAD

**Issue by omarlo66** [microsoft/vscode-copilot-release#3403]
Type: <b>Performance Issue</b>

it destoryed the whole page up to 800 lines of codes to insert a few lines of codes. I used 
Cursor and Wind Surf their are much better try their tools or use their technology to handle things.

Really upset of this.

Extension version: 0.23.2
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.18362
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A10-8700B R6, 10 Compute Cores 4C+6G    (4 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|14.92GB (5.54GB free)|
|Process Argv|--crash-reporter-id d40ad910-31f9-4bcd-b7fb-c11b2346d812|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	   123	 17120	code main
    0	    42	 10072	ptyHost
    0	     5	 14684	     conpty-agent
    0	    53	 14848	     C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\common\scripts\shellIntegration.ps1\" } catch {}"
   25	   574	 10812	extensionHost [1]
    0	    66	  8352	     electron-nodejs (bundle.js )
    1	   133	 14840	     electron-nodejs (intelephense.js )
    0	    38	 14860	     electron-nodejs (init.js )
    0	     8	 12512	   C:\Users\user\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-42b266171e51a016313f47d0c48aca9295b9cbb2.exe /verysilent /log /update="C:\Users\user\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-42b266171e51a016313f47d0c48aca9295b9cbb2.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    0	    22	 14200	     "C:\Users\user\AppData\Local\Temp\is-O5DCJ.tmp\CodeSetup-stable-42b266171e51a016313f47d0c48aca9295b9cbb2.tmp" /SL5="$80826,103861510,828416,C:\Users\user\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-42b266171e51a016313f47d0c48aca9295b9cbb2.exe" /verysilent /log /update="C:\Users\user\AppData\Local\Temp\vscode-stable-user-x64\CodeSetup-stable-42b266171e51a016313f47d0c48aca9295b9cbb2.flag" /nocloseapplications /mergetasks=runcode,!desktopicon,!quicklaunchicon
    7	   498	 13532	window [1] (● sign-up.php - logistics - Visual Studio Code)
    0	    72	 14088	shared-process
    0	    26	 14384	   utility-network-service
    2	    93	 14620	   gpu-process
    0	    43	 14960	fileWatcher [1]
    0	    12	 16572	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● sign-up.php - logistics - Visual Studio Code)
|    Folder (logistics): 7686 files
|      File types: svg(3740) php(1853) js(432) css(242) png(142) md(120) z(84)
|                  DS_Store(55) ttf(54) woff(52)
|      Conf files: makefile(1) dockerfile(1);
```

</details>
<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by omarlo66** [comment]
Let me explain in detail maybe I was upset at this moment, I am sorry if my description was not accurate enough 😅. 

What happened is I was trying the chat to allow it to add a function. Then I pressed "apply on editor" button to insert the function it suggests.


What happens when I click is it start from line 1 until the last line re-writting the whole file lines while it should just append code in the right place as I am used to while using Wind Surf which is amazing IDE.


I was feeling it will change my code or the first thousand lines when it was rewritting and I didn't find any button to stop this long process of rewrite a thousands of lines.


So, I pressed CTRL+Z to undo, then it deleted the code after rewriting instead of removing the part it added to my code.

Hope my explanation this time is more accurate, I am proud of what copilot provide and seeking to find it the best ever in that market.


Sorry again if I was upset at my issue description. Of course all people who worked on this tool is brilliant and they deserve the best respect ever.


Thank you for fast response.

**Comment by aeschli** [comment]
The rewriter creates an edit for every line, even if the line has not been modified.

**Comment by aeschli** [comment]
Looking into this, 'apply in edit' still uses the non-streaming API and it gets changes in one big edit.
So what we see in the screencast is all inline preview, introduced by recent changes @jrieken 

- We want to switch t streaming API anyway, so I'll do that
- IMO we need to improve the inline preview to do fewer visual effects and just focus on the actual change

@omarlo66 Our recent focus has been all on the Copilot Edit experience to change files, and `Apply Edit` got forgotten. We'll improve it but in the meantime I recommend you use the Edits UI for editing.
