### ISSUE TITLE
Limit messages?

### ISSUE THREAD

**Issue by mafimengue** [microsoft/vscode-copilot-release#3426]
Type: <b>Bug</b>

I have a Pro Subsription but I´m limited at the same time? I don´t see any limit messages in the description of my subscription.

Extension version: 0.23.2
VS Code version: Code 1.96.1 (Universal) (42b266171e51a016313f47d0c48aca9295b9cbb2, 2024-12-17T17:50:05.206Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id db7b843e-cf92-458d-ba24-e609b72e0698|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by rebornix** [comment]
@mafimengue were you using o1 when you got the rate limit error?

**Comment by mafimengue** [comment]
Yes, I think so.
________________________________
De: Peng Lyu ***@***.***>
Enviado: viernes, 20 de diciembre de 2024 4:28
Para: microsoft/vscode-copilot-release ***@***.***>
Cc: Diego Vega Loro ***@***.***>; Mention ***@***.***>
Asunto: Re: [microsoft/vscode-copilot-release] Limit messages? (Issue #3426)


@mafimengue<https://github.com/mafimengue> were you using o1 when you got the rate limit error?
