### ISSUE TITLE
Chat view is not visible

### ISSUE THREAD

**Issue by forons** [microsoft/vscode-copilot-release#343]
- VS Code Version: Version: 1.80.2 (Universal)
- OS Version: MacOS Ventura 13.4.1

GitHub Copilot Chat and GitHub Copilot extensions have been installed following the [guidelines](https://docs.github.com/en/copilot/github-copilot-chat/using-github-copilot-chat#installing-the-visual-studio-code-extension). 
<img width="401" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4101332/9b64a9fa-5cbc-4104-8ad6-1f76c7097331">

However, the extension is not usable since it is not visible on the sidebar as shown in the attached picture.
<img width="282" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4101332/3096f93e-60e0-4c1f-ac22-643a57e30bbb">

Could you please help?

**Comment by NikiLentz** [comment]
Maybe try cmd+shift+p and try out the chat: open in sidebar as a workaround.

**Comment by forons** [comment]
There is no option for `chat` 
<img width="592" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4101332/e35ad2fb-9289-416d-84eb-59169390c983">

**Comment by lramos15** [comment]
Do you have an active copilot for business subscription and your organization has enabled the chat beta or do you see that you're off the waitlist [here](https://github.com/github-copilot/chat_waitlist_signup/join)

**Comment by forons** [comment]
From the link you posted, it actually shows that I still have to join the waitlist.

**Comment by lramos15** [comment]
> From the link you posted, it actually shows that I still have to join the waitlist.

Odd, can you screenshot the email you got stating access is granted

**Comment by forons** [comment]
<img width="689" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4101332/ec6fe1b3-bb3d-465e-826d-2c317c381bc6">

**Comment by digitarald** [comment]
@forons can you make sure that you are using the account that got Chat access through `performgroup`.

And a second thing to double-check is to sign out:

<img width="514" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/36f79f5d-9b9a-4340-b2c7-c20c317ce486">

Then reload VS Code and follow the sign in to GitHub Copilot signage (notification or badge on the accounts menu)

**Comment by forons** [comment]
I did that, but unfortunately it didn't help

**Comment by digitarald** [comment]
@forons can you check that Copilot Chat is enabled for all your enterprise orgs? Right now, if one has Chat disabled, it will override any enablement.

**Comment by TeaEwan** [comment]
Chat view was visible until about an hour ago, but now it's not visible, updating the vs code insiders version doesn't work either.

**Comment by lramos15** [comment]
> Chat view was visible until about an hour ago, but now it's not visible, updating the vs code insiders version doesn't work either.

Does `F1 -> Reset View Locations` work for you? Sometimes it's accidentally dragged and moved.

**Comment by rodrigoauglima** [comment]
I am in the list and I was using the copilot chat until 1h ago. But after the last release instalation (I'm using vs code pre release and copilot chat extension pre release as well), the chat menu is there but I click and no chat windown is shown.

**Comment by Starefossen** [comment]
Same issue started after latest version update/restart of VS Code Insiders:

```
Version: 1.82.0-insider (Universal)
Commit: 1606401f5b761397488f53b75130809fba073194
Date: 2023-08-07T05:36:04.921Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
```

```
GitHub Copilot Chat v0.7.2023080701
GitHub Copilot v1.101.318
```

**Comment by lramos15** [comment]
This is a known bug, we're rolling out a new insiders shortly to address it

**Comment by TeaEwan** [comment]
> > Chat view was visible until about an hour ago, but now it's not visible, updating the vs code insiders version doesn't work either.
> 
> Does `F1 -> Reset View Locations` work for you? Sometimes it's accidentally dragged and moved.

Not working. Chat view not visible. `Shift` + `CMD` + `I` is works. 

<img width="1061" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/93706123/5a5cd9cc-3651-4e0f-a172-48dcce6f414a">

**Comment by lramos15** [comment]
Please try the insiders and let me know if it helps. To be clear this helps the people who see the icon but there is nothing when they click it. The lack of an icon all together is a different bug

**Comment by TeaEwan** [comment]
Working on the latest version, thanks!

<img width="950" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/93706123/15570a0a-0822-4a25-b23a-c64f561970cc">

**Comment by johndunderhill** [comment]
This continues to be a problem on a Mac with the latest non-insider builds (VS Code, Copilot, Copilot Chat) installed as of today.  No Github icon on the sidebar.  Copilot itself works, so I presume I'm authenticated/allowed.  No option in Command palette.

**Comment by lramos15** [comment]
> This continues to be a problem on a Mac with the latest non-insider builds (VS Code, Copilot, Copilot Chat) installed as of today. No Github icon on the sidebar. Copilot itself works, so I presume I'm authenticated/allowed. No option in Command palette.

Please give insiders and the pre-release of the extension a try :)

**Comment by digitarald** [comment]
Thanks for your patience and feedback on this issue. We have consolidated all the troubleshooting steps for this problem in https://github.com/microsoft/vscode-copilot-release/issues/436. We have enabled more accounts and resolved some bugs since the first reports came in, so you should encounter this issue much less often now.

**Comment by ahsancloudcode** [comment]
I am facing an issue regarding GitHub Copilot Chat (organization account). In the waitlist URL showing me 404 this time , but week before it was showing me "You are in waitlist".  I dont have any option in vscode to enable copilot chat . I have already installed "Github Copilot Chat" extension.
