### ISSUE TITLE
Copilot does not understand test command

### ISSUE THREAD

**Issue by fhavrlent** [microsoft/vscode-copilot-release#346]
- VS Code Version: 1.81.0-insider (Universal)
- OS Version: MacOS 13.4.1

Steps to Reproduce:

1. Select any testable code
2. Try to generate tests

For past few weeks, Copilot always returns 
```
I'm sorry, I don't understand what you mean by "/test". Can you please provide more context or information about what you are looking for?
```

**Comment by roblourens** [comment]
Good call, the correct command is `/tests` and you can type this manually but the command uses the wrong one.
