### ISSUE TITLE
Code chat context of vs code window + relevant documentation web crawled for additional context.

### ISSUE THREAD

**Issue by FelixMildon** [microsoft/vscode-copilot-release#348]
Title says it all

**Comment by lramos15** [comment]
There are two issues here both of which are already mentioned in this repro.
Marking as duplicate of https://github.com/microsoft/vscode-copilot-release/issues/200

**Comment by FelixMildon** [comment]
My issue is nothing like #200.

Im saying vs code copilot chat should use the vs code "open editors" as context.
