### ISSUE TITLE
[Bug] quick fix dropdown sort order should show import as first option

### ISSUE THREAD

**Issue by dmitrifaleev** [microsoft/vscode-copilot-release#349]
with copilot extension installed, when using quick fix menu to fix a broken import, Copilot options are shown at the top and import option is last. 

![image](https://github.com/microsoft/vscode/assets/80595966/9a5dd383-6548-49c2-89b0-ca551a615467)

suggested feature is to show import option first and copilot options after that. this is specific to fixing import but likely the case for other simple fixes.

**Comment by CyrusNajmabadi** [comment]
This is also affecting Roslyn.  You guys are showing over our *high priority* items.  Specifically, "Add import".  This is the item that has highest pri in our system, and literally has billions of usages in our telemetry tracking.  Can you prioritize the work to not show up above these lang-specific, high pri items?  Thanks!

**Comment by ChewingGlass** [comment]
Agree, this is annoying enough I may uninstall co-pilot.

**Comment by marwie** [comment]
This is very annoying unfortunately

![image](https://github.com/microsoft/vscode-copilot-release/assets/5083203/f7664810-4fde-43bc-b2d0-df8c142f0871)

**Comment by ranjitparva** [comment]
Copilot quick fix options are super annoying. Please provide a setting to disable them or place them at the bottom

**Comment by aiday-mar** [comment]
related to https://github.com/microsoft/vscode-copilot/issues/670

**Comment by caxco93** [comment]
Was able to disable this by disabling:

`Settings` > **Extensions** > **Copilot** > **Enable Code Actions**

Alternatively, via settings.json:
```
{

  "github.copilot.editor.enableCodeActions": false,
  
}
```

Not sure what else it disables yet tho. Will update if I stumble upon something else 👍

**Comment by aiday-mar** [comment]
Hi this setting indeed removes the copilot code actions. 

We are currently discussing how best to reorder the code actions with the team.

**Comment by CyrusNajmabadi** [comment]
Hi @aiday-mar can you please keep roslyn in the loop on this?  Your code actions are definitely affecting some of our core experiences.  Thanks!

**Comment by nolawnchairs** [comment]
Disabling the option outright is a terrible option, because at times I may want to use the Copilot options, the imports quick fix is what 99.99999999999999999% of developers want at the top. Please fix this by adding an option to order, so put Copilot stuff at the bottom of the menu where it belongs.

**Comment by aiday-mar** [comment]
Hi all, this issue is fixed in latest insiders and copilot-chat. When stable comes out you should see it there.

**Comment by i-am-the-slime** [comment]
@aiday-mar How is this fixed? I still get the Copilot stuff as the first entries in the list half a year later on stable. Is there some setting to order them to the bottom?

**Comment by aiday-mar** [comment]
Hi @i-am-the-slime could you please post here a screen-recording of this behavior. Are you on the latest stable?
