### ISSUE TITLE
Responsible AI overaggressive on censoring 

### ISSUE THREAD

**Issue by tabortrailways** [microsoft/vscode-copilot-release#3500]
Type: <b>Bug</b>

Prompt:

Ensure that all db functions called from process_jetstream.py can be use asynchronously

Response (after first showing valid code):

Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again. 

The file in question (which was created by Copilot as well) contains enums that contain the word 'porn' which I suspect is the issue. But again Copilot created these table definitions without issue in the first place.

These tables are used to manage my blocklists on bluesky via their API.

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS listing_queue (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        list_owner_did VARCHAR(64),
        list_id VARCHAR(64),
        listing_did VARCHAR(64),
        list_description TEXT CHECK(list_description IN ('porn', 'lottery', 'profile', 'pch', 'pretender', 'maga', 'beggar', 'creeper')),
        listable BOOLEAN DEFAULT TRUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )
    """)

and

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS automations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        auto_list BOOLEAN DEFAULT FALSE,
        auto_report BOOLEAN DEFAULT FALSE,
        list_type TEXT CHECK(list_type IN ('pornbot', 'beggar', 'maga', 'pretender', 'lottery', 'pch', 'illuminati', 'crypto', 'criminal', 'creeper')),
        report_type TEXT CHECK(report_type IN ('profile', 'posts', 'misleading')),
        report_text TEXT,
        match_type TEXT CHECK(match_type IN ('handle', 'profile', 'post')) NOT NULL,
        match_text TEXT NOT NULL,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )
    """)
    

Extension version: 0.24.2024121201
VS Code version: Code 1.96.2 (Universal) (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|12, 9, 8|
|Memory (System)|64.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 23ae5c05-98bd-4422-8060-62887e466304|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by AlexHall13** [comment]
This is awful and happening to me too, I just wanted help making sure my sword attack happened in the direction the character was facing and now I'm completely locked out of using ANY co-pilot feature. Even just typing "help" will repeat the same "Sorry this response has been filtered".

Wtf.
