### ISSUE TITLE
/createWorkspace no longer visible in the / commands

### ISSUE THREAD

**Issue by mahujaDonorly** [microsoft/vscode-copilot-release#351]
The /createWorkspace command no longer shows up in the list of commands available

Version: 1.80.0
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:48.236Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-46-generic
Github copiliot chat verion 
4/27/2023, 00:13:54
Last released
8/3/2023, 14:27:09
Identifier
github.copilot-chat

Steps to Reproduce:

1. The commands no longer appear. They did briefly when I installed. They suggested a few things and then they disappeared.

**Comment by joyceerhl** [comment]
`createWorkspace` is currently only available when using the pre-release of Copilot Chat. Please switch to that and let us know if you still don't see it as an option.

**Comment by hhhhaaarry** [comment]
I'm using last version of Insiders, and also the pre release version of copilot chat extension, but the command /createWorkspace only appeared the first time i installed copilot chat, and it did let me to create a wokspace, in visual studio (not insiders), and then it dissapeared from the command palette and can't use it anymore. I've downloaded the pre-release of copilot chat and installed vs code insiders and it still doesn't show up. 

Thanks

**Comment by joyceerhl** [comment]
@hhhhaaarry `/createWorkspace` has been renamed to `/new`, please let us know if you don't see that option

**Comment by hhhhaaarry** [comment]
Thank you, i see that command now. The only thing that doesn't work is when you add more prompts to refine the creation, it only "sees"the new one and forget about the first prompt

**Comment by joyceerhl** [comment]
Hm, I cannot repro, can you please file a new issue for that?

**Comment by adamantivm** [comment]
> @hhhhaaarry `/createWorkspace` has been renamed to `/new`, please let us know if you don't see that option

I'm probably on the dumbest side of things but it took me a couple of hours to finally get here and find this update. Googling and chatting with copilot didn't help.

I really hope some refrence to this rename is adding somewhere close to here: https://github.blog/changelog/2023-07-14-github-copilot-july-14th-update/#new-create-commands-in-visual-studio-code-1-80
