### ISSUE TITLE
Need an 'x' button.

### ISSUE THREAD

**Issue by DebrisHauler** [microsoft/vscode-copilot-release#3510]
Type: <b>Feature Request</b>

Why is there no x button on the copilot terminal prompt? It is taking up too much screen space to use the terminal comfortably!

Extension version: 0.23.2
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.167.4-microsoft-standard-WSL2

**Comment by kieferrm** [comment]
Pressing <kbd>ESC</kbd> closes the inline chat widget in the terminal.
