### ISSUE TITLE
(intermediate value)(intermediate value)(intermediate value)?.map is not a function

### ISSUE THREAD

**Issue by tuturis** [microsoft/vscode-copilot-release#3514]
Type: <b>Bug</b>

pointo a folder and ask to extract the layoyt

Extension version: 0.23.2024102903
VS Code version: Code 1.96.0 (138f619c86f1199955d53b4166bef66ef252935c, 2024-12-11T02:29:09.626Z)
OS version: Windows_NT x64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3950)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.91GB (16.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kieferrm** [comment]
Pls see https://github.com/microsoft/vscode-copilot-release/issues/3474#issuecomment-2559894867
