### ISSUE TITLE
Will not accept or discard

### ISSUE THREAD

**Issue by JoryUK** [microsoft/vscode-copilot-release#3517]
Type: <b>Bug</b>

Seems stuck

Extension version: 0.22.2024101103
VS Code version: Code - Insiders 1.95.0-insider (Universal) (a016ec9b66ffdd3ff0f831768b8e75be008a54e4, 2024-10-09T05:04:08.601Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 4, 12|
|Memory (System)|32.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 7e871be8-bb67-4b60-afdb-44fd46d0b691|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aa:30263845
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
vscaac:30438845
c4g48928:30535728
962ge761:30841072
pythonnoceb:30776497
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
cppperfnew:30980852
pythonait:30973460
dvdeprecation:31040973
dwnewjupyter:31046869
2f103344:31071589
nativerepl1:31134653
pythonrstrctxt:31093868
nativeloc1:31118317
cf971741:31144450
e80f6927:31120813
iacca1:31150324
notype1:31143044
dwcopilot:31158714
h409b430:31177054
3d9ag387:31183121
c3hdf307:31184662
6074i472:31201624

```

</details>

**Comment by kieferrm** [comment]
Can you pls provide more details? I assume this is after using Copilot Edits. Do you use the buttons in the Copilot Edits panel or the ones on a diff within the editor?
