### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Nechrito** [microsoft/vscode-copilot-release#352]
- Issue Type: `Performance`
- Extension Name: `copilot-chat`
- Extension Version: `0.7.2023072802`
- OS Version: `Windows_NT x64 10.0.25921`
- VS Code version: `1.82.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/phili/AppData/Local/Temp/GitHub.copilot-chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by roblourens** [comment]
Please attach the file mentioned

**Comment by Nechrito** [comment]
[GitHub.copilot-chat-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-copilot-release/files/12378351/GitHub.copilot-chat-unresponsive.cpuprofile.txt)


> Please attach the file mentioned

**Comment by roblourens** [comment]
Thanks. Unfortunately, the trace doesn't capture the issue, so there isn't anything I can do about this right now. If you see this message often, we can have you capture a trace manually of the extension activating.
