### ISSUE TITLE
copilot won't sign in any more from devcontainer.

### ISSUE THREAD

**Issue by TijlJappens** [microsoft/vscode-copilot-release#3521]
- Copilot Chat Extension Version: 1.254.0
- VS Code Version: 1.96.1
- OS Version: Kubuntu 24.04
- Logs: None

![Image](https://github.com/user-attachments/assets/bb0bc9c2-c96e-46f6-8666-179f67322229)

Ever since an update copilot won't sign in any more in my devcontainer. It still works locally though. I have copilot premium.

I get the use copilot button but pressing it doesn't do anything.

Steps to Reproduce:

1. Just open a devcontainer and try to log in.

Edit: I've noticed the problem only appears sporadic and when it happens rebuilding the container can help but I would still like to understand why I need to rebuild the container to make it work and if I can't do something less drastic then rebuilding my entire container.

**Comment by kieferrm** [comment]
Pls see https://github.com/microsoft/vscode/issues/236537. The fix is in 1.96.2 that we released last week. Pls reopen, if this does not fix your problem.
