### ISSUE TITLE
Chat Not Working With Code-Server (1.80)

### ISSUE THREAD

**Issue by cnaples79** [microsoft/vscode-copilot-release#353]
- VS Code Version: 1.80
- OS Version:
- Logs:

Steps to Reproduce:

1. Install Copilot-chat via vsix
2. Error message occurs

I can't seem to get copilot-chat working with the latest version of code-server. The extension says it is incompatible with Version 1.80. Is there any workaround for this or way to install an earlier version of the extension that worked with 1.80? I tried manually installing 0.4.0, and it installs, but the sidebar icon is missing and there is no functionality.

**Comment by lramos15** [comment]
Can you try the official VS Code server via one of the remote extensions? Third party integrations may not work and are not officially supported.

**Comment by cnaples79** [comment]
> Can you try the official VS Code server via one of the remote extensions? Third party integrations may not work and are not officially supported.

I am not exactly sure what you mean. I am using the latest version of Code-Server (official), which is running 1.80 right now. The extension DOES work on VS Code (1.81), just not Code-Server. The versions of Copilot Chat past 0.4.0 (0.5+ and up) will not install on the latest version of Code-Server right now. Also, what do you mean by 'remote extensions'? Thank you for the response, if there is any other information I can provide please let me know.

**Comment by cnaples79** [comment]
> Can you try the official VS Code server via one of the remote extensions? Third party integrations may not work and are not officially supported.

Ah, I think I see what you meant. Yes, the extension DOES work on the FULL version of VS Code (1.81). However, I'm trying to get it to run on Code-Server, and the latest version of Code-Server is using 'Code 1.80', which does not seem to be compatible with the Chat extension currently. I'm just trying to figure out 1. If there is any kind of work-around, and 2. Why an earlier version of the Chat extension (0.4.0 for example) ALSO is not working.

**Comment by lramos15** [comment]
> > Can you try the official VS Code server via one of the remote extensions? Third party integrations may not work and are not officially supported.
> 
> Ah, I think I see what you meant. Yes, the extension DOES work on the FULL version of VS Code (1.81). However, I'm trying to get it to run on Code-Server, and the latest version of Code-Server is using 'Code 1.80', which does not seem to be compatible with the Chat extension currently. I'm just trying to figure out 1. If there is any kind of work-around, and 2. Why an earlier version of the Chat extension (0.4.0 for example) ALSO is not working.

You're using this https://github.com/coder/code-server ?

**Comment by cnaples79** [comment]
> > > Can you try the official VS Code server via one of the remote extensions? Third party integrations may not work and are not officially supported.
> > 
> > Ah, I think I see what you meant. Yes, the extension DOES work on the FULL version of VS Code (1.81). However, I'm trying to get it to run on Code-Server, and the latest version of Code-Server is using 'Code 1.80', which does not seem to be compatible with the Chat extension currently. I'm just trying to figure out 1. If there is any kind of work-around, and 2. Why an earlier version of the Chat extension (0.4.0 for example) ALSO is not working.
> 
> You're using this https://github.com/coder/code-server ?

Yes. Code-Server running code version 1.80
2. Copilot Chat will not install even though this is the latest version.

**Comment by lramos15** [comment]
Yeah code server is distributed by a third party and is not officially supported. The latest stale build of VS Code is 1.81 and the latest insiders is 1.82. Please upgrade to the latest builds and use official builds and see if you can reproduce :)

**Comment by digitarald** [comment]
https://code.visualstudio.com/docs/remote/vscode-server is the officially supported VS Code Server. Please re-open if the issue persists using this stack.
