### ISSUE TITLE
Attach Image is needed like Cursor.ai

### ISSUE THREAD

**Issue by AlexiaChen** [microsoft/vscode-copilot-release#3530]
The cursor.ai has a feature that can attach/upload images to chat.  That's very helpful for frontend developers , that can quickly implement prototype of Web pages.

Vision for Copilot Preview extension is not good. it need API key  and I must pay for another platform.... but corsor is built-in for image... just pay once, no more again.....  I want all-in-one like cursor.

**Comment by AlexiaChen** [comment]
found the answer : https://github.com/microsoft/vscode-copilot-release/issues/2127#issuecomment-2460564937   seems vision will built-in in the future

**Comment by kieferrm** [comment]
Early 2025
