### ISSUE TITLE
Install for VS2022 fails with "This extension is not installable on any currently installed products"

### ISSUE THREAD

**Issue by bjorn-jarisch** [microsoft/vscode-copilot-release#356]
- VS Version: Visual Studio Enterprise 2022 Version 17.5.5
- OS Version: Windows 11 Pro 22H2
- Logs: [dd_VSIXInstaller_20230807172712_144c.log](https://github.com/microsoft/vscode-copilot-release/files/12282051/dd_VSIXInstaller_20230807172712_144c.log)

Steps to Reproduce:

1. Uninstall existing GitHub Copilot extension
2. Close Visual Studio
3. Download "GitHub Copilot Chat" VSIX installer (https://visualstudioexptteam.gallerycdn.vsassets.io/extensions/visualstudioexptteam/vsgithubcopilot/0.1.1227.30435/1691107996632/VisualStudio.GitHub.Copilot.vsix)
4. Run VSIX installer
5. Get immediate error message "This extension is not installable on any currently installed products"

**Comment by bjorn-jarisch** [comment]
Update: VS Version 17.6.5 works, but a) the invite email says the minimum required version is 17.5.1, and b) the extension download page only says "Visual Studio 2022" in general, so at least the documentation should be updated.

**Comment by markw-t** [comment]
Hi @bjorn-jarisch - my apologies for the misalignment of the invitation mail. We recently raised the minimum requirement for GitHub Copilot Chat to Visual Studio 2022 Version 17.6 as you have observed. I'll make sure the invitation mail gets updated.

Thanks also for trying Copilot Chat in Visual Studio. If you have further feedback and issues regarding the Github Copilot Chat extension for Visual Studio it'd be really great if you can report via the [report a problem feature](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) - this allows us to gather more information about your installation and provides a way for you to share your Copilot chat logs directly with us too. Logs are very helpful in diagnosing some issues. They are written each time you close Visual Studio. You can find your logs in the %TEMP%\VSConversationsDiagnosticLogs folder, sorting in reverse date order to find the latest log

Thanks
Mark

**Comment by macjohnmcc** [comment]
I am having this exact same error on Visual Studio 2022 Enterprise 17.10.34928.147

C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe,/skuName:Enterprise,/skuVersion:17.10.34928.147,/appidname:Microsoft Visual Studio Enterprise 2022,/culture:en-US,/noep,C:\Users\John\AppData\Local\Temp\VSIX1bukhugc.vsix

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products

**Comment by nzhul** [comment]
Hey,
I also have the same problem.
Copilot stopped working since yesterday.

This is my Visual Studio info:

Microsoft Visual Studio Professional 2022
Version 17.10.1
VisualStudio.17.Release/17.10.1+34928.147
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

**Comment by macjohnmcc** [comment]
Okay after research I found out that it only supports community edition because it is now part of the Visual Studio installation. Not very intuitive when you already have visual studio installed. I think that either they should remove the extension from the extensions in the extension search results for VS 2022 Pro/Ent or they should at the very lease show "Now built into your version of Visual Studio. Please use the Visual Studio Installer to enable the feature." I like the integration in VSCode much better. I like to just write a comment and then for the copilot extension to suggest code based on my comment. I have not seen this happening in VS2022 Ent with the copilot option enabled.

**Comment by calinmorosan** [comment]
Same problem here, Github Copilot Chat fails to install with "This extension is not installable on any currently installed products.":

![Github Copilot Chat fails](https://github.com/microsoft/vscode-copilot-release/assets/170002810/101ddf7d-0dfb-4d41-af4f-8144749d1787)


6/17/2024 2:28:00 PM - Microsoft VSIX Installer
6/17/2024 2:28:00 PM - -------------------------------------------
6/17/2024 2:28:00 PM - vsixinstaller.exe version:
6/17/2024 2:28:00 PM - 17.10.2185+1efd885b2e
6/17/2024 2:28:00 PM - -------------------------------------------
6/17/2024 2:28:00 PM - Command line parameters:
6/17/2024 2:28:00 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.10.35004.147,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,C:\Users\calin.morosan\AppData\Local\Temp\VSIXkr3d31xx.vsix
6/17/2024 2:28:00 PM - -------------------------------------------
6/17/2024 2:28:00 PM - Microsoft VSIX Installer
6/17/2024 2:28:00 PM - -------------------------------------------
6/17/2024 2:28:01 PM - Initializing Install...
6/17/2024 2:28:02 PM - Extension Details...
6/17/2024 2:28:02 PM - 	Identifier         : VS.GitHub.Copilot
6/17/2024 2:28:02 PM - 	Name               : GitHub Copilot Chat
6/17/2024 2:28:02 PM - 	Author             : Microsoft
6/17/2024 2:28:02 PM - 	Version            : 0.2.755.36570
6/17/2024 2:28:02 PM - 	Description        : GitHub Copilot Chat brings fully integrated AI-powered Copilot chat experiences to Visual Studio. Requires a GitHub ID which has been admitted for access to the private preview.
6/17/2024 2:28:02 PM - 	Locale             : en-US
6/17/2024 2:28:02 PM - 	MoreInfoURL        : https://aka.ms/VisualStudio.GitHub.Copilot/moreinfo
6/17/2024 2:28:02 PM - 	InstalledByMSI     : False
6/17/2024 2:28:02 PM - 	SupportedFrameworkVersionRange : [4.5,)
6/17/2024 2:28:03 PM - 	SignatureState     : ValidSignature
6/17/2024 2:28:03 PM - 	SignedBy           : Microsoft Corporation
6/17/2024 2:28:03 PM - 	Certificate Info   : 
6/17/2024 2:28:03 PM - 		-------------------------------------------------------
6/17/2024 2:28:03 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/17/2024 2:28:03 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/17/2024 2:28:03 PM - 		[Serial Number] : 330000056067F73C897D62BABD000000000560
6/17/2024 2:28:03 PM - 		[Not Before]    : 1/11/2024 3:05:33 PM
6/17/2024 2:28:03 PM - 		[Not After]     : 1/10/2025 3:05:33 PM
6/17/2024 2:28:03 PM - 		[Thumbprint]    : 80AF76D324CE728D7DF51CDCA241F5E9598169B7
6/17/2024 2:28:03 PM - 	Supported Products : 
6/17/2024 2:28:03 PM - 		Microsoft.VisualStudio.Community
6/17/2024 2:28:03 PM - 			Version : [17.8,17.10.34712.116)
6/17/2024 2:28:03 PM - 			ProductArchitecture : amd64
6/17/2024 2:28:03 PM - 		Microsoft.VisualStudio.Community
6/17/2024 2:28:03 PM - 			Version : [17.8,17.10.34712.116)
6/17/2024 2:28:03 PM - 			ProductArchitecture : arm64
6/17/2024 2:28:03 PM - 	References         : 
6/17/2024 2:28:03 PM - 	Prerequisites      : 
6/17/2024 2:28:03 PM - 		-------------------------------------------------------
6/17/2024 2:28:03 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/17/2024 2:28:03 PM - 		Name         : Visual Studio core editor
6/17/2024 2:28:03 PM - 		Version      : [17.0,18.0)
6/17/2024 2:28:03 PM - 		-------------------------------------------------------
6/17/2024 2:28:03 PM - 		Identifier   : Microsoft.VisualStudio.Component.IntelliCode
6/17/2024 2:28:03 PM - 		Name         : Visual Studio IntelliCode
6/17/2024 2:28:03 PM - 		Version      : [17.0,18.0)
6/17/2024 2:28:03 PM - Signature Details...
6/17/2024 2:28:03 PM - 	Extension is signed with a valid signature.
6/17/2024 2:28:03 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by je573r** [comment]
> Same problem here, Github Copilot Chat fails to install with "This extension is not installable on any currently installed products.":
> 
> ![Github Copilot Chat fails](https://private-user-images.githubusercontent.com/170002810/340423833-101ddf7d-0dfb-4d41-af4f-8144749d1787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjUyMTMsIm5iZiI6MTcxODc2NDkxMywicGF0aCI6Ii8xNzAwMDI4MTAvMzQwNDIzODMzLTEwMWRkZjdkLTBkZmItNGQ0MS1hZjRmLTgxNDQ3NDlkMTc4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwMjQxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjNmYjNlZjI3MmI3NmQxZDQxNjM3ZjMxNTMxNzU5YjQ1MDRjZTc0YWFiNWExYmFlNmI2YTA2MzAzMDkyZDg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ND6MY6lW0ovVwbMhsuem2Bba-vuaH4UUL2Z6BXo3zG0)
> 
> 6/17/2024 2:28:00 PM - Microsoft VSIX Installer 6/17/2024 2:28:00 PM - ------------------------------------------- 6/17/2024 2:28:00 PM - vsixinstaller.exe version: 6/17/2024 2:28:00 PM - 17.10.2185+1efd885b2e 6/17/2024 2:28:00 PM - ------------------------------------------- 6/17/2024 2:28:00 PM - Command line parameters: 6/17/2024 2:28:00 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.10.35004.147,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,C:\Users\calin.morosan\AppData\Local\Temp\VSIXkr3d31xx.vsix 6/17/2024 2:28:00 PM - ------------------------------------------- 6/17/2024 2:28:00 PM - Microsoft VSIX Installer 6/17/2024 2:28:00 PM - ------------------------------------------- 6/17/2024 2:28:01 PM - Initializing Install... 6/17/2024 2:28:02 PM - Extension Details... 6/17/2024 2:28:02 PM - Identifier : VS.GitHub.Copilot 6/17/2024 2:28:02 PM - Name : GitHub Copilot Chat 6/17/2024 2:28:02 PM - Author : Microsoft 6/17/2024 2:28:02 PM - Version : 0.2.755.36570 6/17/2024 2:28:02 PM - Description : GitHub Copilot Chat brings fully integrated AI-powered Copilot chat experiences to Visual Studio. Requires a GitHub ID which has been admitted for access to the private preview. 6/17/2024 2:28:02 PM - Locale : en-US 6/17/2024 2:28:02 PM - MoreInfoURL : https://aka.ms/VisualStudio.GitHub.Copilot/moreinfo 6/17/2024 2:28:02 PM - InstalledByMSI : False 6/17/2024 2:28:02 PM - SupportedFrameworkVersionRange : [4.5,) 6/17/2024 2:28:03 PM - SignatureState : ValidSignature 6/17/2024 2:28:03 PM - SignedBy : Microsoft Corporation 6/17/2024 2:28:03 PM - Certificate Info : 6/17/2024 2:28:03 PM - ------------------------------------------------------- 6/17/2024 2:28:03 PM - [Subject] : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 6/17/2024 2:28:03 PM - [Issuer] : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US 6/17/2024 2:28:03 PM - [Serial Number] : 330000056067F73C897D62BABD000000000560 6/17/2024 2:28:03 PM - [Not Before] : 1/11/2024 3:05:33 PM 6/17/2024 2:28:03 PM - [Not After] : 1/10/2025 3:05:33 PM 6/17/2024 2:28:03 PM - [Thumbprint] : 80AF76D324CE728D7DF51CDCA241F5E9598169B7 6/17/2024 2:28:03 PM - Supported Products : 6/17/2024 2:28:03 PM - Microsoft.VisualStudio.Community 6/17/2024 2:28:03 PM - Version : [17.8,17.10.34712.116) 6/17/2024 2:28:03 PM - ProductArchitecture : amd64 6/17/2024 2:28:03 PM - Microsoft.VisualStudio.Community 6/17/2024 2:28:03 PM - Version : [17.8,17.10.34712.116) 6/17/2024 2:28:03 PM - ProductArchitecture : arm64 6/17/2024 2:28:03 PM - References : 6/17/2024 2:28:03 PM - Prerequisites : 6/17/2024 2:28:03 PM - ------------------------------------------------------- 6/17/2024 2:28:03 PM - Identifier : Microsoft.VisualStudio.Component.CoreEditor 6/17/2024 2:28:03 PM - Name : Visual Studio core editor 6/17/2024 2:28:03 PM - Version : [17.0,18.0) 6/17/2024 2:28:03 PM - ------------------------------------------------------- 6/17/2024 2:28:03 PM - Identifier : Microsoft.VisualStudio.Component.IntelliCode 6/17/2024 2:28:03 PM - Name : Visual Studio IntelliCode 6/17/2024 2:28:03 PM - Version : [17.0,18.0) 6/17/2024 2:28:03 PM - Signature Details... 6/17/2024 2:28:03 PM - Extension is signed with a valid signature. 6/17/2024 2:28:03 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products. at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) at VSIXInstaller.ExtensionService.ComputeInstallableExtensions(IStateData stateData, Boolean isRepairSupported, Boolean isExtensionPack, IDictionary`2 skuDataMapping, IList`1 installableExtensionsPaths) at VSIXInstaller.App.Initialize(Boolean isRepairSupported) at VSIXInstaller.App.Initialize() at System.Threading.Tasks.Task`1.InnerInvoke() at System.Threading.Tasks.Task.Execute()

hey, how did you resolve this because i am getting the exact same thing

**Comment by JeffreyHsu26** [comment]
I got the same issue, I can see the Copilot Chat window, but not able to use it, here is the log:

6/19/2024 5:34:37 PM - Microsoft VSIX Installer
6/19/2024 5:34:37 PM - -------------------------------------------
6/19/2024 5:34:37 PM - vsixinstaller.exe version:
6/19/2024 5:34:37 PM - 17.10.2186+0bf64ad641
6/19/2024 5:34:37 PM - -------------------------------------------
6/19/2024 5:34:37 PM - Command line parameters:
6/19/2024 5:34:37 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\tw1733\Downloads\VisualStudio.GitHub.Copilot.vsix
6/19/2024 5:34:37 PM - -------------------------------------------
6/19/2024 5:34:37 PM - Microsoft VSIX Installer
6/19/2024 5:34:37 PM - -------------------------------------------
6/19/2024 5:35:00 PM - Initializing Install...
6/19/2024 5:35:00 PM - Searching for applicable products...
6/19/2024 5:35:00 PM - Found installed product - Visual Studio Enterprise 2022
6/19/2024 5:35:00 PM - Found installed product - Visual Studio Enterprise 2019
6/19/2024 5:35:01 PM - Found installed product - ssms
6/19/2024 5:35:01 PM - Found installed product - Global Location
6/19/2024 5:35:01 PM - Extension Details...
6/19/2024 5:35:01 PM - 	Identifier         : VS.GitHub.Copilot
6/19/2024 5:35:01 PM - 	Name               : GitHub Copilot Chat
6/19/2024 5:35:01 PM - 	Author             : Microsoft
6/19/2024 5:35:01 PM - 	Version            : 0.2.755.36570
6/19/2024 5:35:01 PM - 	Description        : GitHub Copilot Chat brings fully integrated AI-powered Copilot chat experiences to Visual Studio. Requires a GitHub ID which has been admitted for access to the private preview.
6/19/2024 5:35:01 PM - 	Locale             : en-US
6/19/2024 5:35:01 PM - 	MoreInfoURL        : https://aka.ms/VisualStudio.GitHub.Copilot/moreinfo
6/19/2024 5:35:01 PM - 	InstalledByMSI     : False
6/19/2024 5:35:01 PM - 	SupportedFrameworkVersionRange : [4.5,)
6/19/2024 5:35:02 PM - 	SignatureState     : ValidSignature
6/19/2024 5:35:02 PM - 	SignedBy           : Microsoft Corporation
6/19/2024 5:35:02 PM - 	Certificate Info   : 
6/19/2024 5:35:02 PM - 		-------------------------------------------------------
6/19/2024 5:35:02 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/19/2024 5:35:02 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
6/19/2024 5:35:02 PM - 		[Serial Number] : 330000056067F73C897D62BABD000000000560
6/19/2024 5:35:02 PM - 		[Not Before]    : 1/12/2024 4:05:33 AM
6/19/2024 5:35:02 PM - 		[Not After]     : 1/11/2025 4:05:33 AM
6/19/2024 5:35:02 PM - 		[Thumbprint]    : 80AF76D324CE728D7DF51CDCA241F5E9598169B7
6/19/2024 5:35:02 PM - 	Supported Products : 
6/19/2024 5:35:02 PM - 		Microsoft.VisualStudio.Community
6/19/2024 5:35:02 PM - 			Version : [17.8,17.10.34712.116)
6/19/2024 5:35:02 PM - 			ProductArchitecture : amd64
6/19/2024 5:35:02 PM - 		Microsoft.VisualStudio.Community
6/19/2024 5:35:02 PM - 			Version : [17.8,17.10.34712.116)
6/19/2024 5:35:02 PM - 			ProductArchitecture : arm64
6/19/2024 5:35:02 PM - 	References         : 
6/19/2024 5:35:02 PM - 	Prerequisites      : 
6/19/2024 5:35:02 PM - 		-------------------------------------------------------
6/19/2024 5:35:02 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/19/2024 5:35:02 PM - 		Name         : Visual Studio core editor
6/19/2024 5:35:02 PM - 		Version      : [17.0,18.0)
6/19/2024 5:35:02 PM - 		-------------------------------------------------------
6/19/2024 5:35:02 PM - 		Identifier   : Microsoft.VisualStudio.Component.IntelliCode
6/19/2024 5:35:02 PM - 		Name         : Visual Studio IntelliCode
6/19/2024 5:35:02 PM - 		Version      : [17.0,18.0)
6/19/2024 5:35:02 PM - Signature Details...
6/19/2024 5:35:02 PM - 	Extension is signed with a valid signature.
6/19/2024 5:35:02 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
