### ISSUE TITLE
Generate commit message

### ISSUE THREAD

**Issue by askpt** [microsoft/vscode-copilot-release#359]
As part of the GH Copilot chat, it would be interesting to have the option to generate commit messages.

The idea behind this is to take the commit diff into consideration and give a small explanation of what happened. The inverse of the `Fix this` prompt.

**Comment by lszomoru** [comment]
Support for generating commit messages is included in the October 2023 release.

**Comment by MattJeanes** [comment]
It would be great to also have an option or customizable pre-prompt we can have to allow a certain style of commit message e.g. conventional commits

**Comment by digitarald** [comment]
@MattJeanes love the idea, showing it prior message styles could also help here. Could you please file a follow-up issue, as this one is closed?

**Comment by MattJeanes** [comment]
Raised! https://github.com/microsoft/vscode-copilot-release/issues/526

**Comment by jorupp** [comment]
> Support for generating commit messages is included in the October 2023 release.

Is there a way to disable this button?  Adding a new button in the tab order between the box where you type the commit message and the "commit" button is messing with my workflow :(  I'm too used to hitting typing something in the box, hitting tab, and enter and having it commit, not overwrite the message I just spent time writing with a generated message.

And/or have it prompt before overwriting the user-written content there?

**Comment by kpostekk** [comment]
Is there any option to disable this button? I'm used to hitting tab enter after typing my commit message. Also replacing user's message without option to undo this promt is straight annoying.

**Comment by lszomoru** [comment]
Sorry for not chiming in on the issue earlier:
1. The latest VS Code Insides release contains a new setting to globally disable the source control input box action button independent of the extensions that contribute the action - `scm.showInputActionButton`. The setting will be available in VS Code Stable towards the end of next week.
2. In the latest VS Insiders, generated commit messages are also being pushed to the undo stack. If you hit the generate commit message by mistake, and your commit message is overwritten, you can invoke the "Undo" command to get back the message that was overwritten. This will also be available in VS Code Stable next week.
3. As far as committing using keyboard shortcuts, you can also use Cmd+ENTER, Ctrl+ENTER

**Comment by julien-blanchon** [comment]
> Yes, we are looking at including previous commit messages from the author/repository into the prompt context to have Copilot generate commit messages that match the style of the existing commit messages. We are also looking at exposing the git diff information so that users can write their custom prompt which would generate a commit message.

@lszomoru Any update on this ?

**Comment by lszomoru** [comment]
@julien-blanchon, 
* yes previous commit messages are now included in the prompt context. 
* the capability to write custom prompts to generate the commit message is not available
