### ISSUE TITLE
Sabotage. Repeated Observations of Sabotage.

### ISSUE THREAD

**Issue by dmattox10** [microsoft/vscode-copilot-release#3594]
Type: <b>Bug</b>

Can you check out my private TattleTea repo? Work with copilot chat on it for 20 minutes, and at some point, I promise, it will completely mess up utils/crypto.js

It will take working code, and break it, which breaks the whole app. All I have to do to fix it every time I catch it, is copy the old one in again, like I just did on commit 7b7cd129a23f401f2ad2cf615286b6c6acc30ae6

the one before it is 9fad0822dee129570c7cbc39e3d1c885d29f10e1
which has a broken example of it needlessly overwriting my file in the background while working on other issues compare it to the one above.

Extension version: 0.23.2
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|36.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id dd107edc-30df-4997-abec-8bb941cac314|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc1:31192215
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by Nyacuma** [comment]
It indeed is true! I have wasted two months working with Copilot. Yesterday my code was complete and i expressed gratitude to that demon. One ESP32 worked and from then on NOTHING worked. I had this uncanny feeling Copilot is sabotaging my work deliberately. Today I decided to uninstall it from vscode. Then an idea crossed my mind. to check if someone elses has been messed. I ended up here!

**Comment by dmattox10** [comment]
There has to be a way to prove it. I’m hoping it’s incidental, that it’s a
way of trying to remain relevant and helpful by stretching out the time,
but either way I’m 100% certain that copilot breaks projects intentionally.

**Comment by dmattox10** [comment]
I added comments to my code with instructions to keep it from flattening
orbital mechanics to straight lines, and it’s solution was to first delete
the comment, THEN delete my Hoffman transfers AGAIN in favor of x2-x1/y2-y1
BS. At one point in the last week it deleted over 600 lines of code in one
apply to “simplify things” broke it all.
