### ISSUE TITLE
Can't access shared PDF

### ISSUE THREAD

**Issue by NorbNorb** [microsoft/vscode-copilot-release#3599]
Type: <b>Bug</b>

I've attached a PDF which is a modbus documentation for a device. Despite being part of my VS Code project and shared in the "Working Set" window, Copilot can't see and use that file. I've tried it twice without luck.
I would have expected Copilot to be able to read from that PDF.

Extension version: 0.23.2
VS Code version: Code 1.96.2 (Universal) (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupyter:31046869
nativerepl1:31139838
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode-copilot-release/issues/3179
