### ISSUE TITLE
Store chat or add undo

### ISSUE THREAD

**Issue by gamousquesORT** [microsoft/vscode-copilot-release#36]
version 1.79.0
OS: Windows_NT x64 10.919043
Copilot chat v0.1.2023051801

This is a usability request. It happened to me twice that I clicked the upper right Clear chat button (looks like a hamburger menu) and I lost all the context I had been constructing for a while. It could be nice to have a feature that saves the dialog to a file or an undo command associated. Maybe there is something similar but haven't found it.

Thank you

**Comment by AntoineWVN** [comment]
Hi @gamousquesORT it is already possible to save the current conversation to a json file with the export/import features.
You can access these features via the command panel (ctrl/cmd + p, followed by '>chat export' or '>chat import').
You can also assign these commands to any shortcut.

**Comment by gamousquesORT** [comment]
@AntoineWVN Thank you very much for the tip, it is very useful. I was thinking about this feature to keep the chain of thought with the bot.

**Comment by digitarald** [comment]
History is now enabled by default. But please let me know if there is another issue.
