### ISSUE TITLE
Visual Studio 2022 (NOT VS CODE) - Inline Copilot completion is "broke"

### ISSUE THREAD

**Issue by robvet** [microsoft/vscode-copilot-release#360]
- Visual Studio 2022 v. 4.8.09032 and v. 17.8.0 Preview 1 (NOT VS CODE)
 OS Version: Windows 11
- GH Copilot v. 1.1000.0.0 (@6ffo82509
- GH Copilot Chat v. 01.1227.30434

Inline prompt returns completion inside the prompt text-area element (see image 1 below).

![completion-returned-in-prompt](https://github.com/microsoft/vscode-copilot-release/assets/4884576/3512d693-19fc-4522-9d2d-6f93ca076095)

- The response no longer presents an "expanded view" of the completion in which it contrasts the current state with the suggestion, while providing user ability to Accept, Discard, or Regenerate, as it did in preceding Visual Studio version and in VS Code (image 2 below).

![completion-as-should-be](https://github.com/microsoft/vscode-copilot-release/assets/4884576/db29c889-3478-4ac2-bcc1-d9fc66d59bfe)

Additionally, look at the length of **prompt textbox size and font-size** from image 1 above. Very narrow and font is very small. Contrast with that with image 2 above. For some users, the smaller/narrower presentation may cause usability concerns.

**Enterprise customers (with whom we present GH Copilot multiple times per week) have negatively questioned and commented on this usability loss. To keep excitement/adoption elevated, suggest you consider prioritizing and fixing. You already have the code from the preceding release and VS Code**.

Not sure this is helpful, but here is log output from the Output screen:

[CopilotSessionProvider Information] Request content: "how do I add button to insert default value in systemprompt"
[Conversations Information] [CopilotClient] Restricted telemetry is sent. Is user opted in: True. Is user microsoft internal: True

Reach out to for more detail if needed.

**Comment by roblourens** [comment]
This repo is just for vscode it looks like https://github.com/orgs/community/discussions is the right place for VS copilot feedback
