### ISSUE TITLE
Visual Studio 2022 (NOT VS CODE) - Chat completion Displays Result in Light Gray Background with white font

### ISSUE THREAD

**Issue by robvet** [microsoft/vscode-copilot-release#361]
Visual Studio 2022 v. 4.8.09032 and v. 17.8.0 Preview 1 (NOT VS CODE)
OS Version: Windows 11
GH Copilot v. 1.1000.0.0 (@6ffo82509
GH Copilot Chat v. 01.1227.30434

Chat completion occasionally returns suggestion in light gray background with white text. Look at following image. 

![completion-light-gray](https://github.com/microsoft/vscode-copilot-release/assets/4884576/78491d04-7e47-4d2f-a434-8b45a8cfef75)

**Comment by robvet** [comment]
Just in time, here's another example of light gray background. This time, just happened in the prompt textbox.

![completion-light-gray-prompt-textarea](https://github.com/microsoft/vscode-copilot-release/assets/4884576/558f0142-b230-4c91-a483-a3be961eeea9)

**Comment by jrieken** [comment]
wrong repo, this is about vscode
