### ISSUE TITLE
Visual Studio 2022 (NOT VS CODE) -- Inline comment-invoked prompt doesn't work

### ISSUE THREAD

**Issue by robvet** [microsoft/vscode-copilot-release#362]
Visual Studio 2022 v. 4.8.09032 and v. 17.8.0 Preview 1 (NOT VS CODE)
OS Version: Windows 11
GH Copilot v. 1.1000.0.0 (@6ffo82509
GH Copilot Chat v. 01.1227.30434

In current version of Visual Studio 2022 (v. 4.8.09032), inline comments do nothing (image 1):

![no-completion-with-comment](https://github.com/microsoft/vscode-copilot-release/assets/4884576/e7049ce3-ccb1-4232-af45-bfecda5e1cc6)

However, in the prerelease version of Visual Studio 2022 (17.8.0 Preview 1), inline comments generate code as expected (image 2):

![completion-with-comment](https://github.com/microsoft/vscode-copilot-release/assets/4884576/22ac1310-c6af-439b-916a-65f8be58aee0)

Note in scenario 1, where inline comments do nothing, no telemetry/logging generated in GitHub Copliot Chat output window.

**Comment by roblourens** [comment]
This repo is just for vscode it looks like https://github.com/orgs/community/discussions is the right place for VS copilot feedback
