### ISSUE TITLE
Invalid file pattern provided [object Object]

### ISSUE THREAD

**Issue by UltraInstinct0x** [microsoft/vscode-copilot-release#3661]
Type: <b>Bug</b>

its a known issue and its been like this FOR WEEKS. I am already using latest version of vscode and im on release version of the extension. I MEAN... ITS REALLY HARD TO STAY SANE IN THIS WORLD WHEN COMPANIES WITH. YOU know what, nevermind.
I just wanted you all to see this stream of consciousness.

Extension version: 0.23.2024102903
VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Darwin arm64 24.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id d38a23b6-3946-4b9b-93e6-a339b312fc57|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
dvdeprecation:31068756
dwnewjupytercf:31046870
nativerepl2:31139839
pythonrstrctxt:31112756
nativeloc2:31192216
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530
6074i472:31201624

```

</details>

**Comment by UltraInstinct0x** [comment]
for anyone wondering, just make a COMPLETE reinstall for the extension (and vscode if below steps won't solve it). 
Switching versions didn't work for me.

What I did was:
- Disabled the extension 
- Restarted code 
- didn't work so uninstalled the extension
- Restarted code an installed & restarted again
- still no luck?
- uninstall extension & code
- reinstall code and extension back

problem solved.

**Comment by sbatten** [comment]
@UltraInstinct0x At the time of filing this issue, I noticed that you had the "pre-release" version of the extension installed with the "Stable" version of VS Code. Due to the versioning scheme, this actually keeps you from getting the latest updates on the extension. Please consider using the "release" version of the extension with "Stable" VS Code, or consider using the "Insiders" version of VS Code.
