### ISSUE TITLE
Copilot has a problem with large files

### ISSUE THREAD

**Issue by ksampolski** [microsoft/vscode-copilot-release#368]
I have a problem with helping with a large file, I am working on legacy code where the file is 12k lines and one method is 2k lines. I tried to read if there is a character limit but did not find one. When I ask Copilot to simplify the selected code then I get not the correct code, looks like Copilot reads only the last 70 lines, it comes out that always the end of the marked code is taken into account. And by the way, the non-insider version does not understand the simplify code command.

- VS Code Version: 1.82.0-insider (Universal)
- OS Version: MacOS 13.4.1 (22F82)
- Logs: - 

Steps to Reproduce:

1. Open a big Python file
2. Select one big method using the cursor
3. Right-click -> Copilot -> start chat
4. Write refactor or simplify the code
5. Copilot generates new code based only on the last selected lines (approx 70 lines in my case)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/173
