### ISSUE TITLE
Conflicting bindings for Inline Chat and Quick Chat

### ISSUE THREAD

**Issue by jbriales** [microsoft/vscode-copilot-release#369]
- VS Code Version: 1.81.1
- OS Version: Fedora 36
- Logs:

# Steps to Reproduce:

Add to keybindings.json:
```
    {
        "key": "alt+i",
        "command": "inlineChat.start",
        "when": "inlineChatHasProvider && !editorReadonly && !inlineChatVisible"
    },
    {
        "key": "alt+i",
        "command": "chat.action.askQuickQuestion",
        "when": "hasChatProvider && editorFocus && inlineChatVisible"
    },
```

# Expected
On first `A-i` in the editor, an Inline-Chat pops up.
On a second `A-i` right after, a Quick-Chat pops up instead.

# Actual
The Inline-Chat pops up but subsequent A-i have no effect.

**Comment by ackvf** [comment]
Maybe you don't have `editorFocus` when in an inlineChat.

When you open inlineChat, you need to pass the conditions, it

**Comment by ackvf** [comment]
Maybe you don't have `editorFocus` when in an inlineChat, so the "when" does not match.

When you open inlineChat, you can assume that the conditions are met, so you can safely construct the second command with just:
```
    {
        "key": "alt+i",
        "command": "chat.action.askQuickQuestion",
        "when": "inlineChatVisible"
    },
```

I believe that that should do the trick.

**Comment by jbriales** [comment]
Ah, actually that was the issue. Funny enough, I took the `editorFocus && inlineChatVisible` from a Copilot suggestion :)
But yeah, it seems both are mutually exclusive so an `&&` on both is non-sense.

This worked for the purpose I wanted:
```
    {
        "key": "alt+i",
        "command": "chat.action.askQuickQuestion",
        "when": "inlineChatVisible"
    },
```

**Comment by jbriales** [comment]
Or actually even more like this for the behavior I was after:
```json
    {
        "key": "alt+i",
        "command": "runCommands",
        "args": {
            "commands": [
                "inlineChat.cancel",
                "chat.action.askQuickQuestion"
            ]
        },
        "when": "inlineChatVisible"
    },
```
