### ISSUE TITLE
High latency for Chat responses, stuck in "Thinking…"

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-copilot-release#37]
Copilot Cat had a performance regression. We are working on an issue that fixes long delays for responses being stuck in "Thinking …".

**Comment by astroctrl** [comment]
Same problem here but after switching internet connections the issue solved for me, probably a network issue

**Comment by digitarald** [comment]
Fix was released yesterday. Please file a new issue if you see latency issues.

**Comment by silvestreh** [comment]
I'm still having this issue, though not idea if it's related to a network issue. It certainly gets stuck at `Thinking…` and it never comes up with a response
