### ISSUE TITLE
Stuck on Activating

### ISSUE THREAD

**Issue by hyperabstractor** [microsoft/vscode-copilot-release#371]
Type: <b>Bug</b>

I dont know how to reproduce it.. But Copilot and Copilot chat both are not working and stuck on Activating....

Extension version: 0.7.2023081101
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (41.23GB free)|
|Process Argv|--crash-reporter-id 677deeac-4b89-4333-9a36-2ddb8c024e27|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by ahmedivy** [comment]
Same

**Comment by roblourens** [comment]
What exactly do you see? Can you share the log from the Copilot output channel?

**Comment by ahmedivy** [comment]
In my case it stucks when press enter after writing prompt and response never came?

Its not the case every time but most of the time.

**Comment by ahmedivy** [comment]
In my case it stucks when press enter after writing prompt and response never came?

Its not the case every time but most of the time.

**Comment by roblourens** [comment]
Can you share the log from the Copilot Chat output channel and maybe a screenshot?

**Comment by ahmedivy** [comment]
Currently its working, I will share logs when it stucks

**Comment by joyceerhl** [comment]
Please reopen if you can provide the requested info @hyperabstractor
