### ISSUE TITLE
Using the "/fix" shortcut is duplicating code in a Python project

### ISSUE THREAD

**Issue by KalleV** [microsoft/vscode-copilot-release#373]
- VS Code Version: 1.82.0-insider 
- OS Version: Darwin x64 22.5.0
- Logs: N/A

Kudos for tools like Copilot making moving between frameworks, programming languages, and projects significantly easier! I encountered this one while trying to customize a Streamlit project.

Steps to Reproduce:

1. Select a code block and activate an in-line chat prompt. Example:
![Screenshot 2023-08-20 at 10 28 31 AM](https://github.com/microsoft/vscode-copilot-release/assets/5942028/4fab076e-d340-443b-ba3a-080925763c4c)

2. Ask it to change the code block using "/fix". Example:
```
/fix Change the Podcast Guest Details to show a results list with clickable links.
```

3. Duplicated code is generated. Example:
![Screenshot 2023-08-20 at 10 37 20 AM](https://github.com/microsoft/vscode-copilot-release/assets/5942028/ef789ae8-97b4-4d69-a90c-80eb0601b59d)

4. The duplicated code is not generated after removing the "/fix" shortcut and applying the exact same instructions. Example:
![Screenshot 2023-08-20 at 10 35 54 AM](https://github.com/microsoft/vscode-copilot-release/assets/5942028/d834c8d9-2f17-4d56-b087-e445ee028ef0)

**Comment by aiday-mar** [comment]
Hi thank you for filing the issue. A fix went in yesterday for this issue: https://github.com/microsoft/vscode-copilot/pull/1163. Let me know after the release is out if you continue seeing this issue.

**Comment by KalleV** [comment]
Nice! I tried to replicate it and couldn't with Copilot Chat v0.7.2023082404
