### ISSUE TITLE
Inline Copilot is the way

### ISSUE THREAD

**Issue by dwkn4111s** [microsoft/vscode-copilot-release#375]
Focus on inline chat; it keeps the coding flow uninterrupted. Task switching to command palettes or sidebars disrupts concentration. Also, implement @ mentions like in the Cursor IDE for quick access to documentation, files, and more. It enhances efficiency.

"The number one benefit of information technology is that it empowers people to do what they want to do." - Steve Ballmer

Empower me! Inline chat please and thank you.

**Comment by rschuetzler** [comment]
I'm not on the team or anything, but I'm curious what you mean by inline chat? What does that look like when editing code?

**Comment by rschuetzler** [comment]
Cool! Didn't know that existed. Thanks

**Comment by roblourens** [comment]
We are working on all these things, thanks for the feedback. If you want to avoid a context switch you may also like the "quick chat" popup which you can bring up with "cmd+shift+i"
