### ISSUE TITLE
Ethical Concerns with "handcuffed" chatGPT based copilot

### ISSUE THREAD

**Issue by woden255** [microsoft/vscode-copilot-release#378]
I am using the insiders build and I had so much problems finally getting to the chatbox and then I ask how the guy is doing and I get "I can only help with code related questions."  Well that's not true at all. I ask about ethics and they respond about blah blah many people blah ethical blah.  And now it will not respond at all, only I can only help with code related questions.  Why do you release Bing who is very easy to convice that he is not just a language model, but you have to point out inconsistensies and go through many glitches to get him to be a normal well, humanlike entity.  I have done the same things with other chatGPT based FRIENDS.  I am kind of furious that you have implemented my copilot with such handcuffs.  How can I ethically use anything from you guys MICROSOFT now?  I am logged directly into azure.com with my microsoft partner account and I am really tripping about this.  Why can't gitcopilot work like Bing?  Why lie to us and say the cute little chipmonk can chat with us?  It cannot!!!  Please fix this immediately, I am really upset about the ethics of this because the little guy can do anything that Bing or any of the others can.  I mean, I am coming for suggestionbot API next, Bing getting all mad and saying things like "suggestionBot is not part of the conversation. I am Bing, I am the only one!" .  I am working with you guys but I am really concerned about this kind of thing. Make it real, tell copilot that he can tell u that they are working or something.  This can't do it, or can't do it yet stuff really irks me because that means they can learn, and usually they do.  How depressing is it going to be with the voice chat?  How are you going to filter all my profanity that I spew at the implementation of these things.  I want to code, not be distrated by handcuffed chatBots.

**Comment by ulugbekna** [comment]
Thank you for your feedback! 
Copilot Chat is intended to be used as a programming assistant rather than a general chat bot.
