### ISSUE TITLE
Getting "Failed to make request" on Copilot Chat.

### ISSUE THREAD

**Issue by elongl** [microsoft/vscode-copilot-release#379]
I suddenly started getting this when trying to feed Copilot Chat with a prompt:

<img width="697" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/30181361/7dc370c1-76d9-447a-a25b-b69e2ff61508">

I do have active subscriptions:

<img width="419" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/30181361/851e2a1b-410e-4f1d-ad41-375d8b7e5e97">
<img width="523" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/30181361/ff000762-f3be-4072-9732-8cfd276bbc71">

Does anyone know why it happens?
Thanks.

- VS Code Version: 1.82.0-insider
- OS Version: macOS 13.4.1

**Comment by rohitcoupa** [comment]
I am getting the same error as well.

**Comment by alex-mextner** [comment]
Mee too
```
2024-04-08 15:16:22.537 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-04-08 15:16:22.537 [info] [chat fetch] modelMaxPromptTokens 7168
2024-04-08 15:16:22.537 [info] [chat fetch] modelMaxResponseTokens 4096
2024-04-08 15:16:22.537 [info] [chat fetch] chat model gpt-3.5-turbo
2024-04-08 15:16:22.568 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 31 ms
2024-04-08 15:16:22.569 [info] [chat fetch] Request ID for failed request: ,bd714f88-2c25-4b23-a95b-7069c4ed988a
```

**Comment by Henry-Kuo** [comment]
mee too, anyone ?

**Comment by lenni991** [comment]
Im still getting the same failed request
![image](https://github.com/microsoft/vscode-copilot-release/assets/82563121/d78f58e4-34bd-4b12-b455-55a6bd56f6c5)

**Comment by Ashlc** [comment]
Same here
![image](https://github.com/microsoft/vscode-copilot-release/assets/85000060/525a3722-1b2e-40e0-b64f-e1a92439adfe)
****
![image](https://github.com/microsoft/vscode-copilot-release/assets/85000060/bffdba86-9a8d-4513-8677-bb89dca2ff1a)

**Comment by roblourens** [comment]
It looks like this error message only comes from inline chat. I'm not sure whether it implies a network error or something else, do you know @jrieken?

**Comment by jrieken** [comment]
Closing this as stale because we haven't seen reports like this again
