### ISSUE TITLE
GitHub Copilot Chat icon not visible in VS Code Insiders

### ISSUE THREAD

**Issue by kishsal** [microsoft/vscode-copilot-release#387]
- VS Code Version:
> - Version: 1.82.0-insider (Universal)
> - Commit: f125afbc800ec611f5a9ab1333c769832ce424b3
> - Date: 2023-08-21T05:34:49.942Z (2 wks ago)
> - Electron: 25.5.0
> - ElectronBuildId: 23084831
> - Chromium: 114.0.5735.289
> - Node.js: 18.15.0
> - V8: 11.4.183.29-electron.0
> - OS: Darwin x64 22.6.0

- OS Version: Mac OSX 13.5.1
- Logs: N/A

Steps to Reproduce:

1. Authenticated to Github copilot and able to use extension
2. Installed both pre-release and release version of Github Copilot Chat but the chat icon is not displayed on the left side

<img width="1628" alt="Screenshot 2023-09-05 at 10 27 22 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/18578295/e17b6ded-02a7-47a1-88c3-b59b44a14933">

**Comment by wangduoyuuu** [comment]
Same issue here.

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 20.5.0

**Comment by wweevv-johndpope** [comment]
https://github.com/orgs/community/discussions/68463

**Comment by digitarald** [comment]
Please re-open if https://github.com/microsoft/vscode-copilot-release/issues/436 didn't help.
