### ISSUE TITLE
Settings only remembered for a few queries

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode-copilot-release#390]
I'm using Copilot to generate `jsdoc`, it works great, except it shows full function body as an answer, which is unnecessary.
So I query: `from now on, when generating jsdoc don't show full code, just a header` it responds with `Sure, I'll keep that in mind.`
And indeed, it generates `jsdoc` with function body omitted.
However, after few more queries, it starts showing full function body again.
```
Version: 1.82.0
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:07:07.438Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by alexdima** [comment]
@vanowm How are you triggering the jsdoc generation? Are you using the context menu entry, the code action or are you using the sidebar panel?

**Comment by vanowm** [comment]
I use the side panel. Now I'm curious, why would it matter?

**Comment by alexdima** [comment]
@vanowm We have fine-tuned the jsdoc generation when invoked via the UI e.g. 


https://github.com/microsoft/vscode-copilot-release/assets/5047891/77282a18-f83a-4fb0-bf00-b65612f198da

**Comment by vanowm** [comment]
It still shows the whole function...but why? In fact in my experience, with a large function its not only annoying, but also creates a problem, when the comment is long and you can't scroll horizontally, because the scroll bar is on the bottom of the suggested changes outside of view area. So you have to scroll down to find the horizontal scroll bar, blindly scroll it, then scroll up in hope you didn't scroll too far.
I've tried telling the copilot to auto wrap text into 100 characters, but it doesn't understand, it shortens the text itself instead. Regardless, even if it did, it wouldn't last long anyway, hence is this issue.

**Comment by ulugbekna** [comment]
This should be fixed.
