### ISSUE TITLE
Add a setting that copilot starts collapsed

### ISSUE THREAD

**Issue by alexander-kastil** [microsoft/vscode-copilot-release#393]
Recently you deployed an update in which copilot chat takes 50% of the VS Code Terminal. Although it can be collapsed, it has to be done manually every time one opens a new instance of VS Code. Please add a setting, so it starts in a collapsed way. Copilot Chat is cool, but I use it maybe only 1–2 times a day, and I need my terminal space for my work to be done.

![image](https://github.com/microsoft/vscode-copilot-release/assets/16348023/10a65b95-b1f5-4d08-a294-a649c904b961)

**Comment by roblourens** [comment]
It might be easier for you to leave it in its own tab in the panel or activity bar, instead of putting in the terminal's tab.

@sbatten is it possible to configure this?
