### ISSUE TITLE
Store chat sessions history, export a chat session

### ISSUE THREAD

**Issue by juri-sinitson** [microsoft/vscode-copilot-release#394]
After I close e.g. VSCode or switch off my PC I want to have session history. 
I want also to be able to export the chat history to html, pdf or just text.

Typical use case: 
I've generated a table with a UI-Library using the chat. Later I want to go back to this chat session and continue using it. E.g. request the chat for modifications of the code already generated in it. Sometimes I want to reuse the parts of the chat in another AI-System or append them as documentation e.g. to the ticket e.g. for a hand off.

**Comment by tgrall** [comment]
Have you tried the Command Panel > `Chat : Export Session` ?

It allows you to export the Chat session that you have opened as json file. 

![Screenshot 2023-09-26 at 14 18 07](https://github.com/microsoft/vscode-copilot-release/assets/541250/9a1c38ff-db69-46bd-800a-5b56355949c0)

**Comment by lifeinchords** [comment]
expanding on this idea, 2 valuable use cases

- as an author, coming back to a proj x months later and having how-did-i-figure-this-out documentation. Having to import/export manually on every commit or session is cumbersome and prone to forgetting, and copypasta is prone to errors

- as a collaborator reviewing PR's, being able to see what assumptions guided the solution, having discussions on challenges, alternative paths not taken, etc 

so, it would be nice that any assistant use automatically remembers. Brainstorming, maybe like 
```

.chat
├── 2023-10-01/
│   ├── 94ignaf__how-do-i-set-up-vite.md
│   ├── 1a2b3c__fixing-webpack-issues.md
│   └── 7g8h9i__optimizing-react-app.md
├── 2023-10-02/
│   ├── 8k9l0m__using-async-await.md
│   ├── 2d3e4f__migrating-to-typescript.md
│   └── 5t6u7v__implementing-redux.md
├── 2023-10-03/
│   ├── 9o0p1q__debugging-node-app.md
│   ├── 3r4s5t__unit-testing-with-jest.md
│   └── 6v7w8x__working-with-graphql.md
└── 2023-10-04/
    ├── 0y1z2a__integrating-d3.md
    ├── 4b5c6d__building-rest-api.md
    └── 8e9f0g__managing-state-with-mobx.md

```
uid's guarantee uniq, but also human readable titles. This makes it easy to scan by topic, whether in a code editor or a cloud repo UI.

Ideally a standard emerges, so as chat becomes ubiquitous, diff layers of the dev process stack respect/expect/can use this metadata if the dir exists, in the same way a `.git` folder is universally understood:
- editors (VS Code, natively with OpenAI GPT API) 
- editor extensions ([Continue](https://github.com/continuedev/continue) wrapping [Ollama](https://ollama.ai/) locally on open models, Code Llama ) 
- agent/assistant apps ([OpenInterpreter](https://openinterpreter.com/)) and soon to come on the OS-level

**Comment by roblourens** [comment]
You can now export a session as @tgrall pointed out, and you can also click the history button to use the persisted chat history that way.
