### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by suhrob008** [microsoft/vscode-copilot-release#396]
- Issue Type: `Performance`
- Extension Name: `copilot-chat`
- Extension Version: `0.7.2023081101`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/user/AppData/Local/Temp/GitHub.copilot-chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jrieken** [comment]
@suhrob008 Please attach the mentioned file (`C:/Users/user/AppData/Local/Temp/GitHub.copilot-chat-unresponsive.cpuprofile.txt`). Otherwise we cannot help you
