### ISSUE TITLE
Multiple chat panes.

### ISSUE THREAD

**Issue by thorbeck** [microsoft/vscode-copilot-release#397]
I find myself copypasting a lot to refine the answers I get, and I would like to avoid that.
I would like to have multiple panes with different contexts.
That way I could create a "react chat pane", "css/html chat pane" etc.

For each pane, I would like to change the avatar, the copilot name and set a suffix that is always added to each prompt.
The context would persist when I clear the pane dialog, but with an option to only add the suffix on the first prompt.

**Comment by roblourens** [comment]
One thing you can do is run "Chat: Open Editor" and have multiple chat editors with independent sessions. But we don't have any way to customize the prompt with a suffix like that.

**Comment by thorbeck** [comment]
I just found out chatGPT has relative new feature that is related to this.
It's called Custom instructions and available on all plans.
https://help.openai.com/en/articles/8096356-custom-instructions-for-chatgpt
It works quite well, though it would be even better to have multiple instructions depending on what I want to do.
E.g. one custom instructions for development related tasks, and another for personal things.
And with copilot this would translate into different instructions for CSS, JS, React, etc.
