### ISSUE TITLE
Not able to install latest pre-release versions (0.8.+)

### ISSUE THREAD

**Issue by cnaples79** [microsoft/vscode-copilot-release#398]
- VS Code Version: 1.82.1
- OS Version: Windows
- Logs: N/A

Steps to Reproduce:

1. Go to Extensions
2. Latest version (0.8+) is not available. Fails to install via .vsix.

Hello. I'm on VS Code 1.82.1 and using Copilot Chat 0.7.2023090101. I know 0.8+ is now released, but my extensions is not attempting to update. When I try to install manually via .vsix, it says my version of VS Code is not supported.

Are these newest versions of Chat only available on Insiders?
Also, out of curiosity, is the stable 0.7.0 ahead feature-wise compared to pre-release version 0.7.20230901 (since it was released later)?

**Comment by roblourens** [comment]
The latest pre-release versions will require vscode Insiders. I recommend using stable Copilot Chat in stable vscode.
