### ISSUE TITLE
`/vscode` Commands Result in Stack Trace: No instance of IExperimentationService registered

### ISSUE THREAD

**Issue by mastercactapus** [microsoft/vscode-copilot-release#399]
## Description
Whenever I try to execute any `/vscode` command, the operation fails immediately and returns a stack trace. The error message suggests that "No instance of IExperimentationService has been registered."

## Environment Details

- VS Code Version: 1.83.0-insider
- Extension Version: v0.8.2023091401
- OS Version: Linux x64 6.4.6-76060406-generic
- Electron: 25.8.1
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0

## Steps to Reproduce

1. Open VS Code Insiders with the Copilot extension enabled.
2. Try executing any `/vscode` command.
3. Observe the stack trace error.

## Logs
```
No instance of IExperimentationService has been registered. Accessor created at: at new t.ServicesAccessor (/home/nathan/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091401/dist/extension.js:2:1263708) at t.createProductionContext (/home/nathan/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091401/dist/extension.js:2:1006999) at Y (/home/nathan/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091401/dist/extension.js:2:1605355) at e.activate (/home/nathan/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091401/dist/extension.js:2:1608464) at Function.ib (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:13152) at Function.hb (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:12873) at /usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:10997 at v.n (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:6206) at v.m (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:6169) at v.l (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:5626)
```

## Expected Behavior
The `/vscode` commands should execute as expected without throwing any errors.

## Actual Behavior
The `/vscode` commands fail immediately and throw a stack trace error related to `IExperimentationService`.

**Comment by lramos15** [comment]
This should be fixed now, please let me know if it's still an issue

**Comment by mastercactapus** [comment]
Confirmed this is fixed in the latest version this morning

**Comment by jtmano** [comment]
Just downloaded insiders and I'm experiencing the same issue. VS is up to date.

**Comment by lramos15** [comment]
> Just downloaded insiders and I'm experiencing the same issue. VS is up to date.

Make sure you're running the latest pre-release extension
