### ISSUE TITLE
GitHub Copilot Chat Icon is not showing up in activity bar.

### ISSUE THREAD

**Issue by zfields** [microsoft/vscode-copilot-release#4]
I was invited to the private beta: :heavy_check_mark:

![image](https://github.com/microsoft/vscode-copilot-release/assets/2801887/95b9c1bb-c490-4acf-8da7-0905c7815da6)

I installed the pre-release version of VSCode: :heavy_check_mark: 

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.6-76060206-generic
Sandboxed: No

I installed the required extensions: :heavy_check_mark: 

![image](https://github.com/microsoft/vscode-copilot-release/assets/2801887/aff11e85-c360-4d5a-878b-e779d83555ce)

- Name: GitHub Copilot Labs
  Id: GitHub.copilot-labs
  Description: Experimental features for GitHub Copilot
  Version: 0.14.884
  Publisher: GitHub
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-labs
- Name: GitHub Copilot Nightly
  Id: GitHub.copilot-nightly
  Description: Your AI pair programmer
  Version: 1.86.92
  Publisher: GitHub
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-nightly
- Name: GitHub Copilot Chat
  Id: GitHub.copilot-chat
  Description: AI chat features powered by Copilot
  Version: 0.1.2023051601
  Publisher: GitHub
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat

After installing all the required extensions, I restarted my entire computer just to be safe. As you can see from the window above, no chat icon appears in the activity bar.

What am I missing?

**Comment by roblourens** [comment]
It looks like you filed this issue from a stable release, are you sure you're testing this in VS Code Insiders? It will only work there.

**Comment by zfields** [comment]
Thank you @roblourens, you were correct in your observation.

Originally, I clicked the link provided in the email, and I downloaded the latest binary and updated VSCode. It upgraded me to 1.78.2, away from whatever I had before (which I thought was up-to-date). While writing this I followed the "same procedure" to validate the steps. This time it lead me to 1.79.0-insider, instead of 1.78.2.

Now, I've downloaded and installed the `vscode-insiders` binary. I tripped up on the fact that when I close and reopen vscode I'm not getting the insiders version 1.79.0 -- I'm still stuck on 1.78.2.

For the others out there unfamiliar with the VSCode Insiders, there is a new binary `code-insiders` that will launch VSCode that must be called instead of `code` as I had done before.

Furthermore, It doesn't import your settings and preferences from VSCode (regular), so you will have to go through and reinstall all your extensions.

**Comment by bamurtaugh** [comment]
> Furthermore, It doesn't import your settings and preferences from VSCode (regular), so you will have to go through and reinstall all your extensions.

This is a great question! You should be able to use Settings Sync to get most of your setup in Insiders: https://code.visualstudio.com/docs/editor/settings-sync#_syncing-stable-versus-insiders.

**Comment by lbussell** [comment]
I am also hitting this issue. I am on VS Code `1.79.0-insider` and Copilot Nightly `v1.86.92`. There is no chat icon in the activity bar.

**Comment by digitarald** [comment]
@lbussell please file a separate issues, as I will resolve this one (root cause was not using Insiders).

**Comment by jeffscottward** [comment]
I commented on the latest one someone just filed 30 mins ago.

Insiders
Nightly
Pre-release Chat

Nothing.

**Comment by exquest** [comment]
I'm on Ubuntu 20.04 and don't have a button in my activity bar...

I have the insiders build and the co-pilot nightly build like th emailed instructions tell us to.

**Comment by ArslanAmeer** [comment]
I was using stable VS Code.
What I did to get Chat feature 
- Install VS Code insider @ latest
- Install Copilot nightly extension and login to my github account (with copilot access) when asked.
DONE. no need to restart etc

**Comment by clipartinc** [comment]
Same issue, no chat icon or chat functionality. It was working fine, then it updated and stopped working.

**Comment by ArslanAmeer** [comment]
@clipartinc Just uninstall other extension like nightly etc. You only need these 2 extensions.

<img width="421" alt="Screenshot 2023-12-16 at 1 41 09 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/34485088/a326259e-9002-4144-85a3-199323fcc46b">
