### ISSUE TITLE
Store chat history locally

### ISSUE THREAD

**Issue by CasinoHe** [microsoft/vscode-copilot-release#40]
As a programmer, there are many cases that I need to return to some previous conversations and continue the previous questions. For example, after asking a few questions, I found that there was a question that I didn’t think clearly before, and then encountered the same situation again, then I need to repeat previous conversation from beginning. If there is a local history, then I can go back to the previous conversation directly, saving a lot of time.

**Comment by AntoineWVN** [comment]
Hello @CasinoHe. That would be a nice feature, I have no doubt they will implement it.
I just found out that you can export the current conversation.
It will create a json file that you can import later on.
You can access these features via the command panel (ctrl/cmd + p, followed by '>chat export' or '>chat import').
I am pretty sure they will create some buttons to be able to do it with the UI.

**Comment by CasinoHe** [comment]
> Hello @CasinoHe. That would be a nice feature, I have no doubt they will implement it. I just found out that you can export the current conversation. It will create a json file that you can import later on. You can access these features via the command panel (ctrl/cmd + p, followed by '>chat export' or '>chat import'). I am pretty sure they will create some buttons to be able to do it with the UI.

Thanks. I will try it. This is a great temporary alternative solution.

**Comment by roblourens** [comment]
There is also now a history list- you will see a button to see your history appear in the chat view toolbar
