### ISSUE TITLE
update issues

### ISSUE THREAD

**Issue by Tarseus** [microsoft/vscode-copilot-release#401]
- VS Code Version:code-insiders_1.83.0-1694757349_amd64
- OS Version:Linux-ubuntu 18.04
- Logs:No instance of IExperimentationService has been registered. Accessor created at: at new t.ServicesAccessor (/home/god/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091501/dist/extension.js:2:1263628) at t.createProductionContext (/home/god/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091501/dist/extension.js:2:1006999) at Y (/home/god/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091501/dist/extension.js:2:1605275) at e.activate (/home/god/.vscode-insiders/extensions/github.copilot-chat-0.8.2023091501/dist/extension.js:2:1608384) at Function.ib (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:13185) at Function.hb (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:12906) at /usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:136:11030 at E.n (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:6206) at E.m (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:6169) at E.l (/usr/share/code-insiders/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:5626)

I simply updated my vscode-insider and this is what i got.

**Comment by roblourens** [comment]
I think this is fixed in the latest- please let us know if you see it with the latest Insiders and latest version of the copilot chat extension
