### ISSUE TITLE
[Feat]:Smooth scrolling animation 

### ISSUE THREAD

**Issue by egyleader** [microsoft/vscode-copilot-release#402]
after the submitting the question and receiving the answer it is written to the screen with high speed and the scroll changes quickly in short time which is very annoying if you try to read the answer before the writing  is completed , here are some suggestions for making it user friendly : 

- hide the answer until completed and showing it completely with fade animation .
- make the writing effect more slow with smooth scrolling.
- make each paragraph show with smooth fade up animation & smooth scrolling change.

thanks in advance.

**Comment by roblourens** [comment]
Thanks for the suggestions, I will also consider them along with https://github.com/microsoft/vscode-copilot-release/issues/138
