### ISSUE TITLE
Cleanup and code deletion (negative edits)

### ISSUE THREAD

**Issue by agowa** [microsoft/vscode-copilot-release#403]
Currently copilot is completely useless when cleaning up a project or deleting code fragments that are loosely related.

Like having a project that has similar (but not completely identical) code for different versions or cases (like debian 8, 9, 10, fedora 36, 37, 38) and now starting to delete the sections related to older out of support versions/cases.

Copilot doesn't help with this at all.

Example project structure:

Root
| --> scripts/foo-debian8-bar.sh
| --> html/debian8/foo
| --> tests.sh

and test.sh contains sections for each version/case.

Even after doing it once for e.g. debian 8 it is not possible to tell copilot to "learn the structure" and repeat it for debian9 and so on.

**Comment by ulugbekna** [comment]
I do not understand how this uses copilot (inline or panel chat), what queries used, what files are open when you make the request. Please, provide a more complete flow. A screencast can help.

**Comment by agowa** [comment]
I wanted inline copilot to suggest the same change on the other sections as I did before. So "moneky see, monkey do" kind of suggestion for the negative edit.

I also tried to use the panel chat with a query like "remove distroX" and it didn't work either, but I'd have to try it again to be able to tell how exactly that one went wrong.
