### ISSUE TITLE
Takes time to connect and reply 

### ISSUE THREAD

**Issue by sahillangoo** [microsoft/vscode-copilot-release#405]
- VS Code Version:
- Version: 1.83.0-insider (user setup)
Commit: 7c7f7eee860e299499a3bd2915ad716f09f2d6a6
Date: 2023-09-19T08:56:35.775Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
- OS Version: Windows_NT x64 10.0.19045
- GitHub Copilot Chat Version : v0.8.202309190
Network: Jio Fiber 
Country: Kashmir, India 

Steps to Reproduce:
 1. Whenever i open VScode Insider Copiolot chat takes time to connect with the servers and throws this error : Error on conversation request. 
Workaround : Then i have to clear chat 2 3 time after then it responses or else have to connect via VPN afterwards it works fine!

**Comment by lramos15** [comment]
Checking if you still have this issue as many updates have been made.

**Comment by sahillangoo** [comment]
Yes, Issue was fixed last months update and its working fine now, Thank you!
