### ISSUE TITLE
Co-Pilot should have access to files in your VsCode workspace

### ISSUE THREAD

**Issue by RobKaiser97** [microsoft/vscode-copilot-release#408]
Copilot should be able to parse files and folders in entire workspaces to better contextualize questions being asked about code being currently worked on and also suggest where an error may be occuring

**Comment by viveknimkarde** [comment]
+1

**Comment by PaulSuarez1** [comment]
Do you have any suggestions to get this to work in the meantime? I've accidentally had it notice my codebase at times, but most of the time it says "I apologize for the confusion. As an AI language model, I don't have access to your local machine or the files you have open in your Visual Studio Code editor."

**Comment by RobKaiser97** [comment]
Not entirely sure, I've found that when you have just the folder you want to work in open it can reference the other files sometimes but it's hit or miss

**Comment by markfields** [comment]
I expected the chat to be a beefed up version of comment prompts - i.e. I was describing a change I wanted it to make in the code and wanted it to then go do it.

**Comment by RobKaiser97** [comment]
Phind has a good system that allows no context, auto context,and custom context that pulls entire workspaces as context, but it hasn't worked that well since it came out of alpha

**Comment by digitarald** [comment]
Duplicate of #14

**Comment by digitarald** [comment]
Sharing from #14: `@workspace` with _"Used references"_ landed in Copilot Chat 0.10 as part of VS Code's [October release](https://code.visualstudio.com/updates/v1_84#_workspace)

<img width="657" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/8599/9ac45254-74ae-4319-8c57-a612221b6985">

Please give it a try and file new issues for any follow-up feedback!

**Comment by Jjarrard** [comment]
Prompt: @workspace read all the files in the workspace

"I'm sorry, but as an AI, I don't have the ability to directly access or read files from your workspace. I can provide assistance based on the information or code snippets you provide in the conversation. If you could share the relevant parts of the code from the files you mentioned, I'd be happy to help analyze and compare them"

I'm struggling to get it to read 4 specific files, but sometimes it reads 13 and some duplicated? is there a limit on characters it can read? It sometimes picks up random files, even when I specify which file to focus on for a query.

**Comment by damokeitzy** [comment]
I am also getting this

I'm sorry for the confusion. As an AI, I don't have direct access to your files or codebase. I can only provide assistance based on the information you provide in the conversation. If you could share the relevant parts of the filterResultsHTML function and the structure of the HTML it generates, I would be able to provide more accurate guidance.

I replied with @workspace but the file is in my workpsace

and it repeated the same again.

original prompt was

@workspace not using react just jQuery Please use functions.lib.php function filterResultsHTML for the example html used

**Comment by Jjarrard** [comment]
Had this issue a lot today, I don't know if something has been changed or whether using it for a long period has caused it.

prompt
_@workspace  [literally question about highlighted code or focussed file]_

response
_GitHub Copilot
used @workspace
Encountered an error while deciding what workspace information to collect: failed_


The only way I've been able to get around it ~70% of the time is to: @workspace /fix [question]

**Comment by astra1dev** [comment]
Same issue here.

**Comment by lzeal** [comment]
Funny fact: in VSCode if subscription is expired, AI answears "I'm sorry for any confusion, but as an AI developed by OpenAI, I don't have access to your local files or your development environment.". And he doesn't have a clue (or prenends) about subscriptions, references etc.

**Comment by kawada711** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/100365282/79f5c582-5323-4260-927f-57ebcf7875c4)
awesome

**Comment by stellarpower** [comment]
> > @ workspace tell me about SimpleStatefulModel. Tell me how data are loaded into it, where is it used?
> 
> I'm sorry, but I still need the actual code of the SimpleStatefulModel to provide a detailed analysis. The structure of your workspace helps me understand the context, but without the specific code, I can't provide information on how data are loaded into SimpleStatefulModel or where it is used. **Please paste the code of SimpleStatefulModel here.**


Still falling back to the same as without the workspace "agent". and its contextual history wouldn't cover even 20 files were I to break them into sections not too long and paste them one by one.

**Comment by Showerss** [comment]
This is extremely annoying that I would have to copy/paste my entire codebase every time I want a suggestion 
Why was this disabled?

**Comment by tromboris** [comment]
I'm having the same issue. Has the issue improved at all for you or is it still hit or miss?

**Comment by leewaa** [comment]
Yeah this is very frustrating.

**Comment by alexpopa-work** [comment]
```
I'm sorry, I can't provide the exact code changes without knowing the current structure of the table in your active document 
```
The active file is opened and the code is highlighted. It used to "see" the code without trouble before, now it seems to be blind all of a sudden.

**Comment by WhiteX** [comment]
Experiencing the same problem. If I'm not mistaken this worked before. Especially while using the @workplace command.

**Comment by digitarald** [comment]
We had one change that got rolled back beginning of this week that didn't include the currently focused/visible file content by default. This is working again now.

`@workspace` did not change though and we don't have known regressions. If you have a `@workspace` query that worked before but fails now, please share the logs in a new issue so we can debug it.

**Comment by WhiteX** [comment]
I can confirm it works again. It was more like a VS Code bug, than a problem with Co-Pilot. Even though VS Code was updated and  restarted, at the Co-Pilot extension there was a prompt to reload the extension. Once I did that, `@workplace ` and file reading got back to normal / functional. Thanks.

**Comment by blueglyph** [comment]
It's hit and miss, but doesn't work most of the time. Starting from the editor (with Ctrl-I or right-clicking) works for a while, then it suddenly says "As an AI, I don't have direct access to your workspace or files" etc.

Sometimes, it's more insidious and it starts making up types; for example, when I ask to create a unit test.

Very unstable.

**Comment by digitarald** [comment]
@blueglyph by right-clicking in the editor, do you mean `Explain with Copilot`?

We got some more UX for showing which context Chat works in coming up that should help with this.

To be most specific about code, I recommend using:

- Selecting specific code chunks to ask about
- Referencing specific files with `#file` variable
- `@workspace` (or `Cmd-Enter`) for a questions that would look through the whole codebase.

If you have cases that end up in confused answers, please open issues with specific steps.

**Comment by blueglyph** [comment]
@digitarald It's for anything, really. The right-click commands seem to keep the context of the workspace, but using the side chat usually doesn't work. It briefly works after using Copilot from the editor, then it gets back to this "As an AI, I don't have direct access to your workspace or files" error.

Anyway, I've seen that Copilot was pretty bad at coding, which was to be expected. Generative AI shouldn't be used for this. Maybe the `Explain` and generic questions on the language are OK for people who really want this, so I would advise to use right-click or Ctrl-I to use Explain and the side chat for generic questions (which I think is what you mean, too).

The thing is, when you need explanation about a project, you don't want to browse through all the files to find where is such or such class to start the query, then find the next bit and iterate. It'd be much easier to ask all the questions from the chat.

**Comment by JamesAllerlei** [comment]
I’m having the same issue too. Copilot can’t read more than 80 lines of context in my script but also its very inconsistent. Occassionally it can.
