### ISSUE TITLE
Chat panel shortcut cmd+i cannot be modified.

### ISSUE THREAD

**Issue by ifyour** [microsoft/vscode-copilot-release#410]
Currently the call chat shortcut `cmd` + `i` is taken and cannot be changed. I'd like to make it configurable to change the shortcut. Thank you for your help.

**Comment by rafales** [comment]
Are you sure it can't be modified? I removed the binding with ease. It's a pain in the back that it's hijacked in the first place and definitely a bad decision, but it can be configured.

Simply open up shortcuts editor and either change keybinding for "Inline Chat: Start Code Chat" or remove it. There are actually two bindings (Another one is for `CMD+K I`.

**Comment by ifyour** [comment]
Bindings can be removed now, thank you sir.

Since I saw that the source showed System, I didn't notice that it was from Copilot.
