### ISSUE TITLE
Oops, your response got filtered. Opacity is decreased. 

### ISSUE THREAD

**Issue by AbdulRehmanUNI** [microsoft/vscode-copilot-release#414]
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

In some of the responses, when this message is shown in the "i" button on the end of the response. The opacity if the response is decreased. It makes the code really difficult to be seen which is really annoying.
![Screenshot 2023-09-22 181343](https://github.com/microsoft/vscode-copilot-release/assets/129224315/9af36e60-8d0f-4c61-be24-e0a96333b37e)

**Comment by ulugbekna** [comment]
The response is dimmed due to it being filtered and is intentionally not visible. Please, vote down if you think the response is filtered unjustly.
