### ISSUE TITLE
Chat  interrupted in middle

### ISSUE THREAD

**Issue by Mrt009** [microsoft/vscode-copilot-release#415]
While  I was using the copilot chat feature and i was telling it to update my code with the latest version of dependencies in my json files it was doing it while, but in middle the code got fade out , and i see the msg at the bottom telling Oops, your response got filtered. Vote down if you think this shouldn't have happened.

**Comment by GroovinChip** [comment]
This is happening a lot for me, too.

**Comment by digitarald** [comment]
Duplicate of #89
