### ISSUE TITLE
AI was too stupid for simple JS question

### ISSUE THREAD

**Issue by abdullzz** [microsoft/vscode-copilot-release#417]
copilot keep giving me the wrong answer after i told them to not repeat, also the suggestion seems broken as hell, with only one file in my project, most often it doesnt show any recomendation or auto completion, i got good internet connection

**Comment by abdullzz** [comment]
there's a lot of broken things in copilot, no different when i used it back in beta when it still free. i guess microsoft just rob me one more time

**Comment by abdullzz** [comment]
i wonder, what copilot do their best with? i dont think javascript is one of them

**Comment by abdullzz** [comment]
the data that was supplied for copilot seems really outdated back to 2021 november, it doesnt event recognize the newest bootstrap version

**Comment by ElectricRCAircraftGuy** [comment]
To help others verify and duplicate the problem, please post your entire conversation, in JSON format, like this: with your chat open, press Ctrl + Shift + P to open the command palette, type in `Chat: Export Session...`, save the chat.json file. Drag and drop it here.

If there was a particular JS (JavaScript) file you were working on when you were having the chat, and you are able to share it, please drop it here too.

**Comment by thomazchamberlain** [comment]
First day using Copilot in VS Code for Javascript. It sucks so bad. Every single time I've asked in chat to add some code/feature, it rewrites the whole source with hallucinated garbage. It's 100% unusable. Waste of money!

**Comment by thomazchamberlain** [comment]
It's not hard to duplicate. It really genuinely sucks with JS. Every single time I've asked in chat for a basic change to test it out it fails and spews nonsense hallucinations. I just paid the subscription today and it's clearly a total waste of money.

**Comment by chikega** [comment]
> You can also get a nice Markdown version by right-clicking in the chat and going to "Copy All". 
This is exactly what I needed. I like saving my notes in the [Bear app](https://bear.app) which supports very nice Markdown formatting.
