### ISSUE TITLE
Remember my native language to the extension settings

### ISSUE THREAD

**Issue by lilacs2039** [microsoft/vscode-copilot-release#419]
The following chat allows code descriptions in my language (Japanese).

```
/explain 日本語で回答
```

However, it is time-consuming to specify my language each time.
So, please add a setting item for my native language to the extension settings, and add it automatically to AI instructions. If the instructions are only `/explain`, it will save my time.

If my native language can be automatically obtained from "VSCode settings" or "GitHub account settings", it may save further time to setup this extension.

**Comment by joyceerhl** [comment]
@lilacs2039 do you use a language pack in VS Code? Perhaps we could infer the desired language from that, cc @TylerLeonhardt

**Comment by TylerLeonhardt** [comment]
`vscode.env.language` would be set to `ja` I believe if the user is using a language pack.

**Comment by lilacs2039** [comment]
> @lilacs2039 do you use a language pack in VS Code? Perhaps we could infer the desired language from that

No, I'm not using any language packs.

**Comment by lilacs2039** [comment]
> `vscode.env.language` would be set to `ja` I believe if the user is using a language pack.

This method looks good. My AI suggested the same method. (But I couldn't set up the vscode extension development environment in my environment, so I couldn't check the value)

**Comment by TylerLeonhardt** [comment]
Using a language pack has been the way to tell VS Code you're looking to use a different language and installing one is what changes the value of the `vscode.env.language` API.

I think that Copilot Chat could use this value to influence how Copilot should respond, but this won't help you if you don't use a language pack.
