### ISSUE TITLE
Chat input interpreted as markdown in log

### ISSUE THREAD

**Issue by Uberroot** [microsoft/vscode-copilot-release#422]
- VS Code Version: 1.82.2
- OS Version: Windows 10.0.19045
- Logs: n/a

Steps to Reproduce:

1. Open copilot chat dialog
2. "Describe the purpose of \_\_main\_\_ in Python"
3. Note that while the reply was appropriate the log for the developer-side dialog treated the input as markdown and displayed __main__ instead of \_\_main\_\_

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/107
