### ISSUE TITLE
[error] Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants

### ISSUE THREAD

**Issue by vonnilsson** [microsoft/vscode-copilot-release#423]
- VS Code Version: 1.82
- OS Version: Windows: Windows 10 Pro, 22H2
- Logs:

Steps to Reproduce:

1. install GitHub Copilot Chat
2. check output log

2023-09-26 20:29:09.112 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-26 20:29:09.611 [error] Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, handleIssueUri, chatSlashCommands, readonlyMessage, chatVariables, mappedEditsProvider, aiRelatedInformation
product.json (WINS): handleIssueUri, interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, chatSlashCommands, readonlyMessage, mappedEditsProvider, aiRelatedInformation
2023-09-26 20:29:11.651 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-26 20:29:11.989 [info] [perf] Render performance baseline is 45ms
2023-09-26 20:29:12.256 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-26 20:29:20.974 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-26 20:29:21.179 [error] Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, handleIssueUri, chatSlashCommands, readonlyMessage, chatVariables, mappedEditsProvider, aiRelatedInformation
product.json (WINS): handleIssueUri, interactive, interactiveUserActions, terminalContextMenu, terminalDataWriteEvent, terminalSelection, terminalQuickFixProvider, chatSlashCommands, readonlyMessage, mappedEditsProvider, aiRelatedInformation
2023-09-26 20:29:23.074 [warning] Settings pattern "application.*" doesn't match any settings
2023-09-26 20:29:23.747 [info] [perf] Render performance baseline is 31ms
2023-09-26 20:29:24.077 [warning] Settings pattern "application.*" doesn't match any settings

**Comment by digitarald** [comment]
Might be expected, but I let Rob clarify

**Comment by roblourens** [comment]
You should be able to ignore that, it will be fixed up in the next vscode release.

**Comment by thesolution** [comment]
I'm seeing this today 4/24/24 while trying to fix dev container extension host crashing. Should this be re-opened?

**Comment by digitarald** [comment]
@thesolution are your extension and VS Code on the latest updates?

**Comment by thesolution** [comment]
@digitarald As far as I can see I am. I deleted all extensions and VSCode as well as deleting VSCode user settings listed in the first answer of  [SO Question: How to completely uninstall VS Code on mac?](https://stackoverflow.com/questions/42603103/how-to-completely-uninstall-vs-code-on-mac) then reinstalled with a fresh download of the VSCode installer.

GitHub Copilot: `v1.183.0`

VSCode:

```
Version: 1.88.1 (Universal)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:42:52.765Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0
```
Error message in Developer Tools(line breaks added):

```
[Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' \
  CANNOT  use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: handleIssueUri, interactive, terminalDataWriteEvent, \
  terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, \
  chatParticipantAdditions,  defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, \
  aiRelatedInformation, codeActionAI,  findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, \
  newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT \
  aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following \
   command line switch: --enable-proposed-api GitHub.copilot-chat
w @ console.ts:137
```

<img width="555" alt="Screenshot 2024-04-25 at 11 47 55 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/1847089/43bdd279-89d4-4bd1-88ce-ddd008a9e411">

**Comment by digitarald** [comment]
@thesolution what's the Copilot Chat extension version (Command: `Developer: Show Running Extensions`)

cc @roblourens for checking out the shared logs.

**Comment by thesolution** [comment]
Copilot Chat `0.14.1`

<img width="373" alt="Screenshot 2024-04-25 at 1 05 50 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/1847089/69094961-cc26-4ffc-bcc4-ccd51cb6f4b2">

**Comment by thesolution** [comment]
Thank you @digitarald  and @roblourens for coaching me on what I need to send. I'm new at this.

**Comment by AdamCoulterOz** [comment]
I'm getting basically the same errors (`GitHub.copilot-chat` - `v0.15.0`)

**VSCode**
Version: 1.89.0
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:10:13.496Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

```log
2024-05-09 22:45:15.281 [error] Extension 'github.copilot-chat' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): extensionsAny, newSymbolNamesProvider, interactive, chatProvider, codeActionAI, findTextInFiles, findFiles2, textSearchProvider, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, mappedEditsProvider, aiRelatedInformation, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, contribSourceControlInputBoxMenu, authLearnMore, testObserver, aiTextSearchProvider
product.json (WINS): interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver
2024-05-09 22:45:17.213 [error] [Extension Host] [chat] Registration of interactive providers failed: Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
```

**Comment by zkreutzjanz** [comment]
Seeing same issue in a way. Getting that issue in vscode remote, breaking copilot chat remote. Also seeing no logs for normal copilot in remote, totally non functional. Issues began sometime in the last week.

**Comment by hhfrancois** [comment]
Same for me, too much issues with github copilot, tired
024-05-11 20:59:36.026 [info] [chat] Registration of interactive providers failed:,Error: Extension 'GitHub.copilot-chat' CANNOT use API proposal: aiTextSearchProvider.
Its package.json#enabledApiProposals-property declares: interactive, terminalDataWriteEvent, terminalExecuteCommandEvent, terminalSelection, terminalQuickFixProvider, chatParticipant, chatParticipantAdditions, defaultChatParticipant, chatVariableResolver, chatProvider, mappedEditsProvider, aiRelatedInformation, codeActionAI, findTextInFiles, textSearchProvider, contribSourceControlInputBoxMenu, newSymbolNamesProvider, findFiles2, extensionsAny, authLearnMore, testObserver but NOT aiTextSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.copilot-chat
2024-05-11 20:59:36.026 [info] [githubTitleAndDescriptionProvider] Initializing GitHub PR title and description provider provider.
2024-05-11 20:59:36.065 [info] [auth] Got Copilot token for hhfrancois
2024-05-11 20:59:36.067 [info] [githubTitleAndDescriptionProvider] Successfully activated the GitHub.vscode-pull-request-github extension.
2024-05-11 20:59:36.067 [info] [githubTitleAndDescriptionProvider] Successfully registered GitHub PR title and description provider.

**Comment by mrvlasyuk** [comment]
+1, same issue, copilot not working in remote with error about aiTextSearchProvider.
vscode and github copilot extension are the newest versions.

**Comment by hhfrancois** [comment]
finally, update vscode, uninstall plugins. remove github folder extensions, reinstall folder... works... many hours losted

**Comment by roblourens** [comment]
Please just check that Copilot Chat is updated to the latest, and note that it has to be updated on the remote you're connected to
