### ISSUE TITLE
CreateWorkspace command treats files without extensions as folders

### ISSUE THREAD

**Issue by asizikov** [microsoft/vscode-copilot-release#424]
- VS Code Version: 1.83.0-insider (Universal)
- OS Version: MacOS
- Logs:

Steps to Reproduce:

1.  Use this prompt: `/createWorkspace with hello.txt file and a Dockerfile`
2. Hit Create Workspace button

`Dockerfile` is rendered (and created) as a folder, not as a file, see the screenshot below

![Image](https://github.com/microsoft/vscode-copilot-release/assets/819053/4548e63d-67d1-4eab-ac8d-e643b499d694)

**Comment by NatCubed** [comment]
Can confirm on latest builds for Linux and Windows

**Comment by arun279** [comment]
Is there any reason this keeps getting pushed out? It could be quite useful.

**Comment by joyceerhl** [comment]
Fix should be out in tomorrow's Insiders alongside the pre-release of Copilot Chat
