### ISSUE TITLE
wayyyyy to much padding guys

### ISSUE THREAD

**Issue by leo-ware** [microsoft/vscode-copilot-release#425]
Just asking to reduce padding in messages. Too much text wrapping, messages disappear too quickly up the screen.

**Comment by daviddossett** [comment]
Any particular examples that would help illustrate the problem here? I may do some visual tweaks soon so it would be helpful to see what you're seeing.

**Comment by leo-ware** [comment]
I do a lot of web dev, so even though I have a monster monitor, every square inch very precious, because I always need multiple tools open. So, I just need the chat to take up less space.

Right now, each message has a ton of padding top and bottom, and it also shows my name, which is redundant information. Also, the font size is big... 

![image](https://github.com/microsoft/vscode-copilot-release/assets/54528853/a41ce9da-7d4a-42a4-99cc-e48feacf6f85)

Just because of the nature of the tool, I going to be sending a receiving a lot of long messages containing code snippets. Because so much vertical space is devoted to padding and username/profile pic, I can only really see one or two question/response pairs in the chat.

![image](https://github.com/microsoft/vscode-copilot-release/assets/54528853/218525c1-716a-4aa9-a42c-f16f48f4dece)

I would rather use copilot chat because I've already payed for a subscription, but I may end up using the ai in Warp terminal just its use of vertical space is so much more economical.

![image](https://github.com/microsoft/vscode-copilot-release/assets/54528853/22743519-faf6-4872-8f19-6d2ae0d371cc)

I'm not saying this is the worst thing ever or anything--just I would be happier as a user if the copilot chat widget were a more responsible consumer of screen space.

**Comment by justinmchase** [comment]
Compact mode :)

**Comment by roblourens** [comment]
Sorry, I'm seeing much fatter margins in Warp and a very large empty space at the bottom... you're saying that UI is _more_ efficient?
