### ISSUE TITLE
Error on conversation request (self signed certificate)

### ISSUE THREAD

**Issue by olek-ske** [microsoft/vscode-copilot-release#427]
xPlease search existing issues to avoid creating duplicates

- VS Code Version: Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0
- OS Version: macOS 13.6 Ventura
- Logs:  grep -Rnw 'Library/Application Support/Code/logs/' -e 'ChatMLFetcher'
Library/Application Support/Code/logs//20230925T110118/window6/renderer.log:185:2023-09-26 10:18:24.260 [error] [Extension Host] 2023-09-26T08:18:24.259Z [ERROR] [ChatMLFetcher] Error on conversation request: (FetchError) self signed certificate in certificate chain

Steps to Reproduce:

1. Start VScode and select some code
2. In the "GitHub Copilot Chat" pane, write: /tests , <Tab>, <Enter> => Submit
3. => "Error on conversation request. Check the log for more details." 
4. [Output], drop down: Window
2023-09-26 10:18:24.260 [error] [Extension Host] 2023-09-26T08:18:24.259Z [ERROR] [ChatMLFetcher] Error on conversation request: (FetchError) self signed certificate in certificate chain

Which certificate chain?
Please provide hints to how I debug

**Comment by alexdima** [comment]
@olek-ske Did you install any self-signed certificate in your certificate store?

**Comment by alexdima** [comment]
I think you can use the Keychain Access app to see certificates, clicking on System from the left and Certificates from the top.

**Comment by chrmarti** [comment]
Are you behind a network proxy?

Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`.

**Comment by olek-ske** [comment]
Solved by using the mac-ca-vs-code extension linhmtran168
[self-signed certificates installed in the Keychain](https://marketplace.visualstudio.com/items?itemName=linhmtran168.mac-ca-vscode)
