### ISSUE TITLE
Copilot Chat will not open

### ISSUE THREAD

**Issue by AlexandraKemperMS** [microsoft/vscode-copilot-release#429]
- VS Code Version: 1.82.2 (user setup)
- OS Version: Windows 11 (Windows_NT x64 10.0.22621)
- Logs: N/A
- Copilot Chat Version: v0.7.2023090101

My issue is that chat does not seem to be available - in the activity bar, in the output telemetry, etc. even though I have the extension. I also was given access to copilot chat previously, and it worked for me last week. I suspect I must have changed some sort of configuration/github login, but when I checked those it was using my corporate microsoft credentials so that should be fine. 

Steps to Reproduce:
1. Install the github copilot chat extension (insiders)
2. See that the extension is not shown in the activity bar

**Comment by wweevv-johndpope** [comment]
honestly - I've wasted 3 hours this week. I am on mac / ubuntu / windows - latest / vs code insiders - copilot can work - but chat doesn't. 
this seems like a capacity backend problem.

**Comment by wweevv-johndpope** [comment]
related
https://github.com/microsoft/vscode-copilot-release/issues/388

**Comment by digitarald** [comment]
Please see https://github.blog/2023-07-20-github-copilot-chat-beta-now-available-for-every-organization/#enterprise-admins for instructions to enable.

**Comment by digitarald** [comment]
@wweevv-johndpope sorry for the work this caused. There is no capacity issues, just some complex configurations on the org size that can currently conflict. The client, VS Code, has no insights into why Chat is not enabled.

Since Chat is rolling out to more users, like Individual subscribers, we expect to make this more obvious for users.

**Comment by AlexandraKemperMS** [comment]
With no changes on my side, Chat is now available for me again.

**Comment by stationname** [comment]
_FYI for employees:_  Maybe your organization turned off that feature on purpose.
If chat is turned on, some company data might get processed for "service improvements", while in beta.
