### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by pingayush** [microsoft/vscode-copilot-release#431]
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

work on this because it's not complete it's response and in between it stopped so work on it and give reasons why this happens every time.

I need proper solution for this bug in your chat feature

**Comment by digitarald** [comment]
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/295
