### ISSUE TITLE
Chat window has no code context?

### ISSUE THREAD

**Issue by markrmiller** [microsoft/vscode-copilot-release#433]
Maybe I just don't understand how this app is designed, but it loves to kick me over to the chat panel, like, "Hey man, go talk to the AI about this, that guy is just waiting to help on this", and then the chat panel is always like "Who are you, what are you talking about, why are you here?"

If I click, continue this discussion in the chat panel or anything like that, the chat panel is like, uh, what discussion. What code? What planet are you from?

If I click something like Quick Fix -> Use CoPilot, CoPilot is all like "GitHub Copilot: I'm sorry to hear that. Could you please provide more context or information about the issue you are facing?"

Oh I'm sorry, I left the context in the editor window that you seem to treat as my secret diary. But then my secret diary keeps sending me to you...and you don't know any more about anything than my browser window. What's the point of you again?

- VS Code Version: latest insiders
- OS Version: latest windows 11
- Logs: None

Steps to Reproduce:

1. Try to do anything with the chat window.
2. Chat window has no idea what you are talking about.

**Comment by alexdima** [comment]
@markrmiller Do you experience this in the sidebar or in the inline chat? Could you show us an example where this happens for you?

**Comment by aiday-mar** [comment]
Thank you for filing the issue. Could you also let use know what slash command you are using when you encounter the error. IE: is it /explain, /fix or perhaps you are not using a slash command - in which case could you give an example of the prompts that generate this issue?

**Comment by mipo57** [comment]
I have the same issue (Elixir, js & html codebase) in sidebar chat. Pretty much the same behaviour no matter what /slash (or without any) command I use. 

Eg. when I ask "What does module Some.Module.Name.ParseText do?" and I have a source code for this module opened on my side, it answers vaguely sth like this:

"From the name of the module "Some.Module.Name.ParseText" it seems like it parses some text. I would need more context do answer more specifically"

When I ask about arguments to function of this module, it says that it would need to have access to source code of that module
