### ISSUE TITLE
GitHub Copilot - Oops, no response has returned.

### ISSUE THREAD

**Issue by juntei0** [microsoft/vscode-copilot-release#434]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. open VS Code
2. type any word in Copilot chat window

I've updated , restarted VSCode, no change. is there something going on with copilot?

**Comment by lramos15** [comment]
Are you on insiders or stable?

**Comment by juntei0** [comment]
Insiders. Build.
 Updated again today (daily builds) and now I am getting 
 
 GitHub Copilot
Error on conversation request. Check the log for more details.

**Comment by juntei0** [comment]
> Are you on insiders or stable?

I was uninstalled and re-installed VS Code Insiders Edition and it appears to be working now.
