### ISSUE TITLE
Is there a plan to allow conversations to be threaded?

### ISSUE THREAD

**Issue by flowt-au** [microsoft/vscode-copilot-release#435]
It would be great if the conversations in the chat were threaded, similar to how it woks in (say) ChatGPT. 
If I want to find a question I asked 3 weeks ago, I need to scroll to find it. 
There doesn't seem to be a search option either?
This seems like basic chat functionality. Am I missing something obvious here?
Thanks,
Murray

**Comment by digitarald** [comment]
We have been looking at more complex threading but have to better understand how it's being used.

Curious, how do you find past questions in ChatGPT's threads?

**Comment by roblourens** [comment]
There is a button at the top of the pane, "Show History" to pull up past sessions

**Comment by flowt-au** [comment]
> Curious, how do you find past questions in ChatGPT's threads?

Not so much in the threads themselves, but... in my ChatGPT client in browser on the Mac it is a parent / child layout with the previous questions listed on the left. Click a previous question to see the chat messages for that question. Probably my use of the word "threading" was confusing.

Unfortunately ChatGPT doesn't allow searching of the questions, but that is another issue! ;-) 

It would be great if this copilot allowed threading + searching / filtering so one could quickly find the previous discussion about a question.

Thanks,
Murray

**Comment by flowt-au** [comment]
> There is a button at the top of the pane, "Show History" to pull up past sessions

Yes, I tried that. I get a dialog with a placeholder "Select a chat session to restore" but no items appear below it. If I start typing nothing appears either.

**Comment by roblourens** [comment]
> Yes, I tried that. I get a dialog with a placeholder "Select a chat session to restore" but no items appear below it. If I start typing nothing appears either.

If you have cleared the session, then it will appear in that picker. It sounds like you just have one really long thread.

> And anyway, what does "restore a session" mean in this context?

The past session will be loaded into the chat view

**Comment by flowt-au** [comment]
> It sounds like you just have one really long thread.

Yes, I do, because I didn't want to lose what I had there.

> If you have cleared the session, then it will appear in that picker. 

Is that what `/clear` does? I looked in `/help` and that slash command is not documented. So, I didn't try it in case I lost what I had. To me `/clear` means something like in a terminal. So, is `/clear` actually "clear the session which you can restore later"?

**Comment by flowt-au** [comment]
Ok. So `/clear` actually means: "Save the session and clear the chat box". Yes, you can then review the saved sessions as you described. My bad.

Thanks,
Murray
