### ISSUE TITLE
Add ability to remove "Fix using copilot" from Quick Fix menu

### ISSUE THREAD

**Issue by cvijdea-bd** [microsoft/vscode-copilot-release#437]
![image](https://github.com/microsoft/vscode-copilot-release/assets/136353184/ff2d86c1-5f8e-43ba-b92c-ac32e04aaa09)

When pressing ctrl + . on a reference to a missing import, what I want to do is import that missing reference, not ask copilot to spend 2 minutes trying to break my code.

I don't want to be forced to press down arrow twice just to avoid the copilot options, there should be an option to prevent them from showing up at all.

**Comment by dsherret** [comment]
This is already possible. See here for the must have setting: https://github.com/microsoft/vscode-copilot-release/issues/349#issuecomment-1740936588
