### ISSUE TITLE
Conflicting chat policies in two enterprise orgs results in no visible chat UI and no error message.

### ISSUE THREAD

**Issue by jannemagnusson** [microsoft/vscode-copilot-release#438]
- VS Code Version:
- Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0

- OS Version:
Windows_NT x64 10.0.22621

- Logs:

Steps to Reproduce:

1. Be a member of 2 enterprise organizations, one with Copilot and Copilot Chat enabled and one with Copilot and Copilot Chat disabled
2. Copilot works, but for Copilot Chat the extension will report "copilot token chat_enabled: false" and Chat UI will not appear.

I am not sure what the expected result should be in this case. Which policy should "win"?

**Comment by jannemagnusson** [comment]
There is also a support case for this, #2346211, if you want to connect the dots.

**Comment by Jenverse** [comment]
@jannemagnusson If user is part of two enterprises, then the strictest settings win i.e., if one enterprise has not allowed access to Copilot Chat then user would not get the access. If a user is part of two organizations within the same enterprise, then user could get chat beta access even if one of the organizations has granted access.

**Comment by jannemagnusson** [comment]
As far as I can see, it is not so much that chat is not allowed as copilot as a whole was not configured for the other enterprise (they don't have copilot there).
We are looking at having a separate enterprise setup for some partnerships. In this context we do not plan to offer copilot. This will be handled by the "parent" enterprise. How should the partnership enterprise be configured for this to work?
Also, there is no hint in VS code that this is the reason why you can't see chat, and it is also not in the "known issues" issue describing what to look at if you cannot see the chat view.

**Comment by thoth-seshat** [comment]
I'm only apart of a single org and I can't see the chat box.
