### ISSUE TITLE
Error on conversation request. Check the log for more details.

### ISSUE THREAD

**Issue by LinKPrian** [microsoft/vscode-copilot-release#439]
Version: 1.83.0-insider (user setup)
Commit: 4268e464763087044d0c1b5bdd37ebbe683cadfa
Date: 2023-09-29T20:42:50.630Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1.Start VScode and select some code
2.In the "GitHub Copilot Chat" pane, write: /tests , , => Submit
3. "Error on conversation request. Check the log for more details." 
4. [Output] [Extension Host] [error] Error: Failed to make request
    at t.fetchResponse (c:\Users\13255\.vscode-insiders\extensions\github.copilot-chat-0.8.2023092902\dist\extension.js:896:970)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at t.provideInteractiveEditorResponse (c:\Users\13255\.vscode-insiders\extensions\github.copilot-chat-0.8.2023092902\dist\extension.js:894:1602)
[Github Copilot Chat] [INFO] [chat fetch] modelMaxTokenWindow 4096
[Github Copilot Chat] [INFO] [chat fetch] chat model copilot-chat

Lastest 2023-10-01 10:32:26.961 [error] [Extension Host] 2023-10-01T02:32:26.960Z [ERROR] [ChatMLFetcher] Error on conversation request: (Ow) read ECONNRESET

**Comment by LinKPrian** [comment]
Yeah,eh,how to say what is often....This problem appeared first on Sep.29.I tried to reinstall this extension,update the vscode insiders,but it still didn't work until now.
Location:China.

**Comment by LinKPrian** [comment]
> [ulugbekna](/ulugbekna)

Yeah,eh,how to say what is often....This problem appeared first on Sep.29.I tried to reinstall this extension,update the vscode insiders,but it still didn't work until now.
Location:China.

**Comment by josephclarkmargen** [comment]
same issue

**Comment by dayanjan** [comment]
Same issue. Whether it is First it was VSCode and VSCode Insiders were working properly. Now the same issue in VSCode Insiders as well. 
Location: US East Coast

**Comment by jeffseiffert** [comment]
I've tried on both as well same issue

**Comment by jeffseiffert** [comment]
I'm not sure if this will fix it for anyone else but this article fixed it for me. Essentially install win-ca extension. Go to preferences -> settings -> extensions -> win-ca. Change to append mode. Restart VSCode.
https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot

**Comment by josephclarkmargen** [comment]
resolved it by installing this:
![image](https://github.com/microsoft/vscode-copilot-release/assets/47767607/04c89d29-11fa-4ba0-8f36-3aa4300a6434)

and change the settings to this
![image](https://github.com/microsoft/vscode-copilot-release/assets/47767607/1dd5a818-dc80-4540-9da6-db26a841c10a)

**Comment by josephclarkmargen** [comment]
> I'm not sure if this will fix it for anyone else but this article fixed it for me. Essentially install win-ca extension. Go to preferences -> settings -> extensions -> win-ca. Change to append mode. Restart VSCode. https://stackoverflow.com/questions/71367058/self-signed-certificate-in-certificate-chain-on-github-copilot

yup this works for me.

**Comment by LinKPrian** [comment]
not work sorry:(

**Comment by Loyal0713** [comment]
Hate to beat a dead horse but can confirm not working, I typically use Insiders (because cool features) but was running into this issue. Decided to reinstall VSCode (not Insiders), let all my settings/extensions sync and still not working. I tried installing the win-ca extension like suggested (and changed setting) but this did not work.

I do see below in window output:
**[ERROR] [ChatMLFetcher] Error on conversation request: (Ow) certificate signature failure**

**Comment by Sudiukil** [comment]
I was having the same issue on VSCode Insiders 1.83.0 earlier this week. Not being able to find a solution, I tried with VSCode stable 1.82.0 and it worked.

Today, it stopped working again, I checked my VSCode version... it got updated to 1.83.0.

Downgraded Code to 1.82.0 (as well as Copilot Chat to 0.7.1 since more recent versions require Code 1.83+) and it works again.

Seems the problem comes either from VSCode 1.83.0 or from the latest versions of Copilot Chat.

**Comment by LinKPrian** [comment]
@ulugbekna hello?

**Comment by sh-admin-AW** [comment]
I'm continuously getting this with copilot chat, even after installing the win-ca extension and setting it to 'append':

'Error on conversation request. Check the log for more details.'

output:
2023-10-10T02:35:42.149Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-10-10T02:35:42.151Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-10-10T02:35:42.152Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-10-10T02:35:42.234Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable
2023-10-10T02:35:42.246Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable

**Comment by aizhen1412** [comment]
> resolved it by installing this: ![image](https://user-images.githubusercontent.com/47767607/272486689-04c89d29-11fa-4ba0-8f36-3aa4300a6434.png)
> 
> and change the settings to this ![image](https://user-images.githubusercontent.com/47767607/272486830-1dd5a818-dc80-4540-9da6-db26a841c10a.png)

This method is inconsistent for me.

**Comment by lagebj** [comment]
Enabling the following setting in VSCode worked for me; In Settings > Application > Proxy enable `Experimental: System Certificates V2`

![image](https://github.com/microsoft/vscode-copilot-release/assets/32771387/f5453817-9817-4de5-b645-7c03e55db155)

**Comment by sh-admin-AW** [comment]
> Enabling the following setting in VSCode worked for me; In Settings > Application > Proxy enable `Experimental: System Certificates V2`
> 
> ![image](https://user-images.githubusercontent.com/32771387/276609927-f5453817-9817-4de5-b645-7c03e55db155.png)

I tried that and moved back into the 0.8.0 release but the issue remains.  

good suggestion though.

**Comment by sh-admin-AW** [comment]
I see this in the output when running (a functional version of) Copilot Chat 

2023-10-19T20:46:13.322Z [INFO] [chat fetch] engine https://copilot-proxy.githubusercontent.com/v1/chat
2023-10-19T20:46:13.322Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-10-19T20:46:13.322Z [INFO] [chat fetch] chat model copilot-chat
2023-10-19T20:46:15.132Z [INFO] [chat fetch] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions], took 1807 ms
2023-10-19T20:46:21.153Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-10-19T20:46:21.157Z [INFO] [streamChoices] request done: headerRequestId: [01afd55d-aa39-4e95-ba1d-d21406085d98] model deployment ID: [x31dbc412c159]

can someone confirm the URI has changed?  I cannot capture packets without an admin account. 

working:

https://copilot-proxy.githubusercontent.com/v1/chat

**Comment by lramos15** [comment]
> can someone confirm the URI has changed? I cannot capture packets without an admin account.

Yes, as I stated in https://github.com/microsoft/vscode-copilot-release/issues/471#issuecomment-1769478982 the Url has changed

**Comment by lramos15** [comment]
> ok, I see a *.githubcopilot.com. Could you provide an FQDN I can test with?

https://api.githubcopilot.com/

**Comment by sh-admin-AW** [comment]
thank you.  I can establish a port 443 connection on api.githubcopilot.com  from my EC2 instance and from my corporate laptop. let me know if more verbose logging can be enabled for this extension.

**Comment by lramos15** [comment]
> thank you.  I can establish a port 443 connection on api.githubcopilot.com  from my EC2 instance and from my corporate laptop. let me know if more verbose logging can be enabled for this extension.  
> 
> 
Can you try the latest pre-release of the extensions and insiders

**Comment by Declare777** [comment]
I'm also having issues with this as well and have tried all the other options above. 

Any news on the latest VPN update?

Log shows:

2023-10-20T13:49:50.115Z [ERROR] [asyncCompute] Failed to compute async parser based result: (Error) Unrecognized language: sql
2023-10-20T13:49:50.116Z [ERROR] [asyncCompute] Failed to compute async parser based result: (Error) Unrecognized language: sql
2023-10-20T13:49:50.117Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-10-20T13:49:50.117Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-10-20T13:49:50.117Z [INFO] [chat fetch] chat model copilot-chat

**Comment by LeonardoMor** [comment]
> I'm continuously getting this with copilot chat, even after installing the win-ca extension and setting it to 'append':
> 
> 'Error on conversation request. Check the log for more details.'
> 
> output: 2023-10-10T02:35:42.149Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable 2023-10-10T02:35:42.151Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable 2023-10-10T02:35:42.152Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable 2023-10-10T02:35:42.234Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable 2023-10-10T02:35:42.246Z [ERROR] [asyncCompute] Failed to compute async parser based result: (TypeError) t is not iterable

Getting this too. Running on VS Code on WSL2.

**Comment by LeonardoMor** [comment]
> I'm also having issues with this as well and have tried all the other options above.
> 
> Any news on the latest VPN update?
> 
> Log shows:
> 
> 2023-10-20T13:49:50.115Z [ERROR] [asyncCompute] Failed to compute async parser based result: (Error) Unrecognized language: sql 2023-10-20T13:49:50.116Z [ERROR] [asyncCompute] Failed to compute async parser based result: (Error) Unrecognized language: sql 2023-10-20T13:49:50.117Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat 2023-10-20T13:49:50.117Z [INFO] [chat fetch] modelMaxTokenWindow 4096 2023-10-20T13:49:50.117Z [INFO] [chat fetch] chat model copilot-chat

And this.

**Comment by Declare777** [comment]
@LeonardoMor 

What I did was installed GitHub Copilot Chat version 7.1 and everything worked before. The later versions aren't working well for some reason.

**Comment by lramos15** [comment]
> [@LeonardoMor](https://github.com/LeonardoMor)
> 
> What I did was installed GitHub Copilot Chat version 7.1 and everything worked like before. The later versions aren't working well for some reason.

Can you try the latest pre-release version and the latest insiders then share your logs? I've added some better error logging

**Comment by sh-admin-AW** [comment]
there is apparently a network side to this issue.  when working in VS code from my local C: drive, I can run copilot chat /explain queries fine.  

for now I'm working around this (two instances of VS code, one running pointed at a local folder, another connected to my EC2 instance via SSH), since network settings can't be modified on work devices.

**Comment by LeonardoMor** [comment]
> there is apparently a network side to this issue. when working in VS code from my local C: drive, I can run copilot chat /explain queries fine.
> 
> for now I'm working around this (two instances of VS code, one running pointed at a local folder, another connected to my EC2 instance via SSH), since network settings can't be modified on work devices.

I only get these errors when working on repos inside WSL2. If I'm not mistaken, VS Code and Windows do rely on the network stack for integration, so that might be.

**Comment by LeonardoMor** [comment]
> > [@LeonardoMor](https://github.com/LeonardoMor)
> > What I did was installed GitHub Copilot Chat version 7.1 and everything worked like before. The later versions aren't working well for some reason.
> 
> Can you try the latest pre-release version and the latest insiders then share your logs? I've added some better error logging

Installed VS Code insiders and pre-release versions of Copilot and Copilot chat. Got this:
```
2023-10-25T03:32:51.228Z [INFO] [auth] Logged in as LeonardoMor
2023-10-25T03:32:51.774Z [WARN] [RemoteSkillsService] Invalid /skills response: 404 page not found
 (SyntaxError: Unexpected token p in JSON at position 4)
2023-10-25T03:32:51.987Z [INFO] [chat] copilot token chat_enabled: true
2023-10-25T03:32:51.990Z [INFO] [auth] Got Copilot token for LeonardoMor
2023-10-25T03:32:52.049Z [INFO] [auth] Logged in as LeonardoMor
2023-10-25T03:32:52.050Z [INFO] [chat] copilot token chat_enabled: true
2023-10-25T03:32:52.050Z [INFO] [auth] Got Copilot token for LeonardoMor
2023-10-25T03:37:56.834Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-10-25T03:37:56.834Z [INFO] [chat fetch] modelMaxTokenWindow 8192
2023-10-25T03:37:56.834Z [INFO] [chat fetch] chat model gpt-4
2023-10-25T03:37:57.238Z [ERROR] [extension] Error on conversation request: (xR) The pending stream has been canceled (caused by: self-signed certificate in certificate chain)
```

**Comment by LeonardoMor** [comment]
So it turns out that I had `win-ca` installed in Ubuntu (WSL2). I removed it, restarted and things are working.

So I went to stable VS Code. Removed `win-ca` from Ubuntu. Restarted. The issue remains.

But I least I can use Copilot Chat on Insiders.

**Comment by LeonardoMor** [comment]
> So it turns out that I had `win-ca` installed in Ubuntu (WSL2). I removed it, restarted and things are working.
> 
> So I went to stable VS Code. Removed `win-ca` from Ubuntu. Restarted. The issue remains.
> 
> But I least I can use Copilot Chat on Insiders.

Nope. Restarted Insiders and and the issue came back.

**Comment by LeonardoMor** [comment]
Unchecked this:

![image](https://github.com/microsoft/vscode-copilot-release/assets/66377812/21670175-2dd1-4f84-b1fe-b7e0c3333639)

I'm both working in WSL2 and in a corporate network.

**Comment by lramos15** [comment]
> Unchecked this:
> 
> ![image](https://user-images.githubusercontent.com/66377812/277876235-21670175-2dd1-4f84-b1fe-b7e0c3333639.png)
> 
> I'm both working in WSL2 and in a corporate network.

I'll work on adding a better message in the UI for this error 👍

**Comment by LeonardoMor** [comment]
> Unchecked this:
> 
> ![image](https://user-images.githubusercontent.com/66377812/277876235-21670175-2dd1-4f84-b1fe-b7e0c3333639.png)
> 
> I'm both working in WSL2 and in a corporate network.

Back at not working even though no settings have been changed. I'm confused.

**Comment by lramos15** [comment]
> Back at not working even though no settings have been changed. I'm confused.

Same error?

**Comment by lramos15** [comment]
Here's a network test extension that also may help

Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?

If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`

The url you want to test is https://api.githubcopilot.com/

**Comment by LeonardoMor** [comment]
> > Back at not working even though no settings have been changed. I'm confused.
> 
> Same error?

Yes.

> Here's a network test extension that also may help
> 
> Could you install the Network Proxy Test extension (https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test) and check the output of `F1` > `Network Proxy Test: Test Connection` in VS Code?
> 
> If you cannot install the extension through the Extensions viewlet in VS Code, you can use the `Download Extension` link on the above linked page and then install the downloaded VSIX with `F1` > `Extensions: Install VSIX...`
> 
> The url you want to test is https://api.githubcopilot.com/

Once I install it, what do I do with it?

I was thinking that maybe there's no issue. It might be my company just blocking traffic to Copilot. They recently restricted GPT and all of those. So that might be too. I'll try to reproduce the problem in my personal computer.

**Comment by LeonardoMor** [comment]
These workarounds got it to work for now: https://github.com/LeonardoMor/WSL2_Copilot_and_Chat_WAs

Using the second one to just have NodeJS trust the self-signed cert.

**Comment by sh-admin-AW** [comment]
@LeonardoMor   I'm not sure if it was following the 'js-allow-selfsigned' script process and/or the 'monkey-patch-copilot' script, but I can confirm I'm running v0.8.0 (preview) while connected via SSH to my EC2 instance, and can finally query co-pilot chat consistently without errors (so far, I could be hopefully optimistic).   Thanks!

**Comment by LeonardoMor** [comment]
> @LeonardoMor   I'm not sure if it was following the 'js-allow-selfsigned' script process and/or the 'monkey-patch-copilot' script that resolved this, but I can confirm I'm running v0.8.0 (preview) while connected via SSH to my EC2 instance, and can finally query co-pilot chat consistently without errors (so far, I could be hopefully optimistic).   Thanks!  
> 
> I should note I'm still using the corporate VPN and no network settings have been changed AFAIK on this laptop
> 
> 
> 
> 
> 
> 

People should use the `js-allow-self-signed`.

**Comment by aleon1220** [comment]
you can also remove restrictions, to allow trusted certificates in Visual Studio Code (VSCode) on Windows 11 without using extensions, you can use the Workspace Trust feature or modify the system certificate store. Here are the steps for each method:

[Workspace Trust Feature](https://code.visualstudio.com/docs/editor/workspace-trust)[1](https://code.visualstudio.com/docs/editor/workspace-trust):

[VSCode’s Workspace Trust feature lets you decide whether code in your project folder can be executed by VSCode and extensions without your explicit approval](https://code.visualstudio.com/docs/editor/workspace-trust)[1](https://code.visualstudio.com/docs/editor/workspace-trust).
When in doubt, leave a folder in Restricted Mode. [You can always enable trust later](https://code.visualstudio.com/docs/editor/workspace-trust)[1](https://code.visualstudio.com/docs/editor/workspace-trust).
[Workspace Trust provides an extra layer of security when working with unfamiliar code, by preventing automatic code execution of any code in your workspace if the workspace is open in "Restricted Mode"](https://code.visualstudio.com/docs/editor/workspace-trust)[1](https://code.visualstudio.com/docs/editor/workspace-trust).
[Modify System Certificate Store](https://code.visualstudio.com/docs/editor/workspace-trust)[2](https://stackoverflow.com/questions/53794200/is-there-a-way-to-modify-the-vscode-certificate-store-to-add-certificates):

[Since Chromium uses the OS’s certificate trust infrastructure, the preferred option is to add your proxy’s certificate to your OS’s trust chain](https://stackoverflow.com/questions/53794200/is-there-a-way-to-modify-the-vscode-certificate-store-to-add-certificates)[2](https://stackoverflow.com/questions/53794200/is-there-a-way-to-modify-the-vscode-certificate-store-to-add-certificates).
Please note that these methods involve changing security settings and should be done with caution. Always ensure that you trust the source of the certificates you are adding to avoid potential security risks. If you’re unsure, it’s best to seek advice from a knowledgeable source or professional.

**Comment by chrmarti** [comment]
Please check the output of `F1` > `Developer: GitHub Copilot Chat Diagnostics` in VS Code and append it here.
