### ISSUE TITLE
Shortcut for "Insert at Cursor" and starting chat

### ISSUE THREAD

**Issue by 99991** [microsoft/vscode-copilot-release#44]
There should be a shortcut for the "Insert at Cursor" button and to begin a chat. It would be great if Copilot Chat could be used for advanced refactoring, but opening the chat window, writing a prompt and then trying to hit the tiny invisible-by-default icon introduces more friction than necessary.

The ideal workflow would be:

1. Press shortcut to begin chat with current selection.
2. Write prompt without having to focus the chat.
3. Press enter to insert Copilot response (or undo if the response was not good enough).

**Comment by MatthewCaseres** [comment]
They appear to have tried the approach and did chat because it was simpler? https://code.visualstudio.com/blogs/2023/03/30/vscode-copilot

**Comment by 99991** [comment]
Great! Apparently the thing I want already exists and is called "in-editor Chat".

#### How to use in-editor Chat (also called Code Chat in Visual Studio Code)

1. Select code you want to modify.
2. Press `Ctrl` + `I`. This will open a small Chat window below the selected code.
3. Enter your instructions describing how you want your code to be modified.
4. Press `Enter`.
5. If your instructions were "good enough", you will get a code suggestion (not always though).
6. Accept the suggestion with `Ctrl` + `Enter`.
