### ISSUE TITLE
Copilot inserts backticks

### ISSUE THREAD

**Issue by everdrone** [microsoft/vscode-copilot-release#440]
- VS Code Version: 1.82.2
- OS Version: windows 11 22h2

Steps to Reproduce:

1. open main.rs file or any other rust file
2. write `#[cfg(test)]`
3. copilot suggests:
````rust
mod tests {
    use super::*;

    #[test]
    fn test_main() {
        main();
    }
}
```
````

**Comment by ulugbekna** [comment]
Hi @everdrone ,

Thanks for filing the issue.

Could you please include a gif?

**Comment by everdrone** [comment]
i just realized i might be in the wrong repo, it's not relevant to copilot-chat but github copilot autocomplete.
the only relevant mention I've found https://github.com/orgs/community/discussions/47318#discussioncomment-6838088

video:

https://github.com/microsoft/vscode-copilot-release/assets/22671061/3df4c8ad-6074-4226-83df-a475c2ff4e48

**Comment by ulugbekna** [comment]
Yes, this is the wrong repo, thanks for clearing this up! I'll close the issue.
