### ISSUE TITLE
Copilot filters simple code related prompts

### ISSUE THREAD

**Issue by Dammi87** [microsoft/vscode-copilot-release#443]
- VS Code Version: 1.83.0 Insider
- OS Version: Windows 11
- Logs:

Steps to Reproduce:

1. Any code open
2. Ask it to rewrite as X
![image](https://github.com/microsoft/vscode-copilot-release/assets/23643258/30a376e2-0bee-45f4-8c66-7fb7dc6d9302)

**Comment by lramos15** [comment]
Copilot now respects your CFI / CFB public code matching setting and will disable the filter if you allow public code matches
