### ISSUE TITLE
Copilot chat gives an twirp error invalid_argument error

### ISSUE THREAD

**Issue by BunTymofiy** [microsoft/vscode-copilot-release#444]
- VS Code Insiders Version: 1.83.0-insider
- OS Version: Windows 10
- Logs: 
Everything was working perfectly, I ask a question I get an answer and the next one for no reason prompts me an error

Steps to Reproduce:

1. Ask anything
2.
![image](https://github.com/microsoft/vscode-copilot-release/assets/54686867/3d452d8b-2d46-4bfd-aa78-6d988c8731ff)

**Comment by roblourens** [comment]
Did the problem go away? If you see this again, please share the log from the Copilot output channel, thanks!
