### ISSUE TITLE
PHP solution chat response unreadable 

### ISSUE THREAD

**Issue by BrandonXZ** [microsoft/vscode-copilot-release#448]
- VS Code Version:1.82.1
- OS Version: WIN_NT 
- Logs:

Steps to Reproduce:

1. prompt a question with a lengthy solution:
mine was to generate a table/migration to compare with another solution.
2. wait to see error.

**Comment by ulugbekna** [comment]
Please, provide more information: 

1. copilot chat extension version
2. what error you're getting 
3. which chat you're using: panel or inline
