### ISSUE TITLE
Infer Reasonable File Name When Using "Insert Into New File"

### ISSUE THREAD

**Issue by Innders** [microsoft/vscode-copilot-release#45]
### Current Behaviour

Uses the first line of the suggestion.

For example: `import ReactFlow, { Elements, Node, Edge } from "react-flow-renderer";`

### Expected Behaviour

- Uses the function(s) suggested.
- Exports the function(s).

For example: `findConnectedNodesAndEdges.ts`

![image](https://github.com/microsoft/vscode-copilot-release/assets/49156310/03e1f437-03a5-4e0e-84c8-d14303f30545)

**Comment by digitarald** [comment]
Would be best if chat response annotates the code with a name for the file to create, so we don't have complex heuristics to come up with one on the client side. Wdyt, @roblourens @lramos15 ?
