### ISSUE TITLE
Repeat the previous question and ask him to reconsider answering it again

### ISSUE THREAD

**Issue by RSS1102** [microsoft/vscode-copilot-release#451]
Sometimes I think his answer is incorrect, and I want to ask him again. Can there be a button to repeat the previous question? For the convenience of me, I don't need to copy the previous question again

**Comment by ulugbekna** [comment]
For panel chat: you can press "up" to get the same question in the input box and send it again
For inline chat: you can either just resend or "regenerate" 

<img width="1591" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/16353531/d0a17c01-84e5-4a04-91a4-f27a0b0260cc">
