### ISSUE TITLE
Cannot use copilot chat , always get Error on conversation request. Check the log for more details.

### ISSUE THREAD

**Issue by chilam1234** [microsoft/vscode-copilot-release#455]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.open chat session
2. type anything

Result
![image](https://github.com/microsoft/vscode-copilot-release/assets/6899026/5af590a2-c05e-456f-8792-5acc4e1bbe18)
![image](https://github.com/microsoft/vscode-copilot-release/assets/6899026/de0a68c7-5825-4448-8b54-fa7b71f1ff73)

**Comment by StephenCurry30th** [comment]
Hello，sir，have u solven this issue？
