### ISSUE TITLE
For Visual Studio Code setting.

### ISSUE THREAD

**Issue by zincan-images** [microsoft/vscode-copilot-release#456]
Sorry, poor English.

I ask How to change color setting of Python commnet block area text color. 
Copilot reply normal answer, again and again. (or not good my question.)

For beginner's me, VScode setting is deep like a programming too. So, please help for VScode-self.
Of course, I wrong use copilot.

By the way, I resolved with normal internet search.

Thank you for Have a good flight.

![Screenshot 2023-10-05 202541](https://github.com/microsoft/vscode-copilot-release/assets/98735326/b85c7598-7144-4f38-9131-c98a75bf4ffa)
![Screenshot 2023-10-05 202606](https://github.com/microsoft/vscode-copilot-release/assets/98735326/2ee01eb9-612f-4ebb-beed-3df51e9913d8)
![Screenshot 2023-10-05 202617](https://github.com/microsoft/vscode-copilot-release/assets/98735326/8a29653d-c30b-4d5c-992e-d2a58e3fb16f)
![Screenshot 2023-10-05 202635](https://github.com/microsoft/vscode-copilot-release/assets/98735326/a7a4e85b-28a7-49d0-87ed-86a96635921a)

**Comment by lramos15** [comment]
Feel free to give `/vscode` a shot, next time! It's specialized towards answering questions about VS Code. Glad you figured this one out 👍
