### ISSUE TITLE
The chat only answers me: Error on conversation request. Check the log for more details.

### ISSUE THREAD

**Issue by CHAYA41182** [microsoft/vscode-copilot-release#457]
![צילום מסך 2023-10-05 150237](https://github.com/microsoft/vscode-copilot-release/assets/66823881/27c946c8-7f3f-4412-880f-39f461ab5c43)

- VS Code Version: visual studio insiders 
- OS Version: windows  11
- Logs:
![image](https://github.com/microsoft/vscode-copilot-release/assets/66823881/2d6cee9a-f4a5-41d7-b86b-bd0df30cc279)

Steps to Reproduce:

1.
2.

**Comment by AbderrEdrs** [comment]
i have same issue

**Comment by wsmelton** [comment]
I can report the same issue occurs on Mac OS as well.

- GitHub Copilot: `v1.123.471` (pre-release)
- GitHub Copilot Chat: `v0.9.2023100601` (pre-release/preview)

```console
Version: 1.84.0-insider
Commit: 874831ebcf088f59735879156f62308ce48f17d1
Date: 2023-10-06T19:09:58.333Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 21.6.0
```

**Comment by Szandor72** [comment]
Reporting the same issue on Windows 11. Logs do not turn up any errors and look similar to what wsmelton posted.

**Comment by quduoduo** [comment]
same problem

**Comment by wsmelton** [comment]
Posts "have same issue" or "following" don't help get this issue worked on. Most teams on GitHub prioritize issues by the number of 👍 the origin post receives, they are not counting the number of posts on issues. 

If we want this to get attention, add a 👍 to the first post.

**Comment by quduoduo** [comment]
vscode back to 1.82.3 works

**Comment by map-c** [comment]
same problem

**Comment by CHAYA41182** [comment]
Thank you so much!
I followed the instructions there
(install win-ca extension. Go to preferences -> settings -> extensions -> win-ca. Change to append mode. Restart VSCode.)
And now it's back to work!!
