### ISSUE TITLE
Scan input text files for code generation

### ISSUE THREAD

**Issue by bernardo-suez** [microsoft/vscode-copilot-release#46]
Several Python applications depend on input files with different formats, from json to modeling input files (e.g., EPANET *.inp files). It would be great if Copilot could navigate the structure of these files to suggest code to parse them, create unit tests that depend on sample files, etc. For example, EPANET inp files have pipe junctions defined under the header [JUNCTIONS] and each has an ID, elevation, demand, and pattern, as in the example below:

```
[JUNCTIONS]
;ID              	Elev        	Demand      	Pattern         
 10              	147         	0           	                	;
 15              	32          	1           	3               	;
 20              	129         	0           	                	;
```
If I have a class that imports such files, it would be great if copilot could suggest unit tests or other code to parse junctions and store the elevation of each junction under a class variable `elevation`.

**Comment by digitarald** [comment]
@bernardo-suez what happens right now when you give Copilot Chat these tasks?
