### ISSUE TITLE
Messages created by "View in Chat" cannot be removed

### ISSUE THREAD

**Issue by zyf722** [microsoft/vscode-copilot-release#461]
```
Version: 1.84.0-insider
Commit: 874831ebcf088f59735879156f62308ce48f17d1
Date: 2023-10-06T19:09:07.673Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

Steps to Reproduce:

1. Open VS Code.
2. Create a new file.
3. Write some code in the file.
4. Right-click on the code and select "Copilot -> Start Code Chat."
5. Ask something about the code.
6. Click the "View in Chat" button.
7. Dialog appears in Chat view.
8. Click the "Remove Request and Response" button.
9. Notice that the dialog still exists.

No error message shown in the DevTools or Window logs.

**Comment by roblourens** [comment]
This has been fixed in 1.85
