### ISSUE TITLE
Show history is always empty

### ISSUE THREAD

**Issue by ChrisMiami** [microsoft/vscode-copilot-release#463]
- VS Code Version: Version: 1.83.0-insider (Universal)
Commit: 254b455d8f1f02b3621e1c7c6c19798ea58945b9
Date: 2023-09-27T05:57:10.217Z (1 wk ago)
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

Steps to Reproduce:

1. Click the View History
2. Get the prompt "Select a chat session to restore" -- with nothing to select and no clue what to type into the box

Expected Behavior

Since I'm using the same account for all my code and all my Copilot chats, I'd expect to see all my conversations available no matter in which IDE I had them.

**Comment by ulugbekna** [comment]
Hi again @ChrisMiami ,

Since you're on VS Code Insiders: can you reproduce this behavior with the latest pre-release version of Github Copilot Chat extension? Because I think this got fixed.

**Comment by JohnnyVReply** [comment]
Hi, I am seeing the same issue today. I am using VS Code insider. I'm seeing the following issues:
1. my chats are per folder/repo that I'm opening in VS Code
2. those chats seem to have lost older ones, i'm not sure how long it should be for
3. if i open a new instance of VS Code (not a file or folder), the chat history is there for that window, but I can never seem to find it afterward

For me, I think I'd prefer to have the history be for all my chatting. I work in a bunch of repos, on similar codebases. Figuring out which repo I was in when I asked a question is quite tough

**Comment by roblourens** [comment]
Chat history is only saved per-workspace and per-machine. It's also limited to 25 sessions per workspace. Does that answer your question?

**Comment by Gladskih** [comment]
@roblourens So what if I was chatting without a workspace open? Because initially Copilot got distracted by the content of a workspace when I was asking about completely separate topic.
