### ISSUE TITLE
HTML in prompts is swallowed and not visible in chat

### ISSUE THREAD

**Issue by ChrisMiami** [microsoft/vscode-copilot-release#464]
Version: 1.83.0-insider (Universal)
Commit: 254b455d8f1f02b3621e1c7c6c19798ea58945b9
Date: 2023-09-27T05:57:10.217Z
Electron: 25.8.2
ElectronBuildId: 23977753
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.5.0

Steps to Reproduce:

1. Open Copilot Chat
2. Type a prompt such as
```
I'd like to create the worker like this:
<script>
  const worker = new Worker('js/Worker.js');
</script>
And then use it in the code like this:
  myWorker = document.worker;
Can I do that?
```
4. When you submit the prompt, it will appear in the chat history but WITHOUT the `<script>` tags or what's between them!
5. (Actually, when pasting the above prompt, even Copilot didn't see the tags or their content!  That's a new one on me!)

**Comment by ulugbekna** [comment]
Hi @ChrisMiami , 

Thanks for filing the issue.

For now, you can use wrap your code containing html into markdown inline code (wrapped with backticks) or code blocks (wrapped with triple backticks), e.g., 

```
I'd like to create the worker like this:
\`\`\`
<script>
  const worker = new Worker('js/Worker.js');
</script>
\`\`\`
And then use it in the code like this:
  myWorker = document.worker;
Can I do that?
```

(without backslashes before backticks)



![Image](https://github.com/microsoft/vscode-copilot-release/assets/16353531/eb0d35df-5e8b-4833-bb0e-a51b5d8463de)



![Image](https://github.com/microsoft/vscode-copilot-release/assets/16353531/4a375a25-0c8f-4de7-a532-eaad2c874c6b)


Thank you for patience with this!

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/107
