### ISSUE TITLE
Copilot repeats answers fails to get context

### ISSUE THREAD

**Issue by craftzneko** [microsoft/vscode-copilot-release#465]
- VS Code Version:Insiders and latest release
- OS Version:windows 10

It might be me, but it feels that recently co pilot repeats wrong answers that i have already said wont work. It will acknowledge that its Sorry for repeating and try this, which is just a repeat again. Additionally when asking for a sample of code, if i then have a slight issue with that code and suggest it doesnt work it will then completely provide a non contexted answer for something else asked much earlier

**Comment by mladen5000** [comment]
I've had this issue as well, and it is a recent development. Even when corrected it will apologize and reprint the rest as is

**Comment by samuelenidiaci** [comment]
Same here

**Comment by sleekyom** [comment]
Same here as well and i feel robbed that i had to pay for this monthly

**Comment by craftzneko** [comment]
and now i am getting another issue

Sorry, the response hit the length limit. Please rephrase your prompt.

But if i just ask it again it answers it without stopping. Logged this two weeks with no comments from MS

**Comment by lramos15** [comment]
Samples definitely help us in these cases. If you have some samples that we can test and work on improving that would be great!

**Comment by craftzneko** [comment]
I will give an exmple of repeated wrong answers when it next happens but here is some example of length limit issues

![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/7ad67877-0196-4856-914d-383058f08425)
![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/b8ea4bff-02d6-4d57-8802-d743c4138eff)
example of it not knowing if it has a limit.

Here is a very generic question that causes length limit

![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/49b73ed0-18c6-4a93-b4b5-3d9ddae052ff)
Which works
![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/946a0898-2388-4f3a-a66f-0f0e2d660cb3)
But then ask it to change to using COM instead of cmdlets, which should not generate more than an extra 10 lines

![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/11ed1a3a-3033-45d3-ae04-1e9250486e8e)

**Comment by lramos15** [comment]
Odd tried all these and even asking more questions with more verbose answers and never hit a rate limit. Just curious do you have a large file open with lots of selection? Do you hit this everytime?

**Comment by craftzneko** [comment]
This happens with a file open or all files closed. If i repeat the question it happens very time. I can run the same in general release and it works so appears only to be insiders issue

**Comment by lramos15** [comment]
Is there any information in your output channel?
