### ISSUE TITLE
Stoped responce

### ISSUE THREAD

**Issue by rahul-sharma-alx** [microsoft/vscode-copilot-release#466]
- VS Code Version:
- OS Version:
- Logs:

1. when i use Copilot, its give some responce and then it show : "Oops, your response got filtered. Vote down if you think this shouldn't have happened."
Steps to Reproduce:

**Comment by mcfalld** [comment]
I'm having the same issue, and it happens a lot. I don't get the error asking the same question to a different ai vscode plugin. I do have public code allowed.
![image](https://github.com/microsoft/vscode-copilot-release/assets/32588824/b9219b70-41ad-4bf4-8d16-4e92a1716c32)

**Comment by digitarald** [comment]
Code blocking since got only applies to accounts that have license checks enabled. Please re-open if this still happens.
