### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by ldynia** [microsoft/vscode-copilot-release#468]
### Request

As a software engineer, I work with various diagrams, drawings, and screenshots.  I'd like to have the ability to select (point to) an image, write a prompt, and get a description of the image. 

### Prompt

Explain the selected image.

### Example
![Screenshot from 2023-10-10 12-31-48](https://github.com/microsoft/vscode-copilot-release/assets/1820831/ab82e09e-c086-475e-89f4-8c1317398688)

**Comment by justschen** [comment]
closing in favor of https://github.com/microsoft/vscode-copilot-release/issues/554. if interested, we know have [this "Vision for Copilot Preview" extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-copilot-vision) as well which is a "bring your own key" model
