### ISSUE TITLE
Copilot cannot help with c++ embedded development

### ISSUE THREAD

**Issue by mvanheijningen1988** [microsoft/vscode-copilot-release#474]
- VS Code Version: 1.83.0 (Universal)
- OS Version: MacOS 14.1 Beta (23B5056e)
- Logs: -

Steps to Reproduce:

1. in Copilot chat search for the following "can you provide me a code example for esp32 in c++ to do ADC"
2. Result: Sorry, but I can only assist with programming related questions.

Another example:

1.
`void loop()
{
  // Reading potentiometer value
  potValue = analogRead(potPin);
  Serial.println(potValue);
  delay(500);
}`

2. search for: Can you suggest a way to modify the loop function to control the brightness of an LED using the potentiometer value?
3. Result: Sorry, but I can only assist with programming related questions.

I just registered for Copilot and these are examples that I can easily write myself but was curious with what code Copilot would come up.
As per my understanding I'm asking programming related questions.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/292
