### ISSUE TITLE
improoving chat history

### ISSUE THREAD

**Issue by vvp3** [microsoft/vscode-copilot-release#475]
I did post in some closed requests but because it might get overlooked, I think it is better that other users will see and aprooe this or not. Here it is:

Make the plugin show a hierarchy of files and even a directory structure to better organise the history.
Also, make it possible to rename the chats.

ty !

**Comment by roblourens** [comment]
> Make the plugin show a hierarchy of files and even a directory structure to better organise the history.


Not sure what you're referring to by this hierarchy?

**Comment by joyceerhl** [comment]
Please reopen if you can provide the requested info @vvp3
