### ISSUE TITLE
/createWorkspace stopped working?

### ISSUE THREAD

**Issue by martinwoodward** [microsoft/vscode-copilot-release#477]
Hey folks, just updated to the latest insider build and copilot chat extension and Create Workspace seems to be broken at the moment?  Not bringing up the button to allow you to create a codespace. Same queries were working yesterday.

Version: 1.84.0-insider (Universal)
Commit: 901ac65ea9f906d6996ad8e7639ba81acecf1d7c
Date: 2023-10-12T05:38:41.266Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

Steps to Reproduce:

1. `/createWorkspace a basic python hello world example`

Expected Results:
Get the Create Workspace button in the results

Actual:
Get an answer back from chat on the manual steps you would take.

**Comment by joyceerhl** [comment]
This should be fixed with the latest Insiders, please ping if that's not the case!

**Comment by SagarG23** [comment]
I m also facing the same issue . even after clicking the "create Workspace" , workspace is not getting created.

**Comment by joyceerhl** [comment]
@sagarg23 could you please file a new issue with full repro steps? Thanks!

**Comment by SagarG23** [comment]
@joyceerhl Given that the issue remains unchanged, should I initiate a new support request (new issue)? Following the input with "/createWorkspace," GitHub Copilot generates a file structure and presents an option to create a workspace. However, upon selecting this option, it fails to create the workspace.

**Comment by joyceerhl** [comment]
Can you share your full query, i.e. did you say something like `/createWorkspace create a typescript express app`, or did you literally submit `/createWorkspace`?

**Comment by SagarG23** [comment]
@joyceerhl  i have given something like this 
/createWorkspace Project Name: WeatherForecast Microservice ....(it has many like of prompt) .

**Comment by joyceerhl** [comment]
OK, please file a new issue with the full details of your prompt so we can try to reproduce, thanks!

**Comment by jaimezapataspg** [comment]
I used the following and worked 

@workspace /new
