### ISSUE TITLE
GitHub Copilot Chat gives false information regarding the incorporation of information from open files

### ISSUE THREAD

**Issue by SanjoSolutions** [microsoft/vscode-copilot-release#479]
SanjoSolutions:
> Can you (GitHub Copilot Chat) incoportate information from all open files?

GitHub Copilot:
> As an AI language model, I don't have access to your open files in Visual Studio Code. However, you can use the Visual Studio Code API to access information from all open files, as I mentioned in my previous response.

Then I have create a file `index.js` with the code:

```js
function a(a, b, c) {
  return a + b
}
```

and left it open.

SanjoSolutions:
> How can I fix this function?

GitHub Copilot:
> GitHub Copilot: The function `a` in your `index.js` file seems to be incomplete. It takes three arguments, but only returns the sum of the first two. If you want to fix it to return the sum of all three arguments, you can modify it like this:
> 
> ```javascript
> function a(a, b, c) {
>   return a + b + c;
> }
> ```
> 
> This will add all three arguments together and return the result.

This seems to indicate that GitHub Copilot Chat incorporates content from open files and that what GitHub Copilot Chat answered to "Can you (GitHub Copilot Chat) incoportate information from all open files?" was false.

There seems to be potential to improve what information GitHub Copilot Chat gives to questions regarding its capabilities.

**Comment by julian-shalaby** [comment]
The AI they used is not very strong, and they do not give any transparency to what is being stuffed in the context window of each message. [Here's](https://plugins.jetbrains.com/plugin/22895-chatwindow) an alternative which allows you to user GPT 4 via your own API key, and gives transparency as to what is being included in your context window

**Comment by ulugbekna** [comment]
Hello @SanjoSolutions ,

This is a good catch, thank you! 

It really depends on what you call Copilot (Chat). Copilot (as an AI model) indeed cannot access your open files on its own. It is the Copilot Chat extension identifies relevant content to your request and includes it with your request. 

We now also show what context was used explicitly in the UI: 

<img width="509" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/16353531/90800db8-f5dd-4c35-815b-35f6ec13552d">

Thank you for bringing this to our attention!

**Comment by AcademyOfGames** [comment]
Still having this issue. It says it's referencing my script but anything I ask it it tells me it can't read files on my computer. I'm writing variations of this. 

please list out all functions in the class CatchIt (I've also tried 'in the highlighted code' etc). Also write a 1 sentence description of what the function does.
