### ISSUE TITLE
Be able to Pop Out Chat and dock

### ISSUE THREAD

**Issue by maplion** [microsoft/vscode-copilot-release#48]
I would like to be able to keep the window open and access the rest of VSCode (e.g., Explorer) at the same time.  It would be nice to be able to dock it separately in different parts of VSCode and/or be able to pop it out so it can be its own window and just keep it open.

**Comment by akpi816218** [comment]
Agreed, would be nice. Otherwise I keep having to hide and reopen Copilot Chat just to take a peek at my code

**Comment by michaelronnfeldt** [comment]
Agreed. I keep having to swap back to explorer view or something else to see other files.

**Comment by StupidRepo** [comment]
Yeah. Also agreed for the same reason @michaelronnfeldt said.

**Comment by StupidRepo** [comment]
Alternatively, you could have it as one of these tabs:
![Screenshot 2023-05-20 at 13 09 31](https://github.com/microsoft/vscode-copilot-release/assets/69256931/5e6abd7e-60fe-425f-a6ef-7dade27884b5)

**Comment by maplion** [comment]
@StupidRepo I think that just moves the problem to blocking the terminal, output, etc.  The goal is to have all of VSCode at your disposal and have the chat window popped out so it can be moved around, sit next to your VSCode, etc.  Docking options would be a bonus so it could exist in spaces like the one you show, but next to other items (e.g., so it resembles a split terminal window).

**Comment by MCKevmeister** [comment]
It would be nice if there was more than one primary side bar in vs code. Docking copilot chat the non main side bar would be nice and have clickable icons.

**Comment by StupidRepo** [comment]
> @StupidRepo I think that just moves the problem to blocking the terminal, output, etc. The goal is to have all of VSCode at your disposal and have the chat window popped out so it can be moved around, sit next to your VSCode, etc. Docking options would be a bonus so it could exist in spaces like the one you show, but next to other items (e.g., so it resembles a split terminal window).

Ah yeah... silly me.

**Comment by roblourens** [comment]
You can also put it in the editor view, either with the "Open editor" command or the "Open session in editor" command under the `...` in the view title (currently this command only works when you have already asked a question in the chat)

**Comment by StupidRepo** [comment]
> You can also put it in the editor view, either with the "Open editor" command or the "Open session in editor" command under the `...` in the view title (currently this command only works when you have already asked a question in the chat)

I just found this out and was literally coming here now to tell people this. Looks like you beat me to it. By 4 days!
