### ISSUE TITLE
Add Lua as a recognized language in the Copilot Submenu for suggestions

### ISSUE THREAD

**Issue by Jax-Danger** [microsoft/vscode-copilot-release#480]
Hi, I'm writing scripts in Lua and I'd really like it if I could use the submenu for suggestions. When I try to use the copilot submenu > fix, it says "unrecognized language: Lua". Now, I know lua is technically supported in terms of auto completion and code suggestions using the chat window, but I'd really like it if it was a recognized language for the copilot submenu commands.
![Screenshot 2023-10-13 002352](https://github.com/microsoft/vscode-copilot-release/assets/58536302/03fd5eef-af65-486a-91df-271e3ac18a7a)

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue, Lua is currently not supported by our tree-sitter infrastructure. We will look into it.

**Comment by Jax-Danger** [comment]
I understand. Thank you for your response.

**Comment by aiday-mar** [comment]
Hi @Jax-Danger. This issue should be fixed with the PR https://github.com/microsoft/vscode-copilot/pull/1643. If you are on Insiders, the bug should be fixed if you switch to the latest pre-release extension. For the stable version, it appears that a new pre-release has not been made yet that contains the fix. The pre-release/release should be available soon.

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. It should be fixed on the latest stable

**Comment by lost-scripts** [comment]
> Hi @Jax-Danger. This issue should be fixed with the PR https://github.com/microsoft/vscode-copilot/pull/1643. If you are on Insiders, the bug should be fixed if you switch to the latest pre-release extension. For the stable version, it appears that a new pre-release has not been made yet that contains the fix. The pre-release/release should be available soon.

Does that mean Lua is going to be supported that way, then? The provided link appears broken and I can't get to any further info or details... Thanks.

**Comment by lost-scripts** [comment]
Hi @aiday-mar, thanks for confirming! I'm not using Copilot Chat (yet) but considering, so I just wanted to be sure, knowing Lua it's not listed as one of the officially supported languages, till what point it is supported, and being certain this is not a problem anymore is something... so thanks again and have a nice day!
