### ISSUE TITLE
Too chatty/no fluff mode

### ISSUE THREAD

**Issue by merlindru** [microsoft/vscode-copilot-release#481]
I'd love if there was an absolutely-no-fluff-mode for Copilot Chat.

For example, I was looking at a docker-compose file that had a postgres db configured.

I wanted it to generate a connection string for this, so I typed "connection string". (I know the prompt is bad, but other, longer prompts have yielded even longer results)

Here's what it replied with:

> To create a connection string for the PostgreSQL database service defined in the docker-compose.yml file, you can use the following format:
> ```
> postgres://<username>:<password>@<host>:<port>/<database>
> ```
>
> Using the information from the docker-compose.yml file you provided, the connection string would be:
>
> ```
> postgres://username:password@localhost:5543/postgres
> ```
>
> Note that localhost is used as the host since the database service is running locally on the same machine as the application. The port number 5543 is used since it is mapped to the default PostgreSQL port 5432 in the container. Finally, postgres is used as the default database name for the PostgreSQL image.

When all I needed was this:

> `postgres://username:password@localhost:5543/postgres`

When I asked it to provide just the connection string without any explanation, it put out exactly that. But I don't want to append "No explanations" to every single prompt.

And I realize it can't read my mind and infer intent from a short prompt like that, but all the fluff makes it harder to get to what I want.

Instead of a length prompt once, I'd like to type out multiple prompts, each refining the final solution.

Right now it seems to lose the context unless I specifically refer to the previous message, making it feel much less like a chat

---

Another issue is that when it generates a very long answer, but it already put out the relevant code snippet at the top of its answer, I can't copy it because of the autoscrolling — maybe autoscrolling could stop when we hover over the latest/still-being-written message, and only scroll down when unhovering? 

Otherwise it's been absolutely great :) Hope this didn't come across as harsh, just wanted to leave some thoughts! Thanks y'all

**Comment by digitarald** [comment]
@merlindru have you tried inline chat for directly applying AI to code?

**Comment by lramos15** [comment]
Consolidating custom instructions into https://github.com/microsoft/vscode-copilot-release/issues/563
