### ISSUE TITLE
When enabled I cannot use "quick fix".  Just causes a loading state for forever.

### ISSUE THREAD

**Issue by brycefranzen** [microsoft/vscode-copilot-release#483]
Type: <b>Bug</b>

Open a file using a parameter from an import which isn't included in the file.
Open "quick fix" to add missing import.

With copilot chat installed and active, the "quick fix" menu doesn't work.
With it disabled, all works again.  Verified with Extension Bisect. 

Extension version: 0.9.2023101301
VS Code version: Code - Insiders 1.84.0-insider (4678919d52909efc7c4ab958a2e5c8f45d50ffc3, 2023-10-13T05:33:39.403Z)
OS version: Linux x64 6.4.6-060406-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 3190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|31.08GB (18.84GB free)|
|Process Argv|--unity-launch --crash-reporter-id 2eb08dad-c1c1-4054-a4a6-1c3983eebad2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by aiday-mar** [comment]
Hi thanks for posting the issue. Could you post here an example of the file where you see the error, as well as the exact line where you are triggering the copilot quick fix? 

When you say the quick fix menu does not work, does this mean that you are not able to open the menu when clicking on the lightbulb or that when you click on `Fix using Copilot`, this does not work?

**Comment by brycefranzen** [comment]
The issue is back.  Quick fix stalls and shows a loading bar at the top, but never opens the dialog. Disabling copilot chat extension is the only thing that gets it working again.  Re-enabling this extension breaks it again.  It's definitely something to do with the copilot chat extension. 

I have tried on vscode and vscode-insiders, both have the same issue.

**Comment by kblatna** [comment]
I have similar problem. If I have any mistake in my code and try to use Quick fix, it only repeats the info about mistake.
Before Copilot Chat enabled, it helped me to fix problems.

![Snímek obrazovky 2023-10-23 162748](https://github.com/microsoft/vscode-copilot-release/assets/39617047/bb0588c2-7c71-4714-baeb-4e46718469ff)

**Comment by aiday-mar** [comment]
Hi @kblatna, I think your issue is different. The inline chat actually appears for you. It is expected that the error is written in the inline chat. It contains the error that has to be fixed. The error you are seeing is that the language is not recognized by our tree-sitter code. There is a fix for this that should come out soon.

**Comment by brycefranzen** [comment]
This may have been resolved in a recent update as I haven't experienced this issue in a little while. I'll re-open this issue again if/when this resurfaces and i'll include screen captures/logs at that time.  Thanks!
