### ISSUE TITLE
Copilot chat giving error

### ISSUE THREAD

**Issue by anirban2304** [microsoft/vscode-copilot-release#484]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Started a chat 
2. Got this error: Error on conversation request. Check the log for more details.

**Comment by saraDaum** [comment]
Me too...
I installed GitHub Copilot Chat, but it write only:
Error on conversation request. Check the log for more details.

What should I do??

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/471
