### ISSUE TITLE
Please improve the stability of the extension with regular updates

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#486]
the extension is not stable

**Comment by digitarald** [comment]
@fisforfaheem do you have a specific set of problems you experience? Updates are monthly, with dot releases for regressions.

**Comment by fisforfaheem** [comment]
by means updates, is that the extension seems unstable and not proper. kindly add proper changelogs for users

**Comment by roblourens** [comment]
Feature updates to the extension are described in the VS Code release notes each month. https://code.visualstudio.com/updates
