### ISSUE TITLE
Scroll position memory

### ISSUE THREAD

**Issue by ranulv** [microsoft/vscode-copilot-release#487]
At times it is necessary to scroll up and look through the generated responses while switching between files and doing other tasks. So this would be a really useful feature to have both in sidebar view and editor view.

**Comment by roblourens** [comment]
Sorry, I don't quite understand what you're asking for?

**Comment by ranulv** [comment]
Automatic Position Recall: The application remembers the scroll position in each file or document when users switch to another file or perform different actions. This means that when they return to a file, the application automatically restores the previous scroll position.

**Comment by roblourens** [comment]
I still don't understand. You were talking about the chat history and now you're talking about files, where we should already remember your scroll position. Please explain very clearly step by step what you want to happen

**Comment by joyceerhl** [comment]
Please reopen if you can provide the requested info @ranulv
