### ISSUE TITLE
The "code relevance check" has a lot of false negatives around IC programming. 

### ISSUE THREAD

**Issue by Voxar** [microsoft/vscode-copilot-release#489]
I get the "Sorry, but I can only assist with programming related questions." a lot while learning about firmware and IC programming. Sometimes my questions are more towards the hardware and I could understand that gets flagged. I'm in a Zephyr project and Copilot has been helpful many times as well. 

- VS Code Version: e7e037083ff4455cf320e344325dacb480062c3c
- OS Version: MacOS 13.4.1
- Logs:
<img width="424" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/45087/68c3f11f-9d2b-4015-9293-f1acef7d0fda">

This is after a few back and forth messages, including a decent code snippet reply, on the topic of interrupt handling, so It's not like my questions are out of context. 

Steps to Reproduce:

1. Ask questions around firmware, IC communication, electronics.

**Comment by digitarald** [comment]
Sorry to hear. We have updates on the off-topic filter planned and will make sure we got your test cases covered.

**Comment by mingwu-gh** [comment]
I can reproduce the error when I don't have any repo open and start the conversation fresh (so no previous code context). But once I have any tabs open, this seems to go away. @Voxar do you have all the context when you see the errors? Cc @zhiguoyu

**Comment by felipe-ds-lima** [comment]
I can reproduce it too
![image](https://github.com/microsoft/vscode-copilot-release/assets/46056744/5e630cce-6633-4d77-8a7a-6f30bf885865)

**Comment by sharonlo** [comment]
@Voxar , @felipe-ds-lima thanks for your patience. We've deployed an update that addresses this. Please let us know if you're still hitting these issues!

**Comment by digitarald** [comment]
Closing for now, as those questions work. Please file new issues for follow-up reports.
