### ISSUE TITLE
Allow users to use your GitHub Copilot with all the features in whatever IDE they want to

### ISSUE THREAD

**Issue by MCKevmeister** [microsoft/vscode-copilot-release#49]
I use Webstorm as my primary editor, rider as my primary editor for C#. VS code doesn't come anywhere near close to the feature provided by these editors for me in my use case (and many other users). Only providing GitHub Copilot Chat in VS code means context switching, so no different than using ChatGPT.

I propose you either:

 1. Allow users to use the tools where ever they want to. There is already a GitHub Copilot plugin for IntelliJ for webstorm/rider. Why are you not supporting a release to these platforms of all of the features of GitHub Copliot? I have run into the same issue with [Power Platform Tools](https://learn.microsoft.com/en-us/power-platform/developer/cli/reference/tool) a CLI tool that requires a GUI to install? Why is Microsoft making tools that are dependent on VS code?
 
2. Rename the product. If you won't release GitHub Copilot Chat to IntelliJ then the product should be renamed "GitHub Copliot Chat for VS Code". It then aligns with the rest of Microsoft's branding for Copilot. This then indicates what the product actually is rather than what you are attempting to sell the product as.

3. Explain to your users why they can use GitHub copilot but not GitHub Copilot Chat in Intellij editors. Why are some of the features locked behind IDE choice? There has been zero communication as to this. I could make many assumptions about why this might be, but I'd rather you told me and the rest of your users why you won't support Intellij. I am paying for another editor and choosing to not use VS Code. 

If you want to make me use VS Code, make it better! Look at the features that IntelliJ editors have and include them out of the box. I dislike having to install and configure 100's of extensions just so to make VS code work half as well as Webstorm does out of the box for JavaScript/Typescript, the way Rider does out of the box for C#, the way PHPStorm does out of the box for PHP. No restricting tools to just Microsoft VS Code is going to make me switch in the long run. I've used VS Code in the past, and load it up occasional, but it under preforms in so many different ways that I can't justify using it as my primary IDE.

The reason I'm commenting here is that I've been asked to provide feedback specifically here. Please do not respond with mentioning that this repo is vscode-copilot-release as such is for feedback of the vs code extension. My feedback is for GitHub Copilot Chat as well as the other new features for GitHub Copilot.

**Comment by NikiLentz** [comment]
I am sure they will do this as soon as it is actually released. Since the extensions for normal copilot already exist.

**Comment by xjjon** [comment]
Would love to see this available for jetbrains IDEs. I primarily use Rider and IntelliJ

**Comment by MCKevmeister** [comment]
> I am sure they will do this as soon as it is actually released. Since the extensions for normal copilot already exist.

> 3\. Explain to your users why they can use GitHub copilot but not GitHub Copilot Chat in Intellij editors. Why are some of the features locked behind IDE choice? There has been zero communication as to this. I could make many assumptions about why this might be, but I'd rather you told me and the rest of your users why you won't support Intellij. I am paying for another editor and choosing to not use VS Code.

**Comment by digitarald** [comment]
On a high level, as this in technical preview the team's resources limit how many editors can be supported.

This repo is for feedback for Copilot Chat in VS Code, so we can't help with other editors; but let the GitHub Copilot team know.

Meanwhile to make the most out of your early access to Copilot Chat in VS Code, I recommend our language docs to set it up for your specific language: https://code.visualstudio.com/docs/languages/overview . If you find gaps in features and design, we and the authors of the various language extensions would love to hear feedback and get issues filed (_Help: Report Issue_) .
