### ISSUE TITLE
Causing search issues in settings and when searching all files

### ISSUE THREAD

**Issue by georgekolasa** [microsoft/vscode-copilot-release#491]
Type: <b>Bug</b>

I did a vscode `Start Extension Bisect` bisect and this extension is what was causing search issues in the settings and when searching all files. Disabling it causes searches to not hang and be fine again.

I'm on a M2 mac with plenty of memory and CPU power. But something with this extension is causing searches to hang/never complete.

Extension version: 0.9.2023101701
VS Code version: Code - Insiders 1.84.0-insider (Universal) (0c36b92c82064882a228487040187cfc13669c0f, 2023-10-16T05:37:24.728Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|32.00GB (3.61GB free)|
|Process Argv|--crash-reporter-id 2718ddd7-027e-411f-984a-c80af8a9ef3f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
a9j8j154:30646983
showlangstatbar:30737417
24365598:30687740
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
welcomedialog:30812478
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
copilotsettingt:30808721
dsvsc013:30777762
dsvsc014:30777825
diffeditorv2:30786206
pythonmpsinfo:30859869
dsvsc015:30821418
pythontestfixt:30859590
pyreplss2:30864989
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30864172

```

</details>

**Comment by rzhao271** [comment]
This issue should be fixed with the latest VS Code Insiders along with the latest pre-release of the Copilot Chat extension. There was a misconfigured setting, but the Settings editor also wasn't doing enough validation.

Let me know if you're still experiencing the issue after upgrading!

**Comment by rzhao271** [comment]
Closing for now. Feel free to comment or file a new issue if the problem still exists in the newest version of VS Code.
