### ISSUE TITLE
`Reply me in ${specificLanguage}` is forbidden in Copilot Chat 

### ISSUE THREAD

**Issue by LikeDreamwalker** [microsoft/vscode-copilot-release#494]
- VS Code Version: Codespaces

Steps to Reproduce:

1. Talk to Copilot Chat and ask her to reply in a specific language, like English
2. Copilot Chat will think this request is unrelated to programming, so she refuses to respond.

![image](https://github.com/microsoft/vscode-copilot-release/assets/45194556/764f0efe-34eb-4def-94d3-0a5c5c27ace7)

And Copilot Chat seems like will prefer to reply to me in the language based on my location or my profile, like Chinese. But the Chinese reply is actually translated from English so I prefer English, and that's how I found the issue. What's more, to ask Copilot Chat to reply to me in English, I have to ask her like "Please check this code and reply me in English" to make it work.
Also this issue is not existed for a very long time, but I can't remember when it started.

**Comment by ulugbekna** [comment]
Hi @LikeDreamwalker ,

Thanks for filing this issue. 

Indeed, it's best to ask you programming question. If it doesn't reply in language you prefer, please, include instruction to reply in a specific language in your particular question. "What does this code do? Reply in English". 

Thank you for your patience with this!

**Comment by roblourens** [comment]
You'll also be able to see the new setting `github.copilot.chat.localeOverride` in the next release (or current pre-release in vscode insiders)
