### ISSUE TITLE
Sorry, the response hit the length limit. Please rephrase your prompt.

### ISSUE THREAD

**Issue by craftzneko** [microsoft/vscode-copilot-release#497]
Using preview version, nearly every response that is over 20 lines returns above, making it next to useless to use. Not sure where i am supposed to post this, cant find a preview release repo

**Comment by jdkolassa** [comment]
I just noticed recently that it started doing this on almost every single prompt. It's quite frustrating, especially since my subscription just renewed. I'm trying to find any sort of documentation or mention in the changelogs about this changing. I think I saw somewhere there is a 1000 character limit, but I went back to previous chats and the responses there were sometimes much longer than 1000 characters. Has there been a change, or have I borked something on my own system?

**Comment by ramses-lopez** [comment]
Running into the same problem here. Trying to generate tests for a small rails controller. Maybe unrelated, but it's not taking the context into account when trying to generate the examples -- even when reusing prompts that worked before

**Comment by roblourens** [comment]
Can you share the requests/responses that led to this? You can right click on the chat rows and copy/copy all

**Comment by craftzneko** [comment]
Pasted an example for this in another logged issue that would apply here https://github.com/microsoft/vscode-copilot-release/issues/465#issuecomment-1772967444

**Comment by Ice-mourne** [comment]
One of the prompts which gives me this ``Sorry, the response hit the length limit. Please rephrase your prompt.`` 

Prompt:  
how can i insert div at carret position in content editable div

Response: 
Inserting a div at the caret position in a contenteditable div can be achieved using the Range and Selection APIs in JavaScript. Here's a function that does this:

```JS
function insertDivAtCaret() {
  const div = document.createElement('div');
  div.textContent = 'New div'; // Modify this as needed

  const sel = window.getSelection();
  if (sel.rangeCount) {
    const range = sel.getRangeAt(0);
    range.deleteContents();
    range.insertNode(div);
  }
}
```

In this function, a new div element is created and its textContent is set to 'New div'. Then, the current selection is obtained using window.getSelection(). If there is a selection (i.e., sel.rangeCount is not 0), the first range in the selection is obtained using sel.getRangeAt(0). The contents of the range are deleted using range.deleteContents(), and then the new div is inserted at the start of the range using range.insertNode(div).

You can call this function whenever you want to insert a div at the caret position. For example, you might

**Comment by lramos15** [comment]
Can you check your `Github Copilot Chat` output channel and tell me what you see?

**Comment by ramses-lopez** [comment]
@lramos15 
Prompt: `/tests`

Copilot's response:
```
Sure, here's how you might write tests for the #create and #destroy methods in the Api::V2::MediaController using Minitest:require 'test_helper'

class Api::V2::MediaControllerTest < ActionDispatch::IntegrationTest
  setup do
    @medium = media(:one) # Replace 'media' and ':one' with your actual fixture and object
    @user = users(:one) # Replace 'users' and ':one' with your actual fixture and user
    sign_in @user
  end

  test "should create medium" do
    assert_difference('Medium.count') do
      post api_v2_media_index_url, params: { file: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAAAAAAAD/2wCEAAkGBxMTEhUTExMWFhUXGB4YGRgYGB4eHhweGBgeHRgYHh8gICohGR0lHx8rITEiJSkrLi4uFx81ODMsNygtLisBCgoKDg0OGxAQGy8lICYvLzA1LTctMC0tLS0tLS0tLS0t


Sorry, the response hit the length limit. Please rephrase your prompt.
```

Extension output:
```
2023-10-20T20:28:55.471Z [INFO] [auth] Logged in as ramses-lopez
2023-10-20T20:28:55.837Z [INFO] [chat] copilot token chat_enabled: true
2023-10-20T20:28:55.846Z [INFO] [auth] Got Copilot token for ramses-lopez
2023-10-20T20:28:56.032Z [INFO] [auth] Logged in as ramses-lopez
2023-10-20T20:28:56.041Z [INFO] [chat] copilot token chat_enabled: true
2023-10-20T20:28:56.043Z [INFO] [auth] Got Copilot token for ramses-lopez
2023-10-20T20:29:42.934Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-10-20T20:29:42.934Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-10-20T20:29:42.934Z [INFO] [chat fetch] chat model gpt-4
2023-10-20T20:29:45.384Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2448 ms
2023-10-20T20:29:51.736Z [INFO] [streamMessages] message 0 returned. finish reason: [length]
2023-10-20T20:29:51.742Z [INFO] [streamChoices] request done: headerRequestId: [f2f020da-49f0-48ba-b6fa-844052910d12] model deployment ID: [x23f700076aa]
```

**Comment by lramos15** [comment]
@ramses-lopez Do you have a lot of history in your chat? How big is this ruby file?

**Comment by ramses-lopez** [comment]
> @ramses-lopez Do you have a lot of history in your chat? How big is this ruby file?

The ruby file is 37 lines long. The chat history is much longer (), as I don't clear it regularly -- after copying & pasting into a txt file I see it's 1360 lines long

**Comment by lramos15** [comment]
> The ruby file is 37 lines long. The chat history is much longer (), as I don't clear it regularly -- after copying & pasting into a txt file I see it's 1360 lines long

Thanks, I have a fix out for this, it'll be in the Monday's pre-release. In the meantime the solution is to clear your chat history.

**Comment by godisboy0** [comment]
Agree, that is really annoying!!

**Comment by jdkolassa** [comment]
@lramos15 Thanks so much for your prompt fix! I forgot the appreciation, but you deserve all of it.

**Comment by craftzneko** [comment]
Hi this doesnt seem to be resolved yet, did it get deployed?

**Comment by lramos15** [comment]
> Hi this doesnt seem to be resolved yet, did it get deployed?

Yes it has.

**Comment by craftzneko** [comment]
Ahh i am still getting the issue then clearing the chat does temp fix it

**Comment by lramos15** [comment]
> Ahh i am still getting the issue then clearing the chat does temp fix it

Examples would definitely help

**Comment by craftzneko** [comment]
I will update when it happens again

**Comment by richlysakowski** [comment]
I have the same problem repeatedly.  This is super annoying and unacceptable interruption in my workflow.  

Here is my prompt:


<prompt> Okay, let's start to convert the following SQL code for MySQL into SQL code for PostgreSQL:

"""
import packages
import mysql.connector from mysql.connector import errorcode import asyncio import json import pandas as pd

from mysql.connector import cursor

import global_content as gl_content

class DatabaseHelper():
  analysis_system = None
  cnx = None
  cursor = None
  
def __init__(self, system) -> None:
    
    # receive the context of analysis system
    self.analysis_system = system

    # define constant
    self.one_min_table = [
        "1min_ticker_premarket", 
        "1min_ticker_market", 
        "1min_ticker_postmarket"
    ]

    self.configuration()

def configuration(self):
    """
    Configure database settings for connecting to the MySQL database. 
    This method retrieves database configuration parameters, likely including 
    host, database name, user, and password, from a predefined configuration source.

    Returns:
        dict: A dictionary containing database configuration parameters, such as host, 
        database name, user, and password.

    Side Effects:
        - Accesses external configuration data, potentially from a file or environment variables.
        - This method does not directly interact with the database but prepares the necessary 
        configuration for subsequent database operations.
    """

    config = {
        'user': gl_content.DB_USER,
        'password': gl_content.DB_PASS,
        'host': gl_content.DB_HOST,
    }

    # create the cursor object
    self.cnx = mysql.connector.connect(**config)
    self.cursor = self.cnx.cursor(buffered=True)

    # create database if doesn't exist
    self.cursor.execute('CREATE DATABASE IF NOT EXISTS {}'.format(gl_content.DB_NAME))
    self.cursor.execute('USE {}'.format(gl_content.DB_NAME))

    # crate tables if doesn't exist
    # self.cursor.execute('''DROP TABLE IF EXISTS 1min_ticker_premarket''')
    self.cursor.execute('''CREATE TABLE IF NOT EXISTS 1min_ticker_premarket
      (symbol varchar(255), date_time varchar(50), open float, high float, low float, close float, volume int)''')

    # self.cursor.execute('''DROP TABLE IF EXISTS 1min_ticker_market''')
    self.cursor.execute('''CREATE TABLE IF NOT EXISTS 1min_ticker_market
      (symbol varchar(255), date_time varchar(50), open float, high float, low float, close float, volume int)''')

    # self.cursor.execute('''DROP TABLE IF EXISTS 1min_ticker_postmarket''')
    self.cursor.execute('''CREATE TABLE IF NOT EXISTS 1min_ticker_postmarket
      (symbol varchar(255), date_time varchar(50), open float, high float, low float, close float, volume int)''')

    self.cursor.execute('''CREATE TABLE IF NOT EXISTS ticker_volume_by_day
      (symbol varchar(255), date varchar(50), open_price float, high_price float, low_price float, close_price float, 
      total_volume_day_premarket int, total_volume_day_market int, total_volume_day_postmarket int, total_volume_day int)''')

    self.cursor.execute('''CREATE TABLE IF NOT EXISTS ticker_average_by_minute
      (symbol varchar(255), last_date varchar(50), latest_close float, average_volume_premarket int, 
      average_volume_market int, average_volume_postmarket int)''')

    self.cursor.execute('''CREATE TABLE IF NOT EXISTS runners_day
      (symbol varchar(255), time_of_day varchar(50), avg_min float, last_price float, volume int, price float, 
      change_volume float, change_price float)''')

    self.cursor.execute('''CREATE TABLE IF NOT EXISTS gappers_day
      (symbol varchar(255), last_price float, price_day float, price_change float, 
      change_percent float)''')

```
<RESPONSE>

```
import psycopg2
from psycopg2 import sql
import asyncio
import json
import pandas as pd

import global_content as gl_content 

class DatabaseHelper():
    
    analysis_system = None
    cnx = None
    cursor = None

    def __init__(self, system) -> None:
        
        # receive the context of analysis system
        self.analysis_system = system

        # define constant
        self.one_min_table = [
            "1min_ticker_premarket", 
            "1min_ticker_market", 
            "1min_ticker_postmarket"
        ]

        self.configuration()
    
    def configuration(self):
        """
        Configure database settings for connecting to the PostgreSQL database. 
        This method retrieves database configuration parameters, likely including 
        host, database name, user, and password, from a predefined configuration source.

        Returns:
            dict: A dictionary containing database configuration parameters, such as host, 
            database name, user, and password.

        Side Effects:
            - Accesses external configuration data, potentially from a file or environment variables.
            - This method does not directly interact with the database but prepares the necessary 
            configuration for subsequent database operations.
        """

        config = {
            'user': gl_content.DB_USER,
            'password': gl_content.DB_PASS,
            'host': gl_content.DB_HOST,
        }

        # create the cursor object
        self.cnx = psycopg2.connect(**config)
        self.cursor = self.cnx.cursor()

        # create database if doesn't exist
        self.cursor.execute(sql.SQL('CREATE DATABASE {}').format(sql.Identifier(gl_content.DB_NAME)))

        # create tables if doesn't exist
        self.cursor.execute('''CREATE TABLE 1min_ticker_premarket
          (symbol text, date_time text, open real, high real, low real, close real, volume integer)''')

        self.cursor.execute('''CREATE TABLE 1min_ticker_market
          (symbol text, date_time text, open real, high real, low real, close real, volume integer)''')

        self.cursor.execute('''CREATE TABLE 1min_ticker_postmarket
          (symbol text, date_time text, open real,
```
<<<Sorry, the response hit the length limit. Please rephrase your prompt.>>>

**Comment by paraserv** [comment]
This issue has recurred with Version: 1.86.0-insider and Github Copilot

**Comment by azurecloudexample** [comment]
Create a new session and again ask Copilot or type commands, and then it will work fine.
