### ISSUE TITLE
Don't include windows keyboard shortcuts in outputs when using Mac

### ISSUE THREAD

**Issue by MCKevmeister** [microsoft/vscode-copilot-release#50]
When I ask for keyboard shortcuts inside Visual Studio code because its not my normal editor, I get windows keyboard shortcuts. I agree that mac confused the world by not following the existing keyboard layout and making their own is a nightmare, however, there should be some logic possibly even in the system message prompt that notices what operating system the user is using and outputs instructions using OS specific keyboard shortcuts/menus. Even if I tell Visual studio code GitHub copilot chat that I am using mac, I still get windows specific commands

Steps to Reproduce:

1. Open GitHub Visual Studio Code GitHub Copilot Chat (VS code exclusive) on Mac
2. Ask for a keyboard shortcut in VS Code

**Comment by digitarald** [comment]
Examples for macOS, still showing Windows first:

> digitarald: What's the keyboard shortcut for opening the command palette?
> GitHub Copilot: The keyboard shortcut for opening the command palette in Visual Studio Code is `Ctrl+Shift+P` on Windows and Linux, and `Cmd+Shift+P` on macOS.

**Comment by sandersn** [comment]
For me, this happens when copilot suggests keyboard shortcuts as part of any answer.
