### ISSUE TITLE
Copilot Chat is Reading Local Files when Copilot is Deactivated in Local File System

### ISSUE THREAD

**Issue by stephenandary** [microsoft/vscode-copilot-release#501]
- VS Code Version: 1.83.1
- OS Version:  Ubuntu 22.04.3 LTS

![image](https://github.com/microsoft/vscode-copilot-release/assets/12686470/8e9eef46-4f18-4714-9bce-9798a0cf80e1)

Steps to Reproduce:

1. Ask Copilot chat some questions with files open, and Copilot not activated.
2. See file references it uses.

These lines of code are also note committed publicly yet, so the lines of code it returned don't exist anywhere but locally.

**Comment by LikeDreamwalker** [comment]
I have seen the same issue. Copilot will keep "using" this reference even if I close the file editor. But if I ask Copilot to read some of my files, like a specific file or function, it will say it is not allowed to do this.
I am not sure if this is an actual reference issue or just a UI issue, but whatever it is, it can bring some troubles when Copilot is reading some private or business files. I open another clear repo and use it in Codespaces to ensure it won't have a chance to read some sensitive files by accident.
I think it would be better if it could select reference files and even allow users to upload the reference file and turn off their use.

**Comment by stephenandary** [comment]
Thanks, @LikeDreamwalker for the workaround suggestion. I will try that for now, but the whole reason I pay for enterprise copilot is so I can do this all from the same window. 

I know it is not a UI issue, because it returns exact or nearly exact code snippets from my own files that were never committed and only lived locally. I am certain of this because those snippets included domains that I own and have been the sole owner of. 

I specifically purchase Copilot Enterprise so that I can have control over things like this (I don't want open source results - and preferably hope the model was not trained on oss code but uses oss code docs and maybe proprietary training data). 

I don't wish for specific results or code when working with chat, I am usually asking general questions in the hope of needing to read less documentation to get to what I need, or for a general example that I can modify and turn into my own. If I want something specific I will paste in code snippets explicitly. 

When I work with chat I expect that it respects my copilot settings, and it is deceiving when I see the icon in the bottom right indicate that copilot is not enabled globally or for specific files.

**Comment by roblourens** [comment]
Sorry for the confusion. We've changed the descriptions of the options to disable copilot to clarify that they are about disabling "copilot completions", not Copilot Chat. Copilot Chat may use your current selection or open editor, or when you use the `@workspace` agent, it will use more context from your workspace. There are some notes about that in the last set of release notes: https://code.visualstudio.com/updates/v1_84

**Comment by stephenandary** [comment]
@roblourens can you disable that?

**Comment by roblourens** [comment]
That's not possible currenlty

**Comment by stephenandary** [comment]
Understood, thanks for the information.
