### ISSUE TITLE
Copilot randomly started imposing limits on responses

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#504]
- VS Code Version:1.84.0-insider 
- OS Version: MacOs 14.0 (23A344)
- Logs:

Steps to Reproduce:

1. Ask a question

The code I was working through on Friday is "too long" to work with today. I do not know if this limit was introduced over weekend or if this is a bug, but this file I am working is not long by any stretch of the imagination and if this new limit is legit, it renders the product functionally useless. To be clear, we are talking about a file that is 47 lines long. I've been working with files three of four times that size with no problems.

**Comment by lramos15** [comment]
What version of the extension are you using? This was a bug that was introduced which should be fixed in today's version. `v0.9.2023102302`

**Comment by salientknight** [comment]
It just required a reboot... I'm not on v0.9.2023102302   I will test and reply with new results shortly thank you

**Comment by salientknight** [comment]
I am getting the same problem and it not only fails to finish, it greys out the response it was giving so I cannot use any of it.

**Comment by salientknight** [comment]
I switched to the release version and got the same issue

**Comment by lramos15** [comment]
Does clearing your chat history fix the issue?

**Comment by salientknight** [comment]
Thank you that seems to have solved the problem.

**Comment by lramos15** [comment]
> Thank you that seems to have solved the problem.

Glad to hear it, although ideally this shouldn't be necessary, and I thought I fixed this :thinking:

**Comment by salientknight** [comment]
It actually only partially helped. I am having to delete the thread repeatedly and I am still getting the error enough that it's disrupting my work flow. The way I get code segments from it not helpful and always clear where it's suggesting the updated code goes, so I need a full function or in some cases a full class. It's been working that way fine for weeks. Today, I cannot get the same work flow going. Every time I have to clear the thread I have to affectively start over and that is not a good work flow

**Comment by lramos15** [comment]
> It actually only partially helped. I am having to delete the thread repeatedly and I am still getting the error enough that it's disrupting my work flow. The way I get code segments from it not helpful and always clear where it's suggesting the updated code goes, so I need a full function or in some cases a full class. It's been working that way fine for weeks. Today, I cannot get the same work flow going. Every time I have to clear the thread I have to affectively start over and that is not a good work flow

Can you share your logs in the `GitHub Copilot Chat` output channel as well as an example chat flow  (right click chat + copy all)

**Comment by salientknight** [comment]
I had to delete the last broken response to start over...  the code being returned is about 147 lines long and it worked in a clean chat.  It's like that chat buffer is getting filled faster than usual

**Comment by lramos15** [comment]
@unclecode That's for the ghost text extension and not chat. And there's currently an active incident there https://www.githubstatus.com/

**Comment by unclecode** [comment]
> @unclecode That's for the ghost text extension and not chat. And there's currently an active incident there https://www.githubstatus.com/

Yes 👍 u're spot on! Btw, it's been half an hour that Copilot's been working! U never know how addictive these tools can be! Literally felt paralyzed without it. The irony? Been coding for over a decade & now, in just 1-2 years, I've become so dependent on this coding companion 😅
