### ISSUE TITLE
Better prompt/extension awareness

### ISSUE THREAD

**Issue by mangr3n** [microsoft/vscode-copilot-release#505]
I would love it if the Co-pilot LLM had better contextual awareness about how it's being prompted, and how the context is being shaped.  I would appreciate it, in fact I'd strongly recommend, that you modify co-pilot to be transparent about and informed reasonably about the structure of the plugin, and the nature of how the plugin prompts the LLM using my local code.

What prompted this was an episode in chat.  I asked if it could read my directories and generate a simple index.ts file for a directory, that unified the exports for the modules in a directory.  It responded that it couldn't read the directories of my project or my files.  I gave it a template and asked if it could generate a file like it.  It generated the code and the content was reflective of real files in my project.  It had the names of files I had just been working on, and the exports matched up with 3 files I'd recently looked at, and their file locations.

I then prompted it extensively to understand how it could say it couldn't read my files or see anything beyond my prompt, and at the same time have accurate information that matches my open files in the editor.  It alternated between saying it couldn't read my files, and insisting that I'd included that content in my prompt.  I then asked it to show me what it thought my prompt looked like.  After all, "if there's more in the context window, then show me the rest of it", I thought.  But no, "I can only see what you sent me in chat."  It diverted that question, and simply replied I can only see what you put in the chat window.

Eventually, it ended up spitting up this little tidbit, which feels closer to the truth.  
Me: "I didn't "provide" that excerpt, it was present in my text editor, and my chat was in a separate window. The Plugin provided that excerpt from my interface separately."

Copilot: "I apologize for any confusion. You are correct that the excerpt from DocumentImportError.svelte was provided by the VSCode plugin architecture. The plugin architecture provides contextual information to me based on the active selection in your editor."  

Well that's not exactly true.  That was the active file and the contents are only about 10 lines.  And none of it was selected, so the plugin is proactively choosing to send the file, or a portion of that file as context.

But Co-pilot should say true things about how it operates, and should be transparent.  It should either say, I don't know, or I can't tell you, OR truthful things about what it does.  Not doing so is a good faith failure IMO.

Attached is the entire interaction.

[mangr3n_copilot_interaction.md](https://github.com/microsoft/vscode-copilot-release/files/13077764/mangr3n_copilot_interaction.md)

**Comment by mangr3n** [comment]
FYI, I fully expected that portions of my code would be inspected, copied and sent over the wire with my prompts.  I even half expect that the co-pilot infrastructure would build some type of vector database about code from my project in order to efficiently and effectively make alterations or suggestions.  I also would expect those to be confined to my interactions and to be "garbage collected over time."  My issue was patently false claims or misleading claims from the LLM about our interaction and it's capabilities.  Either inform it of it's ignorance, tell it NOT to discuss the details and to be honest about it, OR to give it enough information to respond intelligently.

**Comment by fisforfaheem** [comment]
copilot updates should add better changelogs as well

**Comment by ulugbekna** [comment]
@mangr3 Thank you for filing this issue. We appreciate your feedback. Here's the issue for workspace awareness - https://github.com/microsoft/vscode-copilot-release/issues/14
