### ISSUE TITLE
Python's special dunder methods get rendered as bold text in chat window

### ISSUE THREAD

**Issue by miron** [microsoft/vscode-copilot-release#506]
- VS Code Version: 1.83.1
- OS Version: Windows 11 Pro 22H2
- Logs:

Steps to Reproduce:

1. type something like `__main__` in the chat window
2. needs to be escaped like this`\_\_main\_\_`
3. GitHub Copilot is not aware of this and gives wrong answers, i.e  `from xxx import main` instead of `from xxx import __main__`
4. Formating Python code to be rendered correctly in markdown is just not a viable option

**Comment by roblourens** [comment]
You can use a markdown codeblock. Agreed this can be unexpected:
 
https://github.com/microsoft/vscode-copilot-release/issues/107

**Comment by miron** [comment]
> You can use a markdown codeblock. Agreed this can be unexpected:
> 
> #107

I know I can, it’s not unexpected but a bug, it is a chat window, not a README.md. chatGPT, bing copilot,   literally everyone doesn’t render conversational text to markup.

**Comment by roblourens** [comment]
Yes, so I have an open bug for it
