### ISSUE TITLE
Se queda pegado

### ISSUE THREAD

**Issue by rafael180496** [microsoft/vscode-copilot-release#507]
- VS Code Version

se queda pegado al hacer preguntas

![image](https://github.com/microsoft/vscode-copilot-release/assets/27708711/e185d6dc-2ee1-4f0d-ac96-4c36687e1d26)

**Comment by digitarald** [comment]
We can check if there is a common theming issue. Meanwhile I recommend changing themes.

**Comment by daviddossett** [comment]
@rafael180496 what theme is this? It looks like a problem with the theme in general since I see that the text is dimmed elsewhere (status bar in this screenshot).

**Comment by daviddossett** [comment]
Actually, doing a quick google translate, this doesn't sound like it's about the theme. Could you update the issue in english if possible, please?

**Comment by digitarald** [comment]
My bad, the questions are removed in the screenshot and I mistranslated without checking.

Please post the full log and which answers you expected, @rafael180496 .
