### ISSUE TITLE
GitHub.copilot-chat-0.9.2023102501.vsix : Unable to install, not compatible with VS Code '1.83.1'. 

### ISSUE THREAD

**Issue by lextendo** [microsoft/vscode-copilot-release#508]
Simple error message in VSCode:
Unable to install extension 'github.copilot-chat' as it is not compatible with VS Code '1.83.1'.

Details:
- VS Code Version: 1.83.1
- Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
- Date: 2023-10-10T23:48:05.904Z (2 wks ago)
- Electron: 25.8.4
- ElectronBuildld: 24154031
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS Version: Windows_NT x64 
- Logs: N/A

Steps to Reproduce:
1. download GitHub.copilot-chat-0.9.2023102501.vsix
2. install using VSCode "Install from VSIX..."

**Comment by lramos15** [comment]
As the error states, that version of the VSIX is not compatible with the given version of VS Code. Installation through the marketplace is recommended as it handled pre-release vs release properly and that VSIX is a pre-release one. You can install it in the latest VS Code insiders.

**Comment by lextendo** [comment]
@lramos15 thanks for the reply. Much appreciated.
