### ISSUE TITLE
Unable to Delete Nonesistent Userdata

### ISSUE THREAD

**Issue by KrakenDev0001** [microsoft/vscode-copilot-release#51]
- VS Code Version: 1.79.0-insider
- OS Version: Windows_NT (Win 10) x64 10.0.19044
- Logs:
CoPilot Chat's Response to a Question I Asked About VSC:

Indexing, this should only happen once and takes about a few minutes...

Unable to delete nonexistent file 'vscode-userdata:/c:/Users/{username}/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/commandEmbeddings.json'

Steps to Reproduce:
Not sure, but I believe it thinks there's a file that exists when it does not. (Obviously, haha)
1. Don't have file
2. Try asking a VSC question using /vscode

**Comment by imperialmarch55** [comment]
Yep got that one too

**Comment by codezjx** [comment]
+1 with MacBook Pro M1 Pro, all quetions about /vscode is not working.

- VS Code Version: 1.79.0-insider
- Github Copilot Nightly v1.86.114
- GitHub Copilot Chat v0.1.2023052205

**Comment by lramos15** [comment]
This should be fixed now
