### ISSUE TITLE
Sorry, but I can only assist with programming related questions

### ISSUE THREAD

**Issue by elhadjiepitech** [microsoft/vscode-copilot-release#511]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

Ajouter une public static void main() pour tester ce code: import planet.*
....

Sorry, but I can only assist with programming related questions

**Comment by elhadjiepitech** [comment]
IDK  if it's a bugg

**Comment by fisforfaheem** [comment]
this shows up atleast 1/3 times

**Comment by axe-abhi** [comment]
its so annoying , even if i give it a program it does not respond correctly

**Comment by fisforfaheem** [comment]
Agree and i am Paying for. months and still no progress

**Comment by suharnikov** [comment]
Yeah. I get that error all the time. Can't use copilot. I canceled my subscription because I don't use its functionality because of its buggy settings

**Comment by sharonlo** [comment]
Hi all, thanks for your patience. We've deployed an update that addresses this. Please let us know if you're still hitting these issues!

**Comment by sdr0x07b6** [comment]
@sharonlo The problem persists. It is not always a problem, but once I get into that state, all I get is "Sorry, but I can only assist with programming related questions." I am obviously only talking about programming related questions.

**Comment by suharnikov** [comment]
I faced this issue again
![image](https://github.com/microsoft/vscode-copilot-release/assets/1702003/f4fd0a47-a885-4104-b5d0-f2b7676c7c5b)

**Comment by suharnikov** [comment]
It doesn't matter what kind of query I'm writing
![image](https://github.com/microsoft/vscode-copilot-release/assets/1702003/f05f4b77-9564-4368-ab25-e0211ebe03ad)

**Comment by fisforfaheem** [comment]
Kindly add experimental features enable option

**Comment by digitarald** [comment]
Closing for now, as a new offtopic detection got deployed and your provided questions pass. Please file new issues for follow-up reports with the specific questions that got filtered (redacted for any private details).

**Comment by hopk8** [comment]
I am running into the same issue. Almost every single question I ask gets replied with: "Sorry, but I can only assist with programming related questions."

**Comment by fisforfaheem** [comment]
also its context is way smaller than chatgpt which is free :(

**Comment by wheeler88** [comment]
> Hi all, thanks for your patience. We've deployed an update that addresses this. Please let us know if you're still hitting these issues!

still an issue in 2024, its an paid service people expect you to work on your service.

**Comment by fisforfaheem** [comment]
No, it has not. now having other bugs...login issue,,,then no
reply....slow...old flutter code being sugegsted

**Comment by dpk899** [comment]
03 May 2024. This is still and Issue. 

![image](https://github.com/microsoft/vscode-copilot-release/assets/142969958/bd533ec9-5d93-4e9a-bdba-c46bbc0577e8)

**Comment by fisforfaheem** [comment]
Agree same issue sometimes...we want to update

**Comment by cdkthno1118** [comment]
Also an issue here still. Please open this issue, it has not been solved.

**Comment by sdr0x07b6** [comment]
`Sorry, but I can only assist with programming related questions.` is repeated many times every day.

Also, he often answers by completely ignoring the context of what was just said.
I wish he would remember the context more.
At the very least, if it were possible to set the basic context in advance, like in ChatGTP settings, then the answer would make sense even if the context is not actually remembered very well.

Recently, it has been extremely slow to start outputting answers.
After waiting for several minutes, the HTML string of an error page was output. It included a base64 encoded image, so the HTML string was extremely long. It was several times longer than the attached image.
He says this at the beginning. What on earth are you talking about?
```
Hello future GitHubber! I bet you're here to remove those nasty inline styles, DRY up these templates and make 'em nice and re-usable, right? Please, don't.
```

Every day I wonder if GitHub Copilot engineers don't use GitHub Copilot themselves.

![504](https://github.com/microsoft/vscode-copilot-release/assets/1102138/065d4eed-daa9-4296-a150-fed1b07fef86)
