### ISSUE TITLE
Determine what framework the user is using before giving a suggestion

### ISSUE THREAD

**Issue by nemowbray** [microsoft/vscode-copilot-release#512]
When asking questions about my coding in playwright, co-pilot doesn't notice I have imported playwright and using the playwright framework, instead it gives suggestions based on jest.  

I would expect that it would be smart enough to notice what was imported in the file and then give suggestions based on what the user is using and if no framework is detected then default to whatever Copilot would prefer.  

I would suggest to default to playwright as its far superior to anything out there in my opinion

**Comment by jrieken** [comment]
* What version of the extension are you using?
* Do you already have any test file in the project?
* What is the naming-scheme of test files, foo.test.js or foo.spec.js or something else?

**Comment by nemowbray** [comment]
The issue is no longer there, all I did was restart vscode recently and now it's working much better than before.  A new update must have fixed my issue
