### ISSUE TITLE
`"github.copilot.chat.welcomeMessage": "never"` does not take effect

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode-copilot-release#517]
Version: 1.84.0-insider (system setup)
Commit: 35419fc016b8d3d5dbc59aa11a0be957b0897309
Date: 2023-10-27T10:41:08.734Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Add the following to the `settings.json`:

``` json
{
  "github.copilot.chat.welcomeMessage": "never"
}
```

2. Activate Copilot Chat.

* Note: I still see the welcome message at the top of the chat history even after reloading the window.

**Comment by joyceerhl** [comment]
The function of this setting value is to not show the _detailed_ welcome message, not to avoid showing a message entirely.
