### ISSUE TITLE
I can't help with that

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#522]
Copilot often gives code snippets that are fractured and so far out of context that they are not helpful. It will make a suggest that offers a function without specifying that the new function replaces the old. It will suggest one line as a change without providing the full context about where that line goes. There are several other issues like that. It will provide solutions that invite human error. 

My work around for this is to ask for full context. This morning, when I ask for that context I get "I can't help with that" And if ask for clarification I get a message that it's only able to provide fragments.  This is the latest is a series of what appears to be unreliable results. I cannot from day to day expect the same results from the same type of queries. Last week, I posted an error that it was running into a code length issue and this problem seemed to have resolved itself and now there is a new issue today.  I am paying for this service and I need reliable results. Arbitrary changes are not acceptable.  It's bad enough that the only feature that provides anything useful is the chat. None of the other services seem to work. It replaces the quick fix in the code editor and never works. None of the buttons on the main tool ever do anything useful. Code complete is a mixed blessing, so when I do find something that is working it's very frustrating that it's arbitrarily nerfed. 

- VS Code Version: Version: 1.84.0-insider
- OS Version: mac 14

Steps to Reproduce:

1. Ask copilot to provide full context.

**Comment by salientknight** [comment]
I want to add, that method of giving fragmented code also fails because it often requires a 3rd place to stash code while you stitch everything together. As I said, it invited human error, which is not helpful at all

**Comment by lramos15** [comment]
Do you have any example queries that could help diagnose this.

Have you tried the inline chat via `CTRL + I`?

**Comment by lramos15** [comment]
I've been unable to reproduce these cases and haven't heard back from you since November. Please feel free to open a new issue containing examples of the errors so we can better get to the bottom of it. Inline chat via `CMD + I` is the recommended way to edit code at this time. If the commands are not working properly excluding chat logs via `CMD + SHIFT + U -> Copilot Chat` is also super helpful. Ensure you're on the latest version of VS Code and Copilot Chat for the best experience. Happy coding!

**Comment by salientknight** [comment]
I'm not sure what I can add to this. It will give results with placeholder comments for example // your code but do this so many times in an answer that it invites human error.  Yesterday it suggested a change that was unlike anything in the body of the code I had shared with no context to know where to put it. (I am dealing with functions that similar enough that it might have gone in more than one place). Yesterday it also provided at least 30 deprecated solutions, wrong versions of functions and so on, where it usually doesn't. I know that is not related but it speaks to the general reliability of results. Yesterday for example every query I man needed 3 or 4 rounds of fixing, whereas 1 or 2 is the norm. I don't quite know why some days it makes so many more mistakes than others.  I guess you can close this ticket as I am not sure what the actionable is here. Thank you for listening.

**Comment by lramos15** [comment]
Do you have access to chatGPT? Do you see similar answers there? It might just be a model limitation and we're continuing to improve the model that powers chat. See https://github.com/microsoft/vscode-copilot-release/issues/560

And you haven't mentioned if you're trying the panel chat or the inline chat or both?

**Comment by salientknight** [comment]
ChatGPT and Bing give me a more consistent experience there are obviously some frustration built to all of it at the moment. I'm just finding the inconsistencies of the experience to be a bit much. All of the different AI seem to locked into circular reasoning — do A, ok that didn't work do B, ok that didn't work do A, but when you specify the version of the libraries you are working with and missing that var consistently in replies and provided deprecated solutions one day and perfectly workable solutions the next (working on a similar problem) It's a bit confusing.
