### ISSUE TITLE
Github Copilot Chat not working and panel is not showing up

### ISSUE THREAD

**Issue by chanon-mike** [microsoft/vscode-copilot-release#524]
- VS Code Version: 1.83.1
- OS Version: macOS Ventura 13.5.2

Problems:
- GitHub Copilot Chat is not appear in the sidebar. 
- When I click `copilot icon -> Github Copilot Chat`, nothing is happening. 
- When I tried `cmd + .` at the code, there are also no code action such as using `Fix with Copilot` or `Explain with Copilot` appear.

What I've tried
- Uninstall and reinstall copilot extensions
- Signout and re-signin account

Steps to Reproduce:

1. Click on the copilot icon at the bottom right, then click Github Copilot Chat
2. Press `cmd + .` button at the code for code action and

**Comment by austenstone** [comment]
Open the command prompt and type `copilot logs`.

Do you see something like this?
```
2023-11-01T20:24:41.101Z [INFO] [auth] Logged in as austenstone
2023-11-01T20:24:41.555Z [INFO] [chat] copilot token chat_enabled: false
2023-11-01T20:24:41.555Z [INFO] [auth] Got Copilot token for austenstone
```

**Comment by chanon-mike** [comment]
Here is my log
```
2023-11-02T02:01:03.168Z [INFO] [auth] Logged in as chanon-mike
2023-11-02T02:01:03.765Z [INFO] [chat] copilot token chat_enabled: false
2023-11-02T02:01:03.765Z [INFO] [auth] Got Copilot token for chanon-mike
```

**Comment by lramos15** [comment]
Do the in editor ghost text completions work for you? Based on your logs you do not have copilot access.

**Comment by chanon-mike** [comment]
Yes, ghost texting work. Only chat is not working. I have GitHub student which include copilot. 
It just remind me that I just joined the organization, when this happened. Does it related?

**Comment by lramos15** [comment]
Please try some of the steps in https://github.com/microsoft/vscode-copilot-release/issues/436 such as logging out and back in within VS Code

**Comment by chanon-mike** [comment]
Thank you for your response! I've tried all of those but nothing helped. I looked into Github Copilot settings and here is my settings.

I have my copilot on my own, but it seems like copilot from the organization overwritten my settings...
Are there anyway to prioritize my own settings over organization one?

<img width="958" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/27944646/6254526e-15fd-493f-9ecc-c76403b5eb99">

**Comment by lramos15** [comment]
> I have my copilot on my own, but it seems like copilot from the organization overwritten my settings... Are there anyway to prioritize my own settings over organization one?

There is not this is because there are different legal requirements for organizations than individuals so the most restrictive case is taken. Copilot is of course unable to distinguish between you using it on Individual vs Organization code and therefore the Organization always takes priority. You would have to get your organization to opt into the Copilot Chat beta.

**Comment by chanon-mike** [comment]
Thank you for your answer!!
