### ISSUE TITLE
Generated commit message style

### ISSUE THREAD

**Issue by MattJeanes** [microsoft/vscode-copilot-release#526]
I love the new auto generated commit message feature in the VSCode 1.84 release that's just come out.

What I would love to see to make it even better is the ability to customize the style of commit message, for example conventional commits: `ci: added yaml build definition` or `feat: added test controller` etc.

Some of our projects at work require conventional commits for example, and given that the underlying tech is just based on prompts I can imagine this being pretty easy to add with a prompt tweak.

It would be even more amazing if you could give it any style by having the option for a custom pre-prompt e.g. "Use conventional commit styling" or "Use relevant emojis at the start of the message".

A suggestion by @digitarald also is that VSCode could be aware of previous commit messages and copy their style too which I think is also a great idea.

Thank you!

**Comment by kaminskypavel** [comment]
adding for reference.
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by johan-lejdung** [comment]
This would be fantastic. The GitLens plugin has a VSCode setting to modify the prompt it uses to send to OpenAI, so I assume this would be quite simple to change for the prompt to CoPilot as well :)

**Comment by AliMD** [comment]
Any setting/hack for customize the prompt before sent?

**Comment by dasaqui** [comment]
I have the same need to use conventional commits

**Comment by edouardmisset** [comment]
Same here :)

**Comment by AhmedY0unes** [comment]
same here 🤞

**Comment by rafaelmfonseca** [comment]
same here 👈

**Comment by netdjw** [comment]
same here

**Comment by superlevure** [comment]
Please stop posting `same here`, we get it, VSCode team gets it, the world gets it and it triggers useless notifications for all

**Comment by netdjw** [comment]
> Please stop posting `same here`, we get it, VSCode team gets it, the world gets it and it triggers useless notifications for all

Sorry :) next time if you posting any answer "we get it", then you can keep calm folks of the Internet

**Comment by Sam-Lin-MillersLab** [comment]
@superlevure just said something everyone subscribed to this thread wanna said. I am surprised that some still don't know the community rules even they are on Github for such a long time. Maybe it should be a feature request for Github that repo can set a rule to block message like same here, +1 etc.

**Comment by phily245** [comment]
We use https://cbea.ms/git-commit/

**Comment by phily245** [comment]
> We use https://cbea.ms/git-commit/

This follows recommendations by git itself: https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

**Comment by michvllni** [comment]
> > We use https://cbea.ms/git-commit/
> 
> This follows recommendations by git itself: https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

What we are requesting is the possibility to follow [conventional commits](https://www.conventionalcommits.org/).

While the recommendations by git provide a valuable basis, conventional commits further increase the readability of commit messages.

Many teams use it because of its integration with semver to automatically generate version numbers via the commit types.

It is common practice to use conventional commits, thus it would be great if the copilot auto commits would also support it.

**Comment by benjefferies** [comment]
Adding a git commit prompt setting would give the flexibility to define the style of the commit message. This would allow users to choose their preference for the commit message format

**Comment by lwestfall** [comment]
> What we are requesting is the possibility to follow [conventional commits](https://www.conventionalcommits.org/).

Not to nitpick, but while the majority of us _do_ want conventional commit support, the issue as written is not specifically for conventional commits and only conventional commits. It's merely used as an example for a broader request to customize the prompt to support whatever style the developer prefers.

If @phily245 also wants to be able to support some other spec too that's fine.

**Comment by michvllni** [comment]
> > What we are requesting is the possibility to follow [conventional commits](https://www.conventionalcommits.org/).
> 
> Not to nitpick, but while the majority of us _do_ want conventional commit support, the issue as written is not specifically for conventional commits and only conventional commits. It's merely used as an example for a broader request to customize the prompt to support whatever style the developer prefers.
> 
> If @phily245 also wants to be able to support some other spec too that's fine.

Yes, sorry you are correct. It has been quite some time since I had this issue open last and I forgot it's not only about conventional commits

**Comment by leonardorocha-fluencyacademy** [comment]
Same here :)

**Comment by jcbowyer** [comment]
Adding my voice here as well, given that this issue has been outstanding for some time. I believe implementing this feature would significantly enhance the efficiency of numerous development teams, allowing us to allocate our time more effectively.

**Comment by MattJeanes** [comment]
The March update of VSCode includes improvements to this:

https://code.visualstudio.com/updates/v1_88#_commit-message-generation-improvements

> To improve the quality of the generated commit messages, we are now also including the commit messages of the 10 most recent commits in the repository, and the commit messages of the 10 most recent commits of the current user as extra context.

This is fantastic and will have to see how well this works. A custom prompt would still be useful but this will likely solve the issue in most use cases.

**Comment by kaminskypavel** [comment]
> The March update of VSCode includes improvements to this:
> 
> https://code.visualstudio.com/updates/v1_88#_commit-message-generation-improvements
> 
> > To improve the quality of the generated commit messages, we are now also including the commit messages of the 10 most recent commits in the repository, and the commit messages of the 10 most recent commits of the current user as extra context.
> 
> This is fantastic and will have to see how well this works. A custom prompt would still be useful but this will likely solve the issue in most use cases.

this is such a clever idea! i haven't tested it very thoroughly, but on the surface it seems to work! 
kudos! 🤗

**Comment by misaelmoreno** [comment]
The update represents an improvement without a doubt, but it would be incredible to be able to determine a custom pattern as context... for example, my company has strict rules like writing the commit in lowercase, including the ticket number, or not exceeding 100 characters. The message generation is perfect, but I need to fix a lot before I can commit.

**Comment by julien-blanchon** [comment]
[Gitbutler](https://gitbutler.com/) have a similar features that follow conventionalcommits. I think this would a very good improvement to vscode

**Comment by Jossec101** [comment]
This is really needed! A custom message would match each team's own way of writing commits

**Comment by movahhedi** [comment]
I don't know how, but GitHub Copilot is giving me conventional-commits-style messages today.

VSCode version: `1.89.1`
GitHub Copilot extension version: `v1.190.0`

**Comment by lexfrei** [comment]
@movahhedi it just checks last 10 commit messages and tries to mimic.

**Comment by jorismak** [comment]
So, for someone who wants to disable this? It now puts 'chore' in front of every message it generates :(.

**Comment by 1forh** [comment]
I'm getting the same thing. Doesn't seem to be looking at previous commits. It just uses conventional-commits-style.

**Comment by musuyaba** [comment]
> > The March update of VSCode includes improvements to this:
> > https://code.visualstudio.com/updates/v1_88#_commit-message-generation-improvements
> > > To improve the quality of the generated commit messages, we are now also including the commit messages of the 10 most recent commits in the repository, and the commit messages of the 10 most recent commits of the current user as extra context.
> > 
> > 
> > This is fantastic and will have to see how well this works. A custom prompt would still be useful but this will likely solve the issue in most use cases.
> 
> this is such a clever idea! i haven't tested it very thoroughly, but on the surface it seems to work! kudos! 🤗

![image](https://github.com/microsoft/vscode-copilot-release/assets/49295513/a4891605-5adb-46bd-9ced-0516ede313d7)
Oh, fantastic. The latest feature just reads the last 10 commits and spits out the same sentences. Sorry, this is genius 🙄

**Comment by tomerh2001** [comment]
Even with the last ten commits, it still sometimes generates an extremely long and weird commit message, for example:
```
Refactor lodash import in activity-ad-set.ts

The code changes in `src/models/mongo/activity-ad-set.ts` refactor the import statement for the lodash library. The unnecessary `type String` import is removed, and the import for the default lodash module is updated to use the correct syntax.

This commit message follows the established convention of starting with a verb in the imperative form and providing a clear and concise description of the changes.
```

It generated this redundantly long commit for this change:
```
Before:
import _, {type String} from 'lodash';
After
import _ from 'lodash';
```

This simple change to remove an unused import should not receive this long commit message. Also, we use conventional commits; all the previous commit messages follow that pattern, but the generated message doesn't adhere to them.

**Comment by derrix060** [comment]
I was able to improve how the commit messages are by adding this to my settings.json:

```
"gitlens.experimental.generateCommitMessagePrompt": "Now, please generate a commit message. Ensure that it includes a precise and informative subject line that succinctly summarizes the crux of the changes in under 50 characters. If necessary, follow with an explanatory body providing insight into the nature of the changes, the reasoning behind them, and any significant consequences or considerations arising from them. Conclude with any relevant issue references at the end of the message.  Make sure that the body is separated from the subject line by a blank line.  For more information, refer to the following resources:  - https://chris.beams.io/posts/git-commit/  - https://www.conventionalcommits.org/en/v1.0.0/.  Also, make sure the lengh of each line for the commit message is less than 72 characters.",
```

**Comment by jorismak** [comment]
That's a setting for GitLens. Are you sure it's working for copilot ? Or are you using GitLens ai-commit messages without realizing it ? 

(Yes, it could very well be that copilot uses the same setting key, I honestly don't know )

**Comment by derrix060** [comment]
<img width="415" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/14082769/f47b04dd-8d36-404e-b3f1-62b840e82657">


It just shows generate message with copilot.  Let me try disabling the gitlens extension and see what happens

**Comment by derrix060** [comment]
Yeah, this was for gitlens, sorry.  It would be really cool if copilot would expose the prompt so we could configure it

**Comment by Sam-Lin-MillersLab** [comment]
> Yeah, this was for gitlens, sorry. It would be really cool if copilot would expose the prompt so we could configure it

Thanks for testing it nevertheless

**Comment by PandaCoffeeBara** [comment]
Well with the knowledge that, github copilot does try to mimic the last few N number of commit message formats, If I enforce the project's commits to follow a format than soon the formatting won't be an issue, which in all honesty works for me

**Comment by caendesilva** [comment]
> Well with the knowledge that, github copilot does try to mimic the last few N number of commit message formats, If I enforce the project's commits to follow a format than soon the formatting won't be an issue, which in all honesty works for me

For me it's not at all mimicking the last commits. Would love to be able to modify the prompt context.

**Comment by JacobJNilsson** [comment]
> I was able to improve how the commit messages are by adding this to my settings.json:
> 
> ```
> "gitlens.experimental.generateCommitMessagePrompt": "Now, please generate a commit message. Ensure that it includes a precise and informative subject line that succinctly summarizes the crux of the changes in under 50 characters. If necessary, follow with an explanatory body providing insight into the nature of the changes, the reasoning behind them, and any significant consequences or considerations arising from them. Conclude with any relevant issue references at the end of the message.  Make sure that the body is separated from the subject line by a blank line.  For more information, refer to the following resources:  - https://chris.beams.io/posts/git-commit/  - https://www.conventionalcommits.org/en/v1.0.0/.  Also, make sure the lengh of each line for the commit message is less than 72 characters.",
> ```

This was not for copilot, but this is a great workaround. It is one more button press, but it does exactly what we wanted it to do. Thank you @derrix060 !

**Comment by derrix060** [comment]
> There is now [a precedent for steering the prompt for Copilot chat responses](https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_93.md#code-generation-instructions-experimental) via:
> 
> ```
> "github.copilot.chat.experimental.codeGeneration.instructions": [
>     {
>       "file": ".vscode/code-style.md" // import instructions from file `code-style.md`
>     }
> ],  
> ```
> 
> so perhaps we can have something like?
> 
> ```
> "github.copilot.chat.experimental.commitGeneration.instructions": [
>     {
>       "file": ".vscode/commit-style.md" // import instructions from file `code-style.md`
>     }
> ],  
> ```

I tried yesterday with the following prompt and it did not made any differences:

```
"github.copilot.chat.experimental.codeGeneration.instructions": [
        {
            "text": "When creating a commit message, ensure that it includes a precise and informative subject line that succinctly summarizes the crux of the changes in under 50 characters. If necessary, follow with an explanatory body providing insight into the nature of the changes, the reasoning behind them, and any significant consequences or considerations arising from them. Conclude with any relevant issue references at the end of the message.  Make sure the body is separated from the subject line by a blank line.  For more information, refer to the following resources:  - https://chris.beams.io/posts/git-commit/  - https://www.conventionalcommits.org/en/v1.0.0/.  Also, ensure the length of each line for the commit message is less than 72 characters. "
        },
    ],
```

**Comment by MattJeanes** [comment]
@derrix060 indeed that setting does not currently affect commit generation which is why @nathanchase is asking for a new setting for it: `github.copilot.chat.experimental.commitGeneration.instructions` - which I also think is a great idea!

Also note that it won't actually load up those URLs in your prompt when generating, but they may still be useful as it might be able to associate the URL with that format in it's training data.

**Comment by jd-solanki** [comment]
As a reference GitLense provides config for changing the prompt via: `gitlens.experimental.generateCommitMessagePrompt`

**Comment by MattJeanes** [comment]
This is now a feature in Visual Studio (not Code) in [17.12.0 Preview 3](https://learn.microsoft.com/en-gb/visualstudio/releases/2022/release-notes-preview?tabs=preview3#17.12.0-pre.3.0), so hopefully we'll also see this come to VSCode soon!

![Image](https://github.com/user-attachments/assets/7c13e7ce-ec1a-4648-8ed4-888434ac9ab6)

**Comment by maxisam** [comment]
@MattJeanes Technically you can use instruction with VSCode to do this as well. I am doing that now, but it doesn't always follow my instruction very well. Like I want an icon like 🐛 before "fix:" and I think it only does that when my copilot is in the right mood.

**Comment by lszomoru** [comment]
The next stable version of the Copilot Chat extension added support for custom instructions for generating commit messages though the `github.copilot.chat.commitMessageGeneration.instructions` setting. You can use the setting to specify a set of instructions or point to a file that contains the custom instructions. The custom instructions will be appended to the commit message generation prompt.

If you want to try this out now, you can install the Copilot Chat pre-release extension. 

Give it a try and let us know your feedback. Thanks!

**Comment by MattJeanes** [comment]
Amazing, thank you so much! 🚀 🎉

**Comment by doggy8088** [comment]
FYI.

![Image](https://github.com/user-attachments/assets/368f1b10-ee63-423c-9459-9f7a45171ff5)

**Comment by doggy8088** [comment]
> adding for reference. https://www.conventionalcommits.org/en/v1.0.0/

I think the Conventional Commits spec should be the default prompt for generating commit messages.
