### ISSUE TITLE
Indentation Error when generating Makefile code.

### ISSUE THREAD

**Issue by LiAuTraver** [microsoft/vscode-copilot-release#527]
the title above is self-explanatory. Say I asked Copilot to correct my Makefile error, the code he returned to me was pretty tricky, since the Makefile require actual tab characters, not spaces, which led to issues when copying and pasting code.
(Dunno Python also require an actual tab character, but py code works well. :P )

here is a simple Makefile indentation error:
##### the code shown below had been modified to avoid Markdown auto-conversion.

#Rule to build .o files from .cpp files
$ (OUT _ DIR)/ % : $ (SRC _ DIR) / %.cpp
&nbsp; &nbsp; &nbsp;	$ (CXX) $ (CXXFLAGS) -o  $@ $< -lncurses     // say this command requires a literal tab character, so the code copilot gave, in which he use space, dosen't work, although the space appears to be the same with tab in VS Code.

#Rule to clean up
clean:
&nbsp; &nbsp; &nbsp;	rm -f $(OUT_DIR)/*      // the question occurs repeatedly, same as above.

- VS Code Version:Version:  1.83.1 (user setup)
- OS Version:Windows 11 Pro Insider Preview, Evaluation Copy. Build 23570.1000 ni_prerelease

### Best wishes to Copilot! He's helped me loads!

**Comment by ulugbekna** [comment]
Hi @LiAuTraver ,

Thank you for using Copilot Chat and filing this issue! 

This should be fixed. If your file uses tabs, Copilot should generate tabs in the code it produces. Here's how to convert your file to use tabs: 

https://github.com/microsoft/vscode-copilot-release/assets/16353531/cd7c3d84-685f-4902-a627-c024972b444a

Let us know (with a gif, if possible) if this doesn't work!
