### ISSUE TITLE
`@workspace` can't find anything through my code base

### ISSUE THREAD

**Issue by alessandro-newzoo** [microsoft/vscode-copilot-release#529]
- VS Code Version: `1.84.0`
- OS Version: `macOS 13.6.1, GH Codespace running on VS Code Desktop`
- Copilot Chat: `v0.10.0`

Hello,
I was really excited about workspace codebase awareness, but I sadly can't make it work.

As you can see here, it doesn't find what I'm looking for, even though it's obvious from the search on the left that this var is defined somewhere.
I also don't understand the logic it's using to find the references. I've asked it to look into php files, and it looks into `composer.json` and the workspace file? How did it pick that one php file specifically, since I have dozens of other php files?

<img width="1343" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/47320294/48c46446-f37c-4573-b2ab-1684b4ed2427">

I then ran it a second time with different wording, completely different and random results:
<img width="612" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/47320294/e3a2b82a-e37b-47bc-8202-f597186d0cf0">

~~In case it's relevant, what you see is a multi-root workspace in a GH Codespace, on VS Code Desktop.~~
~~The multi-root workspace has two folders: `THEME` and `DDEV`.~~

**Update: same issue on a local single-root repo: https://github.com/microsoft/vscode-copilot-release/issues/529#issuecomment-1844867361**

**Comment by kcaswick** [comment]
I'm having similar issues in a single root, TypeScript JSX workspace. It only seems to be including selected text as context, even when I explicitly mention other files.

> REDACTED: `@workspace` Please compare the functions in ResourceDetails.fieldGroup.tsx and ResourceRequest.fieldGroup.tsx

> GitHub Copilot:
> Used 1 reference: Untitled-1:43-65
> I'm sorry, I can't answer that question with what I currently know about your workspace. I don't have access to your `ResourceDetails.fieldGroup.tsx` and `ResourceRequest.fieldGroup.tsx` files to compare the functions.

I also tried copying the relative path from an open tab, then trying to mention it while in another tab:
> REDACTED: @workspace /explain src\packages\\_relative path to file_\ResourceDetails.fieldGroup.tsx

> GitHub Copilot: 
> Used 1 reference: Untitled-1:43-65
> I'm sorry for any confusion, but as an AI, I don't have access to your local or remote files. Therefore, I can't directly analyze the file `src\packages\`_relative path to file_`\ResourceDetails.fieldGroup.tsx` that you mentioned.
> 
> However, I can certainly help you create a new component based on the general patterns used in React and TypeScript. If you could provide some details about what's in `ResourceDetails.fieldGroup.tsx`, such as the structure of the component, the props it takes, and how it handles state and events, I could provide a more accurate example.

**Comment by Joroze** [comment]
> "I'm sorry, I can't answer that question with what I currently know about your workspace. Please provide more information about your project structure or the files in your workspace."

This occurs for me when my VSCode has multiple workspaces open. It works fine when opening VSCode with a specific project, only.

**Comment by mjbvz** [comment]
@piotrpalek Please open a separate issue

**Comment by mjbvz** [comment]
@jhaisley From original issue text:

> In case it's relevant, what you see is a multi-root workspace in a GH Codespace

Open an separate issue

**Comment by alessandro-newzoo** [comment]
> Currently copilot isn't multi-workspace aware. I've updated the issue title to track this
> 
> By default it seems like we should search the entire workspace while potentially also providing a way to scope the question to individual workspace root folders

I have removed the 2nd folder from my workspace and I still face the same issue, so I doubt it's got anything to do with my workspace being multi-root.

<img width="1595" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/47320294/764275c2-3294-47a4-a13d-0c0d020a14da">
<img width="313" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/47320294/2d0a807b-c482-4eb6-bb0f-d496eecf9e07">

**Comment by mjbvz** [comment]
@alessandro-newzoo Thanks for checking. Can you share your project or a minimal example one? 

Also created a new issue for multi root support because that definitely won't work: https://github.com/microsoft/vscode-copilot-release/issues/645

**Comment by piotrpalek** [comment]
I have updated vscode today and all extensions, after that I've got a different error, something like "problem while collecting workspace data: failed" (sorry didn't copy). After that I've created a new chat by clicking the "+" icon on the top, and now it's working!

**Comment by Pager07** [comment]
fix for this issue: restart the chat. (worked for me)

**Comment by alessandro-newzoo** [comment]
> fix for this issue: restart the chat. (worked for me)

Appreciate the input but that does not fix it for me, obviously I have restarted the chat countless times in the month and a half after opening this issue.

**Comment by ZetiMente** [comment]
<img width="308" alt="Screenshot 2023-12-15 at 11 01 41 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/76985631/0084223e-03ce-40cd-b76f-94e51a560163">

Similar issue but here, the workspace can't determine what is a workspace is.

**Comment by mjbvz** [comment]
Please test out the next insiders release of the vscode-chat extension. There was a bug that caused php identifiers to not get tokenized correctly because they start with `$`

**Comment by kgnfth** [comment]
> > Currently copilot isn't multi-workspace aware. I've updated the issue title to track this
> > By default it seems like we should search the entire workspace while potentially also providing a way to scope the question to individual workspace root folders
> 
> I have removed the 2nd folder from my workspace and I still face the same issue, so I doubt it's got anything to do with my workspace being multi-root.
> 
> <img alt="image" width="1595" src="https://private-user-images.githubusercontent.com/47320294/288682797-764275c2-3294-47a4-a13d-0c0d020a14da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzMzMTAsIm5iZiI6MTcwMzk3MzAxMCwicGF0aCI6Ii80NzMyMDI5NC8yODg2ODI3OTctNzY0Mjc1YzItMzI5NC00N2E0LWExM2QtMGMwZDAyMGExNGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIxNTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ZWZlMTgzNTgxNzNmMzJiNDBhYjQwYjI2YjIzY2I0NTk2ZTE1MmMyNzJmYTNiOTlmZDQzN2M0NDM1ZjEyZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kE0m6YwoEhKY-R4gr_fKO79N4rgYJsBzXg-746Xg2SA"> <img alt="image" width="313" src="https://private-user-images.githubusercontent.com/47320294/288682976-2d0a807b-c482-4eb6-bb0f-d496eecf9e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzMzMTAsIm5iZiI6MTcwMzk3MzAxMCwicGF0aCI6Ii80NzMyMDI5NC8yODg2ODI5NzYtMmQwYTgwN2ItYzQ4Mi00ZWI2LWJiMGYtZDQ5NmVlY2Y5ZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIxNTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYzcyZGM1YTdjNDhlZjNlMGNmMzkyNTI4NGM0MDBhNTM5MmI3NGI5MTQ0MmNkZDQ0NzFjZjg5NTBhMmIwZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPjuJRtjNNb0akHeTXDc3Qp9WV3DtzpEfoKkHoxSDAc">
> ```
> 2023-12-07T08:12:01.754Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
> 2023-12-07T08:12:01.754Z [INFO] [chat fetch] modelMaxTokenWindow 4096
> 2023-12-07T08:12:01.754Z [INFO] [chat fetch] chat model gpt-4
> 2023-12-07T08:12:08.192Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 6437 ms
> 2023-12-07T08:12:10.286Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
> 2023-12-07T08:12:10.287Z [INFO] [streamChoices] request done: headerRequestId: [55dc51a7-ac4d-453d-bfce-386a92affd4d] model deployment ID: [x74a4b0e7ace1]
> 2023-12-07T08:12:12.565Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
> 2023-12-07T08:12:12.565Z [INFO] [chat fetch] modelMaxTokenWindow 4096
> 2023-12-07T08:12:12.565Z [INFO] [chat fetch] chat model gpt-4
> 2023-12-07T08:12:15.839Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 3274 ms
> 2023-12-07T08:12:17.085Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
> 2023-12-07T08:12:17.086Z [INFO] [streamChoices] request done: headerRequestId: [67930983-20f3-4c5e-9960-9d9ba81ffec3] model deployment ID: [x74a4b0e7ace1]
> 2023-12-07T08:12:17.201Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
> 2023-12-07T08:12:17.201Z [INFO] [chat fetch] modelMaxTokenWindow 8192
> 2023-12-07T08:12:17.201Z [INFO] [chat fetch] chat model gpt-3.5
> 2023-12-07T08:12:17.653Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 451 ms
> 2023-12-07T08:12:17.654Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
> 2023-12-07T08:12:17.654Z [INFO] [streamChoices] request done: headerRequestId: [60f325d9-550c-407c-83fb-9061f1459f76] model deployment ID: [x202bdb0a76e7]
> ```
> 
> I've also just tried with ALL extensions disabled except for Copilot, on a single-root **local** workspace, and I get the same underwhelming results:
> 
> <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/47320294/288709537-589e8cfd-5068-41b5-9dae-cc8816d880af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzMzMTAsIm5iZiI6MTcwMzk3MzAxMCwicGF0aCI6Ii80NzMyMDI5NC8yODg3MDk1MzctNTg5ZThjZmQtNTA2OC00MWI1LTlkYWUtY2M4ODE2ZDg4MGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIxNTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMDMwY2ZiMWYwYWYyNjYwOTAyM2E3MmEyYWQ0MGI3N2YyNDIyMGU5ZDBiMDg0NTFiNTMwY2EwYTc1MWM4N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HN_b9CpnXbYt6yPrB3BqV25HSr57DNXlxaGMTFwoViU"> <img alt="image" width="366" src="https://private-user-images.githubusercontent.com/47320294/288709487-8de39f92-456b-4bfe-9c8b-f83f604e6912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NzMzMTAsIm5iZiI6MTcwMzk3MzAxMCwicGF0aCI6Ii80NzMyMDI5NC8yODg3MDk0ODctOGRlMzlmOTItNDU2Yi00YmZlLTljOGItZjgzZjYwNGU2OTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDIxNTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkNDM5ODI0YTM0Y2IyMWU4MzdhMzAyNjBhZWM3MWYzZjFjZWM4ZjcxZmU5MDdiNmJhYTg2NTNkZDJmMzdjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jqFNXIfjv0cwZi7_a5mhwPyTM6ySx3BPo5jMgfjIGvs">
> ```
> 2023-12-07T09:40:04.095Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
> 2023-12-07T09:40:04.095Z [INFO] [chat fetch] modelMaxTokenWindow 4096
> 2023-12-07T09:40:04.095Z [INFO] [chat fetch] chat model gpt-4
> 2023-12-07T09:40:10.995Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 6900 ms
> 2023-12-07T09:40:11.843Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
> 2023-12-07T09:40:11.845Z [INFO] [streamChoices] request done: headerRequestId: [495af48b-d254-4707-b4ca-6d6ec92b2cd7] model deployment ID: [x74a4b0e7ace1]
> 2023-12-07T09:40:16.861Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
> 2023-12-07T09:40:16.861Z [INFO] [chat fetch] modelMaxTokenWindow 4096
> 2023-12-07T09:40:16.861Z [INFO] [chat fetch] chat model gpt-4
> 2023-12-07T09:40:20.935Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 4073 ms
> 2023-12-07T09:40:22.073Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
> 2023-12-07T09:40:22.074Z [INFO] [streamChoices] request done: headerRequestId: [80d83940-b951-4aa2-9d7e-4826919ef21c] model deployment ID: [x74a4b0e7ace1]
> 2023-12-07T09:40:22.183Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
> 2023-12-07T09:40:22.183Z [INFO] [chat fetch] modelMaxTokenWindow 8192
> 2023-12-07T09:40:22.184Z [INFO] [chat fetch] chat model gpt-3.5
> 2023-12-07T09:40:22.637Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 453 ms
> 2023-12-07T09:40:22.638Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
> 2023-12-07T09:40:22.638Z [INFO] [streamChoices] request done: headerRequestId: [339469fc-195c-42e3-a3a9-60c72d33239a] model deployment ID: [x202bdb0a76e7]
> ```

I'm curious about the VSCode theme and font you're using, it looks really cool. Could you please share your preferences?

**Comment by alessandro-newzoo** [comment]
@kgnfth hey sorry for the late reply I was on holiday!
The theme is https://marketplace.visualstudio.com/items?itemName=WollaceBuarque.tailwind-theme (I'm using the `Darkest` variation), and the font is `Hasklug Nerd Font Propo`: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/Hasklig.zip

**Comment by alessandro-newzoo** [comment]
> Please test out the next insiders release of the vscode-chat extension. There was a bug that caused php identifiers to not get tokenized correctly because they start with `$`

What version specifically?
I'm using Copilot Chat `v0.12.2023120701` (pre-release) and Copilot `v1.147.0` (stable) on Code `1.85.1`, and I still face the same issue.

I've also tried Chat `v0.12.2023120701` on Code `1.86.0-insider` , but it's been hanging on "Generating workspace info" for half an hour now

![image](https://github.com/microsoft/vscode-copilot-release/assets/47320294/293d1e41-54ca-430c-99bf-af51846e4b9f)


![image](https://github.com/microsoft/vscode-copilot-release/assets/47320294/2c62cff7-660c-405c-b15f-86ef4160ea77)

**Comment by mjbvz** [comment]
Please try updating. Those release are from early December of latest year. The current release is 0.12.2024010901

**Comment by alessandro-newzoo** [comment]
@mjbvz sorry I pasted the wrong version for Insiders, I'm indeed running Chat `v0.12.2024010901` on the latest Insiders and it hangs indefinitely on "Gathering workspace info".
I have all extensions disabled except for Copilot and Copilot Chat, and here's the output:

```log
2024-01-10 09:52:38.323 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-01-10 09:52:38.323 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-10 09:52:38.323 [info] [chat fetch] chat model gpt-4
2024-01-10 09:52:39.440 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1117 ms
2024-01-10 09:52:43.853 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-10 09:52:43.854 [info] [streamChoices] request done: requestId: [cae7d24e-5afb-4042-9f01-dfbdcefad63a] responseId: [6d858429-c61a-4f02-aefd-faafe061ba1a] model deployment ID: [wda6aab3977b]
```

**Comment by brentmjohnson** [comment]
same:
```
2024-01-13 14:37:44.432 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-01-13 14:37:44.432 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-13 14:37:44.432 [info] [chat fetch] chat model gpt-4
2024-01-13 14:37:45.125 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 693 ms
2024-01-13 14:37:46.801 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-13 14:37:46.802 [info] [streamChoices] request done: requestId: [2834dcb1-7b85-4f46-ab54-48c049850796] responseId: [3deec2bb-9be2-4a23-a7f8-cb40b3abb2b9] model deployment ID: [x8d3c95500d67]

```

**Comment by mjbvz** [comment]
@alessandro-newzoo Can you share an example project which causes this issue?

**Comment by alessandro-newzoo** [comment]
@mjbvz [the repo is private](https://github.com/newzoo-com/theme/) so I've added you to the contributors with `Write` access, but you're gonna have to accept the invite :)

thanks!

**Comment by kevinLourencoDev** [comment]
Hi, maybe the not yet released? I'm using the Pre-release v0.12.2024012301 and when I ask the chat: " what i can do with the @workspace command ? " the answer: 

> The @workspace command is a placeholder used in this context to represent actions or queries related to your current workspace in Visual Studio Code. However, it's important to note that @workspace is not a real command you can use in Visual Studio Code or any other IDE.
> 
> As an AI, I can assist you with various tasks related to your workspace, such as:
> 
> Answering general programming questions
> Explaining how the selected code works
> Generating unit tests for the selected code
> Proposing a fix for the problems in the selected code
> Scaffolding code for a new workspace
> Creating a new Jupyter Notebook
> Answering questions about VS Code
> Generating query parameters for workspace search
> Answering questions about VS Code extension development
> Guiding on how to do something in the terminal
> **However, I don't have the ability to directly interact with or manipulate your workspace.**

It's not look like it will be capable of doing anything with stuff that are not opened files...

**Comment by AA-ATL** [comment]
Something that worked for me was I had to first open a folder via "File" > "Open Folder" instead of just navigating to a given folder via the terminal cli.  This allowed "@workspace" context.

**Comment by mjbvz** [comment]
Quite a lot has changed since this was originally opened. I've been keeping this open mainly because there a number of different possible root causes of issues like this, some of which we have already addressed, some we potentially haven't, and some which we likely can't (such as ambiguous questions)

If you are still seeing any issues related to workspace knowledge, please open a new issue with an example codebase and question that we can use to reproduce the problem so we can investigate and continue improving the feature
