### ISSUE TITLE
/help initial Markdown section not rendering correctly

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-copilot-release#536]
- VS Code Version: 1.85 Insiders, Copilot Chat Pre-release
- OS Version: Windows 11
- Logs:

Steps to Reproduce:

1. Open Copilot chat
2. run /help

![image](https://github.com/microsoft/vscode-copilot-release/assets/12818376/220178b7-b5bc-4fbd-bed1-d1ea3a31bdec)

Looks like the initial Markdown section is being rendered as a code block. Doesn't repro on 1.84 stable with Copilot Chat pre-release

**Comment by joyceerhl** [comment]
I fixed this yesterday
