### ISSUE TITLE
/createWorkspace missing both on current and pre-release version

### ISSUE THREAD

**Issue by arun279** [microsoft/vscode-copilot-release#538]
- VS Code Version: 1.84.0
- OS Version: Windows 11 Home 22H2
- GitHub Copilot Chat version: tried both 0.10.0 and 0.9.2023103102

I am not able to see the /createWorkspace option anymore
![image](https://github.com/microsoft/vscode-copilot-release/assets/21064858/3fb43525-f4f7-4d6d-9c94-e5a606481184)

I tried both the latest version and the pre-release version
![image](https://github.com/microsoft/vscode-copilot-release/assets/21064858/32d0e73b-e90c-4d60-b0bd-600320618524)

My current build:
Version: 1.84.0 (user setup)
Commit: d037ac076cee195194f93ce6fe2bdfe2969cc82d
Date: 2023-11-01T11:29:04.398Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by gregvanl** [comment]
Changed to use the @workspace agent so now `@workspace /new`
https://code.visualstudio.com/updates/v1_84#_chat-agents

**Comment by arun279** [comment]
@gregvanl Thanks! It works with `@workspace /new` 
I did not know the feature had moved under a different name
