### ISSUE TITLE
Docs not clear around the extension not being compatible with VSCode. (VSCode Insiders is required)

### ISSUE THREAD

**Issue by osobytes** [microsoft/vscode-copilot-release#54]
- VS Code Version: 1.78.2
- OS Version: Windows 10 Pro version 22H2
- Logs: Logs in the Output for Github Copilot Chat are empty :(

**UPDATE:** I found these logs on the developer tools console:
Extension 'GitHub.copilot-chat CANNOT USE these API proposals 'interactive, terminalDataWriteEvent, semanticSimilarity, handleIssueUri'. You MUST start in extension development mode or use the --enable-proposed-api command line flag

So I assumed the problem was that I wasn't using VSCode Insiders.
I installed VSCode Insiders and tried it out there and it worked.
I've updated the title of the Issue.

**Steps to Reproduce:**

1. I have access to github copilot chat. I know this because I'm able to use it within Visual Studio.
2. I'm logged into my account in VSCode.
3. I have both GitHub Copilot and the GitHub Copilot Chat Extensions Installed.
[Expected] Pressing CTRL+I should bring the copilot chat view.
[Actual] Pressing CTRL+I brings up the completions box. I'm not able to find where the Copilot chat functionality is.

I searched through the settings, and couldn't find any way to enable the chat window.

**System Information:**
CPUs | AMD Ryzen 7 2700X Eight-Core Processor (16 x 3693)
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) |  
Memory (System) | 15.93GB (2.92GB free)
Process Argv | --folder-uri file:///d%3A/#REDACTED# --crash-reporter-id 72638b30-e45b-47b9-a753-b2a04083b73e
Screen Reader | no
VM | 0%

**A/B Experimentation Info:**
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
pythonms35:30701012
pythonfmttext:30731395
fixhidewlkth:30730051
hidesbindicator:30730055
pythongtdpath:30739704

**My current extensions installed: (obtained using code --list-extensions)**
Angular.ng-template
Azurite.azurite
bradlc.vscode-tailwindcss
burkeholland.simple-react-snippets
Dart-Code.dart-code
dbaeumer.vscode-eslint
eamodio.gitlens
GitHub.copilot
GitHub.copilot-chat
hancel.google-translate
humao.rest-client
Leopotam.csharpfixformat
mathiasfrohlich.Kotlin
mhutchie.git-graph
ms-azuretools.vscode-azurefunctions
ms-azuretools.vscode-azureresourcegroups
ms-azuretools.vscode-azurestaticwebapps
ms-azuretools.vscode-docker
ms-dotnettools.blazorwasm-companion
ms-dotnettools.csharp
ms-dotnettools.vscode-dotnet-runtime
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode.azure-account
ms-vscode.cpptools
ms-vscode.powershell
ms-vscode.vscode-typescript-next
platformio.platformio-ide
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
VisualStudioExptTeam.vscodeintellicode-completions

**Comment by digitarald** [comment]
I did clarify the readme for the extension. This will be further simplified this month.
