### ISSUE TITLE
Configuration Option for Ordering Copilot Suggestions in VS Code Quick Fixes

### ISSUE THREAD

**Issue by FrancoisJULIENNE** [microsoft/vscode-copilot-release#540]
![image](https://github.com/microsoft/vscode-copilot-release/assets/190781/d1e0538d-14b8-4376-a9d1-9bdee376c1b4)

### Description
The "Quick Fix" suggestions provided by GitHub Copilot in VS Code are currently displayed at the top of the list of possible actions. This can be disruptive for developers who prefer other default editor suggestions or fixes. The ability to configure the display order of these suggestions would enhance the user experience by allowing developers to customize their workflow.

### Requested Feature
Add a configuration option in VS Code that allows users to set the order of GitHub Copilot suggestions in the "Quick Fixes". Two settings could be offered: "On Top" to keep Copilot suggestions at the top of the list, and "On Bottom" to place them at the bottom.

### Benefits

- Increased Customization: Allows developers to tailor the user interface to their personal preferences.
- Improved Productivity: Reduces interruptions by prioritizing the correction tools more frequently used by the developer.
- Optimized User Experience: New users or those who prefer other corrections will not be confused by the placement of Copilot suggestions.

### Use Case Scenario
A developer working on a project finds that the Copilot suggestions dominate the first options in "Quick Fix". However, they prefer using the native suggestions from the VS Code editor and would like those to appear first. With the proposed feature, they could go into the settings and choose "On Bottom" for Copilot suggestions, making native fixes more accessible.

### Conclusion
This feature would significantly improve the experience of many developers using VS Code in conjunction with GitHub Copilot. It would add a welcome layer of customization to an already powerful tool.

**Comment by justschen** [comment]
@FrancoisJULIENNE what version of vs code are you currently on? This was addressed recently, so updating to the latest stable version should have an update for this.

atm, it will demote copilot quick fixes to the bottom of the list. @aiday-mar worked on this last iteration - maybe you can take a look and see if the setting is something you'd like to implement?

**Comment by FrancoisJULIENNE** [comment]
Thank you for the swift response and for addressing this feature request. I am pleased to hear that this has been implemented recently. I will update my VS Code to the latest stable version and check out this new setting. A big thank you to @aiday-mar and the team for your efforts!
