### ISSUE TITLE
Inline chat generates code in a json file

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-copilot-release#542]
1. Open inline chat in an empty file
2. Ask `edit this file to contain json, use tabs`
3. Retry a few times
4. :bug: JS is generated instead of JSON

**Comment by jrieken** [comment]
@joyceerhl what is the language of the document?

**Comment by joyceerhl** [comment]
It's an untitled document

**Comment by jrieken** [comment]
Yeah, I guess my question was if you have `files.defaultLanguage` configured or if the new file inherited a language from the active file?

**Comment by joyceerhl** [comment]
Hm, no, the new file is the active file, and I don't have the setting
