### ISSUE TITLE
Copilot status menu is too busy

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-copilot-release#545]
- VS Code Version: 1.84.1 Stable, Copilot stable
- OS Version: Windows 11

![image](https://github.com/microsoft/vscode-copilot-release/assets/12818376/2b867cae-2894-42fb-9f61-b6167eedb977)

Feels like a grab bag of Copilot links and features rather than a status menu. Should this menu be scoped to just helping users check status and enable completions?

Suggestions: 
Remove Edit Keyboard Shortcuts and Edit Settings 
Remove GitHub Copilot Chat and Open Completions Panel
Remove Copilot Forum

**Comment by gregvanl** [comment]
Adding @isidorn in case this needs to move to a different repo

**Comment by isidorn** [comment]
@smalllemur I think this belongs in the copilot-client repo. Could you grant @gregvanl access to it? Or would you like me to re-create this issue there? Thanks

**Comment by SmallLemur** [comment]
@isidorn @gregvanl i created a duplicate issue in the copilot-client repo: https://github.com/github/copilot-client/issues/4471

From the suggestion i would say that we can remove the Forum. 
The rest is based on user feedback and discoverability.

**Comment by isidorn** [comment]
Thanks for creating this issue. Thus closing this one.
Can you also make sure to invite @gregvanl to the other repo so he has access to that discussion>?
