### ISSUE TITLE
Silent failure to open Copilot Chat if organization policy is incorrect

### ISSUE THREAD

**Issue by mikkorantalainen** [microsoft/vscode-copilot-release#551]
Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:31.181Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-1016-lowlatency

View – Output – GitHub Copilot Chat shows following clue:
`
[INFO] [chat] copilot token chat_enabled: false
`

Steps to Reproduce:

1. Use a web browser to login to github.com using crendentials for organization admin
2. Go to organization page and click Settigs – Code, planning, and automation – Copilot – Policies and features
3. Look for "GitHub Copilot Chat for IDEs" in Features.
4. Make sure the value is "Disabled".
5. Add Copilot Chat to VS Code extensions
6. Click Github icon on bottom right (login if needed)
7. Click "Github Copilot Chat" in the menu that opens

Expected result:

VS Code should show a warning that says something along the lines "Your organization XYZ has configured a policy to disable the Copilot Chat feature." This could be implemented as opening the chat and the GitHub Copilot could say this message instead of the typical welcome message. And hopefully the Copilot could then help the user to configure the organization settings correctly, if the policy has been set incorrectly!

Actual result:

Nothing happens, no errors or warnings are emitted anywhere. The end user will be left guessing if the view has been opened to e.g. hidden sidebar or some other location but nothing can be found. The only clue is message `copilot token chat_enabled: false` in the Copilot Chat output which should be interpreted as "denied by organization policy", but that's very hard to know from such log message.

**Comment by mikkorantalainen** [comment]
Related:
Conflicting chat policies in two enterprise orgs results in no visible chat UI and no error message
https://github.com/microsoft/vscode-copilot-release/issues/438

**Comment by mikkorantalainen** [comment]
Related:
Solution: Chat view is not visible
https://github.com/microsoft/vscode-copilot-release/issues/436

**Comment by roblourens** [comment]
The change looks fine but any idea how to verify it @joyceerhl ?

**Comment by joyceerhl** [comment]
Short of creating a fake GitHub organization, no :/ we don't have a dummy one to test against either, last I asked @digitarald

**Comment by connor4312** [comment]
Looks okay via code review, I'll mark as verified pending any contraduction from @mikkorantalainen
