### ISSUE TITLE
Error: e.split is not a function

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-copilot-release#553]
- VS Code Version: 1.85 Insiders, Copilot Chat pre-release
- OS Version: Windows 11

Steps to Reproduce:

1. Open Chat view and select sparkle and proposed query "What are some best practices for writing clean code?":

Error: 'e.split is not a function`

![image](https://github.com/microsoft/vscode-copilot-release/assets/12818376/3a7474ef-f7c2-4466-a675-0ffa9b567fb5)

**Comment by gregvanl** [comment]
Also trying another suggested query:

![image](https://github.com/microsoft/vscode-copilot-release/assets/12818376/3b17d67a-fd47-4779-9eb9-a1f62ab726c2)

**Comment by ronelgazar** [comment]
I also encountered this problem, any idea why this happens?

**Comment by roblourens** [comment]
If you see this again can you share the Copilot Chat log, or check whether that error shows up in the Window or Extension Host output channels?

**Comment by gregvanl** [comment]
Here's the issue again https://github.com/microsoft/vscode-copilot/issues/3128 and includes a consistent repro

**Comment by pyrenaicus** [comment]
Hi there, I'm having the same issue when using the chat view on side panel only. Using quick chat, everything works fine.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/652 @pyrenaicus
