### ISSUE TITLE
sorry , the reponse hit the leng limit , please your rephrase prompt

### ISSUE THREAD

**Issue by DarklinuxFr** [microsoft/vscode-copilot-release#556]
- VS Code 1.84.1:
- OS debian 12.2:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by wuxiaotingco** [comment]
请问这个问题什么时候修复

**Comment by ulugbekna** [comment]
This happens because Copilot can take limited number of characters. This will improve in future.
