### ISSUE TITLE
Why is the previous conversation canceled?

### ISSUE THREAD

**Issue by NingishuAAA** [microsoft/vscode-copilot-release#557]
Why was the previous ai continuous dialog canceled and replaced with a set of fixed words.
I preferred the know-it-all tone or attitude of the previous one, can the developers develop two modes to switch between them? And can the support for Chinese be a bit longer now?
Thank you very much!

**Comment by aeschli** [comment]
Not sure what you refer to. Can you add a screenshot? That shows the dialog you are referring to?

**Comment by aeschli** [comment]
Closing the issue. I need more information to know what it is about.
