### ISSUE TITLE
Add an option to disable autocompletions from other extensions

### ISSUE THREAD

**Issue by sergiopani** [microsoft/vscode-copilot-release#558]
Autocomplete is very annoying in chat. It tries to complete me with options that are not useful, such as HTML tag suggestions when I am asking anything else. Could there be an option in VS Code to disable it?

The problem:
<img width="504" alt="Captura de pantalla 2023-11-09 a las 15 52 55" src="https://github.com/microsoft/vscode-copilot-release/assets/42542864/59f51afe-4197-4d6a-9599-72c9e111b744">

Solution: The option could be incorporated here
<img width="886" alt="Captura de pantalla 2023-11-09 a las 15 57 01" src="https://github.com/microsoft/vscode-copilot-release/assets/42542864/60456a8b-5a8a-45b4-a607-177eed9c9cf2">

**Comment by roblourens** [comment]
I think this should be fixed in VS Code Insiders, please let me know if not
