### ISSUE TITLE
[feat] : when to support floating window display ? 

### ISSUE THREAD

**Issue by weykon** [microsoft/vscode-copilot-release#559]
<img width=350 height=500 src="https://github.com/microsoft/vscode-copilot-release/assets/36456814/dab2e7c2-0f81-4f9f-8485-1b0057a67bbc"/>

I want to use this page as a floating window to make up for the regret that there is no copilot chat in neovim.   

Although copilot has released the latest CLI, which has the function of gh copilot explain, it is in the form of one shot, so it will take some time. .  

Then if this floating window supports it, I can freely adjust my window in the system, with neovim on the left and copilot chat floating window on the right.

**Comment by bpasero** [comment]
Moving a chat editor out into a floating window works for me without issues, but I know that we are working on this currently in https://github.com/microsoft/vscode/issues/197219

**Comment by aiday-mar** [comment]
Hey @bpasero @weykon thank you for commenting. The PR is currently on temporary hold as we are working on some other issues. I will let you know when that is finished.

**Comment by aiday-mar** [comment]
Hey all, I have started to look again at the PR, it is almost finished and will soon be sent for review.
