### ISSUE TITLE
No context about the project

### ISSUE THREAD

**Issue by Muchaszewski** [microsoft/vscode-copilot-release#56]
Currently, the project is very limited and saves me one copy-paste, not very useful. I expected when this would come out it would be able to see API of the whole project and help me with more complex questions.

Imagine having 2 files A and B. A inherits B.

Question to Chat:
`How to do X that uses a method from B`
Answer
`I'm sorry, but as an AI language model, I don't have access to your project files or any other information outside of the context you provide. Can you please check your project directory to see if there are any other files present?`

**Describe the feature you'd like.**
I expected to have a full vector database underneath to support more advanced queries that we currently cannot do with a normal copilot. Or manual prompting

Example:
 - `Please find a wrapper for X`
 - `Please write a method that uses class B`
 - `Implement interface that does X`
 
 and so on...

**Comment by daxtron2** [comment]
It would definitely be useful to at least have a way to provide context from multiple files instead of only one at a time.

**Comment by Hawdjer** [comment]
Yeah, that one would be game changer, provide Embeddings/Memory capability so it has awareness of whole project or use internally the GPT-4-32K model passing all the files related to the current one (required/usings/imports)...

**Comment by digitarald** [comment]
Duplicate of #32
