### ISSUE TITLE
Context Code Replacement In Copilot Chat

### ISSUE THREAD

**Issue by BeamoINT** [microsoft/vscode-copilot-release#561]
There should be a feature inside of Copilot chat where when it gives suggestions for long pieces of code, it typically puts comments inside of the code in places that don't need to be changed in order to be faster and save resources. What it should do is assign each changed piece of code to a certain part of the code to be replaced so that there can be a button that can be clicked in the new code snippet that replaces the entire relevant piece of code with the new changes even if the entire code wasn't written out by Copilot chat so that the developer does not have to go through that new code and just copy each individual piece of the code to the relevant section which can take a lot of time to find and go through as well as copy and paste. This is what Copilot inline chat currently does, this should be an option with a /command like /fix and /tests.

**Comment by lramos15** [comment]
I don't believe we plan to address this anytime soon. Chat is great for a conversational piece but mapping edits especially when they're not associated with any particular file is super difficult, this is why inline chat is our answer to the case of when a user wants Copilot to directly apply an edit to their codebase.
