### ISSUE TITLE
Allow selection of lines in shell for copilot to discuss

### ISSUE THREAD

**Issue by queglay** [microsoft/vscode-copilot-release#564]
When selecting a line in a shell in vscode, and pressing command+shift+I, It would be good if copilot could also comment on this and if its an error provide suggestions to fix it.

**Comment by joyceerhl** [comment]
This is already supported

<img width="963" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/30305945/46115f31-937a-4efa-9d12-e517189b396e">
