### ISSUE TITLE
Copilot chat giving [object Object] instead of code in VSCode

### ISSUE THREAD

**Issue by Roolingen** [microsoft/vscode-copilot-release#567]
Happens on VSCode insiders, Copilot Chat Preview and Copilot Chat Preview Pre-Release versions.
- VS Code Version: 1.85.0-insiders
- GitHub Copilot Chat version(s): v0.10.1 and v0.11.2023111302
- OS Version: Windows_NT x64 10.0.22631 (Win 11)
- Logs: [vscode-copilot-object-log.txt](https://github.com/microsoft/vscode-copilot-release/files/13345743/vscode-copilot-object-log.txt)

Steps to Reproduce:

1. Start VSCode
2. Go into Copilot Chat
3. Write something that provides code snippets, i.e. "What's the difference between built-in types such as decimal that start with uppercase or with lowercase letter?"

![image](https://github.com/microsoft/vscode-copilot-release/assets/24584330/ce4a3bfc-6a96-4130-9302-ff8ca6e504f1)

**Comment by iwangbowen** [comment]
Same here

**Comment by maxilirator** [comment]
Me to

**Comment by maimaid5669** [comment]
Same here

**Comment by ghostmou** [comment]
Same here:

- VS Code Version: 1.85.0-insider (Universal)
- OS Version: macOS Sonoma 14.0 and VS

**Comment by cshjin** [comment]
Installing the pre-release version helps me to resolve this issue.

**Comment by Roolingen** [comment]
Can agree this is now solved with `v0.11.2023111401`, however I see chat model has been downgraded from gpt-4 to gpt 3.5-turbo.
