### ISSUE TITLE
signin is not working 

### ISSUE THREAD

**Issue by kasinadhsarma** [microsoft/vscode-copilot-release#569]
The sign in page of chat is not working at my pop os i have installed through snap  can any one fix this issue 
![image](https://github.com/microsoft/vscode-copilot-release/assets/81065703/1f2f6820-2783-4d45-8806-9c5232e73b49)

![image](https://github.com/microsoft/vscode-copilot-release/assets/81065703/8c692b01-ba15-475f-9057-e069a825abec)

- VS Code Version:1.84.2
- OS Version: PoPOS

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Trigger the sign in
* _Wait for the issue to happen..._
* Open the Output pane (ctrl+shift+u I think on Linux)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel
