### ISSUE TITLE
Feature Request: Manage multiple conversation threads

### ISSUE THREAD

**Issue by chakravarthik27** [microsoft/vscode-copilot-release#57]
Copilot Chat is an innovative conversational tool designed to assist users in navigating and managing multiple conversations in a project-oriented manner. With its intuitive interface, Copilot Chat provides users with a seamless experience to effortlessly switch between various conversations while keeping them organized based on specific projects.

When using Copilot Chat, users can easily create distinct conversation threads dedicated to specific projects or topics. Each project thread acts as a container, allowing users to collate related discussions, messages, and interactions in one centralized location. This project-wise organization helps users maintain clarity and focus, ensuring that conversations and relevant information remain easily accessible and identifiable.

Additionally, Copilot Chat offers efficient navigation capabilities, empowering users to swiftly move between different project threads. Whether you need to review past discussions, refer back to critical details, or contribute to ongoing conversations, Copilot Chat streamlines the process by providing a clear overview of all projects and enabling quick transitions between them.

With its project-wise navigation and load functionality, Copilot Chat promotes collaboration, enhances productivity, and eliminates the hassle of managing numerous conversations across multiple projects. Whether you are working on team projects, client collaborations, or personal endeavors, Copilot Chat acts as a reliable companion, assisting you in effortlessly organizing and engaging with various conversations in a project-focused manner.

**Comment by digitarald** [comment]
Did you expand your description with ChatGPT? I shrunk it back using ChatGPT, let me know if I got it wrong @chakravarthik27:

> Navigate and manage multiple conversations in a project-oriented manner with Copilot Chat.

**Comment by chakravarthik27** [comment]
Actually, what happened was that if I opened a project and asked questions in the Copilot chat, the history was wiped after reopening the same project.

Anyway, let me double-check.

**Comment by chakravarthik27** [comment]
> Did you expand your description with ChatGPT? I shrunk it back using ChatGPT, let me know if I got it wrong @chakravarthik27:
> 
> > Navigate and manage multiple conversations in a project-oriented manner with Copilot Chat.

It seems good.
