### ISSUE TITLE
accept partial 'Start Inline Chat' suggestions.

### ISSUE THREAD

**Issue by NightmareZero** [microsoft/vscode-copilot-release#573]
Is it possible to accept only a part of the suggested modifications provided by 'Start Inline Chat' rather than accepting or rejecting all of them entirely?
Now, I can only accept all or reject all. Sometimes, the suggestions it provides are partly correct, while another part is entirely wrong.

**Comment by jrieken** [comment]
> by 'Start Inline Chat' rather than accepting or rejecting all of them entirely?

You can do that my making edits. The right hand side of the diff is editable and you can just go in and tweak the suggested edits. You can also use the arrows of the diff editor for parts that you want to undo again.  Like so 


https://github.com/microsoft/vscode-copilot-release/assets/1794099/1d04acc8-4213-4061-af6e-642aa1d47243

**Comment by NightmareZero** [comment]
I understand, but it feels counterintuitive.
Before seeing this video, I always thought that the arrow was "accept". It should be changed to a different icon.
