### ISSUE TITLE
No copilot chat icon in sidebar, no copilot chat window available, cant initiate copilot chat

### ISSUE THREAD

**Issue by pete312** [microsoft/vscode-copilot-release#575]
Chat icon does not appear in sidebar ( Enterprise license ).

- VS Code Version: 1.83.1
- OS Version: Oracle Linux 8 and Centos 7

I cannot see or a chat window.  The command `copilot chat` will not function either.  Also using the crtl + alt + shift + numpad minus -   key combo will not bring up any window.

I have had this work on the private license. Is this related to Enterprise license ?

**Comment by lramos15** [comment]
`CTRL + SHIFT + U` -> `Copilot Chat`

Paste the oput

**Comment by lgk-bsw** [comment]
I had the same issue, but I just fixed it. The feature "GitHub Copilot Chat for IDE" has to be enabled in the GitHub settings section.

**Comment by pete312** [comment]
I had notepad++ keybindings (ctrl shift U is uppercase for NP++) but disabling that cant see anything from that keybinding.  What is the full command for that ? 

Also, I think this maybe firewall related because a clue is; I can see the chat icon at home, but not at work. Any remote sessions from home to work, it disappears, whilst on all home remote sessions chat works.  Ill confirm if it's firewall, and update the ticket.  This seems to be silent behavior and would be helpful if it wrote something to console log.

**Comment by lramos15** [comment]
Very odd, glad to hear it's fixed 👍
