### ISSUE TITLE
Feature Request: Private and Public Bookmarks Collections

### ISSUE THREAD

**Issue by Hillsie** [microsoft/vscode-copilot-release#576]
Forgetfulness: Being human, I like to optimize my short term cache... synaptic pruning and chunking .... I forget... 😉️ So my hash lookup may be pruned and when I need a syntax, a command or code example and I can't recall it, I  end up requesting it again.

Basically, I seem to be requesting the same things over for various reasons

Thought it would be great if I could have a collection of bookmarks I can use for something I asked and have forgotten the exact syntax.

**Comment by lramos15** [comment]
I'm not sure I follow what you're looking for here. Can you do a rough mockup of steps of what you would expect so we can properly triage this issue

**Comment by Hillsie** [comment]
Sure.  The challenge I have with useful Copilot  code snippets is finding it in future. I end up trawling through Copilot history, and sometimes I might not find it at all,  so end up having Copilot generate it again or storing useful snippets offline.
The idea was that it would be helpful if the plugin had a bookmark feature that would help categorized and store snippets for future reference. Saves on  processing time and the good stuff isn't lost in history, nor is it stored offline. The ability to bookmark to a place like github gist would be useful.

**Comment by Hillsie** [comment]
for example, if a piece of code was generated and it was possible to bookmark it here
![image](https://github.com/microsoft/vscode-copilot-release/assets/17975287/70a2b44e-70f3-4173-9030-cb8389755b11)
