### ISSUE TITLE
Copilot Chat Generally Less Powerful Than The GPT4 Model Chat

### ISSUE THREAD

**Issue by MelbourneDeveloper** [microsoft/vscode-copilot-release#581]
- VS Code Version:

Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:57.054Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0

- OS Version: macOS Sonoma

Steps to Reproduce: Compare code chats between Copilot Chat and Chat GPT4

## Basic Issue

Copilot generally does not produce results as satisfactory as ChatGPT4. I use ChatGPT4 for all kinds of coding tasks, such as refactoring, writing tests, diagnosing bugs and so on. I haven't been able to achieve the same thing with Copilot. There are two reasons for this:

1) Copilot doesn't seem to allow me to take control of the context. There is no visibility of what context is getting sent to the model, and I can't control which files are getting sent. It seems like I can only send one file at a time.

2) Even when I do send a full file to Copilot it usually only answers with vagaries like "You should try 1. x 2. y 3." instead of pinpointing faulty line of code or even referring to the code I've written.

This problem is hard to document because it's not easily repeatable. You need to take the time to copy/paste your code into ChatGPT4. I made a video here with my app Context Note that allows you to take control of the context that gets sent to ChatGPT4. I explicitly selected the gpt4 model in the API, which I believe is the same model that we use in the ChatGPT website.

In this video, you see that the context is shared as a file `test.dart` between vscode and Context Note. The prompt I use in both apps is:

> Tell me about this code. Try to point to a line that has a bug

Look at the response from Copilot:

<img width="284" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/16697547/1b5e16a2-8e70-4941-b0aa-9dded05ae52a">

Now, look at the response from GPT4. It clearly enumerates several potential issues:
<img width="617" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/16697547/dd91f863-1241-4c28-8f19-5a8f76410678">

Here is the full video:

https://github.com/microsoft/vscode-copilot-release/assets/16697547/4a294d96-e7f0-4e2a-b034-c79a26b0f394

## Still Using ChatGP4

Even though I have Copilot, I'm still copy/pasting my code in to ChatGPT4, and I made my own tool Context Note for this reason. The video above is the general result I get when comparing Copilot to ChatGPT4. Saying all that, I have had some success with Copilot recently. Although, the lack of ability to control which files get sent as part of the context has reduced the usefulness of Copilot Chat.

I will log further videos here as I create them. This is mostly for reference.

**Comment by ManfredLange** [comment]
I noticed that when I activate a particular editor, then when I send the next prompt, Copilot appears to use the in that editor.

Furthermore, when I select a piece of code, then the selection will be included in the context as well. 

I'm not saying this addresses the concerns raised in this github issue. I merely wanted to share my observation in case someone else may find that tip useful. Meanwhile I deliberately make a particular editor active or select a piece of code before I write and send the next prompt. In my experience the responses seem to better using this approach.

**Comment by MelbourneDeveloper** [comment]
Yes, I'm not exactly sure what is happening under the hood. Sometimes I get better results than other times. Sometimes it seems like Copilot hasn't got any of my context at all. 

That's why we need the ability to see what we're actually sending

**Comment by roblourens** [comment]
We are now using gpt-4, this is a sort of recent change. If vscode and the extension are fully updated, you should have it.

> Copilot doesn't seem to allow me to take control of the context. There is no visibility of what context is getting sent to the model, and I can't control which files are getting sent. It seems like I can only send one file at a time.

If you use vscode Insiders, you will see variables which you can trigger with `#`, including `#file` which lets you include a full file. This is the route we are taking to give you explicit control over the context. However it's a bit rough currently which is why they are not enabled by default. Need more work here.

> Even when I do send a full file to Copilot it usually only answers with vagaries like "You should try 1. x 2. y 3." instead of pinpointing faulty line of code or even referring to the code I've written.

It's pretty hard to say why the model responds one way and not another. I'm hoping that with explicit context variables we will be able to give hints to the model so for better results. Also be sure to check out the agents and slash commands we have that provide better results for specific scenarios.
