### ISSUE TITLE
ieri ho comprato (cioè ha comprato mia zia) GitHub Copilot, ma non so come fare ad attivarlo (ho una sottoscrizione mensile), come lo attivo sul mio VS Code?

### ISSUE THREAD

**Issue by filatterio74** [microsoft/vscode-copilot-release#584]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by filatterio74** [comment]
VSCode Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

**Comment by filatterio74** [comment]
ieri mia zia mi ha comprato GitHub copilot ma non some attivarlo (ho una sottoscrizione mensile), come lo attivo od uso?

**Comment by filatterio74** [comment]
non posso scrivere quello che desidero scrivere, penso che ci siano problemi di policy

**Comment by filatterio74** [comment]
chat copilot v0.10.1

**Comment by lramos15** [comment]
Can you provide a screenshot / gif of your issue?
