### ISSUE TITLE
disable scrolling while generating answer

### ISSUE THREAD

**Issue by Shandelier** [microsoft/vscode-copilot-release#586]
Since chat is used in narrow column the generated text jumps one line every few words. It's hard to read when the text is moving.
I would suggest locking the window scroll by default when generating answer + adding some indicator that there is more text underneath.

**Comment by aeschli** [comment]
Is this about chat in the panel or in the editor?

**Comment by Shandelier** [comment]
in the panel:
<img width="368" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/26363920/451e557e-db53-44b0-9657-d95c6d32f662">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/138
