### ISSUE TITLE
(Error) Invalid progress type

### ISSUE THREAD

**Issue by idleworm** [microsoft/vscode-copilot-release#588]
- VS Code Version:1.85.0-insider
- OS Version:Windows 10
- Copilot Chat:v0.10.1
- Logs:[ERROR] [extension] (Error) Invalid progress type: {"responseId":"3140f0a2-e4a6-46b0-aa4b-c2251d6a4315"}

**Comment by Wenbobobo** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/585#issue-2001671481

**Comment by lramos15** [comment]
Duplicate #585
