### ISSUE TITLE
/vscode Tool in chat not working

### ISSUE THREAD

**Issue by mschoenb97** [microsoft/vscode-copilot-release#59]
- VS Code Version: Downloaded VSCode Insiders on May 20
- OS Version: Working on GCP Linux machine
- Logs: Error: ENOENT: no such file or directory, unlink '/home/"my name"/.vscode-server-insiders/data/User/globalStorage/github.copilot-chat/commandEmbeddings.json'

Whenever I try using the /vscode tool in the Github Copilot chat, I get the above error.

**Comment by skrln** [comment]
On windows 10 similar issue:

VS Code Insiders Version: 1.79.0-insider
Copilot Nightly version last released: 5/19/2023, 18:54:39

Input: `/vscode anything`

Output: 
`Unable to delete nonexistent file 'vscode-userdata:/c:/Users/skral/AppData/Roaming/Code - Insiders/User/globalStorage/github.copilot-chat/commandEmbeddings.json'`
