### ISSUE TITLE
Sorry, the response matched public code so it was blocked. Please rephrase your prompt. Learn more.

### ISSUE THREAD

**Issue by Rayatcoding** [microsoft/vscode-copilot-release#593]
#591 

![image](https://github.com/microsoft/vscode-copilot-release/assets/149446821/db3d0e3d-1e7b-49e2-ba2e-ab66b1fefd2d)

- VS Code Version: 1.84.2
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by ulugbekna** [comment]
duplicate https://github.com/microsoft/vscode-copilot-release/issues/583
