### ISSUE TITLE
Github error 

### ISSUE THREAD

**Issue by Kayla538** [microsoft/vscode-copilot-release#595]
I tried to code but everything I say it just says "Sorry, the response matched public code so it was blocked. Please rephrase your prompt." And I have to at allow please someone help.

**Comment by kynexis** [comment]
I'm also experiencing this.

**Comment by Kayla538** [comment]
How do you fix it?

**Comment by kynexis** [comment]
I don't think we can. The issue is on their end. Copilot might be entirely down. There are several issues opened up about the same error within the last 15 minutes.

**Comment by Kayla538** [comment]
Thanks for letting me know, hopefully, Github Copilot can start working again.

**Comment by K8sKween** [comment]
This should be closed as a duplicate #583

**Comment by TylerLeonhardt** [comment]
duplicate of https://github.com/microsoft/vscode-copilot-release/issues/583
