### ISSUE TITLE
all responses filtered.

### ISSUE THREAD

**Issue by paytriot45** [microsoft/vscode-copilot-release#596]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by slwhitman** [comment]
+1 "Oops, your response got filtered. Vote down if you think this shouldn't have happened."

**Comment by paytriot45** [comment]
at this point it is the only response the system will generate

**Comment by K8sKween** [comment]
I got this with a python file only containing `print("Hello World")` selecting the clicking "Explain This" if I open my chat window in the left hand side I see "Sorry, the response matched public code so it was blocked. Please rephrase your prompt." They must have done a bad push.

**Comment by eperry** [comment]
I am getting the same issue. was working 2 hours ago

**Comment by DiscoverProgramming** [comment]
Same here.

**Comment by eperry** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/6170692/33bf90a0-f0bd-420b-b403-8a5d5c5fc997)

**Comment by Svetloslav15** [comment]
Same here, It was working 1 hour ago.

**Comment by akhilesh84** [comment]
same issue for weeks in regular build of 1.84 but was working fine in insiders build.
Today it stopped working in that as well.
Will we get refund??

**Comment by K8sKween** [comment]
This should be closed as a duplicate of #583

**Comment by digitarald** [comment]
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/583
