### ISSUE TITLE
GitHub Copilot Saying "Sorry, the response matched public code so it was blocked. Please rephrase your prompt. Learn more." for every question I ask

### ISSUE THREAD

**Issue by DiscoverProgramming** [microsoft/vscode-copilot-release#597]
I was just working with GitHub Copilot on a project until it just kept replying with the Public Code Matched Error. I cannot ask anything without it replying with it.
![image](https://github.com/microsoft/vscode-copilot-release/assets/150089635/a58063fe-ca70-4a6b-b8c6-d5d0e51de425)

**Comment by h-kod** [comment]
This problem still persists for me.

**Comment by DiscoverProgramming** [comment]
No sorry, it still doesn't work for me either, I just closed it because I saw that this would be a duplicate issue.

**Comment by DiscoverProgramming** [comment]
Yeah, it was working around an hour ago but then stopped.
