### ISSUE TITLE
/help inline chat link doesn't work

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-copilot-release#598]
- VS Code Version: 1.85 Insiders, Copilot Chat pre-release
- OS Version: Windows 11

1. Bring up Chat view
2. Run /help
3. try to click the "starting an inline chat session" link

Inline chat isn't started in the open editor. Command ID `inlineChat.start` looks correct

![image](https://github.com/microsoft/vscode-copilot-release/assets/12818376/5be20569-4cbc-428f-aef3-75636da1fbe8)

Works with VS Code 1.84.2 and Copilot Chat stable

**Comment by jrieken** [comment]
@roblourens The `inlineChat.start` command cannot be used like this, it requires editor focus (and an editor...) I'd suggestion to add a special command that first focuses an editor (or creates an untitled one) and then triggers the command. I believe this should be done inside the extension

**Comment by roblourens** [comment]
@joyceerhl It doesn't seem helpful to open an untitled editor with the inline chat widget, should we have this just list the keyboard shortcut or tell users to click the sparkle button?

**Comment by joyceerhl** [comment]
This message only appears when the user has an active editor at the time that the chat welcome message is rendered, but of course it doesn't rerender when the active editor changes. I think we could go with listing the keyboard shortcut

**Comment by joyceerhl** [comment]
Oh, actually, this text is still owned by Copilot Chat, and I don't think we should hardcode the keybinding. We don't yet allow extensions to look up the keybinding for a command, though there have been several issues filed about this https://github.com/microsoft/vscode/issues/162433, https://github.com/microsoft/vscode/issues/196835. I actually have a RemoteHub use case for being able to lookup keybindings https://github.com/microsoft/vscode-remote-repositories-github/issues/366, I'll start an API proposal for that and remove the command link from the `/help` text in the meantime

**Comment by jrieken** [comment]
> We don't yet allow extensions to look up the keybinding for a command,

Shouldn't the markdown renderer simple insert keybindings? The MD refer to a command and all it takes is a lookup for the keybinding in the renderer. IMO no need for special API

**Comment by joyceerhl** [comment]
Do you mean to e.g. support the `kb()` syntax similar to how we add keybindings on the vscode-docs site? I would also like this tho I didn't think this was generally supported in markdown renderers. @mjbvz is supporting keybinding syntax in our markdown renderer something you'd be open to?

**Comment by joyceerhl** [comment]
Apparently GitHub uses `<kbd></kbd>` tags e.g. <kbd>Ctrl+Enter</kbd>

**Comment by joyceerhl** [comment]
Filed upstream https://github.com/microsoft/vscode/issues/199802

**Comment by roblourens** [comment]
I think he's saying that vscode/ChatListRenderer should be responsible for seeing that we rendered a command link, looking up the keybinding, and doing something to render it, like adding it to the tooltip. Or it could do something smart like append it into the link text like ` (cmd+i)`.

kbd rendering is supported by our markdown renderer, the markdown preview uses it, but all the fancy stuff is disabled in chat.

**Comment by joyceerhl** [comment]
Hm, I don't know if injecting that everywhere is going to lead to weird/unexpected behavior. I was thinking of supporting `kbstyle(inlineChat.start)` directly in the markdown renderer instead, since it's unambiguous that you'd want the label to be rendered there, and we'd also be able to use this in more places than just chat

**Comment by joyceerhl** [comment]
I got pretty far with supporting `kbstyle` and ran into the problem that the styles for our keybinding label renderer get stripped during markdown sanitization, and I don't think there's a way to allowlist specific styles using dompurify, so went with a scoped fix for chat as suggested

**Comment by jrieken** [comment]
> looking up the keybinding, and doing something to render it, like adding it to the tooltip

Yeah, I was thinking about the tooltip and not much more. 


@joyceerhl What are you planning, not really I can follow. Also, lets keep in mind that `inlineChat.start` is only useful when having an editor to begin with. Otherwise it's a noop (maybe command link rendering should also take enablement into account)

**Comment by joyceerhl** [comment]
We'll inject the keybinding in parentheses after the command link text now if a keybinding exists (in insiders after we release stable). The welcome message doesn't include the inline chat command link if there is no active editor, but the welcome message is only computed once and then restored from serialized state, so most of the time it is stale. Maybe we should update it when the active editor changes and/or always call the api for the latest data?
