### ISSUE TITLE
`"github.copilot.editor.enableCodeActions": false` does not disable code actions

### ISSUE THREAD

**Issue by Veykril** [microsoft/vscode-copilot-release#604]
- Copilot version: v1.138.568
- VS Code Version: 1.84.2
- OS Version: Windows_NT x64 10.0.19045
- Logs: n/a

I strictly use copilot for its autocompletion but I am not interested in any of its other capabilities. Yet since recently it seems to inject itself into the code actions panel when invoked with a selection active, but the corresponding config does not do anything.
![image](https://github.com/microsoft/vscode-copilot-release/assets/3757771/df229909-6001-4dd7-8bcd-20da893576c1)
As you can tell, this is disabled, yet I still get the code actions:
![image](https://github.com/microsoft/vscode-copilot-release/assets/3757771/fe9ed60a-242d-4674-bc42-8ff9b983bef4)

**Comment by ertankara** [comment]
It still isn't disabling anything, In the latest version 1.88 as well.

**Comment by aiday-mar** [comment]
Hi @ertankara thank you for posting this concern. I am currently not able to reproduce your issue, that is when I disable the Copilot code actions, I do not see the code actions in the menu either. 

https://github.com/microsoft/vscode-copilot-release/assets/61460952/2208a59c-6b90-4a48-8b35-aa8b777d3177

What version of the Copilot Chat extension are you using?  I am using the following version `v0.15.2024040501 (pre-release)`.
