### ISSUE TITLE
Advice: add "remember last order" feature for pop up copilot window

### ISSUE THREAD

**Issue by dbsxdbsx** [microsoft/vscode-copilot-release#606]
Currently, when using the pop up copilot with `ctrl+i`, it can't remember the last order.  In my case, I use a lot "format line by line", I hope every time except the 1st to use this order can be fast rechoosed by just pressing the arrow up/down key to switch the history order.

**Comment by jrieken** [comment]
> ... the arrow up/down key to switch the history order.

I can be done via `ctrl+up/down` and since very recent it actually persists across editor sessions. 

@dbsxdbsx What version are you using? Can you try vscode insiders?

**Comment by dbsxdbsx** [comment]
> > ... the arrow up/down key to switch the history order.
> 
> I can be done via `ctrl+up/down` and since very recent it actually persists across editor sessions.
> 
> @dbsxdbsx What version are you using? Can you try vscode insiders?

Thanks for your advice, with `ctrl+up/down`, it is workable.
