### ISSUE TITLE
Start Inline Chat no longer available in the command palette

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-copilot-release#609]
1. Open an editor
2. Open the command palette
3. Search for `Start Inline Chat`
4. :bug: no match

Maybe related to https://github.com/microsoft/vscode/commit/edc4698236d31fa84088b58e6f216d11acd8794b since the editor indeed does not have focus when the command palette is open

**Comment by aiday-mar** [comment]
Hi @joyceerhl thank you for the catch, it is likely as you mentioned related to that change. I will look into the code.

**Comment by aeschli** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/199371
