### ISSUE TITLE
welcome message inline chat link doesn't work

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode-copilot-release#616]
- VS Code Version: 1.85 Insiders, Copilot Chat pre-release
- OS Version: Windows 11

The link is using an obsolete command ID `workbench.action.quickchat.launchInlineChat`
Command ID should be `inlineChat.start`

![image](https://github.com/microsoft/vscode-copilot-release/assets/12818376/9be68a55-8ea2-4a66-b77f-dc5236dad303)

**Comment by joyceerhl** [comment]
We no longer include a command link since we cannot start an inline chat session if you don't have a file open already, the welcome message content is restored from history but if you click on the + you should see the newest content
