### ISSUE TITLE
Copillot uses files for reference even when not asked for it

### ISSUE THREAD

**Issue by cesarqdt** [microsoft/vscode-copilot-release#621]
- VS Code Version: 1.84.2
- OS Version: Darwin arm64 23.0.0

Steps to Reproduce:
When you ask for a question with any file open, copilot uses that file or a portion of that file for reference, even when the question has nothing to do with that file.
1. Open a dummy file
2. Type a question n the chat with copilot
3. wait until copilot shows "Used * reference <filename>"  in the answer.

I think this is a bug and should not use any files for reference if not asked for it. Attached is a screenshot of the issue, where copilot uses a file called "install.sh" which has nothing to do with a SQL statement that was asked.

![Screenshot 2023-12-01 at 13 58 52](https://github.com/microsoft/vscode-copilot-release/assets/97994493/3dff7b94-3b85-4363-ae43-8dd12af5e9ae)

**Comment by grant-singleton-nz** [comment]
I having this problem but with closed files.

I had the file open some time ago, I closed it and then had a long 'conversation' on an unrelated topic. Every time it would still say 'Used 1 reference' and refer to some lines in that file. Then occasionally it would answer a question assuming I was talking about the contents of the file.

**Comment by lramos15** [comment]
@grant-singleton-nz Your bug should be fixed if you're on the latest versions.


As for including the file, it's quite difficult to know when the user wants the file included and when they don't. We assume if you have a file open you're talking about it. We've tried to use the LLM to select context, but it's very hit or miss. Do you have a proposed solution?

**Comment by Richard-Weiss** [comment]
@lramos15 I'm having a similar problem with this default behavior. Would it be possible to have a command like @noReference or if you are adding a feature to add manual references like in Jetbrain's Plugin to have a toggle to add none?
Someone I have followup questions about a concept and it gets confused by the file reference.

**Comment by cesarqdt** [comment]
I have a suggestion, to use context if asked or when text is highlighted in
an open file.

**Comment by Richard-Weiss** [comment]
@cesarqdt I think wouldn't really work because it uses the editor view by default and I think most people like this default behavior.

**Comment by grant-singleton-nz** [comment]
> @grant-singleton-nz Your bug should be fixed if you're on the latest versions.

Thanks, that's working for me now

**Comment by roblourens** [comment]
We are getting rid of using your open editors with no selection as context automatically. We will start out doing this with an experiment where 50% of users will not get that context by default, and we'll see what the feedback is and probably roll it out from there.

Follow https://github.com/microsoft/vscode-copilot-release/issues/675#issuecomment-1899103384 for updates

**Comment by ChrisBoik** [comment]
I must be in the 50% of users having it no reference my open editor. I have become used to this and have no idea how to get it to reference it now, even when I explicility prompt it to 'consider the current open file'.
Is there a directive (command, @, etc.) I now need to use? Where can I find out when these things change

**Comment by roblourens** [comment]
You can use `#editor` to bring in that context manually. This is described in our release notes, https://code.visualstudio.com/updates follow that for updates

**Comment by dylanyoung-dev** [comment]
Still annoying to have this go away without warning, and not everyone will find this thread.  Maybe a little information should be placed where it was because I wasted tons of time to get it back (uninstalling the extension and re-installing, and tirelessly searching for it).  I can see the argument of having it used when you don't expect it, but now that users have gotten used to it being there (and how the current file is open, it drastically improves accuracy), and then it's not, then without the context, the prompts are almost useless, maybe more thought should've been put in to opt-out vs opt-in.
