### ISSUE TITLE
There should be a button or context menu to retry failed messages

### ISSUE THREAD

**Issue by NSExceptional** [microsoft/vscode-copilot-release#623]
<img width="410" alt="Screenshot 2023-12-01 at 1 25 18 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/89099176/e9c31de1-b68a-4647-a19e-141d6038fe9a">

**Comment by lramos15** [comment]
The goal is to not have failed messages at all :)

If you do get a failed message you can press the up arrow and hit enter to resend it. However, we hope this case is a < 0.1% occurrence and adding a UI element would be more of a crutch.

The error you're seeing above is likely some corporate proxy issue.

**Comment by NSExceptional** [comment]
The issue is my Wi-Fi was turned off. These things will happen and shouldn't be ignored. Calling it a crutch just sounds like you don't believe it will ever happen in practice
