### ISSUE TITLE
How to generate Chinese  commit message

### ISSUE THREAD

**Issue by wengshuang** [microsoft/vscode-copilot-release#628]
<img width="433" alt="image" src="https://github.com/microsoft/vscode/assets/80451560/a5f97b49-3eab-4259-816a-7811dfeeea26">

**Comment by lszomoru** [comment]
Please use the latest pre-release version of the extension. 
You can use the `github.copilot.chat.localeOverride` to control the language of the commit message

**Comment by doggy8088** [comment]
@lszomoru The `github.copilot.chat.localeOverride` won't change the default language for commit generation.

**Comment by lszomoru** [comment]
@doggy8088, thank you very much for giving this a try.
 Yes, at the moment this is only available in the pre-release extension.

**Comment by lszomoru** [comment]
Verification steps:
1. Launch the latest VS Code Insiders release
2. Ensure that you have the latest Copilot Chat pre-release extension installed
3. Make changes to some file(s)
4. Update the `github.copilot.chat.localeOverride` setting
5. Click the Sparkle action to generate commit message
    * Confirm that the commit message is generated for the selected locale
