### ISSUE TITLE
High CPU Usage and Errors in macOS After Enabling GitHub Copilot Chat

### ISSUE THREAD

**Issue by YouXam** [microsoft/vscode-copilot-release#633]
- VS Code Version: insiders 1.85
- OS Info: 
```
macOS Sonoma 14.1.2 (23B92)
CPUs | Apple M1 (8 x 24)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: enabled_on direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: enabled
Load (avg) | 4, 4, 4
Memory (System) | 16.00GB (0.33GB free)
Process Argv | --crash-reporter-id c40fb58f-e51d-4a6e-ac70-fae3c3a5f776
Screen Reader | no
VM | 0%
```
- Logs:
```
2023-12-04T16:58:57.297Z [INFO] [auth] Logged in as YouXam
2023-12-04T16:58:58.159Z [INFO] [chat] copilot token chat_enabled: true
2023-12-04T16:58:58.162Z [ERROR] [extension] GitHub Copilot could not connect to server. Extension activation failed: "X.interactive.onDidPerformUserAction is not a function"
2023-12-04T16:58:58.198Z [INFO] [auth] Logged in as YouXam
2023-12-04T16:58:58.199Z [INFO] [chat] copilot token chat_enabled: true
2023-12-04T16:58:58.199Z [ERROR] [extension] Could not register explain command: (Error) command 'github.copilot.interactiveEditor.explain' already exists
Registration of chat agents failed: TypeError: X.interactive.onDidPerformUserAction is not a function
2023-12-04T16:58:58.203Z [INFO] [auth] Logged in as YouXam
2023-12-04T16:58:58.204Z [INFO] [chat] copilot token chat_enabled: true
2023-12-04T16:58:58.204Z [ERROR] [extension] Could not register explain command: (Error) command 'github.copilot.interactiveEditor.explain' already exists
Registration of chat agents failed: TypeError: X.interactive.onDidPerformUserAction is not a function
2023-12-04T16:58:58.218Z [INFO] [auth] Logged in as YouXam
2023-12-04T16:58:58.219Z [INFO] [chat] copilot token chat_enabled: true
2023-12-04T16:58:58.219Z [ERROR] [extension] Could not register explain command: (Error) command 'github.copilot.interactiveEditor.explain' already exists
...
```

Steps to Reproduce:

1. Open vscode.

---

Hello GitHub Copilot Chat Team,

I am writing to report a significant issue I've encountered with the GitHub Copilot Chat extension on Visual Studio Code for macOS. Upon enabling the extension, I've noticed a rapid increase in CPU usage, which severely slows down the overall performance of VSCode. This issue is concerning as it hampers the usability of the editor.

Furthermore, the output console is continuously logging an error, which seems to be related to the extension. The error information is given above.

I was able to pinpoint this issue to the GitHub Copilot Chat extension using the Extension Bisect feature in VSCode.

Thank you for your attention to this matter.

---

<details>
  <summary>Other informations</summary>

## Extensions

Extension | Author (truncated) | Version
-- | -- | --
rust-bundle | 1Yi | 1.0.0
vscode-tailwindcss | bra | 0.10.3
arm | dan | 1.7.4
rust-syntax | dus | 0.6.1
gitlens | eam | 2023.12.204
esp-idf-extension | esp | 1.6.5
figma-vscode-extension | fig | 0.2.7
code-runner | for | 0.12.1
copilot-labs | Git | 0.17.1121
remotehub | Git | 0.62.0
go | gol | 0.40.0
marp-vscode | mar | 2.8.0
rainbow-csv | mec | 3.9.0
vscode-language-pack-zh-hans | MS- | 1.85.2023112909
isort | ms- | 2023.11.13191009
python | ms- | 2023.21.13351006
vscode-pylance | ms- | 2023.11.102
jupyter | ms- | 2023.11.1003351000
jupyter-keymap | ms- | 1.1.2
jupyter-renderers | ms- | 1.0.17
vscode-jupyter-cell-tags | ms- | 0.1.8
vscode-jupyter-slideshow | ms- | 0.1.5
remote-ssh | ms- | 0.107.1
remote-ssh-edit | ms- | 0.86.0
cmake-tools | ms- | 1.16.32
cpptools | ms- | 1.19.1
cpptools-extension-pack | ms- | 1.3.0
makefile-tools | ms- | 0.8.16
powershell | ms- | 2023.8.0
remote-explorer | ms- | 0.4.1
remote-repositories | ms- | 0.40.0
veriloghdl | msh | 1.13.0
typst-lsp | nva | 0.11.0
vscode-print | pdc | 0.11.18
csv-to-table | php | 1.4.0
LiveServer | rit | 5.7.9
rust-analyzer | rus | 0.4.1755
crates | ser | 0.6.3
markdown-preview-enhanced | shd | 0.8.10
even-better-toml | tam | 0.19.2
octave | toa | 0.0.3
pdf | tom | 1.2.2
cmake | twx | 0.0.17
errorlens | use | 3.15.0
volar | Vue | 1.8.24
vscode-typescript-vue-plugin | Vue | 1.8.24
vscode-wakatime | Wak | 24.4.0

(1 theme extensions excluded)

## a-b test

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
py29gd2263:30784851
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
showlangstatbar:30737417
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30901777
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30902439
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232
f11bh871:30912879
```
</details>

**Comment by lramos15** [comment]
What version of copilot chat?

**Comment by YouXam** [comment]
> What version of copilot chat?

The current latest version does not seem to be able to reproduce this bug.
