### ISSUE TITLE
AI specification config and permissions

### ISSUE THREAD

**Issue by caperaven** [microsoft/vscode-copilot-release#634]
I have deno tests but when I use the generate tests feature it assumes jest.
It would be nice to have some config file where you can instruct the AI on certain details about the project and give permissions.
For example that we use deno bdd testing and the test folder can be found at this location of the workspace. 
When generating tests it then understands that context.

This can also be used for other scenarios where you want to give access permissions and define parameters.

**Comment by jrieken** [comment]
What version of the extension/vscode are you using? Also do you already have any existing test file? Would it be possible to share you workspace (or a simplified version of that)
