### ISSUE TITLE
Allow us to control "what goes into" @workspace

### ISSUE THREAD

**Issue by JKHSDTV** [microsoft/vscode-copilot-release#635]
For me, the performance and usability of @workspace has been extremely poor and disappointing. While resources on the topic are hard to find, I suspect this may be because we have huge amounts of test data and snapshots in our workspaces, literally hundreds of MB, which I would not typically want to 'poison' the context. I would love a way to customize what is considered 'relevant context' somehow, even as simple as a settings entry that lets me specify a list of included/excluded glob patterns.

**Comment by mjbvz** [comment]
To make copilot ignore certain files:

- Add them to your `.gitignore` if they are temporary files that shouldn't be committed
- Create a `.copilotignore` file at the root of your project. This works just like a `.gitignore` and lets you specify globs that will be ignored
