### ISSUE TITLE
Latest features of Copilot Chat (GPT-4 support, #context, et) is not working. How can I fix that?

### ISSUE THREAD

**Issue by it-sha** [microsoft/vscode-copilot-release#636]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.84.2
- OS Version: Win 11 Pro 
GitHub Copilot Chat v0.10.2
GitHub Copilot v1.140.583

I am about features announced 04 Dec 23. Details here https://www.youtube.com/watch?v=SZVCJRUADc4 

What should I do to start using these new features if I already have Copilot and Copilot Chat extensions? Chat is still using GTP-3 which works much worse. Also, #context is not working.

Should I remove Copilot chat and reinstall Copilot?

Steps to Reproduce:

Check for #context 
1. Open Chat in VSCode
2. Type "#fileName" /explain for any existing file
3. See "I'm sorry, but I can't provide the explanation you're asking for because I don't have the TaskItem.vue file. Could you please provide the content of the TaskItem.vue file?"

Check for GPT-4
1. Open Chat in VSCode
2. Type What GPT version are you using?
3. See "As an AI developed by OpenAI and GitHub, I'm based on the GPT-3 model."

**Comment by Devfarz** [comment]
I installed it a week ago, but it shows GPT-3 version as AI model for me too, and non of those features in the video works. I also tried the pre-release version, but it still couldn't figure out how to use them.

**Comment by lramos15** [comment]
Please try VS Code insiders + Copilot Chat Pre-release.

**Comment by lramos15** [comment]
@mateuszmazurek First line in the GH blog https://github.blog/changelog/2023-11-30-github-copilot-november-30th-update/

**Comment by mateuszmazurek** [comment]
@lramos15 I've seen this, but there are many users reporting that it still uses GPT-3 🤔

**Comment by NeverioDev** [comment]
can't make #context to work
and it told it's still powered by GPT-3

**Comment by TheOnlyOne1987** [comment]
Having the same issue. In the log file it seems Copilot is using GPT-4 for some things. Than reverting back to 3.5 for others.

2023-12-05T17:08:05.018Z [INFO] [streamChoices] request done: headerRequestId: [6cd3d8d9-6712-44aa-b5a6-f2d1603798f2] model deployment ID: [x74a4b0e7ace1]
2023-12-05T17:08:05.858Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-05T17:08:05.858Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-12-05T17:08:05.858Z [INFO] [chat fetch] chat model gpt-4
2023-12-05T17:08:07.435Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1576 ms
2023-12-05T17:08:16.008Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-05T17:08:16.010Z [INFO] [streamChoices] request done: headerRequestId: [25206732-8bcb-444c-992a-57f75093d7b4] model deployment ID: [x74a4b0e7ace1]
2023-12-05T17:08:16.373Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-05T17:08:16.373Z [INFO] [chat fetch] modelMaxTokenWindow 8192
2023-12-05T17:08:16.373Z [INFO] [chat fetch] chat model gpt-3.5
2023-12-05T17:08:16.670Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 296 ms
2023-12-05T17:08:16.671Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-05T17:08:16.672Z [INFO] [streamChoices] request done: headerRequestId: [f306888a-c5f1-4ea0-b7fb-c1d95d65a856] model deployment ID: [x338b9c029b38]

**Comment by bulawow** [comment]
Got same problem github copilot chat is already in prerelease version on v0.12+ and i cant even install it

After clicking install prerelease-version it installs the latest released which is v0.10.2 where is even v11 ?
So much problems...

**Comment by lramos15** [comment]
@bulawow You must have insiders as well which has a green icon

**Comment by nevercast** [comment]
It looks like gpt-3.5-turbo is used for the automatic follow up questions at the bottom, so you'll see that model in the logs, even when Copilot Chat is using gpt-4 for the rest. 

I see that `#file` sometimes works, but not in the way I thought it would. I can't seem to get it to refer to many files at once. Perhaps that doesn't work yet. I'd love to be able to say:
> Refer to #file:new.service.ts and #file:readme.md to upgrade #file:old.service.ts to the new API format.

**Comment by Yazi27** [comment]
Is this fixed? I bought copilot because of the #context feature and its not even showing up, and yes I have the pre-release and @workspace is working.

**Comment by lramos15** [comment]
> Is this fixed? I bought copilot because of the #context feature and its not even showing up, and yes I have the pre-release and @workspace is working.

From all my confirmation there is no bug here. Please confirm you're on insiders and the latest pre-release (version should match today / yesterday's date). If you have specific bugs about a specific context not behaving properly please open a separate bug

**Comment by eduards-vavere** [comment]
You can use this command to check if it's 3.5 or 4. For me sometimes it's 3.5 other times 4

"I have 10 books, I read 2 books, how many books do I have left?"

8 books = GPT 3.5
10 books = GPT4

easy :)

**Comment by lramos15** [comment]
> I have 10 books, I read 2 books, how many books do I have left?
Are you saying GPT 4 gets the math wrong?

Here's a test using the Azure Open AI playground with the GPT 4 model 
<img width="717" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/02b257d9-32c1-428e-8f3a-b28fd0626ed7">
