### ISSUE TITLE
Copilot Chat is slow

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode-copilot-release#637]
_Originally posted by @rafales._ 

Sometimes the copilot chat requests take a lot of time to resolve. We should look into how to maximally reducing this time. @rafales mentioned the requests take so long, he would rather ask ChatGPT directly for an answer.

**Comment by nhattruong0000** [comment]
i have got same problem

**Comment by hidaris** [comment]
Is this because GPT-4 is slower than GPT-4 Turbo?

**Comment by alejoar** [comment]
Extremely slow for me as well since yesterday.

**Comment by Raulvalverdeleal** [comment]
Extremely slow for me too, yesterday also.

**Comment by lramos15** [comment]
Please share your logs via `CMD / CTRL + SHIFT + U` -> `GitHub Copilot Chat`

**Comment by alejoar** [comment]
@lramos15 here's a log:

```
2023-12-06T18:32:52.105Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-06T18:32:52.105Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-12-06T18:32:52.105Z [INFO] [chat fetch] chat model gpt-4
2023-12-06T18:32:52.105Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-06T18:32:52.105Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-12-06T18:32:52.105Z [INFO] [chat fetch] chat model gpt-4
2023-12-06T18:32:54.923Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2816 ms
2023-12-06T18:32:55.037Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2928 ms
2023-12-06T18:32:57.136Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-06T18:32:57.138Z [INFO] [streamChoices] request done: headerRequestId: [d0cbd06a-9ad6-45e8-be65-f78b57a0389b] model deployment ID: [x3b0892d9e5fc]
2023-12-06T18:33:00.243Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-06T18:33:00.243Z [INFO] [streamChoices] request done: headerRequestId: [98bf1327-2c06-42a8-9c1f-25fd3fe8bfc9] model deployment ID: [x3b0892d9e5fc]
2023-12-06T18:34:07.132Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-06T18:34:07.132Z [INFO] [chat fetch] modelMaxTokenWindow 4096
2023-12-06T18:34:07.132Z [INFO] [chat fetch] chat model gpt-4
2023-12-06T18:34:07.305Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-06T18:34:07.305Z [INFO] [chat fetch] modelMaxTokenWindow 8192
2023-12-06T18:34:07.305Z [INFO] [chat fetch] chat model gpt-3.5
2023-12-06T18:34:07.310Z [INFO] [chat fetch] engine https://api.githubcopilot.com/chat
2023-12-06T18:34:07.310Z [INFO] [chat fetch] modelMaxTokenWindow 8192
2023-12-06T18:34:07.310Z [INFO] [chat fetch] chat model gpt-3.5
2023-12-06T18:34:08.124Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 813 ms
2023-12-06T18:34:08.126Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-06T18:34:08.127Z [INFO] [streamChoices] request done: headerRequestId: [959453f2-01a0-4fc4-b9be-2728c161c598] model deployment ID: [x338b9c029b38]
2023-12-06T18:34:08.615Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1304 ms
2023-12-06T18:34:08.618Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-06T18:34:08.620Z [INFO] [streamChoices] request done: headerRequestId: [b411a205-0813-46ed-bcd8-e757a3de1bcb] model deployment ID: [x338b9c029b38]
2023-12-06T18:34:08.670Z [INFO] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1537 ms
2023-12-06T18:34:15.313Z [INFO] [streamMessages] message 0 returned. finish reason: [stop]
2023-12-06T18:34:15.314Z [INFO] [streamChoices] request done: headerRequestId: [ea32b584-98df-4ef2-9b31-9469a148d723] model deployment ID: [x3b0892d9e5fc]
```

A couple comments:
- I cleared all the logs and this is for a single query
- The time span in these logs is around 3 minutes, however before the first log message appeared I waited for around 1 minute

I recorded a video as well of the interaction, in case that helps. Let me know if you want me to upload that as well.

**Comment by lramos15** [comment]
> A couple comments:
> 
> * I cleared all the logs and this is for a single query
> * The time span in these logs is around 3 minutes, however before the first log message appeared I waited for around 1 minute
> 
> I recorded a video as well of the interaction, in case that helps. Let me know if you want me to upload that as well.

These logs are a bit weird. What version of the extension are you using? Does this happen all the time for you?

**Comment by alejoar** [comment]
@lramos15 I'm using version v0.10.2 Preview. 

Yes, it's happening all the time since the day before yesterday.

**Comment by lramos15** [comment]
> @lramos15 I'm using version v0.10.2 Preview.
> 
> Yes, it's happening all the time since the day before yesterday.

Can you try insiders and the latest pre-release? Then provide those logs as they have a bit more verbosity

**Comment by lramos15** [comment]
> I don't have time to install insiders right now, but I switched to the pre-release version.

Pre-release unfortunately doesn't work in stable. You're probably getting pretty much the same version you had before since they're pinned to a given VS Code version. I will try to see if I can reproduce at all in the stable builds, when you do have time to install insiders that would be greatly appreciated.

**Comment by lramos15** [comment]
> This is not exclusive to VS, Copilot is extremely slow to respond even if you go to through the browser, so seems like a server side issue.

How are you accessing copilot through the browser?

**Comment by luciferxiaozhi** [comment]
any suggestion on improving response time?

> [DEBUG] [proxy-socket-factory] [2024-01-10T09:52:14.765Z] Attempting to establish connection to proxy
[DEBUG] [proxy-socket-factory] [2024-01-10T09:52:14.766Z] Socket Connect returned status code,200
[DEBUG] [proxy-socket-factory] [2024-01-10T09:52:14.766Z] Successfully established tunneling connection to proxy
[DEBUG] [getCompletions] [2024-01-10T09:53:08.474Z] Requesting completion at position 36:1, between "class PassiveMoveSourceComponent : public Echo::NodeActorComponent\r\n{" and "\r\n    DECLAREACTORCOMTYPE_H(PassiveMoveSourceComponent);\r\n".
[INFO] [default] [2024-01-10T09:53:08.584Z] [fetchCompletions] engine https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:08.585Z] Attempting to establish connection to proxy
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:08.586Z] Socket Connect returned status code,200
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:08.586Z] Successfully established tunneling connection to proxy
[INFO] [default] [2024-01-10T09:53:09.723Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex/completions] took 1139 ms
[INFO] [streamChoices] [2024-01-10T09:53:09.723Z] solution 0 returned. finish reason: [stop]
[INFO] [streamChoices] [2024-01-10T09:53:09.723Z] request done: headerRequestId: [feb43cec-2b9c-4177-a6c9-81d51e018ec4] model deployment ID: [x1c5e8d1294d6]
[INFO] [RequestProposalsAsync] 0 completions available.
[DEBUG] [getCompletions] [2024-01-10T09:53:16.495Z] Requesting completion at position 39:7, between "\r\npublic:" and "\r\n    virtual void init(Echo::ActorComponentInfo* info) override;\r\n".
[INFO] [default] [2024-01-10T09:53:16.599Z] [fetchCompletions] engine https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:16.600Z] Attempting to establish connection to proxy
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:16.601Z] Socket Connect returned status code,200
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:16.601Z] Successfully established tunneling connection to proxy
[INFO] [default] [2024-01-10T09:53:17.578Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex/completions] took 979 ms
[INFO] [streamChoices] [2024-01-10T09:53:17.579Z] solution 0 returned. finish reason: [stop]
[INFO] [RequestProposalsAsync] 0 completions available.
[INFO] [streamChoices] [2024-01-10T09:53:17.579Z] request done: headerRequestId: [30070293-6dc7-499f-835d-fe9abb11b19d] model deployment ID: [x1c5e8d1294d6]
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:23.517Z] Attempting to establish connection to proxy
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:23.518Z] Socket Connect returned status code,200
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:23.518Z] Successfully established tunneling connection to proxy
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:24.731Z] Attempting to establish connection to proxy
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:24.732Z] Socket Connect returned status code,200
[DEBUG] [proxy-socket-factory] [2024-01-10T09:53:24.732Z] Successfully established tunneling connection to proxy

**Comment by lramos15** [comment]
@luciferxiaozhi Those logs are from Copilot and not Copilot Chat. This repository only focuses on the chat experience.

**Comment by ePaint** [comment]
I'm experiencing this issue too. It has not been fixed server-side. I used to be able to get +1000 lines of output in a few seconds. It is now taking over an hour to get 800 lines.

**Comment by mariuslacatus** [comment]
Yup, I'm about to cancel my subscription, not only Copilot chat is painfully slow, but most times it fails with the @workspace tag saying it can't access the workspace (intermittently), and 80% it gives me the wrong output anyways...

**Comment by liaozhangsheng** [comment]
> Yup, I'm about to cancel my subscription, not only Copilot chat is painfully slow, but most times it fails with the @workspace tag saying it can't access the workspace (intermittently), and 80% of the time it gives me the wrong output anyways...

This is most likely a network problem! I use copilot chat at home and have a quick reaction time, but when I use it at school, my reaction time is as slow as a turtle......

**Comment by ZackStone** [comment]
Same here, the copilot stays "Thinking" for a long time, even more than a minute sometimes.
In some cases, canceling the current request and sending it again do the trick.

**Comment by linonetwo** [comment]
<img width="516" alt="截屏2024-04-12 14 43 58" src="https://github.com/microsoft/vscode-copilot-release/assets/3746270/8bcd7f1e-77a7-4d14-a172-d624ebc5d2fd">

It stop here for 5 mins.

And I didn't see any webrequest in proxifier, is it really working for me?

<img width="978" alt="截屏2024-04-12 14 44 24" src="https://github.com/microsoft/vscode-copilot-release/assets/3746270/ad7ea52c-9625-4a53-be65-a01ca9914f28">

**Comment by lramos15** [comment]
@linonetwo Do you have any logs you can share via `CMD / CTRL + SHIFT + U ` -> `GitHub Copilot Chat`

**Comment by pavanmanideep** [comment]
Copilot Studio, mainly the Copilot is too slow, if this slow no one would use Copilot...you guys agree with me?

**Comment by linonetwo** [comment]
<img width="1573" alt="截屏2024-05-08 14 17 58" src="https://github.com/microsoft/vscode-copilot-release/assets/3746270/961a5484-f0d1-4de9-971b-f31edd508189">


@lramos15 It doesn't show log when `/fix` stucks. I've logined with a paid account.

**Comment by lramos15** [comment]
@Kobi-Blade Your comment was regarding https://copilot.microsoft.com/ which is a separate product all together backed by separate servers.

This issue is tracking `GitHub Copilot Chat`. We have made many improvements to improve the speed and haven't heard an update in this issue since May 16. If you're still having problems with the VS Code extension on the latest versions please attach logs as more has been added and describe your problem.

**Comment by lramos15** [comment]
@Kobi-Blade Can you provide your latest Copilot Chat logs on the latest version of the extension?
