### ISSUE TITLE
Session does not persist in WSL2

### ISSUE THREAD

**Issue by Aplietexe** [microsoft/vscode-copilot-release#64]
- VS Code Version: 1.79.0-insider
- OS Version: Windows 11 Pro 10.0.22621 Build 22621 + WSL2 Ubuntu 22.04.2 LTS
- Logs:

Steps to Reproduce:

1. Set up Copilot Nightly
2. Reload window or close current window and open a new one
3. You will be asked to sign in again

![image](https://github.com/microsoft/vscode-copilot-release/assets/52302877/5f93b858-e061-45d1-95eb-453ab9b96a68)

Output from Github Copilot Chat
```
[INFO] [auth] [2023-05-21T20:09:57.588Z] GitHub login failed
[ERROR] [default] [2023-05-21T20:09:57.594Z] You are not signed in to GitHub. Please sign in to use Copilot.
```

The same seems to happen with the Pull Requests extension.

**Comment by xV0lk** [comment]
Same issue here in:

VS Code Version: 1.79.0-insider (Universal)
macOs Ventura: 13.3.1 (a)

**Comment by digitarald** [comment]
@TylerLeonhardt is that an issue for core or extension related?

**Comment by TylerLeonhardt** [comment]
@Aplietexe can you give this troubleshooting doc a try? https://code.visualstudio.com/docs/editor/settings-sync#_windows

You say WSL2 but I'm assuming the VS Code UI is the Windows app and not the Linux app, yes? If so, follow the Windows troubleshooting steps.

**Comment by Aplietexe** [comment]
As of
- code-insiders 1.80.0-insider
- GitHub Copilot Chat v0.3.2023062302
- GitHub Copilot Nightly v1.92.182

the problem seems fixed.
