### ISSUE TITLE
Multi cursor - add suggestions to all cursors

### ISSUE THREAD

**Issue by elkir** [microsoft/vscode-copilot-release#640]
![image](https://github.com/microsoft/vscode-copilot-release/assets/20708119/b20625eb-7c74-48eb-93ba-6926449ebb69)

As seen in the picture above, the copilot suggestions are only applied to the first cursor of the multicursor.

Normally, multiple cursors are used to input the same text at multiple locations, so it would make sense to apply the suggestion across all of them. There is, of course, the caveat that the suggestion is tailored only to the first line and might not produce useful results for the consequent lines, and future multi-suggestion approach might be useful, but for now, just replicating the suggestion would be sufficient.

The current behaviour produces suggestions that go directly against the workflow of multicursor. The user has to either:
1) continue writing manually ignoring the suggestion (defeating the purpose of Copilot)
![image](https://github.com/microsoft/vscode-copilot-release/assets/20708119/a44a884f-cd69-4621-886d-5723035453e6)

2) if accepted require the user to abandon multi-cursor to continue writing the rest of the instances (defeating the purpose of the multicursor selection)
![image](https://github.com/microsoft/vscode-copilot-release/assets/20708119/226808d2-950b-48a4-a884-c84632882fc0)
![image](https://github.com/microsoft/vscode-copilot-release/assets/20708119/c05ba358-bf60-4828-8e2a-392eeff5c3ed)
![image](https://github.com/microsoft/vscode-copilot-release/assets/20708119/d40f3ee0-5c3d-49c8-b51f-c51e083ed0b0)

**Comment by lramos15** [comment]
This repo tracks Copilot Chat. This is copilot completions which should be filed here https://github.com/orgs/community/discussions/categories/copilot
