### ISSUE TITLE
[question] vs-code version compatibility - install chat extension error

### ISSUE THREAD

**Issue by cleancoda** [microsoft/vscode-copilot-release#642]
- VS Code Version: 1.84.20
- OS Version: Linux x64 6.1.0-13-amd64
- Logs: n/a

Copilot chat extension .vsix seems to be unsupported on vs-code versions 1.84.xx. However, base Copilot extension installs and runs perfectly fine.

Steps to Reproduce:
1. search extensions or download .vsix from https://marketplace.visualstudio.com/items?itemName=GitHub.copilot-chat
2. install .vsix file manually from vs-code
3. error occurs on install: ``Unable to install extension 'github.copilot-chat' as it is not compatible with VSCodium '1.84.2'.``

Question:
is there possibility of adding support for chat extension to work in versions 1.84.xx till current insider version goes live as main version? currently do not have access/permission to install insider on network. any suggestions are appreciated! 

Thank you for your amazing work! :)

**Comment by alessandro-newzoo** [comment]
I believe I have the same or a very similar issue, when activating the latest stable Copilot bundle, the chat extension would refuse to activate:

```
'workbench.panel.chat.view.copilot.focus' not found
```

what fixed it for me was to install the Pre-Release version of the chat extension:

<img width="283" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/47320294/4dd045f2-e346-4cb1-ae80-80aadf3ad5bc">

so I'm guessing and hoping the new stable version will support Code `1.84.2`

**Comment by alessandro-newzoo** [comment]
well scratch that, after reloading the window a couple of times I now get the same issue again even with the Pre-Release version.

**Comment by roblourens** [comment]
We don't officially support VSCodium
