### ISSUE TITLE
Extension activation failed: "Failed to get copilot token"

### ISSUE THREAD

**Issue by scyuan** [microsoft/vscode-copilot-release#643]
- VS Code Version:  1.84.2 (Universal)
- OS Version: Darwin arm64 22.4.0
- Logs: 
[INFO] [auth] Invalid copilot token: missing token: 500 
[ERROR] [extension] GitHub Copilot could not connect to server. Extension activation failed: "Failed to get copilot token"

**Comment by lramos15** [comment]
Are you still able to reproduce this? I don't believe we fail activation anymore if the token is not properly fetched. This also appears like a service error based on the 500 so should be fixed.
