### ISSUE TITLE
Copilot Chat Connected to Wrong Account

### ISSUE THREAD

**Issue by IEduStu** [microsoft/vscode-copilot-release#644]
I have 2 GitHub accounts connected to My VS Code. 
While I configure the extension to work with a specific account, it only connects to the account I sync my settings with (my personal account).

While I want it to connect to my work account.

Github copilot working as usual, only the **copilot chat** does not work properly

- VS Code Version: 1.84.2
- OS Version: macOS 14.1.2

Steps to Reproduce:

1. Sync your settings with a GitHub account that does not have access to GihHub Copilot
2. Sign in to GitHub Copilot with an account that has access to GitHub Copilot
3. Make sure in the settings that the copilot is supposed to use the work account

The solution I found is to sync the settings with a Microsoft account instead of a GitHub account.

I tried this multiple times, and every time I connect a sync account the Copilot chat stops working, with a message I need to buy Copilot

**Comment by TylerLeonhardt** [comment]
Multiple GitHub account support is tracked with https://github.com/microsoft/vscode/issues/127967
