### ISSUE TITLE
@workspace doesn't pick up multi root workspaces

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-copilot-release#645]
In a multi root workspace, `@workspace` will only check the first workspace root. We should support looking into all root while also potentially adding a mode to scope the question to a single root

**Comment by TylerLeonhardt** [comment]
This is old I'm pretty sure... but I'll go ahead and mark it for verification

**Comment by mjbvz** [comment]
This still doesn't work AFAIK. There's a lot of places where we assume we are talking about the first root

**Comment by TylerLeonhardt** [comment]
Ah. Sorry I was thinking only the context of codesearch which does support multi-workspace.

**Comment by mjbvz** [comment]
Should have fairly good support now. Can track individual issues separately
