### ISSUE TITLE
Add python code execution button to chat window for enhanced workflow productivity 

### ISSUE THREAD

**Issue by bschnurr** [microsoft/vscode-copilot-release#657]
I'd like copilot to generate python code to make code edits.

Goal:
I need to move/refactor a bunch of localization strings between two files `package.json` and `package.nls.json`
example here
![image](https://github.com/microsoft/vscode-copilot-release/assets/1946977/9441c14c-c591-4d50-8732-50ea46d2da8d)

##Things I tried:
Copilots completion suggestions in the `package.nls.json` was coming up the the correct format but it was also changing the loc string very slightly (subtle bugs) 

Then i tried asking it to make edits for me and it generated python code because it said it couldn't do it. 

"As an AI, I don't have the ability to directly edit your files. However, I can guide you on how to make the changes."
![image](https://github.com/microsoft/vscode-copilot-release/assets/1946977/63a809e1-94c1-4845-82f0-c4c605cc2b3d)

![image](https://github.com/microsoft/vscode-copilot-release/assets/1946977/dc7a2e2d-80be-4f8d-94fe-0192058cb5f1)

I would be nice to have copilot in excel/vscode/vs be able to execute generated python code from the chat window.   
We could also have Language server support on the copilot generated python code before it executes, along with a preview diff of resulting edits
 
  
Similar to this vid where George adds python execution to his chat output.
https://youtu.be/2QO3vzwHXhg?si=68omwxAytVuSpyhY&t=12391

**Comment by roblourens** [comment]
I think this is something that should be able to be handled without code execution, and somewhere there is an issue for improving cross-file edits and context like this. But enabling code execution is another solution and I'll keep this issue open for that.

**Comment by bschnurr** [comment]
Alternatively, looking at the recent text edits for a pattern and suggesting a code action could also work.
