### ISSUE TITLE
Response length limit

### ISSUE THREAD

**Issue by KaiyouS** [microsoft/vscode-copilot-release#658]
Please allow us to still see what Copilot wrote even when it hits the length limit. Because right now, if it hit's the length limit, it doesn't allow us to copy it, and even covers it. Thank you!

**Comment by paraserv** [comment]
Yes, this is really annoying and just wastes our time and the resources of GPT.

**Comment by roblourens** [comment]
I don't expect it to disable copy, etc when hitting the length limit. I think that would indicate a different type of issue. A screenshot would help me understand. Or the log from the Github Copilot Chat output channel

**Comment by KaiyouS** [comment]
Hi! Here are some screenshots. I can't copy anything inside the code block and it also get's covered by the gradient.


Beginning:
![image](https://github.com/microsoft/vscode-copilot-release/assets/143686622/a2cafafc-dec5-4b53-8032-ecca7585eec9)

Middle:
![image](https://github.com/microsoft/vscode-copilot-release/assets/143686622/61acd45b-243e-4182-a5c5-880e1a4a02e4)

End:
![image](https://github.com/microsoft/vscode-copilot-release/assets/143686622/d3d798a6-5e33-4f57-9482-e782e4348ad5)

**Comment by roblourens** [comment]
Hm, could you check that you have the latest versions of VS Code and the Copilot Chat extension?

**Comment by KaiyouS** [comment]
I just updated it today, but I don't know how to check the VS Code version on codespaces. But checking the conversation (the screenshots I sent) again, the gradient is still there and I still can't copy the code in the code block.

I'm trying to get Copilot to reach the response limit again to see if it is fixed on new conversations but I can't make it reach the response limit for now.

**Comment by roblourens** [comment]
This is an issue that was fixed a couple weeks ago, if you have the latest version of the extension it should be gone. Your screenshots show some extension updates available.
