### ISSUE TITLE
[BUG] 'Fix using copilot' feature fixes highlighted code not erroring code

### ISSUE THREAD

**Issue by wesleydpadilla** [microsoft/vscode-copilot-release#66]
- VS Code Version: Latest
- OS Version: Windows 10
- Logs:

Steps to Reproduce:

1. Get code that has an error
2. Highlight unrelated code
3. Open quick fix menu Ctrl+.
4. Press fix using copilot

It will 'fix' the code you have highlighted rather than the code with error.

**Comment by digitarald** [comment]
Was able to reproduce, thank you for the report.

**Comment by alexdima** [comment]
This has been fixed in the meantime.
