### ISSUE TITLE
In the prompt there should be intellisense to reference my classes/interfaces faster

### ISSUE THREAD

**Issue by rominator1983** [microsoft/vscode-copilot-release#660]
I was using VS code and I thought it would be nice to have some suggestions for the input as I have in the code window.
The prompt I was using was something like:
`write me a decorator for IPictureViewController that prints the name of the called method to the console.`

One could easily misstype the IPictureViewController so some suggestions would be great.
I would say some people might be annoyed by that. So probably that would be a feature that had to have a feature flag to be able to deactivate it.

**Comment by roblourens** [comment]
The great thing about LLMs is that if you have a typo or shorten the name, it will probably figure out what you mean. But we might also have intellisense for symbol names so that you can refer more precisely to a symbol.
