### ISSUE TITLE
GPT-4 in Inline Chat

### ISSUE THREAD

**Issue by BeamoINT** [microsoft/vscode-copilot-release#664]
GitHub copilot inline chat currently uses GPT-3.5 while the sidebar chat uses GPT-4. I really like the inline chat feature since it is convenient and easy to work with, but since it uses GPT-3.5, I choose to use the sidebar chat since 3.5 is not good enough for my needs. I think it would be great if the inline chat feature would use GPT-4 so that I can have the same level of power while having greater convenience in my workflow. (GPT-4 Turbo is coming out of preview soon and I also left another issue saying to add that so by saying to change inline chat to GPT-4, I really mean GPT-4 Turbo. I also get that you guys have a multi-model approach so, I also mean that you should have GPT-4 Turbo as an option of models to switch between, with it being the primary model).

**Comment by digitarald** [comment]
So far GPT-3.5 is picked based our benchmarks, where 3.5 is on par for reliability with GPT-4 for most inline chat and slash commands test scenarios. We'll keep evaluating though as we get access to new models.

Meanwhile it might be worth adding a switch.

Do you have an example for which GPT-4 works more reliable than 3.5?

**Comment by aiday-mar** [comment]
Hi @BeamoINT as @digitarald mentioned, currently we are exploring using a higher version of GPT for slash commands that require more complex work. We are investigating using GPT-4 for example for the /fix command. If this rolls out, we could consider adding a setting to switch between GPT-3.5 and GPT-4 for /fix. 

I am not sure if we will be using GPT-4 Turbo however.

**Comment by Anselmoo** [comment]
> GitHub copilot inline chat currently uses GPT-3.5 while the sidebar chat uses GPT-4. I really like the inline chat feature since it is convenient and easy to work with, but since it uses GPT-3.5, I choose to use the sidebar chat since 3.5 is not good enough for my needs.

In addition to this, the results for inline and sidebar strongly differ in accuracy and complexity. The sad point is you might want to fix or improve code line-wise but end up marking or copying the complete text into the sidebar chat and copying it back.

**Comment by kurutah** [comment]
> So far GPT-3.5 is picked based our benchmarks, where 3.5 is on par for reliability with GPT-4 for most inline chat and slash commands test scenarios. We'll keep evaluating though as we get access to new models.
> 
> Meanwhile it might be worth adding a switch.
> 
> Do you have an example for which GPT-4 works more reliable than 3.5?

Inline chat is almost useless for now, Idk what benchmarks it based on, I literally regret every time I try to use it

**Comment by Eianex** [comment]
I think it is time to switch to `GPT-4` for inline code predictions (non turbo version), the inline-chat is just annoying and will become obsolete the moment the inline code predictions start using `GPT-4`'s power. Also, give the Github Copilot the ability to directly edit file/s by itself when prompted by the user, it does not make any sense that it can read your entire workspace but can not edit it. It is nerve-racking. Thanks for the current work and I hope that the new Blackwell stuff from our taiwanese dude from Nvidia helps you guys implement `GPT-4`'s full potential. Cheers.

**Comment by digitarald** [comment]
@nonoash please file a new issue with a test case and we can make sure to cover in our automated benchmarks

**Comment by kurutah** [comment]
Any news?

**Comment by tats-u** [comment]
Why doesn't Inline Chat even use the GPT-4o mini today? 
We don't need stale models (GPT-3.x based) that don't know of the current Prime Minister of Japan.
Training data of all GPT-4 based models including the current Bing Chat is much newer than that of GPT-3.x.

**Comment by kurutah** [comment]
openAI devs say:

"We recommend choosing gpt-4o-mini where you would have previously used gpt-3.5-turbo as this model is more capable and cheaper."

I wonder if Github Copilot team needs further evaluations for next months though :/

**Comment by digitarald** [comment]
GPT-4o is fully rolled out to Inline Chat (versions 0.19 and above).

We see in our offline and online experimentation that 4o shines with better understanding of tasks, suggesting higher quality code edits, with just slightly slower response times.

Relatedly, Chat view pane has been using [4o since 0.17](https://github.com/microsoft/vscode-copilot-release/issues/1211#issuecomment-2265388668), and got a larger context window in the past weeks.

Happy Smart Coding!

**Comment by tats-u** [comment]
Not mini? It's super great news. Thank you for the update.
