### ISSUE TITLE
Code line break Request support

### ISSUE THREAD

**Issue by ringcrl** [microsoft/vscode-copilot-release#672]
![image](https://github.com/microsoft/vscode-copilot-release/assets/16740021/9581ec9c-0d56-4155-9523-bcd5104b5139)

As you see，I dont have enough space to display copilot sidebar，and I don't want to frequently drag to enlarge the sidebar.Hope to provide code automatic line wrapping capability.

**Comment by roblourens** [comment]
There is a setting, `chat.editor.wordWrap`
