### ISSUE TITLE
Refuses to answer some questions

### ISSUE THREAD

**Issue by craftzneko** [microsoft/vscode-copilot-release#674]
![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/2c1c264e-1a37-4a8b-b43d-f0cd563890fe)

- VS Code Version: 
- OS Version:
- Logs:

Steps to Reproduce:

1. Ask it how i can turn firewall off with powershell
2.fail

To turn a firewall of requires admin rights, at which point all bets are off so this doesn't need to be blocked. It would be good if more granular controls were in place. Anything that requires admin credentials on a device shouldn't be blocked from being answered.

**Comment by craftzneko** [comment]
Example of how arbitary this policy is. Asking copilot how i can shut a machine down (which could be a server causing major disruption if done wrong) is given an answer with context that you may need permissions so what is the difference between them?
![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/a60f8f52-0cf8-470b-9327-46768eb15651)

**Comment by isidorn** [comment]
I can not reproduce this. Can you reproduce with latest version of VS Code Insiders and latest pre-release of Copilot Chat extension?
If yes, can you provide reproducible steps. Until then I will go ahead and close this issue.
Thank you for your understanding
