### ISSUE TITLE
Feature request: add a temporary mute option

### ISSUE THREAD

**Issue by allsey87** [microsoft/vscode-copilot-release#677]
Copilot is great but sometimes it is a bit too much. I would love to be able to "mute" copilot (ideally with a keyboard shortcut) and not get any suggestions for the next 1 or 2 minutes while I am trying to write a comment or complex bit of code. It is endlessly annoying when it keeps trying to autocomplete while I am thinking. I often find it takes me 2-3x longer to write something due to copilot constantly interrupting me.

**Comment by allsey87** [comment]
> I often find it takes me 2-3x longer to write something due to copilot constantly interrupting me

My current solution is to literally disable the extension (and re-enable it when I am done) which is not great since then I need to restart vscode.

Another way this could be resolved is using some sort of exponential back off, e.g., if I reject a suggestion with ESC, wait 5, 10, 20, 40 seconds before suggesting again.

**Comment by lramos15** [comment]
This is an issue with the Copilot extension and not the Copilot Chat extension.  Those bugs normally go [here](https://github.com/orgs/community/discussions/categories/copilot)

But, you can set a custom keybinding for this to toggle the suggestions

<img width="717" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/a0284d11-e244-446e-88ea-158b56811f1a">
