### ISSUE TITLE
Manually provide explicit question context

### ISSUE THREAD

**Issue by WillCMcC** [microsoft/vscode-copilot-release#68]
It would be great to see which code of mine the chat interface has access to. It would be even better to be able to "tune" it -- some or all of a file, one or all open tabs. I understand there are limitations here -- personally I feel like I would feel more "in the drivers seat" if I could adjust / see what I was asking about. 

It seems to be visible code in the active tab, which is definitely useful and actionable. 

It could be useful even to have some pre baked prompt with information about file structure and perhaps even succint commented function signatures for files that could be sent along as more context. This could also be tuneable - "generate structure summary", "generate file annotations"

So the feature request is:

- give the user control over what code context is sent over to the llm
- allow the user to include entire files
- allow the user to include multiple files
- allow the user to use the llm to create for itself summaries of directory structure and file contents to provide a larger question and answer context

Thanks for this tool! What a joy to use.

**Comment by jrieken** [comment]
We have this by, there is the attach action and dnd gestures that allow to add files, symbols and more
