### ISSUE TITLE
Copilot Bugs Out When Closed Out

### ISSUE THREAD

**Issue by orgenom** [microsoft/vscode-copilot-release#681]
- VS Code Version: 1.85.1
- OS Version: Windows 11
- Logs:

Steps to Reproduce:

I meant to add @workspace with ctrl enter so I quickly closed out, but then the chat bugs out.

1. enter a prompt to GitHub Copilot Chat
2. While the prompt is loading, press 'X' on the top right of the prompt
3. The prompt box will not be able to send any messages, and the 'stop' square doesn't work.
4. In order to fix, open a new chat window or close and reopen vscode.

**Comment by roblourens** [comment]
I can't repro an issue, can you share a screenshot or some more details to be sure I understand? You can check the "GitHub Copilot Chat" or "Window" output channels for errors
