### ISSUE TITLE
Refactoring code into reusable parts by scaffolding files

### ISSUE THREAD

**Issue by johnnyelwailer** [microsoft/vscode-copilot-release#684]
Hello

This is related to https://github.com/microsoft/vscode-copilot-release/issues/300

However, I wanted to describe my specific use case.

Often I start to write code in a single file, and then later refactor it by splitting it up into multiple files.
For example, in an angular application, this would mean creating multiple presentation components, based on one initially big smart component template.

Right now, Copilot helps out a lot with writing out big formulars and other repetive blocks of code.
However, when the time comes to split up the code, I am left with a lot of manual work to create files and scaffold the components.

Ideally, I would like to select a part of code, for example in my angular template, and ask copilot to move it into a seperate component, creating one or multiple files (Example Angular, a `component.html` as well as `component.ts` file), with the code style of the current codebase. Then, it would of course have to replace the usage in the exising code by referencing the new component.

For copilot to have this extended knowledge of the codebase is probably a lot to ask.
But I believe, even with a limited scope of the current open file, it could already do a lot of magic.

Even if it would not be able to automaticly perform **all** the steps, like in the angular example, to also update code imports and component level imports, if I at least had two scaffolded files with the basic splitted out code inside, it would be a massive productivity boost for me.

**Comment by jrieken** [comment]
Copilot edits should support this, see https://code.visualstudio.com/docs/copilot/copilot-edits for how/what. You should be able to tell it extract parts of a file into a new file and it will do it. Please try this out and report back
