### ISSUE TITLE
Add multiple file to context like cursor.sh

### ISSUE THREAD

**Issue by BrianLYS** [microsoft/vscode-copilot-release#685]
It'd be nice to be able to tag files I want to ask questions about in the chat like @file.txt @file1.txt and it gets context for both. 

The usecase would be if I want to ask about implementing a certain component and how it relates to the code it's on it's only reading one file at a time using the auto "with reference" to.

**Comment by lramos15** [comment]
Please try insiders and the pre-release of the extension we've added experimental support for `#file`. Let us know what you think and provide feedback!
