### ISSUE TITLE
Disable Ctrl+L shortcut to log out

### ISSUE THREAD

**Issue by lackovic** [microsoft/vscode-copilot-release#686]
From time to time it happens that I accidentally press `Ctrl`+`L` while chatting with Copilot and that has the effect to _reset_ the chat (or _start a new session_ or _log out_?).

Can you add the possibility to disable the shortcut?

**Comment by roblourens** [comment]
You can change or disable all keyboard shortcuts through the keyboard shortcuts editor in vscode
