### ISSUE TITLE
@workspace not working properly

### ISSUE THREAD

**Issue by navidrigi** [microsoft/vscode-copilot-release#687]
- VS Code Version: 1.85.1
- OS Version: macOS 10.15.7 (19H2026)
- Logs: Encountered an error while deciding what workspace information to collect: failed

Starting from today, it only throws this error, all the time.
No matter whether it is a simple question or a complex log, only errors are happened.

**Comment by sbatten** [comment]
@mjbvz what error logs can we collect currently for this?

**Comment by MikeT2424** [comment]
I am also seeing this error for every question I ask with @workspace.

**Comment by digitarald** [comment]
Duplicate of https://github.com/microsoft/vscode-copilot-release/issues/618#issuecomment-1904843603
