### ISSUE TITLE
Copilot Chat not answering on Microsoft Fabric related questions

### ISSUE THREAD

**Issue by rabbyn** [microsoft/vscode-copilot-release#688]
as reported some months ago via https://github.com/microsoft/vscode-copilot-release/issues/213#issuecomment-1589792866 (+see screenshot provided there) I'm still stuggling to get any help from GitHub Copilot with my Microsoft Fabric Lakehouse development. 

As seen again in this panel below Copilot doesn't want to provide any help about Fabric ... but funnily the suggestion show below is "How can I create a Delta Table in Apache Spark?" 

Basically it feels strange as a VS code user to be force to fall back on **Edge Copilot** while I'm doing data engineering  with [VScode Fabric Synapse Extension](https://learn.microsoft.com/en-us/fabric/data-engineering/setup-vs-code-extension). Maybe it's me who is stuggling to understand the boundaries between "various copilots" (Edge Copilot Vs GitHub Copilot)

![image](https://github.com/microsoft/vscode-copilot-release/assets/72968975/f14dc851-d008-4c13-b3c9-7b220aaeaa7a)

As well I tried to find where is I could setup this https://github.com/images/modules/site/copilot/features-breakout.mp4 as it seems to be a acceptable workaround. QED :  In this case I will just provide the GitHub documentation repo of Microsoft Fabric (like https://github.com/MicrosoftDocs/fabric-docs/tree/main/docs/data-engineering) et voila !

**Comment by isidorn** [comment]
This should be done as part of a Chat Extension https://code.visualstudio.com/api/extension-guides/chat
Thus closing as an extension candidate
