### ISSUE TITLE
.copilotignore is not honored

### ISSUE THREAD

**Issue by Checkm3out** [microsoft/vscode-copilot-release#689]
To make copilot ignore certain files:

- Add them to your `.gitignore` if they are temporary files that shouldn't be committed
- Create a `.copilotignore` file at the root of your project. This works just like a `.gitignore` and lets you specify globs that will be ignored

_Originally posted by @mjbvz in https://github.com/microsoft/vscode-copilot-release/issues/635#issuecomment-1841288552_

![image](https://user-images.githubusercontent.com/56098823/291633632-5413228f-911d-4b58-bb69-6da97314d32d.png)

I added .copilotignore to the root of my project with .env in it

then query copilot chat with
@workspace while the .env is open in the viewer

Copilot will pull the .env as a reference still

**Comment by lramos15** [comment]
The release note was a bit unclear. `@workspace` will respect the file as to not index it, but your open file will always be sent along. To prevent further confusion I've gone ahead and pushed a changed that should be in tomorrow's insiders + pre-release that will also not include the opened file if it matches a `.copilotignore` pattern.
