### ISSUE TITLE
Copilot Chat does not open

### ISSUE THREAD

**Issue by 23chrischen** [microsoft/vscode-copilot-release#690]
Type: <b>Bug</b>

I installed github copilot and copilot chat, the click "reload window". The copilot chat icon in the activity bar shows for about 2 seconds and is clickable, and I can even see the copilot chat contents for a second, but then it disappears from both the side bar and the activity bar and I can't open it again.

Extension version: 0.12.2023120701
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 23.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 8, 7|
|Memory (System)|32.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id f4f1107a-55e1-409f-a5f3-13a875f33183|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t:30925682

```

</details>

**Comment by 23chrischen** [comment]
Also notable, for the 1-2 seconds that I can actually see the copilot chat, the "profile" icon for copilot chat doesn't show.

I took this screenshot, I believe this conversation is from a while back, perhaps when I was in the private beta.

<img width="435" alt="Screenshot 2023-12-19 at 10 42 39 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/6621177/a86a96ce-d097-4dc4-995c-778bec3dbf62">

**Comment by 23chrischen** [comment]
Additionally, the command @command:workbench.action.openQuickChat.copilot doesn't do anything

**Comment by joyceerhl** [comment]
@23chrischen can you please share the GitHub Copilot Chat output channel logs? Were you previously able to access Copilot Chat, and do you have access through an individual or enterprise subscription?

**Comment by moti-malka** [comment]
I Have the same issue, @23chrischen   did you manage solve this

**Comment by moti-malka** [comment]
I found the answer, you need to enabled the GitHub Copilot Chat feature on your organization setting on GitHub
![image](https://github.com/microsoft/vscode-copilot-release/assets/27952544/baf5c8c1-f141-4d44-8e1a-82f37c1619ff)

**Comment by 23chrischen** [comment]
Hi guys, thanks for the help, I just checked and it looks like my copilot subscription changed from personal to enterprise and I didn't realize it, and my organization doesn't allow copilot chat. I'll close this issue.
