### ISSUE TITLE
Feature Request: Custom Shortcut Commands for Frequent Prompts

### ISSUE THREAD

**Issue by garam-kim1** [microsoft/vscode-copilot-release#692]
### Description
I'm a regular user of Copilot Chat, and I find myself frequently using certain prompts. To enhance efficiency and user experience, I propose custom shortcut commands, similar to the existing ones like `/tests` and `/fix`. This feature would allow users to create their own shortcuts, like `/xxx`, which are tied to specific prompts they use often.

### Proposed Feature
- **Custom Shortcut Commands**: Users can set custom shortcuts for their frequently used prompts. 
- **Settings Format**: The setting for this feature could follow a format similar to: `custom_prompt::{"shortcut":"custom_prompt_text"}`. For example, if a user wants to create a shortcut for a review prompt, they could set it as `custom_prompt::{"review":"Please review the following code"}`.
- **Ease of Use**: This would significantly streamline the workflow for users who rely on specific prompts regularly.
- **Customization**: It allows for a more personalized and efficient use of the Copilot Chat interface.

I believe this feature would be a valuable addition to Copilot Chat, making it even more user-friendly and efficient for regular tasks. Thank you for considering this request.

**Comment by roblourens** [comment]
What I typically do is `/`, type a few characters, hit tab. It can be very quick this way

**Comment by MishkaMishka** [comment]
It could be helpful for certain code commenting style. For instance I would like to have a possibility to design custom prompt with some static data eq: 

########
Author: Doe, John
Date: 2024-01-01
Description: <Short summary of the code generated by copilot here> 
########

Is there any chance I could do that in the near future?
