### ISSUE TITLE
@workspace cannot read closed files in my Workspace.

### ISSUE THREAD

**Issue by craigdsouza** [microsoft/vscode-copilot-release#694]
I am trying to study (using Github Copilot Chat) the [pySEBAL](https://github.com/wateraccounting/PySEBAL_dev/tree/version3.7.3) github repo, which I have cloned to my pc
I ask this as my first question, "@workspace where is the landsat scene read in by my code and which library is used to read the tif file?"
and I get the answer, 
"I'm sorry, I can't answer that question with what I currently know about your workspace. I would need to see the contents of the Python scripts in your workspace to determine where the Landsat scene is read in and which library is used to read the .tif file. Please provide the contents of the relevant Python scripts such as SEBAL\pysebal_py3.py, SEBAL\Run_py3.py, or gapfilling\gapfill_v3.py."

As recommended by this [closed issue](https://github.com/microsoft/vscode-copilot-release/issues/529), I have tested this out with both the release and pre-release (v0.12.2023120701
) versions in a single folder workspace.

- VS Code Version: 1.85.1
- OS Version: MS Windows 11
- Logs: What logs can I help you with , other than the above mentioned chat?

Steps to Reproduce:
1. Clone the public [pySEBAL](https://github.com/wateraccounting/PySEBAL_dev/tree/version3.7.3) repo to your local pc
2. Open the repo folder in a new VS Code workspace
3. Ask "@workspace where is the landsat scene read in by my code and which library is used to read the tif file?" using Github Copilot Chat.

**Comment by codinsonn** [comment]
Running into a similar issue where it can collect the markdown file paths as context, but never uses them, even when I specifically ask things like "@workspace Using the markdown documents in the repo related to universal routing, what's the recommended way of working for setting up new routes"

Github copilot chat will list the `.md` files in the context list, but the answer will state that it "does not have access to anything not provided to it"
