### ISSUE TITLE
CoPilot triggers loss of input control system-wide

### ISSUE THREAD

**Issue by ghost-ng** [microsoft/vscode-copilot-release#695]
- VS Code Version: code -v    
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64

- OS Version: 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux
- Logs: need help finding the right logs
  the github copilot logs in exthost dont give me any information, just a routine authentication sequence.
- Copilot Version: v1.143.0
- vscode source: Microsoft apt repos

Steps to Reproduce:

1.  Start vscode with copilot already installed
2.  Type away for an unknown period of time, randomly trigger a screen freeze

I don't even know how to begin troubleshooting.  What I do know:
- when I uninstall the copilot extensions, vscode is stable, no issues at all
- when i install copilot extensions, i'll have issues every few hours to days.

Symptoms:
Entire screen ceases to accept input.  The screen appears frozen, but I can see my CPU counter still ticking away.  Also the autosave on code still seems to work.  I noticed that if I leave code open still for a few minutes my unsaved changes will eventually remain upon system reboot and vscode restart.  The only way to regain my input control (that I know of) is to restart my system (vm reboot).

Edit: I forgot to mention, if the "freeze" occurs while I am typing, that particular last letter becomes on repeat and start spamming the screen as if I am holding that key down.  Again, it doesnt go away so i have to restart the VM.

**Comment by jrieken** [comment]
Also try to CPU profile this. Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

https://user-images.githubusercontent.com/1794099/120606621-a97e0180-c44f-11eb-8e32-9fdafdc949ec.mov
