### ISSUE TITLE
Using different Github accounts for VS Code Setting Sync and for Copilot Chat

### ISSUE THREAD

**Issue by aderbenev-intermedia-com** [microsoft/vscode-copilot-release#698]
- VS Code Version:
Version: 1.86.0-insider
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:36:57.756Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: 10 22H2

Steps to Reproduce:

1. Sign in to VS Code with GitHub for settings sync
2. Sign in to Copilot extension with a different Github account for Copilot access

(it works at this point)

3. Enable Chat extension
- it complains that my Copilot license is expired.

The account I'm using for VS Code settings sync is my old account, which had Copilot enabled for about a year;
the account I have Copilot license enabled now in is a company-bound account (this one).

Copilot itself and Copilot Labs work, but Chat doesn't and it complains on each VS Code start about that.

**Comment by Falven** [comment]
This is a critical scenario.
We really need this for enterprise scenarios... Isolation of Enterprise account data for/without copilot enabled...

**Comment by LogicDaemon** [comment]
I'd rather not use chat at all (and currently I'm not using it, despite Copilot extension installs the chat every time, and then Chat disables it if I disable Chat, though the main Copilot extension working flawlessly without Chat).
