### ISSUE TITLE
Copy full response as markdown (feature request)

### ISSUE THREAD

**Issue by sumeetpareek** [microsoft/vscode-copilot-release#699]
## Feature Request Summary 

Can we please add a "copy full response as markdown" button to Github Copilot Chat as well? Thanks ❤️ (See attached screenshot for more context).

## Helpful Details

- There are many instances when we benefit from copy-pasting a full response from Github Copilot Chat. **For Example:** When saving the response in a project's documentation directory, or when sending it to a team member on Slack, or modifying some parts of the response, and so on.
- While currently we can drag the cursor > select full response > and press `cmd+v` > doing so does not copy the ```**markdown** _version_ `with` backticks``` or any markup.
- Other AI chat tools like Google's Bard, OpenAI's ChatGPT, Perplexity AI, etcetera all have a button to copy the markdown version of a full chat response. (Besides having separate copy buttons for various code snippets within the full response).
- It would be very helpful to have  a "copy full response as markdown" button to Github Copilot Chat as well.

![image](https://github.com/microsoft/vscode-copilot-release/assets/140441/12874b9d-eda8-42e0-9d92-2ce115e396d3)

**Comment by peter-maday** [comment]
Hi I am using VSCode `1.85.1` on MacOS, and I can select Copilot responses and copy them as Markdown (with formatting) using the "Copy" command. When selected the segment is highlighted (blue border). This is different from using the text selection (that works the way you described - and copies the text not the Markdown).

**Comment by roblourens** [comment]
You can also right click the item to copy it. See this issue for more https://github.com/microsoft/vscode-copilot-release/issues/416#issuecomment-1745426765
