### ISSUE TITLE
i'm sure these are just early testing issues but still, just letting you know

### ISSUE THREAD

**Issue by navjack** [microsoft/vscode-copilot-release#7]
- VS Code Version: insider
- OS Version: windows 11 pro for workstations latest canary
- Logs:

Steps to Reproduce:

the copilot chat:
first it was working great. then i got server not responding errors. then it was working again... then it was giving me absolutely unrelated "explain this code" replies and now it has no ability to know i have anything selected.

**Comment by digitarald** [comment]
If it happens again please file issues for each bug you find and steps to reproduce.
