### ISSUE TITLE
Support the means to save a Copilot chat session

### ISSUE THREAD

**Issue by dineshh** [microsoft/vscode-copilot-release#70]
Support the means to save a Copilot chat session to make it easier to come back to some of the reasoning behind decisions made or code written. That also helps the user with reviewing the prompts to improve them in subsequent  projects

**Comment by LucaCiucci** [comment]
That would be very helpful, similar feature request: #12

**Comment by imperialmarch55** [comment]
Ctrl+Shift+P, Chat: Export Session will save as a json file.

**Comment by roblourens** [comment]
We now have the Export/Import commands, but also there is a button in the view title to see your chat session history
