### ISSUE TITLE
Fixed Page during Answer Generation

### ISSUE THREAD

**Issue by shahbaz-mogal** [microsoft/vscode-copilot-release#704]
Would love to have the sidebar and text not constantly scroll by default when generating an answer. Reading a constantly moving text is not intuitive. Recommend having the question to fix all the way to the top of the sidebar when you hit enter on a question, and the answer slowly generate and fill the empty space below but the generated text isn't constantly scrolling.

Would love to hear thoughts

:)

**Comment by joyceerhl** [comment]
Probably duplicate of https://github.com/microsoft/vscode-copilot-release/issues/138
