### ISSUE TITLE
Elimination of Question upon Accidental Press of Top Arrow Button with Cursor on the First Line

### ISSUE THREAD

**Issue by umarrazapreesoft** [microsoft/vscode-copilot-release#707]
If you carefully compose a question in the chat bar, then navigate to the top line and accidentally press the top arrow button, your question disappears, and there is no way to retrieve a question once it's gone.

- VS Code Version: 1.85.1
- OS Version: Ubuntu 22.04.3 LTS

**Comment by umarrazapreesoft** [comment]
[Chat disappaer Issue.webm](https://github.com/microsoft/vscode-copilot-release/assets/76509505/ef5b0330-884a-445c-a59c-b8127256f135)

**Comment by joshistoast** [comment]
This is probably the most annoying part of the UI

**Comment by umarraza** [comment]
> This is probably the most annoying part of the UI

This is a pain in the ass.

**Comment by JamesInDenver** [comment]
Standard undo keyboard shortcut (in Windows at least) also does not restore the lost text.  It seems the arrow keys are providing prompt history, which is nice, but the pressing the down arrow key past the last submitted prompt does not return the unsubmitted text that was pending.  This is how most shells work.  Type text, hit up n times, then hit down n times and you will be returned to the text that was pending on the command line.

**Comment by andresmeidla** [comment]
It also happens when scrolled to the end of the text and pressing "Down".
It has had me putting my fists up in the air and curse out loud for about ~10 times now.

**Comment by Sisyphean-a** [comment]
I am in dire need of this rectification. I believe that when I press the upward key, it often signifies that I have inputted a substantial amount of content. The disappearance of such content under these circumstances is truly vexing.

**Comment by vbrozik** [comment]
This is extremely annoying. Although I know about the problem it happens to me very often that I lose my carefully written question. I have to write the question in a text editor first to not lose it :(

**Comment by bjtucker** [comment]
This is really harmful to my workflow. Like others, I'm only usually arrowing around my unsubmitted comment when I've typed a lot of stuff in it. So this bug hits when it is most painful.

I see this has been assigned to @rebornix a couple of weeks ago. Do you have any update you can share with us?

**Comment by Flywheel** [comment]
I see I'm not the only one who's encountered this frustrating experience.

**Comment by aricAI** [comment]
Also happens on the last line with a down arrow press.

**Comment by leobastin** [comment]
Kindly prioritise. A serious productivity killer and an extremely annoying thing. A painstakingly well crafted query is lost forever with the press of an arrow key.

**Comment by kien-pham** [comment]
I hate this, I loose all my question and have to type it again. Please fix this ASAP!

**Comment by e-simpson** [comment]
The feeling when you write the most fire prompt and accidentally bump the arrow keys 😭

**Comment by roblourens** [comment]
This is actually fixed now
