### ISSUE TITLE
Pressing the up / down arrow keys in the chat input field sometimes clears what you've typed

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#708]
I'm pretty sure this is related to the ability to pull up previous questions by pressing the up arrow. 

It'd be good to have a safeguard that prevents the chat input field from being cleared if there is text in it. Otherwise you can spend a long time crafting a question only to have it wiped out before submission because you're using the up/down arrow keys when editing it.

**Comment by sidewaysdesign** [comment]
+1 This seems incorrectly implemented. Pressing the down arrow should simply restore the incompleted prompt.

**Comment by moshemo613** [comment]
I don't think that the arrow keys by themselves should move us from one chat to another.  Perhaps alt-shift-downarrow/uparrow -- but not just the arrow keys themselves.  On many occasions I use the arrow keys to go to the top or bottom of a chat with no desire to switch to a previous or later chat.  If I do wish to cycle through chats, that's a unique case that should require some extra keys to make sure that it doesn't happen by accident.

That is in addition to the annoying problem that it deletes what we are currently working on.

**Comment by jakeRPowell** [comment]
Came here to report this, was editing a fairly long and detailed prompt and it just vanished. This was on a new chat window so there are no previous questions, up and down arrows now do nothing except delete what's in the text area.

**Comment by binaryfire** [comment]
> I don't think that the arrow keys by themselves should move us from one chat to another. Perhaps alt-shift-downarrow/uparrow -- but not just the arrow keys themselves. On many occasions I use the arrow keys to go to the top or bottom of a chat with no desire to switch to a previous or later chat. If I do wish to cycle through chats, that's a unique case that should require some extra keys to make sure that it doesn't happen by accident.
> 
> That is in addition to the annoying problem that it deletes what we are currently working on.

I agree with this 100%. It would actually be better to remove this feature completely. If we want to find a previous chat we can use the clock (history) icon. Being able to flick through them with arrow keys in the input box doesn’t add anything.

**Comment by roblourens** [comment]
Apologies, tracking this in https://github.com/microsoft/vscode-copilot-release/issues/661
