### ISSUE TITLE
Using more then one reference

### ISSUE THREAD

**Issue by dpoettler** [microsoft/vscode-copilot-release#709]
Title pretty much describes it.
Would it be possible for Copilot Chat to use more then one reference file.
Maybe by naming the filenames in the promt.

**Comment by bulawow** [comment]
Just #file and choose the file u want

**Comment by dpoettler** [comment]
Oh well thanks. Didnt know that

**Comment by dpoettler** [comment]
This doesnt work sadly

**Comment by TopT95** [comment]
I would love to see that implemented to Capilot!

**Comment by dpoettler** [comment]
Sadly not working for me like this. I use the nightly build of VSC and Copilot Chat.

**Comment by dpoettler** [comment]
I completly reinstalled VSC and now it works. No idea what caused this problem. Thanks for the information though
