### ISSUE TITLE
Unable to log into VSCode using github account on Ubuntu

### ISSUE THREAD

**Issue by neilbGH** [microsoft/vscode-copilot-release#71]
- VS Code Version: 1.79.0 insider
- OS Version: Ubuntu 20.04
- Logs: [ERROR] [default] [2023-05-22T05:59:11.046Z] GitHub Copilot could not connect to server. Extension activation failed: "Timed out waiting for authentication provider to register"

Steps to Reproduce: 

1. Start code insider with no account logged in and copilot nightly will display the above error
2. To force a login, press ctrl+shift+P, type settings sync then click Turn on Settings Sync
3. Choose sign in and turn on
4. Two options are given, "insiders Default" and "Stable".
5. Choosing either option offers a single option of signing into a Microsoft account. This differs to the stable build where a choice of logging into a Microsoft or GitHub account is offered.
7. Can't continue because I can't log into a GitHub account from the nightly.

**Comment by TylerLeonhardt** [comment]
Can you follow these steps so that we can get more information on what's going on?

* Open the Output pane (ctrl+shift+u)
* drop in this issue he contents of the following:
  * `GitHub Authentication` Output channel

**Comment by neilbGH** [comment]
There is no GitHub Authentication output channel. It won't allow me to log into GitHub. There is no option for it, I can only log in using a Microsoft account. Doing so will display a Microsoft Authentication channel.

Perhaps whatever it is that allows GitHub logins for Visual Studio is disabled or broken on the Ubuntu version?

**Comment by TylerLeonhardt** [comment]
I'd like you to see if the built-in GitHub Auth extension is accidentally disabled. Can you go to the Extensions pane in VS Code and search `@builtin`, then under features find `GitHub Authentication`. Make sure it's enabled.

**Comment by neilbGH** [comment]
Yes, it was disabled. I enabled it and everything works. Thanks.

**Comment by TylerLeonhardt** [comment]
Glad you're unblocked!
