### ISSUE TITLE
Sorry, the response matched public code so it was blocked. Please rephrase your prompt. WHY ?

### ISSUE THREAD

**Issue by hhfrancois** [microsoft/vscode-copilot-release#712]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by garethjax** [comment]
I have the same issue and my copilot setting is "allow public code".
<img width="1075" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/3459602/6506e828-84cf-4075-9706-4bc2c75eeaf3">
Also my repository is set to "private".

**Comment by garethjax** [comment]
Hmmm after an extension reload, it seems to have bypassed the issue.

**Comment by erni313** [comment]
I have the same issue even if the setting is set to allow. I always had it like that and I keep getting the annoying message:
Sorry, the response matched public code so it was blocked. Please rephrase your prompt.
![image](https://github.com/microsoft/vscode-copilot-release/assets/11357040/19b533b0-c291-4ffc-844e-56e13e36c849)

**Comment by dasali-jenario** [comment]
same. extension reload didn't solve the issue.

**Comment by garethjax** [comment]
I’ve noticed that opening a new session solved most of issues.

**Comment by erni313** [comment]
I was able to fix the problem by removing the extension, reinstall and then
instead of continuing with the older conversation that gets offered by
default, I started a new convo. That fixed the issue.

**Comment by craftzneko** [comment]
This issue is really frustrating as it seems to crop up from time to time, its started again for me even asking it some basic questions triggers it.

![image](https://github.com/microsoft/vscode-copilot-release/assets/662108/abc9e208-2db0-4cdf-84d3-c001c2f1aae8)

**Comment by lramos15** [comment]
Please ensure you are on the most up to date version of VS Code and Copilot Chat. If you're still experiencing filtering please include your Copilot Chat Logs
`CMD / CTRL + SHIFT + U -> Copilot Chat`

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
