### ISSUE TITLE
Please add  'Save Chat As Markdown' feature.

### ISSUE THREAD

**Issue by pipe-organ** [microsoft/vscode-copilot-release#713]
I find some conversations very helpful and I'd like to keep them to study further. But it's almost impossible to save them or print them. 

If I try to select it with my mouse (like a web page), code blocks won't be selected so it gets really tedious to save even a simple chat. 

A simple '**save as markdown**' would be fantastic. 
Thanks in advance!

**Comment by roblourens** [comment]
You can right click > Copy All to get the session as markdown. You can also run the command "Chat: Export Session" to export to JSON

**Comment by pipe-organ** [comment]
Oh.. I feel so silly. Thank you so much @roblourens !!
