### ISSUE TITLE
charts overlap

### ISSUE THREAD

**Issue by huolibo** [microsoft/vscode-copilot-release#715]
- VS Code Version:
1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2

- OS Version:
mac os 12.3

Steps to Reproduce:

1. open session in  Editor
![image](https://github.com/microsoft/vscode-copilot-release/assets/17586328/598e3b0d-d3f6-4543-bd1a-5e82ad04a4e7)
the two charts overlap.

**Comment by bhavyaus** [comment]
Could you please include repro steps to help us diagnose the issue better? I am unable to reproduce this on my end.

**Comment by huolibo** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/17586328/8b9c6d9a-7317-4606-ac10-11fb6214dfe8)

**Comment by roblourens** [comment]
I can't repro it, were you able to @bhavyaus?

@huolibo do you have a custom file icon theme, or any other interesting settings? Does it happen if you comment out all your settings?
