### ISSUE TITLE
Can't properly explain to me what its own "modifiers" do

### ISSUE THREAD

**Issue by VividLemon** [microsoft/vscode-copilot-release#716]
It bothers me that the bot can't explain what some of the question modifiers are. For example, I'm trying to ask it what its own @workspace modifier does, but it doesn't know. I tried to be very specific about it and say "what does @workspace do for github copilot" but no luck. It would be nice if it had more knowledge about itself. I'm not exactly sure if this is a feature request in the traditional sense 🧐 

In addition to maybe explaining some of the other capabilities that it has, such as describing how to use the inline chat editor and other features.

**Comment by roblourens** [comment]
I like @mjbvz's suggestion, we could have a `@help` agent to answer questions like this. To me, it's related to https://github.com/microsoft/vscode/issues/197081. If we populate help content for all the agents, we should be able to ask questions about it too.
