### ISSUE TITLE
Disappearing Chat Icon on Activity Bar

### ISSUE THREAD

**Issue by DanielNanto** [microsoft/vscode-copilot-release#717]
Type: <b>Bug</b>

Step 1) Open Github Copilot Chat. I have the extension accessible via the Activity Bar on the left hand side of my screen.
Step 2) Click and drag the chat icon off of your Activity Bar, and onto the opposite side of the window.
Step 3) File > Open Folder > (some other project)

Your GitHub Copilot Chat is now gone, and you seemingly aren't able to open it or restore it to your Activity Bar.

You can fix this issue by:
Step 1) File > Open Folder > (The project folder that you originally moved chat icon within)
Step 2) Click and drag the Github Copilot Chat icon back onto the task bar.

Extension version: 0.11.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (49.42GB free)|
|Process Argv|--crash-reporter-id 78ac44e6-b2cd-4646-8b09-0c80e8c4f5d8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
vsjup518:30340749
vshan820:30294714
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019cf:30917260
cp7184t:30925682

```

</details>

**Comment by digitarald** [comment]
@DanielNanto Do you see the toggle panel in the VS Code title bar? That should bring back the secondary sidebar in case it is closed.

**Comment by sbatten** [comment]
<img width="127" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/6561887/1666f3a4-a437-4e05-8954-e0ff4671f98e">

**Comment by digitarald** [comment]
Please re-open if this persists. I make sure to add this to the catch-all issue on chat not appearing.
