### ISSUE TITLE
Render MathJax inside chat

### ISSUE THREAD

**Issue by andynameistaken** [microsoft/vscode-copilot-release#718]
Rendering mathjax (also simple plotting capabilities would be cool). It would be useful when chatting about programs logic and complexity. I hope I'm not alone who need this.

**Comment by mjbvz** [comment]
Closing as not something we plan on supporting anytime soon

**Comment by hamadzidani** [comment]
Any update on this?

**Comment by hamad12a** [comment]
This discussion has been [moved](https://github.com/microsoft/vscode-copilot-release/issues/978).
Finally, it is on the milestone [list](https://github.com/microsoft/vscode-copilot-release/milestone/80)
