### ISSUE TITLE
Bug when sending large prompt

### ISSUE THREAD

**Issue by nicolas-goyon** [microsoft/vscode-copilot-release#72]
- VS Code Version: VSCode insiders latest
- OS Version: windows (remote to linux server)
- Logs:

Steps to Reproduce:

1. Copy paste a large file to the chat area
2. unhandled status from server: 400 Bad request: bad request: role must be "user", got "system"

**Comment by jclarkdev** [comment]
> unhandled status from server: 400 Bad request: bad request: role must be "user", got "assistant"

**Comment by IvanVeridian** [comment]
I also got this error when pasting a large error message into the chat. 
GitHub Copilot: 
unhandled status from server: 400 Bad request: bad request: role must be "user", got "assistant"

**Comment by digitarald** [comment]
Dupe of #20
