### ISSUE TITLE
Terminal: Copilot explain this should expand selection to current line/command if there is no selection

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-copilot-release#723]
1. In the terminal, type a command but do not run it
2. Right click on the line and select `Copilot: Explain this` in the context menu

**Bug**
If there is no selection, copilot doesn't get any info

Here's the chat that gets run:

![Image](https://github.com/microsoft/vscode-copilot-release/assets/12821956/328e7bc6-c6fa-44d6-b439-6d5e01efbd24)

**Comment by Tyriar** [comment]
I don't think this is worth doing since the cursor is usually on the prompt line and will therefore not be what you're after.
