### ISSUE TITLE
Improve chat session management

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#725]
- Check naming- eg "All Sessions" instead of "History"
- Let the user rename sessions
- Show a dropdown of sessions in the view title?
  - How do we combine this with the management (x to remove, pencil icon to rename) that we can do in a picker?

**Comment by isidorn** [comment]
Love that you started on this! There was an interesting discussion in [Zurich standup today](https://microsoft.sharepoint.com/:v:/r/teams/VSCode68/Shared%20Documents/Z%C3%BCrich/Recordings/View%20Only/Daily%20Standup-20240117_100224-Meeting%20Recording.mp4?csf=1&web=1&e=Mmx6jR&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifSwicGxheWJhY2tPcHRpb25zIjp7InN0YXJ0VGltZUluU2Vjb25kcyI6MTQ3My4yM319), and I just wanted to summarise it here: 
* Love for less buttons in the Chat Title area.
* Feedback button does not belong on every chat message, feedback is general and might fit well under `...`
* Love for how ChatGPT manages sessions. Every time a user goes to ChatGPT they do not have to do anything, there is a new session waiting and a nice history. Can we reduce clunky manual session management that users have to do? For example:
1. Currently we preserve sessions on Window reload, or when user reopens a workspace. Is this the optimal experience? Alternative we could always show the Chat Welcome view that has pointers to older sessions. So by default user will start a new session, but can easily pick an older session.
2. ChatGPT uses AI to summarise chats to get a good title, if it can not just uses the name "New Chat". Can we do something similar to get a good name for each chat?

If we decide to do 1, it is a good candidate for an experiment.

In the standup there was also discussions about how to improve the issue that when you start talking to an @agent, you always have to explicitly mention that @agent. This is also the feedback that we are getting from extension partners. I think it is an important thing we must tackle, but orthogonal to this.

**Comment by hbons** [comment]
@isidorn for 1: Restoring sessions by default I think is a good thing. We can also show a `New Chat` action in place of the prompt suggestion when we restore:

<img width="403" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/103326/eb851520-0277-45d7-9e92-01c029025778">

**Comment by roblourens** [comment]
> We should explore Dropdown for showing multiple sessions. Might be cluttered, but will know better once there is a mock.

There is a mock, sounds like you didn't get to that though

**Comment by Wladefant** [comment]
definitely +1 for autogenerated names, as 
![image](https://github.com/microsoft/vscode-copilot-release/assets/79611093/99dd4d37-cda8-4732-9211-ebf29b641910)
is not clear at all. Shouldnt be too difficult to implement. 

Another thing, that lies on the heart of many is to be able to view all chats from all repos, as there is often important information hidden in these chats, Plus one code base can be used in github codespaces, downloaded once again from github etc. and then all the chats get lost even though it is the same codebase

**Comment by epaulson** [comment]
I'm really glad you're looking at ways to improve the session management, I try to keep a lot of different chats going to keep the context of each chat clearer. Just being able to name a chat and have that chat name show up in the dropdown would be nice, right now I start off each chat with 'Let's name this chat XYZ'. It'd be nice if the chat dropdown had the name of the chat and maybe the timestamp of the last entry.

it'd be really slick if you could with a press of a button turn a chat into a github issue and upload the chat history right into the issue/link it to a PR so you could see how things developed, and that UI should probably be tied to whatever you improvements you make to session management.

**Comment by HemalR** [comment]
Would like to chime in and suggest the way Raycast does it. Chat sessions is new by default unless it is being revisited within x amount of time (say 5 minutes or some sane number).

**Comment by diminutivesloop** [comment]
Would love to see auto-generated titles. Currently the list of chats just shows truncated text from the first message which is not very useful.
