### ISSUE TITLE
@workspace doesn't work. Says it doesn't have access or cant find the file, even if the file shows up in 'used references'

### ISSUE THREAD

**Issue by ianbruton** [microsoft/vscode-copilot-release#727]
There's really not that much to say to be honest other than it just doesn't work. 

OSX: ventura 13.3.1

vscode: Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:16.874Z (3 wks ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.4.0

Copilot: v1.145.0

Steps to Reproduce:

1. just try do anything with workspace
2. responses from copilot:
    1. "I'm sorry, I can't provide the specific details you're asking for because I don't have access to the content of the files you mentioned. "
    2. "I'm sorry, but as an AI model I don't have access to your local or remote file system"

**Comment by TylerLeonhardt** [comment]
Can you include the Copilot Chat Output Channel please

![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/1f6684cb-7e3b-47ad-951b-d557f33ce974)

**Comment by ianbruton** [comment]
Hi @TylerLeonhardt, 

Here is the prompt, response and chat.


ME:

@workspace

can you look at these files for me?:
/path/to/file_1.ts
/path/to/file_2.ts

I feel like these are doing the same thing? or are they talking to different things?

I am thinking to merge them if they are the same


COPILOT:

I'm sorry, I can't provide the specific details you're asking for because I
don't have access to the content of the files you mentioned. However, based on
their names, file_1.ts and file_2.ts might be doing similar tasks.

Here's a general approach to determine if they can be merged:

Check the functionality of each file: Look at the methods and their
implementations in each file. If they are doing the same thing, it's a good
sign that they can be merged.

Check the usage of each file: Look at where and how each file is being used in
the project. If they are used in the same way, they might be candidates for merging.

Check the dependencies of each file: Look at the dependencies of each file. If
they have the same dependencies, it's another sign that they can be merged.

Remember, even if they are doing similar things, they might be used in
different contexts or for different purposes. Always make sure to thoroughly
test your application after such a refactoring to ensure nothing has broken.


COPILOT CHAT:

2024-01-09 10:43:55.540 [info] [auth] Logged in as ianbruton
2024-01-09 10:43:55.945 [info] [chat] copilot token chat_enabled: true
2024-01-09 10:43:55.945 [info] [auth] Got Copilot token for ianbruton
2024-01-09 10:43:55.990 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-09 10:43:55.991 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-09 10:43:55.991 [info] [chat fetch] chat model gpt-4
2024-01-09 10:43:58.615 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 2624 ms
2024-01-09 10:44:05.271 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-09 10:44:05.275 [info] [streamChoices] request done: requestId: [aee118c1-e7e3-4149-a667-d5d2c2b261d3] responseId: [7264d6a8-5bfd-4026-98c3-230bdff9132e] model deployment ID: [wda6aab3977b]
2024-01-09 10:44:07.441 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-09 10:44:07.441 [info] [chat fetch] modelMaxTokenWindow 4096
2024-01-09 10:44:07.441 [info] [chat fetch] chat model gpt-4
2024-01-09 10:44:11.804 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 4363 ms
2024-01-09 10:44:27.181 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-09 10:44:27.182 [info] [streamChoices] request done: requestId: [f0b0ef54-88da-4639-8279-9c575cd3c489] responseId: [520a21fb-bbea-44af-99e2-e6f4aaf38c30] model deployment ID: [wda6aab3977b]
2024-01-09 10:44:27.193 [info] [chat fetch] engine https://api.githubcopilot.com/chat
2024-01-09 10:44:27.193 [info] [chat fetch] modelMaxTokenWindow 8192
2024-01-09 10:44:27.193 [info] [chat fetch] chat model gpt-3.5-turbo
2024-01-09 10:44:28.409 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 1216 ms
2024-01-09 10:44:28.410 [info] [streamMessages] message 0 returned. finish reason: [stop]
2024-01-09 10:44:28.411 [info] [streamChoices] request done: requestId: [cbc03941-900e-462b-b558-a4b5a3d4d381] responseId: [02ff0501-5ec8-4a29-9b44-dfe64c436bef] model deployment ID: [x338b9c029b38]

**Comment by kevinLourencoDev** [comment]
Hi, same here, on Windows machine this time, so probably not related to the system. I made something really simple:

**Prompt**: "@workspace list files in current selected dir src/"
**Analyze copilot in progress** 
**Chat Answer**: "I'm sorry, I can't provide the list of files in the src directory as I currently don't have the specific information about your workspace."

That is the whole point of @workspace, so the whole feature seems to not work.  I have GitHub Copilot v1.153.0

**Comment by TylerLeonhardt** [comment]
In insiders & the prerelease version of Copilot Chat, you can include explicit file references using the variable: `#file`...

When you type `#file:` you'll get a quick pick that shows up and allows you to search for the file you'd like to include. Try this out with your query:

```
can you look at these files for me?:
#file:/path/to/file_1.ts
#file:/path/to/file_2.ts

I feel like these are doing the same thing? or are they talking to different things?

I am thinking to merge them if they are the same
```

and let me know how it goes.

**Comment by crackwitz** [comment]
I'm on the Copilot Chat v0.12.2023120701 pre-release, but on the Copilot release v1.154.0 (no prerelease/insiders option available). When I type `#` in the chat window, it's not suggesting `#file`.

**Comment by TylerLeonhardt** [comment]
@crackwitz are you on the latest [insiders of VS Code](http://code.visualstudio.com/insiders/)?

Because with the latest insiders I'm on v0.12.2024012401 of Copilot Chat which is much newer.

**Comment by crackwitz** [comment]
I entered just `#file:script.user.js any refactorings that would be a good idea to improve this code?` with the file being open and focused and not in any subdirectory:

>I'm sorry, but I can't provide any suggestions without seeing the actual code. Could you please provide the code you want to improve?

Though, now, prefixed with `@workspace`, with and without the `#file:` bit, it now seems to consider the majority of that file (everything that's in functions, as opposed to global scope statements)

**Comment by TylerLeonhardt** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/2644648/133bf72c-63ea-4397-a790-f3198631b8ec)
you get the highlighting of `#file:...` right? If not, I don't think it would actually be included.

**Comment by crackwitz** [comment]
> #file:...

Yes, and the suggestions I get are (now) very specific to the entire file I have. Previously, the given reference was exactly the part of it that was visible on screen.

**Comment by crackwitz** [comment]
OOOOOH I have to actually let it autocomplete! I can't just literally type `#file:script.user.js`. I have to type `#file`, then tab, so it throws up a selection of files, and pick it from that. ***Then*** it's highlighting. Weird but okay.

**Comment by TylerLeonhardt** [comment]
> The response I get is missing explicit mention of referenced files. I guess it doesn't need to since I specifically gave the reference.

We have an issue on this one already. Actually I opened an issue about this :)

I think there's room for improvement:
1. the UX of `#file`
2. how to know when to use `@workspace` versus `#file`. I know the _idea_ is that if you wanna pull in a specific file, well, that's `#file` but if you're trying to find something in your workspace, that's `@workspace`.

**Comment by roblourens** [comment]
1. https://github.com/microsoft/vscode-copilot-release/issues/801
2. You can use both! And they should be better integrated in the future as well. But you can plug specific files into any agent, including `@workspace` which will also search the workspace

**Comment by TylerLeonhardt** [comment]
@roblourens I think two is more like... `@workspace` gives the impression that you can just add a file path in the query and it'll know because you're asking `@workspace`. Maybe this is more an issue on `@workspace` to somehow either:
1. support that - `@workspace tell me about ./foo/blah.ts`
2. make it clear that the user should use `#file` for this scenario

**Comment by roblourens** [comment]
`@workspace gives the impression that you can just add a file path in the query and it'll know because you're asking @workspace`

Where do you get the impression that `./foo/blah.ts` will work? I think that making it more clear that users can use `#file` is the way forward

**Comment by crackwitz** [comment]
How about you have this thing *ask the user for permission* instead of requiring to be told? I'd be happy to grant one-time or permanent access to certain files, or deny it to specific files, if asked.

It's already "thinking" and considering what parts of the workspace to read, before reading them. That's a multi-step process. Just throw in some permissions dialogs.

Or at least train it to always suggest to the user how he can get what he wants (besides saying "sorry, I can't do that, Dave"), if he failed to use those UX elements properly.

> (Dave) Hey what's going on in fizzbuzz.tcl?
> (HAL) I'm sorry Dave, I can't read your files without your permission. If you want to grant me the privilege, type this: `#file:fizzbuzz.tcl`
> (Dave) `#file:fizzbuzz.tcl`
> (HAL) Sweet jesus, Dave! That's not fizzbuzz! That is \*surprised pikachu\*!

**Comment by demonspork** [comment]
`@workspace` and `#file` rarely works with VS Code both release, insider, pre-release plugin etc. for me on Windows 11. I have used both local code and code on a remote system and the copilot chat only sporadically can access my selections, workspace, or specific files and usually just gives the canned response.

Every once and a while, after a re-install, restart, etc I can get one request with `@workspace` or `#file` to work correctly, then it immediately breaks.

**Comment by digitarald** [comment]
The latest release should fix general context awareness. Follow-up work for large files is tracked in https://github.com/microsoft/vscode-copilot-release/issues/1083. Used references also shows variables now, and drop them if they could not get included (more polish will happen there).

If specific issues around "As an AI I can't see your files persist", please open a new issue with logs attached so we can debug specific scenarios.

**Comment by anggrayudi** [comment]
How can this issue is closed? It's May 15th now, i'm using the latest VSCode & Copilot Chat, yet the issue is not resolved @digitarald. I'm facing the same issue like @demonspork mentioned. Here's the message i got from the latest version:

> I'm sorry, I can't answer that question with what I currently know about your workspace. I would need to have access to the file names or code excerpts from the **xxxxx** directory to provide a more accurate answer.

**Comment by digitarald** [comment]
@anggrayudi please file a new issue, with details of the general query and if the expected files show up in _used references_
