### ISSUE TITLE
Code generation is incomplete

### ISSUE THREAD

**Issue by alongnice** [microsoft/vscode-copilot-release#73]
- VS Code Version:1.70.0-insider
- OS Version:uos 1053
- Logs:

Steps to Reproduce:

1.Open the copilot chat dialog bar and put forward the need to generate a piece of code to realize two stack structures to realize the queue structure.
2.The code will output only part of it, and there is even no definition of the full output class.
3.It will be the same if you try other code, such as the merge algorithm.

**Comment by yaukeywang** [comment]
+1

**Comment by digitarald** [comment]
Do you have an example source and conversation, so we can test against it?
