### ISSUE TITLE
Unable to log into Copilot from VSCode Insiders

### ISSUE THREAD

**Issue by andreafinlay** [microsoft/vscode-copilot-release#730]
Suddenly logged out and unable to log back into Copilot. 
Restarting the IDE/uninstalling + reinstalling the extension has no effect.
I'm in the trial version of Copilot, using VSCode Insiders.

- VS Code Version: `vscode/1.86.0-insider`
- OS Version: `Darwin 23.2.0`
- Logs:
```
[INFO] [auth] [2024-01-08T23:13:58.193Z] Invalid copilot token: missing token: 403 
[ERROR] [default] [2024-01-08T23:13:58.193Z] Extension activation failed: "User not authorized"
```

Steps to Reproduce:

1. Open VSCode
2. Be presented with this error:

![Screenshot 2024-01-08 at 18 26 32](https://github.com/microsoft/vscode-copilot-release/assets/35619265/22fd1c11-2f19-4a1e-9649-af0647d50b8b)

3. Attempt to log in via `Retry` button, command palette, Copilot Chat extension window, etc.
4. No result is produced, clicking on "Sign in" does not direct me anywhere, no additional logs are produced

**Comment by bulawow** [comment]
to me it looks like ur trial expired make sure to check it out

**Comment by andreafinlay** [comment]
@bulawow I just started my 30-day trial on jan 4th, also the Copilot settings in Github are totally fine, no indication of an error or expiry

**Comment by andreafinlay** [comment]
more details:
i first noticed this issue after asking a question in Github Copilot Chat using `@workspace`. the chat got stuck on `Collecting workspace info` for a while. I didn't think it was related, but after starting VSCode today, I once again have access to Copilot/Chat, but my Chat is once again stuck on `Collecting workspace info`. Maybe the two issues are related 🤷‍♀️

**Comment by TylerLeonhardt** [comment]
@andreafinlay can you switch to the prerelease version of the extension and let me know if it shows signs of improvement? You can get it by clicking on the extension here:
<img width="345" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/2644648/ff52f307-0f31-4896-a11c-e54fc5c999fa">

**Comment by TylerLeonhardt** [comment]
We'll be releasing a new stable in about a week in case you ever want to switch back.
