### ISSUE TITLE
keep saying I'm not connected to the internet

### ISSUE THREAD

**Issue by dt12** [microsoft/vscode-copilot-release#731]
- VS Code Version:1.85.1
- OS Version:Windows 10
- Logs: - It appears you're not connected to the internet, please check your network connection and try again.

Steps to Reproduce:

1.open vscode
2.type anything in Github Copilot chat extension
3.Getting anwser “- It appears you're not connected to the internet, please check your network connection and try again.”

why?

**Comment by dt12** [comment]
Resolved, seems to be a problem of the API server.

**Comment by ahleksu** [comment]
How did you resolved this?

**Comment by bpop-admin** [comment]
How did you resolved this?

**Comment by dt12** [comment]
Guys, it was a dns problem, that my dns direct the connection to a wrong ip, so just reset the dns works.
