### ISSUE TITLE
Sorry, your request was rate-limited. Please wait and try sending again later.

### ISSUE THREAD

**Issue by alokjain-lucky** [microsoft/vscode-copilot-release#732]
- VS Code Version: 1.85.1
- OS Version: mac 14.2.1 (23C71)

Getting this message "Sorry, your request was rate-limited. Please wait and try sending again later." 

I have a paid individual plan.

**Comment by kbirk** [comment]
Same

**Comment by sohaviaestenome** [comment]
Same here.

**Comment by vigalo** [comment]
Hi, same situation here.

**Comment by nathan1658** [comment]
Same here, I can't work without it any more, please fix it asap

**Comment by vitorsm19** [comment]
Same here!

**Comment by nathan1658** [comment]
> it's back for me. random?

Works for me now!

**Comment by o-chan-1998** [comment]
same here

**Comment by BrennerSpear** [comment]
Same

**Comment by AleAgu200** [comment]
same here

**Comment by lramos15** [comment]
This was a GitHub service wide issue that has since been resolved.

**Comment by fsoft72** [comment]
I have this issue again, today

**Comment by JJEccles** [comment]
I have this issue right now also

**Comment by wise3d** [comment]
same

**Comment by NobodyButMe-Haiya** [comment]
eh ? not just me ?

**Comment by garcipat** [comment]
Nope me as well

**Comment by Creiv** [comment]
same

**Comment by jdiogomagalhaes** [comment]
First time having this issue today (also have a paid plan)

**Comment by pete4dev** [comment]
same

**Comment by IbrahimSwaiss** [comment]
Starting a new chat by clicking the plus sign from the chat top right corner solved this for me.

**Comment by chiragpurohit71085** [comment]
something strange is happening 

`Sorry, your request was rate-limited. Please wait and try sending again later.`

2024-02-19 19:20:58.426 [info] [chat fetch] url https://api.githubcopilot.com/chat/completions
2024-02-19 19:20:58.426 [info] [chat fetch] modelMaxPromptTokens 3072
2024-02-19 19:20:58.426 [info] [chat fetch] modelMaxResponseTokens 3540
2024-02-19 19:20:58.426 [info] [chat fetch] chat model gpt-4
2024-02-19 19:20:58.794 [info] [chat fetch] request.response: [https://api.githubcopilot.com/chat/completions], took 366 ms
2024-02-19 19:20:58.796 [info] [chat fetch] Request ID for failed request: ,90fe858a-f6b9-4c39-b0f3-76bb8a1c9682

**Comment by MohamedBenTaher** [comment]
same here

**Comment by madkrell** [comment]
same, getting this now :(

**Comment by Laurendv** [comment]
same here

**Comment by sovetski** [comment]
Same problem, with a "paid" account, it is very strange 🙂

**Comment by neutrix-developer-ten** [comment]
i am getting this error from now why !!"I have been receiving this error message consistently lately. I'm not sure why it keeps happening."

**Comment by scallop123** [comment]
Sorry, your request was rate-limited. Please wait and try sending again later. Popped up! Will someone work on this or does everyone have to keep posting 'same here'?

**Comment by johnkeers-bca** [comment]
Same issue on a paid plan!! - Please fix ASAP

**Comment by theREMASTERED1** [comment]
aaa yes, Well guess I'll have to actually use my brain to solve my issue till this gets fixed haha

**Comment by Tlemondy** [comment]
Same issue - Paid individual plan

**Comment by qma9** [comment]
Same here, with paid individual account

**Comment by sebmeng** [comment]
Same here, with paid individual account

**Comment by RolfMoleman** [comment]
Same here, with paid individual account

**Comment by qma9** [comment]
Weird it is working for me now with a new chat, but only if i don't select any of my code as a reference

**Comment by neutrix-developer-ten** [comment]
My issue has been resolved. I installed the pre-release version, and the problems I was experiencing in the chat window and the inline chat have been fixed. However, the issues in the floating window persist. You can give the pre-release version a try. I hope you find it helpful!"g window. You can try it out too, have fun!

**Comment by theREMASTERED1** [comment]
Tried the method of making a new chat, worked for a while, and then it started doing it again regardless. As @neutrix-developer-ten just suggested, switching versions seems to also fix it I think, I was on the pre-release version, and switching back to the release version solved it for now

**Comment by theREMASTERED1** [comment]
nevermind,worked for a second,o well

**Comment by LaurentOngaro** [comment]
Same problem for me with the current version. This was not the case in the previous ones, but I don't know from which version the problem appeared

**Comment by asleekgeek** [comment]
Same here:

> "Sorry, your request was rate-limited. Please wait and try sending again later."

Using vscode.

I have a paid individual account.

**Comment by Erogenesis** [comment]
I believe the issue may not stem from the extension itself, but rather from Github Copilot encountering rate limits imposed by its integration with OpenAI (or Azure, depending on their infrastructure).

Additionally, I've experienced multiple instances of hitting this limit today, with the restrictions being lifted at seemingly arbitrary (random) intervals.

**Comment by vinukaliyar** [comment]
Same here in vscode on paid account

Sorry, your request was rate-limited. Please wait and try sending again later.

**Comment by johnkeers-bca** [comment]
I tried again after restarting VSCode for an unrelated extension update and it started working again. Very random

**Comment by Mariusjuvet1** [comment]
Same here in vscode on paid account

**Comment by carlosdanna** [comment]
As @johnkeers-bca mentioned above restarting vscode fix it for me, but I haven't done many queries afterwards.

**Comment by neutrix-developer-ten** [comment]
Guys After installing the pre-released version, I restarted VS Code, and all the issues were fixed.

**Comment by aminebouaziz** [comment]
Same here, vscode paid version

**Comment by suryakun** [comment]
Same here,

**Comment by tmccormack165** [comment]
> Starting a new chat by clicking the plus sign from the chat top right corner solved this for me.

Thank you worked for me too.

**Comment by 7Flafleur** [comment]
Same issue here

**Comment by alirusta** [comment]
For me neither the pre-release nor restarting VSC work consistently as of today. The copilot plugin either responds with:
```
Sorry, your request was rate-limited. Please wait and try sending again later.
```
 or with
 ```
 "Cannot read properties of undefined (reading 'split')"
 ```
 Which is particularly frustrating as I am paying for this service myself. I hope this gets resolved soon.

**Comment by thortiede** [comment]
I am having the same issue. Switching to the pre-release version and restarting VSCode switched to gpt-3.5-turbo model for one request, which was answered successfully. A subsequent request then failed again with the same error message. It attempted to use gpt-4 again for this request.

**Comment by 0x7878** [comment]
same here

**Comment by shemesh1500** [comment]
Same to me

**Comment by rzolin** [comment]
Just asked a couple of questions, it worked fine, and now this "Sorry, your request was rate-limited. Please wait and try sending again later.". What's going on?

**Comment by tomasz-paluch-sh** [comment]
Same here

**Comment by andrew-tiosa** [comment]
same here,....

**Comment by tkruke** [comment]
This one has been closed. I follow [issue #920](https://github.com/microsoft/vscode-copilot-release/issues/920) now to see if there are updates.

**Comment by kanaan-dvlps** [comment]
I have the same issue today! while talking to copilot chat.

**Comment by ferreque** [comment]
same here º_º

**Comment by iamOmarFaruk** [comment]
Same to me facing this issue form this morning :(

**Comment by RachaelNantale** [comment]
Had to open a new copilot chat  for me and its now working

**Comment by sanrandry** [comment]
same

**Comment by RobertLaudan** [comment]
same

**Comment by dzelentcov** [comment]
Same

**Comment by quememo** [comment]
Same

**Comment by serhiikravets** [comment]
same, thank you very much github copilot for charging me for this

**Comment by serhiikravets** [comment]
Fix:
1. copy your message that it wont respond to
2. type "wake up"
3. Paste and send your message again

**Comment by doma2k** [comment]
same

**Comment by sbondarenko-msft** [comment]
Having this issue as well.
Perhaps it would be helpful to make these error messages a bit more verbose to be able to know if it's an infra overload thing or a bug.

**Comment by jnagelkerke** [comment]
same here! personal paid account.

**Comment by KonradGC** [comment]
I got also this and iam also paying for copilot. It was very bugged on its answers today and showed me 40times the same answer if i asked something. And then suddenly this message appeared and it stopped working at all for hours now. Its just not usable for any kind of question or tasks now due to this rate limiting.

Please fix this..

**Comment by CesarAugusto14** [comment]
Same here, personal paid account.

**Comment by eusouoviana** [comment]
Same

**Comment by black7in** [comment]
Same

**Comment by yasmin-movingpay** [comment]
same right now

**Comment by bevanwsjones** [comment]
ffs

**Comment by ViniciusHenriqueWebDev** [comment]
Acontece novamente

**Comment by ray-su** [comment]
same

**Comment by cedricpinson** [comment]
same here

**Comment by ROLDANCALO23** [comment]
same

**Comment by epawel** [comment]
1+

**Comment by black7in** [comment]
Ssssaaaameeeeeeeeeeee

**Comment by cpakken** [comment]
Ok not just me...

**Comment by nicole-hucke** [comment]
same

**Comment by bruak** [comment]
now again

**Comment by BalajiSriraman** [comment]
lmao

**Comment by shirily** [comment]
same

**Comment by ThimanKrish** [comment]
Same for me.

**Comment by sreeni2020** [comment]
Sorry, your request was rate-limited. Please wait and try sending again later. --> I'm a paid user.  Why I'm getting this?

**Comment by Stefano-H** [comment]
Samee

**Comment by pbrisson** [comment]
Same

**Comment by NapoBona** [comment]
same

**Comment by howar31** [comment]
same

**Comment by roncojon** [comment]
same

**Comment by YanisTrabelsi** [comment]
same

**Comment by abivlqz** [comment]
same

**Comment by brucelee11b** [comment]
same

**Comment by sebastianbernalv** [comment]
same

**Comment by nicole-hucke** [comment]
> same

omg hiiiiiiii :3

**Comment by sebastianbernalv** [comment]
> > same
> 
> omg hiiiiiiii :3

hiiiiiii :3

**Comment by igbins09** [comment]
Copilot is down lol

**Comment by djimonlee** [comment]
I cannot code without AI pls help lol

**Comment by StevenCrocker** [comment]
Noticed everyone is commenting right now, same issue lol.  Guess I have to wait.

**Comment by YanisTrabelsi** [comment]
Sad, need to work as before... With my own brain

**Comment by ivana-g** [comment]
same here

**Comment by sufyankhatri** [comment]
ok not only mee

**Comment by fsepulveda** [comment]
same problem

**Comment by igbins09** [comment]
> Sad, need to work as before... With my own brain

gotta dust out the cobwebs in my brain now :(

**Comment by BryanCastro** [comment]
I pay good money for this, wtf Microsoft! We should all get a month free of charge! 😉

**Comment by MuSHaKS** [comment]
the same error `Sorry, your request was rate-limited. Please wait and try sending again later.`

**Comment by sufyankhatri** [comment]
its back boys lets go back to work

**Comment by GiorgosBetsos** [comment]
Same problem. I have a paid subscription, despited this got this error twice.

**Comment by nicole-hucke** [comment]
we're ballin boys!!!!!!!!!!!!!!!

**Comment by sebastianbernalv** [comment]
oh no

**Comment by lramos15** [comment]
A bad server side deploy was rolled back. If you're still experiencing issues please open another issue 🫡

**Comment by bruak** [comment]
problem solved its works me now

**Comment by GiorgosBetsos** [comment]
Works now for me too

**Comment by haternesto** [comment]
Got the same is issue today
