### ISSUE TITLE
There's a ✨ absolutely everywhere in the editor and it's a bit annoying tbh

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode-copilot-release#735]
- VS Code Version: 1.86.0-insider
- OS Version: Pop!_OS 22.04 LTS x86_64
- Logs: N/A

Steps to Reproduce:

1. Click in an editor

What happens:

![image](https://github.com/microsoft/vscode-copilot-release/assets/10495562/7b5d6d99-2c07-439f-81c2-36b780d59f0f)

What should happen:

![image](https://github.com/microsoft/vscode-copilot-release/assets/10495562/58d0372d-43e7-452b-a7a0-16153fc78aa6)

**Comment by aeschli** [comment]
The sparkle is a variant of the light bulb and signals that there's some code action available at the given location. We find that code actions are a good way activate inline chat.

You can control this by:
Turning off code actions for Copilot: `"github.copilot.editor.enableCodeActions": false`
Only show code actions on non-empty lines (the old behaviour of code actions): `"editor.lightbulb.enabled": "onCode"`

**Comment by NatoBoram** [comment]
Thanks, `"editor.lightbulb.enabled": "onCode"` is exactly what I needed.

**Comment by kettanaito** [comment]
This should be an opt-in feature. It's incredibly distracting and kills any value proposition offered here by the sheer act of being annoying.

**Comment by alwaysmpe** [comment]
Hilariously, asking github copilot chat how to do this gave me the wrong answer. I was told to change
`"github.copilot.inlineSuggest.enable": false,`
