### ISSUE TITLE
VS Code insiders and normal both generate an Unhandled exception when i try to type anything to chat with a Powershell File open

### ISSUE THREAD

**Issue by craftzneko** [microsoft/vscode-copilot-release#738]
VS Code insiders and normal both generate an Unhandled exception when i try to type anything to chat with a Powershell File open

![295912709-898b347e-8cf2-4dd0-bc16-f5dddf51365d](https://github.com/microsoft/vscode-copilot-release/assets/662108/5519f7ed-9298-4338-8c05-501cf524e742)

- VS Code Version: 1.85.1 (insiders 1.86.0)
- OS Version: Windows 10
- Logs:

This started happening yesterday so possibly something in my ps script causing it to fail when appended to chat.

**Comment by digitarald** [comment]
This should be fixed in pre-release (coming out next week)
