### ISSUE TITLE
Introduce Command for Opening and Focusing Sidebar Chat 🗨️🔦

### ISSUE THREAD

**Issue by jonathanlinford** [microsoft/vscode-copilot-release#739]
# Feature Request
## Summary:
Add a command to open the sidebar chat and immediately focus on it in the GitHub Copilot extension for VS Code.

## Rationale:
The sidebar chat is often more convenient than the quick chat, since it doesn't obstruct open files. However, it requires manual focus after opening. This command would streamline the process.

## Proposed Command:
`workbench.action.chat.openAndFocusSidebar`

## Expected Behavior:
On execution, the command should open the chat in the sidebar and automatically shift the focus to the chat input field, enabling immediate typing.

This enhancement would improve the user experience by making the chat feature more efficient and user-friendly.

**Comment by rross13** [comment]
This would be amazing!

**Comment by BenjaminDazey** [comment]
Oh yeah I hate the copilot covers my code. This would be awesome!

**Comment by ruffjaxson** [comment]
I would definitely use this

**Comment by roblourens** [comment]
We have `workbench.action.chat.open` for this

**Comment by jonathanlinford** [comment]
> We have `workbench.action.chat.open` for this, are you looking for something different? ctrl+cmd+i

This is just what I'm looking for. Thank you!
