### ISSUE TITLE
Actual Context from Multiple Messages like Bing Chat

### ISSUE THREAD

**Issue by imperialmarch55** [microsoft/vscode-copilot-release#74]
I did a bunch of tests, and it made it very clear that the chat bot has a lot of trouble remembering previous messages, and it will even tell me at times that it can't know more than anything but the current message, like this for example:

"GitHub Copilot: As an AI language model, I can only access the current message or prompt that I receive. I do not have the ability to keep track of previous messages or context beyond the current message. However, I can provide assistance based on the current message or prompt to the best of my ability. Please let me know how I can assist you further."

This is a huge step down from Bing Chat and is very, very disappointing. It also can't handle near the amount of characters that the current version of Bing chat lets you paste (but not type out) in a single message, which compounds the problem. I feel like certain code I can't paste in Bing chat because I'd be afraid of it being used as training data, but with Copilot Chat as long as you have the right settings turned off it's supposed to keep your code confidential. So it's upsetting that the Copilot Chat doesn't have the same ability as the Bing Chat for understanding context and for character limit.

Please add this.

**Comment by roblourens** [comment]
Copilot Chat does have conversation history, even if it says it doesn't 😁 

We include as much as will fit in the context window. If you have an example of a conversation where this still isn't working as expected, please share a specific example

**Comment by imperialmarch55** [comment]
> Copilot Chat does have conversation history, even if it says it doesn't 😁
> 
> We include as much as will fit in the context window. If you have an example of a conversation where this still isn't working as expected, please share a specific example

As far as I can see, the issue isn't relevant anymore since the recent updates with GPT-4 .

It would be nice though if there was documentation or a video or something explaining exactly how it handles the conversation history along with the current context in the editor. 

I sometimes find myself creating a chat in the editor rather than the sidebar, in order to make sure it's not using any context of the open file and is instead only using the conversation history as context. I feel like when I'm in the sidebar it's replies could get weird or off topic from what I'm talking about in the moment, because it's referencing the current context it can see in the open file or what's selected in the open file, when that's not what I'm concerned with during that message. If that's not the case I would love to hear an explanation for how it handles that.

But anyway, it seems like resources on how all this works are lacking, and I've only discovered what I have by doing a lot of testing and messing around. I love the new updates and it has worked fantastic once I got the hang of it, but it wasn't the most straightforward process.

**Comment by roblourens** [comment]
I agree 100% that it's sometimes not helpful when random context from your open editor gets included automatically. This will actually be a focus in January, making sure that the user is in control of the chat context. Follow https://github.com/microsoft/vscode-copilot-release/issues/675 for details

**Comment by imperialmarch55** [comment]
> I agree 100% that it's sometimes not helpful when random context from your open editor gets included automatically. This will actually be a focus in January, making sure that the user is in control of the chat context. Follow #675 for details

Glad to hear this is being worked on, thanks for the update!
