### ISSUE TITLE
AI-Generated Code for Complete Projects

### ISSUE THREAD

**Issue by PierrunoYT** [microsoft/vscode-copilot-release#747]
Hello

I've been brainstorming about enhancing our development process and came up with an idea I'm really excited about: What if we had a tool that could turn text descriptions into fully functioning software projects? Imagine describing what you need in plain language, and voila – you get a ready-to-use codebase! This tool would handle various programming languages and adhere to coding best practices. I believe it could be a game-changer for prototyping and learning. Keen to hear your thoughts!

Best,
PierrunoYT

My Idea: Used AI to make the Text better.

**Comment by lramos15** [comment]
This is already implemented in VS Code Copilot Chat as `@workspace /new` give it a try and let us know what you think!

**Comment by PierrunoYT** [comment]
Can I use my own API Key for GPT? Im using Cursor right now.

**Comment by lramos15** [comment]
No you cannot. This repository is for VS Code Copilot Chat. Do you have a Copilot subscription?

**Comment by PierrunoYT** [comment]
> No you cannot. This repository is for VS Code Copilot Chat. Do you have a Copilot subscription?

Yes I just made one but just to testing if it works.

**Comment by lramos15** [comment]
`@workspace /new` takes your query like "Create me an express app" and creates an entire project with it

**Comment by PierrunoYT** [comment]
Hello?

**Comment by fisforfaheem** [comment]
project IDX can help

**Comment by PierrunoYT** [comment]
> project IDX can help

I signed up but I did not have access.

**Comment by joyceerhl** [comment]
> Okay but when I have the workspace created I want to like ask fix this and that issue and it should fix it but it says I need to do that myself.

We now support the following:
- You can fix error diagnostics in the workspace from the problems view or by right clicking on the diagnostic and selecting Fix with Copilot
- You can use Copilot Edits to directly modify files in your workspace
