### ISSUE TITLE
Chat Not Working With latest version of Code-Server (4.20.0)

### ISSUE THREAD

**Issue by KangByungwoo** [microsoft/vscode-copilot-release#751]
VS Code Version: 1.85
OS Version: Ubuntu
Logs:
Steps to Reproduce:

Install Copilot-chat via vsix
Error message occurs
I can't seem to get copilot-chat working with the latest version of code-server. The extension says it is incompatible with Version 1.85.

I am opening this b/c I couldn't reopen a similar issue #353

**Comment by lramos15** [comment]
As the linked issue states, are you using https://github.com/coder/code-server?

**Comment by lramos15** [comment]
Closing due to lack of info update
