### ISSUE TITLE
Arrow up/down in the chat prompt erases the prompt with no ability to return the erased data

### ISSUE THREAD

**Issue by sbondarenko-msft** [microsoft/vscode-copilot-release#752]
Type: <b>Bug</b>

Hi,

The scrollback in the chat prompt is currently not ideal. 
It's so bad, I am not even sure if it's intended to be this way, or if it's a small market share platform (i.e., just the Mac version) bug.

I carefuly craft the prompt, scroll up with keyboard arrow up to add more details in the beginning, and if I don't stop exactly before the 1st line - voila - EVERYTHING is gone to bring the previously submitted prompt.

And if I hit arrow down to go back, it's NOT THERE anymore.
Similarly, if you are at the last line and hit arrow down, you lose everything as well.

Looks like you tried to implement bash-like scrollback.
Good idea, but needs improvement.

1. In bash you can come back to partially completed unsubmitted input
...or...
2. Should not be able to lose my prompt that I had been crafting for minutes SO easily.

Thank you

Extension version: 0.11.1
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by shrikster-SW** [comment]
i agree this is super frustrating

**Comment by roblourens** [comment]
Sorry for the trouble, but this is fixed in Insiders

**Comment by sbondarenko-msft** [comment]
@roblourens when will this be available in the main channel? Thank you.
