### ISSUE TITLE
Let user hide followups

### ISSUE THREAD

**Issue by hbons** [microsoft/vscode-copilot-release#755]
The prompt suggestions are helpful when using Copilot for the first couple of times, but after a while the suggestions become less useful and clutter the response area, specially when there are multiple suggestions.

It would be nice if I could hide them or they if they would disappear automatically after a couple responses.

<img width="666" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/103326/fe036f24-daba-4f1c-95ff-0a993026fd85">

**Comment by isidorn** [comment]
There is a setting `github.copilot.chat.followUps` that you can use for this.
Thus I will go ahead and close this issue as done
