### ISSUE TITLE
Show how many characters are selected and the limit.

### ISSUE THREAD

**Issue by AntoineWVN** [microsoft/vscode-copilot-release#76]
For the moment, it seems like the copilot can only read the code that is currently selected.
It also seems like there is a limit on this, if we select more than 8K characters, it acts like nothing was selected.
It could be nice to display to the user how many characters are selected and the limit. Ex: (6502/8200).
If the amount of selected characters exceeds the limit, it could be nice to display a warning message informing the user that the selected text is too long.

**Comment by roblourens** [comment]
To some extent, this is a better situation now 7 monthths later. But context management will also be a priority in January.
