### ISSUE TITLE
Show History not working with VS Code Version: 1.85.2

### ISSUE THREAD

**Issue by gunjan-singh-ggn** [microsoft/vscode-copilot-release#762]
<img width="1038" alt="Screenshot 2024-01-19 at 8 53 17 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/69294739/16d5931d-df24-47d5-88e7-3f988d022c3a">

- VS Code Version:
- OS Version: Mac Sonoma 14.2.1

Steps to Reproduce:
<img width="1115" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/69294739/e67ee9b2-7914-44ab-a1a9-0cc05bd0ed79">

1.
2.

**Comment by telemachush** [comment]
I have the same issue. Restarted the laptop and the history is gone

**Comment by roblourens** [comment]
Can you check for errors in the "Window" output channel

**Comment by gunjan-singh-ggn** [comment]
Even in the "Window" output channel, not able to see chat history

**Comment by gunjan-singh-ggn** [comment]
I am on mac. Where can i check the vscode logs, if the chat history is not loading

**Comment by roblourens** [comment]
The "Window" output channel
