### ISSUE TITLE
Copilot Chat  Icon was disappeared !!

### ISSUE THREAD

**Issue by chisun-joung** [microsoft/vscode-copilot-release#764]
![image](https://github.com/microsoft/vscode-copilot-release/assets/1191050/daa4744e-b0d4-4e23-b173-bec3f9818ab5)

- VS Code Version: 1.85.2
- OS Version: Windows_NT x64 10.0.22621
- Logs:

Steps to Reproduce:
![image](https://github.com/microsoft/vscode-copilot-release/assets/1191050/7c0d0bd1-0626-460d-9f26-6fea37a1c2ec)

1.  
2.

**Comment by chisun-joung** [comment]
I recently changed my subscription plan from Personal to Business Oragization plan and the icon has since disappeared.

**Comment by digitarald** [comment]
@chisun-joung can you follow the steps from https://github.com/microsoft/vscode-copilot-release/issues/436 . It shows which commands to try and which logs to check for diagnostics. Please re-open if it persists.

**Comment by chisun-joung** [comment]
@digitarald  Thanks a lot.  I find a solution.
