### ISSUE TITLE
I am getting old results, from chat, it always give wrong answers about FLUTTER SDK why?

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/vscode-copilot-release#765]
Please update flutter documents and dart docs

I asked: latest flutter version?

As of March 1, 2023, the latest stable version of Flutter is 2.10.3. Please note that Flutter versions are updated frequently, so it's a good idea to check the official Flutter website or its GitHub repository for the most up-to-date information.

**Comment by fisforfaheem** [comment]
Flutter code given by this tool is from 2021 why?

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode-copilot-release/issues/513
