### ISSUE TITLE
bug d'affichage 

### ISSUE THREAD

**Issue by Pochton0** [microsoft/vscode-copilot-release#766]
Type: <b>Feature Request</b>

l'icon de mon extension s'affiche a l'ouverture de vscode avant de disparaitre apres quelques secondes et donc impossible de l'utiliser 

Extension version: 0.11.1
VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by roblourens** [comment]
Sorry but can you explain in English? Please share a screenshot or screen recording if possible, that might help.
