### ISSUE TITLE
SCM Generate commit message: No diff provided

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-copilot-release#768]
I got the following generated commit message:

<img width="507" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/44439583/d3852c66-ac7f-41f8-9afe-ab5433fd0c4a">

Repo steps:
1. make changes
2. commit them (do not push)
3. revert the changes (git reset --soft HEAD~1)
4. ask copilot to generate a commit message

**Comment by mempler** [comment]
Having the same issue here

**Comment by lszomoru** [comment]
I believe that I have tracked down the root cause of the issue. It should be fixed in Thursday's pre-release version.
