### ISSUE TITLE
pressing up/down destroys unsubmitted prompt

### ISSUE THREAD

**Issue by subtleGradient** [microsoft/vscode-copilot-release#771]
- VS Code Version: latest as of 2024-01-22

Steps to Reproduce:

1. start typing in copilot chat
2. before hitting enter, press up or down keys

Expected: move cursor around within unsubmitted message.
Unexpected actual behavior: replaces message with previous submitted messages, making the unsubmitted message lost forever

Maybe save the current unsubmitted message in the history also so that you can get back to it?

**Comment by leobastin** [comment]
Kindly prioritise. A serious productivity killer and an extremely annoying thing.  A painstakingly well crafted query is lost forever with the press of an arrow key.
