### ISSUE TITLE
Print asked question in the window EVEN if it is not sent yet

### ISSUE THREAD

**Issue by Kyliathy** [microsoft/vscode-copilot-release#774]
I just lost a long question due to some outage with Copilot servers. Once pressing <ENTER>, the question should ALWAYS be sent into the window. This allows for editing, history and is the UX I expect when I send a text somewhere. 

Currently, I just send my text into nothingness and lost it :). Of course, I had clipboard'ed parts of the question, but not all. It's a bit silly to have to CTRL + A and CTRL + C before every time I use this feature out of fear to not lose everything I typed ;).

**Comment by roblourens** [comment]
Sorry for the trouble, I'm hoping things are more stable now. It likely would have showed up in input history at least (up arrow). 

And it's supposed to work in the way you describe, so I'm not sure what went wrong so that the request was not rendered.
