### ISSUE TITLE
Unable to resolve nonexistent file.

### ISSUE THREAD

**Issue by mbs0221** [microsoft/vscode-copilot-release#776]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.85.2 Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681 Date: 2024-01-18T06:40:11.430Z (2 days ago)
- OS Version: macOS 14.2.1

Steps to Reproduce:

1. Connect to a remote server with SSH Remote.
2. Install Github Copilot
3. Install Github Copilot Chat

<img width="450" alt="image" src="https://github.com/microsoft/vscode/assets/12655889/acee777d-0384-409a-a728-aa261af113ab">

**Comment by WillMichels** [comment]
I also have this problem. It tries to get a file that used to be named Controller.py, but after I renamed it to MainViewController.py it started throwing this error. **After restarting VS Code, problem is resolved.**

## Copilot

- Version: 1.168.0
- Build: prod
- Editor: vscode/1.86.2

**Comment by sandy081** [comment]
Can you please share following log while you reproduce the issue?

- F1 > Open View... > Server

**Comment by chscott** [comment]
> Can you please share following log while you reproduce the issue?
> 
> * F1 > Open View... > Server

I have the same issue but don't have a `Server` option.

![image](https://github.com/user-attachments/assets/a4159095-b994-4c8c-aca4-0378fa64e184)
