### ISSUE TITLE
"Fix using Copilot" should have lower priority in "quick fix" menu than linter suggestions.

### ISSUE THREAD

**Issue by fahrenq** [microsoft/vscode-copilot-release#78]
Currently "Fix using Copilot" is always the first option when you use quick fix with `CMD + .`. I am so used to double-pressing the quick fix shortcut to resolve imports, change quotes, etc, that copilot's fix option gets in the way.

I reckon there should be some way to push these options further down in the quick fix menu.

<img width="508" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/10668780/86a54497-1683-4473-9625-9369494ef223">

**Comment by fahrenq** [comment]
I just noticed that it's not happening with all suggestions:

eslint seem to take priority over copilot, for example:
<img width="449" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/10668780/4fc9e9a1-da69-45ec-941f-4992999391ad">

**Comment by eddited17** [comment]
+1 here. For me it isn't showing any other quick fixes besides fix and expain with Copilot
