### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AlexDev404** [microsoft/vscode-copilot-release#781]
- Issue Type: `Performance`
- Extension Name: `copilot-chat`
- Extension Version: `0.11.1`
- OS Version: `Linux x64 6.5.0-14-generic`
- VS Code version: `1.85.2`file:///tmp/GitHub.copilot-chat-unresponsive.cpuprofile.txt

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/GitHub.copilot-chat-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[GitHub.copilot-chat-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-copilot-release/files/14042585/GitHub.copilot-chat-unresponsive.cpuprofile.txt)

**Comment by MEZboy** [comment]
I saw when i try to change vscode to performance model on my laptop, it will take lot's of GPU to run it, maybe it used GPU hardware acceleration to improve experience?!
![image](https://github.com/microsoft/vscode-copilot-release/assets/5998050/b6ac1439-9a95-4e34-a223-176b53c2cea1)
![image](https://github.com/microsoft/vscode-copilot-release/assets/5998050/fa5fa8ba-b020-4951-b719-ebdb0f2618db)
![image](https://github.com/microsoft/vscode-copilot-release/assets/5998050/de6714a1-36da-4136-9d4f-88e95cfe7cb7)

**Comment by TylerLeonhardt** [comment]
@AlexDev404 we just released a new version this past week. Can you try with the latest version and tell us if performance has improved?
