### ISSUE TITLE
CPU spikes and stays at 100%

### ISSUE THREAD

**Issue by tdharris** [microsoft/vscode-copilot-release#784]
Type: <b>Bug</b>

With the VSCode Extension GitHub Copilot Chat enabled, CPU Utilization spikes to 100% and remains stuck making my computer unresponsive. It appears to happen with a particularly large repo. It started happening Jan 23, 2024.

Extension version: 0.12.2024012401
VS Code version: Code - Insiders 1.86.0-insider (1091f68d834974d78cd4f9769034b4ae4581ff2a, 2024-01-24T05:36:35.802Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Connection to 'wsl+Ubuntu-20.04' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (41.80GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-20.04/home/tywer/dev/wrk/infrastructure-live --remote=wsl+Ubuntu-20.04 --crash-reporter-id fe3a46f2-fad5-40b8-8247-874787273194|
|Screen Reader|no|
|VM|40%|

Connection to 'wsl+Ubuntu-20.04' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
edj9j583:30943796
fegfb526:30945144
e3gdj431:30946825

```

</details>

**Comment by andreamah** [comment]
What do you do to trigger this behavior? Was it on extension startup?

**Comment by tdharris** [comment]
Yes, but I've used `Help: Start Extension Bisect` to help A/B test until it arrived at the conclusion of it being this Extension. I can also dupe manually immediately once I Enable the extension (no vscode reload required) and it goes away after Disabling after reloading vscode.

**Comment by andreamah** [comment]
If you follow https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-is-consuming-a-lot-of-cpu, can you tell what in the extension host is taking up the memory?

**Comment by tdharris** [comment]
There isn't any obvious hog to me from `code --status` outputs while duplicating it, but the `Vmmem` process continually grows as well. So perhaps it's doing some snooping around of files in the repo on start? I'd prefer it didn't snoop! 😆 

It's fairly difficult because I have about 5 seconds once enabling the extension to try things before everything becomes unresponsive and mouse movements are very sluggish and I have to disable the extension and reload for things to become usable again.

**Comment by tdharris** [comment]
It doesn't happen on all repos for me, just larger ones with lots of files it seems.. 🤔

**Comment by andreamah** [comment]
Do you notice a `rg` process taking a lot of memory when you look at your task manager?

**Comment by tdharris** [comment]
I don't see any `rg` process listed anywhere. :( I did notice this related discussion as well https://github.com/orgs/community/discussions/56755

**Comment by tdharris** [comment]
Perhaps if I can try the Monday build somehow, that might demonstrate different behavior? It did start happening Tuesday IIRC.

**Comment by tdharris** [comment]
Interesting... Adding `**/.terragrunt-cache` (a source of tons of temporary cache files) to the `files.exclude` VSCode Settings, and the issue appears to be fixed. 🤯

**Comment by andreamah** [comment]
if you add it to `search.exclude`, does it still fix it?

**Comment by tdharris** [comment]
Yes it does 👍

**Comment by TylerLeonhardt** [comment]
Yep. Rather than waiting for the first call to `@workspace` we index early.

Marked as a candidate, we'll revert this behavior for now while we experiment with performance improvements.

**Comment by roblourens** [comment]
In the future if you need to use rg to index, some things you might try

- make sure we can use `--files` instead of a text search
- experiment with throttling rg using the `--threads` flag. It can be less impactful (but slower) if you limit it to 1
- wait a little bit after extension activation to start rg, so it's not interfering with vscode and other extension startup

**Comment by connor4312** [comment]
@tdharris can you verify whether the latest release fixes the issue for you?

**Comment by tdharris** [comment]
Very much improved 🎉 🚀  Thank you!

**Comment by lopugit** [comment]
I'm still getting this issue 👀

![Screenshot 2024-08-05 at 12 45 44 PM - Activity Monitor - Activity Monitor](https://github.com/user-attachments/assets/ea7f8b72-2cfc-45d5-8055-60c44808d8fe)

**Comment by lopugit** [comment]
After closing vscode no issues

![Screenshot 2024-08-05 at 12 51 09 PM - Activity Monitor - Activity Monitor](https://github.com/user-attachments/assets/ef13d24c-8f8c-4293-856a-f7bfbea0822c)
