### ISSUE TITLE
When generating a commit message, add a few previous commit messages to the prompt

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode-copilot-release#785]
The auto-generated commit message can get quite nonsensical, prose-heavy and meaningless. Here's an example of a commit message I just generated:

> Refactor code to improve performance and readability

This is a terrible commit message.

Here's some commits from my history:

```log
* fd0b3d7 - ✨ Add a rotating tagline component (#155) (10 days ago) <Nato Boram>
* 71874c6 - ⬆️ Update GitHub Actions versions (#153) (2 weeks ago) <Nato Boram>
* 62c38c7 - 📝 Add download count badges to `README.md` (#145) (3 weeks ago) <Nato Boram>
* f2d20e0 - 🧐 Add F-Droid metadata (#146) (5 weeks ago) <Nato Boram>
* 1be5f81 - 👷 Rename uploaded apk in releases (#144) (5 weeks ago) <Nato Boram>
* c5c2109 - ⬆️ Update @capacitor/assets to version 3.0.4 (#143) (5 weeks ago) <Nato Boram>
* ad117d2 - 💄 Add Get it on SVG (#142) (6 weeks ago) <Nato Boram>
* 4c9e3a5 - ✅ Add unit tests for comment_tree (#141) (6 weeks ago) <Nato Boram>
* af88439 - ♻️ Change Vite's define for base36 UUIDs (#140) (6 weeks ago) <Nato Boram>
* fb6c5c7 - ⬆️ lemmy-js-client@0.19.0 (#138) (6 weeks ago) <Nato Boram>
* be5849f - 👷 Build Docker image in PRs (#136) (6 weeks ago) <Nato Boram>
* c6eb615 - 🎨 Upgrade ESLint (#135) (6 weeks ago) <Nato Boram>
* 1f0e34f - 📝 Google Play badge (6 weeks ago) <Nato Boram>
* c60a014 - ✨ IPFS build (#132) (6 weeks ago) <Nato Boram>
* a07c8d1 - 🔧 Sign with SSH (#130) (6 weeks ago) <Nato Boram>
* cfc6916 - 👷 Node.js Publish (#129) (6 weeks ago) <Nato Boram>
* a18577c - 📝 Add some install info (#128) (6 weeks ago) <Nato Boram>
```

These commit messages directly reference the changes made and don't group them all under "refactor the functions" and "update the code" and "improve performance and readability". There's also a specific pattern there; I'm using Gitmoji.

By adding a few past commit messages from the current user to the prompt, I think we can improve the generated commit messages to match the user's writing style.

**Comment by NatoBoram** [comment]
That sounds like it's part of the prompt

**Comment by lszomoru** [comment]
The prompt contains the last 5 commits of the user, and the last 5 commits in the repository for context. We have also added support for specifying custom instructions when generating commit messages. Please see [this comment](https://github.com/microsoft/vscode-copilot-release/issues/526#issuecomment-2509017787) on how to specify custom instructions for commit message generation.
