### ISSUE TITLE
Crashes after a few minutes of using as of today

### ISSUE THREAD

**Issue by ryandward** [microsoft/vscode-copilot-release#788]
Type: <b>Bug</b>

No steps to reproduce. Just having it installed crashes.

Extension version: 0.12.2024012401
VS Code version: Code - Insiders 1.86.0-insider (1091f68d834974d78cd4f9769034b4ae4581ff2a, 2024-01-24T05:35:58.929Z)
OS version: Linux x64 6.7.1-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|125.73GB (115.47GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id 82ac9485-e2d2-4cad-988f-73e4fa79c21a|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b5d27386:30943795
fegfb526:30945144
bg6jg535:30946824

```

</details>

**Comment by ulugbekna** [comment]
Hi @ryandward ,

Can you reproduce this issue with the latest vscode insiders and Copilot Chat pre-release versions? 

If yes, please provide logs from the output panel for Copilot Chat and developer console (invoke the vscode command "Developer: Toggle Developer Tools" to open dev console)

Output panel: 

<img width="1228" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/16353531/d0b07e9f-8993-4d9c-abfe-7b006d8e3f9e">

**Comment by ryandward** [comment]
It actually was quite intermittent, after 4-5 days and an update or two, it seems to have stopped altogether now. 

For reference, the complete freezing behavior frequently occurred even when there was no document being edited, with no repo open, and only this extension loaded. 

Not sure why VS code became so sluggish, even when system available resources over 100 gb and virtually no processing load. 

Thanks for checking in.

**Comment by nojoven** [comment]
Hi, Copilot makes VS Code crash minutes after the startup
![image](https://github.com/microsoft/vscode-copilot-release/assets/20012659/3b2cac00-7d0f-4fd4-bfbc-e259f90db062)

VSCode is very slow and crashes every time.

My system :
![image](https://github.com/microsoft/vscode-copilot-release/assets/20012659/0eaf11f8-36c4-42b7-bf87-cda94458b777)
 RAM 16GB
 Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Copilot: V1.156.0 
More Info
Published
2021-06-29, 16:26:17
Last released
2024-02-06, 02:36:09
Last updated
2024-01-31, 13:44:52
Identifier
github.copilot

@ulugbekna  What do you mean by "latest vscode insiders" ? How can I switch to pre-release ?
