### ISSUE TITLE
[Feature Request] Ability to stop generating text.

### ISSUE THREAD

**Issue by evowizz** [microsoft/vscode-copilot-release#79]
From time to time, I may either click the suggestions at the bottom by mistake, or I may send a query and realize I forgot something. In these cases, I have to wait for the response to be entirely generated. In most of these cases, I won't even read the answer, because I know that the part I forgot to add to my initial query is important.

In some cases I also happen to have the answer I needed in the first few lines, making it useless to generate the rest of the response.

A "Stop" button would prevent useless response generation. It would be beneficial for both Microsoft and its users. :)

**Comment by roblourens** [comment]
We now have a stop button :)
