### ISSUE TITLE
High CPU load on WSL

### ISSUE THREAD

**Issue by zerocom38** [microsoft/vscode-copilot-release#790]
Type: <b>Bug</b>

When installing copilot chat in the WSL extension, the CPU load of vmmemwsl raises to 50% to 90%, which degrates the system performance a lot. This happens with huge directories (yocto folder including build directory of yocto).

Extension version: 0.12.2024012401
VS Code version: Code - Insiders 1.86.0-insider (3dea5cbbcb88d7f6dad71148f3d3f98b853ab836, 2024-01-25T07:31:07.980Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Connection to 'wsl+debian' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (14.98GB free)|
|Process Argv|--crash-reporter-id 0173f5eb-c137-4a4e-8c62-f16e8dfa4f0d|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+debian' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b1063948:30943794
fegfb526:30945144
bg6jg535:30946824

```

</details>

**Comment by TylerLeonhardt** [comment]
@zerocom38 can you try with today's VS Code Insiders and Copilot Chat prerelease? We fixed this yesterday:

https://github.com/microsoft/vscode-copilot-release/issues/784

**Comment by zerocom38** [comment]
The problem seems to be fixed with the latest plugin. I was on Insider and Prerelease already and noticed it for some days. Reinstalling the latest plugin on the same folder works fine now.
