### ISSUE TITLE
Copilot Checking Prompt for Code Duplication

### ISSUE THREAD

**Issue by kelly-ogawa** [microsoft/vscode-copilot-release#791]
- VS Code Version: 1.85.2 (user setup)
- OS Version: Windows 10 Enterprise     Version	22H2     OS build	19045.3930
- Logs: [GitHub Copilot Chat.log](https://github.com/microsoft/vscode-copilot-release/files/14057596/GitHub.Copilot.Chat.log)

Steps to Reproduce:

1. ask a question about the code highlighted in the test file
2. ask the same question by copying/pasting it, not by using the up arrow
3. sometimes it will give the response "Sorry, the response matched public code so it was blocked. Please rephrase your prompt. Learn more." with a link to the code duplication policies

this doesn't seem to happen using the up arrow
this happens when i am not generating any new code, just trying to explain existing code
at least two other members in my organization have had the same issue

**Comment by bhavyaus** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have: https://github.com/microsoft/vscode-copilot-release/issues/2626. Please refer to that one for updates and discussions. Feel free to open a new issue if you think this is a different problem.
