### ISSUE TITLE
Creation of empty directories in place of files

### ISSUE THREAD

**Issue by kemko** [microsoft/vscode-copilot-release#794]
- VS Code Version: 1.85.2
- OS Version: MacOS Sonoma 14.3

Steps to Reproduce:

1. Ask Copilot Chat to create project with Dockerfile or Makefile or any other file without extension (for example `@workspace /new sample go project with a dockerfile`).
2. Press `Create Workspace` button
3. Github Copilot will create the described project, but will treat each file without extension as a empty directory.

**Comment by TylerLeonhardt** [comment]
@kemko this is fixed in the prerelease of the extension. You can install that through the VS Code extension pane or wait a week for the new version to drop.
