### ISSUE TITLE
[Bug] when pressing down key deletes all the text in the chat box

### ISSUE THREAD

**Issue by qequ** [microsoft/vscode-copilot-release#795]
- VS Code Version:
    1.85.2
    8b3775030ed1a69b13e4f4c628c612102e30a681
    x64
- OS Version: ubuntu 20.04
- Logs:

Steps to Reproduce: 
- open Copilot chat window
-  write text
- press down key

**Comment by roblourens** [comment]
This is fixed in vscode insiders
