### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by salientknight** [microsoft/vscode-copilot-release#796]
- VS Code Version: Version: 1.86.0-insider (Universal)
- OS Version: Mac 14.2.1 (23C71)
- Logs:

Steps to Reproduce:

1.Submit a question

Submitting questions results in the following error message: Cannot read properties of undefined (reading 'split')

**Comment by roblourens** [comment]
Can you check that you're using the pre-release version of the Copilot Chat extension, not the stable version, and the latest version of Insiders?

**Comment by chottuthejimmy** [comment]
Hey @roblourens I am facing the same issue, i asked a question it answered and its not answering anything after this. I am in the latest version of insiders and i am in the pre-release version of the extension as well

**Comment by OccultSlolem** [comment]
Can confirm, am facing the same issue.

**Comment by ness001** [comment]
Same issue here

**Comment by RPLaine** [comment]
I'm getting this error with Windows but not on Mac. I can always start a new chat to get answers, but this error prevents me to make a continued conversation.

**Comment by roblourens** [comment]
Can you please double-check that it is the pre-release extension, and share the extension version? This was reported multiple times before and we expect it when there is a version mismatch.

**Comment by chottuthejimmy** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/108192034/4f928338-6d82-40d7-8146-bae3210c2b97)
![image](https://github.com/microsoft/vscode-copilot-release/assets/108192034/6b6b149c-d76c-4b03-8dc0-135dd10f316a)

**Comment by OccultSlolem** [comment]
@chottuthejimmy I have both and this issue persists in both forms of chat.

**Comment by OccultSlolem** [comment]
@roblourens I got this issue on pre-release v1.155.677 and on the latest release as well:

`2024-01-29 07:38:38.134 [info] [extension] TypeError: Cannot read properties of undefined (reading 'split')
    at t.printMessageContent (/Users/ethanhanlon/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1251:85)
    at /Users/ethanhanlon/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5254
    at Array.map (<anonymous>)
    at t.logMessages (/Users/ethanhanlon/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1245:5183)
    at n1._provideResponseWithProgress (/Users/ethanhanlon/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1256:1173)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at n1.provideResponseWithProgress (/Users/ethanhanlon/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1254:2086)
    at i.y (/Users/ethanhanlon/.vscode-insiders/extensions/github.copilot-chat-0.11.1/dist/extension.js:1266:1022)
    at o.$invokeAgent (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:150:40137)`

**Comment by roblourens** [comment]
@chottuthejimmy your screenshot shows that you are not using the pre-release version of the Copilot Chat extension. @OccultSlolem your error stack shows that you also aren't using the pre-release version of the extension.

**Comment by wagnerone** [comment]
Piping in to say I'm in the same boat with 

vscode Version: 1.86.0-insider
Commit: 8c08612b658a37f96892f8ed5a9c6e7a6667847d

chat - v0.12.2024013003 (pre-release)

**Comment by roblourens** [comment]
@wagnerone can you also look for the full error in the Copilot Chat output channel

**Comment by chottuthejimmy** [comment]
> @chottuthejimmy your screenshot shows that you are not using the pre-release version of the Copilot Chat extension. @OccultSlolem your error stack shows that you also aren't using the pre-release version of the extension.

For me the issue has been fixed for now , I switched to pre-released version and it works fine for now

**Comment by andrewlucas-bg** [comment]
Started seeing this a lot today, but updating the extension seems to have fixed it.

**Comment by salientknight** [comment]
My issue seems to have resolved. Thank you

**Comment by victoreronmosele** [comment]
The issue came up right after I updated VS Code by clicking "Restart to update".

The issue got fixed after clicking "Reload Required" from the Copilot Extension.

**Comment by JhonDan1999** [comment]
Same issue here

**Comment by jiriperoutka** [comment]
same here

**Comment by JohannKaspar** [comment]
same here

**Comment by pshanmukha** [comment]
same here

**Comment by tinix84** [comment]
same here

**Comment by digitarald** [comment]
As many confirmed here, this is fixed on the latest 0.12 version.

👉  **Need help with updates? See https://github.com/microsoft/vscode-copilot-release/issues/838#issue-2116615394 for detailed steps**.

**Comment by Abu-Hurrara** [comment]
I am also getting the same error. I have paid subscription of copilot but now it says start your 30 days free trial.
When I click the button it takes me to github where it says I already have
a paid subscription.

copilot version: 1.159.0
copilot chat version; 0.12.0

**Comment by edraghiciu-vks** [comment]
Same here

**Comment by razzededge** [comment]
Got the same problem after recent update of VSCODE

**Comment by razzededge** [comment]
> got the same problem on mac just need to update the extensions and reload it and that resolve it.

I confirm, update resolved the issue (update of extensions)
