### ISSUE TITLE
Responses are not in the language used to ask the question

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-copilot-release#797]
Type: <b>Bug</b>

Copilot responds in english for a question asked in Kannada:
![image](https://github.com/microsoft/vscode-copilot-release/assets/3840081/a9abcb11-1e46-4cd3-9f51-712e48f1bb85)

Kannada prompt:
ನಾನು ರಸ್ಟ್‌ನಲ್ಲಿ ವೆಬ್‌ಸೈಟ್ ಬ್ಯಾಕೆಂಡ್ ರಚಿಸಲು ಬಯಸುತ್ತೇನೆ. ಅದಕ್ಕೆ ನನಗೆ ಬೇಕಾದ ಪ್ಯಾಕೇಜ್‌ಗಳು ಯಾವುವು? ನನಗೆ ಟೈಪ್‌ಸ್ಕ್ರಿಪ್ಟ್ ಪ್ರಾನ್ಟ್ಎಂಡ್ ಬೇಕು. ನೀವು ನನಗೆ ಕಾರ್ಯಕ್ಷೇತ್ರವನ್ನು ಹೊಂದಿಸಬಹುದೇ?

Extension version: 0.12.2024012601
VS Code version: Code - Insiders 1.86.0-insider (feff7c8a7e1c82320380f42d898a1e03051fefb7, 2024-01-26T03:26:40.730Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (15.85GB free)|
|Process Argv|--folder-uri file:///c%3A/GIT/TPI/jan2024/simpleweb --log info --crash-reporter-id 4fb1ebc1-cf4c-4880-a88a-47738ec3768d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vsc_aacf:30263846
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:30784851
c4g48928:30535728
vscrpc:30624061
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
b1063948:30943794
fegfb526:30945144
bg6jg535:30946824

```

</details>

**Comment by TylerLeonhardt** [comment]
@joyceerhl my guess is that this is really on the model to respond in Kannada, but I wanted to rule out your language work just in case. Is it possible your work would affect this?

**Comment by karthiknadig** [comment]
Asking the same prompt again it responds in kannada:
![image](https://github.com/microsoft/vscode-copilot-release/assets/3840081/0238228a-9e51-4bd9-8f2f-2f2b9e5ebb5e)

**Comment by karthiknadig** [comment]
It is not consistent, it keeps going back and forth between english and kannada:
![image](https://github.com/microsoft/vscode-copilot-release/assets/3840081/7a6ede25-b42d-4b68-96c8-eeedd5b52ba3)

**Comment by joyceerhl** [comment]
@karthiknadig do you have VS Code set to use a display language other than English? That's the only thing that might influence the outcome here. If it's just using English, then this wouldn't have anything to do with the locale rules,

**Comment by TylerLeonhardt** [comment]
@joyceerhl Does our base prompt tell the model to respond in the same language or has it just been a coincidence that it works?

**Comment by joyceerhl** [comment]
It's always "just worked"

**Comment by bhavyaus** [comment]
@joyceerhl is there a prompt element to help add this instruction?
