### ISSUE TITLE
Code generation on copilot extension on vscode after prompt to reply in markdown bug

### ISSUE THREAD

**Issue by RicardoGEsteves** [microsoft/vscode-copilot-release#798]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1. Prompt copilot chat extension to generate code in markdown. 
2. It fails to render all the code in markdown after the first block of 
```bash
code
``` 

![vscode-copilot](https://github.com/microsoft/vscode-copilot-release/assets/30535937/315bb3d9-6906-4c3c-b33b-9563bc4aab3d)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/470 and https://github.com/microsoft/vscode-copilot-release/issues/793
