### ISSUE TITLE
Chat feature not available

### ISSUE THREAD

**Issue by HotSauceTea** [microsoft/vscode-copilot-release#8]
- VS Code Version:
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (6 days ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No
- OS Version:
Venture 13.1
- Logs:

Steps to Reproduce:

Hello, I'm very excited to try Copilot Chat! However, I'm having trouble using it. I'm using VSc Code Insiders, and I've installed the Github Copilot Nightly Extension, but I don't see the chat icon in the activity panel. I confirmed that Copilot is connected by checking that autocomplete functionality works. I've tried restarting VS Code and my computer and that didn't work.

The screenshot below should show that 1. chat icon is missing 2. I have Github Copilot Nightly Installed and 3. Copilot is working (by completing my code).

Thanks for your help!

![image](https://github.com/microsoft/vscode-copilot-release/assets/65139469/23f319cf-bc6e-403b-9d23-bdd4d3154195)

**Comment by Qasszls** [comment]
Can you switch to version 1.79.0 and give it a try?
<img width="1079" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/42531952/07f45bf6-d774-4d06-adb6-c38be731eda8">

**Comment by HotSauceTea** [comment]
Thanks for the quick response! Where can I find v1.79? Here it looks like it hasn't been released yet: https://code.visualstudio.com/updates/v1_79

**Comment by Qasszls** [comment]
Maybe if you look in the mailbox, there should be an address in the invitation email to download it.😁

**Comment by HotSauceTea** [comment]
I did follow the link :) It brought me here: https://code.visualstudio.com/insiders/ and I downloaded the most recent version. At the top of the page, I see a banner that says "Version 1.78 is now available! Read about the new features and fixes from April." That makes me think that 1.79 isn't publicly available yet.

**Comment by Qasszls** [comment]
Oh, I guess that misled you. But when I clicked Download, it was version 1.79.0.

**Comment by HotSauceTea** [comment]
I tried downloading it again and it worked! Not sure how I got the wrong version the first time, but it's working now, thanks so much for your help! :)

**Comment by Qasszls** [comment]
nice




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/vscode-copilot-release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/vscode-copilot-release] Chat feature not available (Issue #8)





 
I tried downloading it again and it worked! Not sure how I got the wrong version the first time, but it's working now, thanks so much for your help! :)

**Comment by jeffscottward** [comment]
> I tried downloading it again and it worked! Not sure how I got the wrong version the first time, but it's working now, thanks so much for your help! :)

I second this, they somehow deployed the wrong build, and just re-downloading insiders worked
