### ISSUE TITLE
Ability to reposition the Chat Window without moving the side bar

### ISSUE THREAD

**Issue by c42alyst** [microsoft/vscode-copilot-release#80]
a. Ability to reposition the Chat window to a different place independent of the side bar, 
b. if we can pop out into a separate window that would be ideal

Many thanks for the efforts, it is an amazing productivity boost.

**Comment by RogerBarreto** [comment]
Already mentioned here #60

**Comment by NikiLentz** [comment]
you can simply drag it to the right side, afaik.
