### ISSUE TITLE
GitHub Copilot Chat can lose the entire prompt contents due to arrow key scrolling.

### ISSUE THREAD

**Issue by TrevorBenson** [microsoft/vscode-copilot-release#804]
# Description
While editing prompts in Copilot if the user needs to scroll up or down to modify the prompt or correct a mistake and the cursor moves beyond the first or last line of the prompt the entire text is lost. Either the previous interaction, when scrolling too far up, or an empty prompt, when scrolling too far down, is provided. 

If the user then tries to navigate back, the prompt has already been cleared entirely. This results in the loss of the current prompt content, requiring the user to recreate it from scratch.

- VS Code Version: 1.85.2
- OS Version: Fedora 39
- Logs:

# Steps to Reproduce:

1. Open CoPilot chat.
2. Fill in the prompt.
3. Scroll up until reaching the first line and press up once more, or scroll down until reaching the last line and press down once more.
4. Observe the prompt is changed to either an empty prompt, or the last submitted prompt.
5. Try to go back and observe that you do not get the contents back.

# Additional Context
It is too easy to lose a prompt currently being created. This leads to wasted time trying to recreate a prompt, especially when context and additional details are being provided to try and improve the response or correct prior incorrect or unuseful responses.

I've tested this with multiple other chat-oriented AI plugins for vscode and did not find this behavior in any of them.

**Comment by virtuallyunknown** [comment]
What a coincidence, I was just about to open an issue on the same problem and then I saw yours! Here is a demonstration of the problem.

https://github.com/microsoft/vscode-copilot-release/assets/24871108/08c61f83-6f20-4a4a-b17e-e8a2f27c78d3

I've lost count how many times I've lost my entire message because I accidentally pressed UP an additional time, either by some habit or accident.

Please, someone address this, I'd be very grateful.

**Comment by TrevorBenson** [comment]
> I've lost count how many times I've lost my entire message because I accidentally pressed UP an additional time, either by some habit or accident.

Yep! Last week I frustratingly did this at least twice (pretty sure it was three times) on a single prompt. That was after spending quite a few minutes painstakingly formatting the prompt. There were other prompts lost that day as well, just not quite as frustrating, or that cost nearly as much time trying to precisely recreate them.

**Comment by roblourens** [comment]
Sorry for the pain. This is fixed in Insiders.

**Comment by virtuallyunknown** [comment]
Thanks a lot for the quick response @roblourens, appreciated!

**Comment by TrevorBenson** [comment]
> Sorry for the pain. This is fixed in Insiders.

Thank you very much @roblourens!

**Comment by noxgear-simon** [comment]
I'm new to GitHub, but when will this fix be released?

**Comment by TrevorBenson** [comment]
> I'm new to GitHub, but when will this fix be released?

It's released. Yesterday I updated to 1.86.0-1706698221 and the fix works perfectly.
