### ISSUE TITLE
The code action UI covers code and interferes with editing

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-copilot-release#807]
- VS Code Version:Version: 1.86.0-insider (user setup)
Commit: 8c08612b658a37f96892f8ed5a9c6e7a6667847d
Date: 2024-01-30T21:44:10.295Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621
- Logs: I'm using GitHub Copilot Chat v0.12.2024013003 (pre-release)

Steps to Reproduce:

1. Create a new test.cpp file and enter code "int ii;"
```cpp

int ii;

```
3. Try to double click on "int" to change it to something else like "double".

Bug: The code action for Copilot is blocking my ability to select "int".

<img width="236" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/19859882/16a68d77-5fc3-4e93-8475-238eace4438e">

Expected: Can you do something to make it not render over the code I want to edit? I couldn't figure out a good way to get it to move out of the way.

UPDATE: I figured out a workaround -- moving the keyboard cursor to that line (2) causes the icon to move. With my repro, my cursor was on line 3.

**Comment by AngeloAmadei** [comment]
The extension opens a handy chat if you click the extension chat icon on the left panel, and also gives the opportunity to open an inline chat by pressing Ctrl+I. All of this is great, just a single click or two keys combo to access the chat. Now, showing inside the editor a moving plus signs icon every time the cursor is in an empty line, overlapping with the beginning of any line of code above it, is very distracting to me, kind of unnecessary, and not even aligned with the demo video the extension shows in vscode. I would loved to have an option to turn that off

**Comment by sean-mcmanus** [comment]
This bug appears to be fixed for me. Or the repro has changed or some setting added to control it, because I don't see the spark icon anymore.
