### ISSUE TITLE
GitHub Copilot won't reference two files

### ISSUE THREAD

**Issue by TaylorHuston** [microsoft/vscode-copilot-release#809]
- VS Code Version: 1.85.2
- OS Version:
- Logs:

Steps to Reproduce:
Context: I have two terraform files in adjacent directories
web-app/main.tf
provision/main.tf

1. Ask Copilot 'what does web-app/main.tf do'. This is to double check that Copilot can see this file. It returns an appropriate explanation.
2. Ask 'Why does the plan for web-app/main.tf want to delete the resources in provision/main.tf'. It will use 1 reference, provision/main.tf and give you some suggestions, but ends with the statement 'To provide a more accurate answer, I would need to see the web-app/main.tf and provision/main.tf files.'

I am unable to get it to properly 'see' both files at the same time to give me an accurate answer.

**Comment by joyceerhl** [comment]
@TaylorHuston does this work better when you use the `@workspace` agent, i.e. your question would be `@workspace Why does the plan for web-app/main.tf want to delete the resources in provision/main.tf`?

**Comment by laillatoyumi** [comment]
I'm getting exactly the same issue, help appreciated please!

**Comment by joyceerhl** [comment]
@laillatoyumi can you please share a screenshot of the question you're asking and ideally the repo in which it occurs

**Comment by laillatoyumi** [comment]
> @laillatoyumi can you please share a screenshot of the question you're asking and ideally the repo in which it occurs

<img width="2672" alt="Screenshot 2024-02-07 at 16 31 42" src="https://github.com/microsoft/vscode-copilot-release/assets/142615402/621fc02b-7206-43ea-96fb-87844c66cfa7">

I have multiple files open and vs code is only reading the current file selected

**Comment by lramos15** [comment]
You should use `#file` which allows you to explicitly include files that are open in other tabs. Take a look at `#` for a wide variety of other variables to build rich prompts

**Comment by laillatoyumi** [comment]
That's kind of ridiculous this was closed after no response for weeks.

**Comment by lramos15** [comment]
@laillatoyumi I just gave you the solution to your problem? Is there something wrong with my suggested fix?

**Comment by laillatoyumi** [comment]
It's not really a good fix because a few months ago the files being read
were automatically whatever was open. To manually say/ref every open file
is quite cumbersome for each and every question (especially as there is no
history). Why did this feature once exist and no longer exist? (regarding
reading open tabs/files).

**Comment by sudoxnym** [comment]
Hold ctrl when you hit enter on your prompts, it grabs the entire workspace
