### ISSUE TITLE
Copilot Chat not responding to @workspace: vscode extension host terminated unexpectedly

### ISSUE THREAD

**Issue by BenLJM** [microsoft/vscode-copilot-release#810]
Type: <b>Bug</b>

Copilot Chat gives no response when using @workspace(only shows extension host terminated unexpectedly). Everything else works fine. It looks like it stucks at the step of gathering worksapce info.

![image](https://github.com/microsoft/vscode-copilot-release/assets/35580709/b0fa91c6-befe-4f0e-9899-d429440d7e38)

After reload the window:
![image](https://github.com/microsoft/vscode-copilot-release/assets/35580709/77ea1e0d-0c02-4301-b6c4-96c2e5960bda)

Extension version: 0.12.2024013003
VS Code version: Code - Insiders 1.86.0-insider (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T03:29:26.801Z)
OS version: Linux x64 5.15.0-88-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz (40 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|13, 12, 7|
|Memory (System)|62.48GB (49.94GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3853ecd2-1bd1-4879-8ef5-52d79dcc1b68|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
8082a590:30953407
b5d27386:30943795
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp1r6:30950905

```

</details>

**Comment by porterlyman** [comment]
I've been getting this whenever @workspace is used. 
![image](https://github.com/microsoft/vscode-copilot-release/assets/116583797/55ce38be-5583-4766-9601-9d269fde3a0c)

**Comment by bgpedersen** [comment]
Im getting the same kind of crash errors everytime i try to use the `@workspace` agent command. 

I also tried to create a workspace file in my root dir of the project, if the command maybe was leaking out to to parent projects (our project is nested within projects, but the current project is opened as a directory, so it shouldn't matter). But with same results.

![image](https://github.com/microsoft/vscode-copilot-release/assets/3582953/7079d227-7e8a-4a0c-b6ac-0f9cfc20acdf)

**Comment by mjbvz** [comment]
Sorry for not following up. This was fixed a while back by moving all of the indexing work into worker thread

If you are still seeing any perf issues related to `@workspace` with the current release, please open an new issue and I'll take a look
