### ISSUE TITLE
@workspace not working

### ISSUE THREAD

**Issue by toh-ableton** [microsoft/vscode-copilot-release#814]
- VS Code Version: Version: 1.86.0 (Universal)
- OS Version: 14.4 Beta (23E5180j)
- Logs:

Steps to Reproduce:
1. I asked @workspace a simple question about my workspace.

Expected Results:
An answer within a reasonable timeframe.

Actual Results:
No answer after about an hour. Activity Monitor shows that VS Code is using ripgrep to scan every single file in my workspace. There are 161807 files in my workspace, with a total of 106GB of contents. I don't think this approach can work for workspaces of this size.

**Comment by mjbvz** [comment]
A few questions about your workspace:

- How many of those files are normal content vs stuff like data and logs?
- Are some of the files/folders in `.gitignore`?

**Comment by toh-ableton** [comment]
- A very large part of this is generated build outputs, and they are all under `.gitignore`.
- About 60000 files are normal content (source code, text files, and the like).
