### ISSUE TITLE
After asking a question, the "Thinking..." and [Cancel] UI elements don't go away

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-copilot-release#817]
- VS Code Version:Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621
- Logs: version  v1.156.0

Steps to Reproduce:

1. See my screenshot:
<img width="301" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/19859882/a017f333-4a48-49e9-803b-8249fa03933d">

**Comment by roblourens** [comment]
Can you check for errors in the "Window" or "Copilot Chat" output channels? Thanks

**Comment by ilchenkoArtem** [comment]
I have the same issue but in Web Strom... Always thinking...

<img width="448" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/33321841/b7fd6855-eac3-4ee9-9e12-b8a1320b3258">

**Comment by sean-mcmanus** [comment]
@roblourens I don't repro the bug anymore.

**Comment by sean-mcmanus** [comment]
@roblourens I just reproed the issue again when connected to Ubuntu 22 via WSL. The Window log says

2024-02-12 15:07:40.946 [error] Sorry, this message is too long. Please try a shorter question.: Error: Sorry, this message is too long. Please try a shorter question.

**Comment by sean-mcmanus** [comment]
@roblourens After resizing the left pane, the UI becomes "messed up" and shows previously answers to my most recent question, e.g.

<img width="632" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/19859882/ddcc3852-8c89-42d7-a411-65ff9d67dd4f">

**Comment by sean-mcmanus** [comment]
@roblourens It appears to show a random previous answer after using the scrollbar in the panel.

<img width="553" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/19859882/7012ba90-e845-4698-a71a-7c74046ccba4">

**Comment by sean-mcmanus** [comment]
@roblourens When that happens, the "correct answer" disappears from the UI, replaced by a previous question's answers.

**Comment by roblourens** [comment]
Can you check for errors in the "Window" or "Copilot Chat" output channels?

**Comment by sean-mcmanus** [comment]
@roblourens I already provided that info in comment https://github.com/microsoft/vscode-copilot-release/issues/817#issuecomment-1939760333 .

To repeat, the Window log says

2024-02-12 15:07:40.946 [error] Sorry, this message is too long. Please try a shorter question.: Error: Sorry, this message is too long. Please try a shorter question.

If you can't repro the issue via connecting to a remote machine (WSL), I could ask others on my team if they repro it as well.

**Comment by roblourens** [comment]
From all the symptoms you describe, I'm pretty sure something in the list rendering flow is throwing exceptions, because that's what generally happens. You don't see any other errors in the window log though?

Not sure whether the "message too long" error is related, although I don't follow how you got that, is this a conversation with a long history? Did you have a selection in an open editor when this happened?

**Comment by sean-mcmanus** [comment]
@roblourens Today it's not reproing, but it starts reproing again I can provide more info.

**Comment by sean-mcmanus** [comment]
@roblourens I'm reproed the issue again and now in the non-remote scenario. The only error I get in the Window log is "[error] Sorry, this message is too long. Please try a shorter question.: Error: Sorry, this message is too long. Please try a shorter question.". The chat conversation was somewhat long, since it had a scrollbar. I don't think I had any selection in the editor, but it's in the C++ scenario so it sends the current file as a "reference". I found a potential workaround via using the "New Chat" to clear the chat history and that seems to fix it, although I'm guessing I'll re-hit the issue later on after the chat gets longer.

**Comment by roblourens** [comment]
Sorry for no response @sean-mcmanus but I wasn't sure what to do about this. Have you seen it again? Quite a lot has changed

**Comment by sean-mcmanus** [comment]
@roblourens Yeah, it appears to be fixed now or I don't repro it anymore. I'll close it.
