### ISSUE TITLE
Copilot Chat Plugin CPU Usage Too High

### ISSUE THREAD

**Issue by R4v3nl0** [microsoft/vscode-copilot-release#819]
Type: <b>Bug</b>

enable the `GitHub Copilot Chat` plugin, and open any python project(may other can too), cpu usage on my macbook will go from 18% to 184% or higher..

Extension version: 0.10.2
VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 7, 7|
|Memory (System)|32.00GB (12.00GB free)|
|Process Argv|--crash-reporter-id 859e86ff-9fec-4d23-9f3f-cd10fd2117f9|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30951796
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by aeschli** [comment]
Are you sure this originates from the Copilot extension? 
Can you open the `Running Extensions` view (Command: `Developer: Show Running Extensions`) and click on the `Start Extension Host Profile` button to get more information on running processes.
Also, opening the `Process Explorer` (Help > Open Process Explorer` can be useful to see what processes are using the CPU.

**Comment by R4v3nl0** [comment]
> Are you sure this originates from the Copilot extension? Can you open the `Running Extensions` view (Command: `Developer: Show Running Extensions`) and click on the `Start Extension Host Profile` button to get more information on running processes. Also, opening the `Process Explorer` (Help > Open Process Explorer` can be useful to see what processes are using the CPU.

When I enable `Github Copilot Chat` plugin, the `Process Explorer` show me:
<img width="798" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/41482088/a7eadae0-ae81-4ec2-90ef-61bde49ea134">

And after disable this plugin, it show me:
<img width="802" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/41482088/ae5ba581-3696-47d9-abae-56bfcd16c42f">

**Comment by R4v3nl0** [comment]
`Github Copilot Chat` plugin version: `v0.10.2`
I asked my colleague who uses the Windows operating system and he didn't seem to have this problem :(
Maybe it's a bug on MacOS?

**Comment by R4v3nl0** [comment]
Oh, I'm sorry, it's my fault..
I forgot to update copilot's version...🤣
I upgrade to the latest stable version, the problem doesn't happen again
