### ISSUE TITLE
Chat history

### ISSUE THREAD

**Issue by ShayGus** [microsoft/vscode-copilot-release#82]
After a prompt had disappeared, there's no way of seeing the prompt history.
When a code was generated  by a prompt it's important to see what prompt had created it.

**Comment by roblourens** [comment]
You can navigate prompt history with the arrow keys, is that what you're looking for? You can also now see a history view of past chat sessions with the new button in the view toolbar

**Comment by bnegrao** [comment]
i would like to see the code chat history too, i can't find it. 
I am looking a prompt I sent when I selected a text in the editor, mouse right click -> copilot -> start code chat.

I can't find that prompt anywhere.

**Comment by roblourens** [comment]
That history can be navigated with the keybindings in the placeholder, if that history is in this workspace

<img width="513" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/323878/ad143c47-a36a-44ee-aaea-3ca0e4c16c65">
