### ISSUE TITLE
Use only one command prefix

### ISSUE THREAD

**Issue by rswerve** [microsoft/vscode-copilot-release#820]
Currently, Copilot chat supports slash / pound # and at @ prefixes for commands.  Forcing the user to remember which prefix goes with which command is unnecessary and creates cognitive overhead.  If I want the codebase it's an @, but if i want a file it's a #.  I understand that it's supposed to distinguish between broader contextual commands and more targeted ones, but as a user, I don't care about that distinction.  I just want to muscle-memory my magical chat invocation.

Thanks!

**Comment by roblourens** [comment]
These prefixes all have different meanings. 

All commands go to an agent with `@` (or the default agent with no `@`). Agents can have subCommands that you invoke with `/`. Context variables with `#` can be passed to any agent, including `@workspace`. I get that it's a little confusing, but I'm hoping people will get used to it over time.
