### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by phuongtt-its** [microsoft/vscode-copilot-release#822]
- VS Code Version: v0.7.2023090101
- OS Version:
     Model Name:	MacBook Pro
    Model Identifier:	MacBookPro18,3
    Chip:	Apple M1 Pro
    Total Number of Cores:	8 (6 performance and 2 efficiency)
    Memory:	16 GB
    System Firmware Version:	7459.141.1.700.1
    OS Loader Version:	7459.141.1.700.1
    Serial Number (system):	T6V0H44XPP
    Hardware UUID:	2E1148D7-D113-545B-821A-EB3022B77566
    Provisioning UDID:	00006000-001264D13CFA401E
    Activation Lock Status:	Disabled
- Logs:
  Always response: "Oops, your response got filtered. Vote down if you think this shouldn't have happened."
Steps to Reproduce:

1.
2.

**Comment by joekrump** [comment]
Examples of things I'm asking where I get this response:
- "what does this line do?"
- "what is a <button> element used for in HTML?"
- "why might I be getting the following error: <post error>?"

Starting about 8 hours ago, every question I ask gets the "Oops, your response got filtered. Vote down if you think this shouldn't have happened." response. 

I've tried restarting my computer, signing out and back into GitHub in VSCode. Closing and reopening VSCode. So far no luck.

**Comment by sudiptabm** [comment]
I'm getting similar, error, does anyone have idea how to fix it?

**Comment by Rahulreddy1020** [comment]
same here

**Comment by sevenblack3166** [comment]
same here

**Comment by EricLabile** [comment]
Same here TnT

**Comment by Benji1309** [comment]
same here, for every question, even very simple (as print "Hello world")

**Comment by it-is-i** [comment]
same

**Comment by marreddysr** [comment]
same here since this morning

**Comment by postaluka** [comment]
same Macbook pro 2019 Ventura 13.5.1

**Comment by samepatw** [comment]
It is happening for me as well. I am a windows user.
VS Code version: 1.82.0

**Comment by navyaGenpact** [comment]
Same issue I'm facing as well. I am a windows user.
VS Code version: 1.82.2

**Comment by lramos15** [comment]
Please ensure you're on the latest VS Code and latest Copilot chat then include your logs, via `CMD / CTRL + SHIFT + U` -> `Copilot Chat`

**Comment by VincenzoKoestler** [comment]
Same error, cannot use the chat anymore:
```
24-02-02T15:04:37.135Z [INFO] [chat fetch] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions], took 160 ms
2024-02-02T15:04:37.137Z [ERROR] [chat fetch] Unhandled status from server:,410,{"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.7.1","editor-version":"vscode/1.82.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}
```

**Comment by joekrump** [comment]
The fix for me:

Update VS Code. 
<img width="276" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/3317231/f2102fd9-c8b3-4f2b-befc-f0ec5aa26fd4">

When I tried this the first time it said I couldn't update though and it turns out this is because Visual Studio Code was in my Downloads folder and with a recent MacOS update, that prevents it from being able to be updated. See [here](https://github.com/microsoft/vscode/issues/7426).

I then:
1. shut down VS Code
2. dragged and dropped it from `Downloads` into `Applications`. 
3. Opened again
4. Tried updating _(see screenshot above)_ and it worked!
5. Restarted VS Code and went to the Extensions explorer and click on the button next to GitHub Copilot chat extension for "reload required"
6. VS Code restarted.
7. Tested it out, and it works!

So I think the key problem was I was missing critical updates that I used to get automatically since my VS Code installation was in the Downloads dir. 

Thanks for pointing me in the right direction @lramos15!

**Comment by EricLabile** [comment]
> Please ensure you're on the latest VS Code and latest Copilot chat then include your logs, via `CMD / CTRL + SHIFT + U` -> `Copilot Chat`

Fixed. Thx :)

**Comment by VincenzoKoestler** [comment]
my mistake, issue fixed. VS Code was outdated (corporate device), newest Version in userMode fixed the issue.

**Comment by it-is-i** [comment]
> same

Solved with vscode update as mentioned below.

**Comment by Nurmaan** [comment]
Fixed for me:
- I switched to pre-release version 1.156.688
- Uninstalled vs code
- Downloaded the latest version of the software
- Reinstalled it

**Comment by silcro-123** [comment]
> * shut down VS Code
> * dragged and dropped it from `Downloads` into `Applications`.
> * Opened again
> * Tried updating _(see screenshot above)_ and it worked!
> * Restarted VS Code and went to the Extensions explorer and click on the button next to GitHub Copilot chat extension for "reload required"
> * VS Code restarted.
> * Tested it out, and it works!

Thank you very much, fixed for me

**Comment by shen-qin** [comment]
> The fix for me:
> 
> Update VS Code. <img alt="image" width="276" src="https://private-user-images.githubusercontent.com/3317231/301883321-f2102fd9-c8b3-4f2b-befc-f0ec5aa26fd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTgyNDgsIm5iZiI6MTcwOTE5Nzk0OCwicGF0aCI6Ii8zMzE3MjMxLzMwMTg4MzMyMS1mMjEwMmZkOS1jOGIzLTRmMmItYmVmYy1mMGVjNWFhMjZmZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjlUMDkxMjI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2NlYjA0YmY4NTU1Y2QyNThiZDBmYTdhMGQ2NGU1N2FlODk3ZjE2NWVmYTJjNDVhYjIyOTA4MTY4YjgxNTk5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z46Ef7o4Ru4tIsYhJeoMAbrvlfdQNj0RjEgjOuhrvXo">
> 
> When I tried this the first time it said I couldn't update though and it turns out this is because Visual Studio Code was in my Downloads folder and with a recent MacOS update, that prevents it from being able to be updated. See [here](https://github.com/microsoft/vscode/issues/7426).
> 
> I then:
> 
> 1. shut down VS Code
> 2. dragged and dropped it from `Downloads` into `Applications`.
> 3. Opened again
> 4. Tried updating _(see screenshot above)_ and it worked!
> 5. Restarted VS Code and went to the Extensions explorer and click on the button next to GitHub Copilot chat extension for "reload required"
> 6. VS Code restarted.
> 7. Tested it out, and it works!
> 
> So I think the key problem was I was missing critical updates that I used to get automatically since my VS Code installation was in the Downloads dir.
> 
> Thanks for pointing me in the right direction @lramos15!

Yep, fixed with this. Thank you very much :)

**Comment by pkatakam** [comment]
updating vscode worked for me too .

**Comment by starball5** [comment]
So many issue tickets about this... #848, #875, #882, #969, #980, #984, #986, #992 how many are actually about unique issues?

**Comment by oscar-dong** [comment]
yes, after reinstall vs code, it worked for me.

**Comment by lramos15** [comment]
Closing as the message has been updated to be more clear here, please ensure you're on the latest version and if still experiencing an issue file a bug. Thanks!

**Comment by pkatakam** [comment]
yeah Installing latest version fixed for me too.

**Comment by feed0** [comment]
My VSCode was installed in `/Users/>my_name</Downloads/`. 

1. I saved my open work.
2. Quitted the app.
3. Draged from downloads to applications on Finder
4. command palette (cmd + shift + p): check for updates

BOOM. Solved.
