### ISSUE TITLE
Stop chat output when mouse hover a code box

### ISSUE THREAD

**Issue by gnllucena** [microsoft/vscode-copilot-release#823]
I would like for the chat to stop scrolling when I hover a code box.

It would be much easier to copy the output of trivial actions:

<img width="677" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/2061623/0467ceff-61ae-4c5d-88bc-4dad2d4017a1">

**Comment by roblourens** [comment]
I don't think I want to do it exactly like this, because it would be easy to trigger by accident. But I recognize the issue and have this issue open where I will try to make some improvements

https://github.com/microsoft/vscode-copilot-release/issues/138
