### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by Spike433** [microsoft/vscode-copilot-release#826]
- VS Code Version: 1.83
- OS Version: Windows 10

Steps to Reproduce:

I'm using students license and chat works well in Visual Studio but it fails in VSC.

![image](https://github.com/microsoft/vscode-copilot-release/assets/24856398/7a655218-6fbd-441a-a8b3-88a749ee41bf)

More info in closed [issue](https://github.com/microsoft/vscode-copilot-release/issues/295#issuecomment-1923552903)

**Comment by xKoutsi** [comment]
I am having the same issue, except I'm using the individual license.  Tried Pre-release and release versions. Both fail.

**Comment by lramos15** [comment]
Please update your copilot chat extension as well as your version of VS Code to the latest. You're on a much older version that we've deprecated as you can see by the message in the logs. 

Once you've updated send new screenshots. Thanks!

**Comment by quocvuong2000** [comment]
same issues, very frustrating

**Comment by lramos15** [comment]
@quocvuong2000 Did you make sure you're on the latest vs code + copilot. This is caused by using deprecated versions

**Comment by digitarald** [comment]
As we pointed out, please update your VS Code (Command: `Check for Updates...`) + Copilot Chat extension (Command: `Extensions: Update All Extensions`).

**⚠️ Both VS Code and the extension need to be updated**, as the latest release of Copilot Chat requires the latest release of VS Code.

**If you can't update, please share what blocks you from updating** here so we can better understand and improve this process in the future.

**Comment by Spike433** [comment]
The issue was that I was using VSC 1.83 version and I was unable to get Copilot Chat 0.12, rather 0.8..

After updating it to **1.86**, **Copilot 0.12** was downloaded automatically.
