### ISSUE TITLE
Copilot Chat cannot see files unless text is highlighted.

### ISSUE THREAD

**Issue by Cohors1316** [microsoft/vscode-copilot-release#827]
Copilot version: 1.156.0
Chat version: 0.12.0

Originally experienced this in VSC for windows. Updates, restarts, and reboots did not fix.
Opened up a new default codespace in the web and it experienced the same issue.
Copilot seems incapable of reading files unless text is highlighted, and even then it can only see the highlighted text. Asking it a question related to a file results in `I'm sorry for the confusion, but as an AI, I don't have the ability to directly access or view your files. Could you please paste the code you want me to explain here?`
Also tested pre-release versions and experienced the same issues.

To be a little more explicit, When entering a prompt without any text lightlighted Chat does not indicate it has any references, whereas if I highlight something it does show that the file is referenced.

Other peculiar notes:
- It really, really likes to identify as an OpenAI tool rather than copilot.
- `/clear` no longer is a valid command. Earlier while trying to debug it acknowledged `/clear` as a command, said it was clearing, but did not actually do so. Eventually it just started telling me I can't do that, and `/clear` no longer shows under commands.
- I originally was dealing with the `Cannot read properties of undefined (reading 'split')` error before this, so do not know if it is directly related.

edit: tried to use copilot inline and got error `command 'inlineChat.start' not found`

**Comment by roblourens** [comment]
We've changed the default context to only look at selected code by default. You can use the `#editor` variable to include the visible code from the active text editor. Details: https://code.visualstudio.com/updates/v1_86#_default-context-in-chat

`/clear` is now `/newChat`

As far as I know, that error will only come up when the Copilot Chat extension version doesn't match the VS Code version, so just make sure that everything is fully up to date

**Comment by Cohors1316** [comment]
I guess I missed that change. I did notice that using the command pallet to start copilot chat results in the old behavior of including the active file by default. Don't know if thats intended or if it got missed.

**Comment by Rednas83** [comment]
> As far as I know, the 'split' error will only come up when the Copilot Chat extension version doesn't match the VS Code version, so just make sure that everything is fully up to date.

I had the same issue and indeed updating Copilot Chat extension fixed the issue for me. Is it not possible to do a version check when running copilot and display an error something like 'Copilot Chat extension is outdated. Please update!'?

**Comment by simoncpu** [comment]
I thought something was borked in my specific configuration. Copilot also stopped working for me a few days ago.

**Comment by meleyal** [comment]
@roblourens can this be a configuration option? 90% of the time I'm referring to code in the current file.

**Comment by alexdima** [comment]
> edit: tried to use copilot inline and got error command 'inlineChat.start' not found

The inline chat error will be addressed with the upcoming VS Code 1.86.1 recovery release (via https://github.com/microsoft/vscode/pull/204113)

**Comment by kawada711** [comment]
Still not working most of the time, but at least the monthly cost is the same regardless if the advertised functionality is working or not.

**Comment by moriartyb** [comment]
Quick Fix -> "Explain Using Copilot" puts the error in Copilot Chat with "@workspace /explain" which does not give copilot chat the context of the file or code which caused the error. This greatly limits the ability of the chat to explain the error being seen. 

It seems like the action should do "#editor /explain" instead (which works), or @workspace /explain should actually be able to read the file which output the error.

It seems "@workspace /explain" is supposed to "explain how the selected code works", but when you see red squiggles for an error, and select a quick fix to explain the error, you have no code selected, so it loses the context.

**Comment by Briaoeuidhtns** [comment]
even using #editor or #file, it randomly can't access files:
```
Briaoeuidhtns
what does this sql server express error log mean? #file:Detail_Rules.txt

GitHub Copilot
I'm sorry, but as an AI programming assistant, I can't access or view files on your system, including the Detail_Rules.txt file. However, I can help you interpret the error messages if you provide them. Please copy and paste the relevant parts of the error log, and I'll do my best to assist you.

Briaoeuidhtns
what about #editor ?

GitHub Copilot
The term "editor" in the context of Visual Studio Code refers to the main area where you can open and edit files. You can have multiple editors open side by side, either in the same or different editor groups. The active editor is the one that currently has focus. You can perform various operations on the editor like opening, closing, and switching between files, modifying the content of the files, and so on.
```

**Comment by roblourens** [comment]
When you have issues like that with variables, the most likely cause is that the variable content didn't fit into the chat context window. Opening an issue to provide more UI for that case https://github.com/microsoft/vscode-copilot-release/issues/926

**Comment by billboyles** [comment]
> @roblourens can this be a configuration option? 90% of the time I'm referring to code in the current file.

same, this change has made the tool vastly less useful

**Comment by digitarald** [comment]
The latest release should fix general context awareness. Follow-up work for large files is tracked in #1083
