### ISSUE TITLE
Prompts getting blocked

### ISSUE THREAD

**Issue by 3kh0** [microsoft/vscode-copilot-release#828]
- VS Code Version: 1.86.0
- OS Version: Windows 11 Pro 10.0.22631

Steps to Reproduce:

1. Ask prompt
2. Prompt gets blocked

![image](https://github.com/microsoft/vscode-copilot-release/assets/58097612/48e5963a-4819-4b79-9f7c-76d09a93a4b7)

**Comment by lramos15** [comment]
CTRL + SHIFT + U and include your copilot chat logs

**Comment by 3kh0** [comment]
I am unable to reproduce, will open new issue if I see it again
