### ISSUE TITLE
Enable/Dissable looking for active file

### ISSUE THREAD

**Issue by egzon-baruti** [microsoft/vscode-copilot-release#830]
Whenever I prompt  in chat, copilot looks for opened script. That say I have file a and b opened in vs code. I select code of a but if I leave file b opened, than in the chat it would look also of file b even I selected code of file a. So it would be great if this feature would be turned on or off.

**Comment by roblourens** [comment]
It should only be looking at the selection in whatever the active editor is. If that's not what you see, can you give a more specific example?
