### ISSUE TITLE
Copilot not using references, happens a lot, it's getting annoying

### ISSUE THREAD

**Issue by Gerschel** [microsoft/vscode-copilot-release#831]
> I apologize for the confusion. The reference you're seeing is a simulated concept for the purpose of this scenario. It's meant to represent the idea that you've provided a file or code snippet for review. However, as an AI, I don't have the ability to access or view files. I can only provide assistance based on the information you provide in the text of your messages.  

![image](https://github.com/microsoft/vscode-copilot-release/assets/9631031/b17e2589-277a-47dc-b2e6-9d31cd99db90)

> I'm sorry for any confusion, but as an AI, I don't have the ability to see what you're highlighting or access any files on your computer. I can only provide assistance based on the information you provide in the text of your messages. If you could copy and paste the relevant parts of the `PromptServer` class into a message, I would be able to provide more specific advice on how to modify it to use HTTPS.  
  
![image](https://github.com/microsoft/vscode-copilot-release/assets/9631031/b71839ea-4c80-40fb-9f11-588fb4a42022)

**Comment by hjain-spcg** [comment]
did they even test this for one second.  the broke the usefullness

**Comment by roblourens** [comment]
It's not clear what your scenario is. Maybe this is related to the change described in https://code.visualstudio.com/updates/v1_86#_default-context-in-chat. But maybe you can explain some more

**Comment by ImHoffy** [comment]
> It's not clear what your scenario is. Maybe this is related to the change described in https://code.visualstudio.com/updates/v1_86#_default-context-in-chat. But maybe you can explain some more

Thanks, that is working for me.

![image](https://github.com/microsoft/vscode-copilot-release/assets/34977238/e4537d94-8818-42bf-8ab2-52a46d45d64b)

**Comment by Gerschel** [comment]
I think this will certainly help. The issue seemed to pop up whenever I had used a statement like "in my code" "my reference", but even if I stopped using terminology as such, it would get stuck on the idea for a while. I think this can be closed for now. I just have to be carefull not to use certain words and use the default context in chat opperators.
