### ISSUE TITLE
Make saving an entire thread easy

### ISSUE THREAD

**Issue by richhas** [microsoft/vscode-copilot-release#832]
Two forms for this request:
1) Just give an easy and direct way to save off the entire text stream of a conversation thread
2) Preserve threads for later continuance - like openAI chatgpt subscriptions

**Comment by roblourens** [comment]
This exists- when you click the + to start a new chat, the previous is saved, and you can click the 'history' button to retrieve previous chats

**Comment by richhas** [comment]
Did not know that. Thanks!
