### ISSUE TITLE
"Hey Code" not functioning on M1

### ISSUE THREAD

**Issue by dtedesco1** [microsoft/vscode-copilot-release#833]
Type: <b>Bug</b>

I've tried various combinations of turning on an off extensions. In all combinations, "accessibility.voice.keywordActivation" is not recognized and I do not see a mic icon in the status bar, not does speaking "Hey Code" produce any response.

Extension version: 0.13.2024020201
VS Code version: Code 1.86.0 (Universal) (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:29:15.765Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|24.00GB (1.31GB free)|
|Process Argv|. --crash-reporter-id 2bc01c52-17cc-4d13-8409-27c9e8a896be|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928
e3gdj431:30956216

```

</details>

**Comment by bpasero** [comment]
To figure out more about this issue related to voice recognition, can you do this:
* close all instances of VS Code
* open a terminal / console
* define an `VSCODE_SPEECH_LOGS_PATH` environment variable pointing to a folder that exists
  * on Windows: `set VSCODE_SPEECH_LOGS_PATH=<path to existing folder>`
  * on macOS/Linux: `export VSCODE_SPEECH_LOGS_PATH=<path to existing folder>`
* start VS Code from that terminal / console by typing `code` (or `code-insiders`) 
* set log level to trace for the extension (see [1])
* open the output channel for the extension (see [2])
* try to reproduce the issue that you had seen with voice recognition or keyword activation

Can you then share the output from the extension output channel as well as any log files in the folder of `VSCODE_SPEECH_LOGS_PATH`. Thanks!

[1]
<img width="729" alt="image" src="https://github.com/microsoft/vscode/assets/900690/f5df37a3-9949-4742-85a4-05f9976e0f74">
<img width="730" alt="image" src="https://github.com/microsoft/vscode/assets/900690/8c160914-904f-490f-a13c-173f6ef083c4">
<img width="722" alt="image" src="https://github.com/microsoft/vscode/assets/900690/40c2c84c-a15a-4cc8-aa77-88979c9e19f8">

[2]
<img width="934" alt="image" src="https://github.com/microsoft/vscode/assets/900690/30628791-8419-4758-a29d-0175fcc14d62">

**Comment by dtedesco1** [comment]
Thanks, @bpasero. The latest update to the voice extension seems to have resolved it.
