### ISSUE TITLE
Request for User DIY Model Support in GitHub Copilot

### ISSUE THREAD

**Issue by dbsxdbsx** [microsoft/vscode-copilot-release#834]
I am writing to inquire about the possibility of introducing a feature that allows users to utilize their own custom models(through API token like that offered by OPENAI) in the GitHub Copilot extension.

As a frequent user of GitHub Copilot, I have found the tool to be incredibly useful in assisting with code generation. However, I believe that the ability to use custom models could greatly enhance the flexibility and effectiveness of the tool. I know there are some alternative models provided within Copilot currently, but the LLM community over the world is becoming more and more diversified. Different users may have different needs and preferences(like customized code style) when it comes to code generation, and a one-size-fits-all model may not always be the best solution.

Moreover, from the perspective of the extension, allowing users to use their own models through a customized API token could potentially reduce the load on your official servers. This could lead to cost savings and improved performance for all users. Additionally, it could provide an opportunity for a more flexible pricing for this extension.

**Comment by roblourens** [comment]
Well, the Chat Participant API (https://github.com/microsoft/vscode/issues/199908) will enable people to write extensions that provide chat `@` participants, and they can use whatever model they want.

But if you're asking for the ability to use all the same current functionality with a different model plugged in, I think that's very unlikely to happen in the near future. We've found that we can't just send the same prompts to a different model and get good results. Switching models usually requires more rounds of prompt crafting and tweaks.

**Comment by dbsxdbsx** [comment]
> Well, the Chat Participant API ([microsoft/vscode#199908](https://github.com/microsoft/vscode/issues/199908)) will enable people to write extensions that provide chat `@` participants, and they can use whatever model they want.
> 
> But if you're asking for the ability to use all the same current functionality with a different model plugged in, I think that's very unlikely to happen in the near future. We've found that we can't just send the same prompts to a different model and get good results. Switching models usually requires more rounds of prompt crafting and tweaks.

What a pity. Frankly, this would discourage me to subscribe Copilot again.
