### ISSUE TITLE
Feature Request:  Change Language for Auto Commit Message

### ISSUE THREAD

**Issue by dbsxdbsx** [microsoft/vscode-copilot-release#835]
Currently, the language for auto `Commit message` is controllered by `github.copilot.chat.localeOverride`(v.1.86), But sometimes, users want to use language A for a project and use another language B for another project.    

So, I think there could be something be done just like that in markdown:
![image](https://github.com/microsoft/vscode-copilot-release/assets/17372655/1009d76a-bf76-4c25-aea2-93bf81d3be8b)
For example, when users want the `Commit message` be in another language, this can be done by a similar trailing button like that in the image.

**Comment by TylerLeonhardt** [comment]
Couple ideas based on what's already in place that you could use:
* `github.copilot.chat.localeOverride` does allow for workspace specific overrides. For that 1 or few repos where you want it to respond in language B, set language B in those repos
* If you have many repos where you want A and many repos where you want B, use VS Code's Profile support to set which language override you want to use. Use Profile A with override A and Provide B with override B.

Both of these options give you the control you're looking for.

**Comment by dbsxdbsx** [comment]
Thanks for your reply.  But after testing, I found that `github.copilot.chat.localeOverride` would be changed to be consistent across different workspaces.

**Comment by dbsxdbsx** [comment]
> @dbsxdbsx you can configure this setting for a specific project by using workspace settings https://code.visualstudio.com/docs/editor/workspaces#_singlefolder-workspace-settings

Thanks.
