### ISSUE TITLE
Cannot clear Chat window

### ISSUE THREAD

**Issue by peterbud** [microsoft/vscode-copilot-release#84]
Version: 1.79.0-insider (user setup)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:18:53.811Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Open GitHub Copilot Chat window
2. select at the top "Clear"
3. I get the following error mesaage:

`Cannot read properties of undefined (reading 'requesterUsername')`

Otherwise code generation / chat works as expected.

**Comment by peterbud** [comment]
One more thing: using "/clear" command also works

**Comment by roblourens** [comment]
Should be fixed now
