### ISSUE TITLE
"Invalid array length" and "All promises were rejected" when using `@workspace` argument with Copilot in VSCode

### ISSUE THREAD

**Issue by DylanDevelops** [microsoft/vscode-copilot-release#842]
- VS Code Version: Version: 1.86.0 (Universal)
- OS Version: According to "About VSCode": Darwin arm64 23.2.0. 
- OS: MacOs Sonoma 14.2.1 (23C71)

I'm working with the source code for GitHub Desktop and keep getting this error `Invalid Array Length`:

<img width="391" alt="Screenshot 2024-02-03 at 4 51 43 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/48571264/d644fd00-0bca-4753-84b5-89eb0d2fdef1">

Steps to Reproduce:

1. Go to the https://github.com/desktop/desktop repository.
2. Ask a question passing in the `@workspace` argument
3. See results.

**Comment by DylanDevelops** [comment]
I just updated GitHub Copilot and also made sure I was on the most recent version of vscode, and it now gives me this new error.

<img width="375" alt="Screenshot 2024-02-08 at 1 29 40 PM" src="https://github.com/microsoft/vscode-copilot-release/assets/48571264/f2066570-5dc3-43f0-945d-39439e92584e">

Any ideas how to fix this new one?

**Comment by jsparks** [comment]
I haven't seen that one before.

**Comment by DylanDevelops** [comment]
If you run this same behavior specified in my instructions to reproduce:

> 1. Go to the https://github.com/desktop/desktop repository.
> 2. Ask a question passing in the `@workspace` argument
> 3. See results.

Do you get the same result?

**Comment by mjbvz** [comment]
I believe this was fixed. I can't repro this in desktop/desktop 

Let me know if you're still seeing this
