### ISSUE TITLE
`/clear` was a better name

### ISSUE THREAD

**Issue by flexbox** [microsoft/vscode-copilot-release#845]
as a developer,
I can use the same tools as the terminal,
so that I do not have cognitive overhead.

---

We used to have `/clear` on the chatbox, it's not the case anymore
![CleanShot 2024-02-05 at 10 32 54](https://github.com/microsoft/vscode-copilot-release/assets/360936/18a715c6-0760-460f-a85c-9010ede81480)

As devs using the terminale all day we know what `/clear` means

With the `/newChat`, we have 3 choices to make and I am loosing my focus everytime 😬 
![CleanShot 2024-02-05 at 10 34 00](https://github.com/microsoft/vscode-copilot-release/assets/360936/373a02dd-fc65-40b3-9690-fe22fd0170f5)

I think we can keep both `/newChat` and `/clear` as an alias.

**Comment by evilmonkey19** [comment]
I agree! I have been the last month looking for the `/clear` as always and it was never working. Please make it go back 🙏

**Comment by roblourens** [comment]
I actually made this change

**Comment by flexbox** [comment]
Thank you @roblourens ❤️ this little change will bring devs joy.

![CleanShot 2024-03-08 at 09 51 47@2x](https://github.com/microsoft/vscode-copilot-release/assets/360936/4b8982e9-742f-4676-9f5f-3a9aa1a8ebd3)

**Comment by evilmonkey19** [comment]
> I actually made this change in February

Sorry for the mistake 😅. But now, with the pace of writing code using co-pilot, it feels like months old 😋
