### ISSUE TITLE
github copilot is not working on vscode

### ISSUE THREAD

**Issue by waynesbc** [microsoft/vscode-copilot-release#846]
VS CODE - 
Version: **_**1.53.2**_**
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 18.7.0

======
Error while installing 'GitHub Copilot Chat' extension.
Unable to install 'github.copilot-chat' extension because it is not compatible with the current version of VS Code (version 1.53.2).

on ...  Mac OS10.14.  

was working a few days ago ...????? 

Fix??

**Comment by DWboutin** [comment]
Mine is not showing too

Version: 1.88.0-insider (Universal)
Commit: f7c827a5e0ddbba66425ea54e33430bce8f53c84
Date: 2024-03-20T05:50:33.199Z (1 day ago)
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

**Comment by bhavyaus** [comment]
Please give this a try on a newer release of vscode.
