### ISSUE TITLE
Follow-up questions after blocked request/responses loose conversation context

### ISSUE THREAD

**Issue by jtlapp** [microsoft/vscode-copilot-release#85]
- VS Code Version: 1.79.0-insider
- OS Version: MacOS 12.3.1

Check out this conversation. Chat is frequently losing prior context.

I was trying to get chat to tell the difference between `__brand` and `kind` in branded types and discriminated unions, using TypeScript. It was able to provide a reasonable abstract description, but it wasn't able to produce distinct code that demonstrated the difference. In any case, we are clearly having a conversation about branded types and kind properties with code examples in TypeScript. But then it chokes:

![Screen Shot 2023-05-22 at 16 55 46](https://github.com/microsoft/vscode-copilot-release/assets/138133/8e657cd0-2d67-4b2a-8948-39b634a59b27)

Notice that all I did was repeat my prior question starting with the words "In TypeScript", and it was able to regain context.

But this trick didn't always work:

![Screen Shot 2023-05-22 at 17 05 00](https://github.com/microsoft/vscode-copilot-release/assets/138133/c7a81c9a-174d-4150-b78e-936552942a9d)

FYI, I've been regularly using ChatGPT-3 and now ChatGPT-4, and I've never had this problem with it. (I know that unlike Copilot it isn't limited to coding, but it has always known that we're talking about coding.)

**Comment by 1nVitr0** [comment]
I have a similar issue. When requesting long code snippets (such as providing comments for a long list of constants), copilot just stops after some amount of lines. When requesting to continue, copilot forgets the constraints and specificities of the previous request:

> Write short comments in tne line above each public constant in the style "/** [description] */"

```php
[...]

  /** Region: Asia */
  public const REGION_ASIA = 'as';
  /** Region: Australia */
  public const REGION_AUSTRALIA = 'au';
  /** Region: Austria */
  public const REGION_AUSTRIA = 'at';
  /** Region: Belgium */
  public const REGION_BELGIUM = 'be';
  /** Region: Brazil */
  public const REGION_BRAZIL = 'br';
  /** Region: Canada */
  public const REGION_CANADA = 'ca';
  /** Region: China */
  public const REGION_CHINA = 'cn';
  /** Region: Denmark */
  public const REGION_DENMARK = 'dk';
  /** Region: Europe */
  public const REGION_EUROPE = 'eu';
  /** Region: Europe PAL A */
  public const REGION_EUROPE_PAL_A = 'eupala';
  /** Region: Europe PAL B */
  public const REGION_EUROPE_PAL_B = 'eupalb';
  /** Region: Finland */
  public const REGION_FINLAND = 'fi';
  /** Region: France */
  public const REGION_FRANCE = 'fr';
  /** Region: Germany */
  public const REGION_GERMANY = 'de';
  /** Region: Greece */
  public const REGION_GREECE = 'gr';
  /** Region: Hong Kong */
  public const REGION_HONG_KONG = 'hk';
  ?>
  ```
  
  Copilot just stopped there, althougn there were more regions:
  
  >Please continue for the rest of the regions
  
  ```php
  <?php
  public const REGION_INDIA = 'in';
  public const REGION_IRELAND = 'ie';
  public const REGION_ITALY = 'it';
  public const REGION_JAPAN = 'jp';
  public const REGION_KOREA = 'ko';
  public const REGION_NETHERLANDS = 'nl';
  public const REGION_NEW_ZEALAND = 'nz';
  public const REGION_NORWAY = 'no';
  public const REGION_POLAND = 'pl';
  public const REGION_PORTUGAL = 'pt';
  public const REGION_RUSSIA = 'ru';
  public const REGION_SOUTH_AMERICA = 'sa';
  public const REGION_SPAIN = 'es';
  public const REGION_SWEDEN = 'se';
  public const REGION_SWITZERLAND = 'ch';
  public const REGION_TAIWAN = 'tw';
  public const REGION_UNITED_ARAB_EMIRATES = 'ae';
  public const REGION_UNITED_KINGDOM = 'gb';
  public const REGION_UNITED_STATES = 'us';
  public const REGION_WORLDWIDE = 'ww';
?>
  ```

**Comment by NikiLentz** [comment]
i also had similar problems with it thinking i stopped talking about programming. I think they are resetting the context too often, but if my experience with chatgpt is anything to go by they need to reset it at some point. Longer conversations tend to lead to halucinations more often as far as i can tell.

**Comment by jtlapp** [comment]
> I think they are resetting the context too often, but if my experience with chatgpt is anything to go by they need to reset it at some point. Longer conversations tend to lead to halucinations more often as far as i can tell.

That could be it. If they are intentionally resetting the conversation, they should throw a line into the thread informing us, so that we know we need to provide context again.

**Comment by jordyfilbert** [comment]
This is a huge issue, pasting codes over the character limit and it keeps forgetting what we're talking about.

**Comment by jtlapp** [comment]
I should mention that the issue as I originally reported it did not involve large segments of code or even a long conversation. I was asking short, simple questions. It lost context on my 9th question.

**Comment by NikiLentz** [comment]
Yeah i have the Same experience. Short questions and it forgets completely what i am talking about or repeats itself when asked for something different

**Comment by samir-jorge-araujo** [comment]
I have tried to ask the chat to rewrite the last response with a change, but it got completely lost out of context.

These are my device details:
Version: 1.79.0-insider
Commit: 667d4629dee90744edd5054f13bc2452c8c14490
Date: 2023-05-29T05:39:27.608Z
Electron: 22.5.3
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0

Steps to reproduce:
1. Have a project open with a Magento 1 code
2. Ask in the chat tab: "How can I create an extension that creates a customer attribute?"
3. It answered with a code for Magento 2 and response returned the following error "Oops, your response got filtered. Vote down if you think this shouldn't have happened."
4. Answer with "No, I want it for Magento 1"
5. It shows an answer completely out of context with the original request

This is the full conversation:

```
samir-jorge-araujo: How can I create an extension that creates a customer attribute?

GitHub Copilot: To create a customer attribute in Magento 2, you can create a custom module and use the `InstallData` script to create the attribute. Here are the general steps:

1. Create a new module with a registration.php file and a module.xml file.
2. Create a new InstallData.php file in your module's Setup folder.
3. In the InstallData.php file, use the `eavSetup` factory to create a new customer attribute.
4. Set the attribute's properties, such as label, input type, and source model.
5. Use the `addAttribute` method to add the attribute to the customer entity.

Here is an example of how to create a customer attribute using InstallData.php:

```php
<?php
namespace Vendor\Module\Setup;

use Magento\Customer\Model\Customer;
use Magento\Customer\Setup\CustomerSetupFactory;
use Magento\Eav\Model\Entity\Attribute\SetFactory as AttributeSetFactory;
use Magento\Framework\Setup\InstallDataInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;

class InstallData implements InstallDataInterface
{
    private $customerSetupFactory;
    private $attributeSetFactory;

    public function __construct(
        CustomerSetupFactory $customerSetupFactory,
        AttributeSetFactory $attributeSetFactory
    ) {
        $this->customerSetupFactory = $customerSetupFactory;
        $this->attributeSetFactory = $attributeSetFactory;
    }

    public function install(ModuleDataSetupInterface $setup, ModuleContextInterface $context)
    {
        $customerSetup = $this->customerSetupFactory->create(['setup' => $setup]);
        $customerEntity = $customerSetup->getEavConfig()->getEntityType(Customer::ENTITY);
        $attributeSetId = $customerEntity->getDefaultAttributeSetId();

        $attributeSet = $this->attributeSetFactory->create();
        $attributeGroupId = $attributeSet->getDefaultGroupId($attributeSetId);

        $customerSetup->addAttribute(Customer::ENTITY, 'custom

samir-jorge-araujo: No, I want it for Magento 1

GitHub Copilot: I apologize for the confusion. Here are some possible commands and settings for Magento 1:
- Magento: Run Compilation ("magento.compiler") (Keybinding: "Not set")
- Magento: Flush Cache ("magento.cache.flush") (Keybinding: "Not set")
- Magento: Enable Template Path Hints ("magento.templatehints.enable") (Keybinding: "Not set")
- Magento: Disable Template Path Hints ("magento.templatehints.disable") (Keybinding: "Not set")
- Magento: Reindex Data ("magento.reindex") (Keybinding: "Not set")

```

**Comment by giuricich** [comment]
yeah the filter seems wayyy too hardcore, i was messing around with css gradients and asked what a value was in degrees but thinks im talking about something unrelated :/

**Comment by digitarald** [comment]
Fine-tuning filtering and improving the UX is in progress, so lets focus this issue on the loss of context after the filter got hit.

**Comment by digitarald** [comment]
Closing for now, as a new offtopic detection got deployed. Please file new issues for follow-up reports.
