### ISSUE TITLE
Feature Request: Help guide copilot chatbot's responses

### ISSUE THREAD

**Issue by scottpetrovic** [microsoft/vscode-copilot-release#851]
The actual code copilot is generating is useful, but it would be nice if I could override the general guidance it gives me. I am currently using this a lot to teach me various programming concepts (IRQ and direct memory access right now). These are the types of thoughts or prompts I would like to help guide copilot.

1. Try to include messaging around common use cases on when this code is needed
2. Guide it to give me more URL references about education. This will help me research to check the AI's "hallucination" that it occasionally does when explaining things.
3. Allow me to craft a bit more personality for the bot instead of such a generic personality (e.g. You don't need to say "Happy coding!" so much. ).

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/563
