### ISSUE TITLE
Wrong formatting when generating Markdown

### ISSUE THREAD

**Issue by qequ** [microsoft/vscode-copilot-release#854]
- VS Code Version:
 1.86.0
05047486b6df5eb8d44b2ecd70ea3bdf775fd937
x64

- OS Version: Ubuntu 20.04
- Logs:

Steps to Reproduce:
When generating markdown code that contains  snippets of code  around three inverted commas "```"  the box of code of the chat breaks and treats the generated  markdown as part of the chat, not as source code

**Comment by mjbvz** [comment]
Duplicate of #760
