### ISSUE TITLE
Extend '#selection' Context Variable to Support Multiple Selection Functionality

### ISSUE THREAD

**Issue by ilund** [microsoft/vscode-copilot-release#856]
Visual Studio Code's "multiple selection" feature is a powerful tool that enables users to select and edit multiple, non-adjacent lines of code simultaneously. This is typically achieved by holding down a modifier key (like 'Alt' on Windows and Linux, or 'Option' on macOS) and clicking in different places in the text. However, the current implementation of the `#selection` context variable in GitHub Copilot Chat seems to only recognize the first selection, ignoring any subsequent selections made.

This limitation hampers the full utilization of the multiple selection feature, particularly when dealing with large codebases where multiple selections across different files could provide GitHub Copilot Chat with a more specific context for its responses.

## Proposed Enhancement:

I propose an enhancement to the `#selection` context variable to capture all selected areas when using the multiple selection feature, not just the first one. This would allow users to extract maximum benefit from the multiple selection feature, making their coding workflows more efficient and seamless.

## Advanced Feature:

As an advanced feature, it would be beneficial if the `#selection` context variable could also capture selections made across multiple files. In addition to the selected code, it could provide GitHub Copilot Chat with the file names containing each selection. This would give the model a broader context, potentially improving the relevance and accuracy of its responses.

> **Note:** The modifier key used for multiple selection may vary depending on the operating system. For the purpose of this request, I've referred to it as the 'Alt' key, commonly used in Windows and Linux environments.

| ![image1](https://github.com/microsoft/vscode-copilot-release/assets/69800230/bdc900ab-fddf-4b7d-8dba-be7b232a070f) | VS. | ![image2](https://github.com/microsoft/vscode-copilot-release/assets/69800230/5cdec95c-cd0c-4612-8396-3cadae23dffb) |
|:---:|:---:|:---:|

**Comment by Mr-Ruben** [comment]
This is useful also for **Notebooks**, where you select a few cells and expect them to be captured on `#selection`
