### ISSUE TITLE
Copilot chat not using the current opened file in the editor (vscode) and giving generic answers

### ISSUE THREAD

**Issue by KrisSandy** [microsoft/vscode-copilot-release#858]
Couple of days back, copilot use to take the current opened file as context and suggests based on it. But not it is no longer using the context and giving generic answers. I tried switching to pre-release version, but its the same. 

- VS Code Version: 1.86.0
- OS Version: Mac OS 13.2

Steps to Reproduce:

1. Just type a question in the chat and it gives generic answer.

**Comment by pedro-rodiguero** [comment]
I'm having the same issue, but on Linux Ubuntu:
VS Code Version: 1.86.0
OS: Linux x64 6.5.0-15-generic

**Comment by lramos15** [comment]
Are you selecting the code?

**Comment by pedro-rodiguero** [comment]
It's not necessary to select the code. If you don't select a specific snippet, copilot will use as reference the whole file or the lines that are being shown on the IDE. Eg.: lines 4-37 of routes.py

**Comment by lramos15** [comment]
@pedro-rodiguero It is necessary. See https://code.visualstudio.com/updates/v1_86#_default-context-in-chat

**Comment by KrisSandy** [comment]
Thanks @lramos15. It looks like we need to either select the code or use `#editor` to include the code snippet in the context. I am happy to close this issue.
