### ISSUE TITLE
Encountered an error on the GitHub Copilot while using on vscode while attempting to use the service.

### ISSUE THREAD

**Issue by umerfarok** [microsoft/vscode-copilot-release#859]
![Screenshot 2024-02-07 at 7 37 31 PM](https://github.com/microsoft/vscode-copilot-release/assets/114828722/11bb4cfc-41a1-4101-97cc-de063658e054)
VS.code details
Version: 1.86.0
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:11.933Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.2.0
steps to reproduce  is just send a message to chat

**Comment by dominik-kosic** [comment]
@umerfarok, update Github Copilot Chat extension and it should work fine

**Comment by umerfarok** [comment]
@dominik-kosic  that issue is resolved but i have paid subscription and it says subscribe to 30 day free trial  and i am logged in github
<img width="257" alt="Screenshot 2024-02-08 at 1 20 36 AM" src="https://github.com/microsoft/vscode-copilot-release/assets/114828722/92d3d868-8c17-41b4-948a-5a443dc60679">

**Comment by umerfarok** [comment]
fixed by updating extenshion
