### ISSUE TITLE
[Feature Request] For branding reasons, make Copilot Chat sound different from ChatGPT

### ISSUE THREAD

**Issue by jtlapp** [microsoft/vscode-copilot-release#86]
I know that GitHub Copilot is based on ChatGPT-3 technology, but I think it might be wise to give Copilot a way of talking that is distinct from ChatGPT, or at least give it different common phrases. I'll explain why.

I have been using ChatGPT-3 and now ChatGPT-4 for coding for several months. I have become extremely frustrated with how it comes back to me with solutions that have no basis in reality. It invents APIs and behavior rather than says, "I don't know" or "I can't help with that." Instead, it always confidently offers a solution, even if it has to fabricate it, and I waste time trying to get the solution to work. I'm fed up enough with ChatGPT that I now only ask it for general pointers, nothing specific.

In short, I've developed a bad taste in my mouth trying to use ChatGPT for coding.

I'm grateful to have been given a chance to play with Copilot chat, especially because I absolutely love Copilot. But I had a sinking feeling when I starting seeing the same phrases that ChatGPT emits. I feel like I'm still using ChatGPT -- someone else's product. I know that logically it's a different beast, but my emotional response is deflation. I feel less hope for Copilot chat, less eagerness to be using it.

And all this despite not yet encountering on Copilot Chat the problems I've had with ChatGPT.

So I think for branding and marketing purposes, you might want to give Copilot Chat a distinct voice. It may be as simple as changing the common phrases like, "I apologize for the confusion" and "I hope this clears up any confusion", which are the ones that triggered me. I haven't seen it yet in Copilot Chat, but another one to jettison would be "It is important to note that..."

**Comment by giuricich** [comment]
As AI models our responses are generated based on the data and patterns that we have been trained on, we do not have personal experiences or emotions that could influence our responses.

**Comment by roblourens** [comment]
I agree that the OpenAI models have a certain style of speaking, however we are stuck with those models and trying to change their "accent" with prompt crafting would probably just cause issues.
