### ISSUE TITLE
Provide option to move "sparkle" (Modify Using Copilot) to just a regular command

### ISSUE THREAD

**Issue by matschaffer-roblox** [microsoft/vscode-copilot-release#865]
The new sparkle icon is pretty distracting since it shows up even when just highlighting to do something like a copy/paste operation.

![Screenshot 2024-02-07 at 8 21 01 PM](https://github.com/microsoft/vscode-copilot-release/assets/115565899/1c91dc34-2d8b-4f5c-9785-d9973f522ae4)

I'd like an option to disable it instead have a command-palette version of the same Modify Using Copilot command.

**Comment by matschaffer-roblox** [comment]
Ah, thanks to https://github.com/microsoft/vscode-copilot-release/issues/735 I found that:

```
"editor.lightbulb.enabled": "off",
```

works to disable the sparkle. Looks like "onCode" was the old behavior, but the lightbulb was a lot less distracting I think.

It'd still be nice to have a "Modify Using Copilot" command. Doesn't look like it's available from the command palette in 1.86.0

**Comment by AnsonH** [comment]
I still want to retain the original light bulb for code actions, but only disable the Copilot sparkle icon. If I set `"editor.lightbulb.enabled": "off"`, the light bulb for code actions will also be disabled.

It'd be great if there is a separate option for setting the Copilot sparkle only :pray:

**Comment by aiday-mar** [comment]
Hi @matschaffer-roblox thanks for posting this issue. You have correctly found the setting name. The code action `modify using copilot` still exists, you will however most likely find it in the code action menu when the icon is a lightbulb with a sparkle, not just the sparkle. The reason for this is because the lightbulb with a sparkle icon is used to show when the code action menu has both standard code actions and AI code actions. The `modify using copilot` code action often appears in conjunction with other standard code actions. 

<img width="278" alt="Screenshot 2024-02-19 at 09 34 06" src="https://github.com/microsoft/vscode-copilot-release/assets/61460952/5fa67cb6-1dbf-41fb-bdf8-c89c7bfa7777">

**Comment by matschaffer-roblox** [comment]
Interesting! Not sure I've seen the sparkle lightbulb combo before. Is there maybe a color override for the bulb/sparkle/sparklebulb?

I think with a lower saturation it might be less distracting.

**Comment by aiday-mar** [comment]
Hi yes there is a color override, which you just found in your settings. This color is used for all three icons as you mentioned.

**Comment by aiday-mar** [comment]
Hi @ev45ive thanks for the comment. We will take that into consideration.

**Comment by KillyMXI** [comment]
- `"github.copilot.editor.enableCodeActions": false` - also removes the action from ligthbulb menu, where it is tolerable addition, not standing out;
- `"editor.lightbulb.enabled": "onCode"` - seems to do just enough to remove the sparkle. But it is not obvious for me whether it is a proper solution.

I assume the idea behind current implementation is that there might be multiple content generators.
But I would really appreciate a more subtle way to access them when I actually need them. In-your-face, always present sparkle is too much.
It could've been something equally subtle to folding symbol in the gutter/line numbers area - no bright colors, only visible on hover.

And individual providers, like Copilot, can always have more granular options.
Copilot seems to be tapping into different menus and panels in random ways to see what will stick...
While you're doing the UI research on users - expect all attempts can be frustrating and provide toggles.

**Comment by kraig-droid** [comment]
Just adding on: the sparkle is EXTREMELY distracting, placing itself ON TOP of code I just wrote that I need to see to continue my thought. I like Copilot and want to keep using it. But I don't want it hindering me to the point of searching for solutions to turn off sparkle and making comments in issues.

**Comment by aiday-mar** [comment]
As was previously mentioned can disable the copilot code actions using `"github.copilot.editor.enableCodeActions": false` and set `"editor.lightbulb.enabled": "onCode"` to revert the behavior of the lightbulb to the previous behavior.

**Comment by marclove** [comment]
+1 That this is incredibly annoying and really ought to be shown in the Settings for the Copilot extension, not a secret setting where I have to find this issue to know how to turn it off.

**Comment by justschen** [comment]
hey all! in addition to `onCode` settings or disabling Copilot Code Actions, the widget will now use a "best case" placement and can spawn in the gutter as to not block any code! if there is space above, it will spawn above. if there is space below, it will spawn below. 

there have also been improvements on the TS side to make the lightbulb appear **significantly** less (by making `Move To` actions more explicit vs. implicit). See https://github.com/microsoft/TypeScript/pull/58548

in many cases, the sparkle will still show up on **empty lines** or when there are diagnostics unless `"github.copilot.editor.enableCodeActions"` is set to `false`, but we hope this will mitigate how often it covers your actual code.

This is released in our latest Insiders already and is shipping in 1.92.
