### ISSUE TITLE
GitHub Copilot Not Displaying Chat History in Visual Studio Code

### ISSUE THREAD

**Issue by soummyaanon** [microsoft/vscode-copilot-release#872]
- VS Code Version: 1.86
- OS Version: Mac OS 14 

Steps to Reproduce:

1. open the GitHub Copilot  Toggle  and click On History Icon
2. Result Is Not Showing

**Comment by soummyaanon** [comment]
Got fIxed The issue  by My self

**Comment by nabosh** [comment]
same issue. any info on how you fixed it?

**Comment by soummyaanon** [comment]
@nabosh log out the GitHub From Your VS code  and sign in if possible reinstall the GitHub copilot  and again sign in with your  GitHub account if your Giithub account is signed in anywhere else Then sign out The season  

That's It  I fixed it By Doing Only  do this step to see it is working Or not  if its work just inform me
