### ISSUE TITLE
Github Copilot /fix Does not offer discard to clipboard anymore

### ISSUE THREAD

**Issue by acoustesh** [microsoft/vscode-copilot-release#873]
v1.159.701 (pre-release)
- VS Code Version: 1.86.1 (user setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22635
Github Copilot extension v1.159.701 (pre-release) on Ubuntu 22.04
GitHub Copilot Chat v0.13.2024020201 (pre-release)

They eliminated the option to discard to clipboard when using /fix to propose code. Now only accept or cancel which is dangerous and useless.  I want to review changes before they are applied

Steps to Reproduce:

1.In any line of code (in python) right-click select Copilot->Fix this.  Then only accept and cancel options appear.Old discard to clipboard was extremely useful and gone
![Screenshot 2024-02-10 004847](https://github.com/microsoft/vscode-copilot-release/assets/10789758/6e032264-9203-444a-9983-7a033e85fadd)

**Comment by jrieken** [comment]
Yeah, that was an experiment which we have removed by now
