### ISSUE TITLE
Cannot read properties of undefined (reading 'split') after the second submit 

### ISSUE THREAD

**Issue by issam-seghir** [microsoft/vscode-copilot-release#874]
My VS Code  updated to the latest version today. However, when I open Copilot chat, the first message is sent correctly. But, after the first message, any message I send throws an error. `Cannot read properties of undefined (reading 'split')`

![image](https://github.com/microsoft/vscode-copilot-release/assets/74573675/44061128-bc46-4cb7-a787-af9bcf6d2527)

the only thing that works for me is to create a new chat every time I send a message !! 

- VS Code Version: 1.86.0
- OS Version:  windows 10 22H2
- Logs:

**Comment by maniiiisha** [comment]
Getting the same error.

![Screenshot 2024-02-10 180526](https://github.com/microsoft/vscode-copilot-release/assets/63800003/e491ac18-e3c8-4e57-8592-b97f977ec77f)

**Comment by issam-seghir** [comment]
The issue was resolved when I navigated to the `extensions` tab in the Activity Bar and searched for `Copilot Chat`. I then clicked the **"Reload Required"** button in the extension, causing VSCode to reload. Copilot functioned appropriately after this, and the error was resolved.

**Comment by maniiiisha** [comment]
This worked !!! Thanks a lot.

**Comment by aiday-mar** [comment]
Hi the reason this worked is because the extension was updated and the bug fixed. On the latest extension, this should no longer be a problem.
