### ISSUE TITLE
Chat History in all instance of vscode

### ISSUE THREAD

**Issue by DhaniAM** [microsoft/vscode-copilot-release#877]
After I open vscode on new window or opening a new folder, my previous history of chat in vscode is gone. I can't see it in the history. In fact there's no history at all. I guess it doesn't get save on my account. It would be nice if I could see all of my previous chat like how ChatGPT or Gemini does.

**Comment by roblourens** [comment]
Chat history is saved per-workspace, so you will only see messages that were sent within that same window/folder

**Comment by suolongjunjun** [comment]
so how do I get my old workspace back?

**Comment by suolongjunjun** [comment]
> Chat history is saved per-workspace, so you will only see messages that were sent within that same window/folder
so how do I get my old workspace back?

**Comment by stellarpower** [comment]
Is it buried somewhere in the workspace folder under ~/.config then? It can cause a bit of a problem when a workspace will no longer open or is not accessible for any reason - e.g. a container will no longer start, folder has been renamed, a remote SSH server isn't accessible, etc.
