### ISSUE TITLE
Copying terminal code snippets shouldn't include $

### ISSUE THREAD

**Issue by palkan** [microsoft/vscode-copilot-release#88]
- VS Code Version:  1.79.0-insider (Universal)
Commit: f6be5461f8bc69013a605f5baea834651c6589fb
Date: 2023-05-20T01:20:35.044Z (2 days ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 21.6.0

Steps to Reproduce:

1. Ask chat to generate some shell command (e.g., "How to install Graphviz on MacOS?")
2. Try copying the snippet with the "Copy" icon. For example, having the following snippet:

```sh
$ brew install graphviz
```

I expect a valid command to be copied; instead, the full "$ brew install graphviz" is copied into the buffer.

Similarly, "Run with Terminal" copies the whole contents.

**Comment by Tyriar** [comment]
This should only happen if $ is proposed by the AI. I've never seen this personally and have a feeling it's improved greatly as models have moved forward:

![Image](https://github.com/user-attachments/assets/e5bff4bc-2e68-49a8-a195-baa2f3b6a273)
