### ISSUE TITLE
Copilot in VS Code doesn't suggest code anymore

### ISSUE THREAD

**Issue by bvbeek** [microsoft/vscode-copilot-release#880]
Copilot in VS Code doesn't suggest code anymore.

- VS Code Version: 
Version: 1.86.1 (system setup)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:20.941Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621

- OS Version:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28626283/815e9ca0-9580-48ff-9f82-cc8fe8ae8060)

- GitHub Copilot version: v1.159.0

- Logs:
![image](https://github.com/microsoft/vscode-copilot-release/assets/28626283/ea48b962-ac7c-46ae-a7af-b741722ef7da)

**Comment by james0r** [comment]
weird ya mine stopped today too. icon in the tray just spins.

Github Copilot Version: v1.159.0
VS Code Version: 1.86.1
macOS Version: 14.3.1 (23D60)

**Comment by TristanSpeakEasy** [comment]
Just to pile on seeing the same behavior

```
## Copilot

- Version: 1.159.0
- Build: prod
- Editor: vscode/1.86.1
```

This is on Windows while developing in WSL2 on Ubuntu 20.04

**Comment by mikeltsan** [comment]
Same here

**Comment by bhaskarverma** [comment]
Same thing is happening in Linux too, Working on Zorin 17 ( Based on Ubuntu ). Showing same result in output with no suggestions

**Comment by TristanSpeakEasy** [comment]
Just to add some additional information a colleague has said this is still working in Jetbrains IDEs

**Comment by james0r** [comment]
> Just to add some additional information a colleague has said this is still working in Jetbrains IDEs

oh great so I'm gonna have to hear about that from PHPStorm buddies too.

**Comment by bablu-explory** [comment]
Just to add, issue persists with pre-release version as well.
v1.159.0 (pre-release)

**Comment by mikeltsan** [comment]
It's like going back to the stone age without code complete 😆

**Comment by Creative-Geek** [comment]
seems to have been fixed, check it out

**Comment by vivdesign** [comment]
Still not suggesting for me - latest vscode latest version of the extension (not pre-release)

**Comment by furkanatilgan** [comment]
Not working for me too, tried installing/reinstalling, pre-release version, earlier versions, clearing workplace settings. Nothing seems to work

**Comment by supline** [comment]
Also not working on Mac Visual Studio Code, I tried all the other versions, but didn't work. Btw, chat working well.

**Comment by bjoernskau** [comment]
I get this:
[default] [fetchCompletions] engine https://copilot-proxy.githubusercontent.com/v1/engines/copilot-codex

Version:
Ubuntu 22.04.3 LTS
Visual Studio Code 1.86.1
Copilot v.1.159.0

Just started today, worked yesterday.

**Comment by mikeltsan** [comment]
Yes! It is back. Good timing, I was starting to have withdrawal symptoms 😆

**Comment by bvbeek** [comment]
I see that this problem has now been resolved!

**Comment by bvbeek** [comment]
Hmm, sometimes it's working, sometimes not.

**Comment by chrber04** [comment]
Same for me. Tried restarting vscode, updating vscode, reinstalling copilot, restarting computer. Nothing worked

**Comment by Eyoubbb** [comment]
> Confirming, does not work on Mac Visual Studio Code, as of today.
> 
> Edit: works!

how did you fix it ?

**Comment by donthomasitos** [comment]
Same here. Everything up to date, icon just keeps spinning. Chat works however.

**Comment by Irfan2700** [comment]
I just reverting both vscode (i am using 1.84.2) and copilot(1.158) to previous version of copilot fix my issue

![image](https://github.com/microsoft/vscode-copilot-release/assets/37483515/36fbdf87-105a-459f-9e0b-6ce696d90283)

![image](https://github.com/microsoft/vscode-copilot-release/assets/37483515/168069a7-7700-4279-ae52-517f869615d7)

**Comment by lramos15** [comment]
There's an ongoing incident regarding copilot completions.  

https://www.githubstatus.com/

Please file issues with Ghost Text [here](https://github.com/orgs/community/discussions/categories/copilot)
