### ISSUE TITLE
Github Copilot Chat wrong log in account

### ISSUE THREAD

**Issue by loveshkumrawat** [microsoft/vscode-copilot-release#885]
Type: <b>Bug</b>

After updating to v1.86, my VSCode setup with two GitHub accounts encounters an issue. Despite being logged in with my 1st GitHub account, Copilot chat keeps switching to my 2nd account. The problem resolves temporarily when I log out of the 2nd account completely, but returns upon logging back in with my 2nd account for other extensions.

Extension version: 0.12.1
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:07:19.849Z)
OS version: Linux x64 5.15.0-89-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 3300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 7, 9|
|Memory (System)|31.15GB (15.10GB free)|
|Process Argv|--unity-launch --crash-reporter-id 19908b30-4c38-4c7c-afcd-8697f0e6b324|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
b1063948:30958189
3ef8e399:30962115
bg6jg535:30958357
ccp1r6:30958156

```

</details>

**Comment by TylerLeonhardt** [comment]
This issue is caused by VS Code not properly supporting multiple auth sessions. Not much can be done on the extension side until VS Code fixes this. It was a bug that this worked before

Ref:
https://github.com/microsoft/vscode/issues/203850
https://github.com/microsoft/vscode/issues/127967
