### ISSUE TITLE
Copilot works poorly for demographic data

### ISSUE THREAD

**Issue by NDNnerd** [microsoft/vscode-copilot-release#886]
It's not a bug, per se, but this is where the link for sending generic feedback took me. I'm a demographer, and using copilot is really hard.  It won't complete any inline suggesting that contains the word 'sex', it it difficult to get it to complete if the words "race", "ethnicity" or "gender" are in the line.  It won't answer any questions related to similar code.  As it a coding question with those words in the reference material and all it says is "Sorry, but I can only assist with programming related questions."

I don't know what kind of use cases you are actually worried about here, but the security features you have on it make it very difficult for me to work.

Thanks.

**Comment by digitarald** [comment]
We updated the off-topic filter and see a significant drop in false-positive filtering in experiment results.

Closing as fixed, but please don't hesitate to file new issues in case you still run into this.
