### ISSUE TITLE
Inline Chat jumps to the top when suggesting fix

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode-copilot-release#887]
Instead of showing the copilot suggestion at the code block it suggested it at the far top of the file. Not sure if this is only related to /fix

![Code_-_Insiders_5pn0VCETvp](https://github.com/microsoft/vscode-copilot-release/assets/44439583/2e1707ac-c424-4347-ba07-0cefe76ef44e)

**Comment by aeschli** [comment]
I tried to reproduce with the same error, but didn't see any problems.

We would need the prompt log to understand what went wrong here. Either fix produced a wrong edit, or inline chat applied an edit the wrong way

Closing, please reopen if you have a log.
