### ISSUE TITLE
After typing a large prompt, pressing up blows the unsent prompt away and now i have to re-type it all over again

### ISSUE THREAD

**Issue by airtonix** [microsoft/vscode-copilot-release#888]
```
Version: 1.85.1
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:47:11.635Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.6.13-100.fc38.x86_64
```

1. open copilot chat
2. start typing epic wall of text
3. continue typing epic wall of text
4. be there till next day typing epic wall of text
5. press up
6. see that all that text is gone
7. try to get it back by focusing the input field again
8. nope.
9. gone.
10. ...

![5qxIHd](https://github.com/microsoft/vscode-copilot-release/assets/61225/ff108476-4a38-43ca-91a4-0d870cf481a4)

**Comment by roblourens** [comment]
This is fixed in 1.86
