### ISSUE TITLE
Copilot can't see my code in open files

### ISSUE THREAD

**Issue by jpriollaud** [microsoft/vscode-copilot-release#890]
Copilot could see functions in my **currently open file** in VS Code for the past 6+ months.  Every day I just referred to the functions by name and Copilot knew exactly what I was talking about.  Suddenly after upgrading VS Code it can't see any code blocks unless I highlight them.  This is a 50% reduction in utility.

- VS Code Version: 1.86.1
- OS Version: Ubuntu 20
- Logs:

Steps to Reproduce:

1. Ask Copilot about a method in the currently open file.
2. Copilot responds with:

_"As an AI developed by OpenAI, I don't have the ability to see your screen, your open files, or any other part of your system..."_

**Comment by jpriollaud** [comment]
Maybe related to [861](https://github.com/microsoft/vscode-copilot-release/issues/861) (?)

**Comment by michaelslec** [comment]
Exact same issue on codesapces!

**Comment by alexander-nolan** [comment]
This is expected behaviour according to the release notes. I agree this is a massive reduction in utility. I'm having to select the entire file in order to give it the correct context.

**Comment by cjkaminski** [comment]
This change in functionality caught me off guard too. I would highly recommend improving Copilot's response, because it's incorrect and misleading. Right now, asking the chatbot to reference your code through natural language results in a message that says it cannot look at your code. It can, but you need to use the "#file" or "#editor" commands. Copilot's reply should contain that information.

Also, it took me a while to find the release notes referenced in the previous comment. Here's a link for anyone else looking for more information:
https://github.blog/changelog/2024-02-12-vs-code-copilot-chat-january-2024-version-0-12/

This is a massive change in functionality that wasn't gracefully rolled out. Hope the next update improves the user experience across the entire spectrum.

**Comment by npetersen-cricut** [comment]
That's an awful change and a significant step away from the idea that Copilot is like pair programming with a brilliant human. It's also a bit weird how the release notes make it sound like the #file function is new.

**Comment by jpriollaud** [comment]
@cjkaminski Thank you for the answer.

This should be added to the extension settings obviously.  Something like editor_default: true

**Comment by allancorrigall** [comment]
This change has severely degraded the usability of copilot imo.  If you don't use @workspaces or another command the response is almost always : 

I'm sorry, but your message seems to be incomplete. Could you please provide more details or clarify what you need help with...

And my personal experience is that the results when using @workspaces/etc seem less useful/coherent. Not to mention it being an extra step each time you query.

**Comment by GeekMaster85** [comment]
Is downgrading VSCode to version 1.85 the only solution to restore the auto-reference feature?

**Comment by orlando320** [comment]
Experiencing the same issue any solutions to revert this?

**Comment by roblourens** [comment]
Sorry for the churn here. We were trying to push people towards the `#editor` variable, as the release notes describe https://code.visualstudio.com/updates/v1_86#_default-context-in-chat, but we see that hasn't been working out. So we are reverting the change until we have a better UX story for this, and you should now get the visible code as context.

**Comment by buzzy** [comment]
> Sorry for the churn here. We were trying to push people towards the `#editor` variable, as the release notes describe https://code.visualstudio.com/updates/v1_86#_default-context-in-chat, but we see that hasn't been working out. So we are reverting the change until we have a better UX story for this, and you should now get the visible code as context.

Did you recently re-implement that?? All of sudden, the current file is not auto-used and I have to add #editor on every question. Exactly WHY did you think this was a good idea to begin with, without offering a way to set it as default?
