### ISSUE TITLE
Can't sign in on earlier versions

### ISSUE THREAD

**Issue by alexander-nolan** [microsoft/vscode-copilot-release#893]
- VS Code Version:  1.85.2
- OS Version: Windows 10

Unable to sign in using any version other than v0.12.*. The latest version is basically unusable with the highlight to use context change and the lack of syntax highlighting for HCL code. I'm trying to use previous versions until these issues are fixed, but copilot chat just will not sign in, even though my github account is signed in:

![image](https://github.com/microsoft/vscode-copilot-release/assets/34385107/cc0e8bca-7120-4d48-a5a6-96b08fb5cd55)

If I sign out and in again, it opens a window but nothing loads:

![image](https://github.com/microsoft/vscode-copilot-release/assets/34385107/9e8249f7-47d5-4056-af5f-67f3568497d3)

Steps to Reproduce:

1. Upgrade to v0.12.*
2. Install any version prior to this
3. Sign in

**Comment by TylerLeonhardt** [comment]
First off, why are you downgrading?

Second off, you need to also downgrade the Copilot extension to 1.156.0

**Comment by alexander-nolan** [comment]
That worked. Thank you. HCL syntax highlighting which is broken in the new version (please see https://github.com/microsoft/vscode-copilot-release/issues/881) also works on this version:

![image](https://github.com/microsoft/vscode-copilot-release/assets/34385107/69d1b7a2-ac14-4439-b412-d0672f2d42e9)

This can be closed now.

**Comment by TylerLeonhardt** [comment]
Thanks for confirming!
