### ISSUE TITLE
Maximum call stack size exceeded with @workspace query in chat

### ISSUE THREAD

**Issue by thhicks** [microsoft/vscode-copilot-release#900]
- VS Code Version: version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:08:57.920Z (1 wk ago)
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

- OS Version: mac os 14.3.1
- Logs: ?

Steps to Reproduce:
I have a workspace (which maps to a repository) which consists of 27959 directories and 137733 files (this  includes build artifacts and a variety of languages source).

when i attempt to interact with copilot chat and ask it @workspace questions, I get this:
-Determining workspace structure
-Deciding which workspace information to collect
-Gathering workspace info
! Maximum call stack size exceeded

**Comment by mjbvz** [comment]
I believe this was fixed. If you're still seeing this, please share an example workspace and question that causes the problem
