### ISSUE TITLE
Arrow up/down keys shouldn't delete chat message

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#902]
Opening a new issue for this because the problem still exists and the old issue (https://github.com/microsoft/vscode-copilot-release/issues/661) hasn't been re-opened:

VS Code Version: 1.86.1
OS Version: Windows 11 / WSL2 Ubuntu 22.04

Steps to Reproduce:

1. Type something in chat
2. Arrow up or down multiple times until message disappears
3. Message is lost

Video: https://www.youtube.com/watch?v=vKFvWYfogng

This bug was possibly fixed previously and reintroduced in 1.86.1. See: https://github.com/microsoft/vscode-copilot-release/issues/661#issuecomment-1939373002

**Comment by roblourens** [comment]
Continuing in the original issue
