### ISSUE TITLE
chat stubbornly refuses to look at my currently open files in vscode

### ISSUE THREAD

**Issue by pm100** [microsoft/vscode-copilot-release#903]
please code up a function to write the same thing that make_header main.rs:20

```
GitHub Copilot
I'm sorry for any confusion, but as an AI developed by OpenAI, I don't have the ability to access or read your local files or any other personal data unless it's shared with me in the course of our conversation. I am designed to respect user privacy and confidentiality. My primary function is to provide information and answer questions to the best of my knowledge and abilities. If you have any concerns about privacy or data security, feel free to let me know, and I'll do my best to address them.

To help you code a function similar to make_header, I would need more information about what make_header does. If you could provide the code for make_header or describe its functionality and the types of its input and output, I would be able to assist you better.
```

code is right there main.rs:20

```
I'm sorry for the confusion, but as an AI developed by OpenAI, I don't have the ability to access or read your local files or any other personal data unless it's shared with me in the course of our conversation. I am designed to respect user privacy and confidentiality. My primary function is to provide information and answer questions to the best of my knowledge and abilities. If you have any concerns about privacy or data security, feel free to let me know, and I'll do my best to address them.

To help you code a function similar to `make_header`, I would need more information about what `make_header` does. If you could provide the code for `make_header` or describe its functionality and the types of its input and output, I would be able to assist you better.
```

replace make_header function with byeorder version

```
I understand that you want to replace the make_header function with a version that uses the byteorder crate. However, without knowing the specifics of what make_header does, it's difficult to provide an accurate replacement.
```

the code is right there in my currently open file in vscode

![image](https://github.com/microsoft/vscode-copilot-release/assets/489231/d2ca3da8-1736-489b-bcd7-bd0fa876f69c)

I know I have seen something where copilot shows what lines it is currently looking at, but I dont know how to force it to look.

**Comment by epipolarity** [comment]
Same. I found that it now only works if you have the code selected. But I thought it used to have access to multiple open documents without selecting anything. I also seem to have hit a limit today where the amount I have selected is too much, so it just gives the same message as you shared, saying it has no access.

**Comment by Londones** [comment]
I get the same issue but inconsistently, I was using it just fine for hours, and it just randomly started saying a variation of your message. It was not the 1st time, either. Though right now, it's saying that either my message is incomplete or that it can't understand a copied error message.

**Comment by amirna2** [comment]
I have similar issues. Previously I was able to highlight code from an open tab  and use it in my prompt but now it just says
```
I'm sorry, but as a text-based AI, I don't have the ability to see or interact with your screen. However, you can copy and paste the code here, and I'll be glad to help you with it.
```

I can't possibly copy/paste the whole file as it is too long. If this was intentional, it seriously reduces the usefulness of copilot as a refactoring assistant tool.

**Comment by TeemuHarinen** [comment]
Copilot chat introduced new context variables in version 0.12, this means by default it doesn't "see" all your code. Not sure if this was intended or not. https://github.blog/changelog/2024-02-12-vs-code-copilot-chat-january-2024-version-0-12/

A temporary fix what worked for me is to include #editor in all of my prompts to provide the context. However it's kinda broken, since it can only view the current file you have open and not all the file open in the editor. I think  #selection is supposed to act like this, not #editor.

**Comment by sailxjx** [comment]
I need to change to the old the behaviour, or at least, provide a setting that can be toggled to allow the chat to access and view the currently open files in VSCode.
Don't force me to enter #editor every time.

**Comment by digitarald** [comment]
The latest release should fix general context awareness. Follow-up work for large files is tracked in https://github.com/microsoft/vscode-copilot-release/issues/1083
