### ISSUE TITLE
Error from provider: Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by Rudresh-sisode** [microsoft/vscode-copilot-release#905]
- VS Code Version: 1.87.0 insider
- OS Version: Windows-NT x64 10.0.22621
- Logs:

Steps to Reproduce:

1. I'm asking question to copilot but it's not working, 
"Error from provider: Cannot read properties of undefined (reading 'map')" this error is occuring
2.

**Comment by Rudresh-sisode** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/52784991/5db10dec-0eb4-4560-8b67-5b38fae7dad8)

please check the image for better understanding

**Comment by roblourens** [comment]
Please make sure that you're using the latest version of Insiders, and also the latest pre-release version of the extension.

**Comment by Rudresh-sisode** [comment]
After changing the version of copilot chat to release one, it worked.
