### ISSUE TITLE
github copilot - subscription conflict

### ISSUE THREAD

**Issue by viclunam** [microsoft/vscode-copilot-release#909]
- VS Code Version: 1.86.2 (Universal)
- OS Version: Darwin x64 22.6.0

1. i have the github copilot subscription (personal)
2. An organization I am part of has just added github copilot, so I also have access.

The organization disabled github copilot chat, so I can't access its functionalities.

Is there any way to make github copilot consider my personal subscription ?

**Comment by aiday-mar** [comment]
Hi @lramos15 do you know if this is something we can fix, or should @viclunam address the question to someone else?

**Comment by canuckjacq** [comment]
You can't have more than one Copilot subscription. A Copilot for Business seat will cancel your individual plan, so you only have access via the org, which means their settings apply. If you were on a paid Copilot plan, you should see a refund in your billing history. 

You can ask the org to remove you, and then you can re-subscribe and use your own settings.

**Comment by viclunam** [comment]
Entiendo, gracias.
