### ISSUE TITLE
copilot has lost ability to answer basic questions using @vscode and other

### ISSUE THREAD

**Issue by allancorrigall** [microsoft/vscode-copilot-release#912]
copilot seems to have lost its ability to answer basic questions, and keeps giving boilerplate answers that are in no way relevant.

![image](https://github.com/microsoft/vscode-copilot-release/assets/6101356/b048cede-0bc5-487d-bc8a-133948552a7a)

**Comment by allancorrigall** [comment]
issue occurs in both release version and nightly build.

**Comment by lramos15** [comment]
Please try the latest insiders + latest pre-release as I cannot repo
<img width="316" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/4544166/dc797dc8-427d-4f0d-933f-b7a1e7ae3b5a">
