### ISSUE TITLE
#File operation bug

### ISSUE THREAD

**Issue by Rafcin** [microsoft/vscode-copilot-release#916]
- VS Code Version: 1.86.0
- OS Version: Ubuntu 22.04
- Logs:

Steps to Reproduce:

1. Create two files, in this case I created schema.prisma and sample-user.json
2. I then used the file operation to ask copilot to compare the JSON to the schema and see if they are compatible. 
3. File operation fails and it only ever references one file.
4. ![Screenshot from 2024-02-19 18-56-44](https://github.com/microsoft/vscode-copilot-release/assets/10494843/061e6e75-95d5-4e3e-a9b6-81bdbf2a0b35)

**Comment by Soheilsad** [comment]
Having the same issue. this is incredibly frustrating.

**Comment by roblourens** [comment]
Most likely, these files were too large and weren't able to be included. It isn't clear right now when this happens, but I plan to make that more clear in the future. Does that seem like the case?

**Comment by tg90nor** [comment]
What is too large? I'm unable to reference a file with 750 lines of source code (24 KB), which for the projects I'm usually working on is rather on the small side.

**Comment by roblourens** [comment]
Well, it depends on the file, how it tokenizes, and other context that must be added. I have this issue to make it more transparent though: https://github.com/microsoft/vscode-copilot-release/issues/926
