### ISSUE TITLE
can't auto reference opened code

### ISSUE THREAD

**Issue by GeekMaster85** [microsoft/vscode-copilot-release#918]
Type: <b>Bug</b>

Copilot chat can auto reference opened code on my machine previously. Lately, I have to select code manually for it to reference. Is there a setting where I can toggle auto reference?

Extension version: 0.12.2
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.23536
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (2.15GB free)|
|Process Argv|--crash-reporter-id b0ea2c93-a2f7-43cf-bcb6-1bd14278abff|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30967273

```

</details>

**Comment by GeekMaster85** [comment]
Previous
![image](https://github.com/microsoft/vscode-copilot-release/assets/95865003/c2345732-dd51-440a-9261-c23fc5188e70)
now
![image](https://github.com/microsoft/vscode-copilot-release/assets/95865003/dd8ba15d-338a-4ee7-b0fb-ceab910fb16f)

**Comment by HuanMeng0** [comment]
#890

**Comment by joyceerhl** [comment]
We now include your active file based on the [implicit context widget](https://code.visualstudio.com/docs/copilot/copilot-chat#_chat-context), please let us know if that's not working as expected
