### ISSUE TITLE
Sorry, your request was rate-limited. Please wait and try sending again later.

### ISSUE THREAD

**Issue by scallop123** [microsoft/vscode-copilot-release#920]
This error is marked as 'resolved' but many users are still seeing it.

**Comment by LaurentOngaro** [comment]
Same problem for me with the current version. This was not the case in the previous one, but I don't know from which version the problem appeared

**Comment by maciej-wakula-opuscapita** [comment]
I'm seeing this as well. Using Copilot Business. After 2 re-tries I finally got it sent and afterwards received `unhandled status from server: 408 Request Timeout`

**Comment by thekristaps** [comment]
Same issue here. Rate limited.

**Comment by changshunxu520** [comment]
Same issue here. Rate limited.

**Comment by andreicode** [comment]
Same here. Rate limited.

**Comment by ashwani1218** [comment]
Same issue here, Rate Limited.

**Comment by berrutti** [comment]
Every other request is rate limited.

**Comment by lcainswebdeveloper** [comment]
Me too! Sudden rate limiting errors and i'm not on the free plan

**Comment by paprikka** [comment]
Same here

**Comment by norayesnir** [comment]
Same issue here

**Comment by borislipo** [comment]
same here

**Comment by kanaan-dvlps** [comment]
Same here, using copilot chat

**Comment by carameloKevin** [comment]
Same here. I just reformat the question to copilot and it starts working

**Comment by ErisDwarf322** [comment]
Yes I have been getting it several times today I have never previously had it

**Comment by asleekgeek** [comment]
Same here:

"Sorry, your request was rate-limited. Please wait and try sending again later."
Using vscode.

I have a paid individual account.

**Comment by ewiik** [comment]
I am also having this problem right now, and I am on the paid github copilot (well still in the free trial window but..)

**Comment by roblourens** [comment]
There was a service-side issue which should now be resolved- sorry for the trouble everyone!

**Comment by ivana-g** [comment]
I see this issue was resolved on Feb 20, but I just started receiving this error. Can anyone please explain what does limited rate mean? Does this mean that the quantity of requests I can make is limited? I don't recall seeing this in a documentation. Thanks.

**Comment by CodeBreaker518** [comment]
same mas @ivana-g i just got this error too

**Comment by howar31** [comment]
same here

**Comment by dkumza** [comment]
confirm, same error

**Comment by ricardodasi** [comment]
Same issue again....

**Comment by ThimanKrish** [comment]
Same here. Tried restarting vscode, with new chat but no luck.

**Comment by NicciWill-Solutions** [comment]
Same issue here, as well.

**Comment by bugerchip** [comment]
Same

**Comment by codebyeli** [comment]
Encountered this issue just now, using the Copilot extension on VSCode.

**Comment by haternesto** [comment]
> Encountered this issue just now, using the Copilot extension on VSCode.

The same case on my side

**Comment by digitarald** [comment]
Duplicate of #1610
