### ISSUE TITLE
GitHub Copilot Sorry, your request was rate-limited. Please wait and try sending again later.

### ISSUE THREAD

**Issue by Jasiel-Stark8** [microsoft/vscode-copilot-release#923]
This issue was resolved Jan 10, and it seems to be back again.
I've been away the whole night and just received this after 3 prompts
What is the cap for subscribed users?

**Comment by 4ugusta** [comment]
here also

**Comment by firasglai** [comment]
Also here i have to reload my IDE again so i can use for few more prompts and then is back again

**Comment by YourDailyMoose** [comment]
The same happening here; however, it works the next time I submit my prompt again.

**Comment by leonardo-travagini-delboni** [comment]
same with me

**Comment by alexander-nolan** [comment]
I've been getting this all morning. I'm also now getting this - "Sorry, the response matched public code so it was blocked. Please rephrase your prompt."

**Comment by AhsanHasan** [comment]
I am getting the same issue, also I am getting "Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again". Although i haven't asked anything which might be labeled as irresponsible. Shame!

**Comment by TomasMurua** [comment]
same here...

**Comment by craftzneko** [comment]
Getting the same, also randomly getting "Sorry no response was returned" halfway through it giving me an answer.

**Comment by wickedw** [comment]
Same here, thanks.

**Comment by Jasiel-Stark8** [comment]
Guys check if it has been restored

**Comment by malah-code** [comment]
same here

**Comment by TomasMurua** [comment]
<img width="489" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/71956038/03046c1b-d44e-43d3-8baf-fd7f6cd4b93d">

no change

**Comment by PeterScream** [comment]
same issue - **more context here.** 
Came across same issue on windows machine, went back to my mack as I knew there was a older version of plugin, vscode and **it worked until I updated** everything to latest version. 

sadly using option "select pre-release" version seams to have problems with @workspace - and @vscode co thats not really a workaround.

**Comment by Abdelhz** [comment]
Paid version (indiv licence)
Getting the same issues as you all !

The worst is that Copilot now seem to have reverted to a much weak version !

Responses seem to be non accurate and very bad in comparison to yesterday !

**Comment by Nickb6437** [comment]
Getting the same issue, nearly every other request or so 

On a paid license.

**Comment by Jasiel-Stark8** [comment]
> same issue - **more context here.** 
> Came across same issue on windows machine, went back to my mack as I knew there was a older version of plugin, vscode and **it worked until I updated** everything to latest version. 
> 
> sadly using option "select pre-release" version seams to have problems with @workspace - and @vscode co thats not really a workaround. 

I'm using Kali, so it's not an OS issue for sure

**Comment by Jasiel-Stark8** [comment]
For now, don't use the chat. Just let it feed suggestions into the code area. That's what I did. The rate limit is initiated with a chat instance only.
Hopefully, it gets resolved. It could be maintenance of Microsoft systems as it was a month ago.
