### ISSUE TITLE
Hard to tell whether chat variables were used

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#926]
Submit a chat request with some `#file` or other variables. Since variables don't show up "used references", it's impossible to tell from the UI whether or not they were actually used by the agent. They may not be used if they represent a lot of data that doesn't fit into the context window. We should always add variables to "used references" so that when they're missing, you know that they weren't used.

It would still be helpful to know specifically _why_ they were missing and have even more feedback here, so we can probably go further.

We can also do more to compress the values of variables to fit more data into the context window.

**Comment by sbracegirdle** [comment]
Yeah, to add some extra commentary here, I notice when I tag multiple files with `#file`, and then ask a question about those files, it'll often say "I don't have access" or will hallcuinate something unrelated. Anecdotally I don't seem to have that issue when selecting code in the editor, and getting a "used reference" that way.

It would be great if using `#file` worked exactly the same as selecting text and getting a "used reference".
