### ISSUE TITLE
Looks like #file handle is broken and the Copilot hallucinates entire file

### ISSUE THREAD

**Issue by RB-Lab** [microsoft/vscode-copilot-release#932]
- VS Code Version: 1.86.2 
- OS Version: mac OS Sonoma 14.2.1 (23C71) 
- Logs: (lost, I restarted the editor)
- Copilot Chat version: v0.12.2

Steps to Reproduce:

Not sure, if these steps will actually reproduce the problems, but here's what I did:

1. Ask a lot of questions with selection (I didn't use `#selection` handle, just selected text and asked a question)
2. Ask a question about `#file:file.py`
3. Get ??? about the answer
4. Ask to print `#file:file.py` content

**Expected result:** the `file.py` content is printed
**Actual result:** the poor bot puts all selection pieces from the previous conversation and hallucinates an entire somewhat coherent file out of it and prints that file. Apparently, between steps 2 and 3 it tried to explain that file, not the real file attached by `#file` handle.

**Comment by RB-Lab** [comment]
Apparently, in new chat it can access the file provided by `#file` handle.
<img width="487" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5694678/992f8781-1a2c-4ad4-bad3-eed5560c2121">
Although this time the "used reference" is incorrect.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/926
