### ISSUE TITLE
Anything I say or put in chat gets this response "Oops, your response got filtered. Vote down if you think this shouldn't have happened." 

### ISSUE THREAD

**Issue by Jmatyas0** [microsoft/vscode-copilot-release#934]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce
<img width="270" alt="Screenshot 2024-02-22 at 14 38 44" src="https://github.com/microsoft/vscode-copilot-release/assets/144806686/b54b4177-771f-46a5-b5f0-80fc40baadf1">

1. Ask copilot to do anything

**Comment by RishabhShukla04** [comment]
yes me too its so frustrating

**Comment by erikschull** [comment]
Same here.  This tool is absolutely broken for me.

**Comment by lramos15** [comment]
Please ensure you're on the latest version and include your logs via `CMD / CTRL + SHIFT + U ` -> `Copilot Chat`

**Comment by QiaohuiGao** [comment]
same. The solution didn't work on me.

**Comment by QiaohuiGao** [comment]
2024-02-23 18:06:53.858 [info] [fetcher] Using Helix fetcher, Electron fetcher is not available.
2024-02-23 18:06:53.858 [info] [code-referencing] Public code references are enabled.

**Comment by lramos15** [comment]
@QiaohuiGao Can you include more logs

**Comment by QiaohuiGao** [comment]
> @QiaohuiGao Can you include more logs
Hi, I solved this problem yesterday. I deleted my VS code and downloaded the latest version. Then the copilot works.
