### ISSUE TITLE
unhandled status from server: 410

### ISSUE THREAD

**Issue by keith666666** [microsoft/vscode-copilot-release#936]
- VS Code Version: 1.80.1
- OS Version: macOS Ventura 13.2.1 (22D68)
- Logs:
```
[INFO] [default] [2024-02-22T15:22:17.758Z] [fetchChat] engine https://copilot-proxy.githubusercontent.com/v1/chat
[INFO] [default] [2024-02-22T15:22:18.515Z] request.response: [https://copilot-proxy.githubusercontent.com/v1/chat/completions] took 757 ms
[ERROR] [chat fetch] [2024-02-22T15:22:18.518Z] Unhandled status from server:,410,{"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.4.1","editor-version":"vscode/1.80.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}
```
![image](https://github.com/microsoft/vscode-copilot-release/assets/14068334/709c266a-1ec7-45e5-8ffc-fd277cee18d4)

Steps to Reproduce:

1. open copilot chat
2. send anything 
![image](https://github.com/microsoft/vscode-copilot-release/assets/14068334/0da1f73c-deb6-46e6-84d1-ef8ec9f4596e)

**Comment by Samson-Vaisala** [comment]
Also experiencing this issue. 

`unhandled status from server: 410 {"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.7.2023081101","editor-version":"vscode/1.81.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}`

**Comment by raghavdixit99** [comment]
also experiencing the same :

`unhandled status from server: 410 {"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.6.0","editor-version":"vscode/1.81.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}`

**Comment by testererrewr** [comment]
Windows 10 same issue in Visual studio code

**Comment by auchiya** [comment]
same here 
`unhandled status from server: 410 {"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.4.1","editor-version":"vscode/1.80.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}`

**Comment by MaheeGamage** [comment]
Getting the same issue.
Windows 11, Version 10.0.22631 Build 22631
VSCode

**Comment by august-medhus** [comment]
same: 

unhandled status from server: 410 {"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.6.0","editor-version":"vscode/1.81.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}
;

**Comment by Totoual** [comment]
same: 

```
unhandled status from server: 410 {"error":{"agent-version":"","details":"https://github.blog/changelog/label/copilot/#%F0%9F%8C%90-upcoming-deprecation-of-copilot-chat-api-endpoints","editor-plugin-version":"copilot-chat/0.4.1","editor-version":"vscode/1.80.1","engine":"copilot-chat","message":"copilot-proxy.githubusecontent.com is no longer accepting chat requests. Please update your IDE extension to continue using GitHub Copilot chat."}}
```

**Comment by lramos15** [comment]
This means your VS Code and extension version are too old. You must update VS Code and update to the latest version of Copilot Chat

**Comment by keith666666** [comment]
> This means your VS Code and extension version are too old. You must update VS Code and update to the latest version of Copilot Chat

Thanks, the error is gone after upgrade VS Code to 1.86.2 and GitHub Copilot Chat to v0.12.2
