### ISSUE TITLE
Copilot ignores files even if filename is mentioned with @workspace

### ISSUE THREAD

**Issue by qwertie** [microsoft/vscode-copilot-release#938]
- VS Code Version: 1.86.2
- OS Version: Windows 10
- Logs: I don't think you need logs to reproduce?

Steps to Reproduce:

It appears that Copilot simply ignores instructions to look inside specific files, even when using `@workspace`. It also ignores whatever file I'm currently looking at. Example:

> @workspace I want unit tests for this function, which are going to be snapshot tests that simply verify that the output is the same as it always has been. Please use the helper functions for creating entities and connections in test-helpers.ts

> export function exportToLayerBlob(selection: Array<Entity | Connection>, data: ScenarioData, format?: 'kml'|'geojson'): Blob { ... }

Copilot response:

> Used 9 references [none of which are the file I asked for, and only one of which was relevant]

Me:

> Copilot are you unable to look at the functions inside test helpers

Copilot:

> As an AI, I don't have the ability to directly access or view your files. I generate responses based on patterns and information I've learned during my training. I can provide general advice on how to use helper functions in tests based on common practices, but I can't provide specific advice based on the actual content of your test-helpers.ts file.

Me: 🤦‍♂️

P.S. I don't understand the instruction to "test using the latest insiders build to make sure your issue has not already been fixed". The Extensions Marketplace is the same regardless of whether one uses Insiders or normal VS Code, is it not? I am seeing the same version of Copilot in both anyway (v1.165.0).

**Comment by onx001** [comment]
+1 same problem faced

**Comment by mjbvz** [comment]
Please share an example project and set of questions that cause this

For the future, you can also explicitly include a file using `#file` in your question
