### ISSUE TITLE
Can't send messages to copilot chat

### ISSUE THREAD

**Issue by aribornstein** [microsoft/vscode-copilot-release#941]
Type: <b>Bug</b>

Though it was working two days ago now I can no longer send messages in github copilot chat the send button hi lighted in green does not respond and the enter key doesn't work. I can still use copilot with cmd + I but not the chat.

![image](https://github.com/microsoft/vscode-copilot-release/assets/3045407/9a200bfc-fdfb-4c2f-b8bc-8621ca15beaa)

Extension version: 0.12.2
VS Code version: Code - Insiders 1.87.0-insider (1cc266cc82838981034c2baa637f357a83711d5d, 2024-02-22T22:52:59.987Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|42, 34, 15|
|Memory (System)|32.00GB (13.99GB free)|
|Process Argv|--crash-reporter-id 7808ae11-7f02-4084-9fc2-870122a8abc5 --crash-reporter-id 7808ae11-7f02-4084-9fc2-870122a8abc5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
vsaa593:30376534
py29gd2263:30784851
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
bf62j303:30968145
pydisww2:30959801
cppperfnew:30963552
d34g3935:30961436
edj9j583:30969294
fegfb526:30952798
7j2b6412:30951517
e3gdj431:30946825
ccp1r6:30958151
pythonaic:30968499

```

</details>

**Comment by eacabbi** [comment]
having the same exact problem here

**Comment by win21H2** [comment]
I think copilot went offline yesterday but should be working now.

**Comment by xvaleriex** [comment]
same here

**Comment by SHalabiD** [comment]
same

**Comment by SHalabiD** [comment]
I just updated and restarted vs code and is working as expected

**Comment by Yangbodi** [comment]
I also have the same problem, uninstalling and reinstalling are still the same, and even if I change my computer, I still cannot use the chat function

**Comment by Kevinello** [comment]
same here, and i got suspicious logs in copilot chat output:
```
[chat] Registration of chat agents failed:,TypeError: na.chat.createChatAgent is not a function
```

**Comment by Victor-Botelho** [comment]
Switching to pre-release version worked for me, as suggested [here](https://github.com/microsoft/vscode-copilot-release/issues/436#issue-1918583137)

**Comment by Harvnlenny** [comment]
I'm experiencing this same behavior.
I've restarted VSC. I've signed out of Github and then signed back in.
I've restarted my laptop. I've checked to make sure I had the latest VSC and github copilot and chat.

Nothing seems to be working currently. If I try to pull up my chat history it only appears for a split second before going back to a blank chat. If I try to type in a new question I can't click to send that question to chat.

**Comment by roblourens** [comment]
When you are using Insiders, please use the latest pre-release version of the extension

**Comment by Nicholas-Autio-Mitchell** [comment]
@roblourens   I am using the latest VSCode Insiders with the latest pre-release of Copilot and Chat extensions, but am seeing the same issue. 

Additionally, I am unable to open any chat history entries. Clicking on the history icon does open the list to select from as expected, but selecting any of them, I just get a flicker of something then a blank grey panel. Is this a known issue?

(total coincidence btw, that I write this minutes after you close the issue)

**Comment by Boomboom-nightclub** [comment]
Experienced this as well this morning, i just update to the new version and reload the new update. It run well now.

**Comment by Rishita317** [comment]
I experienced the exact same issue I could't send any messages to copilot chat. The problem was my settings sync wasn't turned on. 

How to fix this:

Step 1: Click on settings on the bottom left corner in VS code
Step 2: Click on setting sync it will ask you to sign in with either microsoft or github
step 3: That should direct you back to VS code and the copilot chat should now work again
Step 4: if this still doesn't work try restarting VS code. 

Hope this helps :)

**Comment by copdips** [comment]
same here. tried pre-release and also reenable setting sync
