### ISSUE TITLE
Chat windows full screen an draggable

### ISSUE THREAD

**Issue by arambazamba** [microsoft/vscode-copilot-release#942]
It would be fine if one would be able to have the ability to drag the copilot chat as a main full size window or a split of the screen. Some people have large monitors with 32" 4K, and it would be great to be able to position the Copilot chat window wherever it fits my needs and use my available space. At the current position it hides my Explorer window.

![image](https://github.com/microsoft/vscode-copilot-release/assets/16348023/ddd0ce53-2abd-43de-a106-6caa88c5ba10)

**Comment by roblourens** [comment]
You can click the `...` button in the top toolbar and use "Open Chat in Editor" or "Open Chat in New Window"

**Comment by arambazamba** [comment]
@roblourens You are my hero!!! Thanks a lot
