### ISSUE TITLE
Chat is unable to recognize context and keeps blocking public code

### ISSUE THREAD

**Issue by cbdev74** [microsoft/vscode-copilot-release#943]
1- Copilot Chat keeps blocking public code matches even if I allowed it from settings.

2- Despite the chat's interface says that it is using the highlighted code as reference, Copilot is completely unable to recognize that it has the reference, so it must "assume".

Honestly I was enthusiastic at the beginning, but the more i use it, the more I think I'm wasting time.

**Comment by cbdev74** [comment]
Tried to re-install the entire VSCode environment, works better for now.

**Comment by cbdev74** [comment]
I have to re-reopen this issue because Chat is still unable to recognize the reference.

![image](https://github.com/microsoft/vscode-copilot-release/assets/156440636/8ca53645-e746-47c8-9485-4ef9a95b6632)

**Comment by cbdev74** [comment]
Ok, this is not solved. Chat keeps ignoring the highlighted code, despite it says that it is currently using it as reference:

![image](https://github.com/microsoft/vscode-copilot-release/assets/156440636/d3711ded-db6b-4cfb-9404-dad9408f34d6)

This is beyond extremely annoying and bothering, absolutely unacceptable. Now, one can argue that the highlighted code is 'too long', but until this afternoon it was working fine. 

I'm using VS Code in Ubuntu (version 22.04) WSL, Windows 11 Professional. As I specified above, I tried to reinstall everything, and it worked fine for like 10 mins, then it started again ignoring references. This is unacceptable.

**Comment by cbdev74** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/156440636/c20fcab0-59a0-4cb5-aa26-b359f8c36b79)

![image](https://github.com/microsoft/vscode-copilot-release/assets/156440636/ea058cee-118e-44b3-a400-1a030d97b6cc)

In this one we can see that it is able to handle a shorter code, but not a longer one. Again, this is the first time I have this issue, since it was always able to read much larger code, even thousands of lines.

**Comment by Gleepoj** [comment]
I've got exactly the same issue, and other issues seems similar ... @workspace seems to work, but i've already waste to many time with this shovelware today to investigate more !

**Comment by cbdev74** [comment]
After days of waiting, not even a reach from assistance. Closing the issue and deleting my subscription. Github Copilot is complete garbage, and it's not even free.

**Comment by cbdev74** [comment]
@Gleepoj  I agree with you, it's a showelware. I hope they'll improve it because by now it is complete garbage and it's not even free. Sorry Github, but I cancel my subscription.
