### ISSUE TITLE
Add @editor or @openfiles context method

### ISSUE THREAD

**Issue by TrevorBenson** [microsoft/vscode-copilot-release#945]
## Request

Create a method which is similar to @workspace, but is limited to scanning each file which is open in the editor. A scan of additional files in the repository should not happen, as all relevant files will be open in the editor, with the primary file being discussed being the one given the editors current focus, and each additional reference being open in the editor but not provided the editors focus.

## Reasoning
In large repositories the @workspace method rarely finds the correct files, even when provided function and class names, file names, or even relative or fully qualified paths. Even when the files required to reference are the only files open in the editor and this is told to copilot. Often telling it the files are open can lead to a response that "copilot is an AI which cannot access your files", which is clearly not the case, but somehow when too much content exists Copilot I think "taps out" and gives up. In these cases the references used can be completely unrelated to the discussion and result in suggestions which have relatively low relevance.

The ability to force the references to be scanned from only the editors open files, and each file, could be extremely helpful in providing the user the ability to easily increase the relevance of suggestions. I'm fairly confident this should be a worthwhile feature if it works as described. I can simulate what I presume should be a fairly similar effect by creating a single temporary file and copying chunks of relevant code from multiple files into the temp file, then using this as the only reference for a discussion. While this works it is time consuming to do for the user, leads to extra files that need to be cleaned up later, or worse, repeated blocks of code in non temporary files which might be missed during "cleanup" after the conversation.

**Comment by digitarald** [comment]
@TylerLeonhardt this is about having a `#workspace`-like variable that limits semantic embeddings to open files (similar to copilot completion's default behavior). Does that fall into your area?

**Comment by TylerLeonhardt** [comment]
@TrevorBenson you should be able to use `#editor` when talking about the active editor or `#selection` for your selection in that editor. Additionally there's `#file:....` to include certain files.

@digitarald honestly, not sure. Feels like it would be more @roblourens as it feels closer to `#editor` and `#selection` than `@workspace`, but maybe it goes to any of the `@workspace` people...

**Comment by TrevorBenson** [comment]
> @TrevorBenson you should be able to use `#editor` when talking about the active editor or `#selection` for your selection in that editor. Additionally there's `#file:....` to include certain files.
> 
> @digitarald honestly, not sure. Feels like it would be more @roblourens as it feels closer to `#editor` and `#selection` than `@workspace`, but maybe it goes to any of the `@workspace` people...

I was not aware `#` was an alternative symbol to `@`, searching the copilot chat docs I can't seem to find `#edtitor`, `#file`, or other hashtag methods, described in the copilot chat docs.

However, I tried the `#editor` option and it does not seem to achieve the goal. With three open files in the editor and either: nothing highlighted; a section of code highlighted; the entire file highlighted, only the active file in the editor is used as a reference. The other open files in the editor are not used as a reference.

I also tried `#file:path/to/file.py` and `#file: path/to/file.py` and `#file path/to/file.py`. Each time only the foreground file in the editor is used as a reference, the file from the path is never part of the references used to formulate a response. :shrug:

**Comment by TylerLeonhardt** [comment]
@roblourens correct me if I'm wrong, I think if you include context via a variable (`#`) it doesn't show up in the references because the references are only things that were implicitly used.

If you use a variable, it's definitely used to formulate a response.

**Comment by roblourens** [comment]
If you use a variable, we will try to use it, but it may not fit into the context window if the file is too big.

And yeah, I would like to make `#file` easier to use, for example we could show references for all the open files in the suggest widget, and an `#openFiles` variable might make sense too.

**Comment by TrevorBenson** [comment]
> If you use a variable, we will try to use it, but it may not fit into the context window if the file is too big.
> 

I definitely understand that files that are quite large can exceed the number of tokens that can be handled in a single request, as I've seen this with even a single file.

> And yeah, I would like to make `#file` easier to use, for example we could show references for all the open files in the suggest widget, and an `#openFiles` variable might make sense too.

Yes, anything that provides more clarity to the user on what files will be chosen or can be influenced to be chosen, would be a very welcome enhancement. 

Thanks
