### ISSUE TITLE
chat with workspace 

### ISSUE THREAD

**Issue by uset82** [microsoft/vscode-copilot-release#948]
GitHub Copilot Chat revolutionizes coding by allowing developers to generate entire workspaces from scratch using natural language. However, once a workspace is created, the current iteration lacks the capability for ongoing, in-depth interaction with the codebase. This proposal introduces the concept of expanding Copilot Chat with three distinct "brains" or modes: a Simple Chat, a Code Control Brain, and a Code Conversation Brain, each tailored to different stages and types of user interaction.

Current Limitation:
After initial workspace generation, users may find themselves needing more nuanced and direct interaction capabilities with their code. The current setup does not support continuous, context-aware conversations with the existing code or offer granular control over code manipulation and understanding through the chat interface.

Proposed Feature Details:
Simple Chat Mode: This mode would handle general queries and provide assistance similar to the current functionality but enhanced for more generalist advice, documentation lookup, and coding best practices. It's aimed at broad, non-project-specific interactions.

Code Control Brain: A specialized mode focused on understanding and manipulating the codebase. It would offer capabilities such as refactoring code, suggesting optimizations, debugging, and adding new features or functionalities directly through conversation. This brain would have deep integration with the user's current workspace, providing precise and context-aware actions.

Code Conversation Brain: Designed for an interactive dialogue about the open code in the editor, this mode would allow developers to discuss their code with Copilot as if they were pair programming with a colleague. Questions could range from "Why is this function implemented this way?" to "What are the potential side effects of this method?" This conversational approach would facilitate a deeper understanding of the codebase and support educational and exploratory coding practices.

Benefits:
Enhanced Productivity: By offering specialized interaction modes, developers can work more efficiently, leveraging the most appropriate type of assistance based on their current task.
Improved Code Quality: Direct manipulation and conversation about the code could lead to better optimization, cleaner code, and more effective debugging.
Educational Support: The Code Conversation Brain can serve as a learning tool, offering explanations and discussions about coding decisions, patterns, and best practices.
Conclusion:
Integrating these three brains into GitHub Copilot Chat would significantly expand its utility, making it not just a tool for initiating projects but a comprehensive companion throughout the coding process. This feature request aims to bridge the gap between initial code generation and ongoing project development, ensuring that developers have access to tailored support at every stage of their work.

**Comment by roblourens** [comment]
Can you tell me more about what you feel is missing with the way things work currently?
