### ISSUE TITLE
Font sizes in rendered code

### ISSUE THREAD

**Issue by win21H2** [microsoft/vscode-copilot-release#949]
Hello all, I've had this small 'grudge' for a while but when I open copilot in the sidebar, the font size of the code rendered is almost always larger than the code in my actual programming window. This can be annoying especially when having to scroll sideways to see what code is produced (the example below shows what I'm talking about better).

Would it be possible to 'separate' the font sizes e.g. when I scroll out in vscode to decrease the font size of the editor, the font size in code rendered by copilot remains the same?

![image](https://github.com/microsoft/vscode-copilot-release/assets/92825997/bc6d2cdf-b058-45b6-a42d-ce9fcd9d25d5)

![image](https://github.com/microsoft/vscode-copilot-release/assets/92825997/4f0ec765-9af8-4099-8e39-b72ccc275235)

Best regards,
**9662e103-129a**

**Comment by roblourens** [comment]
You can control this by `chat.editor.fontSize` and set it to match the editor, does that help?

**Comment by win21H2** [comment]
Hello @roblourens, 
I added this to my settings.json file:
```json
"github.copilot.advanced": {
        "chat.editor.fontSize": "14px",
    }
```
but that doesnt seem to fix anything.

Best regards,
9662e103-129a

**Comment by roblourens** [comment]
It should be at the top level, the second way

![Image](https://github.com/microsoft/vscode-copilot-release/assets/323878/f1c50074-de54-4602-b2ec-5fb0bf6a6b60)
