### ISSUE TITLE
chat with my pdf file 

### ISSUE THREAD

**Issue by uset82** [microsoft/vscode-copilot-release#950]
It would be beneficial to have the capability to upload PDF files containing data requirements, previous code, instructions, and configurations similar to GPT settings

**Comment by piggyy** [comment]
+1

**Comment by TylerLeonhardt** [comment]
To do this, we really need custom instructions. I'm going to mark this as a duplicate of https://github.com/microsoft/vscode-copilot-release/issues/563 once we have that, then we can talk about providing instructions in other forms.
