### ISSUE TITLE
Outdated TypeScript  Help

### ISSUE THREAD

**Issue by felixphixer** [microsoft/vscode-copilot-release#951]
Steps to Reproduce

Asking GitHub Copilot (v 1.165.0) in VSCode (1.86.2)

"Please explain the 'satisfies' keyword in TypeScript" 

results in the following authoritatively ignorant response. 

----

There is no `satisfies` keyword in TypeScript. TypeScript has a set of keywords for type annotations, classes, interfaces, and other constructs, but `satisfies` is not one of them.

If you're seeing `satisfies` in a TypeScript context, it might be part of a comment or a string, or it might be a variable or function name, but it's not a built-in keyword in the language.

If you're looking at a type constraint or a way to express that a type should satisfy a certain condition, TypeScript uses interfaces, type aliases, and other constructs for this purpose.

...

**Comment by roblourens** [comment]
Yes, we need to be able to incorporate up-to-date documentation in general https://github.com/microsoft/vscode-copilot-release/issues/299
