### ISSUE TITLE
无法使用Copilot聊天功能

### ISSUE THREAD

**Issue by Yangbodi** [microsoft/vscode-copilot-release#952]
![1708913525415](https://github.com/microsoft/vscode-copilot-release/assets/154630721/84706a3a-e1bf-4ef1-a66b-3ea9ebaa80be)
我现在每次提问都是出现这个错误，基本功能都不能使用只能起到代码提示的作用
![1708913694122](https://github.com/microsoft/vscode-copilot-release/assets/154630721/d5c432de-371b-4eb9-a8a7-a28e8b99c0b1)

**Comment by lramos15** [comment]
Please update your version of VS Code and your extesnion and try again.

**Comment by Yangbodi** [comment]
> 请更新您的 VS Code 版本和扩展程序，然后重试。

It's back to normal. Thank you
