### ISSUE TITLE
Disable prompting to grant access to my github account

### ISSUE THREAD

**Issue by karlkeefer** [microsoft/vscode-copilot-release#960]
The copilot chat extension keeps asking me to grant access to various repositories, including those owned by organizations I'm a part of.
There doesn't seem to be a way to disable this alert, which interrupts every vs code session I start.

I feel like I _must_ be missing something somewhere in the docs, because it seems like a really common thing folks might not want to enable...

**Comment by TylerLeonhardt** [comment]
This has been improved in the pre-release version of Copilot Chat. Can you grab that and give it a spin?
