### ISSUE TITLE
Code block disappears when resizing chat sidebar

### ISSUE THREAD

**Issue by LamatFTP** [microsoft/vscode-copilot-release#961]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

**Comment by roblourens** [comment]
Please give some more info, a screen recording might help. 

You can also check for errors in the "Window" output channel

**Comment by LamatFTP** [comment]
Screen Recording 2024-02-27 at 19.34.39.mov
<https://drive.google.com/file/d/1nd2XkuIu_ExJUQNV5nuMlYmPMvI8zk_b/view?usp=drive_web>
Please find attached a screen recording


Thanks and best Regards
Lamat


Fishtankproduction
Email   ***@***.***
Website   https://fishtankproduction.com

**Comment by roblourens** [comment]
Attachments can't be sent over email, you will have to upload it to github.com
