### ISSUE TITLE
please bring the chat auto-reference back

### ISSUE THREAD

**Issue by maxfaa** [microsoft/vscode-copilot-release#963]
can you please bring the copilot chat auto-reference back, at least as an option in the extension settings. this new "update" is really a huge step back... (now we have to press `cmd A` every time we use copilot chat or it is dumb and loses its attractiveness) :/

**Comment by jrieken** [comment]
> can you please bring the copilot chat auto-reference back

Sorry, but I don't understand what you refer to. Can you describe in more details what used to work and apparently has been removed/broken?
