### ISSUE TITLE
I Have to ask it for time complexity of everything!

### ISSUE THREAD

**Issue by DamianEstey** [microsoft/vscode-copilot-release#965]
It would be really, really cool if Github Copilot just presented the time complexity on the side in some little box; even a tiny one! More specifically, if it generates code; that code no matter how mundane should have some time complexity displayed if a data structure is present.
This may be too much to ask and that is fine but if it is then just say it is.

**Comment by lramos15** [comment]
I believe this falls under https://github.com/microsoft/vscode-copilot-release/issues/563
