### ISSUE TITLE
Coding related questions are being filtered

### ISSUE THREAD

**Issue by slice-Adityaraj** [microsoft/vscode-copilot-release#967]
"can I add again a go routine inside worker"

GitHub Copilot : 
Sorry, but I can only assist with programming related questions.

**Comment by Perusae** [comment]
We are getting "Sorry, the response was filtered by the Responsible AI Service. Please rephrase your prompt and try again" as a response on that question?!

**Comment by mempler** [comment]
![image](https://github.com/microsoft/vscode-copilot-release/assets/33131394/edffb322-a8e2-4ecd-8882-6fd3b9820110)
it can see that i have a TS file open, which is obviously webdev related. How is it so bad ?

**Comment by digitarald** [comment]
We updated the off-topic filter and see a significant drop in false-positive filtering in experiment results.

Closing as fixed, but please don't hesitate to file new issues in case you still run into this.
