### ISSUE TITLE
The document generation function of copilot should generate documents in the corresponding language and should not default to English

### ISSUE THREAD

**Issue by z505985755** [microsoft/vscode-copilot-release#979]
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.Right click
2.Copilot
3.generation document

**Comment by joyceerhl** [comment]
We have a setting which allows you to configure which language Copilot responds in: 

<img width="972" alt="Image" src="https://github.com/user-attachments/assets/02eb0a6e-e537-4097-96d7-fb50faedeb1c" />
