### ISSUE TITLE
Copilot Chat Not give latest  information about framework

### ISSUE THREAD

**Issue by mr-chetan** [microsoft/vscode-copilot-release#98]
It gives 2021 results and so many changes in framework
![image](https://github.com/microsoft/vscode-copilot-release/assets/56998650/08c469cd-b849-41db-90d7-5f9db5c4cf66)

**Comment by ivorpad** [comment]
GitHub Copilot X utilizes the GPT-4 model, which means its training data is current only up until 2021.

**Comment by GhoulamMB** [comment]
> GitHub Copilot X utilizes the GPT-4 model, which means its training data is current only up until 2021.

It uses GPT-3
![image](https://github.com/microsoft/vscode-copilot-release/assets/97346336/aa0f53af-c231-4c90-bf82-956d285a1e58)

**Comment by Rettend** [comment]
Copilot Chat really needs Search and the internet!

**Comment by culstrup** [comment]
Just wanted to bump this. I asked Copilot to refactor my code, much of which involves calls to the GPT-4 API endpoint. It did a decent job, although it overwrote the OpenAI API endpoint calls with the completions spec as opposed to what works for the chat endpoint and it invoked text DaVinci 2 when I had been using GPT-4 before. It's sort of funny that a product powered by GPT-4 isn't aware of itself or how to query itself programmatically. Another reason why there needs to be an internet connection to retrieve up-to-date documentation about libraries, APIs, etc.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-copilot-release/issues/299
