### ISSUE TITLE
Codeblock streaming is not smooth

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-copilot-release#983]
- Get a codeblock in chat response, watch response streaming
- There is a lot of flickering- code appears and disappears, and the sizing is inconsistent

I'm guessing there is an issue with https://github.com/microsoft/vscode/pull/205943

**Comment by mjbvz** [comment]
Should be fixed/significantly improved by microsoft/vscode#208130

**Comment by roblourens** [comment]
![Recording 2024-03-26 at 11 40 07](https://github.com/microsoft/vscode-copilot-release/assets/323878/9ae9b228-2fac-49dc-bd7a-02afcf8f5fa6)
Still seems a bit off, I can help investigate
