### ISSUE TITLE
Fix multiple chat windows

### ISSUE THREAD

**Issue by streamville** [microsoft/vscode-copilot-release#985]
Hey team,

Would love it if we could try to contain Copilot Chat either in a single sidebar, editor, or window. For example, the small modal that pops up on a file with the button that says "View in Chat" will always get clicked because of the small screen real estate, and redirects the chat to the sidebar - which I don't mind but when I need to use the Explorer again, I will choose to open the chat in a new window. 

BUT - whenever I use the shortcut "Cmd + i" again to ask another question, the chat will redirect back to the sidebar instead of the separate window that I just had open. This is quite confusing when I just want the chat to remain in a single file or window. I hope this make sense.

Let me know if I'm using it correctly. Thank you all!

**Comment by bencbartlett** [comment]
+1 this would be pretty useful; I like to have the explorer window open but at a very narrow width, while the copilot chat is more comfortable at a wider width. It is tedious to have to constantly resize this pane when switching back and forth between these options.

**Comment by streamville** [comment]
It is quite tedious to constantly having to either resize or manually move the chat out of view. Not a great visual experience.

**Comment by roblourens** [comment]
Not sure I'm following the scenario, but does it help to move the chat view to the secondary sidebar so it's not in the same place as the Explorer?

Or are you just asking for "View in Chat" to open whatever the last-used chat was instead of going to the sidebar?
