### ISSUE TITLE
Copilot Chat UI Unresponsive After Latest Update on Linux and MacOS

### ISSUE THREAD

**Issue by ryandward** [microsoft/vscode-copilot-release#987]
**Issue Description:**
After updating to version 1.88.0-insider on both my Linux and MacOS systems, the Copilot Chat interface remains visible but is unresponsive. Previously, the feature worked as expected on both systems. The issue surfaced immediately following the latest update.

**Steps to Reproduce:**
1. With the Copilot Chat working correctly, update to version 1.88.0-insider.
2. After the update, attempt to interact with the Copilot Chat interface.
3. Notice that the interface is visible briefly, disappears, then you cannot interact.

![image](https://github.com/microsoft/vscode-copilot-release/assets/6970996/8a6d720a-3435-4eac-903e-ad291004a723)

**Expected Behavior:**
The Copilot Chat should be interactive and responsive to user input after the update.

**Actual Behavior:**
The Copilot Chat is visible but unresponsive to any form of user interaction on both Linux and MacOS systems.

**System Details:**

- **Linux System:**
  - Version: 1.88.0-insider
  - Commit: b148975cafa8f034592310659f3dc989b124685c
  - Date: 2024-02-29T22:45:19.703Z
  - Electron: 28.2.2
  - Chromium: 120.0.6099.276
  - Node.js: 18.18.2
  - V8: 12.0.267.19-electron.0
  - OS: Linux x64 6.7.5-arch1-1

- **MacOS System:**
  - Version: 1.88.0-insider (Universal)
  - Commit: b148975cafa8f034592310659f3dc989b124685c
  - Date: 2024-02-29T22:55:07.312Z
  - Electron: 28.2.2
  - Chromium: 120.0.6099.276
  - Node.js: 18.18.2
  - V8: 12.0.267.19-electron.0
  - OS: Darwin arm64 23.1.0

Both systems were functioning correctly with the Copilot Chat feature until the latest update was applied. The issue is consistent across both operating systems, indicating a possible regression introduced in the latest version.

**Comment by ryandward** [comment]
Temporarily I reverted to a previous version and the issue had disappeared. It's definitely part of the newest release.

Copilot chat is available in this version:
```Version: 1.88.0-insider
Commit: 8c2b09c0443b94d75a73819ed35610f7e09375ae
Date: 2024-02-28T19:00:39.000Z
Electron: 28.2.2
ElectronBuildId: 26836304
Chromium: 120.0.6099.276
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.7.5-arch1-1```

**Comment by barlowtj48** [comment]
Encountering the same issue on Windows 11 as well.
```
Version: 1.88.0-insider (user setup)
Commit: b148975cafa8f034592310659f3dc989b124685c
Date: 2024-02-29T22:51:22.369Z
Electron: 28.2.2
ElectronBuildId: 26836304
Chromium: 120.0.6099.276
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621
```

**Comment by scottishdeveloper** [comment]
Same

**Comment by roblourens** [comment]
Please make sure that you have the latest pre-release of Copilot Chat installed, everything should be in sync now.

**Comment by KoheiKanagu** [comment]
I installed Version 0.14.2024030101 of Copilot Chat and this issue was resolved.

**Comment by barlowtj48** [comment]
Updated to latest (v0.14.2024030102), all seems to be working again for Windows 11

**Comment by Band-Aid** [comment]
Still not working for me on macos sonoma 14.4 
copilot v0.14.2024032101 (pre-release)

**Comment by roblourens** [comment]
I think the original identified issue is fixed, @Band-Aid if you still have issues could you open a new issue and include the Copilot Chat outptu channel, and some more details about what exactly you see? Thanks
