### ISSUE TITLE
Copilot errors appearing in problem panel (typescript's language server is linting copilot's answers / vscode is checking copilot)

### ISSUE THREAD

**Issue by bn-l** [microsoft/vscode-copilot-release#989]
Screenshot:

![image](https://github.com/microsoft/vscode-copilot-release/assets/13162197/67dfaa5d-d1ce-4408-8ebf-c99142f9a9b8)

Typescript output:
```
2024-03-01 11:46:40.819 [info] Using tsserver from: c:\Users\me\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js
2024-03-01 11:46:40.819 [info] <syntax> Forking...
2024-03-01 11:46:40.819 [info] <syntax> Starting...
2024-03-01 11:46:40.819 [info] <semantic> Forking...
2024-03-01 11:46:40.819 [info] <semantic> Starting...
```

Version: 1.87.0 (user setup)
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:41:44.469Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Open copilot chat panel. 
2. Ask a question. 
3. Observe Copilot's code being linted by typescript and appearing as errors in the problem panel.

**Comment by joansam** [comment]
I'm having the same issue!

**Comment by Chris3918** [comment]
same issue suddenly occurring for me as well

**Comment by armandtht** [comment]
same!

**Comment by aiday-mar** [comment]
HI thank you for posting this issue. I believe this is as designed. Copilot just inserts code into the editor, and it continues behaving as before, that is it continues to analyze the code in search for compiler error. Let me know if you meant something else.

**Comment by aiday-mar** [comment]
Hi, I am not quite sure I understand fully. Could you include a GIF showing the error, so we can have a visual representation of what is happening? Following this, I will route the issue to the appropriate person.

**Comment by armandtht** [comment]
Hello @aiday-mar, 

After the latest update of VSCode, the TypeScript error checks seem to be scanning not just my project files but also the code snippets in Copilot's chat window. This results in some odd errors popping up in the problems window, like references to "resource": "6dcd1caf-c6e3-4804-90ad-57c8dca5cbb9", which are from the Copilot chat.

It's a bit confusing because it mixes up actual project errors with these irrelevant ones. Hope this can be looked into. 

Please check the demo video below
https://github.com/microsoft/vscode-copilot-release/assets/136462994/287b5ace-2e9e-4f68-898b-07961285983a

Thanks!

**Comment by pmwangi** [comment]
I'm having the same problem, suddenly occurred for me as well this past week

**Comment by pmwangi** [comment]
> I see thank you for the clarification. @mjbvz is this issue a duplicate of [microsoft/vscode#206644](https://github.com/microsoft/vscode/issues/206644)?

I'm having the same problem, suddenly occurred for me as well this past week, I don't believe these are related

**Comment by armandtht** [comment]
Hi @aiday-mar, 

Any news?

**Comment by jpshackelford** [comment]
Confirmed this with additional details here:   https://github.com/orgs/community/discussions/112621
