### ISSUE TITLE
Categorizing chat history

### ISSUE THREAD

**Issue by eschindev** [microsoft/vscode-copilot-release#99]
Currently, it seems like there is one perpetually continuous chat conversation that lacks any sort of organization or ability to revisit particular topics.

It would be great to be able to file a given conversation away for later reference and continuation. I'm envisioning a "file system" where you can create nested folders for custom categorization of chats, which can be saved to any directory in this system. This would allow you to categorize conversations by project / related technologies / date / whatever else the user wants.

**Comment by BernardDoherty** [comment]
Yes, I will second that. Currently, on the ChatGPT website, having the history saved in individual chats is invaluable. I keep the history and can quickly jump to a specific chat that was related to a feature I was asking questions about. Not having this feature here would probably make me continue to use ChatGPT website instead.

**Comment by roblourens** [comment]
We now have chat history too- there is a new button in the view toolbar to see your past chat sessions
