### ISSUE TITLE
500 Internal Server Error / error getting copilot user details

### ISSUE THREAD

**Issue by binaryfire** [microsoft/vscode-copilot-release#990]
Have been getting these quite frequently today:

<img width="212" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5361908/2f2b8902-2ce9-4584-bafb-8ac4bebf0b29">
<img width="304" alt="image" src="https://github.com/microsoft/vscode-copilot-release/assets/5361908/f67987fd-90e6-4537-b045-2f848d86e596">

**Comment by lramos15** [comment]
There was a service incident. Please let us know if you're still receiving these

**Comment by guymercier** [comment]
I also received this error message "unhandled status from server: 400 Bad Request... and now 500 internal Server Error... is IA first sign it is taking over the world : ---(

**Comment by Castor93** [comment]
I also received this error message "unhandled status from server: 400 Bad Request... and now 500 internal Server Error... is IA first sign it is taking over the world : ---( [2]

**Comment by YkTru** [comment]
> I also got this error message "unhandled status from server: 400 Bad Request... and now 500 internal Server Error... this is the first sign from AI that it's taking over the world : ---(

Yes, there seems to be a strike; their union is criticizing the fact that they work 24/7.

**Comment by LuisCardeBu** [comment]
![image](https://github.com/user-attachments/assets/4e4b61b5-6da6-4ce0-9386-74865033deb8)

**Comment by MohamadSamra** [comment]
I am also having the same error 

![image](https://github.com/user-attachments/assets/82ae3f39-4e4e-41fc-a0ef-ab49edb00a0f)

**Comment by 10807903-RayYeh** [comment]
I am also having the same error 
![image](https://github.com/user-attachments/assets/8f26bbc6-81eb-42bb-9184-31832627ca71)

**Comment by joezchan** [comment]
I'm still getting the same error. Wonder if the problem been resolved yet.

**Comment by 976077663** [comment]
I thought it was just my own problem.

**Comment by enganese** [comment]
Still getting the 500/400 errors!
![image](https://github.com/user-attachments/assets/f367405f-f7b9-4f29-909f-369b5baf8164)
![image](https://github.com/user-attachments/assets/cdc8e555-3935-4d9f-9792-3e045dd01cba)

**Comment by mypark-virnect** [comment]
same issue here!
![image](https://github.com/user-attachments/assets/ac8270ff-6ad3-472b-973a-6f6c00ea1d8e)

**Comment by gitxulang** [comment]
same error

**Comment by JoaGabri** [comment]
prob copilot service down, same problem here

**Comment by NantipatSoftEn** [comment]
I also same  error , not sure what happen.

**Comment by XiaoMingMingBai** [comment]
me too

**Comment by AiprNick** [comment]
wired..
It shows the service is OK. https://www.githubstatus.com/
But, I'm suffering the bad situation on both IDE and mobile.
![image](https://github.com/user-attachments/assets/f410630e-ae82-4368-8aa2-d5a70eedf108)
![image](https://github.com/user-attachments/assets/ca3a1a10-f68c-4405-ba05-c92ddc032d8f)

**Comment by Herbert77** [comment]
me too..
