### ISSUE TITLE
Oops, your response got filtered. Vote down if you think this shouldn't have happened.

### ISSUE THREAD

**Issue by LorenzoValente3** [microsoft/vscode-copilot-release#992]
- VS Code Version: August 2023 (version 1.82)
- OS Version: Version 14.1.2 (23B92)
- Logs:

Steps to Reproduce:

1. Just open my chat on VS code
2.

**Comment by lramos15** [comment]
Please include your logs.

`CTRL / CMD + SHIFT + U` -> `GitHub Copilot Chat`

**Comment by RaphaelKalfonEngie** [comment]
Same problem, copilot will filter any prompt with the same message. Logs:
![image](https://github.com/microsoft/vscode-copilot-release/assets/159459641/d9b85139-5378-45b5-bacb-89a2ee9b2dff)

**Comment by lramos15** [comment]
@RaphaelKalfonEngie Those logs are from a much older version can you try on the latest version of Copilot Chat. Thanks!
