### ISSUE TITLE
CP Chat can't see any code

### ISSUE THREAD

**Issue by Kevpedia** [microsoft/vscode-copilot-release#998]
Type: <b>Bug</b>

GH Copilot Chat doesn't seem to be able to see my code in this workspace. I was using it earlier today on another workspace without a problem.

Steps:
1. open workspace
2. select code
3. open chat
4. type '@workspace / explain' and hit enter
5. CP shows "Used 1 reference: main.ts:1-638"
6. CP responds "I'm sorry, but there seems to be a misunderstanding. I can't see any code in your message. Could you please provide the code you want me to explain?"

- this is a TS file, just like the other workspace that works
- the selected file is not in .gitignore nor in .copilotignore

Extension version: 0.13.0
VS Code version: Code 1.87.0 (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:51.279Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id e4cf1f20-48ac-4d23-8cff-ed9de6772c2b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
cppperfcontrol:30979541
d34g3935:30971562
edj9j583:30969295
a89i1917:30973842
dsvsc020:30976470

```

</details>

**Comment by mjbvz** [comment]
Seems to work for me. Please share a project and specific selection  in it that causes this to happen

**Comment by Kevpedia** [comment]
Works for me now too 🤷

**Comment by Kevpedia** [comment]
I do think that's it. I've encountered it again once or twice now and it
has always been with really large selections/files. Probably just exceeds
the token limit for GPT or something.
